### ISSUE TITLE
Calc error in COORDINATE:Get2DDistance(TargetCoordinate) ?

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#1004]
Calc error in COORDINATE:Get2DDistance(TargetCoordinate) ?
Open
@jspencer46 opened this Issue on 26 May · 0 comments

COORDINATE:Get2DDistance(TargetCoordinate) appears to return a distance about 3X the distance observed in a mission. Following code Sends message at 7 miles, where 2 miles is expected:

AtkDist12 = AtkCoord2:Get2DDistance( BmbrCoord )
   if AtkDist12 < 4000 then
        MESSAGE:New( "Test Message.", 15 ):ToAll() 
   end

**Comment by funkyfranky** [comment]
I am using Get2DDistance() all the time and it works correctly. Also the equation used in the function is correct.

**Comment by FlightControl-User** [comment]
I am closing this.
