### ISSUE TITLE
Error AI_A2A_Patrol - GetRandomePointVec2 (a nil Value)

### ISSUE THREAD

**Issue by falcon76** [FlightControl-Master/MOOSE#1008]
I am getting this error when running the ai Patrol in my mission. I will post the at bottom my code: 

2018-09-30 17:21:38.648 INFO    Scripting: event:type=takeoff,initiator=RU CAP SU27#002-01,place=Krasnodar-Pashkovsky,t=18497.61,placeDisplayName=Krasnodar-Pashkovsky,initiatorMissionID=1000003,
2018-09-30 17:21:41.848 INFO    SCRIPTING: Error in SCHEDULER function:[string "Scripts/Moose/AI/AI_A2A_Patrol.lua"]:323: attempt to call method 'GetRandomPointVec2' (a nil value)
2018-09-30 17:21:41.848 INFO    SCRIPTING: stack traceback:
	[string "Scripts/Moose/Core/Fsm.lua"]:912: in function 'GetRandomPointVec2'
	[string "Scripts/Moose/AI/AI_A2A_Patrol.lua"]:323: in function <[string "Scripts/Moose/AI/AI_A2A_Patrol.lua"]:305>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "Scripts/Moose/Core/Fsm.lua"]:921: in function '_call_handler'
	[string "Scripts/Moose/Core/Fsm.lua"]:682: in function <[string "Scripts/Moose/Core/Fsm.lua"]:592>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "Scripts/Moose/Core/ScheduleDispatcher.lua"]:131: in function <[string "Scripts/Moose/Core/ScheduleDispatcher.lua"]:90>

    
    PatrolZoneGroup1 = GROUP:FindByName( "RU Zone Patrol A" )
    PatrolZone1 = ZONE_POLYGON:New( "RU Zone Patrol A", PatrolZoneGroup1 )
    
    PatrolZoneGroup2 = GROUP:FindByName( "RU Zone Patrol B" )
    PatrolZone2 = ZONE_POLYGON:New( "RU Zone Patrol B", PatrolZoneGroup2 )   
  SCHEDULER:New(nil, 
  function()
  --RUS EWR System
    RUAADetectionSetGroup = SET_GROUP:New()
    RUAADetectionSetGroup:FilterPrefixes( "RUS-EWR" )
                         :FilterCoalitions("red")
                         :FilterActive(Active)
    RUAADetectionSetGroup:FilterOnce()
           
    RUAADetection = DETECTION_AREAS:New( RUAADetectionSetGroup, 100 )
          RUAADetection:FilterCategories( Unit.Category.AIRPLANE )
          RUAADetection:SetFriendliesRange( 10000 )
          RUAADetection:SetRefreshTimeInterval( 130 )
          RUAADetection:Start(-5)
  -- Setup the A2A dispatcher, and initialize it.
    RUA2ADispatcher = AI_A2A_DISPATCHER:New( RUAADetection ) 
    -- Initialize the dispatcher, setting up a radius of 100km where any airborne friendly 
    -- without an assignment within 100km radius from a detected target, will engage that target.
    RUA2ADispatcher:SetEngageRadius( 100000 )     
    RUA2ADispatcher:SetGciRadius( 150000 )
    RUA2ADispatcher:SetIntercept(50)
    RUA2ADispatcher:SetDisengageRadius(300000)
    RUA2ADispatcher:SetTacticalDisplay( false )
    RUA2ADispatcher:SetRefreshTimeInterval(120)
    RUA2ADispatcher:SetDefaultCapLimit(2)
  --RUS Air defense Templates 
    local RUAATemplates = {
        "RU CAP MIG29A",
        "RU CAP SU27",
        "RU CAP SU33",
        "RU CAP MIG29S",
        "RU CAP SU30",
        "RU CAP MIG31",
        "RU CAP M2000C",
        "RU CAP F5E"
        }
   -- RUA2ADispatcher:SetSquadron( "Beslan1", AIRBASE.Caucasus.Beslan, RUAATemplates, 120 )
   -- RUA2ADispatcher:SetSquadronGci( "Beslan1", 600, 800 )

    RUA2ADispatcher:SetSquadron( "Anapa1", AIRBASE.Caucasus.Anapa_Vityazevo, RUAATemplates, 120 )
    RUA2ADispatcher:SetSquadronGci( "Anapa1", 600, 800 )
    RUA2ADispatcher:SetSquadronCap("Anapal",PatrolZoneGroup1,3000,10000,200,600,200,800,"RADIO")
    
    RUA2ADispatcher:SetSquadron( "Novo1", AIRBASE.Caucasus.Novorossiysk, RUAATemplates, 120 )
    RUA2ADispatcher:SetSquadronGci( "Novo1", 600, 800 )
    RUA2ADispatcher:SetSquadronCap("Novo1",PatrolZoneGroup1,3000,10000,200,600,200,800,"RADIO")
    
    RUA2ADispatcher:SetSquadron( "Kras1", AIRBASE.Caucasus.Krasnodar_Pashkovsky, RUAATemplates, 120 )
    RUA2ADispatcher:SetSquadronGci( "Kras1", 600, 800 )
    RUA2ADispatcher:SetSquadronCap("Kras1",PatrolZoneGroup1,3000,10000,200,600,200,800,"RADIO")
    
    RUA2ADispatcher:SetSquadron( "KrasC1", AIRBASE.Caucasus.Krasnodar_Center, RUAATemplates, 120 )
    RUA2ADispatcher:SetSquadronGci( "KrasC1", 600, 800 )
    RUA2ADispatcher:SetSquadronCap("KrasC1",PatrolZoneGroup1,3000,10000,200,600,200,800,"RADIO")
    
    RUA2ADispatcher:SetSquadron( "Maykop", AIRBASE.Caucasus.Maykop_Khanskaya, RUAATemplates, 120 )
    RUA2ADispatcher:SetSquadronGci( "Maykop", 600, 800 )
    RUA2ADispatcher:SetSquadronCap("Maykop",PatrolZoneGroup1,3000,10000,200,600,200,800,"RADIO")
    
    RUA2ADispatcher:SetSquadron( "Krymsk1", AIRBASE.Caucasus.Krymsk, RUAATemplates, 120 )
    RUA2ADispatcher:SetSquadronGci( "Krymsk1", 600, 800 )
    RUA2ADispatcher:SetSquadronCap("Krymsk1",PatrolZoneGroup1,3000,10000,200,600,200,800,"RADIO")
    
    --RUA2ADispatcher:SetSquadron( "Nalchik", AIRBASE.Caucasus.Nalchik, RUAATemplates, 120 )
    --RUA2ADispatcher:SetSquadronGci( "Nalchik", 600, 800 )
    
    RUA2ADispatcher:SetSquadron( "Vody", AIRBASE.Caucasus.Mineralnye_Vody, RUAATemplates, 120 )
    RUA2ADispatcher:SetSquadronGci( "Vody", 600, 800 )
    RUA2ADispatcher:SetSquadronCap("Vody",PatrolZoneGroup2,3000,10000,200,600,200,800,"RADIO")
    
    RUA2ADispatcher:SetSquadron( "Mozdok", AIRBASE.Caucasus.Mozdok, RUAATemplates, 120 )
    RUA2ADispatcher:SetSquadronGci( "Mozdok", 600, 800 )
    RUA2ADispatcher:SetSquadronCap("Mozdok",PatrolZoneGroup2,3000,10000,200,600,200,800,"RADIO")
       
    RUA2ADispatcher:SetDefaultTakeoffFromParkingHot()
    RUA2ADispatcher:SetDefaultLandingAtEngineShutdown()
  
   end, {}, 12, 0, 0, 2)

let me know If there is anything else you need.

thanks 

Falcon

**Comment by Delta-99** [comment]
This line in your script looks incorrect: 

`:FilterActive(Active)`

unless you have Active as a variable defined and set to a boolean value of true or false. Please correct and report back here if this is still an issue.

**Comment by FlightControl-User** [comment]
@falcon76 is this still an issue?
Closing, but if it is still an issue, please post the mission so i can resimulate this.
