### ISSUE TITLE
SPAWN template from an external file

### ISSUE THREAD

**Issue by Prof-hilactic** [FlightControl-Master/MOOSE#101]
in DCS\MissionEditor there is a templates.lua file which contain all the templates created in the mission editor.
It would be useful to some of us if the Spawn_Templates_Visible could look into this file to extract potential templates.

**Comment by FlightControl-Master** [comment]
Is this urgent?

**Comment by Grey-Echo** [comment]
@Prof-hilactic hasn't been active for a long while, but maybe this feature might be useful to other mission designers.

**Comment by FlightControl-Master** [comment]
Low low priority

**Comment by FlightControl-Master** [comment]
Not needed. Closed.
