### ISSUE TITLE
possible bug in SET_GROUP

### ISSUE THREAD

**Issue by snakesn** [FlightControl-Master/MOOSE#1013]
please check this version: https://github.com/FlightControl-Master/MOOSE_INCLUDE/tree/develop/Moose_Include_Static

has a bug can't call FN_Create_Menu fucntion due to "attempt to index field '?' (a nil value)" issue 

**NOTE: works in 2.3 master version**

Set_Active_Clinet_Groups = SET_GROUP:New():FilterCoalitions("red"):FilterCategories("plane"):FilterStart()
function FN_Refresh_Clinet()
    Set_Active_Clinet_Groups:ForEachGroup(
        function(Current_Client_Name)
            FN_Create_Menu(Current_Client_Name)
        end)
end

Error details:
2018-10-04 06:14:32.579 INFO    SCRIPTING: Error in timer function: [string "C:\Users\alexs\AppData\Local\Temp\DCS.HD\/~mis00000805"]:7351: attempt to index field '?' (a nil value)
2018-10-04 06:14:32.579 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\alexs\AppData\Local\Temp\DCS.HD\/~mis00000805"]:5061: in function <[string "C:\Users\alexs\AppData\Local\Temp\DCS.HD\/~mis00000805"]:5058>
	[string "C:\Users\alexs\AppData\Local\Temp\DCS.HD\/~mis00000805"]:7351: in function 'SetGroupMenu'
	[string "C:\Users\alexs\AppData\Local\Temp\DCS.HD\/~mis00000805"]:8060: in function 'New'
	[string "C:\Users\alexs\AppData\Local\Temp\DCS.HD\/~mis00002D97"]:93: in function 'FN_Create_Tanker_Menu'
	[string "C:\Users\alexs\AppData\Local\Temp\DCS.HD\/~mis00002D97"]:110: in function 'IteratorFunction'
	[string "C:\Users\alexs\AppData\Local\Temp\DCS.HD\/~mis00000805"]:12083: in function 'co'
	[string "C:\Users\alexs\AppData\Local\Temp\DCS.HD\/~mis00000805"]:12099: in function 'Schedule'
	[string "C:\Users\alexs\AppData\Local\Temp\DCS.HD\/~mis00000805"]:12113: in function 'ForEach'
	[string "C:\Users\alexs\AppData\Local\Temp\DCS.HD\/~mis00000805"]:12676: in function 'ForEachGroup'
	[string "C:\Users\alexs\AppData\Local\Temp\DCS.HD\/~mis00002D97"]:108: in function 'FN_Refresh_Clinet'
	[string "C:\Users\alexs\AppData\Local\Temp\DCS.HD\/~mis00002D97"]:117: in function <[string "C:\Users\alexs\AppData\Local\Temp\DCS.HD\/~mis00002D97"]:116>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\alexs\AppData\Local\Temp\DCS.HD\/~mis00000805"]:5101: in function <[string "C:\Users\alexs\AppData\Local\Temp\DCS.HD\/~mis00000805"]:5055>

**Comment by shadowze** [comment]
It is a known bug in the FilterCategories()  method which is yet unfixed
I just edit my moose.lua to work around it to stop the error

**Comment by Delta-99** [comment]
What is on line 116-117 in your script. Looks to me more like an error in your function.

**Comment by FlightControl-User** [comment]
@snakesn which moose version you use?

**Comment by thebgpikester** [comment]
Thank you for your report. As you can see from the age of the report the ticket is open with no updates for a very long time. In 14 Nov 2018 the last commit to Moose 2.4 stable was made on the live branch. Since then the de facto live build has been the DEV branch which is the only one we can use for updates. This is because Flight control has stopped work on MOOSE and only, he has the permissions to release new branches, all work is on DEV branch. Your ticket predates thousands of lines of code change and has to be reproduced on a moose version that is on DEV in order to be able to be assessed.
