### ISSUE TITLE
Carrier left Behind when cargo and carriers are spawned.

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#1016]
when using AI_Dispatcher_APC if you spawn both cargo and carriers, 1 carrier never picks up the cargo no matter how you change the spawn count. 

Using this code
local DogGreenBeach = GROUP:FindByName( "Dog Green Beach" )
local DogGreenBeachZone = ZONE_POLYGON:New( "Dog Green Beach", DogGreenBeach )
 
 local CargoInfantrySet = SET_CARGO:New():FilterTypes( "USMCINF" ):FilterStart()
local SetAPC = SET_GROUP:New():FilterPrefixes( "USMCCarrier" ):FilterStart()
--local PickupZonesSet = SET_ZONE:New():FilterPrefixes( "Pickupp" ):FilterOnce()
local DeployZonesSet = SET_ZONE:New():FilterPrefixes( "Beachhead" ):FilterOnce()
AICargoDispatcherAPC = AI_CARGO_DISPATCHER_APC:New( SetAPC, CargoInfantrySet, nil, 

DeployZonesSet ) 
AICargoDispatcherAPC:SetDeploySpeed(70)
AICargoDispatcherAPC:SetPickupSpeed(70)
AICargoDispatcherAPC:Start()
 
 SpawnInfantry = SPAWN:New( "Marine3" )
    :InitLimit( 50, 8 )
    --:InitRandomizePosition(true,500,100)
    :InitRandomizeZones( {DogGreenBeachZone} )
    :OnSpawnGroup( 
      function( SpawnGroup )
       CARGO_GROUP:New(SpawnGroup,"USMCINF",SpawnGroup:GetName(),150,10)
      end
      )
    :SpawnScheduled( .01, .02 )

    SpawnInfantry = SPAWN:New( "USMCCarrier" )
    :InitLimit( 5, 6 )
    --:InitRandomizePosition(true,500,100)
    :InitRandomizeZones( {DogGreenBeachZone} )
    :InitKeepUnitNames()
    :SpawnScheduled( .01, .02 ) 

Ive changed the initlimit all sorts of ways and always one carrier gets left behind.

**Comment by FlightControl-User** [comment]
fixed.
