### ISSUE TITLE
request: Spawn units with AI off

### ISSUE THREAD

**Issue by 132nd-Entropy** [FlightControl-Master/MOOSE#102]
Add an initialization to SPAWN in order to spawn units with AI off.

**Comment by FlightControl-Master** [comment]
Working on that... Building class to deactivate ground troops with no enemy near...

**Comment by FlightControl-Master** [comment]
Entropy, You remember the context?

**Comment by entropySG** [comment]
hi Sven, context was to save CPU resources on the server on very complex missions. So unit AI will only be activated when needed (e.g. when a player aircraft approaches a zone)

**Comment by FlightControl-Master** [comment]
Ok. Will look into that... But! Units with ai off won't move!

**Comment by FlightControl-Master** [comment]
Would it be meaningful that we monitor if a client is near x km from a group of units, those units get activated?

**Comment by FlightControl-Master** [comment]
How would you see this working? Zones maybe?

**Comment by afinegan** [comment]
This could free up needed resources from scanning units. Since I run a full map of spawned units, I think this is greatly needed, just some units (the moving ones) would need to be skipped (maybe the name of the moving units can unfilter them. Right now the main issue I am having is the f10 map lagging horribly due to to many units being shown on it, I don't think I can do much about that (aside from not showing them on the map, but then people wont know where the battle is.....(atm they compare between bases that have units and ones that don't to figure this out since the the entire map is capturable, and the front can be in any direction))

**Comment by FlightControl-Master** [comment]
Ok. I think about 2 things here, short and long term.

* Short Term: New option methods added to the SPAWN class. There ate two ways to do that:
1. to spawn with AI off or switch AI back on. SPAWN:InitAIOn( #Boolean ). 
2.Make 2 methods with SPAWN:InitAIOff() and SPAWN:InitAIOn.().

* Long term... We'll talk about that on slack... Entropy, afinegan, ...

**Comment by Delta-99** [comment]
Typically this is done in other games (like Arma) where units are "cached" and not spawned or de spawned based on whether they are close enough to "human" players or other "AI" from a none friendly side. This way it saves on resources. In some other caching algorithms, only the leader of a group is spawned (at all times). And all others are despawned and only spawned when there is a unit from a none friendly side "close" enough.

I would call it "caching" or something along those lines. And it has to be optional. You don't always want this happening on all units. Only in very complex missions and even then only if run on servers that can't handle that number of AI.

I would think this would also add a massive amount of complexity to your system FC so I'm not sure the investment of time and the possibility of introducing bugs is worth it.

Are we sure this is even a problem?

**Comment by afinegan** [comment]
In DCS, the algorithm for handing AI is not good at all, DCS cant handle many AI, more than 40-50 moving and shooting and the server is lagging horribly, even static are scanning. I wish DCS would spend some time optimizing it. If you jump on multiplayer, look for -=16AGR=- US East Dynamic Caucasus, my map does indeed need something like this to allow me to make the mission a lot more alive and enjoyable (I think its pretty amazing what I have working atm though lol, TY flightcontrol and friends!) - we can discuss on slack

**Comment by FlightControl-Master** [comment]
Yup. Lets work out a solution :-) have an idea, complicated but very performant and sufficiently accurate.

**Comment by 132nd-Entropy** [comment]
very nice!

**Comment by FlightControl-Master** [comment]
Implemented with merge #215 . Check out test mission SPA-017.

New methods added on GROUP level. AI is turned on or off on group level, and only on group level.
SPAWN has added methods InitAI..., which use internally those GROUP level methods to control the AI.

This is a piece of example code, how to use (extract from SPA-017):

```lua
ZoneTable = { ZONE:New( "Zone1" ), ZONE:New( "Zone2" ) }

Spawn_Vehicle_1 = SPAWN:New( "Spawn Vehicle 1" )
  :InitLimit( 10, 10 )
  :InitRandomizeRoute( 1, 1, 200 ) 
  :InitRandomizeZones( ZoneTable )
  :InitAIOnOff( false ) -- This will disable the AI. You can also use :InitAIOff(). Set AI On (for those groups with AI Off in the ME), with :InitAIOn().
  :SpawnScheduled( 5, .5 )
```

-- Added SPA-017 test mission
-- Added SPAWN:InitAIOnOff()
-- Added SPAWN:InitAIOn()
-- Added SPAWN:InitAIOff()
-- Added GROUP:SetAIOnOff( AIOnOff )
-- Added GROUP:SetAIOn()
-- Added GROUP:SetAIOff()
-- Documentation

**Comment by Grey-Echo** [comment]
Since nobody commented for 2 months, I guess this feature is bugfree ! I'm going to go ahead and close this issue. If you find a bug in the feature, please open a new issue !

**Comment by FlightControl-Master** [comment]
Yup. This is done.
