### ISSUE TITLE
CARGO_GROUP: name parameter must be unique!

### ISSUE THREAD

**Issue by funkyfranky** [FlightControl-Master/MOOSE#1020]
A code like
```
local groupA=GROUP:FindByName("Infantry Alpha")
local groupB=GROUP:FindByName("Infantry Bravo")

local cargoA=CARGO_GROUP:New(groupA, "Infantry", "Some Name")
local cargoB=CARGO_GROUP:New(groupB, "Infantry", "Some Name")
```
causes **big** trouble since the respawned groups will have **identical names**, i.e. both get the name "Some Name#CARGO". This confuses the MOOSE database and probably DCS as well.

It should at least be **highlighted in the docs**, that the name of the cargo group **must be unique** and it should be checked that this name does not already exist in the DB.

**Comment by Kalbuth** [comment]
Or an Id could be added to spawned group name?

**Comment by FlightControl-User** [comment]
OK. I understand, I thought is was obvious but it seems it is not. I will update the documentation. All names of objects should be unique.

**Comment by FlightControl-User** [comment]
@funkyfranky is it a structural problem, this? I mean, for warehouse?

**Comment by FlightControl-User** [comment]
What I can do is to check first if a cargo with the same name is already existing, and if yes, then return an error message.
I always provide a cargo name which is equal to the group name. I could even add a method names NewFromGroup( ... ) ...

**Comment by Delta-99** [comment]
I think Id’s are already added but probably not tracked across spawns so still something needs to be worked out

**Comment by funkyfranky** [comment]
No structural problem. Just saw users running into issues and me too at some point :) For now, just update the docs a bit as this is the plan anyways and maybe generate an error if the group with that name is already alive.
