### ISSUE TITLE
Unarmed units are set to give 0 points?

### ISSUE THREAD

**Issue by Enfarda** [FlightControl-Master/MOOSE#1023]
![unarmed units dont give points](https://user-images.githubusercontent.com/43972918/46635713-3fe9b000-cb4d-11e8-9665-c8717f7daa71.PNG)

is a bug or is defined like this?

**Comment by FlightControl-User** [comment]
Was the plane armed?

**Comment by FlightControl-User** [comment]
@Enfarda can you please answer this question? It is normal that 0 points are given when it is a static.

**Comment by FlightControl-User** [comment]
I will close this issue and if you think it is a problem, please revert with more details.
