### ISSUE TITLE
COORDINATE:ToStringBR Suspected Doc Error

### ISSUE THREAD

**Issue by jspencer46** [FlightControl-Master/MOOSE#1024]
Document method description for `COORDINATE:ToStringBR` appears to demand 3 parameters where only 2 should be required. `COORDINATE:ToStringBRA` appears to have same error.

**Comment by FlightControl-User** [comment]
Ok. Mistake with the documentation. Will correct it but I think I already did...

**Comment by Delta-99** [comment]
@FlightControl-User If you followed the thread of discussion on Discord I pointed out that there is something very strange with this regarding the documentation. The docs don't seem to match what I am seeing in the source code. So, I think you probably did fix this a long time ago but for some reason the docs are not being generated properly for this. Not sure how wide spread this is. So this might be a larger issue or something very odd with this particular method for some reason. Maybe there is something odd in the comments breaking the documentation generation in this case.

**Comment by FlightControl-User** [comment]
Fixed. Closing.
