### ISSUE TITLE
AI_A2A_DISPATCHER: CAP will not disengage when target crosses to friendly side of border

### ISSUE THREAD

**Issue by whartsell** [FlightControl-Master/MOOSE#1026]
If you have a squadron with a border designated, once the attacker crosses the border to the defenders side he is targeted and the cap will move to engage it.  If the attacker crosses back to his side of the border the target is removed in the debug window but the cap still has orders to engage it.  The CAP will cross the border and engage it.  This is with version 2.3.  I cannot test with 2.4 or 2.4.1 as there is a different issue keeping the cap from taking off that i haven't troubleshot yet
Here is my mission.lua.  I can provide an example mission if needed

**Comment by whartsell** [comment]
`-- adding our EWR and SAM groups to the detection group
DetectionSetGroup = SET_GROUP:New()
DetectionSetGroup:FilterPrefixes({"EWR Red", "SAM Red"})
DetectionSetGroup:_FilterStart()

-- want to detect multiple aircraft within 5nm as a single group
Detection = DETECTION_AREAS:New(DetectionSetGroup,9260)

Red_A2ADDispatcher = AI_A2A_DISPATCHER:New(Detection)

-- enable the tactical display for debugging
Red_A2ADDispatcher:SetTacticalDisplay( true )

-- Iran's border zone
Red_BorderZone = ZONE_POLYGON:NewFromGroupName("Red Border",GROUP:FindByName("Red Border"))



-- Dispatcher setup
-- border
Red_A2ADDispatcher:SetBorderZone(Red_BorderZone)

-- Engagement
Red_A2ADDispatcher:SetEngageRadius(92600) -- 50nm engagement zone

--Squadrons
Red_A2ADDispatcher:SetSquadron("Bandar AbbasSQ","Bandar Abbas Intl",{"Red Squadron F4"},4)
Red_A2ADDispatcher:SetSquadronOverhead("Bandar AbbasSQ",1)
Red_A2ADDispatcher:SetSquadronGrouping("Bandar AbbasSQ",2)
Red_A2ADDispatcher:SetSquadronTakeoffFromRunway("Bandar AbbasSQ")
Red_A2ADDispatcher:SetSquadronLandingAtRunway("Bandar AbbasSQ")
CAPZoneBA = ZONE_POLYGON:NewFromGroupName("BandarAbbasCAP",GROUP:FindByName("BandarAbbasCAP"))
Red_A2ADDispatcher:SetSquadronCap("Bandar AbbasSQ",CAPZoneBA,7620,7620,750,950,950,1800,"BARO")
Red_A2ADDispatcher:SetSquadronCapInterval("Bandar AbbasSQ",1,300,600,1)`

**Comment by FlightControl-User** [comment]
@whartsell this was specifically fixed in 2.4. I remember very well. Yes, this problem was in 2.3. and I fixed that. There are more things wrong with 2.3, like refuel, and fuel treshold etc.
However, the issue #1027 regarding takeoff from runway needs to be fixed and looked at first I think.

**Comment by whartsell** [comment]
Not sure if you saw my comment in #1027, but we did test this with air start and they still diddnt disengage in 2.4.0,2.4.1,and 2.4.2

**Comment by FlightControl-User** [comment]
I'll check. OK if i do this next week? Let's say tuesday? @whartsell

**Comment by thebgpikester** [comment]
We had this raised and duplicated. SOmetimes they can still do this behaviour, but the likeliehood is far reduced now. Archiving this ticket.
