### ISSUE TITLE
AI_A2A_DISPATCHER: when SetSquadronTakeoffFromRunway is used CAP will not takeoff

### ISSUE THREAD

**Issue by whartsell** [FlightControl-Master/MOOSE#1027]
this happens in 2.4.0 and 2.4.1 NOT in 2.3.1.

when using SetSquadronTakeoffFromRunway at bandar abbas intl the jet spawns at the end of the runway facing the approach end of the runway and not the departure end of the runway "backwards" . It will just sit there and not takeoff.

**Comment by whartsell** [comment]
an important point in reproducing this is you have to host a MP server session for it to happen.  If you just start the mission from the ME or any other way other than through the "server" dialogue it works fine

**Comment by FlightControl-User** [comment]
ok, while having this issue, can you then maybe just start from the air??? and test the other error reported, using 2.4.1? The start from runway is a very very very nasty thing in dcs ...
I won't patch this as this will require some severe testing in the core if i fix this one of all the other modules, like AI_BALANCER etc.

**Comment by FlightControl-User** [comment]
If you can change the start mode, and just test #1026 in 2.4.2, that would be very helpful.
Thank you.

**Comment by whartsell** [comment]
We tried it earlier with the air start in 2.4.2 and they still won’t disengage

**Comment by thebgpikester** [comment]
Runway takeoffs are and have been broojken in MP for years now. Archiving this.
