### ISSUE TITLE
cargo not reloading into carrier after engagement with nme

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#1028]
Cargo units are not reloading into their carriers after an engagement with the nme is completed. 
If a carrier that is loaded with cargo comes within a specified range of an enemy unit, the cargo normally unloads, and follows the carrier as they engage the enemy unit. Once the enemy is eliminated the cargo used to reembark back into the carrier and the carrier would go on its way to its destination.

Now the Cargo will unload from the carrier, the carrier and cargo do not move forward to engage the enemy but will fire upon it. Once the enemy is eliminated the cargo does NOT re-embark back into the carrier. It just stays in place and does not move. Once this happens the carrier and cargo no longer move anywhere.

**Comment by FlightControl-User** [comment]
Ok. Clear.  I'll check next week what is the issue. Pm me your  mission to resimulate.

**Comment by FlightControl-User** [comment]
Gunterlund, we worked on this together. closing this issue.
