### ISSUE TITLE
UH-1H used with AI_CARGO_DISPATCHER_HELICOPTER never loads?

### ISSUE THREAD

**Issue by cjbehm** [FlightControl-Master/MOOSE#1034]
Spent a lot of time trying to figure out what I was doing wrong, since I was essentially just testing/copying the code from 'AID-CGO-200 - Helicopter - Pickup and Deploy.lua'.

I was using a UH-1H for my testing (ME task type set as Transport and tried as Nothing), and the helo would move to the home zone and land (not to the troops intended for pickup). Tried various other combinations, like setting fuel to 50% in case it was rejecting it as a transport due to lift capacity and unchecking External Hardpoints.

When I changed the transport to a Chinook or UH-60A, it all worked exactly as expected.

**Comment by Delta-99** [comment]
Yeah, attach .miz or make it available somewhere. Not sure what attachment options exist here. Maybe it can’t be attached. Usually with something like this it turns out to be a slight mismatched naming issue. But could be a legit bug.

**Comment by cjbehm** [comment]
Hopefully you can download from this link [https://www.dropbox.com/s/3p1jhnwg3ljd06a/Bird%20Dog.miz?dl=0](url) -- it's configured as a UH-1H to start with and it will land at the home zone, but from the ME if I changed the unit from UH-1H to UH-60A then it lands and picks up the infantry.

**Comment by cjbehm** [comment]
Also, I initially ran into the problem using when running from git commit 08c3530da9b4d7e0970b0fc5d329769b90b13c01 from Oct 14 as well as just updating now to 7de9fded562ab73c3bb2e9d8d662e047eb3d23ba from Oct 19

I haven't tried with a specifically released version.

**Comment by FlightControl-User** [comment]
Doubtable. Please report with mission to resimulate.

**Comment by cjbehm** [comment]
Did you see my the Dropbox link? That has a mission that should be illustrating the problem.

**Comment by FlightControl-User** [comment]
ohh. ok. I'll check this next week, ok?
Tuesday probably.

**Comment by FlightControl-User** [comment]
however, can you please retest with the latest version? and please check if the UH-1H picks up cargo. I remember myself testing very well with this helo. some important fixes have been done the past weeks. Pls check with patch 2.4.7.

**Comment by cjbehm** [comment]
Same behavior with 2.4.7 (git commit *** MOOSE GITHUB Commit Hash ID: 2018-10-21T11:35:09.0000000Z-fca5a0f5295f99cb7f6f90b123707e6c06bdc3dd ***)

I ended up adding some output lines in onafterDeploy and onafterPickup in AI_Cargo_Helicopter. In the mission I linked, they don't appear to be getting called when the unit is UH-1H. When I change it to UH-60A, they are called.

Nothing's logging an error, but if there's a flag I can set to enable more debug output from either the FSM or the cargo system, I'd be happy to do so. I'm already trying to figure out whether DCS has a bug about RADIO alt_type waypoints (always seem to be flying BARO), so I'm probably already spending time in DCS logs today ;)

**Comment by Delta-99** [comment]
Never thought of this but can a UH1H actually transport troops? Actually it can because I have done that before I THINK as a player. But maybe something coded in Moose not allowing there to be enough cargo space for infantry??!! Thinking further on this it might depend on the load out you have. If you have side gunners installed then maybe can’t pickup infantry. Worth testing.

**Comment by funkyfranky** [comment]
A Huey definitely can pickup cargo. However, just a certain amount which fits into the cargo bay! So there might be a difference to the Chinook. The group has to be small enough to fit into the Huey as a whole. Groups are not split. 
If the troop is too heavy (too many soldiers) no transport will happen.
I did not look at the mission file yet. But how big is your group and does the behaviour change if you take a smaller group of soldiers <= 4?

**Comment by FlightControl-User** [comment]
What if a group is split and transported 30 km further? That is why I suggest to keep groups small in size.

**Comment by FlightControl-User** [comment]
So you want to have an error  message logged that a too large group size cannot need loaded into the helo... let's do that. It is a great suggestion. Feel free to modify the moose code and submit a pull request for it.

**Comment by cjbehm** [comment]
Yeah, I did a similar kind of group transport system in Arma and managing groups of units + groups of transport units becomes very fragile. I didn't solve making multiple trips either -- if a convoy lost a transport, any units that couldn't fit would be left behind (but split off to act on their own; usually to call for an evac helicopter).

**Comment by cjbehm** [comment]
Yeah I'm looking at the loop that decides that a Carrier can't pick up a group. Since Carriers look for Cargo, I think I can only log that a specific Carrier couldn't load some cargo. I'm not sure how I'd detect that a Cargo couldn't be loaded by any Carrier.

**Comment by FlightControl-User** [comment]
Ok. I'll check it. 




Get Outlook for Android







On Sun, Oct 21, 2018 at 8:32 PM +0200, "cjbehm" <notifications@github.com> wrote:












Yeah I'm looking at the loop that decides that a Carrier can't pick up a group. Since Carriers look for Cargo, I think I can only log that a specific Carrier couldn't load some cargo. I'm not sure how I'd detect that a Cargo couldn't be loaded by any Carrier.

**Comment by cjbehm** [comment]
Alright, think I found the correct place to add the message. If there's a better location to add it, I'm happy to do so. Submitted PR #1038

**Comment by funkyfranky** [comment]
I think some kind of notification is very useful if the cargo group is too heavy for the available transports. Otherwise, many people will stumble across this and don't know what wrong in their mission.

**Comment by Delta-99** [comment]
Could an event be raised as well so that the mission designer can take action in code? Perhaps not this go around but maybe that can be put in as an additional enhancement request. For now, logging the fact is good at least will give the mission designer an idea what is going on.

**Comment by thebgpikester** [comment]
Any feature request tidyups are no longer likely and i'm archiving this.
