### ISSUE TITLE
AI_A2A_DISPATCHER RTB Fuel Threshold Issue

### ISSUE THREAD

**Issue by eric963** [FlightControl-Master/MOOSE#1035]
Using current release MOOSE release version with the default AI-A2A-011 RTB Fuel Threshold Test mission.

When the aircraft hits the fuel threshold you can see in the tactical display "FUEL" and the airbase launches another plane to replace the plane that is returning to refuel but then "LOSTCONTOL" appears in the tactical display for the refueling plane and it then heading off in random directions.

Attached is the dcs.log file. Around line 570 in the log is where all the lost control messages start to appear.

[dcs_AID-A2A-011.zip](https://github.com/FlightControl-Master/MOOSE/files/2489911/dcs_AID-A2A-011.zip)

**Comment by FlightControl-User** [comment]
This is fixed. pushing for MOOSE patch 2.4.7.
