### ISSUE TITLE
AI_A2A_DISPATCHER Refuel Tanker Issue

### ISSUE THREAD

**Issue by eric963** [FlightControl-Master/MOOSE#1036]
Using current release MOOSE release version with the default AI-A2A-016 Refuel Tanker Test mission.

When the aircraft hits the fuel threshold you can see in the tactical display "REFUEL" and the plane proceeds to the tanker and refuels as it should.  Once refueling is done "LOSTCONTOL" appears in the tactical display for that aircraft and then it appears to just randomly fly away from the patrol/cap zone.

Attached is the DCS log. At line 763 the following error appears.

`2018-10-18 01:25:49.615 ERROR   DCS: Mission script error: : [string "C:\Users\Eric\AppData\Local\Temp\DCS.openbeta\/~mis00007628"]:76878: attempt to index local '_AI_A2A' (a boolean value)
stack traceback:
	[C]: ?
	[string "C:\Users\Eric\AppData\Local\Temp\DCS.openbeta\/~mis00007628"]:76878: in function 'Resume'
	[string "local MissionControllable = GROUP:Find( ... ) local Arguments = MissionControllable:GetState( MissionControllable, '_0000000649DA3870' ) AI_A2A_CAP.Resume( MissionControllable, unpack( Arguments ) )"]:1: in main chunk`

[dcs_AID-A2A-016.zip](https://github.com/FlightControl-Master/MOOSE/files/2489926/dcs_AID-A2A-016.zip)

**Comment by FlightControl-User** [comment]
@eric963 checking ...

**Comment by FlightControl-User** [comment]
Fixed, pushing fix to develop and master and will make patch 2.4.7.
