### ISSUE TITLE
feature request - cargo tasks  - infantry transport - :RespawnOnDestroyed( true )

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#1037]
when doing infantry tasks - I use :RespawnOnDestroyed( true ) sometimes

is it possible that AFTER a task has been completed successfully that this is auto set to false so I can delete and cleanup the infantry ?

**Comment by FlightControl-User** [comment]
@shadowze did't see this. Sorry.
Can't you set this to false once the task has been completed successfully?

**Comment by thebgpikester** [comment]
I dont see FC doing this now. If he comes back, the archived ticket will be here to discuss with him.
