### ISSUE TITLE
Wrapper.Controllable ends with an unterminated comment line

### ISSUE THREAD

**Issue by Loophole62ndFF** [FlightControl-Master/MOOSE#1042]
The Controllable.lua file in MOOSE ends with a comment that does not have a line-ending.  When the files are concatenated to form MOOSE.LUA, this comment then gets concatenated to the first comment line in Group.lua

It doesn't really matter, unless you try to parse MOOSE.LUA into Lua Documentation - at least, at the moment; there is always the risk that at some future date this sort of issue might introduce obscure errors.

Recommendation: add a couple of line breaks between each file when concatenating them to create MOOSE.LUA

**Comment by thebgpikester** [comment]
fixed
