### ISSUE TITLE
POSITIONABLE:GetClimbAnge() typo + Angle returned in radians rather than degrees (maybe?)

### ISSUE THREAD

**Issue by Goreuncle** [FlightControl-Master/MOOSE#1051]
The "l" in "Angle" is missing. 
Also, I think this might be returning the angle in radians rather than degrees, so the descriptions in both the MOOSE documentation and intellisense might be incorrect.

https://flightcontrol-master.github.io/MOOSE_DOCS/Documentation/Wrapper.Unit.html##(UNIT).GetClimbAnge

Test mission + script where returned climb/descent angle values can be observed:
[Climb-Descent Angle test.zip](https://github.com/FlightControl-Master/MOOSE/files/2540890/Climb-Descent.Angle.test.zip)

**Comment by funkyfranky** [comment]
Ooops... Yes, the "l" got missing and the angle is returned in rad not degrees. Will fix! Thanks!

**Comment by FlightControl-User** [comment]
@funkyfranky is this fixed frank?

**Comment by funkyfranky** [comment]
In my internal version, yes.

**Comment by FlightControl-User** [comment]
Can I flag it as solved?

**Comment by funkyfranky** [comment]
yes

**Comment by Goreuncle** [comment]
Thanks guys!

**Comment by funkyfranky** [comment]
@Goreuncle I had fixed this only internally so far. It is now fixed in the development branch but not in the master branch.
