### ISSUE TITLE
Feature REQ - Spawning groups without templates

### ISSUE THREAD

**Issue by Mechanist11** [FlightControl-Master/MOOSE#1052]
Hi, The more I spent time with creating randomized missions the more I feel the restrictions of template based spawning. Don't get me wrong, templates are easy and fast to work with but creating entirelly random groups would be a nice addition for "expert" level users and saving resources in mission editor.

Should be separated to ground and air units (don't know about ships, maybe later)

For Ground groups the following parameters could be interresing:

Number of units
Type of units (could be different type for each unit)
Country
Heading of group (optional)
Preset location for units (like column, cone, etc if not defined manually)
Location of units based on the first unit as anchor (distance, angle from first unit, angle of unit) (optional)
Skin (optional)

For Air groups

Number of units
Type of unit (same for a flight)
Country
Heading of group (optional)
Loadout (optional, could be tricky)
Skin (optional)
Bort number (optional)
Callsign (optional)
Frequency (optional)
Height(optional)

**Comment by FlightControl-User** [comment]
gotcha.

**Comment by FlightControl-User** [comment]
okay for relase 2.5, to have this one? i hope to release this soon.

**Comment by Mechanist11** [comment]
Cool!

**Comment by shadowze** [comment]
I too would like this feature +1

**Comment by shadowze** [comment]
I have done a bit of work on this already
I have been using this reference from wiki
https://wiki.hoggitworld.com/view/DCS_func_addGroup

It would be nice if we could create our own template table (as detailed above) with all we want  in it and then pass it to MOOSE spawn functions they way we currently do with Missions editor placed template groups

**Comment by shadowze** [comment]
we can pretty much do this with GROUP:NewTemplate function already in MOOSE ... as we recently discovered

**Comment by Mechanist11** [comment]
I'll experiment with this NewTemplate function in depth, and I aim to make a more convinient function for this to be more useable. Then someone can distill it into moose material, as I'm to dumb for that.

**Comment by thebgpikester** [comment]
Spawnfrom template now exists. its what we got so hopefully enough.
