### ISSUE TITLE
AutoLase - Spams multiple messages for all available targets - Does not appear to respect MaxMarking and MaxDesignation values

### ISSUE THREAD

**Issue by Falcon-CVW5** [FlightControl-Master/MOOSE#1057]
AutoLase - Spams multiple messages for all available targets - Does not appear to respect MaxMarking and MaxDesignation values

When using AutoLase the marking status is for all the targets in the area and continues in a loop.  it does not appear to respect the maxMarking value when set to 1 and also it appears to repeat almost instantly.
there is a screenshot In the Discord Func-designate channel to show the behavior.

thanks 

Falcon-CVW5

**Comment by FlightControl-User** [comment]
This is fixed now in patch 2.4.11. Please reopen if it is not!
