### ISSUE TITLE
AI_A2A_DISPATCHER: when SetSquadronCAPInterval = 2 there are more than 2 aircraft dispatched.

### ISSUE THREAD

**Issue by janiolos** [FlightControl-Master/MOOSE#1058]
I have set a squadron with only 2 aircraft in the CAP interval and 300s for another group popup. The problem is that more than 2 aircraft are dispatched with 2 new aircraft dispatched every 300s.

This behavior is happen in MP.

See the code:

RA2ADispatcher:SetSquadron( "Red CAP", "Sochi-Adler", {  "R_T_MIG29","R_T_MIG23" })
RA2ADispatcher:SetSquadronCap( "Red CAP", RED_TRIGGER_1, 2000, 8000, 600, 800, 800, 1200, "BARO" )
RA2ADispatcher:SetSquadronCapInterval( "Red CAP", 2, 300, 300)
RA2ADispatcher:SetSquadronTakeoffInAir( "Red CAP" )

**Comment by FlightControl-User** [comment]
Really? which version of moose are U using?

**Comment by FlightControl-User** [comment]
If this is an issue, i will fix this for release 2.5.

**Comment by janiolos** [comment]
I am using 2.4.10.
I will do more test to try get more info.

**Comment by FlightControl-User** [comment]
Okay, can you retry this with the latest patches?
https://github.com/FlightControl-Master/MOOSE/releases/tag/2.4.13

**Comment by FlightControl-User** [comment]
sorry, thought you had 2.4.0

**Comment by FlightControl-User** [comment]
don't bother testing. But I've checked myself and cannot resimulate this.

**Comment by thebgpikester** [comment]
closing as fixed.
