### ISSUE TITLE
AI_A2A_DISPATCHER:SetSquadronVisible First GCI spawn invisible to clients

### ISSUE THREAD

**Issue by eric963** [FlightControl-Master/MOOSE#1060]
This only happens when using DEDICATED SERVER set to Resume With Clients.  Only the first GCI plane to spawn is invisible to the clients and subsequent GCI spawns after that are visible to the clients. 

When the clients connect and look at the F10 screen all 3 of the GCI planes are visible.

![initial_f10_screen](https://user-images.githubusercontent.com/20633883/48457369-6fb15680-e790-11e8-8cf2-81a4ac3902df.png)

Once the first plane gets detected the first GCI flight becomes invisible to the clients

![blue_plane_detected](https://user-images.githubusercontent.com/20633883/48457456-cdde3980-e790-11e8-9d9b-bcdbb411813b.png)

![screen_181113_214141](https://user-images.githubusercontent.com/20633883/48457656-72f91200-e791-11e8-8572-81571945e9b9.png)

But on the f10 screen on the dedicated server it is still there

![screen_181113_214127](https://user-images.githubusercontent.com/20633883/48457513-ff570500-e790-11e8-98e9-0b280e318b5a.png)
![screen_181113_214156](https://user-images.githubusercontent.com/20633883/48457701-99b74880-e791-11e8-8a99-e587edac9d0b.png)

When the GCI flight shoots the client down there is no chat message about the kill but on the server chat message you get the AI Mig31 has shot down so and so with a such and such. I ran the test mission 20 times and only 1 time was the first GCI intercept visible.

Here are the Client and server logs along with the test mission.

[dcsclient.zip](https://github.com/FlightControl-Master/MOOSE/files/2579081/dcsclient.zip)
[dcsserver.log.zip](https://github.com/FlightControl-Master/MOOSE/files/2579082/dcsserver.log.zip)
[setvisible.zip](https://github.com/FlightControl-Master/MOOSE/files/2579083/setvisible.zip)

**Comment by FlightControl-User** [comment]
Not sure what to do with this. This smells heavily to dcs bug... we need to report it. But how to resimulate. I reported once a similar issue to ED with ground units.

**Comment by FlightControl-User** [comment]
I can try to spawn in these planes with an  incremental delay for each plane. We'll need to test this together.

**Comment by eric963** [comment]
So another night of flying with my friend on the dedicated server and we had the same issue with the invisible plane when using "Resume on load" also.  If you have anything you want me to test just let me know.


I really like seeing the planes on the airfield!!!!!

**Comment by eric963** [comment]
This same issue also happens when the first CAP plane gets activated when using SetSquadronVisible on dedicated server.

The server dcs.log shows no errors but this error appears in the client dcs.log when the first cap plane gets activated.

2018-11-18 21:33:49.203 ERROR   Dispatcher: lua_pcall failed,?:0: attempt to index field '?' (a nil value)

**Comment by eric963** [comment]
No issues using SetSquadronVisible in single player or player hosted server with either GCI or CAP

**Comment by FlightControl-User** [comment]
This might be a sync issue between MP server and the clients. Because these objects are spawned very fast. Maybe with a small delay this problem can be fixed.

**Comment by FlightControl-User** [comment]
I'll check that error though!

**Comment by FlightControl-User** [comment]
There is a long lasting issue at ED with airplanes that get activated... also ground vehicles that get activated... same thing.

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
