### ISSUE TITLE
SET_BASE:FindNearestObjectFromPointVec2 : attempt to call method 'DistanceFromVec2'

### ISSUE THREAD

**Issue by Kathryl** [FlightControl-Master/MOOSE#1061]
On develop branch, Set.lua file contains this function : 
```
  function SET_BASE:FindNearestObjectFromPointVec2( PointVec2 )
    self:F2( PointVec2 )
    
    local NearestObject = nil
    local ClosestDistance = nil
    
    for ObjectID, ObjectData in pairs( self.Set ) do
      if NearestObject == nil then
        NearestObject = ObjectData
        ClosestDistance = PointVec2:DistanceFromVec2( ObjectData:GetVec2() )
      else
        local Distance = PointVec2:DistanceFromVec2( ObjectData:GetVec2() )
        if Distance < ClosestDistance then
          NearestObject = ObjectData
          ClosestDistance = Distance
        end
      end
    end
    
    return NearestObject
  end
```

But it end in this error : 

> 2018-11-14 14:26:12.063 INFO    SCRIPTING: MOOSE error in MENU COMMAND function: [string ".\MyCode\moose.lua"]:12102: attempt to call method 'DistanceFromVec2' (a nil value)
2018-11-14 14:26:12.063 INFO    SCRIPTING: stack traceback:
	[string ".\MyCode\moose.lua"]:7602: in function 'DistanceFromVec2'
	[string ".\MyCode\moose.lua"]:12102: in function 'FindNearestObjectFromPointVec2'
	[string ".\MyCode\moose.lua"]:16113: in function 'FindNearestAirbaseFromPointVec2'
	[string ".\MyCode\A2G_Static.lua"]:47: in function <[string ".\MyCode\A2G_Static.lua"]:6>
	(tail call): ?
	[C]: in function 'xpcall'
	[string ".\MyCode\moose.lua"]:7613: in function <[string ".\MyCode\moose.lua"]:7609>

If found out by copy/pasting/editing the same kind of code from : 
```
  function SET_GROUP:FindNearestGroupFromPointVec2( PointVec2 )
    self:F2( PointVec2 )
    
    local NearestGroup = nil --Wrapper.Group#GROUP
    local ClosestDistance = nil
    
    for ObjectID, ObjectData in pairs( self.Set ) do
      if NearestGroup == nil then
        NearestGroup = ObjectData 
        ClosestDistance = PointVec2:DistanceFromPointVec2( ObjectData:GetCoordinate() )
      else
        local Distance = PointVec2:DistanceFromPointVec2( ObjectData:GetCoordinate() )
        if Distance < ClosestDistance then
          NearestGroup = ObjectData
          ClosestDistance = Distance
        end
      end
    end
    
    return NearestGroup
  end
```

The error's gone and i have the awaited result

**Comment by FlightControl-User** [comment]
Understand, i'll fix this as a hotfix, ok?
then it is published in master and develop.

**Comment by FlightControl-User** [comment]
OK. fixed. Patch 2.4.12 is under way. Thanks for alerting this error!
Great!

**Comment by Kathryl** [comment]
I should have been more precise
Current fix show theses lines

>        ClosestDistance = PointVec2:DistanceFromPointVec2( ObjectData:GetVec2() )
>      else
>        local Distance = PointVec2:DistanceFromPointVec2( ObjectData:GetVec2() )

but it should be 

>         ClosestDistance = PointVec2:DistanceFromPointVec2( ObjectData:GetCoordinate() )
>      else
>        local Distance = PointVec2:DistanceFromPointVec2( ObjectData:GetCoordinate() )
