### ISSUE TITLE
Possible issue with Designation Area

### ISSUE THREAD

**Issue by DCSBourbon** [FlightControl-Master/MOOSE#1062]
Predator enters an area from a few miles away, enters orbit and begins identifying targets. There are 10 on the ground, but using this code:

RecceDetection = DETECTION_AREAS:New( RecceSetGroup, 5000 )

he only detects 2 of them, both of which are low priority. Full LUA for lasing below:

--begin code for Moose Lasing

--establishes that all unit groups starting with "Recce" are recon units for the mission
--if need to separate into different areas, consider "Recce 1-" and "Recce 2-"
RecceSetGroup = SET_GROUP:New():FilterPrefixes( "Recce" ):FilterStart()

--establishes a Command Center which is in charge of relaying information between Recce and Attack
HQ = GROUP:FindByName( "HQ" )

CC = COMMANDCENTER:New( HQ, "HQ" )

-- Recce vehicles allowed to detect within an area of 5000 meters
RecceDetection = DETECTION_AREAS:New( RecceSetGroup, 5000 )

-- Create a Attack Set, which contains the human player client slots and CA vehicles [not sure if I need this with only human player clients]
AttackSet = SET_GROUP:New():FilterPrefixes( "A-10", "F18" ):FilterStart()

-- Setup Designation for the AttackSet and include threat level prioritization
RecceDesignation = DESIGNATE:New( CC, RecceDetection, AttackSet )
DESIGNATE:SetThreatLevelPrioritization( true )

-- Generate the random laser codes.
RecceDesignation:GenerateLaserCodes()

-- The su-25T uses a specific laser code to guide its laser guides rockets.
-- The code is 1113. A special menu option will be added that allows to lase with 1113.
RecceDesignation:AddMenuLaserCode( 1113, "Lase for SU-25T (%d)" )

-- The A-10A etc use a specific laser code to guide its laser guides rockets.
-- The code is 1680. A special menu option will be added that allows to lase with 1688.
RecceDesignation:AddMenuLaserCode( 1688, "Lase for A-10A (%d)" )

**Comment by timguy99** [comment]
This line is incorrect in your script:

`DESIGNATE:SetThreatLevelPrioritization( true )`

It should be

`RecceDesignation:SetThreatLevelPrioritization( true )`

**Comment by Delta-99** [comment]
This line is incorrect in your script:

`DESIGNATE:SetThreatLevelPrioritization( true )`

It should be

`RecceDesignation:SetThreatLevelPrioritization( true )`

**Comment by DCSBourbon** [comment]
Understood, thanks! I think I found another issue, but it's unrelated and is specific to laser codes, so will create a new issue.
