### ISSUE TITLE
Random laser codes generating invalid codes

### ISSUE THREAD

**Issue by DCSBourbon** [FlightControl-Master/MOOSE#1063]
Using the below .LUA code, the predator generated invalid codes and the menu option to designate for A-10 (1688) didn't appear. Some of the invalid codes generated were:

6547
4780
1130
4578
4785

It recycled through this list quite significantly.

--BEGIN CODE--

--begin code for Moose Lasing

--establishes that all unit groups starting with "Recce" are recon units for the mission
--if need to separate into different areas, consider "Recce 1-" and "Recce 2-"
RecceSetGroup = SET_GROUP:New():FilterPrefixes( "Recce" ):FilterStart()

--establishes a Command Center which is in charge of relaying information between Recce and Attack
HQ = GROUP:FindByName( "HQ" )

CC = COMMANDCENTER:New( HQ, "HQ" )

-- Recce vehicles allowed to detect within an area of 5000 meters
RecceDetection = DETECTION_AREAS:New( RecceSetGroup, 5000 )

-- Create a Attack Set, which contains the human player client slots and CA vehicles
AttackSet = SET_GROUP:New():FilterPrefixes( "A10", "F18" ):FilterStart()

-- Setup Designation for the AttackSet and include threat level prioritization
RecceDesignation = DESIGNATE:New( CC, RecceDetection, AttackSet )
RecceDesignation:SetThreatLevelPrioritizationSetThreatLevelPrioritization( true )

-- Generate the random laser codes.
RecceDesignation:GenerateLaserCodes()

-- The su-25T uses a specific laser code to guide its laser guides rockets.
-- The code is 1113. A special menu option will be added that allows to lase with 1113.
RecceDesignation:AddMenuLaserCode( 1113, "Lase for SU-25T (%d)" )

-- The A-10A etc use a specific laser code to guide its laser guides rockets.
-- The code is 1680. A special menu option will be added that allows to lase with 1688.
RecceDesignation:AddMenuLaserCode( 1688, "Lase for A-10A (%d)" )

**Comment by DCSBourbon** [comment]
In looking at the source code, I couldn't figure out what was causing numbers like 4780 but it seemed like maybe there was a simpler way to get valid codes than looping through and eliminating invalid ones.

I am *extremely* unfamiliar with Lua, so there's probably some syntax issues at play here, but here's what I was thinking:

local _hundreds = math.random(6) * 100
local _tens = math.random(7) * 10
local _ones = math.random(7)
local _code = 1000 + _hundreds + _tens + _ones

**Comment by FlightControl-User** [comment]
Thank you.

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
