### ISSUE TITLE
Error:  Scheduler function - 19894 Parameter #1 group ID missed

### ISSUE THREAD

**Issue by Falcon-CVW5** [FlightControl-Master/MOOSE#1064]
We are getting this error when joining the aircraft in a multiplayer mission.  we are running 2.4.14 development version:
2018-11-16 04:25:45.475 INFO    SCRIPTING:  25444( 19894)/E:                BASE00000.GetID({[1]=Cannot GetID,[Name]=CVW-5 #001,[Class]=GROUP,})
2018-11-16 04:25:45.475 INFO    SCRIPTING: Error in SCHEDULER function:[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:19894: Parameter #1 (group id) missed
2018-11-16 04:25:45.475 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:20616: in function <[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:20612>
	[C]: in function 'outTextForGroup'
	[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:19894: in function 'ToGroup'
	[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:26777: in function 'IteratorFunction'
	[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:12235: in function 'co'
	[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:12251: in function 'Schedule'
	[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:12265: in function 'ForEach'
	[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:12828: in function 'ForEachGroup'
	[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:26775: in function 'MessageToSetGroup'
	[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:49333: in function <[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:49183>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:20624: in function '_call_handler'
	[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:20720: in function <[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:20630>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:5138: in function <[string "C:\Users\GAMESE~1\AppData\Local\Temp\DCS.openbeta\/~mis00005336"]:5097>
thanks 
Falcon-CVW5

**Comment by thebgpikester** [comment]
Thank you for your report. As you can see from the age of the report the ticket is open with no updates for a very long time. In 14 Nov 2018 the last commit to Moose 2.4 stable was made on the live branch. Since then the de facto live build has been the DEV branch which is the only one we can use for updates. This is because Flight control has stopped work on MOOSE and only, he has the permissions to release new branches, all work is on DEV branch. Your ticket predates thousands of lines of code change and has to be reproduced on a moose version that is on DEV in order to be able to be assessed.
