### ISSUE TITLE
Zone Capture error, dunno from where...

### ISSUE THREAD

**Issue by Enfarda** [FlightControl-Master/MOOSE#1066]
SCRIPTING: Error in SCHEDULER function:[string "Scripts/Moose/Functional/ZoneCaptureCoalition.lua"]:803: attempt to call method 'IsInZone' (a nil value)

**Comment by FlightControl-User** [comment]
Is this the only line?

**Comment by Enfarda** [comment]
what iu could find yes but it repeat alot of times for all mission

**Comment by Enfarda** [comment]
btw the task zone capture, dont know if working well or if i missing something
afther a zone is capture, the task is not completed.

and the assign option to automaticly select a task...
in the task zone capture, skip the accpet or reject method.

i put some pics on disc in the #core zone section

**Comment by thebgpikester** [comment]
closing as Duplicate. The issue I have also seen.
