### ISSUE TITLE
Feature REQ - Extend GROUP:GetHeight(FromGround) to UNIT class as well.

### ISSUE THREAD

**Issue by Goreuncle** [FlightControl-Master/MOOSE#1070]
A few days ago, I found myself in a situation where I needed to get the altitude from ground of individual units (rather than the average of the group). 

I thought I could use  :GetHeight(FromGround), but seems like that's only available for GROUP class. 

After checking the declaration of that method in LDT, I saw that it seems to be working at unit level.
So, I put this script together (based on that declaration) and it seems to work fine:

```
SCHEDULER:New( nil, 
function()
   local Unit = UNIT:FindByName("UNIT name in ME")
   local UnitPosition = Unit:GetPosition()
   local UnitName = Unit:GetName() 
   
   local LandHeight = land.getHeight( { x = UnitPosition.p.x, y = UnitPosition.p.z } )
   local UnitHeightFromGround = ( UnitPosition.p.y - LandHeight )
   
   MESSAGE:New(UnitName.." altitude from ground is --> "..UnitHeightFromGround,5):ToAll()
end, {}, 1, 5
)
```
Would it be possible to include :GetHeight(FromGround) to UNIT class in the future?

Thanks!

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
