### ISSUE TITLE
AI dispatcher is not despawing

### ISSUE THREAD

**Issue by Enfarda** [FlightControl-Master/MOOSE#1071]
The CAP group from AI dispatcher is not despawing at landing.

A2ADispatcher:SetDefaultLandingAtRunway()
only tried this kind of land... the anothers ones i dont know.

![blocked](https://user-images.githubusercontent.com/43972918/50022101-f6956100-ffd2-11e8-82b9-5cfb302c84bb.PNG)

MOOSE ❤️

**Comment by Delta-99** [comment]
Hi all, please keep an eye out for this across the board. I was playing with Warehouse class few days ago and saw the same behaviour. I asked @funkyfranky if it was normal and he said no, planes should respawn on landing immediately. I left things running for 4 hours to see if DCS would at least clean up these planes (the pilots exited their airframes and just stood beside them). They never despawned.

I have a feeling this is a recently re-introduced DCS bug that will affect all CLASSES that expect planes to despawn.

**Comment by shadowze** [comment]
Just a note,
I use AI_GCI_CAP a lot  this is DEFO happening a lot now - when it was intermittant before ....
On Causcas map
But I tried it on Persian Gulf today ...... and it did not happen once

**Comment by Delta-99** [comment]
Probably related to #1076
