### ISSUE TITLE
AI_A2G_Dispatcher - Dispatched aircraft not executing mission

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#1072]
AI aircraft are not executing mission. They take off, circle field and land. Errors on each aircraft launche with nil value in patrol.

**Comment by gunterlund** [comment]
[dcs.log](https://github.com/FlightControl-Master/MOOSE/files/2682718/dcs.log)
log file

**Comment by gunterlund** [comment]
![image](https://user-images.githubusercontent.com/12703141/50044672-ff6e4d00-003b-11e9-8792-01398faedf30.png)
lua code

**Comment by gunterlund** [comment]
Moose Version

![image](https://user-images.githubusercontent.com/12703141/50044678-262c8380-003c-11e9-973e-5861df910b6b.png)

**Comment by baluballa** [comment]
Assumed fixed.
