### ISSUE TITLE
Using AI_CGI_CAP getting error is log sometimes - attempt to call method 'ParkDefender' (a nil value)

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#1073]
-12-15 17:43:04.249 INFO    SCRIPTING: Error in SCHEDULER function:[string "D:\games\Develop_Moose_j.lua"]:81314: attempt to call method 'ParkDefender' (a nil value)
2018-12-15 17:43:04.249 INFO    SCRIPTING: stack traceback:
	[string "D:\games\Develop_Moose_j.lua"]:20950: in function 'ParkDefender'
	[string "D:\games\Develop_Moose_j.lua"]:81314: in function <[string "D:\games\Develop_Moose_j.lua"]:81299>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "D:\games\Develop_Moose_j.lua"]:20959: in function '_call_handler'
	[string "D:\games\Develop_Moose_j.lua"]:20720: in function <[string "D:\games\Develop_Moose_j.lua"]:20630>
	(tail call): ?
	[string "D:\games\Develop_Moose_j.lua"]:76774: in function 'onafterRTB'
	[string "D:\games\Develop_Moose_j.lua"]:81279: in function <[string "D:\games\Develop_Moose_j.lua"]:81277>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "D:\games\Develop_Moose_j.lua"]:20959: in function '_call_handler'
	[string "D:\games\Develop_Moose_j.lua"]:20720: in function <[string "D:\games\Develop_Moose_j.lua"]:20630>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "D:\games\Develop_Moose_j.lua"]:5138: in function <[string "D:\games\Develop_Moose_j.lua"]:5097>

line 81314 is 
self:ParkDefender( Squadron, Defender )

Think this happens when a plane ise sent back to base because no targets

**Comment by thebgpikester** [comment]
This was removed because it was so broken. I could reproduce quite often too, I think I did it by deleting and clearing up taxiing aircraft. Archiving.
