### ISSUE TITLE
Function TASK_A2G:updateTaskinfo(DetectedItem) returns nil Value error.

### ISSUE THREAD

**Issue by Falcon-CVW5** [FlightControl-Master/MOOSE#1075]
Issue:  When Building a SET_UNIT and then assigning that set to a TASK_A2G_BAI task results in a nil value being produced and the script fails.  no other actions are completed because moose has crashed.

it appears as though because I am not using the detection method, because no blue forces are in the area for FAC the script throws an error: 
attempt to index local 'TargetCoordinate' (a nil value)

why do I not want to use detection, the tasking maybe to destoy cargo ships, destroy hidden stores behind enemy lines where facs are just unrealistic.  I should be able to create a SET_UNIT | assign it to a BAI task and have the moose script process these as normal.

Error:
"18-12-15 20:03:43.852 INFO    SCRIPTING: MOOSE error in MENU COMMAND function: 
 "C:\Users\MARK~1.TRE\AppData\Local\Temp\DCS/~mis00000E78"]:17573: 

attempt to index local 'TargetCoordinate' (a nil value)
2018-12-15 20:03:43.852 INFO    SCRIPTING: stack traceback:
    [string "C:\Users\MARK~1.TRE\AppData\Local\Temp\DCS/~mis00000E78"]:7602:
 
in function <[string "C:\Users\MARK~1.TRE\AppData\Local\Temp\DCS/~mis00000E78"]:7599>
    [string "C:\Users\MARK~1.TRE\AppData\Local\Temp\DCS/~mis00000E78"]:17573:

 in function 'Get2DDistance'
    [string "C:\Users\MARK~1.TRE\AppData\Local\Temp\DCS/~mis00000E78"]:102705: 

in function 'ReportOrder'
    [string "C:\Users\MARK~1.TRE\AppData\Local\Temp\DCS/~mis00000E78"]:98546: 

in function <[string "C:\Users\MARK~1.TRE\AppData\Local\Temp\DCS/~mis00000E78"]:98546>
    (tail call): ?

    [C]: in function 'sort'
    [string "C:\Users\MARK~1.TRE\AppData\Local\Temp\DCS/~mis00000E78"]:2908: in function 'spairs'
    [string "C:\Users\MARK~1.TRE\AppData\Local\Temp\DCS/~mis00000E78"]:98546: in 

function 'ReportSummary'
    [string "C:\Users\MARK~1.TRE\AppData\Local\Temp\DCS/~mis00000E78"]:98672: in function <

[string "C:\Users\MARK~1.TRE\AppData\Local\Temp\DCS/~mis00000E78"]:98670>
    (tail call): ?

    [C]: in function 'xpcall'
    [string "C:\Users\MARK~1.TRE\AppData\Local\Temp\DCS/~mis00000E78"]:7613: in function <
[string "C:\Users\MARK~1.TRE\AppData\Local\Temp\DCS/~mis00000E78"]:7609>"

My CODE:

```
   TASKING.Three = function()
   local OPName = RandOpName()
   local TSKThreeBRFTXT = {"Five Russian cargo ships are parked along the break water piers at Gachin /n",
                          "They are doing their final checks for departure leaving about two hours /n",
                          "to get them while they are sitting ducks.  /n",
                          "Coordinates: N 27 02 23 E 55 59 00 /n",
                          "Weapons: MK82, MK83, AGM-65F /n",
                          "Laser code: None"}
      TSKThreeSPDEF = SPAWN:NewWithAlias("RU Cargo Ship","TSKThreeBAI")
      TSKThreeSPDEF:Spawn()
      TSKThreeUnitSetBAI = SET_UNIT:New()
                          :FilterActive(true)
                          :FilterPrefixes("TSKThreeBAI")
                          :FilterStart()
      
      TSKThreeBAI=TASK_A2G_BAI:New(MissionBAI,GrndSet,OPName,TSKThreeUnitSetBAI,TSKThreeBRFTXT)
      function TSKThreeBAI:onenterSuccess(Event,From,To)
        TSKThreeUnitSetBAI:FilterStop()
        RemoveMission(ACTIVEMISSIONS, TASKING.Three)
      end 
   end
```

offending Function:
```function TASK_A2G:UpdateTaskInfo( DetectedItem )
  
    if self:IsStatePlanned() or self:IsStateAssigned() then
      local TargetCoordinate = DetectedItem and self.Detection:GetDetectedItemCoordinate( DetectedItem ) or self.TargetSetUnit:GetFirst():GetCoordinate() 
      self.TaskInfo:AddTaskName( 0, "MSOD" )
      self.TaskInfo:AddCoordinate( TargetCoordinate, 1, "SOD" )
```

Looking at the second line:
local TargetCoordinate = DetectedItem and self.Detection:GetDetectedItemCoordinate( DetectedItem ) or self.TargetSetUnit:GetFirst():GetCoordinate() 

it never evaluates the selg.TargetSetUnit:GetFirst():Getcoordinate() because detection is NIL Value

I ran the debugger and receive this back when the following commands were run:
TASKTwoUnitSetBAI:GetFirst():GetCoordinate()
Returned: 

{metatable = table: 0000000289FAE340,["BigSmokeAndFire"] = function: 00000009E4ED2FD0,["BigSmokeAndFireHuge"] = function: 00000009EADA7840,["BigSmokeAndFireLarge"] = function: 00000002880F14B0,["BigSmokeAndFireMedium"] = function: 00000009EE5CCE10,["BigSmokeAndFireSmall"] = function: 000000094E3A6260,["BigSmokeHuge"] = function: 000000029983FD68,["BigSmokeLarge"] = function: 00000009C0E48CC0,["BigSmokeMedium"] = function: 000000001BA88A88,["BigSmokeSmall"] = function: 000000029940A5C0,["ClassName"] = "COORDINATE",["DistanceFromPointVec2"] = function: 00000002981FC820,["Explosion"] = function: 00000009C113FB10,["Flare"] = function: 000000001E0E61C8,["FlareGreen"] = function: 00000008EF384100,["FlareRed"] = function: 00000009C67872C0,["FlareWhite"] = function: 000000001B374A10,["FlareYellow"] = function: 00000002AA07E000,["Get2DDistance"] = function: 000000097BB38020,["Get3DDistance"] = function: 000000001DEDEAC8,["GetAltitudeText"] = function:
00000009EE5A8170,["GetAngleDegrees"] = function: 000000097A528970,["GetAngleRadians"] = function: 00000009C9BF4930,["GetBRAText"] = function: 000000001AA478C0,["GetBRText"] = function: 000000001B39BB20,["GetBearingText"] = function: 000000001DE379E8,["GetClosestAirbase"] = function: 0000000018B58D60,["GetClosestFreeParkingSpot"] = function: 00000009EFD9CE50,["GetClosestOccupiedParkingSpot"] = function: 000000001BCD13D8,["GetClosestParkingSpot"] = function: 00000009E7785030,["GetClosestPointToRoad"] = function: 000000029B5B7340,["GetDirectionVec3"] = function: 0000000019289FB8,["GetDistanceText"] = function: 00000009EAB69F20,["GetHeading"] = function: 0000000299758418,["GetHeadingText"] = function: 00000009C9279150,["GetLandHeight"] = function: 00000009E779DB10,["GetMovingText"] = function: 00000009C66460F0,["GetNorthCorrectionRadians"] = function: 000000029C60FDB8,["GetPathOnRoad"] = function: 000000097BB37010,["GetPressure"] = function: 0000000932044420,["GetPressureText"] = function: 000000001ACD7CE0,["GetRandomCoordinateInRadius"] = function: 00000009C0F3EB80,["GetRandomVec2InRadius"] = function: 00000002982084A0,["GetRandomVec3InRadius"] = function: 00000009EAC25F80,["GetSurfaceType"] = function: 00000009E779C6C0,["GetTemperature"] = function: 00000009E778A2E0,["GetTemperatureText"] = function: 00000009C9A12DA0,["GetVec2"] = function: 00000009EAB25A60,["GetVec3"] = function: 000000028A025610,["GetVelocity"] = function: 00000009EE5

Running the following:
TargetCoordinate = TASKTwoUnitSetBAI and TASKTwoUnitSetBAI.Detection:GetDetectedItemCoordinate(TASKTwoUnitSetBAI) or TASKTwoUnitSetBAI.TargetSetUnit:GetFirst():GetCoordinate()

returned the following error: 

Execution error 206: [string "TargetCoordinate = TASKTwoUnitSetBAI and TASKTwoUnitSetBAI.Detection:GetDetectedItemCoordinate(TASKTwoUnitSetBAI) or TASKTwoUnitSetBAI.TargetSetUnit:GetFirst():GetCoordinate()"]:1: attempt to index field 'Detection' (a nil value)

thanks 
Falcon

**Comment by Falcon-CVW5** [comment]
Here is the mission file and mission lua:

[PersianGulfServer.zip](https://github.com/FlightControl-Master/MOOSE/files/2706208/PersianGulfServer.zip)

I have cut the spawn random down to just two missions let me know you lthink this might be.

**Comment by Falcon-CVW5** [comment]
did not mean to close

**Comment by thebgpikester** [comment]
Thank you for your report. As you can see from the age of the report the ticket is open with no updates for a very long time. In July 2019 the last stable MOOSE version was released on the live branch. Since then the de facto live build has been the DEV branch which is the only one we can use for updates. This is because Flight control has stopped work on MOOSE and only, he has the permissions to release new branches, all work is on DEV branch. Your ticket predates thousands of lines of code change and has to be reproduced on a moose version that is on DEV in order to be able to be assessed.
