### ISSUE TITLE
InitRepeatOnEngineShutDown crashes DCS with new OB DCS 2.5.4.25729

### ISSUE THREAD

**Issue by HellRayzr** [FlightControl-Master/MOOSE#1076]
Since the latest OB update, we have a complete DCS crash when an AI plane lands and then taxi to parking and shuts its engine down. Tried on both servers and client PC's, same on different systems. 
Isolated it to the MOOSE function: InitRepeatOnEngineShutDown.
When using InitRepeatOnLanding DCS does not crash.

**Comment by funkyfranky** [comment]
Thanks for the report. Grimes could reproduce the crash without Moose. So this is a DCS bug. See https://forums.eagle.ru/showthread.php?t=227622

**Comment by funkyfranky** [comment]
Fixed in the development branch by introducing a 3 second delay before destroy/respawn.

**Comment by Delta-99** [comment]
In my mission this did the trick. Well, I'm still on the previous DCS version but it fixed it there too where it wouldn't despawn before. It now despawns. Previous DCS version at least does not CTD.
