### ISSUE TITLE
no heading is send afther join task :(

### ISSUE THREAD

**Issue by Enfarda** [FlightControl-Master/MOOSE#1079]
the A2A task is not sending a heading afther join... i try the intercepet and engage. is the same dont work. everthing else work nice... brifieng, report etc... is only the automatic heading giver not working,
sample of scrpit line:

Sochi_A2A_Task = TASK_A2A_SWEEP:New(A2A_MISSION,A2APilotSet,"Sochi Modern WarFair",A2A_Sochi_Set,"> ENGAGE <")

**Comment by thebgpikester** [comment]
If this issue still occurs its on a version of MOOSE that no longer exists. If you still see it please update  a new ticket as such.
