### ISSUE TITLE
unable to use SET_CLIENT as SETGROUP for A2G_TASK

### ISSUE THREAD

**Issue by Falcon-CVW5** [FlightControl-Master/MOOSE#1080]

**Comment by Falcon-CVW5** [comment]
When SET_CLIENT is used instead SET_GROUP there are missing Functions like SET_CLIENT:GetAliveSet(), SET_CLIENT:ForEachGroupAlive( IteratorFunction, ... )  these are throwing errors when using the SET_CLIENT with TASK_A2G_DISPATCHER When I added these functions the error went away but other were produced so I am going to leave this up to professionals to review and fix.

**Comment by thebgpikester** [comment]
SET_CLIENT is the unit name, SET_GROUP is a group name. Additionally you cannot perform the same operators on players as you can AI so without further information this is all as expected, the two are not the same and cannot be.
