### ISSUE TITLE
Helo not despawning after landing with Warehouse system

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#1081]
Using the Functional Warehouse system, when a helo transport flies and drops off its cargo then returns to the warehouse spawn zone, it lands and then sits there with engines running. I would have at least expected it to despawn and go back into warehouse stock.

**Comment by grandpaSam** [comment]
Do you think could include the mission file and the script?

**Comment by thebgpikester** [comment]
Frank this is yours.

**Comment by baluballa** [comment]
I will do a status check @thebgpikester. I have a fairly new test mission for the Warehouse class. Ill get back to you within the day.

**Comment by baluballa** [comment]
Guess you can close this @thebgpikester ... Its old too,
