### ISSUE TITLE
ABP - Airbase Police - Demo script not updated

### ISSUE THREAD

**Issue by 131stGutts** [FlightControl-Master/MOOSE#1089]
The "LUA" files ( ABP-002 - Nevada.lua and ABP-001 - Caucasus.lua ) are shown with:

```
local PlanesClientSet = SET_CLIENT:New():FilterCategories( "plane" ):FilterStart()
local AirbasePolice = AIRBASEPOLICE_NEVADA:New( PlanesClientSet )
```

When the expected code would be:

`ATC_Ground = ATC_GROUND_NEVADA:New()`

**Comment by thebgpikester** [comment]
we can't seem to change the moose github missions and do not know how to. :/ archiving this
