### ISSUE TITLE
Feature Request - Designate: Does not take SET_Client as AttackSet only takes SET_GROUP.

### ISSUE THREAD

**Issue by Falcon-CVW5** [FlightControl-Master/MOOSE#1105]
I get the following error when using set_Client  

[C]: in function 'ForEachGroupAlive'
    [string "Scripts/Moose/Functional/Designate.lua"]:524: in function 'SetFlashStatusMenu'
    [string "Scripts/Moose/Functional/Designate.lua"]:479: in function 'New'
    [string "D:/Users//Documents/Eclipse/Workspace/CVW-5_Missions/DeadSticks/Zones.1.1.6.lua"]:256: in main chunk
    (tail call): ?
    [string "__Moose.Include('D:/Users/Mark.Trenda/Documents/Eclipse/Workspace/CVW-5_Missions/DeadSticks/Zones.1.1.6.lua')"]:1: in main chunk
If i use SET_GROUP this seems to work fine, but if i am working with clients should it not be SET_CLIENT
  GroundSet = SET_CLIENT:New() -- GROUP:New()
            --:FilterCategoryAirplane()
            :FilterPrefixes( {"A2G", "CVW-5" } )
            :FilterCoalitions("blue")
            :FilterActive(true)
            :FilterStart()

here is the set command

**Comment by baluballa** [comment]
Are you sure you have set the **Client names** to _A2G_ and **not only Groups name**?

This set works on Client/Unit name for prefixes.

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
