### ISSUE TITLE
WAREHOUSE onaftercaptured issue

### ISSUE THREAD

**Issue by janiolos** [FlightControl-Master/MOOSE#1106]
When the enemie coalition capture the warehouse i have a problem with the function "ChangeCoalition" .

2019-01-24 21:57:24.011 INFO    SCRIPTING:  74651( 71667)/I:           WAREHOUSE01147._InfoMessage(WAREHOUSE BESLAN | Warehouse BESLAN: We were captured by enemy coalition (side=2)!)
2019-01-24 21:57:24.011 INFO    SCRIPTING: Error in SCHEDULER function:[string "C:\Users\janiolos\AppData\Local\Temp\DCS.openbeta\/~mis00005E6D.lua"]:71670: attempt to call method 'ChangeCoaliton' (a nil value)
2019-01-24 21:57:24.011 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\janiolos\AppData\Local\Temp\DCS.openbeta\/~mis00005E6D.lua"]:20598: in function 'ChangeCoaliton'
	[string "C:\Users\janiolos\AppData\Local\Temp\DCS.openbeta\/~mis00005E6D.lua"]:71670: in function <[string "C:\Users\janiolos\AppData\Local\Temp\DCS.openbeta\/~mis00005E6D.lua"]:71663>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\janiolos\AppData\Local\Temp\DCS.openbeta\/~mis00005E6D.lua"]:20606: in function '_call_handler'
	[string "C:\Users\janiolos\AppData\Local\Temp\DCS.openbeta\/~mis00005E6D.lua"]:20702: in function <[string "C:\Users\janiolos\AppData\Local\Temp\DCS.openbeta\/~mis00005E6D.lua"]:20612>
	(tail call): ?
	[string "C:\Users\janiolos\AppData\Local\Temp\DCS.openbeta\/~mis00005E6D.lua"]:73002: in function '_CheckConquered'
	[string "C:\Users\janiolos\AppData\Local\Temp\DCS.openbeta\/~mis00005E6D.lua"]:70093: in function <[string "C:\Users\janiolos\AppData\Local\Temp\DCS.openbeta\/~mis00005E6D.lua"]:70083>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\janiolos\AppData\Local\Temp\DCS.openbeta\/~mis00005E6D.lua"]:20606: in function '_call_handler'
	[string "C:\Users\janiolos\AppData\Local\Temp\DCS.openbeta\/~mis00005E6D.lua"]:20702: in function <[string "C:\Users\janiolos\AppData\Local\Temp\DCS.openbeta\/~mis00005E6D.lua"]:20612>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\janiolos\AppData\Local\Temp\DCS.openbeta\/~mis00005E6D.lua"]:5138: in function <[string "C:\Users\janiolos\AppData\Local\Temp\DCS.openbeta\/~mis00005E6D.lua"]:5097>

**Comment by funkyfranky** [comment]
Yes, there was a bug. Should be fixed in the latest development Moose.lua https://github.com/FlightControl-Master/MOOSE_INCLUDE/tree/develop/Moose_Include_Static

**Comment by janiolos** [comment]
Tested and working! good job
