### ISSUE TITLE
ZONE_CAPTURE_COALITION still detects Air groups in Zone

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#1124]
I'm sure this was posted ages back, but it's still the primary issue for our server. The capture mechanics are always temporary, so a fleeting pass from an aircraft flips it. That's possibly a minor issue, here is the real issue:

If you have dispatchers working at airbases and you use ZONE_CAPTURE_COALITION to determine ownership, then all taxiing planes hold the airbase to their coalition. Since we have issues with Air dispatcher spamming due to various reasons - broken runway, debris, taxi fuckups, you name it, then you get a small army of planes built up that reinforce the zone and thus work against you.

Real life example:
Last night i'm capturing an airbase. I put troops on the floor and spent 5 hours battling the server on my own to clear an airbase that had a GCI at it. I dropped a bomb to disable their runway as I was getting shot down a lot...working as intended.

Eventually I kill all the red at the airbase. It won't capture. Says captured on the F10 map of course. I see taxiing airplanes getting stuck. I strafed them, bombed them but they kept spawning and spawning. 

In reality, the ground troops are the only things that should hold the ground.

**Comment by Delta-99** [comment]
I thought capturing via air was an optional thing for this? If not, perhaps air capture should only count for units in the air.

Or maybe this is just really an issue with GCI.

**Comment by thebgpikester** [comment]
This is just a duplicate of the same request by Miller Time back when this was first created. I checked the functions and there is nothing to filter on ground only. A ZoneName:FilterAir(bool) function would fit and retain backwards compat.
