### ISSUE TITLE
ZONE_POLYGON.FindByName() Returns Log Error

### ISSUE THREAD

**Issue by jspencer46** [FlightControl-Master/MOOSE#1127]
Using ME vehicle with the ~ZONE_POLYGON group name tag to define ZONE_POLYGON  returns log error ": attempt to index global 'Expl_Zone' (a nil value)". That is the ~ZONE_POLYGON tag to define the zone object in the ME is not working.

**Comment by baluballa** [comment]
ZONE_POLYGON takes Wrapper.Group#GROUP as argument, not the name. You need to use GROUP:FindByName("GroupsName) in the function.

https://flightcontrol-master.github.io/MOOSE_DOCS_DEVELOP/Documentation/Core.Zone.html##(ZONE_POLYGON).New

ex:
```lua
ZonePlg = ZONE_POLYGON:New("Poly",GROUP:FindByName("GroupsName"))

BASE:E("--- Ppolygon Name = " ..  ZonePlg:GetName())```
