### ISSUE TITLE
AI_A2G_Dispatcher throws an error when executing and does not run

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#1139]
When I run AI_A2G_Dispatcher, an error occurs at moose line
Copy of log, Code and mission listed on Discord under A2G_Dispatcher channel.
Essentially error says attempt to compare number with nil at line 110677
in process ProcessDetected
When error occurs detection stops and function ends.

**Comment by baluballa** [comment]
Seems like var `self.DefenseLimit` in the AI_A2G_Dispatcher is not set (nil) when try to compare on line 110895 (my Moose version)
` if EngageCoordinate and DefenseTotal < self.DefenseLimit then`

**Comment by gunterlund** [comment]
yes putting in the parameter SetDefenseLimit fixes the problem. Dont know if this should stay here as I would think there would be an error check in the code or a default value?

**Comment by baluballa** [comment]
Old, assumed fixed.
