### ISSUE TITLE
GROUP:ResetEvents() / UNIT:ResetEvents() broken

### ISSUE THREAD

**Issue by MOOSEFork** [FlightControl-Master/MOOSE#1146]
```UNIT:ResetEvents()```

https://github.com/FlightControl-Master/MOOSE/blob/178ee096148fe5b0c2ce82f2dfb9b1088d19311d/Moose%20Development/Moose/Wrapper/Unit.lua#L981-L991

and thus ```GROUP:ResetEvents()```

https://github.com/FlightControl-Master/MOOSE/blob/178ee096148fe5b0c2ce82f2dfb9b1088d19311d/Moose%20Development/Moose/Wrapper/Group.lua#L2147-L2161

use ```EVENT:Reset( EventObject )```

https://github.com/FlightControl-Master/MOOSE/blob/178ee096148fe5b0c2ce82f2dfb9b1088d19311d/Moose%20Development/Moose/Core/Event.lua#L523-L544

which is a noop, since ```self.EventsDead``` is allways ```nil```.

This leads to stale event handler functions being execute after specificaly removing all event handler functions from a unit/group.

IMHO solution: Replace ```EVENT:Reset( EventObject )``` calls with ```EVENT:RemoveAll( EventObject  )``` calls.

**Comment by MOOSEFork** [comment]
IMHO even better solution: Remove ```UNIT:ResetEvents()``` and use ```BASE:EventRemoveAll()``` instead.

**Comment by MOOSEFork** [comment]
Adendum

```EVENT:RemoveAll( EventObject  )``` is broken.

https://github.com/FlightControl-Master/MOOSE/blob/178ee096148fe5b0c2ce82f2dfb9b1088d19311d/Moose%20Development/Moose/Core/Event.lua#L549-L560

shoud be

```lua
function EVENT:RemoveAll( EventClass  )
  self:F3( { EventClass:GetClassNameAndID() } )

  local EventPriority = EventClass:GetEventPriority()
  for EventID, EventData in pairs( self.Events ) do
    if self.Events[EventID] then
      if self.Events[EventID][EventPriority] then
        if self.Events[EventID][EventPriority][EventClass] then
          self.Events[EventID][EventPriority][EventClass] = nil
        end
      end
    end
  end
end
```

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
