### ISSUE TITLE
CONTROLLABLE:OptionRTBBingoFuel( RTB ) broken

### ISSUE THREAD

**Issue by MOOSEFork** [FlightControl-Master/MOOSE#1152]
https://github.com/FlightControl-Master/MOOSE/blob/486fc833230f6a021ee24db1cfce3badba68241e/Moose%20Development/Moose/Wrapper/Controllable.lua#L3223-L3245

`RTB = RTB or true` will evaluate to true for nil *and* false.

Should be

` 
if RTB == nil then
  RTB = true
end
`

**Comment by funkyfranky** [comment]
Fixed now. Thanks for the report.

**Comment by funkyfranky** [comment]
Fix is quite obvious ==> closing.
