### ISSUE TITLE
Moose Doc Error Hit 

### ISSUE THREAD

**Issue by jspencer46** [FlightControl-Master/MOOSE#1155]
Moose doc error: 4. EVENT DATA type table shows event Hit populates only the Initiator data field. In fact it populates the Target field, in addition, I believe.

**Comment by thebgpikester** [comment]
Correct but I can't find where you are referencing the error from because you didnt say so dont know what to change. Most folks know the Hit has initiator, target and weapon and it's at least visible as such in the graphics for event.  Archiving this unfixed as it's minor.
