### ISSUE TITLE
GROUP:CommandSwitchWayPoint() Parameters

### ISSUE THREAD

**Issue by jspencer46** [FlightControl-Master/MOOSE#1156]
Confirmed following concerning GROUP:CommandSwitchWayPoint(): 
AI will follow switched flight plan waypoints 1 less than scripted. If script is written (3, 7), AI will actually fly ME flight plan waypoints (2, 6). 

However, if the new switched WP, as scripted (say 8 in the script, relating to 7 in the ME) is a LANDING WP, the AI ignores the CommandSwitchWayPoint() altogether and simply follows the flight plan.

Perhaps Moose code can, at least in part, address this with a work-around. At the least, Moose docs should provide this info.

**Comment by funkyfranky** [comment]
Thanks!
This seems to be a DCS bug. The CommandSwitchWayPoint() function returns exactly the task as described here https://wiki.hoggitworld.com/view/DCS_command_switchWaypoint
Maybe also report this in the DCS bug section.

**Comment by Delta-99** [comment]
As long as we are sure Moose isn't doing any additional checks etc on the limits. I'm guessing likely not because probably there is no way to do that. And as long as Moose is calling switchWaypoint in the way we think it is.

Has anyone tested the actual DCS API call itself and see what happens?

**Comment by funkyfranky** [comment]
As I said, the function literally returns the task described on the hoggit page. No additional checks, no conversion of waypoint numbers.

Regarding the numbering: The first (initial) waypoint in the ME is zero, whereas the (DCS) function obviously has it defined as one.

**Comment by Delta-99** [comment]
I wasn't sure what function you were referring to. Thought you were referring to some DCS API function not Moose. I see that now.
