### ISSUE TITLE
Feature Request - CSAR Module - new method to disable Bearing and Range to CSAR pilot to pickup

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#1157]
I would like a setting  / method to disable the menu option that gives you bearing / range
to pilot you are subscribed to a CSAR task and are going to pickup a pilot (using CSAR module)

I want this so I can make it more realistic for CSAR pilots, with the aim being to maybe add a distress beacon to the downed pilot and get the CSAR to use ADF to locate the pilot

Maybe make it part of the CSAR set-up method ?
thanks for reading this SVEN

**Comment by thebgpikester** [comment]
Unassigned. Good call but nae chance this gets changed by FC now.
