### ISSUE TITLE
in database.lua it looks like a function is duplicated - DATABASE:FindZone( ZoneName ) 

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#1158]
DATABASE:FindZone( ZoneName )
function seems to appear twice

is this maybe why it doesn't work ? (or  Iam too dumb to work out how to use it)

**Comment by baluballa** [comment]
Indeed function appears twice in DATABASE. However they are duplicated so this alone should not cause any issues. 

However function does not return zones, even zone exists and is registered in database.

**Comment by funkyfranky** [comment]
There is a bug in the DATABASE:OnEventNewZone( EventData ) function it seems.

Currently it is:
```--- Handles the OnEventNewZone event.
-- @param #DATABASE self
-- @param Core.Event#EVENTDATA EventData
function DATABASE:OnEventNewZone( EventData )
  self:F2( { EventData } )

  if EventData.Zone then
    self:AddZone( EventData.Zone )
  end
end
```

But it should be
```
--- Handles the OnEventNewZone event.
-- @param #DATABASE self
-- @param Core.Event#EVENTDATA EventData
function DATABASE:OnEventNewZone( EventData )
  self:F2( { EventData } )

  if EventData.Zone then
    self:AddZone( EventData.Zone.ZoneName, EventData.Zone )
  end
end
```
I.e. first argument in AddZone() function should be the name of the zone.

**Comment by shadowze** [comment]
phew, so it is not just me miss-using this

**Comment by shadowze** [comment]
yep I am miss using this,  any functions with DATABASE need to be called with _DATABASE
eg   docs list DATABASE:FindZone   but you use _DATABASE:FindZone
to actually get this to work on the created MOOSE database which is called _DATABASE

Thanks for the help guys
