### ISSUE TITLE
_SETTINGS:SETLL_Accuracy has no effect on coordinates reporting

### ISSUE THREAD

**Issue by falcon76** [FlightControl-Master/MOOSE#1171]
Please uncomment lines 2941-2946
    if acc <= 0 then  -- no decimal place.
      secFrmtStr = '%02d'
    else
      local width = 3 + acc  -- 01.310 - that's a width of 6, for example.
      secFrmtStr = '%0' .. width .. '.' .. acc .. 'f'
    end
this code is written to use the floating decimal point but is currently commented out of the utils.tostringLL function rendering the ability to have decimal seconds for DMS unfunctional.

I will look to see how accurate this decimal is right now and may be why it is remarked out but we need to functionality to have decimal second for jdams and jsows

**Comment by falcon76** [comment]
Additionally we need the elevation of the targets on the reporting.

**Comment by funkyfranky** [comment]
Changes are included in the latest Moose development version. Please test and report back.

**Comment by falcon76** [comment]
sorry did not get back to that this is working and completed
