### ISSUE TITLE
DETECTION: Late activation groups in SET's break DETECTION

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#1173]
So far I've discovered that if a group of EWR is late activated and in a Detection SET then detection is broken.

Steps to repro
1. using attached mission, verify in the F-15 you fly south and see two radars and verify you have a GCI response.

2. go to mission editor.
3. set both EWR's to late activated.
4. remove the script condition so the two EWR's spawn
5. Save and reenter the mission, fly south, observe two EWR on the RWR
6. Notice NO TASK OR INTERCEPTIONS

i.e. the Detection is not working or the SET, one of.
[AID-A2A-071 late activation bug.zip](https://github.com/FlightControl-Master/MOOSE/files/3322038/AID-A2A-071.late.activation.bug.zip)

**Comment by Delta-99** [comment]
Thanks for the detailed issue and mission attached Pikes

**Comment by funkyfranky** [comment]
Problem seems to be this line
self.DetectionCount = self.DetectionSet:Count()
which counts the total number of detection groups, i.e. activated + late activate.
Later there is a line
if self.DetectionCount > 0 and self.DetectionRun == self.DetectionCount then
...
end
but that never becomes true as the number of detection runs (from the active groups) will not reach the detection count (active + late activated).

**Comment by funkyfranky** [comment]
Pikes, you had a chance to test the new code?
