### ISSUE TITLE
CARGO_GROUP:New - for some reason is re-creating cargo inside the buildings instead of  on the roof

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#1180]
been using CARGO_GROUP:New along with TASK_CARGO_TRANSPORT:New for a long time now
Its been great, I have some scripts that spawn in infantry both in single and 4 man fire team configurations and create tasks for heli pilots to pick them up

Some of the locations are on top of roofs and the infantry appear on the roof top and can be picked up, not sure what has **happened but now the infantry are spawning on the ground INSIDE the building**, making picking them up somewhat impossible

If I call a spawn on the buildings location myself the infantry are on the roof and all is well, so I think it must be related to the cargo stuff ( because it destroys and then creates a new version of this group with #CARGO in the name ?)y

 Please can anyone look into this I have some awesome heli missions that rely of infantry being able to be picked up from roof tops.  eg Air Taxi and  fire rescue tasks

**Comment by shadowze** [comment]
![image](https://user-images.githubusercontent.com/30597073/60771581-46a85200-a0e2-11e9-9156-0eb7cdef4982.png)
normally on the roof they are

![image](https://user-images.githubusercontent.com/30597073/60771605-853e0c80-a0e2-11e9-9282-c59b2a182fbb.png)

**Comment by timguy99** [comment]
I'd bet this is 100% due to DCS changes. Don't think there is much of a way for Moose to spawn them on the roof or otherwise!!!

**Comment by Delta-99** [comment]
I'd bet this is 100% due to DCS changes. Don't think there is much of a way for Moose to spawn them on the roof or otherwise!!!

**Comment by funkyfranky** [comment]
I would also think it a change in DCS. What happens if you put them on the roof in ME, i.e. without spawning? Does that work?

**Comment by shadowze** [comment]
never tried manual placement in ME as this is scripted, BUT I can in game spawn an infantry squad in and they spawn on top of the roof, will investigate more when I get home this evening

**Comment by thebgpikester** [comment]
Consider PG map. Read a post that AI handle PG objects differently. They dont navigate objects when moving at least. Either way, nothing we can do. Archiving this one. We have nowhere to go unless you can think of soemthing.
