### ISSUE TITLE
AI A2A Dispatcher [Feature request]: Option for sensor on /off

### ISSUE THREAD

**Issue by 132ndNeck** [FlightControl-Master/MOOSE#1181]
Would it be possible to add an opttion in AI A2A Dispatcher for setting Radar on / off .
This so the CAP flight have radar turned off until he is given a task, and is leaving CAP and starting intercept.
- For randomness, having a random time for when the Radar turns on after he leaves the CAP track, and relies on EWR or AWACS guidance to target for some time. ( to avoid giving away intentions on RWR to players)

For background to this request, please see:
https://github.com/132nd-vWing/OPUF/issues/14
and
https://132nd-vwing.github.io/OPUF-Brief/

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
