### ISSUE TITLE
AI A2A Dispatcher [Feature request]: Spacing out CAP's / share CAP's

### ISSUE THREAD

**Issue by 132ndNeck** [FlightControl-Master/MOOSE#1182]
Would it be possible to setup certain CAP's and have different squadrons rotate on who is responsible for the CAP. Also, having the CAP's rotate between various CAP zones.

For example 3 squadrons and 2 CAP zones:

Squadron 1/Flight 1 flies and conduct CAP in CAP zone 1. Once SQN1/Flight 1 is RTB, then SQN2/Flight 1 flies out, and this time it takes either CAP zone 1 or CAP zone 2. Once RTB, then  SQN 3/Flight 1 flies out and takes either CAP zone 1 or CAP zone 2.

If a CAP is tasked, then the next 2 squadrons both launches their next CAP filling up both CAP zones (to simulate increasing alert levels). As these new CAP's are not an alert CAP/GCI, then it should be an option of setting up a timedelay for when the 2 CAP' should be airborne, to take maintanance and alert level into account. For example, 60 minutes after the CAP is tasked, then the next squadrons launches their aircraft to fill the 2 CAP zones (with a randomness so they launces betweem 30-90 minutes after tasking).

For background to this request, please see:
https://github.com/132nd-vWing/OPUF/issues/14
and
https://132nd-vwing.github.io/OPUF-Brief/

**Comment by thebgpikester** [comment]
Right now the design is that dispatcher has a 1:1 responsibility for it's own CAP. That's quite a fundamental design thing, but it is possible to reissue dispatcher lines to simulate what is being asked and give them a new zone, just call the lines **again** like I do in https://youtu.be/tfrdOMJSo6s

There's almost zero chance of wholesale changes to Dispatcher in the medium future without FLight Control being available.
