### ISSUE TITLE
AI A2A Dispatcher [Feature request]: GCI delay

### ISSUE THREAD

**Issue by 132ndNeck** [FlightControl-Master/MOOSE#1183]
Would it be possible to add an option to set various times for the GCI?
This to set manual alertlevels.  Also adding a way to set a timeframe that the script chooses from to increase randomness.  As soon as there is an intruder detected on radar and given to the appropriate station to deal with then this alert level comes into play, and the aircraft will startup after this.

Having a way to set this alert levels make it more realistic and possible to set realisitic alert levels.

For example: Some squadrons with high alert of 15 minutes, other with lower alertlevels of 30 or 90 minutes.

For background to this request, please see:
https://github.com/132nd-vWing/OPUF/issues/14
and
https://132nd-vwing.github.io/OPUF-Brief/

> 

> Ok, to put it more in words:

> This script is intended to be the basic framework of "standard" Iranian response. So this is intended for something that they will be able to keep for 24/7 operations for some time.

> At any given time, 1 CAP is either operational, or aircrafts are enroute to the CAP zone. This CAP can either be manned from Shiraz or Kerman. The two airbases alternates between who is responsible for the CAP duty. 

> If a CAP is tasked, then 2 additional CAP's will be launched. However, as these are not alert aircrafts, they will need 60 minutes (random between 30-90 minutes) from CAP is tasked until they are airborne and enroute

> **Quick Reaction Alert**

> Both Shiraz and Kerman have their QRA fighters aswell. These aircraft are on a 15 minute alert (15 minutes from they are given a task until they are airborne). For randomness (put this between 7 minutes and 25 minutes). If a CAP is tasked, the QRA flights from one of the airfields will be launched (closest one?).  The other is a backup, so if the original CAP flight is shot down, or the QRA flight is shot down, the second QRA flight is launched.

> **Forward staging**

> In LAR and at JIROFT there is a 50% chance that the airfield will have a 2ship forward staged. If it is forwardstaged it will have on a 15 minute alert to respond to any threats (GCI). For randomness, set time between 7 and 25 minutes.

> **CAP specific**

> - CAP's fly in a racetrack pattern, hotleg toward Blue airfields.

> - For randomness, at times aircraft can fly with radar off, and turn on radar when they leave CAP orbit to intercept (when they have recived an order from AWACS or GCI)

> - Normally a CAP will be flown by a 2ship. However, for randomness, make a small chance for it to be a 4ship  (and if possible, have 2 ac fly to do AAR, while 2 stay at the CAP racetrack when they need to refuel)

> **Objectives**

> 1. The primary objective is to protect Shiraz, Kerman and Lar Air Defence zone as shown on the first picture in this thread. 

> 2. Secondary objective is to prevent any interference with Iranian AWACS or Iranian Tanker activity taking place somewhere Shiraz and Kerman Air Defence Zones.

> Both AWACS and Tanker's are High Value Units so something the Iranians can not afford to loose.

> 3. Third, the effect is to prevent any Blue air activity over Iranian mainland, preventing BLUE from conducting CAS, AR, SEAD or Strike missions

> **Alertlevel**

> Any blue aircrafts taking off and approaching the Iranian mainland increses the alertlevel (detected either by AWACS or EWR). This can have the following reaction: (can be a random thing, set 30 % for any of the things below to happen)

> - QRA (GCI): QRA(GCI) aircraft will reduce their alerttime to 5 minutes.

> - CAP: A second CAP can be launched (So 2 CAP's are manned)

> - A Escortflight  from Kerman can be sent to escort AWACS and/or Tanker?

**Comment by thebgpikester** [comment]
This is complex work. We are in a maintenance mode for existing modules that @FlightControl-User created as he has been absent for most of 2019.
As a mitigation - Dispatcher can mimmic a lot of this by being switched off and on according to events, so it's possible to make it behave a bit like the suggestions already, you just need the triggers at a code level to directly change Dispatcher. See https://youtu.be/tfrdOMJSo6s for ideas.

I'd personally like to an entire overhaul of A2A_Dispatcher as it's a very useful module, but the chances we will get any complex work done are sadly very small if we take a realistic look at Franks workload.

For the sake of being realistic, I'm sadly closing this. If FC comes back or anyone overhauls Dispatcher, we can revisit an overhaul. This ticket will remain as a reference despite being closed so the data and concepts are not lost, anyone working on it can review the old feature requests.
