### ISSUE TITLE
SEAD Fix (weapon names and routines.utils.round)

### ISSUE THREAD

**Issue by nroysden** [FlightControl-Master/MOOSE#1186]
Using some basic debugging (writing out WeaponName, checking the input to routines.utils.round, which was throwing an error after correcting the weapon names), I noticed two issues that were causing the SEAD module to fail.

First, the weapon names need to be changed as following:

```lua
SEADWeaponName == "weapons.missiles.X_58" --Kh-58U anti-radiation missiles fired
    or 
    SEADWeaponName == "weapons.missiles.Kh25MP_PRGS1VP" --Kh-25MP anti-radiation missiles fired
    or
    SEADWeaponName == "weapons.missiles.X_25MP" --Kh-25MPU anti-radiation missiles fired
    or
    SEADWeaponName == "weapons.missiles.X_28" --Kh-28 anti-radiation missiles fired
    or
    SEADWeaponName == "weapons.missiles.X_31P" --Kh-31P anti-radiation missiles fired
    or
    SEADWeaponName == "weapons.missiles.AGM_45A" --AGM-45A anti-radiation missiles fired
    or
    SEADWeaponName == "weapons.missiles.AGM_45" --AGM-45B anti-radiation missiles fired
    or
    SEADWeaponName == "weapons.missiles.AGM_88" --AGM-88C anti-radiation missiles fired
    or
    SEADWeaponName == "weapons.missiles.AGM_122" --AGM-122 Sidearm anti-radiation missiles fired
    or
    SEADWeaponName == "weapons.missiles.ALARM" --ALARM anti-radiation missiles fired 
```

Regarding the 'round' function error: routines.utils.round is never defined in the MOOSE codebase. So I added the following and now the SEAD class seems to be working as intended.

```lua
routines.utils.round = function(number, decimals)
    local power = 10^decimals
    return math.floor(number * power) / power
end
```

(Edited for concision)

**Comment by shadowze** [comment]
great catch, routines.utils.round is indeed missing from MOOSE and it is referenced 13 times in total, so this defo needs to go back in

**Comment by funkyfranky** [comment]
Thanks, I'll add those changes in the next develop Moose version. Please test and report back once it is done :)

**Comment by Delta-99** [comment]
How can it be that round is missing. Shouldn’t this be breaking all kinds of things??!!  Or was it somehow removed by accident recently? Seems very odd.

**Comment by shadowze** [comment]
How can it be missing, because it is either been removed or was never there
checked my archive of MOOSE versions, it aint in April 2019 version so it been gone for a while

**Comment by funkyfranky** [comment]
This part is very old. The "routines" stuff is copied from MIST and not really being used elsewhere.
Also the SEAD class looks ancient as it does not use much of the "newer" Moose functions like SCHEDULER or MESSAGE.
