### ISSUE TITLE
Error's report

### ISSUE THREAD

**Issue by Enfarda** [FlightControl-Master/MOOSE#1193]
"C:\Users\Enfarda\AppData\Local\Temp\DCS\/~mis00004E89.lua"]:5552: attempt to concatenate upvalue 'Source' (a nil value)"

C:\Users\Enfarda\AppData\Local\Temp\DCS\/~mis00004E89.lua"]:5558: attempt to concatenate upvalue 'Source' (a nil value)

this errors came with new update "MOOSE Delevop", making the mission not run the spawns.
currently im using the "MOOSE FF/Delevop" the mission run normally.

can be from my mission... but if run in a older version i dont know so.
any new methods add in the new update? but if was the error log should show my file directory and my mission file only have 1000 written lines (+/-).

**Comment by funkyfranky** [comment]
Thanks @Enfarda . Should be fixed now with commit #1197

**Comment by Enfarda** [comment]
tks for the quick fix :) everthing is working
