### ISSUE TITLE
Resurect Client/Player

### ISSUE THREAD

**Issue by Couby** [FlightControl-Master/MOOSE#1194]
Hi,

Is there a possible way to resurect a client/player after a dead event ?
This to allow a client to resume on game without having to go through slot choice interface.

I tried with CLIENT:Reset and CLIENT:ReSpawnAt but without success, I guess these are not intended for that...

**Comment by Delta-99** [comment]
No, they do not work at the Client level. There is not much (if anything) you can do programmatically with client slots on the scripting engine side of things. On the server engine side of things you can enable / disable slots but not much else.
