### ISSUE TITLE
A2A dispacther

### ISSUE THREAD

**Issue by Enfarda** [FlightControl-Master/MOOSE#1198]
hello.   i tested with 1 enemy unit.

Dont know if is normal but the task is not going to Sucess afther the enemys  destroyed.
i tried multiples times and i wasnt able to complete the task.
then when i was change slot the task was going to replanning then obselete.
the flash report was always reporting even afther enemy dead.
i tried this to check but anything happen... i receive the score of kill but not of the function

function A2ACombat_Dispatcher:OnAfterAssign( From, Event, To, Task, TaskUnit, PlayerName )
  Task:SetScoreOnSuccess( "#"..PlayerName.."#Extra Points granted!", 150, TaskUnit )
end

i hope is a helpfull report. 
Tks for all your work in this free project. we(community) aprreciate all the MOOSE team for the great work.
stay well and good day.

just check it... on A2A and A2G dispatchers. afther i die if i dont change slot or go to spectator, 
the flash report keep report me the task i joined before i crash. 
im not in any task. pic added.

(pic taken just afther report happen)
![test](https://user-images.githubusercontent.com/43972918/64909471-86a03c80-d704-11e9-8294-d66ea96b25e9.PNG)

**Comment by FlightControl-User** [comment]
I'll check. Working on a speech system right now.

**Comment by Enfarda** [comment]
ofc im just reporting... the fix is up to you xD
btw just to add another pic on A2G dispatcher.... in here it goes to Sucess State but then stay stuck in there... and the flash report just keep spamming...

![Capturar](https://user-images.githubusercontent.com/43972918/64911333-2b784500-d718-11e9-8fd7-c3383412b889.PNG)
