### ISSUE TITLE
AI_AIR:onafterStatus() self:Fuel() call keeping RTB from being set to true when checking fuel threshold.

### ISSUE THREAD

**Issue by brianmckinney** [FlightControl-Master/MOOSE#1205]
When self:Fuel() is called inside the if branch checking for fuel threshold RTB is not set to true.

if Fuel < self.FuelThresholdPercentage then
      
        if self.TankerName then
          self:I( self.Controllable:GetName() .. " is out of fuel: " .. Fuel .. " ... Refuelling at Tanker!" )
          self:Refuel()
        else
          self:I( self.Controllable:GetName() .. " is out of fuel: " .. Fuel .. " ... RTB!" )
          local OldAIControllable = self.Controllable
          
          local OrbitTask = OldAIControllable:TaskOrbitCircle( math.random( self.PatrolFloorAltitude, self.PatrolCeilingAltitude ), self.PatrolMinSpeed )
          local TimedOrbitTask = OldAIControllable:TaskControlled( OrbitTask, OldAIControllable:TaskCondition(nil,nil,nil,nil,self.OutOfFuelOrbitTime,nil ) )
          OldAIControllable:SetTask( TimedOrbitTask, 10 )
    
          self:Fuel()
          RTB = true
        end
      else
      end

**Comment by thebgpikester** [comment]
Is this enough to work on Frank?

**Comment by thebgpikester** [comment]
I'd like to leave this a bit longer to see if it fixes some of the silly refuelling calls i've seen in the logs. Feedback approecated

**Comment by Delta-99** [comment]
What is RTB = true doing here? I haven't looked at the code in general so hopefully just a quick answer for someone. Isn't the task being setup to still stay in orbit until refuelling timeout is kicked in? Then an RTB should be done. ALTHOUGH, I'm not sure why this isn't done in the first case as well!!! All-in-all I'm thinking the entire logic for all of this is still messy!!

**Comment by Delta-99** [comment]
I took a quick look at the code. If you look at the next code block RTB = true will be set anyway (well depending on some other logic). So it was probably written this way on purpose and likely makes sense. Setting it here MAY not be a good idea. I'd look further into the logic of this entire refuelling situation.

**Comment by funkyfranky** [comment]
No feedback, so I presume everything is okay. Reopen if not.
