### ISSUE TITLE
AI_AIR_ENGAGE:onafterAccomplish() self:SetDetectionOff() method call is nil.

### ISSUE THREAD

**Issue by brianmckinney** [FlightControl-Master/MOOSE#1206]
SetDetectionOff() does not exist in AI_AIR_ENGAGE or any of the classes it inherits.

**Comment by thebgpikester** [comment]
Hi, I'm not sure I understand the impact of this, could you make a brief attempt at an impact statement so I can assess it accurately, please?
I'v eunassigned FC, because there's no chance he will be working this but if its important enough and worthwhile we could spend the effort.

**Comment by funkyfranky** [comment]
True, self:SetDetectionOff() is called in AI_AIR_ENGAGE:onafterAccomplish() and the :SetDetectionOff() is only in AI_PATROL_ZONE, which is not inherited.

Therefore, I commented out the reference to :SetDetectionOff() in the :onafterAccomplish() function of the AI_AIR_ENGAGE class.
