### ISSUE TITLE
report about A2A,A2G dispacther

### ISSUE THREAD

**Issue by Enfarda** [FlightControl-Master/MOOSE#1207]
![Capturar](https://user-images.githubusercontent.com/43972918/65992939-204b4600-e488-11e9-9ad0-ce82d8d37d12.PNG)

Issues found:
Task is not going to sucess state.(new tasks arent created until i abort the task.)(A2A)
Flash report keep reporting afther task is abort or completed(A2G/A2A)
tasks reports is not showing all units in the group(Using areas detection)(A2G)

Steps i make on flight:
Joined A2A task.
Flash Report was automaticly on
destroyed target.
10 min free fly to check task update(nothing happen)
checked the task's report from mission menu and was only 1 task planned
the pic i sent show  the menu and reports behavior.

since you working on new dispatchers, i just thought this could help in something. probably you already know about this, but well ^^ 
Tks for the awsome work `thumbsup` Cheers

[Mission file if needed to confirm stuffs.zip](https://github.com/FlightControl-Master/MOOSE/files/3678278/Mission.file.if.needed.to.confirm.stuffs.zip)

**Comment by thebgpikester** [comment]
I have seen and read a lot about tasks not being closed. I think it is a legitimate bug with TASK. Unfortunatley you know the status with moose, so Im archiving this as its not getting worked.

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
