### ISSUE TITLE
Provide target land height as part of the A2G Dispatcher Detailed Report

### ISSUE THREAD

**Issue by Harry3106** [FlightControl-Master/MOOSE#1213]
The DCS FA-18C (likely also the F-16) requires, along with precise coordinates, the input of the **target height** for the employment of precision-guided munition in pre-planned and target-of-opportunity mode.
If implemented the target height should be made available as part of the A2G Dispatcher Detailed Report.
The only work around today is to find the coordinate on the F10 map, which is cumbersome and introduces the possibility of inaccuracies.

**Comment by thebgpikester** [comment]
Closing as a duplicated and removing @FlightControl-User 
None of the original Task/Detection/Designation messaging contains height data and we are not working on any enhancements at this time. If Flight Control comes back to Moose we can revisit an overhaul of all those modules that do not display height information. Until then, there's no enhancements coming.
