### ISSUE TITLE
AI_A2A_DISPATCHER - Possibility to add EngageZone which should be within the given Border

### ISSUE THREAD

**Issue by LosMackos** [FlightControl-Master/MOOSE#1223]
Hi there,

I started implementing this by myself, but it seems I would have to re-use (copy&paste) a lot of code, so it probably would make more sense to add this in the Dispatcher directly.
The idea is to have a two layered cold-war scenario, where the Border, which is handed over to the Detection Class as reject criteria, is representing the air space and a additional zone, which should be, at least partially, inside this border, which represents the engagement zone. With this second zone given, I would like to see the CAP or GCI intercept detected targets with ROE = ReturnFireOnly and instead of an EngageTask, they would go in with a FollowTask.
Detected Units crossing this engagement zone would have a higher priority, so the FollowTask could be aborted by an EngageTask or would be accomplished when the followed/intercepted Units leave the Detection Zones.

Thanks,
LosMackos

**Comment by thebgpikester** [comment]
This is very complex work. I dont believe we can assign anything to @FlightControl-User reliably and it would send a wrong message to sugest anyone is working this feature. At the moment the code is in maintenance mode and no enhancements are being pursued. 

The premise of the feature makes sense, but it's wanting different responses in different zones and there is only so much you can do with the AI controllables, they are either in engage mode or they are completely passive. Return FIre settings do not work on existing controllables - you can test this by shooting THROUGH a border zone at an aircraft, it is just dumb drone until it's assigned.

Your workaround/mitigation is to redefine the border zone in realtime according to coded events. I detailed this in a video here: https://youtu.be/tfrdOMJSo6s 
I would suggest you stick to the original design and do not hope for a change, it would not be fair to suggest we can incorporate this.
