### ISSUE TITLE
Invalid escape sequence

### ISSUE THREAD

**Issue by mike-212** [FlightControl-Master/MOOSE#1226]
Hi, i probably found some tiny syntax error in Airboss.lua on line 17763 and 17870

Moose version: 2.5.0pre1
File: Airboss.lua
```lua
self:E(self.lid.."WARNING: lfs not desanitized. Results will be saved in DCS installation root directory rather than your \"Saved Games\DCS\" folder.")
```
There is a escaping slash in \"Saved Games\DCS\" string.

PS: of course i tried to run it without unsanitized options :)

M.

**Comment by thebgpikester** [comment]
Presume since was self assigned and titled as a bug this was solved (I heard something on it in Discord) but the ticket was orphaned. If this is not so, please reopen.
