### ISSUE TITLE
Menu bug - attempt to concatenate local 'Text' (a table value)

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#1227]
running scripts I have run for a long time, noticed this in newest moose version
using
env.info( '*** MOOSE GITHUB Commit Hash ID: 2019-11-09T20:02:28.0000000Z-d30b89cc0bc01fa17edfb022b1da7631afd698c7 ***' )

2019-11-13 18:27:23.396 INFO    SCRIPTING: MOOSE error in MENU COMMAND function: [string "D:\games\Develop_Moose_l.lua"]:136752: attempt to concatenate local 'Text' (a table value)
2019-11-13 18:27:23.396 INFO    SCRIPTING: stack traceback:
	[string "D:\games\Develop_Moose_l.lua"]:8228: in function <[string "D:\games\Develop_Moose_l.lua"]:8225>
	[string "D:\games\Develop_Moose_l.lua"]:136752: in function 'Report'
	[string "D:\games\Develop_Moose_l.lua"]:135556: in function <[string "D:\games\Develop_Moose_l.lua"]:135547>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "D:\games\Develop_Moose_l.lua"]:8239: in function <[string "D:\games\Develop_Moose_l.lua"]:8235>

there are 2 line added to this version diff from MOOSE develop, they are in CSAR section to make only Belgium pilots trigger CSAR missions 

[Develop_Moose_l.zip](https://github.com/FlightControl-Master/MOOSE/files/3842931/Develop_Moose_l.zip)

**Comment by funkyfranky** [comment]
Please elaborate, which classes are used in your scripts that throw the error.

**Comment by shadowze** [comment]
CSAR, it is the only thing I have running that uses the F10 menu

**Comment by thebgpikester** [comment]
I know this one, sort of.

Can you try to make the MENU_COMAND a local variable and the function it calls a local function. I solved exactly that with lots of issues on otherwise correct code with menu's off the latest build.

**Comment by thebgpikester** [comment]
"attempt to concatenate local 'Text' (a table value)" can easily be recreated by sending the wrong data to message, so without further data for 2 months, am closing out. You can reopen it by providing the whole dataset and steps to reproduce at any time if you want to dig into this. Message works right now.
