### ISSUE TITLE
Feature Request - Elevation returned with coordinates Designation 

### ISSUE THREAD

**Issue by falcon76** [FlightControl-Master/MOOSE#1229]
Feature Request - Elevation returned with coordinates
when we get the coordinates from designate can we get the elevation of that item also.  

thanks 
Falcon

**Comment by funkyfranky** [comment]
Can you elaborate, please? Which class and/or example do you mean?

**Comment by falcon76** [comment]
the class would be designate.  when the coordinates are returned we do not get an elevation.  we3 do get lat and log North and east, we can even set the decimal accuracy but we can get it to  return the elevation and with precision bombing we need elevation.  there is a big difference in coordinates at 0 ft and 3000 ft elevation, the bomb wil never hit the target.  

thanks 

Falcon

**Comment by thebgpikester** [comment]
Hi, the ticket makes sense, but we have no developers to work on core feature enhancements and it would be unfair to keep this open. I use mark points and manually add QFE, alt to the coordinates in code. I think this ticket does have a lot of merit however and makes sense. The Designate code developer left moose last year and the effort required to make even sensible changes is  immense to unpick. I think the only way to do this well would be a complete revisit on the code and I would suggest to look at design and discuss in the Discord channel to see if you can get traction with Frank to consider revisting Designate and Detection using things like marker points or other overhaul level changes. Please consider to gain interest from others in the community to increase weight for reconsidering this in the future, if enough groups use this it could tip it over and be accepted. For now, we are in extended maintenance mode and basically only bandaiding thigs actually broken where possible.
