### ISSUE TITLE
AI_ESCORT - CONTROLLABLE:IsHelicopter() - nil value

### ISSUE THREAD

**Issue by CraigOwen** [FlightControl-Master/MOOSE#1230]
In order to get my escort running i simply added the following code to the CONTROLLABLE class.

`--- Returns if the Controllable contains Helicopters.
-- @param #CONTROLLABLE self
-- @return #boolean true if Controllable contains Helicopters.
function CONTROLLABLE:IsHelicopter()
  self:F2()

  local DCSObject = self:GetDCSObject()

  if DCSObject then
    local Category = DCSObject:getDesc().category
    return Category == Unit.Category.HELICOPTER
  end

  return nil
end`

**Comment by thebgpikester** [comment]
If this isn't fixed, please reopen. It appears done.
