### ISSUE TITLE
BUG Report - AI_A2A_DISPATCHER:Order( DetectedItem )  is throwing nil errors

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#1232]
using MOOSE GITHUB Commit Hash ID: 2019-11-09T20:02:28.0000000Z-d30b89cc0bc01fa17edfb022b1da7631afd698c7

I use AI_A2A_GCICAP (and have done for 2 years now and it has worked fine)

now I am getting

2019-11-20 19:36:36.620 INFO    SCRIPTING: 114368(114518)/I:                 AI_A2A_GCICAP03835.Order({[DefenderSquadron]=Novorossiysk,})
2019-11-20 19:36:36.621 INFO    SCRIPTING: Error in SCHEDULER function:[string "D:\games\Develop_Moose_l.lua"]:114373: attempt to index local 'AttackCoordinate' (a nil value)
2019-11-20 19:36:36.621 INFO    SCRIPTING: stack traceback:
	[string "D:\games\Develop_Moose_l.lua"]:22227: in function <[string "D:\games\Develop_Moose_l.lua"]:22223>
	[string "D:\games\Develop_Moose_l.lua"]:114373: in function 'Order'
	[string "D:\games\Develop_Moose_l.lua"]:114518: in function <[string "D:\games\Develop_Moose_l.lua"]:114518>
	(tail call): ?
	[C]: in function 'sort'
	[string "D:\games\Develop_Moose_l.lua"]:3023: in function 'spairs'
	[string "D:\games\Develop_Moose_l.lua"]:114518: in function 'ProcessDetected'
	[string "D:\games\Develop_Moose_l.lua"]:137151: in function <[string "D:\games\Develop_Moose_l.lua"]:137147>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "D:\games\Develop_Moose_l.lua"]:22245: in function '_call_handler'
	[string "D:\games\Develop_Moose_l.lua"]:22341: in function <[string "D:\games\Develop_Moose_l.lua"]:22251>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "D:\games\Develop_Moose_l.lua"]:5621: in function <[string "D:\games\Develop_Moose_l.lua"]:5569>

line number 114373 is :

local EvaluateDistance = AttackCoordinate:Get2DDistance( AirbaseCoordinate )

is a few lines up:
local AttackCoordinate = self.Detection:GetDetectedItemCoordinate( DetectedItem )

returning nil ?
[Develop_Moose_l.zip](https://github.com/FlightControl-Master/MOOSE/files/3871114/Develop_Moose_l.zip)

**Comment by ataribaby42** [comment]
Thanks for fix. I will test latest version.
