### ISSUE TITLE
AI_CARGO_APC no longer working

### ISSUE THREAD

**Issue by neonbasschild** [FlightControl-Master/MOOSE#1233]
Several long-standing functions of moose are no longer functioning, AI_CARGO_APC being one of them.

Code Used:

APC_Set_Blue = SET_GROUP:New():FilterPrefixes("APC"):FilterCoalitions("blue"):FilterStart()

Infantry_Blue = SET_CARGO:New():FilterTypes("Infantry"):FilterCoalitions("blue"):FilterStart()

Mountup_Blue = AI_CARGO_APC:New(APC_Set_Blue,Infantry_Blue,300) <-----line 5 throwing errors

Error:

2019-11-22 16:14:06.057 ERROR   DCS: Mission script error: : [string "C:\Users\Shadow\Gorgas Dropbox\Derrick Cochran\DCS_Mission_Files\Moose.lua"]:127193: attempt to call method 'GetUnits' (a nil value)
stack traceback:
	[C]: in function 'GetUnits'
	[string "C:\Users\Shadow\Gorgas Dropbox\Derrick Cochran\DCS_Mission_Files\Moose.lua"]:127193: in function 'New'
	[string "C:\Users\Shadow\Gorgas Dropbox\Derrick Cochran\DCS_Mission_Files\Moose.lua"]:127710: in function 'New'
	[string "C:\Users\Shadow\Gorgas Dropbox\Derrick Cochran\DCS_Mission_Files\APC.lua"]:5: in main chunk

**Comment by funkyfranky** [comment]
The first argument "APC" in AI_CARGO_APC:New(APC, CargoSet) is a GROUP not a set. If you provide a set, the method GetUnits() is not defined and returns nil.

**Comment by neonbasschild** [comment]
Thanks! Wasnt aware that there was a diffrence between groups and group sets.
