### ISSUE TITLE
A2A/A2G dispatchers

### ISSUE THREAD

**Issue by Enfarda** [FlightControl-Master/MOOSE#1243]
just to remember to review this classes and what is on it... flash reports keep reporting afther person die or respawn and the detection group is not detecting all targets on zone.... mainly the infantry units most of times arent detected.

A2A dispatchers is all the time changing the mission tointercept then swwep vice versa each time a new scan is done, making the mission stuck for a few seconds.

**Comment by thebgpikester** [comment]
Is this solved with the Frank fix 5 days ago?

**Comment by thebgpikester** [comment]
No further updates, closing.
