### ISSUE TITLE
AI_Balancer issues.

### ISSUE THREAD

**Issue by robgrahamau** [FlightControl-Master/MOOSE#1245]
Helping Ziramond1916 trying to sort his script today noticed some 'issues' happening and I'm not certain if it's in AI_Balancer or in SET_CLIENT or in both.

first off this code wasn't working (with correct units) 
```
-Sets up the AI Balancer
BASE:E({"script start ai balance"})
BluePlaneSpawn={}
BluePlaneSpawn[1]=SPAWN:New("BLUE Batumi CAP"):InitCleanUp(45)
BluePlaneSpawn[2]=SPAWN:New("BLUE Senaki CAP"):InitCleanUp(45)
BluePlaneSpawn[3]=SPAWN:New("BLUE Nalchik CAP"):InitCleanUp(45)
BluePlaneSpawn[4]=SPAWN:New("BLUE Carrier CAP"):InitCleanUp(45)

BlueClientPlaneSet={}
BlueClientPlaneSet[1]=SET_CLIENT:New():FilterPrefixes("BLUE CAP F-15C Batumi")
BlueClientPlaneSet[2]=SET_CLIENT:New():FilterPrefixes("BLUE CAP F-15C Senaki")
BlueClientPlaneSet[3]=SET_CLIENT:New():FilterPrefixes("BLUE CAP F-15C Nalchik")
BlueClientPlaneSet[4]=SET_CLIENT:New():FilterPrefixes("BLUE CAP F-14B Carrier")

Blue_AI_Balancer={}
for i=1, 4 do
  Blue_AI_Balancer[i]=AI_BALANCER:New(BlueClientPlaneSet[i], BluePlaneSpawn[i])
end```


First issue was that SET_CLIENT:FilterPrefixes did not seem to be working if the client string was 
"BLUE CAP F-15C Batumi" nothing, shorting it to "BLUE CAP Batumi" didn't seem to work, while shorting it to BLUE CAP1 and the corresponding units etc did.
```
--Sets up the AI Balancer
BASE:E({"script start ai balance"})
BluePlaneSpawn={}
BluePlaneSpawn[1]=SPAWN:New("BLUE Batumi CAP"):InitCleanUp(45)
BluePlaneSpawn[2]=SPAWN:New("BLUE Senaki CAP"):InitCleanUp(45)
BluePlaneSpawn[3]=SPAWN:New("BLUE Nalchik CAP"):InitCleanUp(45)
BluePlaneSpawn[4]=SPAWN:New("BLUE Carrier CAP"):InitCleanUp(45)

BlueClientPlaneSet={}
BlueClientPlaneSet[1]=SET_CLIENT:New():FilterPrefixes("BLUE CAP1")
BlueClientPlaneSet[2]=SET_CLIENT:New():FilterPrefixes("BLUE CAP2")
BlueClientPlaneSet[3]=SET_CLIENT:New():FilterPrefixes("BLUE CAP3")
BlueClientPlaneSet[4]=SET_CLIENT:New():FilterPrefixes("BLUE CAP4")

Blue_AI_Balancer={}
for i=1, 4 do
  Blue_AI_Balancer[i]=AI_BALANCER:New(BlueClientPlaneSet[i], BluePlaneSpawn[i])
end```

However now the mission started to spawn Infinit amounts of F-15's, the F-14's (blue cap4) appear to work fine. 

changing the code to

```
--Sets up the AI Balancer
BASE:E({"script start ai balance"})
BluePlaneSpawn={}
BluePlaneSpawn[1]=SPAWN:New("BLUE Batumi CAP"):InitCleanUp(45):InitLimit(2,200)
BluePlaneSpawn[2]=SPAWN:New("BLUE Senaki CAP"):InitCleanUp(45):InitLimit(2,200)
BluePlaneSpawn[3]=SPAWN:New("BLUE Nalchik CAP"):InitCleanUp(45):InitLimit(2,200)
BluePlaneSpawn[4]=SPAWN:New("BLUE Carrier CAP"):InitCleanUp(45):InitLimit(2,200)

BlueClientPlaneSet={}
BlueClientPlaneSet[1]=SET_CLIENT:New():FilterPrefixes("BLUE CAP1")
BlueClientPlaneSet[2]=SET_CLIENT:New():FilterPrefixes("BLUE CAP2")
BlueClientPlaneSet[3]=SET_CLIENT:New():FilterPrefixes("BLUE CAP3")
BlueClientPlaneSet[4]=SET_CLIENT:New():FilterPrefixes("BLUE CAP4")

Blue_AI_Balancer={}
for i=1, 4 do
  Blue_AI_Balancer[i]=AI_BALANCER:New(BlueClientPlaneSet[i], BluePlaneSpawn[i])
end
```
spawns in 3 

so some weirdness is happening. and wanted it bug reported. Copy of the mission with infinit f15's and a copy with the 3 attached.

infinit15 - working ai balancer but second set of code.
semi - 3 groups when as far as i can tell there should be 2 and possibly infinit after the first group lands.

[Infinitf15sUnnamed_OP.zip](https://github.com/FlightControl-Master/MOOSE/files/4008396/Infinitf15sUnnamed_OP.zip)
[semi_infinitf15sUnnamed_OP.zip](https://github.com/FlightControl-Master/MOOSE/files/4008398/semi_infinitf15sUnnamed_OP.zip)

**Comment by thebgpikester** [comment]
WIll need someone to reproduce this on the mission supplied. Will get round to it.

**Comment by baluballa** [comment]
I am not sure about this... 
I have two files, semi_infinitf15sUnnamed_OP has these AI_Balancer Lines: 
```lua
--Sets up the AI Balancer
BASE:E({"script start ai balance"})
BluePlaneSpawn={}
BluePlaneSpawn[1]=SPAWN:New("BLUE Batumi CAP"):InitCleanUp(45):InitLimit(2,200)
BluePlaneSpawn[2]=SPAWN:New("BLUE Senaki CAP"):InitCleanUp(45):InitLimit(2,200)
BluePlaneSpawn[3]=SPAWN:New("BLUE Nalchik CAP"):InitCleanUp(45):InitLimit(2,200)
BluePlaneSpawn[4]=SPAWN:New("BLUE Carrier CAP"):InitCleanUp(45):InitLimit(2,200)

BlueClientPlaneSet={}
BlueClientPlaneSet[1]=SET_CLIENT:New():FilterPrefixes("BLUE CAP1")
BlueClientPlaneSet[2]=SET_CLIENT:New():FilterPrefixes("BLUE CAP2")
BlueClientPlaneSet[3]=SET_CLIENT:New():FilterPrefixes("BLUE CAP3")
BlueClientPlaneSet[4]=SET_CLIENT:New():FilterPrefixes("BLUE CAP4")

Blue_AI_Balancer={}
for i=1, 4 do
  Blue_AI_Balancer[i]=AI_BALANCER:New(BlueClientPlaneSet[i], BluePlaneSpawn[i])
end
```
The other file (Infinitf15sUnnamed_OP) has these lines: 
```lua
--Sets up the AI Balancer
BASE:E({"script start ai balance"})
BluePlaneSpawn={}
BluePlaneSpawn[1]=SPAWN:New("BLUE Batumi CAP"):InitCleanUp(45)
BluePlaneSpawn[2]=SPAWN:New("BLUE Senaki CAP"):InitCleanUp(45)
BluePlaneSpawn[3]=SPAWN:New("BLUE Nalchik CAP"):InitCleanUp(45)
BluePlaneSpawn[4]=SPAWN:New("BLUE Carrier CAP"):InitCleanUp(45)

BlueClientPlaneSet={}
BlueClientPlaneSet[1]=SET_CLIENT:New():FilterPrefixes("BLUE CAP1"):FilterStart()
BlueClientPlaneSet[2]=SET_CLIENT:New():FilterPrefixes("BLUE CAP2")
BlueClientPlaneSet[3]=SET_CLIENT:New():FilterPrefixes("BLUE CAP3")
BlueClientPlaneSet[4]=SET_CLIENT:New():FilterPrefixes("BLUE CAP4")

Blue_AI_Balancer={}
for i=1, 4 do
  Blue_AI_Balancer[i]=AI_BALANCER:New(BlueClientPlaneSet[i], BluePlaneSpawn[i])
end
```
And only one of the set has any kind of FilterStart mechanism. `BlueClientPlaneSet[1]=SET_CLIENT:New():FilterPrefixes("BLUE CAP1"):FilterStart()`

To me it appears like the F15C AI pilots bails out, at parking-spot right after been spawned.

![image](https://user-images.githubusercontent.com/7481653/74439285-3f150c80-4e6c-11ea-8edf-25627a718651.png)

**Comment by robgrahamau** [comment]
having issues making this one do it on a clean mission so we are closing it for now, if it rears up we'll relook at it.. thanks wing for the help.
