### ISSUE TITLE
House Cleaning: Miss Spelling in CALLSIGN.AWACS.Overloard - Should Be "Overlord"

### ISSUE THREAD

**Issue by falcon76** [FlightControl-Master/MOOSE#1248]
House Cleaning: Miss Spelling in CALLSIGN.AWACS.Overloard - Should Be "Overlord"

minor misspelling in the function call, there is an extra "a" in the word lord.

thanks 

Falcon - JTF70

**Comment by baluballa** [comment]
Seems fixed
