### ISSUE TITLE
david asked if SPAWN can delay the scheduled spawns at mission start

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#125]
Add an option to SpawnScheduled.

**Comment by thebgpikester** [comment]
Is this "an Initial spawn delay" rather than spawn scheduled immediately spawns, then begins to honour the schedule thereafter?

**Comment by Grey-Echo** [comment]
I find this issue very strange. Wouldn't the result be achieved by simply scheduling the spawn win SCHEDULER? If so, is this feature really needed?

**Comment by Delta-99** [comment]
Or maybe this is a spawn delay for the first spawn (perhaps the only spawn) and that is it. Maybe a SpawnDelay() can be added to Spawn. If SpawnScheduled can handle this right now then this is a mute point.

**Comment by FlightControl-Master** [comment]
this is a very Old request and relates to spawnscheduled... At mission start, spawnscheduled spawns all elements immediately. He wanted to have it delayed. This requirement makes sense for missions, but it's a pain for testing missions or dev work. You'll have your units much later instead of immediately and testing takes much more time. A choice to be made and not sure if David is waiting for this requirement.

**Comment by Delta-99** [comment]
I could use this in a lot of cases. Testing isn't so much a problem cause in testing I'm going to set it to something within a few minutes. That should be enough to tell me the function is working.

The level of effort to implement might be too much though for what it is worth. I can think of some possible work arounds that might do the job.

**Comment by Grey-Echo** [comment]
Since there is an interest for this feature, I'll move it back to Moose-2.1. We can always postpone it if the work is not worth the reward just yet.

**Comment by Delta-99** [comment]
If I can find some time to test if what I'm saying is true then may help FC.

**Comment by FlightControl-Master** [comment]
@Delta-99 I think you misunderstood what i wanted to say. If you have all your units at mission start, it tests quicker your mission. If each group spawns minutes later, you're waiting and waiting. It worked like that eaelier, and i was happy I changed to spawn immediately at mission start.  To develop the function is not much of a problem. In mp anyway nobody will notice. But i don't want to be the difficult guy. Is this really important? And if yes, is it important enough to delay the development of key for building blocks in the framework? I can look into this, but wanna rather focus on other stuff first. I delayed this because nobody was urgently asking for it.

**Comment by Delta-99** [comment]
This is not high priority for me and I can work around it. It can wait. I'd just rather see it as an option to Spawn rather than a SpawnScheduled. To me it is different than a delay to SpawnScheduled

**Comment by FlightControl-Master** [comment]
Lets put this on hold ... Or even close ... What is your opinion? Who is asking for this?

**Comment by Grey-Echo** [comment]
Until we can find a solution that is both mission designer-friendly and tester friendly, I'm assigning this issue to Moose-future.

**Comment by thebgpikester** [comment]
could you not just add a boolean for respecting the initial schedule to SPAWN, and by default if its off, then its an instant spawn and if true, then it respects the schedule?

**Comment by FlightControl-Master** [comment]
Guys, I've put this for release 2.1. I'll follow the suggestion of @thebgpikester which seems to me a good solution to merge both worlds.

**Comment by FlightControl-Master** [comment]
Started with the development in branch master-enh-125-spawn-schedule-delay

**Comment by FlightControl-Master** [comment]
Delivered to master for beta testing in #411.

**Comment by gunterlund** [comment]
so how do I read this SpawnScheduled( 30, 0.4, TRUE ) -- respects initial schedule. "Spawn 30 seconds from now give or take 15 seconds"??

**Comment by FlightControl-Master** [comment]
the SpawnScheduled API format is unchanged to ensure backward compatibility. By default the initial delay is added. You can turn off the initial delay by adding an :InitDelayOnOff( false ). I think :InitDelayOff() is still with an issue but will fix that tomorrow.

**Comment by FlightControl-Master** [comment]
I put the default that when SPAWN starts with ScheduledSpawning, it will wait... But actually i will reverse this. When Spawn starts with scheduling, it will NOT wait, unless you specify a delay. I will revert this.

**Comment by Delta-99** [comment]
I agree with this implementation FC especially so that you don't change current functionality that people have in their missions right now. No changes for them. Only changes for people who want to implement the new delay feature.

**Comment by FlightControl-Master** [comment]
Closing ...
