### ISSUE TITLE
WAREHOUSE:

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#1260]
Apparently groups don't fire back during transport to and from warehouses.

Check ROE status when spawning due to a request.

Reported to Wingthor, by Shifty. 

Defect needs to confirmed.  plz, switch label todo to doing when work has started.

**Comment by funkyfranky** [comment]
For GROUND groups, ROE is set to "Return Fire" but the alarm state is set to "Green" to have them moving. Could be changed to "Auto" to let them defend.
For AIR groups ROE is "Return Fire" and ROT is "Passive Defense".
For NAVAL groups ROE is "Return Fire". Alarm state is not applicable here, I think.

**Comment by baluballa** [comment]
Not sure what you mean @funkyfranky . Is this the fix in Moose.lua, or should it be set by user in `OnAfterAssetSpawned` function?

**Comment by funkyfranky** [comment]
Just wanted to report the actual settings. Also worth noting that there is a difference between Ground, Air and Naval groups as the initial report was just about groups in general. Plus, that for ground groups, it is actually the alarm state that prevents groups from fighting back when they are attacked.

Setting ROE, ROT and Alarm State should indeed be possible via the OnAfterAssetSpawned function.

**Comment by baluballa** [comment]
Ok, I have checked that this work. So added some lines to docs.

**Comment by thebgpikester** [comment]
sorry for the aggressive close, but... you explained it and updated docs.
