### ISSUE TITLE
ATC_GROUND_PERSIANGULF: Abu Musa Island Airport double entry

### ISSUE THREAD

**Issue by funkyfranky** [FlightControl-Master/MOOSE#1264]
Double entry of AIRBASE.PersianGulf.Abu_Musa_Island_Airport. One should probably be AIRBASE.PersianGulf.Al_Dhafra_AB

**Comment by thebgpikester** [comment]
merged and closing.

**Comment by funkyfranky** [comment]
Did not test myself but was told that the order is reversed.

**Comment by baluballa** [comment]
What order? Al_Dhafra_AB from was absent list. I tested on missing AB and got kicked due to speeding.

**Comment by baluballa** [comment]
@funkyfranky if not same issue, don't reopen plz. Make a new one.

**Comment by funkyfranky** [comment]
Well, from the message I got:

> line 50709 should be  [AIRBASE.PersianGulf.Abu_Musa_Island_Airport]
> line 50728 should be [AIRBASE.PersianGulf.Al_Dhafra_AB]

Sounds like currently, it is the other way around (again, did not check myself).

**Comment by baluballa** [comment]
Right, well I have tested. Might be a coincidence, it worked at missing AB Al_Dhafra_AB. I close make a new issue and swap and fix.
