### ISSUE TITLE
Add DCS tasks

### ISSUE THREAD

**Issue by funkyfranky** [FlightControl-Master/MOOSE#1272]
Add missing DCS tasks like Embarking/disembarking, carpet bombing etc.

**Comment by thebgpikester** [comment]
These would be fun to use, there are quite a few that should be fairly easy to add so we can do more with CONTROLLABLE!

**Comment by funkyfranky** [comment]
Tasks have been adjusted and work nicely.

**Comment by Delta-99** [comment]
> Tasks have been adjusted and work nicely.

LOL, nice comment ;)
