### ISSUE TITLE
Spawning aircraft AI onto the ground causes them to explode instantly.

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#1274]
This is new in 2.5.6
Steps to repro - use any valid SpawnAtAirbase() script and you will see a big explosion where the aircraft would have appeared.
TO DO: Create lua from the SSE to addGroup() so a bug can be created to ED.

**Comment by thebgpikester** [comment]
pinged Grimes about this at datestamp

**Comment by thebgpikester** [comment]
[SpawnAtAirbaseBug.zip](https://github.com/FlightControl-Master/MOOSE/files/4215229/SpawnAtAirbaseBug.zip)

**Comment by thebgpikester** [comment]
attempted: planes, non FC3, normal, with/without routes, starting from another airbase parked and the result is the same for fixed wing.

However, helicopters behave differently. 
2020-02-17 17:30:45.825 ERROR   DCS: Helicopter birth place is unknown
and no helicopter appears.

In all cases if the parking is blocked, emmergency airstart is invoked, they air start and spawn fine. So its literally spawning to the ground.

**Comment by thebgpikester** [comment]
tested on Dedicated server. same result.

**Comment by thebgpikester** [comment]
OK, fixed with Franks commit to dev.

**Comment by Koene1999** [comment]
sorry sir, i have no idea how Github works... So i hope i'm doing this the right way by asking right here. But i have the exact same problem that you describe here. How do i fix it?

**Comment by thebgpikester** [comment]
Join Moose Discord, cannot troubleshoot this here. It's fixed in the Dev branch. For most airports and some cannto be fixed because its a DCS bug.

**Comment by Koene1999** [comment]
Thank you for the quick reply
