### ISSUE TITLE
SPAWN:NewFromTemplate() does not work.

### ISSUE THREAD

**Issue by OttoWerkr** [FlightControl-Master/MOOSE#1286]
When using SPAWN:NewFromTemplate(), the template provided in the parameters is disregarded and the original template is retrieved using _GetTemplate().  I believe this is done in error, due to the first several lines of SPAWN:_Prepare() which read:
```
--	if not self.SpawnTemplate then
--	  self.SpawnTemplate = self:_GetTemplate( SpawnTemplatePrefix )
--	end
  local SpawnTemplate = self:_GetTemplate( SpawnTemplatePrefix )
--	local SpawnTemplate = self.SpawnTemplate

```
The commenting should be reversed on all 5 lines.  I don't know if this is an error, or was done to fix another problem, but when those edits are made, SPAWN:NewFromTemplate() works as intended.

**Comment by baluballa** [comment]
Which version of Moose is this?

**Comment by OttoWerkr** [comment]
All versions since 2.4.a. 
It doesn't throw an error. It simply disregards the template provided when calling SPAWN:NewFromTemplate(SpawnTemplate, SpawnTemplatePrefix, SpawnAliasPrefix), and retrieves the SpawnTemplate from the group defined by SpawnTemplatePrefix.  This makes NewFromTemplate() functionally the same as SPAWN:NewWithAlias().

The best way to demonstrate this is with an example mission.  Load the mission up in the ME and start it.  Switch views to the spawned aircraft and observe.
Then, back in the mission editor, change the first trigger from FLAG OFF(1) to FLAG ON(1) to load the edited Moose.  Run the mission and observe that now the SPAWN:NewFromTemplate() uses the edited template to spawn an asymmetrical group and change it's destination airbase, from the exact same script.

[NewFromTemplateTest.miz.zip](https://github.com/FlightControl-Master/MOOSE/files/4313388/NewFromTemplateTest.miz.zip)

**Comment by baluballa** [comment]
I must say, this mission is not very suited for debugging... Also the miz file is not a valid DCS mission file.

DeepCopying of tables and inject them into Group tables for tweaking a spawn template is not a common way of using 

Usually you do a MyTemplate =  GROUP:GetTemplate() then you use the result as arg into NewFromTemplate.

Also I am not sure your code will work anyway. If you want help with your mission, you can ask in our Discord group.
```lua
local F14template = SPAWN:New('F-14')
local F18template = SPAWN:New('F-18')
local HomePlate = AIRBASE:FindByName(AIRBASE.Caucasus.Batumi)
local Airbase =   AIRBASE:FindByName(AIRBASE.Caucasus.Kobuleti)

-- Change the landing airbase from Kolkhi to Batumi
local HomeCoord = HomePlate:GetCoordinate()
local NewTemplate = UTILS.DeepCopy(F14template.SpawnTemplate)
local Waypoint = NewTemplate.route.points[2]
Waypoint.x = HomeCoord.x
Waypoint.y = HomeCoord.z
Waypoint.alt = HomeCoord.y
Waypoint.airdromeId = HomePlate:GetID(true)

-- Change Unit #2 of the F-14 group to an F-18
NewTemplate.units[2] = UTILS.DeepCopy(F18template.SpawnTemplate.units[2])

-- Spawn the group and the results SHOULD be:
--
-- Using the Edited Moose file:
-- A 2-unit group consisting of (1) F-14B and (1) F/A-18C will take off from Kobuleti and land at Batumi
--
-- Using a current, unedited Moose file:
-- (2) Tomcats takeoff from Kobuleti and land at Kolkhi

local NewGroup = SPAWN:NewFromTemplate(NewTemplate,'F-14','F-14_and_F18'):SpawnAtAirbase(Airbase,SPAWN.Takeoff.Runway)```
There seems to be many issues in this code.

Anyway I will look for bugs _if, and only if_ you send a valid miz file.

**Comment by OttoWerkr** [comment]
I can't send a valid miz file here, GitHub won't accept it.  I had to add ".zip" to get it to upload.  If you just remove the .zip from the filename, you're left with 'NewFromTemplateTest.miz'.  The code DOES work, and I know about using GetTemplate(), but anything you change in that template (like livery, callsign, etc)  is lost as soon as you call Spawn() because SPAWN:_Prepare() throws out the template that you provided when you called NewFromTemplate().  It renders NewFromTemplate() useless.

Since both NewFromTemplate() and the commented out lines in _Prepare() both first appeared in v2.4.a, I can't imagine why Flight Control would go to the trouble of creating such a useful function as NewFromTemplate() and then intentionally make it useless by commenting out those lines.

**Comment by baluballa** [comment]
Ok, will try open...

Have you tried debugging the function NewFromTemplate() your self? Do you know its not working, or have you just tested with your included code?

**Comment by baluballa** [comment]
Wrong button...

**Comment by baluballa** [comment]
You know you can _override_ Moose function SPAWN:_Prepare() by making a new one with same name.

**Comment by OttoWerkr** [comment]
I've been messing with NewFromTemplate() for months trying to make it work.  I discovered the issue with the commented out lines in _Prepare() the other day, deleted the comment marks, and viola, NewFromTemplate() works!  I have been running the edited version of the moose file on my server for about 3 days now and haven't had an error yet.

**Comment by baluballa** [comment]
BTW: I manage to open the file. 

Are you in Discord?

**Comment by OttoWerkr** [comment]
Yes, I have overridden several functions in my testing.  But I just thought I'd post my findings here.
I am in discord as 'A101Wayz 8083'

**Comment by baluballa** [comment]
Right... I am Wingthor in Dicsord and most else places too.

However I will look more for a bug in the function in a more generic use of it. Your code looks quite complex by DeepCopy of lua tables. I assume FC, GetTemplate() does the same, but it takes the whole template, not just some units.

So your issue might not classify as a bug, but it might be a feature request. I am not sure who or why those lines was commented, but since FC has been away for a while, I can't tell.

**Comment by OttoWerkr** [comment]
I understand.  And I know that DeepCopy isn't the usual way of doing things. I could have used:
local NewTemplate = F14template.SpawnTemplate
But that is just changing the template pointer to point to the original template.  I wanted to produce a unique table that I could change values in without affecting the original template.  Just disregard the DeepCopy calls.

**Comment by OttoWerkr** [comment]
If you run the mission, then change the flag in the ME's trigger section, you will see two very different outcomes from the same script.

**Comment by baluballa** [comment]
I can't reproduce with your mission... Nothing is spawned with both verision of Moose. In both versions I get this message in dcs.log
```
2020-03-10 22:28:32.690 INFO    SCRIPTING:  10954( 10856)/I:            DATABASE00003._RegisterGroupTemplate({[Coalition]=2,[Category]=0,[Group]=F-14_and_F18#001,[Country]=2,[Units]={[1]=F-14_and_F18#001-01,[2]=F-14_and_F18#001-02,},})
2020-03-10 22:28:32.706 INFO    SCRIPTING:  10765( 10867)/I:            DATABASE00003.AddGroup({[1]=Add GROUP:,[2]=F-14_and_F18#001,})
```
Then later down I get this:
```
2020-03-10 22:28:42.417 ERROR   DCS: Mission script error: : [string "C:\Users\xxx\AppData\Local\Temp\DCS.openbeta\/~mis00004C17.lua"]:6400: attempt to index local 'EventMeta' (a nil value)
stack traceback:
	[C]: ?
	[string "C:\Users\xxx\AppData\Local\Temp\DCS.openbeta\/~mis00004C17.lua"]:6400: in function 'onEvent'
	[string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>
``` 
So again your mission is not very well suited to debug native Moose function as the error can very well be in provided code,

**Comment by OttoWerkr** [comment]
Did you hit F2 in mission to switch to the Spawned Group?
Not sure where the error is coming from, but there is nothing in my script that has anything to do with events or event handlers...  Maybe because of OB?  I'm using 2.5.5 and it works on my machine.
Just tried it in OB, and I get the same error.  Don't know what that's all about...

**Comment by baluballa** [comment]
So testing with: 
```lua
local F14group = GROUP:FindByName("F-14")

local f14Template = F14group:GetTemplate()
local NewGroup = SPAWN:NewFromTemplate(f14Template,'F-18','F-14_and_F18'):Spawn()
``` 
Indeed spawns groups with original template (F-18 template), so bug seems to be confirmed. Seems on my system `:SpawnAtAirbase(Airbase,SPAWN.Takeoff.Runway)` does not work. Emphasize the need of clean missions when test for bugs

**Comment by OttoWerkr** [comment]
I apologize for the SpawnAtAirbase.  As I said, I'm still using DCS 2.5.5 because of all the bugs in 2.5.6.  I assure you it is a "clean mission" and works flawlessly in 2.5.5

**Comment by OttoWerkr** [comment]
I did discover one hiccup in using NewFromTemplate()...  The SpawnAliasPrefix  parameter is mandatory.  Without the alias, the newly spawned group gets its GroupName from SpawnTemplatePrefix parameter, and this will create a conflict with the SpawnIndex and despawn the Group with the SpawnTemplatePrefix#001 SpawnIndex.  But it's the same thing that will happen if you use SPAWN:NewWithAlias() and provide an alias that's already in use.  So, not really a bug, just something to be aware of, and the 'optional' tag should be removed from the docs for NewFromTemplate().

**Comment by baluballa** [comment]
Right, I understand... Will make it so NewFromTemplate will return nil if SpawnAliasPrefix()  is not set.
