### ISSUE TITLE
spawn is broken in latest MOOSE

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#1289]
Ok same mission with spawning ground units for my target range using DCS 2.5.6 for both versions of MOOSE and same script 

with MOOSE build  2020-02-22T17:49:44   is works fine

With 2020-03-11T14:36:02 MOOSE build it stop after a short while with this error

2020-03-13 21:01:49.389 INFO    SCRIPTING: Error in SCHEDULER function:[string "D:\games\Develop_Moose_q.lua"]:27060: bad argument #1 to 'pairs' (table expected, got nil)
2020-03-13 21:01:49.389 INFO    SCRIPTING: stack traceback:
	[string "D:\games\Develop_Moose_q.lua"]:22603: in function <[string "D:\games\Develop_Moose_q.lua"]:22599>
	[C]: in function 'pairs'
	[string "D:\games\Develop_Moose_q.lua"]:27060: in function 'SpawnAtAirbase'
	[string "D:\games\Develop_Moose_q.lua"]:115662: in function 'ResourceActivate'
	[string "D:\games\Develop_Moose_q.lua"]:115692: in function <[string "D:\games\Develop_Moose_q.lua"]:115678>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "D:\games\Develop_Moose_q.lua"]:22621: in function '_call_handler'
	[string "D:\games\Develop_Moose_q.lua"]:22717: in function <[string "D:\games\Develop_Moose_q.lua"]:22627>
	(tail call): ?
	[string "D:\games\Develop_Moose_q.lua"]:116432: in function <[string "D:\games\Develop_Moose_q.lua"]:116431>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "D:\games\Develop_Moose_q.lua"]:5826: in function <[string "D:\games\Develop_Moose_q.lua"]:5770>

**Comment by baluballa** [comment]
@shadowze , can you plz, when reporting, provide info so we can reproduce the error. Code, mission or like. Seem like you are expecting us to search for your errors.  Its like telling _"there is something wrong with this  Moose version, you must find out what"_.

**Comment by baluballa** [comment]
Many changes in SPAWN since  _2020-02-22_, However report is sparse. But likely its related to SpawnAtAirbase.

**Comment by shadowze** [comment]
[A2A_GCI_CAP_fucked.zip](https://github.com/FlightControl-Master/MOOSE/files/4332824/A2A_GCI_CAP_fucked.zip)

see if this helps work out what has been broken

**Comment by funkyfranky** [comment]
```
  local SpawnTemplate
  if self.TweakedTemplate ~= nil and self.TweakedTemplate == true then
    BASE:I("WARNING: You are using a tweaked template.")
    SpawnTemplate = self.SpawnTemplate
  else
    SpawnTemplate = self:_GetTemplate( SpawnTemplatePrefix )
    SpawnTemplate.name = self:SpawnGroupName( SpawnIndex )  -- This line was missing
  end```

**Comment by shadowze** [comment]
re-tested and confirmed fixed in commit ID
2020-03-14T19:35:03.0000000Z-e885557770afe1ce3f113f489b25f6a15e5d68e5

**Comment by Delta-99** [comment]
Good work guys.
