### ISSUE TITLE
ATC_GROUND PG

### ISSUE THREAD

**Issue by WarLord211** [FlightControl-Master/MOOSE#1291]
I had an issue with ATC ground on PG:
Cant land on Al_Dhafra_AB and Abu_Musa_Island_Airport without getting kicked.

After some research i think the error is in the definition of x and y for the runways.
The names from Al_Dhafra_AB and Abu_Musa_Island_Airport should be switched. 

i have checked the coordinates and the one form Abu_Musa_Island_Airport matches more them from Al_Dhafra_AB.
(I testet these via Mission Editor; with LALT+Y you can switch the coordinate system in the left corner)
![Screen_200315_161838](https://user-images.githubusercontent.com/10798954/76704357-b5f62d00-66d8-11ea-80e7-0a711cf83612.png)
Mouse was start of runway Abu_Musa_Island_Airport

Moose version was latest Dev version
( '*** MOOSE GITHUB Commit Hash ID: 2020-03-14T19:35:03.0000000Z-e885557770afe1ce3f113f489b25f6a15e5d68e5 ***' )

that would mean:
Line: 51281 = PersianGulf.Abu_Musa_Island_Airport
Line: 51300 = PersianGulf.Al_Dhafra_AB

i changed it for my self and it works now.

**Comment by baluballa** [comment]
Hum, wonder if this is related to issue #1264?
I will have a look. Hopefully we can apply your fix.

Wingthor.

**Comment by WarLord211** [comment]
yes is think so

**Comment by baluballa** [comment]
I wonder @WarLord211 can you send me your working version of Moose.lua. You can use discord if you are there... I am Wingthor.

**Comment by WarLord211** [comment]
i have send it to you via discord

**Comment by WarLord211** [comment]
Fixed ! thanks
