### ISSUE TITLE
CLIENT:Alive() not waiting

### ISSUE THREAD

**Issue by The-Scifer** [FlightControl-Master/MOOSE#1295]
In version 2.4.13, CLIENT:Alive( function ) doesn't wait for a client to be alive to execute its function.

```
local function plane_function( client )
  
  BASE:E( string.format('>>> Client is alive: %s', tostring( client:IsAlive() ) ) )
  
end

local plane_client = CLIENT:FindByName( 'Pilot #001' )
plane_client:Alive( plane_function( plane_client ) )
```

**Comment by funkyfranky** [comment]
A) There is not function :Alive(). You probably mean :IsAlive().
B) Functions dont "wait" do be execute. The are executed when you call them. You can use a scheduler to check if it is alive and then take actions as required.
C) Moose 2.4 is not supported any more. Please use 2.5 from the development branch.

**Comment by The-Scifer** [comment]
It is in Wrapper.Client#CLIENT:Alive().
MOOSE_DOCS/Documentation/Wrapper.Client.html##(CLIENT).Alive
```
--- Checks for a client alive event and calls a function on a continuous basis.
-- @param #CLIENT self
-- @param #function CallBackFunction Create a function that will be called when a player joins the slot.
-- @return #CLIENT
function CLIENT:Alive( CallBackFunction, ... )
  self:F()
  
  self.ClientCallBack = CallBackFunction
  self.ClientParameters = arg

  return self
end
```
It made me think it would act like a client-specific scheduler.

Thanks for your clarification about scheduler and version support.

**Comment by thebgpikester** [comment]
The wording might have related to the old event handler that has been bugged for 4 years, the "on enter unit", never seen a callback "Alive". EIther way this doesn't trigger/exist/work. I'll close, there are other ways to check if a client is alive, just ask in Discord when you've gotten a version of Moose made in the last two years! :)

**Comment by The-Scifer** [comment]
By the way, which branch would you recommend? v2.5.0pre1?
