### ISSUE TITLE
Patrol (and inheriting CAP and A2A_Dispatcher etc) uses AGL as a default altitude type

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#1297]
I've had three people say A2A_Dispatcher is broken and looking into each occasion, the DCS AI is flying stupid because it's trying to fly AGL rather than a barometric flight level. It might not have impacted combat until recently, but for now at least, the Dispatcher can give an engage order and the flight continues in a stupid direction, not engaging.
AGL now at least defaults to a max height of 1200M in the mission editor. I've also seen it impact BVR too. Either way It's my recommendation to make the default altitude "BARO" not "RADIO", which is a silly altitude type anyway and breaks DCS AI.
Because this has wider impacts, I just wanted to ask for thoughts... it goes into Patrol etc due to inheritence.

**Comment by thebgpikester** [comment]
https://github.com/FlightControl-Master/MOOSE/pull/1298

Looking through other places for this

**Comment by thebgpikester** [comment]
https://github.com/FlightControl-Master/MOOSE/pull/1299

Seems these were the only two places I could find that refer to defaulting altitudes to AGL. Anyone know of more?

**Comment by gunterlund** [comment]
totally agree with Pikes on this.

**Comment by timguy99** [comment]
I disagree if this affects other parts of Moose specifically AI_CAP and the like that I use and have used for years without these sort of issues.

The default should be left alone for backwards compatibility and the mission designer can change if they like. If there was no option to change then one should be added.

Again, any sort of changes that will potentially break TONS of missions out there should be made very carefully for backwards compatibility.

**Comment by shadowze** [comment]
I have used AI_A2A_GCICAP for years and it has worked fine, and do not get any issues like this
Will this impact my currently working missions ?
In the past some DCS patches have caused weird stuff eg planes trying to fly higher but going super slow BUT at the moment with this weeks DCS 2.5.6 patch all is working well, they are flying high enough and engaging people
Will this effect AI_A2A_GCICAP ?

**Comment by thebgpikester** [comment]
Right, but, there's a difference between changing something, and fixing something. I'm asking anyone to show where using the default altitude type as a waypoint actually "works" in the current game. This is the issue. DCS AI trying to "terrain follow" is horribly broken, regardless of whether or not it's default and by design. The aircraft basically cannot follow even a route, get's stuck in high alpha, won't engage and won't fly above a certain altitude. By default.
Just taking the AI_Patrol, the arguments include altitude settings that are effectively ignored since "RADIO" the default, is only working up to 1200M. That's never been documented and somewhere people are copying lines that dont include the optional parameter without understanding the problem. And I don't think anyone understands the problem else there would be more noise, all we get is "X is broken".
Also the default arguments for the methods that use this, break altitude, behaviour, tasks, combat, so, it's not valid as a "default", in my opinion, as the default breaks the intention of any mission designer, since they want a plane to behave by instruction and the default option does not allow that.

If there's a valid example of RADIO actually working with any patrol, in DCS then we do have an issue that has to be fixed by bringing the default out of AI_Patrol and into the dispatcher script where it inherits it from, but you need to test very carefully if that patrolling aircraft is actually working, because I'm saying it's broken.

**Comment by thebgpikester** [comment]
> 
> 
> I have used AI_A2A_GCICAP for years and it has worked fine, and do not get any issues like this
> Will this impact my currently working missions ?
> In the past some DCS patches have caused weird stuff eg planes trying to fly higher but going super slow BUT at the moment with this weeks DCS 2.5.6 patch all is working well, they are flying high enough and engaging people
> Will this effect AI_A2A_GCICAP ?

Bar from repeating myself, I can only ask, "Did you specify "BARO" or leave defaults when constructing your squadrons?"

**Comment by shadowze** [comment]
With my working AI_A2A_GCICAP 
I specify MSL 4000 for that plane start height of my AI template planes (late activated)  with one single waypoint with MSL 4000 set (to get them to start flying in the right direction when spawned)
I use airstart set to 1500m for them eg

	GCICAP_Red_modern = AI_A2A_GCICAP:NewWithBorder("EWR Red", "T Squadron Red", "BORDER Red", { "CAP Red 1", "CAP Red 2" }, 1, 6000,  60000, 150000)
	GCICAP_Red_modern:SetDefaultTakeoffInAirAltitude( 1500 )
	GCICAP_Red_modern:SetDefaultCapTimeInterval(30, 60)

**Comment by thebgpikester** [comment]
Can you share the full AI_A2A_GCICAP with some pointers on the miz so I can review how yours works but someone else's doesnt? When i say 'works', I mean the flights aren't flying up and down following the terrain and screwed for combat, which you say doesnt happen to you currently. Right now I only have the case of 3 things not working wherby changing this fixes it. I do not have any examples where the default is ignored and the flights fly straight and level.

**Comment by shadowze** [comment]
hold please, your call is important to us

**Comment by shadowze** [comment]
[A2A_GCI_CAP_demo_shadowze.zip](https://github.com/FlightControl-Master/MOOSE/files/4422353/A2A_GCI_CAP_demo_shadowze.zip)

**Comment by thebgpikester** [comment]
cheers, this is helpful, standby

**Comment by thebgpikester** [comment]
Yep you have it too in that miz. The reason you don't see affect too much is because of the air start and GCI nature means nothing is on "patrol", it spawns, fires and dogfights and RTB's without any patrolling - which is the class design of GCI. You start to see it when they have cleared the aircraft down. Then weird shit happens like in the picture, flying in completely the wrong direction, flying like drunk, etc.
![image](https://user-images.githubusercontent.com/22999891/78277694-cbf35280-750c-11ea-8bec-0b08ca20045c.png)
![image](https://user-images.githubusercontent.com/22999891/78277742-e2011300-750c-11ea-9c6c-4dd0bdc31b90.png)
So the net effect of the change would stop planes flying to Moscow as per image 2.

**Comment by thebgpikester** [comment]
THis one is off to moscow too, same mission, I just tabbed back in. Note the pegged AoA, low speed and headed in the wrong direction which is symptomatic of the "RADIO" default setting.
![image](https://user-images.githubusercontent.com/22999891/78278296-b9c5e400-750d-11ea-8d19-d0d6586bfd4d.png)

**Comment by shadowze** [comment]
I have never seen them head away out of the border zone like that before

**Comment by thebgpikester** [comment]
I dunno what they were supposed to be doing, but where I saw this before was "patrolling". Since your GCI doesnt reach patrolling before intercepting, they all shoot things down then do other things, which I guess include trying to migrate north.
unfortunately for NewWithBorder() you cannot specify "BARO" and you are stuck with "RADIO" so it will be forever borked until a moose change or using the Full AI_A2A_Dispatcher. But its a good example explaining why a change is required, all classes inherit patrol and the default is broken.

As for not seeing it before... it's DCS, I didnt see it before either, it's only come to light through investigation on newer issues. I'd suspect its a new DCS 2.5.6 issue tbh, but difficult to actually get data to prove that.

I'm not sure of all the classes inheriting patrol, but appreciate people telling me ones i've not used and possible issues. I still don't see how patrol can be workable with th edefault, it's prone to breaking like above, but also, they WONT ENGAGE in this state either.

**Comment by shadowze** [comment]
OK what they were supposed to do was fly around inside the large border zone looking for blue aircraft to attack
These ones are the **CAP** ones, there should be 2 of them only, did you edit the mission to add some blue planes flying into the detection zone? this would trigger the GCI ones?

**Comment by thebgpikester** [comment]
yes.

**Comment by shadowze** [comment]
post  the edited mission please

**Comment by thebgpikester** [comment]
![image](https://user-images.githubusercontent.com/22999891/78280465-0eb72980-7511-11ea-85d1-99dacf3fe150.png)
This is waiting for the patrol. The Su-27 went on patrol, pegged at high AoA, wouldnt engage and the incoming plane came and shot it down.
All you need to do is add two planes coming in, there's no change to the miz but here it is

[A2A_GCI_CAP_demo_shadowze.zip](https://github.com/FlightControl-Master/MOOSE/files/4422604/A2A_GCI_CAP_demo_shadowze.zip)

**Comment by shadowze** [comment]
tried it myself got 50 50, mig29 spotted the F16 engaged both killed one then got killed himself, DCS is random AF :-(

**Comment by APEXDCS** [comment]
You guys are awesome, keep up the good work.

**Comment by thebgpikester** [comment]
DCS/2.5.6.45915 (x86_64; Windows NT 10.0.18362)
Can you leave it to watch for patrolling, you can adjust the blue aircraft to appear later so that caps can establish. What you are looking for is a patrolling aircraft in a high AoA. If you don't see that after a few of them then I'm wondering wtf tbh.

**Comment by thebgpikester** [comment]
I've changed RADIO for BARO in nearly all cases in my own moose and I'm getting much better behaviour on AI across the board. Actually RADIO is the default for a lot of moose. The only places i dont want to touch it is helicopters routes. Whilst it doesnt 100% always break AI behaviour, it does sometimes and honestly over 2000ft there is no need to have planes wobbling up and down trying to nap of the earth at 20,000 feet and looking silly with the frequent AoA issues as a default behaviour. So I'll leave this here I've done my work on it and I'll be keeping the changes for myself.

**Comment by shadowze** [comment]
Can you post your modified moose file, I can try it out on our busy server and report back on how it goes under loaded conditions

**Comment by thebgpikester** [comment]
I've changed much more than was in scope and that would be bad to give you. The actual proposed changes are only to the two classes of patrol that all the dispatchers inherit from. The easiest way for you is to CTRL-F 'RADIO' and work through moose.lua and change to BARO in two locations offered at the top of the page. I really need a lot more time to understand the depth of the usage and see what might be impacted in a negative way. I cannot "think" of any, but doesnt mean to say there is not.

**Comment by thebgpikester** [comment]
Just updating this bug with searchable data

**People impacted and spending time since March 20 in #ai-a2a-dispatcher over this issue:**
myself,
Thorimus =BP=
Dawger
Redeye
gunterland
gamecockguy29
scarfur (jBg69)
shadowze(although didnt feel the effects of the symptoms) 
location that affect the default: Demo missions (copied from FC's demo) docs are ok.
modules that are not able to change the default: AI_A2A_GCICAP, possibly more
Searchable symptoms:
**scarfur (JBg69):** "it seems that the ejections happen more often on the red side. GCI radius etc. are the same values too. They Afterburn quite a lot too (90 % of flight time), wobbling around (maybe the ground lvl thing?) and loving an AOA of 17°"
**gamecockguy29:** "-The AI doesn't seem to engage, nor do they seem to scramble aircraft. The CAP patrols sometimes engage if they see the enemy visually, but never seem to be vectored onto hostile aircraft by the dispatcher. I have an aircraft group spawning and flying right through enemy territory and the Dispatcher doesn't seem to care. I've double- and triple-checked the template names, EWR naming scheme, etc. I've also made sure that the CAP areas are spaced out and the engagement ranges don't overlap.

-The CAP aircraft sometimes obey the parameters set in SetSquadronCap, but will sometimes climb far through the ceiling, and generally act drunk. Alternating between speedbrake and burner, yanking on the stick like it's a rodeo, and ignore everything else."

**Dawger** "I am seeing similar issues. A mission with no border zone built before 2.5.6 runs fine. The same mission saved in 2.5.6 has CAP units for both sides flying past each other and not engaging."

**Thorimus =BP=:** "for some reason CAP flights are flying around at 150-250 knots GS even though they're set to fly between 900-1100 kph
[19:14] Thorimus =BP=:
A2ADispatcher:SetSquadronCap( "VazianiSQ29", CAPZoneKuti, 6000, 10000, 900, 1100, 900, 1400, BARO )" --note no quoites on BARO made it default to RADIO

**Comment by funkyfranky** [comment]
Okay, merged your pull requests. Let's see how it goes.

**Comment by thebgpikester** [comment]
Partial success. For customers using the basic GCI (like dispatcher but all defaults preconfigured for less scripting lines) there is still an issue causing the same symptoms. I will cross link it, writing it now. of really want feedback on other use of Patrol than by the Air to Air classes. I dont think we might see any for a  year or more because whatever it is will be masked by DCS current issues with AI groups following waypoint comamnds differently and the lack of use generally which I can't see affecting much. Curious on helicopters mainly, if someone uses patrol in an unexpected way.

**Comment by Delta-99** [comment]
So, did this not really fix the problem? Waiting for cross linkage!!

**Comment by thebgpikester** [comment]
https://github.com/FlightControl-Master/MOOSE/issues/1305

So this fixes the issue with AI_A2A_Dispatcher but not fully on AI_A2A_GCICAP. The reason for that is that Dispatcher you can now no longer specify BARO and be forced to RADIO altitude which stops some behaviour and fixes some scenarios. But GCICAP has an additional setting of speed that cannot be edited/set either so the other bug for it, is that link above.
This particular specific issue is fixed though, but the problem is more with another class and another root cause. And wether its the high AoA or the low speed tha tcauses this, or the wobbling up and down (which is stupid anyway) or both at once... I don't really know, the controller just goes unresponsive sometimes and breaks it. THAT won't happen any more on Dispatcher unless you plug in stupid numbers.

**Comment by Delta-99** [comment]
This might be more of a DCS issue. I changed one of my missions long ago from A10's to F16's because no matter what I did with the A10's they were morons in the mountains. This was with DCS AI and not separate from Moose.

**Comment by thebgpikester** [comment]
Yes, this is fundamentally just a DCS issue. It's only solving that all patrol and inherited patrol actions in MOOSE use AGL as their way of holding altitude which is... retarded, looks retarded, and causes plane AI to spend too much time in afterburner going up and down at high altitude. I also think there is a conenciton with losing the controller of the group, but so far, it's really just a good cosmetic change for practical reasons. I think we can close, any issues can be looked into.

**Comment by Delta-99** [comment]
Fair enough. I assume one can "manually" still set AGL if they wanted to. Just defaulting to not be AGL correct? Most of my missions use AGL (even if it doesn't work to well) because I like planes hiding in the mountains.
