### ISSUE TITLE
Extend SET classes

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#130]
1. Operator overloading... It will allow to add or remove objects from the set using + or - operators....
2. Synchronous and asynchronous iterators... My previous implementation was based on coroutines, but unfortunately, DCS is not able to handle garbage cleaned coroutines... Dcs crashes when it believes there is still a coroutine alive from within their c++ code... So, I'll have to implement my own stack using tables... It'll work... Wait and see...
3. Enrich the methods with more unary functions where SETS can be integrated...
4. Improve the documentation and make example missions...

**Comment by baluballa** [comment]
Think its implemented.
