### ISSUE TITLE
SET_CLIENT doesnt refresh with FilterActive() and SET_PLAYER broken

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#1300]
Similar or related to https://github.com/FlightControl-Master/MOOSE/issues/682 but whereas SET_CLIENT should record clients, you would expect FilterActive() to remove the dead ones, right? Design? It doesnt, the clients keep incrementing so if you visit two slots, the count is 2 and goes up. But if you clear the SET it will repopulate correctly.

I tried SET_PLAYER. It was even stranger. It wouldn't accept FilterActive() or FilterCategories() (error) and when I asked the set for its members always gave me the UNIT name, but, the same unit even if I was in a different slot or in game master slot. However it did give the correct count. I would have expected the player name or an object. I just got a string of "a" unit name.

So, between both of them, you can't do something like count players that are in planes for example, even though it seems you should. The workaround is that you use SET_CLIENT and do Clients:Clear() 
  Clients:FilterOnce() in a schedule. Which is ... wrong, one or both SET's should have handled this computation of counting players (that are alive and in a slot).

**Comment by funkyfranky** [comment]
> you would expect FilterActive() to remove the dead ones, right?
No, not really, as per docs "@{#SET_CLIENT.FilterActive}: Builds the SET_CLIENT with the units that are only active. Units that are inactive (late activation) won't be included in the set!"

But it still filter dead and crashes as there is an event handler started when you run :FilterStart()

**Comment by thebgpikester** [comment]
I see. So FilterDeads() should be used instead of FilterActive() where clients are concerned. Let me get my shit together and present the way this should be done for counting active, oops wrong word!, ALIVE clients with a player, only ;)

**Comment by victorcotap** [comment]
@thebgpikester I'd be interested to know the final way of counting Alive client with a player only as well. Did you manage to get it to work ?

**Comment by funkyfranky** [comment]
Can we close this @thebgpikester `?

**Comment by thebgpikester** [comment]
sure, i never got around to following up with better code examples, which i was considering adding to the ticket, Discord will be better for that.
