### ISSUE TITLE
TaskInfo not updated prior to sorting for multi task mission menu setup

### ISSUE THREAD

**Issue by SteveLockeUK** [FlightControl-Master/MOOSE#1302]
Moose attempts to sort multi-task mission menu items by their distance from the player.
This sort is attempted before task info has been setup which means there is no coordinate data available and the sort fails.

It appears that the ReportOrder function is missing the necessary call to UpdateTaskInfo (which is present in ReportSummary).

By copying "self:UpdateTaskInfo( self.DetectedItem )" from ReportSummary to the start of ReportOrder I was able to get multi-task missions working as expected.

**Comment by funkyfranky** [comment]
Hi Steve, could you please provide a bit more info on this one?

**Comment by SteveLockeUK** [comment]
@funkyfranky  No problem.

I encountered an issue when attempting to create a BAI mission with multiple tasks.
When the DCS mission started the MOOSE command centre didn't appear to initialise properly (at least most of the menu items were missing or non-working).
If I tried a mission which only had one task everything worked as expected.

The DCS.log (extract below) pointed me to a call to `TASK_A2G:ReportOrder` from `MISSION:ReportSummary` in Moose. This was failing because the `TargetCoordinate` was not available.
I compared this to `Task:ReportSummary` because in a single task mission the BRA was displayed in the menu.
`Task:ReportSummary` contained the line `self:UpdateTaskInfo( self.DetectedItem )` which was missing from `TASK_A2G:ReportOrder`.
When I added this to the start of `TASK_A2G:ReportOrder` multi task missions worked as expected.

`
2020-04-05 16:39:11.720 INFO    SCRIPTING: Error in SCHEDULER function:[string "%LOCALAPPDATA%\Temp\DCS.openbeta/~mis00005183.lua"]:19467: attempt to index local 'TargetCoordinate' (a nil value)
2020-04-05 16:39:11.720 INFO    SCRIPTING: stack traceback:
    [string "%LOCALAPPDATA%\Temp\DCS.openbeta/~mis00005183.lua"]:6890: in function <[string "%LOCALAPPDATA%\Temp\DCS.openbeta/~mis00005183.lua"]:6886>
    [string "%LOCALAPPDATA%\Temp\DCS.openbeta/~mis00005183.lua"]:19467: in function 'Get2DDistance'
    [string "%LOCALAPPDATA%\Temp\DCS.openbeta/~mis00005183.lua"]:140392: in function 'ReportOrder'
    [string "%LOCALAPPDATA%\Temp\DCS.openbeta/~mis00005183.lua"]:136104: in function <[string "%LOCALAPPDATA%\Temp\DCS.openbeta/~mis00005183.lua"]:136104>
    (tail call): ?
    [C]: in function 'sort'
    [string "%LOCALAPPDATA%\Temp\DCS.openbeta/~mis00005183.lua"]:3081: in function 'spairs'
    [string "%LOCALAPPDATA%\Temp\DCS.openbeta/~mis00005183.lua"]:136104: in function 'ReportSummary'
    [string "%LOCALAPPDATA%\Temp\DCS.openbeta/~mis00005183.lua"]:135014: in function 'ReportSummary'
    [string "%LOCALAPPDATA%\Temp\DCS.openbeta/~mis00005183.lua"]:134480: in function <[string "%LOCALAPPDATA%\Temp\DCS.openbeta/~mis00005183.lua"]:134471>
    (tail call): ?
    [C]: in function 'xpcall'
    [string "%LOCALAPPDATA%\Temp\DCS.openbeta/~mis00005183.lua"]:7193: in function 'onEvent'
    [string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>
`

**Comment by thebgpikester** [comment]
This is from Discord on 5th April, general channel. I've never looked at the Report code before but it does seem from the way it's put, that multiple missions in the task do something. There are some distracting issues, like the EventHandler error at the bottom which makes me wonder if there is an older moose in play since that was charactersitic post 2.5.6. I would  really want the mission for this to get to the right lines because of moose versioning, DCS being a bit flakey, the complexity of Task in general and needing the right lines of moose without guessing (version changes etc). Now, it does sound like you fixed the issue Steve, in which case, is it possible for you to add that line to moose in your own branch and we can look at verifying it and putting it into a new dev version.

Is that possible please? I'm sure you ar eway ahead of understanding the issue at this point than myself at least.

**Comment by SteveLockeUK** [comment]
Mission file is attached. This uses my modified Moose.lua which includes my suggested fix so you'll need to swap this out in order to reproduce the issue.

I'd used the Moose version from the develop branch linked in the announcements channel in Discord on 2020-0217.

[Battle for the Gulf.zip](https://github.com/FlightControl-Master/MOOSE/files/4493554/Battle.for.the.Gulf.zip)

**Comment by funkyfranky** [comment]
Hi Steve, could you provide the code changes you did? I would like include your fixed in the Moose code but from the complete Moose.lua this is difficult to extract.

**Comment by SteveLockeUK** [comment]
@funkyfranky Added PR for the changes https://github.com/FlightControl-Master/MOOSE/pull/1310

**Comment by funkyfranky** [comment]
@SteveLockeUK PR merged.
