### ISSUE TITLE
AI_A2G_Dispatcher.lua#L4378: bad argument #3 to 'format' (number expected, got string) 

### ISSUE THREAD

**Issue by benedikt-wegmann** [FlightControl-Master/MOOSE#1303]
Hi!

Small error: 
https://github.com/FlightControl-Master/MOOSE/blob/d476922af2eeb3d31efd2b5314de96521f8a881b/Moose%20Development/Moose/AI/AI_A2G_Dispatcher.lua#L4378

If no `DefenderSquadron.ResourceCount` is set, formatting of the report causes an error in `dcs.log`:
```
bad argument #3 to 'format' (number expected, got string)
```

If replaced by ...
```lua
        Report:Add( string.format( "   - %s - %d", DefenderSquadronName, DefenderSquadron.ResourceCount and DefenderSquadron.ResourceCount or -1 ) )
```
... the error is averted, but I guess there is a better way. ;)

**Comment by funkyfranky** [comment]
Thanks Benedikt. I corrected this. Could you check and let us know if it works, please?

**Comment by funkyfranky** [comment]
No feedback so assuming this is now working.

**Comment by benedikt-wegmann** [comment]
Sorry for the lack of feedback, @funkyfranky ! I just got around to test it and it works (tested against the most recent `develop` branch. :+1:
