### ISSUE TITLE
AI_A2A_GCICAP - default speeds include (Veeerrrry slow)

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#1305]
**AI_A2A_GCICAP** (the abbreviated shorter version of the full Dispatcher class) creates patrols using the base Patrol classes and provides random speeds for those patrols. These random speeds are not configurable by the user. Over the last couple of months it's been noticed more (From February) _AI_A2A_Dispatcher_ users can configure these with SetSquadronCAP() and after they work out the kmph conversions tend to have realistic speeds that work. Sadly for **AI_A2A_GCICAP** users what we see is a lot of fast jet planes doing 150kts at 17 units of AoA and they are generally screwed and the **controller for the group starts to become unresponsive**. We will see 
- flying in one direction forever and ejecting
- no detection or engagement
It's as if the controller just gives up on a plane under these conditions. It's not immediately obvious how long it takes to happen. At this point oif the investigation I haven't looked at the code to find out how the random speed is determined.

STEPS TO REPRO
- I do not have them, I have a private mission from someone and other than that I'll just use a sample AI_A2A_GCICAP script on the demoes. Tends to affect higher altitude, hotter air as far as I know. 
Code:
```
RED_EWR_Dispatcher = AI_A2A_GCICAP:New({"RED EWR STATION"}, {"RED EWR ELEMENT"}, {"IRAN DEFENSE ZONE"}, 2)
REDBorderZone = ZONE_POLYGON:New("IRAN Border", GROUP:FindByName("IRAN Border"))
RED_EWR_Dispatcher:SetBorderZone(REDBorderZone)
RED_EWR_Dispatcher:SetDefaultTakeoffFromParkingCold()
RED_EWR_Dispatcher:SetDefaultLandingAtEngineShutdown()
RED_EWR_Dispatcher:SetDefaultFuelThreshold(0.70)
RED_EWR_Dispatcher:SetIntercept(10)
RED_EWR_Dispatcher:SetDisengageRadius(190000)
RED_EWR_Dispatcher:SetEngageRadius(100000)
RED_EWR_Dispatcher:SetGciRadius(150000)
RED_EWR_Dispatcher:Start()
```
As you can see...not much to tweak.

MITIGATION: Use the full AI_A2A_Dispatcher and write more lines. (sorry, no other way, AI_A2A_GCICAP is supposed to be fully automated and giving you good defaults.)

**Comment by thebgpikester** [comment]
https://github.com/FlightControl-Master/MOOSE/issues/1297 link - the AGLE default is fixed but speed is not.

**Comment by thebgpikester** [comment]
`local ToTargetSpeed = math.random( self.PatrolMinSpeed, self.PatrolMaxSpeed )`
which is from 
`self.PatrolMinSpeed = PatrolMinSpeed or SpeedMax * 0.5`
derived from
`local SpeedMax = AIGroup:GetSpeedMax()` 

So in effect the Patrol speed that we don't see set is derived from 50% of the max speed, which is derived from 
```
function UNIT:GetSpeedMax()
  self:F2( self.UnitName )

  local Desc = self:GetDesc()
  
  if Desc then
    local SpeedMax = Desc.speedMax
    return SpeedMax*3.6
  end

  return nil
end
```
3.6 is the conversion from metres per second

Next I need to look at some returns on their own to see if these are returning useful figures in case something changed.
It may just be the Route behaviour is at fault (more likely but harder to discern)

**Comment by Delta-99** [comment]
@thebgpikester I'm thinking that x 0.5 might be the issue. I'm guessing that some airframes just don't fly well at half max speed. Maybe that just needs adjustment.

Why is there a conversion to meters per second needed? I would think the values one is getting should be in the same units of measure but maybe I'm missing something.

**Comment by thebgpikester** [comment]
I don't think this value has been changed since implementation. The conversion is what Sven did, apparently he wanted to work in kmph rather than the returned mps, which makes sense if you are coding in it.
I did a basic test over the weekend and the returned values of getspeed max seemed valid for the first unit I tried. Its more likely to be something else, like DCS changing the task so that the input is now a different argument value... like for example, they changed mps to kmh or something, which would make them 3.6x slower. But that's just a guess. And it cannot be as simple because this isn't a universal issue, you can quite easily get normal flying planes.

**Comment by thebgpikester** [comment]
I haven't done any more work on this. Basically the summary is that when I set reasonable patrol speeds via othe rmethods, its fine and reprodcuing the slow speed is via a default that is in someway affected by plane type or DCS in general. I'll reopen when I can work on it or have more detail on reliable reproduction.

**Comment by thebgpikester** [comment]
[AID-A2A-020_-_GCI_RTB_and_ReEngage_ME_Edit(1).zip](https://github.com/FlightControl-Master/MOOSE/files/4914654/AID-A2A-020_-_GCI_RTB_and_ReEngage_ME_Edit.1.zip)
This mission shows that a 2019 version of moose works and a current one creates the issue. Same code, same DCS just moose different.
Reproduction:
1. You have to FF the mission until a Flanker is "GCI Returning" in the overview.
2. Watch him climb to over 30K feet MSL and peg his AoA

Expected: acts like the old version - no climbing, no AoA, no loss of control

No clues as yet as to why..

**Comment by thebgpikester** [comment]
![image](https://user-images.githubusercontent.com/22999891/87345636-438f3f80-c548-11ea-86f2-bebad9b47d50.png)
starts like this at 8k, with a little climb and descend. (no log entries at this point)
![image](https://user-images.githubusercontent.com/22999891/87345755-6a4d7600-c548-11ea-9168-195cd81d4bfa.png)
22k, he's still going up, levelling out, going up.
![image](https://user-images.githubusercontent.com/22999891/87345874-a41e7c80-c548-11ea-8543-318e9bd759c9.png)
At this point he's afterburner and 112kts and fuel eventually gets him

**Comment by Delta-99** [comment]
If you have the two GitHub hashes for the two versions of Moose we can take a look at the changes in the code. Something might be obvious but probably not.

**Comment by thebgpikester** [comment]
Spent the evening looking. I think I'm somewhere between 19th December and end of January as to working-notworking. Attached the last working one I found.
[MooseDec19.txt](https://github.com/FlightControl-Master/MOOSE/files/4915439/MooseDec19.txt)

The gitblames of that era dont really seem to show any "obvious" change.

So far what you need to do to see this:

Load up the mission attached a few posts above. Fast forward until the Flanker is returning as its state. You need to see a few instances to make sure. After a while of returning, the broken moose verison will start climbing from 6 thousand up to 30,000feet and getting really high AoA. That means that version of moose is "broken".

If you see the Flanker just flying level back the way, and it's consistent, then the moose is probably working OK. 

Swap versions around to verify the dates.
I keep coming back to this blame https://github.com/FlightControl-Master/MOOSE/commit/0bb0c70667ca059c135e922f88ad3c67e33457e8 as its in ballpark time and touches areas, but make sno sense to me.

**Comment by Applevangelist** [comment]
Might be this one, where RTB speed is set very low in AI_AIR.lua around line 608

    if not self.RTBMinSpeed and not self.RTBMaxSpeed then    
      local RTBSpeedMax = AIGroup:GetSpeedMax()
      self:SetRTBSpeed( RTBSpeedMax * 0.25, RTBSpeedMax * 0.25 )  
    end

**Comment by Delta-99** [comment]
I would say that could definitely be the issue. I'm not sure why the RTB speed needs changing at all. I would let the AI decide the speed they need to go unless somewhere in this process you definitely need to give them a speed setting (most likely).

Is there a cruising speed we can derive from somewhere? That would probably be best!!

Good find @Applevangelist

**Comment by Applevangelist** [comment]
for most modern era planes, probably >250 knots

**Comment by Applevangelist** [comment]
should probably be

if not self.RTBMinSpeed or not self.RTBMaxSpeed then    
  local RTBSpeedMax = AIGroup:GetSpeedMax()
  self:SetRTBSpeed( RTBSpeedMax * 0.5, RTBSpeedMax * 0.75 )  
end

**Comment by Applevangelist** [comment]
Tried your demo today but couldn't find it behaves the way you described, Maybe fixed with the last AI update in the beta. But since I was annoyed about the SUs scraping back at ground level and looked at the way the waypoint back to the airport ws calculated. I changed it to be simply 3000ft above the airbase, rather than a point on the ground 5km away from the airport and a calculation with an angle. See the attached mit for testing. SUs behaving better now, both RTB 
[AID-A2A-020_-_GCI_RTB_and_ReEngage_ME_Edit.1.zip](https://github.com/FlightControl-Master/MOOSE/files/5589354/AID-A2A-020_-_GCI_RTB_and_ReEngage_ME_Edit.1.zip)

speed wise and height.

**Comment by Applevangelist** [comment]
AI_AIR from line 595
```
--- Calculate the target route point.
    
    local FromCoord = AIGroup:GetCoordinate()
    local ToTargetCoord = self.HomeAirbase:GetCoordinate() -- coordinate is on land height(!)
    local ToTargetVec3 = ToTargetCoord:GetVec3()
    ToTargetVec3.y = ToTargetCoord:GetLandHeight()+1000 -- let's set this 1000m/3000 feet above ground
    local ToTargetCoord2 = COORDINATE:NewFromVec3( ToTargetVec3 )
     
    if not self.RTBMinSpeed or not self.RTBMaxSpeed then    
      local RTBSpeedMax = AIGroup:GetSpeedMax()
      self:SetRTBSpeed( RTBSpeedMax * 0.2, RTBSpeedMax * 0.5 )  
    end
    
    local RTBSpeed = math.random( self.RTBMinSpeed, self.RTBMaxSpeed )
    local ToAirbaseAngle = FromCoord:GetAngleDegrees( FromCoord:GetDirectionVec3( ToTargetCoord2 ) )

    local Distance = FromCoord:Get2DDistance( ToTargetCoord2 )
    
    --local ToAirbaseCoord = FromCoord:Translate( 5000, ToAirbaseAngle )
    local ToAirbaseCoord = ToTargetCoord2
```

**Comment by Delta-99** [comment]
`ToTargetVec3.y = ToTargetCoord:GetLandHeight()+1000 -- let's set this 1000m/3000 feet above ground`

I think just about everything in Moose is meters just like the DCS API. Although I'm not sure about coordinates!!!!

**Comment by thebgpikester** [comment]
can anyone confirm this is fixed? I have moved away from this class so dont know, but I liked the fix?

**Comment by Applevangelist** [comment]
Yes that’s fixed

**Comment by funkyfranky** [comment]
Thanks guys!
