### ISSUE TITLE
TASK_CARGO_DISPATCHER Details about successful tasks comes up after task is successful

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#1312]
Details about successful tasks comes up after task is successful and player has joined another task.

![image](https://user-images.githubusercontent.com/7481653/80289537-45aee280-873f-11ea-9d65-bfe33aa6faf0.png)

Reported by Kappa in discord channel. Screenshot is from his mission.

**Comment by Applevangelist** [comment]
Same as #1383 - see workaround there
