### ISSUE TITLE
Error when no matching event found

### ISSUE THREAD

**Issue by chump29** [FlightControl-Master/MOOSE#1316]
https://github.com/FlightControl-Master/MOOSE/blob/dc4115d4e3cb5c7f90cc77f8def588e6209f9e01/Moose%20Development/Moose/Core/Event.lua#L1160

Cannot access Text property of undefined EventMeta when event is not pre-defined.

Maybe something like:
`self:T( { "UNDEFINED", Event } )`

**Comment by thebgpikester** [comment]
I think i'm too stupid to understand the problem. Where did the EventData come from, what handler and what is a predefined event? and an undefined EventData? Could this be explained with a bit more code and an expected return and the actual return please?

**Comment by chump29** [comment]
Let me see if I can explain it better. In EVENT:onEvent():829, there is a table lookup done against _EVENTMETA. If the event is not defined, such as S_EVENT_LANDING_AFTER_EJECTION (or other new events that DCS adds periodically that the code is not set up to handle yet), it sets the local EventMeta to nil. Since there is not event that matched the incoming ID, it skips to the ELSE at line 1159. The EventMeta.Text is part of the trace, which causes an error due to accessing a property on a nil parent object. To correct this, I would suggest using a constant/string to pass to the trace instead of the possibly nil EventMeta object, hence the "UNDEFINED" in my code snippet. I hope this helps.

**Comment by funkyfranky** [comment]
Are you referring to the master branch @chump29 ?
Because this should be fixed in the develop branch.

**Comment by chump29** [comment]
I was looking in **master**, not **develop**. I see that you've completely refactored it. 👍 
I only noticed the other day when messing with ATIS in _v2.5.0 pre-release_. Great stuff, sorry to report a resolved issue.
