### ISSUE TITLE
AIRBOSS: SuperCarrier early break-fixes

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#1328]
Super Carrier release immediate fixes pending:

```
--- Carrier types.
-- @type AIRBOSS.CarrierType
-- @field #string ROOSEVELT USS Theodore Roosevelt (CVN-71)
-- @field #string LINCOLN USS Abraham Lincoln (CVN-72)
-- @field #string WASHINGTON USS George Washington (CVN-73)
-- @field #string STENNIS USS John C. Stennis (CVN-74)
-- @field #string VINSON USS Carl Vinson (CVN-70)
-- @field #string TARAWA USS Tarawa (LHA-1)
-- @field #string KUZNETSOV Admiral Kuznetsov (CV 1143.5)
AIRBOSS.CarrierType={
  ROOSEVELT="CVN_71",
  LINCOLN="CVN_72",
  WASHINGTON="CVN_73",
  STENNIS="Stennis",
  VINSON="VINSON",
  TARAWA="LHA_Tarawa",
  KUZNETSOV="KUZNECOW",
}
```
  -- Init carrier parameters.
  if self.carriertype==AIRBOSS.CarrierType.STENNIS then
    self:_InitStennis()
  elseif self.carriertype==AIRBOSS.CarrierType.ROOSEVELT then
    self:_InitStennis()
  elseif self.carriertype==AIRBOSS.CarrierType.LINCOLN then
    self:_InitStennis()    
  elseif self.carriertype==AIRBOSS.CarrierType.WASHINGTON then
    self:_InitStennis()
  elseif self.carriertype==AIRBOSS.CarrierType.VINSON then
    -- TODO: Carl Vinson parameters.
    self:_InitStennis()
  elseif self.carriertype==AIRBOSS.CarrierType.TARAWA then
    -- Tarawa parameters.
    self:_InitTarawa()
  elseif self.carriertype==AIRBOSS.CarrierType.KUZNETSOV then
    -- Kusnetsov parameters - maybe...
    self:_InitStennis()
  else
    self:E(self.lid..string.format("ERROR: Unknown carrier type %s!", tostring(self.carriertype)))
    return nil
  end
```

PLUS an as yet unidentified size change to the deck and grading changes.

This is not a complete list; design changes to AIRBOSS are to be properly assessed post release.

**Comment by thebgpikester** [comment]
actually this probably misses the new 1143/old 1143, but unsure if Airboss is interested in them, it might be good for carrier control.

**Comment by funkyfranky** [comment]
I don't quite understand. This is already included. Basic SC support is there, no? At least the SC will be recognized by the AIRBOSS script.

**Comment by thebgpikester** [comment]
I didn't check if you included the code, I presumed you didn't because it's not released, but that's fine, I'll close.
