### ISSUE TITLE
AIRBASE: Remove dead ships from the Database

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#1329]
Not sure the best way. Any automated task refering to a dead ship does cause an error but I cannt get a crash as suspected, either way, it woudl be a good idea to handle dead ships as I can get some interesting messages once sunk.

**Comment by funkyfranky** [comment]
Ships (and FARPs) are not removed from the DB and from SET_AIRBASE if a Destroy event is triggered. Pls check.

**Comment by Delta-99** [comment]
@thebgpikester was this tested? Can we close it?

**Comment by funkyfranky** [comment]
Ah, yeah, when I wrote "Ships (and FARPs)" are **not** removed...", I meant "Ships (and FARPs)" are **now** removed...".

**Comment by thebgpikester** [comment]
I will self close as fixed
