### ISSUE TITLE
Documentation problem with A2ADispatcher:SetSquadronRefuelThreshold()

### ISSUE THREAD

**Issue by Goreuncle** [FlightControl-Master/MOOSE#1331]
The method _:SetSquadronRefuelThreshold()_ for **AI_A2A_DISPATCHER** doesn't seem to exist (please, do correct me if I'm wrong).

Yet it's mentioned in the documentation (and the IntelliSense description) for _AI_A2A_DISPATCHER:SetSquadronFuelThreshold()_

It's referenced twice in the latest 2.5.0 stable Moose.lua, lines 116612 and 116569

**Comment by thebgpikester** [comment]
seems so :)
I could delete it from comments but I don't know it's story or what should be there instead. ANy ideas?

**Comment by zlinman** [comment]
simply add: not working atm (or something like this...)

**Comment by thebgpikester** [comment]
Non existent would be better i think :)

There once was a man called Sven
Who would write code, don'tcha know, now and then
He wrote the Air Dispatcher,
Ugly as Margaret Thatcher,
Now I've gone and lost my Zen :(

(sorry been drinking)

**Comment by Delta-99** [comment]
> Non existent would be better i think :)
> 
> There once was a man called Sven
> Who wrote code, don'tcha know, now and then
> He wrote the Air Dispatcher,
> Ugly as Margaret Thatcher,
> Now I've gone and lost my Zen :(
> 
> (sorry been drinking)

LOL, what a comment!!! Just going through some of the issues to clean things up somewhat and missed this gem from back then!!!!
