### ISSUE TITLE
Event.Dead error

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#1332]
When a unit is killed and there is an event.dead capture you get a log error stating
6997: attempt to index local 'EventMeta' (a nil value) in function 'onevent'

you can reproduce this is mission EVT-205 for simplicity sake. When unit in group A is killed error in log appears.

**Comment by funkyfranky** [comment]
That mission is working fine.

Also "EventMeta nil" sounds very much like an old Moose.lua version.

![image](https://user-images.githubusercontent.com/28947887/82765844-95ee9280-9e1a-11ea-8ec4-c84fcb405547.png)

**Comment by gunterlund** [comment]
Garghh!!!!!!!! your right my bad... all of mydemo missions have the old lua. I did a pull from Development of the missions just recently. Are they not getting updated with the new Lua?

**Comment by gunterlund** [comment]
Not a bug. Bad Moose.lua in mission
