### ISSUE TITLE
ATC_Ground - Text only in KM/H

### ISSUE THREAD

**Issue by WarLord211** [FlightControl-Master/MOOSE#1336]
Hi 
im using ATC_Ground to catch our racers on the taxi ways :)

it would be nice if the text that says the Max Speed were not only in KM/h, rather also in Knots.
or depending how you set the Max speed.

**Comment by FlightControl-User** [comment]
Ok. I will check that...




Get Outlook for Android







On Sun, Jun 21, 2020 at 10:05 AM +0200, "Sven" <notifications@github.com> wrote:















Hi

im using ATC_Ground to catch our racers on the taxi ways :)


it would be nice if the text that says the Max Speed were not only in KM/h, rather also in Knots.

or depending how you set the Max speed.

**Comment by Applevangelist** [comment]
It's already there. Output is dependent on the settings you take, see e.g. https://flightcontrol-master.github.io/MOOSE_DOCS/Documentation/Core.Settings.html##(SETTINGS).SetMetric
add _SETTINGS:SetImperial() to display different than km/h
