### ISSUE TITLE
LDT Project Setup Issue/Docs Innacurate?

### ISSUE THREAD

**Issue by clairmont32** [FlightControl-Master/MOOSE#1339]
Hello,

I installed LDT and downloaded the source code zip and extracted it to where I wanted it but there's seemingly no moose.lua or moose_.lua files as described in [Moose_Setup_Guide](https://flightcontrol-master.github.io/MOOSE_DOCS/Moose_Setup_Guide.html). I have a handful of folder directories and pointing the LDT doesn't like when I try to point the workspace to the top level MOOSE-2.5.0 directory.

What am I doing incorrectly? Should I only have the moose.lua file in the workspace instead of the 2 files above?

Thank you for the level of documentation of the functions the framework has!!!

**Comment by thebgpikester** [comment]
Please ignore that older documentation its over 5 years old and part of something we cannot undo easily. 
https://github.com/FlightControl-Master/MOOSE_GUIDES
theres a video link that ive tested recently in the main user guide.
User guide is linked in #info in our Discord, ask any basic questions there. 
Thanks!
