### ISSUE TITLE
Duplicate Conditional Statement?

### ISSUE THREAD

**Issue by clairmont32** [FlightControl-Master/MOOSE#1341]
Hey guys, was wondering if this `if GenerateEvent and GenerateEvent == true then`  was really a duplicate statement since it appears to be checking for a true statement twice.

https://github.com/FlightControl-Master/MOOSE/blob/master/Moose%20Development/Moose/Wrapper/Positionable.lua#L105

**Comment by funkyfranky** [comment]
Well, the first statement checks if GenerateEvent is not nil. So it is a bit redundant but it does not hurt.
