### ISSUE TITLE
SPAWN, Aircraft Callsign number always remains one.

### ISSUE THREAD

**Issue by Mechanist11** [FlightControl-Master/MOOSE#1343]
Hello, long time no see :D

Found a bug in Moose 2.5 that which was worked well on 2.4.13

Callsign like Texaco41 cannot be achived with spawning will always end up in Texaco11. Moose 2.5.0 stable

Example:
This is the section in template that defines the callsign, lets look at a Tanker:
	["callsign"] = 
	{
		[1] = 1, -- Texaco
		[2] = 4, -- 4
		[3] = 1, -- 1
		["name"] = Texaco41,	
	},

But instead of 4-1 it will spawn as 1-1.

Other parmeters like [1] and [3] can be changed and works OK.

Enclosed screenshots for further clarification. The difference is only the Moose version.

![M2_5](https://user-images.githubusercontent.com/19891419/89937278-26b45d80-dc15-11ea-8ff8-66fdd01e93fe.jpg)
![M_2_413](https://user-images.githubusercontent.com/19891419/89937285-2ae07b00-dc15-11ea-90af-aff0ae50377e.jpg)

**Comment by Mechanist11** [comment]
I actually find the code that makes this bug:

Version 2_5_1 stable:
it is in SPAWN:_Prepare( SpawnTemplatePrefix, SpawnIndex )

if you comment out this

Callsign[2] = ( ( SpawnIndex - 1 ) % 10 ) + 1

It will work as before.

**Comment by funkyfranky** [comment]
Thanks, will take a look!

**Comment by Delta-99** [comment]
What is that code supposed to be attempting to do? Just make sure a Callsign is always between 1-9 or 0-9 I think? Additionally I'm not sure why it is written that way as I think you get the exact same with SpawnIndex % 10.

In any event I can't see that as causing an issue until someone attempts to go above 10. So anything below 10 should work just like before or without the line at all.

**Comment by funkyfranky** [comment]
I think the code is meant to prevent that multiple spawned tankers get the same callsign. Which will be confusing in the F10 menu. So it's not really a bug. More a feature that needs to be improved.

**Comment by madmoney99** [comment]
Franky, I put this snippet in the spawn channel (pinned by Delta) which makes it so the callsigns are assigned correctly. 

```lua
local dogTrack_1 = SPAWN
:New("Dog Track 1")
:InitLimit(1,0)
:InitRepeatOnLanding()
:OnSpawnGroup(
  function (shell_11)
  shell_11:CommandSetCallsign(3,1)//the second variable sets the flight number, in this case Shell 1-1.  
  shell_11:CommandSetFrequency(296.425)
  local sh11Beacon = shell_11:GetBeacon()
  sh11Beacon:AATACAN(59, "DTH", true)
  end
  )
:SpawnScheduled(60,0)```

TonyG

**Comment by funkyfranky** [comment]
Thanks for pointing this out @madmoney99 (Tony)! I think to use `:OnSpawnGroup()` is indeed the best option if a specific callsign is desired.

The current implementation does not use the value of the template unit for the first number but rather resets this to one and increases it with every spawned taker. As I mentioned above, this is normally a good thing when you spawn multiple tankers so the radio menu is not ambiguous.

I'd say this there is no real issue as the callsign can be set to whatever the mission designer wants. Would you agree @Mechanist11 ? If so, we can close this.

**Comment by Delta-99** [comment]
My point was about that single line of code vs the entire function. I get what the entire piece of code is attempting to do just not that line. I think I do see how it can break things if NOT taken out but also agree it is working as designed.

As the mission designer has other options to resolve this I believe this should be left as is and closed.

**Comment by Mechanist11** [comment]
@funkyfranky 

I'm woking with a code that is creating random callsigns for my spawnd planes.

Like this one:

`	UTG_CallsignFormat = 
		{
			[1] = tonumber(UTG_UnitSource["callsign_name_number"]),
			[2] = tonumber(UTG_UnitSource["callsign_number"]),
			[3] = tonumber(UTG_Current_Group_Unit_Integer),
			["name"] = UTG_UnitSource["callsign_whole"],
			
		}`

So lets say it will crete like this one:

Acro41
[1] = 2
[2] = 4
[3] = 1

But the original script will change it to this one:

Acro11
[1] = 2
[2] = 1
[3] = 1

As this code is base on SpawnIndex and that will be 1 of the first plane of the first group:

Callsign[2] = ( ( SpawnIndex - 1 ) % 10 ) + 1

This will result in 1

Maybe it would be also good tho not chane the Callsign[2] but the Callsign[3]?

So consecutive spawns would look like this:

Acro41
[1] = 2
[2] = 4
[3] = 1

Acro42
[1] = 2
[2] = 4
[3] = 2

Acro43
[1] = 2
[2] = 4
[3] = 3

Or make it at least optional?

**Comment by funkyfranky** [comment]
@Mechanist11 
yes, the current implementation will change the callsign. but you can overrule that with the :OnSpawnGroup function and set any callsign you like as @madmoney99 described above. So that gives you the possibility to create your random callsigns.

**Comment by Mechanist11** [comment]
@funkyfranky  Thanks for the explanation, I used  @madmoney99 's workaround and worked well. I was just confused why it wasn't working as on 2.4.13. Anyhow I'll keep in mind this one. Issue can be closed. Thank for the support!

**Comment by funkyfranky** [comment]
Thanks for the feedback. Enjoy your refueling :)
