### ISSUE TITLE
AI_FORMATION broke between dec 2019 and now

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#1344]
2019-12-30T23:45:40 date last known working
[Formation_Moose_2_5.zip](https://github.com/FlightControl-Master/MOOSE/files/5084908/Formation_Moose_2_5.zip)
[Formation_Moose_old.zip](https://github.com/FlightControl-Master/MOOSE/files/5084910/Formation_Moose_old.zip)

Same mission and script, but with new moose nothing happens and the planes RTB. Something seriously happenend last christmas ;)
refence Code used in demo:
```
local FollowGroupSet = SET_GROUP:New():FilterPrefixes("Follow"):FilterStart()
local number = FollowGroupSet:Count()
env.info(number)
FollowGroupSet:Flush()
local LeaderUnit = UNIT:FindByName( "Leader" )
local LargeFormation = AI_FORMATION:New( LeaderUnit, FollowGroupSet, "Left Line Formation", "Briefing" ):TestSmokeDirectionVector(true)
LargeFormation:FormationLeftLine( 0, 0, 100, 40 ) --(erachter,erboven,ernaast,afstand tot de volgende (alles in meters maar lijkt eerder op feet))
LargeFormation:__Start( 1 )
```
No errors shown.

**Comment by funkyfranky** [comment]
Sven changed something. You now need to add
AI_FORMATION:SetFlightModeFormation( FollowGroup )

**Comment by Delta-99** [comment]
Can this be closed @funkyfranky @thebgpikester ?

**Comment by thebgpikester** [comment]
yep, the doc issue part is minor. More me.

**Comment by brettswift** [comment]
@thebgpikester I'm not sure how you fixed this.  It still won't work for me. 

Is that what you set?    With the code below planes are still RTB

```

local FollowGroupSet = SET_GROUP:New():FilterCategories("plane"):FilterCoalitions("blue"):FilterPrefixes("Follow"):FilterStart()
FollowGroupSet:Flush()
local LeaderUnit = UNIT:FindByName( "Leader" )
local LargeFormation = AI_FORMATION:New( LeaderUnit, FollowGroupSet, "Trail Formation", "Briefing" )
LargeFormation:FormationBox(150,120,0,-5,0,60,8)

LargeFormation:SetFlightModeFormation(FollowGroupSet)  -- not in the mission examples

LargeFormation:__Start( 1 )

collectgarbage()


```

**Comment by funkyfranky** [comment]
Try `LargeFormation:SetFlightModeFormation()`, i.e. without a parameter. If you pass a paramter it has to be a GROUP object not a SET_GROUP object.

**Comment by brettswift** [comment]
Thanks - that didn't work - they still RTB. 

Also tried: 
```
FollowGroupSet:ForEachGroup(
    function( theFollowGroup )
      LargeFormation:SetFlightModeFormation(theFollowGroup)
    end
)
```
