### ISSUE TITLE
IDEA for assigning separate targets for MY flight of 3 AI wingmen

### ISSUE THREAD

**Issue by Saint185th** [FlightControl-Master/MOOSE#1346]
Is it possible using MOOSE scripting to assign separate Preplanned targets to each member of **MY** flight during a bombing mission. 

### Here`s how I would envisage it should work

Using the ME I assign 1 target at waypoint x, I find 3 extra targets 1 for each member. I use the coordinates of the 3 targets from the ME. Load these coordinates into the **COORDINATE: GetVec2()** script as target locations. Then use the **EVENT:OnEventDead()** to dynamically switch targets using **UNIT:TaskAttackMapObject(Vec2, GroupAttack, WeaponExpend, AttackQty, Direction, Altitude, Weapon Type)** for the other flight members based on what’s destroyed. If a target was missed, that target would still be assigned until its dead and the OnEventDead () would switch to the next target.They would drop all their bombs in one pass, but not attack as a group. 

The other way maybe use **AI.AI_BAI module**, set up 3 zones with the center of each zone at the target locations and switch the search off??

**Comment by funkyfranky** [comment]
Not possible unfortunately due to DCS game restrictions. This is more a feature request to ED.
