### ISSUE TITLE
AIB-007 Spawn bug is back, or never went away. ???

### ISSUE THREAD

**Issue by 1noob4ever** [FlightControl-Master/MOOSE#1351]
This is not a new issue.
https://github.com/FlightControl-Master/MOOSE/issues/803

This seems to still be an issue with AI_Balancer, specifically AIB007. Any base that has more than one client then it will attempt to spawn multiple non client aircraft on top of one another then explode. Rinse repeat. I want to note also that the other night I was flying a multiplayer i'm pretty sure the author was using MOOSE and i noticed that ground units were spawning on top of each other. Pretty weird at first when i saw a hybrid Shilka_T-80 tank. This was repeated in all of the little platoon size groups.

**Comment by Delta-99** [comment]
Ah, reading back on issue #803 this is usually something that ED breaks in an update. So at any point in an update this could start operating normally again. Will test AIB007 when I get a chance but likely there isn't much that can be done in Moose to prevent this.

**Comment by funkyfranky** [comment]
This is an issue how the SPAWN object is set up. The example mission is not up to date. One needs to add `:InitAirbase()` to all spawns, e.g.
```RU_PlanesSpawn[1]=SPAWN:New("RU CAP Anapa AB"):InitCleanUp(45):InitAirbase(AIRBASE.Caucasus.Anapa_Vityazevo)```

**Comment by Delta-99** [comment]
Sigh, pain in the ass. I will hopefully find some time to fix the demo mission then. Leave this one assigned to me I guess.

**Comment by funkyfranky** [comment]
No feedback ==> closing
