### ISSUE TITLE
GROUP:IsAirborne(true) reports true when any unit of group is in the air.

### ISSUE THREAD

**Issue by Amarok73** [FlightControl-Master/MOOSE#1354]
Hello, 
I'd like to report that the GROUP:IsAirborne(true) is behaving not as described in the documentation. Instead of reporting 'true' when all units consisting the group are in the air, it reports true when first unit from the group is airborne.
In attached mission, there's the script WTG_Respawner.lua that contains `SpawnGroup:IsAirborne(true)` for four CVN based groups, and is supposed to report only when whole group is in the air, but instead it shows the message as soon as first unit depart as well, as second one. 
The same effect is when the group is based on the ground airfield. 

[Welcome to Georgia 17_8.miz.zip](https://github.com/FlightControl-Master/MOOSE/files/5363681/Welcome.to.Georgia.17_8.miz.zip)

**Comment by funkyfranky** [comment]
Thanks. Will fix.

**Comment by funkyfranky** [comment]
Did you have a chance to test with the latest built @Amarok73 ?

**Comment by funkyfranky** [comment]
Guess this is fixed. Reopen if not.

**Comment by Amarok73** [comment]
Sorry for delay, I've just checked it now and it work properly. Thank You!

**Comment by funkyfranky** [comment]
Thanks for the feedback!
