### ISSUE TITLE
SEAD evasion script - Feature Request

### ISSUE THREAD

**Issue by qwertymanisalive** [FlightControl-Master/MOOSE#1355]
https://github.com/FlightControl-Master/MOOSE_MISSIONS/tree/master/SEV%20-%20SEAD%20Evasion/SEV-001%20-%20SEAD%20Evasion

The script works well and is easy to implement in a mission. One feature that would enhance it would be the ability to dial back the kill zone of the SAM units to a % of the kill zone. In other words if a SAM unit takes a shot a 10 miles (100%), the mission designer would have the ability to have the SAM unit go live at 8 miles (80%) and take the shot. 

This is one of the features of Skynet that makes it deadly. 

https://github.com/walder/Skynet-IADS/blob/master/README.md

**Comment by thebgpikester** [comment]
This is pointless as there is shortly going to be a feature in DCS for this directly.
I'd recommend looking at this in November and seeing if it can be developed on.

**Comment by Delta-99** [comment]
Are you saying @thebgpikester to leave this open and re-evaluate in Nov once these changes from ED are out? I can see them attempting to do something but it not working anywhere nearly well enough or like anything that SEAD or other scripts provide!!!

So time will tell.

**Comment by thebgpikester** [comment]
If it arrived, I would expect this to eventually hit the CONTROLLABLE class as an option. Let's say something like CONTROLLABLE:SamEngageRange(%) which means take a SET of SAM's and apply that option with a ForEachGroup() and you could cut the code down.
Remain positive. I am very positive about this being in the game one day.

**Comment by Applevangelist** [comment]
It's in the game now, right? https://wiki.hoggitworld.com/view/DCS_option_engagementRange

**Comment by thebgpikester** [comment]
Oh look at that, its almost like I could see it coming in development but couldnt say anything about it because of a reason I coudlnt mention and ... urgh, this is tough.
I think Frank picked up on this a while back though when it hit live.

**Comment by Delta-99** [comment]
Wow, its like @thebgpikester is some sort of psychic!!!!

Thanks for updating this @Applevangelist
