### ISSUE TITLE
Func_Arty - extend function to detect timeout when firing

### ISSUE THREAD

**Issue by Applevangelist** [FlightControl-Master/MOOSE#1356]
Noticed artillery can get stuck in FSM state firing, and then target is not removed from queue if number of shots fired isn't zero. Request to change

in function ARTY:_CheckShootingStarted()

change the check to
    -- Check if we waited long enough and no shot was fired.
    if dt > self.WaitForShotTime and (self.Nshots==0 or self.currentTarget.nshells >= self.Nshots) then

thanks

**Comment by Applevangelist** [comment]
Wow that was quick!Thanks! :)

**Comment by funkyfranky** [comment]
Was easy as you already provided the fix :)
Good job!
