### ISSUE TITLE
Func_Arty - avoid spamming DCS log

### ISSUE THREAD

**Issue by Applevangelist** [FlightControl-Master/MOOSE#1357]
DCS log is spammed with Status entries from Arty, coming from the function

function ARTY:onafterStatus(Controllable, From, Event, To)

Change the part under ---FSM state to

  -- FSM state.
  local fsmstate=self:GetState()
  if self.Debug then
    self:I(self.lid..string.format("Status %s, Ammo total=%d: shells=%d [smoke=%d, illu=%d, nukes=%d*%.3f kT], rockets=%d, missiles=%d", fsmstate, ntot, nshells, self.Nsmoke, self.Nillu, self.Nukes, self.nukewarhead/1000000, nrockets, nmissiles))
  end

thanks

**Comment by Applevangelist** [comment]
Wow that was quick!Thanks! :)

**Comment by funkyfranky** [comment]
Thanks for the report!
