### ISSUE TITLE
AI:Formation is broken 

### ISSUE THREAD

**Issue by brettswift** [FlightControl-Master/MOOSE#1358]
This: #1344 was opened, but it's still not working for me. 

In 2.5.1 I've downloaded the Include_static moose.lua file, and loaded up any of the test missions  - the follow group will just do a 180 and RTB.

I've also tried using the MOOSE_INCLUDE (static) file from https://github.com/FlightControl-Master/MOOSE_INCLUDE/tree/234cf3ee3fc3dc6693ccf267ef99961abc170bf6/Moose_Include_Static

Neither of these work.

**Comment by funkyfranky** [comment]
I consider this fixed as the demo mission I ran work again.
