### ISSUE TITLE
SET_GROUP:New():FilterCoalitions Takes String Instead of a #coalition

### ISSUE THREAD

**Issue by clairmont32** [FlightControl-Master/MOOSE#1359]
Hi,

In version 2.5.1, line 1152, we have SET_GROUP:New():FilterCoalitions(self, coalition) but the docs indicate this takes a string with valid options of `"red", "blue", "neutral"`. Since we have `coalition.side.blue|red|neutral` would it make more sense to change the argument type to these constants?

Thanks for all the work you guys do!

**Comment by funkyfranky** [comment]
It would make more sense and would be more universal especially if at some point ED decides to add more coalitions to the game.

However, if this were changed, a lot of existing (user) code would break and therefore this is not gonna happen.

Thanks for your feedback!
