### ISSUE TITLE
Ops.Flightgroup - group:GetSpeedMax() may return nil, which isn't caught causing calc error below

### ISSUE THREAD

**Issue by Applevangelist** [FlightControl-Master/MOOSE#1363]
Hi

got a couple of cases where I got an error for the self.speedCruise below, reason is that GetSpeedMax may return nil sometimes.
Around line 2600:

```
  -- Max speed in km/h.
  self.speedMax=group:GetSpeedMax()

  -- Cruise speed limit 350 kts for fixed and 80 knots for rotary wings.
  local speedCruiseLimit=self.ishelo and UTILS.KnotsToKmph(80) or UTILS.KnotsToKmph(350)

  -- Cruise speed: 70% of max speed but within limit.
  self.speedCruise=math.min(self.speedMax*0.7, speedCruiseLimit)
```

**Comment by funkyfranky** [comment]
Hmm, if GetSpeedMax returns nil that means that all of the units are dead when the FLIGHTGROUP is created. I could cure the symptoms by adding a nil check. But it would be much better to understand under which circumstances this happens. Do you have some example?

**Comment by Applevangelist** [comment]
Sure. I have a CAP-Auftrag which I can call per user menu. If the user calls again, I check if some units are still alive from the Group, if they are not, I'll allow create a new Auftrag after 30 seconds. In the logs I can see that the Auftrag failed:
2020-11-03 09:33:28.260 INFO    SCRIPTING: 117632(117526)/I:                       AUFTRAG07388.Evaluate(Auftrag #2 CAP | Evaluating mission:
Own casualties = 2/2
Own losses     = 100.0 
--------------------------
Targets left   = 0/0
Targets life   = 1.0/1.0
Enemy losses   = 0.0 
--------------------------
Success Cond   = false
Failure Cond   = false
--------------------------
Final Success  = false
=========================)

Thus I can hit the menu to create a new one, then error appears:

2020-11-03 09:38:25.420 ERROR   SCRIPTING: Mission script error: [string "C:\Users\Thomas\AppData\Local\Temp\DCS\/~mis00002F51.lua"]:127284: attempt to perform arithmetic on field 'speedMax' (a nil value)
stack traceback:

which traces back to my function. Now, from a timing perspective I'd think that the whole object would be cleaned up by then and not create an issue after 5 mins still? From what I see currently in the logs, the error doesn't appear each time, so I thought fetching SpeedMax from the DCS Object just sometimes fails...

**Comment by Applevangelist** [comment]
Need to add the the Auftrag is assigned to a Flightgroup, not an Airwing
