### ISSUE TITLE
error in function -  OPSGROUP:onafterLaserResume(From, Event, To)

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#1364]
like previous bug when lasing coords on ground it shows an error

self:I(self.lid.."Switching LASER on again at target ".. target:GetName())

needs changed

**Comment by shadowze** [comment]
maybe ?
self:I(self.lid.."Switching LASER on again at target ".. target:GetName() or "coord")

**Comment by funkyfranky** [comment]
I guess we can close this. Thanks for the report shadowze!
