### ISSUE TITLE
UNIT:UnHandleEvent(Event) doesn't work

### ISSUE THREAD

**Issue by Carlton2001** [FlightControl-Master/MOOSE#1365]
I think there is a problem with UnHandleEvent for units :
```lua
TestUnit = UNIT:FindByName("TestUnit")
TestUnit:HandleEvent(EVENTS.Shot)
TestUnit:UnHandleEvent(EVENTS.Shot)
```
[Moose.lua]42594: attempt to call method 'RemoveForUnit' (a nil value)

**Comment by funkyfranky** [comment]
Thanks! Should be fixed now. Pls test.

**Comment by Carlton2001** [comment]
Working as expected, thanks a lot !
