### ISSUE TITLE
Airboss - Heatblur F-14A

### ISSUE THREAD

**Issue by madmoney99** [FlightControl-Master/MOOSE#1370]
With the update to OB today, the F-14A isn't recognized in Airboss.  I made the following change:

```
AIRBOSS.AircraftCarrier={

  F14A="F-14A_tomcat"
```
should be
```
 F14A="F-14A-135-GR"
```
Tested on my local MP server and restores Airboss functionality to the Heatblur F-14A.

**Comment by funkyfranky** [comment]
Thanks Tony! Added this to the code. Probably need to do the same (and a bit more) once they release the other A versions. I only anticipated one A version.
