### ISSUE TITLE
Clean Up the small Task mess in GROUP...

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#138]
Task functions should not execute the task... They should return a task description... A string.... Some Task functions are however executed immediately, which is confusing! One standard. This change will have an impact to existing missions and users. So it must be well communicated.

**Comment by FlightControl-Master** [comment]
Fixed a few already. Those with Route should execute the action, Task functions should return strings. Will check tomorrow the rest.
