### ISSUE TITLE
multiple detailed task descriptions

### ISSUE THREAD

**Issue by Codingboy** [FlightControl-Master/MOOSE#1383]
When joining a task, cancelling the task and joining it again you will get 2 task descriptions every time.
Each time you cancel it (or die) and join the task again you will get an additional task description.
Is there a way to prevent this?

**Comment by Applevangelist** [comment]
Can you share your code for testing pls?

**Comment by Codingboy** [comment]
I uploaded the mission here: https://nippyshare.com/v/fc58af
you a task, cancel it, join it again.
you will continuously get 2 detailed task descriptions

**Comment by Applevangelist** [comment]
Ah, that's again the case of the never stopping flash message. In Task.lua change line 1255 or line 142185 in your Moose.lua (from your .miz file) to
`self.FlashTaskScheduler, self.FlashTaskScheduleID = SCHEDULER:New( self, self.MenuTaskStatus, { TaskGroup }, 0, 60, 0, 61 )`
Extended status will stay on for 1 minute or so and then drop off. No dupes appearing when re-joining a task.

**Comment by Applevangelist** [comment]
Let me know if that works for you.

**Comment by Codingboy** [comment]
Yeah, it _kinda_ works. It removes the old message but also prevents the new message from flashing. Optimal behaviour would be to keep flashing if the taskstate is assigned until I disable flashing or cancel the task (or got killed).

**Comment by Applevangelist** [comment]
Yes, agree, but that would require mor of a complete refactoring of the Task code. In case a task gets unassigned or the player the connection to the timer doing the flash is lost, hence it flashes forever. This code works with multiple inherited and nested classes, so that is a rather non-trivial task. Hope that it's still ok for the time being, as you can see the extended description anyway by recalling it via the F10 menu.

**Comment by Applevangelist** [comment]
Attaching a different patch as I looked again at the code. Give it a try.
[Moose.zip](https://github.com/FlightControl-Master/MOOSE/files/5628110/Moose.zip)

**Comment by Codingboy** [comment]
I was in fear it might require quite a lot of work.
Your fix works like a charm! Thanks!
Am I bound to this moose.lua or will it be merged to the main project?

**Comment by Applevangelist** [comment]
Wonderful. I'll push a change to merge into the master release.

**Comment by funkyfranky** [comment]
G
