### ISSUE TITLE
MOOSE error in MENU COMMAND function:

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#1388]
2020-11-29 15:54:34.769 INFO    SCRIPTING: MOOSE error in MENU COMMAND function: [string "D:\games\3Develop_Moose_g.lua"]:166374: attempt to concatenate local 'Text' (a table value)
2020-11-29 15:54:34.769 INFO    SCRIPTING: stack traceback:
	[string "D:\games\3Develop_Moose_g.lua"]:9960: in function <[string "D:\games\3Develop_Moose_g.lua"]:9957>
	[string "D:\games\3Develop_Moose_g.lua"]:166374: in function 'Report'
	[string "D:\games\3Develop_Moose_g.lua"]:165178: in function 'MenuMarkToGroup'
	[string "D:\games\3Develop_Moose_g.lua"]:163774: in function <[string "D:\games\3Develop_Moose_g.lua"]:163759>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "D:\games\3Develop_Moose_g.lua"]:9971: in function <[string "D:\games\3Develop_Moose_g.lua"]:9967>

line 166374 traces to **function TASKINFO:Report( Report, Detail, ReportGroup, Task )**

LineReport:Add( ( ( Key and ShowKey == true ) and ( Key .. ": " ) or "" ) .. Text )

**Comment by Applevangelist** [comment]
likely "Key" is an unknown category in the Info.Set here and you end up getting a table instead of a string. Can you shed some light on in which context you used that function?

```
for Key, Data in UTILS.spairs( self.Info.Set, function( t, a, b ) return t[a].Order < t[b].Order end ) do

    if Data.Detail:find( Detail ) then
      local Text = ""
      local ShowKey = ( Data.ShowKey == nil or Data.ShowKey == true )
      if     Key == "TaskName" then
        Key = nil
        Text = Data.Data
      elseif Data.Type and Data.Type == "Coordinate" then
        local Coordinate = Data.Data -- Core.Point#COORDINATE
        Text = Coordinate:ToString( ReportGroup:GetUnit(1), nil, Task )
      elseif Key == "Threat" then
        local DataText = Data.Data -- #string
        Text = DataText
      elseif Key == "Counting" then
        local DataText = Data.Data -- #string
        Text = DataText
      elseif Key == "Targets" then
        local DataText = Data.Data -- #string
        Text = DataText
      elseif Key == "QFE" then
        local Coordinate = Data.Data -- Core.Point#COORDINATE
        Text = Coordinate:ToStringPressure( ReportGroup:GetUnit(1), nil, Task )
      elseif Key == "Temperature" then
        local Coordinate = Data.Data -- Core.Point#COORDINATE
        Text = Coordinate:ToStringTemperature( ReportGroup:GetUnit(1), nil, Task )
      elseif Key == "Wind" then
        local Coordinate = Data.Data -- Core.Point#COORDINATE
        Text = Coordinate:ToStringWind( ReportGroup:GetUnit(1), nil, Task )
      elseif Key == "Cargo" then
        local DataText = Data.Data -- #string
        Text = DataText
      elseif Key == "Friendlies" then
        local DataText = Data.Data -- #string
        Text = DataText
      elseif Key == "Players" then
        local DataText = Data.Data -- #string
        Text = DataText
      else
        local DataText = Data.Data -- #string
        Text = DataText
      end

      if Line < math.floor( Data.Order / 10 ) then
        if Line == 0 then
          Report:AddIndent( LineReport:Text( ", " ), "-" )
        else
          Report:AddIndent( LineReport:Text( ", " ) )
        end
        LineReport = REPORT:New()
        Line = math.floor( Data.Order / 10 )
      end

      if Text ~= "" then
        LineReport:Add( ( ( Key and ShowKey == true ) and ( Key .. ": " ) or "" ) .. Text )
      end

    end
  end
```

**Comment by shadowze** [comment]
Sadly I cannot shed light on what is calling this, most likely a player on our server is requesting some info on a cargo task (they are the only tasks being used on our server)

**Comment by Applevangelist** [comment]
Ok, possibly an overlap with another player action, or is this a regular occurance? Could catch that as so

```
      if Text ~= "" and type(Text) == "string" then
        LineReport:Add( ( ( Key and ShowKey == true ) and ( Key .. ": " ) or "" ) .. Text )
      end
```

**Comment by shadowze** [comment]
i have seen it in the log a few times lately

**Comment by Applevangelist** [comment]
Maybe you can patch that line in your Moose.lua and see if it disappears. Without further context it's impossible to see what drives this.

**Comment by shadowze** [comment]
done, next server restart is at 18:00hrs, see what happens after this

**Comment by Applevangelist** [comment]
Thanks. Let me know how it's going.

**Comment by shadowze** [comment]
I know what causes this
![image](https://user-images.githubusercontent.com/30597073/100641157-01b43980-332f-11eb-83bb-2ea3be418e05.png)

![image](https://user-images.githubusercontent.com/30597073/100641180-08db4780-332f-11eb-9d8c-51a3a4e16111.png)

a cargo mission you have not selected yet, you select Mark Task locations on Map

and it generates this error

**Comment by shadowze** [comment]
TAD-CGO-005 - Transport Test - Various Cargo.miz
load , pick helicopter, try marking locations, it errors same way

**Comment by Applevangelist** [comment]
That we can work with. Thks.

**Comment by Applevangelist** [comment]
ok indeed the catch-all in `Taskinfo.lua `towards the end is the culprit, as it assumes string when you get there. In case of an unassigned task however this is a list of waypoints, hence the error.
I had the right idea, but the wrong location. in `function TASKINFO:Report( Report, Detail, ReportGroup, Task ) `patch the last else to
```
      else
        local DataText = Data.Data -- #string
        if type(DataText) == "string" then
          Text = DataText
        end
      end
```

**Comment by funkyfranky** [comment]
No complaints so assuming this is fixed
