### ISSUE TITLE
SPAWN class cannot handle FARPs

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#1395]
Recently Farps were spawnable. Farps have a legacy object type and weird makeup and for years coudlnt be spawned. However recently several enhancements by ED were added. These include
-Fixing spawning to have the ATC and warehouse elements
-Heatblur added the "Invisible farp"

https://wiki.hoggitworld.com/view/DCS_func_addGroup

FARPS require special handling. Currently you cannot SPAWN one. You can spawn the Static version with no ATC or services with SPAWNSTATIC but its not worth doing because its a brick.
Doing it via SPAWN gives an error message "There is no group declared in the mission editor with the name ..."

I'd like to request the ability to spawn them. It would need special handling, probably outwith the SPAWN or SPAWNSTATIC class. Possibly a new class like SPAWNFARP since needs to handle the new qualities

local _Helipad_Data = {
["visible"] = true,
["hidden"] = false,
["units"] =
{
[1] =
{
["category"] = "Heliports",
["shape_name"] = "FARP", --there are three types
["type"] = "SINGLE_HELIPAD", --can we include the three types?
["heliport_frequency"] = 140.0 
["y"] = _point.z,
["x"] = _point.x,
["name"] = "Helipad",
["heliport_modulation"] = 0, --what other modulations can these accept
["heliport_callsign_id"] = is this the name like "london"? 
}, -- end of [1]

}, -- end of ["units"]
["y"] = _point.z,
["x"] = _point.x,
["name"] = "Helipad #" .. _unitId
}
local FOB_Object = coalition.addGroup(_country, -1, _Helipad_Data) -- "-1" apprently required.

**Comment by funkyfranky** [comment]
Implemented now in the SPAWNSTATIC class

```
  local spawnstatic1=SPAWNSTATIC:NewFromType("FARP", "Heliports", country.id.USA):InitShape("FARPS"):InitFARP(CALLSIGN.FARP.Paris, 127.5, 0)
  
  local spawnstatic2=SPAWNSTATIC:NewFromType("Invisible FARP", "Heliports", country.id.USA):InitShape("invisiblefarp"):InitFARP(CALLSIGN.FARP.London, 127.5, 0)
  
  local spawnstatic3=SPAWNSTATIC:NewFromType("SINGLE_HELIPAD", "Heliports", country.id.USA):InitShape("FARP"):InitFARP(CALLSIGN.FARP.Berlin, 127.5, 0)
    
  local spawnstatic4=SPAWNSTATIC:NewFromType("Gas platform", "Heliports", country.id.USA):InitShape("gas_platform"):InitFARP(CALLSIGN.FARP.Madrid, 127.5, 0)
  
  local spawnstatic5=SPAWNSTATIC:NewFromType("Oil rig", "Heliports", country.id.RUSSIA):InitShape("oil_platform"):InitFARP(CALLSIGN.FARP.Moscow, 127.5, 0)
  
  local mystatic1=spawnstatic1:SpawnFromZone(ZONE:New("Zone Spawn-1"))
  mystatic1:SmokeRed()

  local mystatic2=spawnstatic2:SpawnFromZone(ZONE:New("Zone Spawn-2"))
  mystatic2:SmokeRed()

  local mystatic3=spawnstatic3:SpawnFromZone(ZONE:New("Zone Spawn-3"))
  mystatic3:SmokeRed()

  local mystatic4=spawnstatic4:SpawnFromZone(ZONE:New("Zone Spawn-4"))
  mystatic4:SmokeRed()
  
  local mystatic5=spawnstatic5:SpawnFromZone(ZONE:New("Zone Spawn-5"))
  mystatic5:SmokeRed()```

**Comment by funkyfranky** [comment]
Done!
