### ISSUE TITLE
Escort class message

### ISSUE THREAD

**Issue by FubarBundy** [FlightControl-Master/MOOSE#141]
Escort message class could just as easily be used as an "escortee" class, ie, a clint fighter could escort an AI strike. The wording of the ESCORT message would need to be changed though.

**Comment by FlightControl-Master** [comment]
Fixed. I EscortBriefing is not given, it will display the default text, otherwise it will show your briefing. Note that i oblige a briefing to be given, because otherwise the player won't know that there is an escort on his flight.
