### ISSUE TITLE
AI_BALANCER does not work with group names containing dashes (-)

### ISSUE THREAD

**Issue by josefjahn** [FlightControl-Master/MOOSE#1410]
After lengthy debugging I found out why my AI_BALANCER setup didn't work:

```
RED_PlanesSpawn = {}
RED_PlanesSpawn[1] = SPAWN:New( "RED AIB SU-27 1" ):InitCleanUp( 45 )
RED_PlanesSpawn[2] = SPAWN:New( "RED AIB SU-27 2" ):InitCleanUp( 45 )
RED_PlanesSpawn[3] = SPAWN:New( "RED AIB JF-17 1" ):InitCleanUp( 45 )
RED_PlanesSpawn[4] = SPAWN:New( "RED AIB JF-17 2" ):InitCleanUp( 45 )
RED_PlanesSpawn[5] = SPAWN:New( "RED AIB JF-17 3" ):InitCleanUp( 45 )
RED_PlanesSpawn[6] = SPAWN:New( "RED AIB JF-17 4" ):InitCleanUp( 45 )

RED_PlanesClientSet = {}
RED_PlanesClientSet[1] = SET_CLIENT:New():FilterPrefixes("RED PLAYER SU-27 1")
RED_PlanesClientSet[2] = SET_CLIENT:New():FilterPrefixes("RED PLAYER SU-27 2")
RED_PlanesClientSet[3] = SET_CLIENT:New():FilterPrefixes("RED PLAYER JF-17 1")
RED_PlanesClientSet[4] = SET_CLIENT:New():FilterPrefixes("RED PLAYER JF-17 2")
RED_PlanesClientSet[5] = SET_CLIENT:New():FilterPrefixes("RED PLAYER JF-17 3")
RED_PlanesClientSet[6] = SET_CLIENT:New():FilterPrefixes("RED PLAYER JF-17 4")

RED_AI_Balancer = {}
for i=1, 6 do
  RED_AI_Balancer[i] = AI_BALANCER:New(RED_PlanesClientSet[i], RED_PlanesSpawn[i])

```

The SET_CLIENT filtering doesn't work if the client name contains a dash (-). Worse yet, this fails silently without any hint as to what's wrong. Removing the dashes makes it work:

```
RED_PlanesClientSet[1] = SET_CLIENT:New():FilterPrefixes("RED PLAYER SU-27 1")
RED_PlanesClientSet[2] = SET_CLIENT:New():FilterPrefixes("RED PLAYER SU-27 2")
RED_PlanesClientSet[3] = SET_CLIENT:New():FilterPrefixes("RED PLAYER JF-17 1")
RED_PlanesClientSet[4] = SET_CLIENT:New():FilterPrefixes("RED PLAYER JF-17 2")
RED_PlanesClientSet[5] = SET_CLIENT:New():FilterPrefixes("RED PLAYER JF-17 3")
RED_PlanesClientSet[6] = SET_CLIENT:New():FilterPrefixes("RED PLAYER JF-17 4")

```

Another thing to note: Group name and pilot name must start with the same prefix, or it won't work. Or maybe the clientset is using the pilot name, whereas the spawnset uses the group name...

**Comment by Delta-99** [comment]
Sounds familiar with dash (-) not only for AI BALANCER but probably for anything!! :(

Also perhaps CLIENT_SET does use UNIT names. That wouldn't surprise me. Need to check docs or test further.

**Comment by shadowze** [comment]
I brought this up a year or more ago, advising people NOT to use - character in unit or group names as it causes fuckery
I have been using underscores in my names for a very long time to avoid this, think there are other characters not to use as well as -

**Comment by Delta-99** [comment]
@shadowze do we know if this is a DCS thing or Moose thing? I think I remember it being more of a DCS thing really. If it is NOT a DCS thing and really a Moose issue I wonder if this is worth fixing?? It might be difficult to fix given all the areas this might touch.

At the very least this should be covered in the GUIDE and / or HUGE BOLDED SENTENCE in the main SPAWN docs or something. @thebgpikester do you know if this is in the GUIDE off the top of your head?

**Comment by shadowze** [comment]
It is as far as I know a LUA thing, it was a couple of years ago I discovered this
things I avoid in names in DCS
the dash -
the star *
I try to stick the alpha numeric characters and not use anything funky or weird, as long as people know they should be ok

**Comment by shadowze** [comment]
from LUA docs
* Match the previous character (or class) zero or more times, as many times as possible.
+ Match the previous character (or class) one or more times, as many times as possible.
- Match the previous character (or class) zero or more times, as few times as possible.
? Make the previous character (or class) optional.

**Comment by josefjahn** [comment]
Adding this to the Moose docs is probably a great idea! Also, a check could be done on mission startup that issues a warning in the logs when such groups or units are found.

**Comment by Delta-99** [comment]
Is Moose even supporting this then? This sounds like a regex type of thing. This should definitely be part of the Moose docs if so. Also what it should mean is that the "-" should be escapable as well so that you can actually get dashes to work as long as it is a valid naming convention for groups/units.

I was also thinking of a warning that Moose can check and output. BUT ONLY if this is not a DCS issue. Cause if it is then its likely Moose can't even tell. But it sounds otherwise perhaps.

**Comment by Delta-99** [comment]
Just checked LUA documentation. If Moose is in fact just taking this and its like a magic character in the prefix matching then you can escape the - (dash) with %. So if you have "dumb-name" as a group you should be able to use "dumb%-name" in Moose.

If someone wants to test then that would be great and we'd have our answer for certain.

**Comment by thebgpikester** [comment]
I didn't know, thanks for digging this up, I was where Shadowze was on this, but he's illustrated the reason. Swear to god I just learned this, thanks guys!

It's not that this is a MOOSE thing, it's a LUA thing. How far do you go with that? It's further than I knew. Sure, I'd put it in the guide, as an oddity, I dont think we can endlessly chase how to improve people's LUA skills though, it's beyond our remit, it's hard enough just explaining DCS's odd stuff.

"Avoid using special characters in unit and group names" OK. 👍

**Comment by Delta-99** [comment]
I would take this a step further if someone has time to show it works as we suspect. If so, we can also add "or use %- in your prefix matching if you are using dashes in group names.

**Comment by Delta-99** [comment]
@josefjahn are you able to test this by using what I suggest in my previous comment?

**Comment by thebgpikester** [comment]
closing as no bug
