### ISSUE TITLE
AI_CARGO_DISPATCHER_APC.SetDeploySpeed() not working

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#1418]
In my mission I set AI_CARGO_DISPATCHER_APC.SetDeploySpeed() to AI_CARGO_DISPATCHER_APC.SetDeploySpeed(16,15). When observing the units moved at 35 mph.

**Comment by funkyfranky** [comment]
The values set in :SetDeploySpeed() are acknowledged by the Moose code and the waypoint has the correct speed set. However, DCS units don't obey it ==> DCS bug.

**Comment by gunterlund** [comment]
Dam!!!!! will you be putting in a report to dcs?
