### ISSUE TITLE
FR: SpawnAtAirbase() blacklist/whitelist implementation

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#1427]
ABSTRACT: SpawnAtAirbase() is a key tool used by many dispatching scripts and classes. 
The DCS implementation of taxiing/airbases and spawning is imperfect and low priority for fixing by ED.
We need greater granularity of handling where on airbases spawns can be spawned from automatically, since leaving DCS to decide is not optimal.
The existing tool that is commonly in use both in MOOSE and even without any scripting, is to block spawning areas by placing statics exactly into the spawn destination area, thereby creating a blacklist of spawn spots.
Some of this has been implemented into WAREHOUSE. Existing classes like Dispatcher and AIB can benefit and allow spawning into areas of an airfield to promote rapid taxiing and prevent long backtracks and downtime that come with the seemingly random nature of spawning.

_SpawnAtAirbase()

#table Parkingdata
(optional) Table holding the coordinates and terminal ids for all units of the group. Spawning will be forced to happen at exactily these spots!

SPAWN:SpawnAtParkingSpot(Airbase, Spots, Takeoff)_

Both of these have the capacity to be granular, but the issue is that granularity is not accessible in dispatchers and automation.

If we could preset somehow the blacklists or even whitelists or combinations thereof, we coulds manipulate the DCS engine to work around it's bad taxiing.

**Comment by funkyfranky** [comment]
Added
`AIRBASE:SetParkingSpotWhitelist(TerminalIdWhitelist)`
and
`AIRBASE:SetParkingSpotBlacklist(TerminalIdWhitelist)`
