### ISSUE TITLE
Dynamic AI Tasking similar to Detection Tasking of clients

### ISSUE THREAD

**Issue by dboshardy** [FlightControl-Master/MOOSE#144]
Create a system in which the HQ/AWAC/C&C unit on the map keeps track of taskings similar to the dynamic detection system now (or even using that system), but also utilizes existing AI on map that are available for tasking and assigns them the taskings.

This could be done by issuing messages to those AI.  The AI would parse the message (regex) and assign themselves the tasking (Task SEAD, Task CAP, etc.).  

The AI would also respond to queries by the client and/or HQ as to their BRA from bulls, current tasking (if any), loadout, etc.

**Comment by FlightControl-Master** [comment]
noted.

**Comment by Grey-Echo** [comment]
I don't want to be rude, but this is 7 months old, and @dboshardy hasn't committed anything since then, here or on his fork. I'm going to go ahead and close this issue, @dboshardy , if you are still working on it, please create a new issue and keep us informed of your progress !
