### ISSUE TITLE
FUNCTIONAL.RANGE Accuracy Strafe Target > 100%

### ISSUE THREAD

**Issue by cammeltech** [FlightControl-Master/MOOSE#1475]
On multiple Strafe runs Players achieved an Accuracy Level > 100%

```lua
StrafeRangeWest=RANGE:New( "Poti_Target_Range" )
StrafeRangeWest:AddStrafePit( {"StrafeRangeWest_StrafePitA1"}, nil , nil, nil, true, 20, StrafeRangeWest:GetFoullineDistance("StrafeRangeWest_StrafePitA1", "StrafeRangeWest_FoulLineA"))
StrafeRangeWest:AddStrafePit( {"StrafeRangeWest_StrafePitB1"}, nil , nil, nil, true, 20, StrafeRangeWest:GetFoullineDistance("StrafeRangeWest_StrafePitB1", "StrafeRangeWest_FoulLineB"))
StrafeRangeWest:AddBombingTargets( {"StrafeRangeWest_Circle1"} )
StrafeRangeWest:SetInstructorRadio( 305, "RadioRelayRangePoti")
StrafeRangeWest:SetRangeControl( 256, "RadioRelayRangePoti2" )
StrafeRangeWest:SetAutosaveOn()
StrafeRangeWest:Start()
```
![Capture](https://user-images.githubusercontent.com/47948096/111921345-5c1b0680-8a94-11eb-9d68-bbec93fe2c08.JPG)

**Comment by cammeltech** [comment]
Hash ID: 2021-03-04T15:39:43.0000000Z-730a21e2b9457635dea149fc835e9e10709cb3f6

**Comment by funkyfranky** [comment]
Yeah @thebgpikester had already reported this some time ago. I looked at the code but could not find a bug so far. Also I have never experienced this myself yet, which makes it even harder to find a potential error.

**Comment by thebgpikester** [comment]
I dunno what to add to make it clearer, it was a bit weird. It seemed to get "worse" pass on pass. It is absolutely a big somewhere, but I've no idea where to look. Its probably a DCS issue that causes it. Any refactoring will break it if DCS gets fixed, I would suggest  a fudge to make it not look so silly,like removing the accuracy. I think DCS isnt counting rounds anyway, its a start shooting, stop shooting. thing, a fudge on how many rounds went due to how long you hit the button and its all based on how much ammo we dispensed not really being measured at the other end. But I'm guessing!

**Comment by cammeltech** [comment]
Did some testing today. Iam not sure when you check for the rounds. DCS exports the table not on a regular basis. Sometimes one "pull the trigger" results in 2 or 3 updates. Maybe it ist time related?

Did a short video where I exported the table and compared it to DCS in the same picture.

'''lua
local ammotable = UNIT:FindByName("test"):GetAmmo()
env.warning(routines.utils.oneLineSerialize(ammotable))
'''
Results:
[Short Youtube Video](https://www.youtube.com/watch?v=t78_QXatJBU)

**Comment by funkyfranky** [comment]
Thanks for the vid @cammeltech. Digging deeper on your own is great.

The rounds are counted when you enter the strafe pit and counted again when you leave it. So it is (unfortunately) not related to any shooting start/stop event.

Having an accuracy >100 % indicates more that the hits are counted twice. My initial guess was some kind of ricochet but I could never confirm or disconfirm it. Could still be a hidden bug in the MOOSE code of course.

**Comment by cammeltech** [comment]
ricochet is possible. maybe double collition (first "the net", second the ground plate"). Will try this week  :-)

**Comment by Applevangelist** [comment]
Fixed
