### ISSUE TITLE
Speeds set via routing the controllable are always max and not honoured in code.

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#1484]
I had a report from Thrud on the DIscord https://discord.com/channels/378590350614462464/781443753273458718/827887437392248872 and I tried a different way and although I couldn't understand his code well enough I could understand my own which tended to agree that **when you create routes with a speed for ground units, they ignore it and go at max speed.**

Sample code - misison create a group of two tanks called rtanks and 4 zones as labelled and watch
```
ZoneA=ZONE:New('Zone A')
ZoneB=ZONE:New('Zone B')
ZoneC=ZONE:New('Zone C')
ZoneD=ZONE:New('Zone D')

ZoneList1={ZoneA,ZoneB,ZoneC, ZoneD}
 function ReRouteR( VehicleGroup )
  local ZoneNumber = math.random( 1, #ZoneList1 )
  local FromCoord = VehicleGroup:GetCoordinate() -- Core.Point#COORDINATE
  local FromWP = FromCoord:WaypointGround()
  local ZoneTo = ZoneList1[ ZoneNumber ] -- Core.Zone#ZONE
  local ToCoord = ZoneTo:GetCoordinate()
  local ToWP = ToCoord:WaypointGround( 50, "On Road" )
  local TaskReRoute = VehicleGroup:TaskFunction( "ReRouteR" )
  VehicleGroup:SetTaskWaypoint( ToWP, TaskReRoute )
  VehicleGroup:Route( { FromWP, ToWP }, 4 )
end

Rtanks = SPAWN
:New("rtanks")
:InitLimit(3,0)
Rtanks:OnSpawnGroup(function( SpawnGroupR )ReRouteR(SpawnGroupR)end)
:SpawnScheduled(100,0)
```
Observe that the line   local ToWP = ToCoord:WaypointGround( 50, "On Road" ) should dictate 50 kts. we get 60 every time.

Can I get verification there is a DCS bug here or a sample back on a working speed set in ARMY GROUP class and controllable? Sorry :( I need to verify a DCS bug to go to Grimes and on and one to go to DCS.

**Comment by thebgpikester** [comment]
I've asked Grimes to help with some raw SSE scripting to see if it natively reproduces, but any help appreciated so I can see if tis a bug or not.

**Comment by Applevangelist** [comment]
The speed is always meters/second in the raw API. Not sure if WaypointGround does any transitions, need to look at the code

**Comment by thebgpikester** [comment]
Reproduced 2.7
Next steps:
Need a way to put this into raw code so it cna be submitted as a bug, or someone else to validate this is a bug.

**Comment by funkyfranky** [comment]
This should be fixed now. Was an issue with the waypoint table. The parameter `ETA_locked=true` caused them to go full speed even though `Speed_locked=true`.
