### ISSUE TITLE
AI_A2A_DISPATCHER

### ISSUE THREAD

**Issue by Alex05Matt09** [FlightControl-Master/MOOSE#1504]
Created 2 X F14 CAPs 1 X F18 CAP. The squadrons did not fly assigned altitudes or speeds. assigned 120000-14000 at 350 knots Yet they flew and 123 knots. Climbed to 35000 feet then would dive down to 2000 feet and would then climb again. they were either diving or had a very high AOA. I had them depart from CVN-73 hot start. i had 3 CAP Zones set up North, South and East. I then loaded the F14s into mission editor assigned a route and altitude and they followed it exactly, altitude and speed.

**Comment by Alex05Matt09** [comment]
RescueHelo1 = RESCUEHELO:New( "CVN-73 George Washington" ,"HSC-5" )
RescueHelo1:SetTakeoffHot()
RescueHelo1:SetAltitude(25)
RescueHelo1:SetOffsetZ(100)
RescueHelo1:SetOffsetX(25)
RescueHelo1:__Start(5)

DetectionGroup = SET_GROUP:New():FilterPrefixes( "VAW-111" ):FilterStart()
Detector = DETECTION_AREAS:New( DetectionGroup , 50000 )
Dispatcher = AI_A2A_DISPATCHER:New(Detector)
Dispatcher:SetEngageRadius( 50000 )

Dispatcher:SetSquadron("VF-101", "CVN-73 George Washington","VF-101",4)
Dispatcher:SetSquadron("VF-142", "CVN-73 George Washington","VF-142",4)
Dispatcher:SetSquadron("VMFA-122", "CVN-73 George Washington","VMFA-122",4)

Dispatcher:SetSquadronTakeoffFromParkingHot("VF-101")
Dispatcher:SetSquadronLandingAtRunway("VF-101")
Dispatcher:SetSquadronFuelThreshold("VF-101",0.2)
Dispatcher:SetSquadronGrouping("VF-101", 2 )
CAPZoneEast = ZONE:New( "CAP Zone East" )

Dispatcher:SetSquadronCap("VF-101", CAPZoneEast ,16000 , 18000 , 350 , 500 , 500 ,800 ,"BARO")
Dispatcher:SetSquadronCapInterval("VF-101",1,30,60,1)

Dispatcher:SetSquadron("VF-142", "CVN-73 George Washington","VF-142",4)
Dispatcher:SetSquadronTakeoffFromParkingHot("VF-142")
Dispatcher:SetSquadronLandingAtRunway("VF-142")
Dispatcher:SetSquadronFuelThreshold("VMFA-122",0.15)
Dispatcher:SetSquadronGrouping("VF-142", 2 )
CAPZoneSouth = ZONE:New( "CAP Zone South" )
Dispatcher:SetSquadronCap("VF-142", CAPZoneSouth ,15000 , 19000 , 350 , 500 , 500 ,800 ,"BARO")
Dispatcher:SetSquadronCapInterval("VF-142",1,30,60,1)

Dispatcher:SetSquadronTakeoffFromParkingHot("VMFA-122")
Dispatcher:SetSquadronLandingAtRunway("VMFA-122")
Dispatcher:SetSquadronFuelThreshold("VMFA-122",0.3)
Dispatcher:SetSquadronGrouping("VMFA-122", 2 )
CAPZoneNorth = ZONE:New( "CAP Zone North" )
Dispatcher:SetSquadronCap("VMFA-122", CAPZoneNorth ,12000 , 16000 , 350 , 500 , 500 ,800 ,"BARO")
Dispatcher:SetSquadronCapInterval("VMFA-122",1,30,60,1)

Dispatcher:SetTacticalDisplay(true)

**Comment by Applevangelist** [comment]
CAP Flight heights are meters, and Speed is km/h, hence no bug. Can be closed.
