### ISSUE TITLE
route handling is broken for submerged submarines

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#1535]
Been playing with the new subs in DCS, was trying to:
spawn a sub (submerged) - works ok
get the sub to randomly pick waypoints on a route and move to them - sub moves but it surfaces as soon as it starts moving

Example missions - there are two subs:
one to north is using MOOSE to set it move points (sub surfaces - it should not do this)
second to the south is a normal ME placed one and it follows the route correctly and stay submerged

See attached miz

[Broken submerged submarines GRP-551 - Patrol to random points of a route.zip](https://github.com/FlightControl-Master/MOOSE/files/6519101/Broken.submerged.submarines.GRP-551.-.Patrol.to.random.points.of.a.route.zip)

**Comment by Applevangelist** [comment]
The used function isn't really geared towards subs, it's geared towards GROUND units, basically. Will have to write a SUB (sorry for the pun) function ....

**Comment by shadowze** [comment]
the function works ok with ships and ground units, is there a simple way to find out if a unit is a submarine ?
and not mess with the **alt** part of the route table ?  eg if alt is a negative number the unit is a submarine and is submerged so handle it slightly differently ?

**Comment by Applevangelist** [comment]
Yes, that was my idea, and/or add a parameter for subs giving the depth

**Comment by Applevangelist** [comment]
Build done.
