### ISSUE TITLE
MISSILETRAINER

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#157]
Pikey feedback:
OK example of confusion:
:InitMessagesOnOff(true)
 :InitAlertsToAll(true) 
 :InitAlertsHitsOnOff(true)
 :InitAlertsLaunchesOnOff(false) -- I'll put it on below ...
 :InitBearingOnOff(true)
 :InitRangeOnOff(true)
 :InitTrackingOnOff(true)
 :InitTrackingToAll(true)
 :InitMenusOnOff(false)

Trainer:InitAlertsToAll(true)

Documebntaiton is in this format:

Tracking: Menu to configure missile tracking messages.

   To All: Shows missile tracking messages to all players.
   To Target: Shows missile tracking messages only to the player where the missile is targetted at.
   Tracking On: Show missile tracking messages.
   Tracking Off: Disable missile tracking messages.
   Frequency Increase: Increases the missile tracking message frequency with one second.
   Frequency Decrease: Decreases the missile tracking message frequency with one second.

Alerts: Menu to configure alert messages.

   To All: Shows alert messages to all players.
   To Target: Shows alert messages only to the player where the missile is (was) targetted at.
   Hits On: Show missile hit alert messages.
   Hits Off: Disable missile hit alert messages.
   Launches On: Show missile launch messages.
   Launches Off: Disable missile launch messages.

Details: Menu to configure message details.

   Range On: Shows range information when a missile is fired to a target.
   Range Off: Disable range information when a missile is fired to a target.
   Bearing On: Shows bearing information when a missile is fired to a target.
   Bearing Off: Disable bearing information when a missile is fired to a target.

Distance: Menu to configure the distance when a missile needs to be destroyed when near to a player, during tracking. This will improve/influence hit calculation accuracy, but has the risk of damaging the aircraft when the missile reaches the aircraft before the distance is measured.

   50 meter: Destroys the missile when the distance to the aircraft is below or equal to 50 meter.
   100 meter: Destroys the missile when the distance to the aircraft is below or equal to 100 meter.
   150 meter: Destroys the missile when the distance to the aircraft is below or equal to 150 meter.
   200 meter: Destroys the missile when the distance to the aircraft is below or equal to 200 meter.

Better woudl be to have the variables listed in the documetnaiton so you coudl add them, for example, I would like to  turn the target warnings alert off. the docuemntaiton says: To Target: Shows alert messages only to the player where the missile is (was) targetted at. But iuts doesn't say what the variable shoudl be in the missile trainer.lua to change it

[4:24]  
also the Bool for onoff is confusing, much better would be to have "missiletrackingOn: true or false"

[4:25]  
It doesn't say how to switch off the lthality part, if that is possible so that missiles wll be tracked, but not be stopped which is a possible interesting use, especially if we want to use AI

[4:26]  
COrrection, it gives the example variable later, but not with the expplanation, coudsl save some space there.

[4:29]  
I'd like to rewrite this with a clearer example for the layperson and do a showcase mission thread in the forums, it might get more uptake, we can see

Initial feedback, 
The distance setting in the scheduler should include zero, so we can make missiles hit if we want. Additionally the distance settings are kindda peculiar, I can't imagine an advantage between a missile exploding at 50m or 200m, maybe i've not considered something. ALso the distances are one thing in the menu, but another in the message that comes out - when I set 50m it came up with a message saying 0.05 and I thought, great I can get shot. was not to be, looked like 50m, just a false message.
F10 should be enabled by default, allowing changes int he game rather than enforcing them. Notate the lua file to show what setting to change that if people are editing their own mission, so they start with everythign and can take away. helps learning.

[5:01]  
I'd put a copy of the docs as text int he lua, its minimal and fairly standard now
The on/off bool for a yes/no question.....is it me or a language thing. To avoid changing any funciton names its nicer to put -"True =Yes" at the top of the lua.
Test/showcase Miz shouldnt include the blue plane. Its confusing, i went there first and nothing happened., ha! how unlucky.
Other than that seems good to go,

[5:05]  
setting distance to 0 in the init for missile removal works, so woudl love that one change, the rest is eyecandy

thebgpikester [5:22 PM]  
Message decay time would be a nice to have, especially a nice kill message, like Blue Player Bob killed red player Jim with a hammer (20 seconds life).

thebgpikester [5:50 PM]  
OK I added a switch condition to switch lethality on and off, haven't fuilly tested it backwards and forwards:)

[5:52]  
Oh last one, would be nice to have relative bearing to the missile rather than absolute heading so you can learn to notch properly

**Comment by FlightControl-Master** [comment]
@132nd-Entropy and all, can you review this feedback? What is compelling, what are good ideas.

**Comment by Kalbuth** [comment]
Documentation talks about 2 different things : 1) The menu that is showed in game when using Missile Trainer, 2) the actual Class and its members/methods and parameters. 
There's no need imho to list variable and such when describing the menu. So that part is fine for me as is.
About "OnOff", yes, it might be confusing :) Much better with only "On" and setting it to true or false.
Good point on the zero distance. Simply having in flight information my be a helper, if people want to test actual dogfight but get more info during it.

**Comment by thebgpikester** [comment]
Have we targeted any enhancements for this or is it parked indefinitely? I believe the feedback is valid, in terms of improvements can be made, but I suspect it's mostly cosmetic for new users and thus (right now) low impact.

**Comment by FlightControl-Master** [comment]
There are teams using the module and haven't seen a complaint. Suggest to close.

**Comment by 132nd-Entropy** [comment]
agreed. One bug, manpads are currently not tracked, but thats a bug within DCS

**Comment by Grey-Echo** [comment]
Well, If everybody agree to close this one...
