### ISSUE TITLE
CTLD - Request ability to pickup deployed troops

### ISSUE THREAD

**Issue by bbirchnz** [FlightControl-Master/MOOSE#1572]
No option to pickup deployed units, attempts to pick up met with out of logistics zone message.

**Comment by Applevangelist** [comment]
KInd of beats the logic if I allow to pickup ANY troops ANYWHERE. Sry.

**Comment by bbirchnz** [comment]
The use case here is to further move or retrieve previously deployed troops
from the field, so already groups that match the cargo definitions.

**Comment by Applevangelist** [comment]
closed
