### ISSUE TITLE
CTLD - Not building to template

### ISSUE THREAD

**Issue by Shark149** [FlightControl-Master/MOOSE#1587]
When building groups, the script is ignoring crate placement or original templated unit placement. Attached what the template looks like and what the final build looks like.

![Hawk_Built](https://user-images.githubusercontent.com/78509581/128590777-35143b54-2c86-45cc-94ea-87aebe866617.jpg)
![Hawk_Template](https://user-images.githubusercontent.com/78509581/128590781-8f73d3b0-db26-4a18-a691-5533359bcb99.jpg)

**Comment by Shark149** [comment]
Crates were positioned approx 40=-60 meters apart. Apologies for no screeny of that

**Comment by Applevangelist** [comment]
When you create SAM sites cargo as VRgo Type FOB, the positions of the single units will remain as they were in the template.

**Comment by Shark149** [comment]
Thankyou. Will test that :)

**Comment by Shark149** [comment]
Confirmed this worked as described. Many thanks!
