### ISSUE TITLE
CSAR: Different values returned for event functions

### ISSUE THREAD

**Issue by Shark149** [FlightControl-Master/MOOSE#1588]
Hi team, I noticed the following when using the events for the CSAR script:

Function: my_csar:OnAfterPilotDown the 'groupname' the function delivers is the UNIT name eg: 

```
`function my_csar:OnAfterPilotDown(from, event, to, spawnedgroup, frequency, groupname, coordinates_text)
 env.info("gname= "..groupname) end
```

DCS.log shows:  SCRIPTING: gname= Pilot 290.00kHz-36#001-01

OnAfterBoarded - the groupname delvers is the GROUP name:

eg:
```
`Function my_csar:OnAfterBoarded(from, event, to, heliname, groupname)
	env.info("group = "..groupname)`
```

DCS.log shows:  SCRIPTING: group = Pilot 290.00kHz-36#001

Cheers!

**Comment by Applevangelist** [comment]
You can test once the next development branch build is completed in a couple of minutes

**Comment by Shark149** [comment]
Thank you Applevangelist - i know its only a small thing but didn't want it to trip up others.  I Appreciate the quick turn around!

**Comment by Applevangelist** [comment]
closed
