### ISSUE TITLE
CTLD: Crates spawned on moving ships stay in place - do not move with the ship

### ISSUE THREAD

**Issue by Shark149** [FlightControl-Master/MOOSE#1590]
When making a CTLD zone on a carrier or LHA, when crates spawn they do not move with the ship. They hold their VEC3 position until loaded. 
Please let me know if you would like screenshots

Cheers!

**Comment by shadowze** [comment]
crates and moving ship in DCS do not work (it is a DCS limitation)
example you sling load a crate and drop it on a moving ship deck, the crate will stay in the same position it was dropped off on
when the ship moves the crate will eventually end up hovering in the air as if by magic

**Comment by Shark149** [comment]
Thank you. Yes this is the same behaviour. I wondered if you could spawn the crate with the "Link Unit" property defined. Whilst you cannot sling load a crate spawned with this property, because the crate is being 'removed' by script I thought perhaps it may be possible.... 

Ill have a look at replicating the issue in code and testing link unit. then de-spawning and see if it works.

**Comment by Applevangelist** [comment]
Yes, but I’ll have to make a special ship option / zone first. Else the helis would fly around with the crates they can’t load …

**Comment by shadowze** [comment]
I discovered the flying crate DCS bug several years ago, my solution was simple, do not load / drop off crates onto moving ships

**Comment by Shark149** [comment]
Looking at Moose, SpawnNewFromTemplate or SpawnNewWithAlias dont have "link unit" properties, no no real way to fix without major work. Happy to close this based on that fact alone.

**Comment by Applevangelist** [comment]
In dev branch for testing

**Comment by Applevangelist** [comment]
completed
