### ISSUE TITLE
Error being generated by RAT (I think?)

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#1602]
2021-09-23 18:41:29.441 INFO    SCRIPTING: Error in timer function: [string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:22230: attempt to index local 'aircraft' (a nil value)
2021-09-23 18:41:29.441 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:4744: in function <[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:4741>
	[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:22230: in function 'FindFreeParkingSpotForAircraft'
	[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:33543: in function '_ModifySpawnTemplate'
	[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:31713: in function <[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:31681>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:4781: in function <[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:4735>
2021-09-23 18:41:30.435 INFO    SCRIPTING: Error in timer function: [string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:22230: attempt to index local 'aircraft' (a nil value)
2021-09-23 18:41:30.435 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:4744: in function <[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:4741>
	[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:22230: in function 'FindFreeParkingSpotForAircraft'
	[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:33543: in function '_ModifySpawnTemplate'
	[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:31713: in function <[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:31681>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:4781: in function <[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_public\/~mis00003AF4.lua"]:4735>
2021-09-23 18:41:31.119 INFO    SCRIPTING:  69835( 71209)/I:                    AI_A2A_CAP05952.onafterRTB(Group BLUE CAP_Squadron 3#001 ... RTB! ( Fuel ))
2021-09-23 18:41:32.948 INFO    SCRIPTING:  69835( 71209)/I:                    AI_A2A_CAP21914.onafterRTB(Group BLUE CAP_Squadron 3#002 ... RTB! ( Fuel ))

I will attach the mission file (this mission was running on a dedicated server)
[VAF_Syria_0_9_8_8.zip](https://github.com/FlightControl-Master/MOOSE/files/7225620/VAF_Syria_0_9_8_8.zip)
le

**Comment by shadowze** [comment]
hmm , github is doing something stupid with the log excerpt , I have zipped the log and attached it now
[dcs_logs.zip](https://github.com/FlightControl-Master/MOOSE/files/7225628/dcs_logs.zip)

**Comment by Applevangelist** [comment]
The dcs.log.zip has 1kb and is empty

**Comment by shadowze** [comment]
very sorry hombre, windows f**ked me over once again
here it is (go to bottom)
[dcs_logs.zip](https://github.com/FlightControl-Master/MOOSE/files/7226201/dcs_logs.zip)

**Comment by Applevangelist** [comment]
Looks RAT tries to find a parking spot for a nil plane

**Comment by Applevangelist** [comment]
The prpblem like likely due to your choice of target airbase. Hatay doesn't have space for a C17

**Comment by shadowze** [comment]
ah ok

**Comment by Applevangelist** [comment]
Pushed a small fix to AIRBASE which at least gives an empty table back when no group object exists.

**Comment by Applevangelist** [comment]
Still persists?
