### ISSUE TITLE
CTLD Troops Extract

### ISSUE THREAD

**Issue by Shark149** [FlightControl-Master/MOOSE#1603]
function CTLD:_ExtractTroops(Group, Unit)

lines:
local groupType = string.match(nearestGroup:GetName(), "(.+)-(.+)$")
    local Cargotype = nil
    for k,v in pairs(self.Cargo_Troops) do
      if v.Name == groupType then

Tries to match the "Name" , not the "Templates" name the group spawned from:

Eg: 
my_ctld:AddTroopsCargo("C_Infantry",{"C_Infantry"},CTLD_CARGO.Enum.TROOPS,2,70)
spawns C_Infantry(randomgennumber)#001 which will match for v.Name == groupType

my_ctld:AddTroopsCargo("C_Infantry",{"ctld.Infantry"},CTLD_CARGO.Enum.TROOPS,2,70)	
Spawns ctld.Infantry((randomgennumber)#001 which will fail when trying to match the values

Is there any way to store and match the template name, or perhaps have Moose spawn the groups with the "Name" not "Templates" variable in the name?

**Comment by Applevangelist** [comment]
This has been rewritten a few versions up:
`      -- find matching cargo type
      local groupType = string.match(nearestGroup:GetName(), "(.+)-(.+)$")
      local Cargotype = nil
      for k,v in pairs(self.Cargo_Troops) do
        local comparison = ""
        if type(v.Templates) == "string" then comparison = v.Templates else comparison = v.Templates[1] end
        if comparison == groupType then
          Cargotype = v
          break
        end
      end`

**Comment by Applevangelist** [comment]
Can this be closed now?
