### ISSUE TITLE
Pb in GROUP:GetAmmunition()

### ISSUE THREAD

**Issue by pcoud** [FlightControl-Master/MOOSE#1605]
I am not an expert, but:

line 678 of ...master/Moose%20Development/Moose/Wrapper/Unit.lua (within the UNIT:GetAmmunition() method):
**678  return nammo, nshells, nrockets, nbombs, nmissiles**

(5 arguments are returned).

Now, line 1157 of ...master/Moose%20Development/Moose/Wrapper/Group.lua (within the GROUP:GetAmmunition() method):
**-- Get ammo of the unit**
**local ntot, nshells, nrockets, nmissiles = Unit:GetAmmunition()**

Only 4 arguments are asked (I don't think this generates an error, but I think nbombs is missing and nmissiles is wrong.

**Comment by Applevangelist** [comment]
Looks like an omission, yes

**Comment by Applevangelist** [comment]
Fixed. Missile count was previously returned as bombs
