### ISSUE TITLE
RADIO:SetFrequency - Frequency Range check too Restrictive for new R1155 receiver

### ISSUE THREAD

**Issue by msdlogic** [FlightControl-Master/MOOSE#1608]
Script won't pass check when trying to set up radio broadcasts using the wider range of the Mosquito R1155 receiver. 
I removed the following check and DCS will broadcast properly on the new frequencies:

if (Frequency >= (Frequency >= 30 and Frequency <= 87.995) or (Frequency >= 108 and Frequency <= 173.995) or (Frequency >= 225 and Frequency <= 399.975) 

Range of the R1155 is:
18.5 MHz to 3 MHz & 1500 kHz to 500 kHz & 500 kHz to 75 kHz

I suggest removing the frequency check entirely.

**Comment by Applevangelist** [comment]
Can be tested in the next build
