### ISSUE TITLE
y and z axes flipped with GetRandomPointVec2/TaskFireAtPoint

### ISSUE THREAD

**Issue by DreamingInfraviolet** [FlightControl-Master/MOOSE#1623]
Scenario:

I'd like to have some units fire randomly in a zone. I create a zone, get a random Vec2 point, and order the units to fire.
Let's say the Vec2 point is `(-42136.046965147, -28824.968353617)`.

Code:

```lua
local FireZone = ZONE:New("FireZone")
local Infantry = GROUP:FindByName("Infantry")

local point = FireZone:GetRandomPointVec2()

Infantry:SetTask(Infantry:TaskFireAtPoint(point, 0, 10))
```

Expected:

Units fire at point ( `{ x = -42136.046965147, y = -28824.968353617}`)

Reality:

Units do not fire, because the FireAtPoint command sent has coordinates  `{x = -42136.046965147, y = 2.0000019073486}`

**The point is using the height axis for the y coordinate**

When using a Vec2 and doing `point:GetY()`, I get the expected coordinate of -28824.968353617. But `TaskFireAtPoint` is not using `Vec2:GetY()`, but is instead doing `Vec2.y`, which is different because `GetY` is defined as:

```lua
function POINT_VEC2:GetY()
  return self.z
end
```

But TaskFireAtPoint is using Vec2.y:

```lua
function CONTROLLABLE:TaskFireAtPoint( Vec2, Radius, AmmoCount, WeaponType, Altitude, ASL )
  local DCSTask = {
    id = 'FireAtPoint',
    params = {
      point = Vec2,
      x=Vec2.x,
      y=Vec2.y,
```

This results in the wrong coordinate being used. It should be using Vec2.z, not Vec2.y, for firing at a point.

As in, I'd expect the following task to be sent:

```lua
{
 id = "FireAtPoint",
 params = {
  y = -28824.968353617,
  radius = 152.39999389648,
  expendQtyEnabled = true,
  x = -42136.046965147,
  expendQty = 10,
 },
}
```

But instead Moose is sending:

```lua
{
 id = "FireAtPoint",
 params = {
  y =  2.0000019073486,
  radius = 152.39999389648,
  expendQtyEnabled = true,
  x = -42136.046965147,
  expendQty = 10,
 },
}
```

I'm going to use this **workaround** for now:

```lua
local FireZone = ZONE:New("FireZone")
local Infantry = GROUP:FindByName("Infantry")

local point = FireZone:GetRandomPointVec2()
point.y = point.z -- Make y=z so that no matter which one we use, the value will be correct

Infantry:SetTask(Infantry:TaskFireAtPoint(point, 0, 10))
```

Would be great to have a non-hacky fix though! I'm not entirely sure if it's `TaskFireAtPoint` that should be changed, or `GetRandomPointVec2`.

**Comment by funkyfranky** [comment]
`FireZone:GetRandomVec2()` should do the trick.
The POINT_VEC2 class is not really good for putting it in the fire at point task.
In case a POINT_VEC2 should be used you still need to `local point = FireZone:GetRandomPointVec2()`:GetVec2()`

**Comment by DreamingInfraviolet** [comment]
Ohh thanks, that works! I didn't realise a Vec2 and a POINT_VEC2 are different things.

I guess I just didn't understand the docs, will close this then :)
