### ISSUE TITLE
Possible issue in UNIT:GetAmmunition()

### ISSUE THREAD

**Issue by pcoud** [FlightControl-Master/MOOSE#1624]
Hi team,
As I could not get the UNIT:GetAmmunition() working to retrieve the number of missiles left from a sam site, I had a look into the method in the Moose UNIT class, and I believe SAM and CRUISE missiles are not taken into account.
Please see line 660: all missiles categories AAM, BM, ANTI-SHIP, OTHER are added up, but neither SAM nor CRUISE
(plus the comment line 559: "-- Add up all cruise missiles (category 5)" makes it even more confusing.

**Comment by Applevangelist** [comment]
Not sure why it was done that way, looks both type SAM and CRUISE are missing from the count. Good find! Maybe the plan was to get out a more detailed list of Ammo with missile sub-types, but wasn't finished I assume
