### ISSUE TITLE
SPAWN:NewFromTemplate - aliases ignored

### ISSUE THREAD

**Issue by m4ti140** [FlightControl-Master/MOOSE#1638]
When using SPAWN:NewFromTemplate the groups are spawned with their original name from the template - contents of both SpawnTemplatePrefix and SpawnAliasPrefix seem to be ignored and the group is spawned with the original name, replacing the original template group.

**Comment by m4ti140** [comment]
What do you mean "it's not really meant for the user"? And more importantly, why is the mechanism of action completely different than what is described in reference?

**Comment by Applevangelist** [comment]
It’s mostly used internally by spawn. And congratulations you actually read the description! Mostly it seems these days users don’t do that any more, glad you did. The docu is obviously written by people, so it’s imperfect. In a more general level, the philosophy of Moose is to use late activated groups as templates, so this is against this. If you want to force the use of alias and prefix, there’s a datafield in the object you get back called “tweakedbyuser” if I remember the name correctly. Set that to true and alias and prefix will be adhered to.

**Comment by m4ti140** [comment]
Oh, that's useful. Thanks
