### ISSUE TITLE
AUFTRAG ESCORT Issue

### ISSUE THREAD

**Issue by jojom4n** [FlightControl-Master/MOOSE#1681]
I have the following two functions

```
function spawnEscort(planeToEscort)
  EscortGroupSpawn = SPAWN:New("55th FS 'Fifty Fifth'")
                          :InitKeepUnitNames(true)
                          :InitCleanUp(60)
			  :InitRepeatOnLanding()
                          :OnSpawnGroup(function(escortgrp)
                              local EscortFlightGroup = FLIGHTGROUP:New(escortgrp)
                                                             :SetFuelLowRTB(true)
                                                             :SetOutOfAAMRTB(true)
                                                             :SetHomebase(AIRBASE.Caucasus.Kobuleti)
                                                             :AddMission(createEscortAuftrag(planeToEscort))
                              end)
                         :Spawn()
end

function createEscortAuftrag(planeToEscort)
  return AUFTRAG:NewESCORT(planeToEscort, nil, 30)
                :SetEngageAltitude(20000)
                :SetEPLRS(true)
                :SetEngageDetected(30, { "Air" })
                :SetRadio(251)
                :SetMissionRange(300)
end
```

When EscortGroupSpawn repeats on landing, Auftrag is able to create another escort mission but Auftrag verbosity reports to have created for respawned EscortGroupSpawn a flightplan where "wp=nil". DCS logfile, without any reference to my script, reports in fact the following:

> 2022-01-01 23:34:52.316 INFO    SCRIPTING: Error in timer function: [string "C:\Users\xxxxx\AppData\Local\Temp\DCS.openbeta\/~mis00005BCB.lua"]:63719: attempt to index a nil value
2022-01-01 23:34:52.316 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\xxxxx\AppData\Local\Temp\DCS.openbeta\/~mis00005BCB.lua"]:5070: in function <[string "C:\Users\xxxxx\AppData\Local\Temp\DCS.openbeta\/~mis00005BCB.lua"]:5067>
	[string "C:\Users\xxxxx\AppData\Local\Temp\DCS.openbeta\/~mis00005BCB.lua"]:63719: in function <[string "C:\Users\xxxxx\AppData\Local\Temp\DCS.openbeta\/~mis00005BCB.lua"]:63700>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\xxxxx\AppData\Local\Temp\DCS.openbeta\/~mis00005BCB.lua"]:5107: in function <[string "C:\Users\xxxxx\AppData\Local\Temp\DCS.openbeta\/~mis00005BCB.lua"]:5061>

Auftrag verbosity, on its own, reports this (notice the "wp=nil", while it's usually "wp=2"):
> 
> 2022-01-01 23:35:23.313 INFO    SCRIPTING:  65833( 67606)/I:                   FLIGHTGROUP01816._PrintTaskAndMissionStatus(FLIGHTGROUP 55th FS 'Fifty Fifth'#000 | Missions 1, Current: Auftrag Nr. 3
> [1] Auftrag Nr. 3 (Escort) status=started (started), Time=08:06:43-INF, prio=50 wp=nil targets=1)

**Comment by Applevangelist** [comment]
That's not an issue with Moose but bad programming. If you want to call a function, define it it **before** you try to use it, otherwise the reference is nil. Also there's no reason to not also create the Auftrag in the OnSpawnGroup and hand it to the FlightGroup.
