### ISSUE TITLE
CTLD unable to build vehicles if they have weight

### ISSUE THREAD

**Issue by derbuur** [FlightControl-Master/MOOSE#1688]
I'm unable to build vehicles from more than one crate if they have a weight. I can get and drop the crates but when they have weight always one crate missing during build process.
When I use a single crate, I have no porblems.

`my_ctld:AddCratesCargo("Humvee Avenger",{"Humvee Avenger"},CTLD_CARGO.Enum.VEHICLE,2,2150,10)` → not working
`my_ctld:AddCratesCargo("Humvee Avenger",{"Humvee Avenger"},CTLD_CARGO.Enum.VEHICLE,2)` → working

**Comment by Applevangelist** [comment]
Works for me. If you are using `:UnitCapabilities("SA342L", false, true, 0, 2)` this currently sets the loadable weight to zero (will be corrected soon). Else check your `.CrateDistance` - for some helos the coordinate is far in the back, making some crates unreachable.

**Comment by derbuur** [comment]
my_ctld:UnitCapabilities("UH-60L", true, true, 2, 12, 16, 3500)
this are the settings of the helo I used. 
And also the Crate.distance is far enough.

**Comment by Applevangelist** [comment]
Ok, can you put together a demo miz for me pls?

**Comment by derbuur** [comment]
Here is a small demo miz. In line 17 and 18 the working and not working example
[testCTLD.zip](https://github.com/FlightControl-Master/MOOSE/files/8073626/testCTLD.zip)
.

**Comment by Applevangelist** [comment]
Got it. Side effect from adding weight limits to helos. Fixed now.

**Comment by Applevangelist** [comment]
Can be tested with the new build

**Comment by derbuur** [comment]
I've tested it and now it works as intended.
