### ISSUE TITLE
Event dead not triggered 

### ISSUE THREAD

**Issue by Applevangelist** [FlightControl-Master/MOOSE#1695]
<@!213316463375810561> After the last ob update, the units no longer respawn in my mission.
for the respawn I use EVENT.Dead and CountAlive().
After many tests I noticed that EVENT.Dead is not always called.
If a vehicle explodes immediately after being hit, Event.Dead is called. However, if a vehicle burns for some time before it explodes, the function under EVENT.Dead will not be executed. Therefore the script does not notice that the unit is destroyed and does not respawn.
I don't know if this is a DCS bug or a bug in moose.
However, if I end the mission in the ME, the dead event is listed in the table. So DCS itself recognizes it.

**Comment by Applevangelist** [comment]
https://forum.dcs.world/topic/295922-scripting-api-eventdead-not-called-if-an-object-isnt-immediately-dead/

**Comment by alexsm32** [comment]
I have a similar issue with the event OnAfterAssetDead from the warehouse module. The event doesn't trigger when the asset die.
