### ISSUE TITLE
FOX - issues with new 114k hellfire missile 

### ISSUE THREAD

**Issue by Applevangelist** [FlightControl-Master/MOOSE#1696]
need to update my moose so could be that but lots of log spam with Fox and the hellfire K atm on the 'getMissileTarget' (but again I've not updated moose so don't know if it's that)

**Comment by Applevangelist** [comment]
@robgrahamau Can you provide more intel on the issue pls?

**Comment by funkyfranky** [comment]
It might be a good idea to add a black list of missile types that are not tracked. Maybe add some by default and add a function to add types by the user in case new missiles types are added in the future.

**Comment by robgrahamau** [comment]
@Applevangelist can close it out, the update that came out the day of release seemed to fix it.
