### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#1700]
@Applevangelist , @funkyfranky , @Delta-99 I would like to thank you all for having continued this effort on the MOOSE platform. I've been abscent and will never be able to rejoin this team like before. However, please continue and if you need my support please let me know. Sven.

**Comment by gunterlund** [comment]
Svennnnnnnnnnnnnnnnnn wow it is great to hear from you...... I hope you are
doing well and will stay in touch.

**Comment by shadowze** [comment]
Hi Sven, Great to hear from you, I  was getting worried about you, Hope you and your family are in good health and things are going well for you in these difficult times, Stay safe out there buddy

**Comment by Applevangelist** [comment]
@FlightControl-User Thanks Sven! Hope you are doing fine these days. :) If we can ask a little favor - we'd like to have access to your FC YouTube Channel, since a lot of users are going there it it needs some updates. Thanks!

**Comment by Delta-99** [comment]
@FlightControl-User Sven (FC), really happy to hear from you. Cannot even put it into words. The guys are doing an absolute amazing job keeping your MOOSE legacy going. Long live the MOOSE!!

Stay safe out there and all the best. Always great to hear from you.

Regards,
Delta99

**Comment by Applevangelist** [comment]
Same as this one Sven - Applevangelist

**Comment by Delta-99** [comment]
Should we create a shared MOOSE youtube where multiple admins can login or something. In case we need to update videos etc? I suppose if stuff is passed over to Apple we can do that later at some point though.

**Comment by shadowze** [comment]
that would be a good idea, incase someone gets run over by a bus or abducted by aliens

**Comment by zlinman** [comment]
Nice to hear from you, hope you are fine. All the best

**Comment by thebgpikester** [comment]
Good to hear you are OK. We will survive, you can come round and see your legacy anytime, its in good hands :)
