### ISSUE TITLE
Client player as Forward Air Controller (FAC)

### ISSUE THREAD

**Issue by Abburo** [FlightControl-Master/MOOSE#1718]
This is an enhancement idea to create a new functional class within Moose to allow client players to act as a Forward Air Controller (FAC) for their team and it came mainly to add more gameplay for some less used helicopters or planes like Gazelle or Yak52

The existing Detect/Designate functions are already providing all required functionalities, however they are working only for AI FAC.

A process description as I can see it working can be found below. This process is inspired from existing FAC implementations which might be found on Rotorheads server.

- Client FAC have to use a unit that has defined the FAC functionalities (eg: Gazelle, Yak52)
- all parameters for detection and designation would be configured accordingly with the existing functions during the script preparation. Detection probabilities parameters will add more realism !!!

**-- //Step 1** - Client FAC will enter the combat area and have to report status "On Station Ckeck-In" via F10 menu - this will activate the detection capabilities and broadcast messages to FAC client itself. Would be nice if will be able to change and set dynamically the detection mechanism via F10 commands (_UNITS, _TYPES, _AREAS)
**--// Step 2** - Client FAC unit should detect to itself and choose the unit to be designated via F10 menu. The designation method should be choose by FAC client itself (laser/smoke/illumination). Client FAC should be able to choose a specific Lase code from a given list via F10 commands. Would be useful that FAC client can retrieve the exact LL coordinates for itself so that they can pass this as voice info too their team. 
**--// Step 3** - Client AttackSet unit should be able to check for client FAC units in its proximity. Distance to communicate with FAC unit should be configurable but 50km is a starting point
**--// Step 4** - Attack unit should subscribe to a specific FAC unit as long as it is in its range. Client attack unit should retrieve data about the designated unit by client FAC via messages, but should not be able to change anything about them. Any request by the AttackSet should be made via voice comms or other external method like chat.
**--// Step 5** - While egress the combat zone the FAC client have to report "On station Check-Out" via F10 menu and drop all its subscribers.

Other considerations
--// Messages from FAC unit should  be seen by any AttackSet subscribed to that specific FAC client.
--// Client FAC should be able too see the AttackSets subscribed to it. It could worth that only a limited number of AttackSets subscribers may join.
--// An AttackSet should be able to unsubscribe from an FAC client and choose other if required.
--// If distance between FAC and Attackset is higher than the defined threshold then the AttackSet should drop is subscription and a notification message should be displayed.

Of course all above are subject for further discussions and process tuning.
I can see this functionality siting along with CTLD and CSAR to enhance the gameplay for DCS!

**Comment by Applevangelist** [comment]
Thanks! Will park this for the moment, unless someone else wants to pick this up earlier.

**Comment by thebgpikester** [comment]
Just curious, there was a massive gap between

should detect to itself  and .............................................................................................. choose the unit to be designated via F10 menu

There is no client detection method in the SSE. Are you suggesting to put a list of nearby units into the menu for picking? Seems like you can do this without relaly having to see the cleint at all. How do you match the group you see with the groups out fo the window?

**Comment by Abburo** [comment]
I think the video in the link below will describe more clearly what I am looking for. There are 2 main reasons asking this here. First reason is because the FAC script in rotorheads server is not publicly available. Second reason is having a MOOSE script which can integrates easily with the rest of MOOSE framework

[https://www.youtube.com/watch?v=RSZ_nvXDH5g&list=PLNusdZN7RU_zmvRVhHOD3bjZbAKhFtT0B&index=80](url)

**Comment by Applevangelist** [comment]
Naw, it's almost non-public: https://forum.dcs.world/topic/262118-gazdesignate-laser-designator-script-for-sa342m-gazelle/

**Comment by Abburo** [comment]
That script did not worked for me !

**Comment by thebgpikester** [comment]
You should ask the script owner for help/support on their script, if someone wants to port it to MOOSE then that up to them.

**Comment by Abburo** [comment]
Someone here ported CTLD with a great success to Moose. Why would be a different case for this new AFAC function? Don't really get your point to be honest... but hey... maybe there are better things on your table !

**Comment by Applevangelist** [comment]
That someone was me ;) mainly bc it wasn't further developed. That FAC video looks nice, I'll keep that as a Moose class on the to-do list

**Comment by Abburo** [comment]
I know @Applevangelist it was you behind the CTLD :) ... and the port is amazing especially because of the new features which came with it.
The FAC/AFAC should have been part of DCS vanilla same as the CTLD/CSAR scripts... but it is what it is. Really hope one day we could have a good MOOSE script for the AFAC.
