### ISSUE TITLE
Personal settings radio item appearing by default

### ISSUE THREAD

**Issue by SRF-NightOwl** [FlightControl-Master/MOOSE#1722]
This not a bug, but something where I need support. Since including Moose in our missions, which is great btw, we have personalised settings radio items populating the radio menu. They are named Settings "Player Name", and appear for several players at the same time (see screenshot). Is this some default Moose function which I could turn off? Or else, how could I prevent this from happening? Thanks for the help
![f10_menu_bug](https://user-images.githubusercontent.com/102836898/166157793-4ee8cf80-2f48-441d-b443-e9eed574ad57.png)

**Comment by Applevangelist** [comment]
Use  `_SETTINGS:SetPlayerMenuOff()` at the start of the first script you load after moose loading

**Comment by Applevangelist** [comment]
Support can be had in our Discord btw

**Comment by funkyfranky** [comment]
The strange thing is that multiple players appear. It should only be the current player in the aircraft.

**Comment by Applevangelist** [comment]
Yeah that’s weird. But then we don’t know what the script looks like for this mission

**Comment by SRF-NightOwl** [comment]
Awesome guys, thanks a lot for the very fast help!

**Comment by Applevangelist** [comment]
Can this now be closed?
