### ISSUE TITLE
SCORING - No longer is it crediting every player with a kill that contributed to it. 

### ISSUE THREAD

**Issue by Applevangelist** [FlightControl-Master/MOOSE#1726]
So I think something changed with SCORING and the most recent update. 

No longer is it crediting every player with a kill that contributed to it. 
-Pre update, every player that scored a hit on the target would receive the credit for the target when it died. Now it’s reverted to the ‘last player to touch the bandit before it dies’

I was wondering if anyone else was experiencing this and what I could change back end that would fix it? 

Moose just did this automatically previously and it’s a super awesome feature

**Comment by Fuzzy-Man-Peach** [comment]
heres a piece of my script - the rest of the scoring doc is other event based activity, but the shared kills were all a built in mechanic of the moose framework scoring. i also attached two screenshots of CSV exported stats from before the update and after. both are examples where two players shot another player. previously, ALL members that contributed to the kill would recieve the full credit. Now, it is only the last player to score a hit to receive any credit. 

thanks for taking a look at it:)





GameScore = SCORING:New("Scoring_St.Lo")
GameScore:SetMessagesToCoalition( true )
GameScore:SetScaleDestroyScore( 20 )
GameScore:SetScaleDestroyPenalty( 100 )
GameScore:SetMessagesZone( true )
GameScore:SetCoalitionChangePenalty( 0 )
GameScore:SetMessagesDestroy( true )
GameScore:SetMessagesScore( true )


------------
---------

Allied_Rear_oil = ZONE:New("Allied Rear DEPOT oil tankers")
GameScore:AddZoneScore( Allied_Rear_oil, 20 )
Allied_Rear_Factory = ZONE:New("Allied Rear DEPOT Factory")
GameScore:AddZoneScore( Allied_Rear_Factory, 60 )
Allied_Rear_Buildings = ZONE:New("Allied Rear DEPOT Base Buildings")
GameScore:AddZoneScore( Allied_Rear_Buildings, 10 )

Allied_Front_oil = ZONE:New("Allied Front DEPOT oil tankers")
GameScore:AddZoneScore( Allied_Front_oil, 20 )
Allied_Front_Factory = ZONE:New("Allied Front DEPOT Factory")
GameScore:AddZoneScore( Allied_Front_Factory, 60 )
Allied_Front_Buildings = ZONE:New("Allied Front DEPOT Base Buildings")
GameScore:AddZoneScore( Allied_Front_Buildings, 10 )



Axis_Rear_oil = ZONE:New("Axis Rear DEPOT oil tankers")
GameScore:AddZoneScore( Axis_Rear_oil, 20 )
Axis_Rear_Factory = ZONE:New("Axis Rear DEPOT Factory")
GameScore:AddZoneScore( Axis_Rear_Factory, 60 )
Axis_Rear_Buildings = ZONE:New("Axis Rear DEPOT Base Buildings")
GameScore:AddZoneScore( Axis_Rear_Buildings, 10 )

Axis_Front_oil = ZONE:New("Axis Front DEPOT oil tankers")
GameScore:AddZoneScore( Axis_Front_oil, 20 )
Axis_Front_Factory = ZONE:New("Axis Front DEPOT Factory")
GameScore:AddZoneScore( Axis_Front_Factory, 60 )
Axis_Front_Buildings = ZONE:New("Axis Front DEPOT Base Buildings")
GameScore:AddZoneScore( Axis_Front_Buildings, 10 )


AlliedNavy = ZONE:New("AlliedNavy")
GameScore:AddZoneScore( AlliedNavy, 10 )

AxisNavy = ZONE:New("AxisNavy")
GameScore:AddZoneScore( AxisNavy, 10 )






![After_update_score_example_CSV_](https://user-images.githubusercontent.com/104916455/166711246-0538e0b8-e90a-47ec-b474-5bd143c676d1.png)
![Before_update_score_example_CSV](https://user-images.githubusercontent.com/104916455/166711250-463eae9d-a5a7-4aff-9b4e-700e6788ccda.png)

**Comment by Applevangelist** [comment]
resolved
