### ISSUE TITLE
Developement version errors

### ISSUE THREAD

**Issue by Amarok73** [FlightControl-Master/MOOSE#1727]
I'd like to ask if the error codes listed below I am observing in the log have any significant impact. 
The version I am using right now is MOOSE GITHUB Commit Hash ID: 2022-05-06T06:01:18.0000000Z-092434a1035b2eed3014bcee60dcc33e6eb7f92d, and the errors are as follows:
INFO    SCRIPTING: Error in timer function: [string "e:\temp\DCS.openbeta_server\/~mis000005AF.lua"]:21807: attempt to perform arithmetic on local 'UnitFuel' (a nil value)
INFO    SCRIPTING: Error in SCHEDULER function:[string "e:\temp\DCS.openbeta_server\/~mis000005AF.lua"]:91941: attempt to index local 'CurrentVec2' (a nil value)
INFO    SCRIPTING: Error in SCHEDULER function:[string "e:\temp\DCS.openbeta_server\/~mis000005AF.lua"]:88394: attempt to index local 'TargetCoord' (a nil value)
INFO    SCRIPTING: Error in SCHEDULER function:[string "e:\temp\DCS.openbeta_server\/~mis000005AF.lua"]:13675: attempt to index local 'TargetCoordinate' (a nil value)
INFO    SCRIPTING: Error in SCHEDULER function:[string "e:\temp\DCS.openbeta_server\/~mis000005AF.lua"]:92009: attempt to index local 'CurrentVec2' (a nil value)
INFO    SCRIPTING: Error in SCHEDULER function:[string "e:\temp\DCS.openbeta_server\/~mis000005AF.lua"]:30925: attempt to index local 'DetectionGroupVec3' (a nil value)

**Comment by Applevangelist** [comment]
still more fallout from the dead event blunder. Fixed in the next build

**Comment by Applevangelist** [comment]
done
