### ISSUE TITLE
TASKING: Ensure that when a player crashes, it should be reflected correctly in the fired events.

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#173]

**Comment by thebgpikester** [comment]
I believe this was compelted with a negative score, anyone confirm?

**Comment by FlightControl-Master** [comment]
I need to retest this. It should raise a Fail event that can be captured by the MD to give negative scores or even fail the task.

**Comment by Grey-Echo** [comment]
Might be related, TSK-010 may contain a typo:
https://flightcontrol.slack.com/archives/C1KJU54KW/p1490647423850903

**Comment by FlightControl-Master** [comment]
Done.
