### ISSUE TITLE
Duplicate function

### ISSUE THREAD

**Issue by chump29** [FlightControl-Master/MOOSE#1735]
https://github.com/FlightControl-Master/MOOSE/blob/master/Moose%20Development/Moose/Core/Database.lua contains duplicate function: FindAirbase()

https://github.com/FlightControl-Master/MOOSE/blob/f50c374d04cb5164bbae55c58fe11eff56e484ef/Moose%20Development/Moose/Core/Database.lua#L217
https://github.com/FlightControl-Master/MOOSE/blob/f50c374d04cb5164bbae55c58fe11eff56e484ef/Moose%20Development/Moose/Core/Database.lua#L248

**Comment by chump29** [comment]
Pull request created @ https://github.com/FlightControl-Master/MOOSE/pull/1737

**Comment by Applevangelist** [comment]
Fixed
