### ISSUE TITLE
"attempt to index a nil value" in PSEUDOATC:LocalAirports()

### ISSUE THREAD

**Issue by chump29** [FlightControl-Master/MOOSE#1736]
https://github.com/FlightControl-Master/MOOSE/blob/f50c374d04cb5164bbae55c58fe11eff56e484ef/Moose%20Development/Moose/Functional/PseudoATC.lua#L952

This seems to happen for Late Activated ships. Noticed in the South Atlantic.

Possible solution:

local name=airbase:getName()
local a=AIRBASE:FindByName(name)
if a then
  local q=a:GetCoordinate()
  local d=q:Get2DDistance(pos)
  -- Add to table.
  table.insert(self.group[GID].player[UID].airports, {distance=d, name=name})
end

**Comment by Applevangelist** [comment]
Since you have a working solution, why not create a pull request?

**Comment by chump29** [comment]
Pull request created @ https://github.com/FlightControl-Master/MOOSE/pull/1737
