### ISSUE TITLE
Incorrect ATIS TTS readouts via SRS

### ISSUE THREAD

**Issue by rfdazzle** [FlightControl-Master/MOOSE#1740]
Couple of minor nitpicks when using SRS & MS TTS with ATIS:

- The wind heading is read aloud as, for example, 'Zero Seventy-One' instead of 'Zero Seven One'

- TACAN is read aloud as 'X' instead of 'X Ray'

I've included some suggested fixes in this PR: https://github.com/FlightControl-Master/MOOSE/pull/1739

**Comment by Applevangelist** [comment]
Fixed with #1739
