### ISSUE TITLE
Range unit movement not work

### ISSUE THREAD

**Issue by AzzameenF18** [FlightControl-Master/MOOSE#1753]
Hi, reviewing well all the documentation, I have come across the "randommove" RANGE.AddBombingTargets(targetnames, goodhitrange, randommove) function.

Well, I define it like this:
local bombtargets= {"Bomb1", "Bomb2", "Bomb3"}
local bombtargets2={"M1", "M2", "M3"}

Range:AddBombingTargets(bombtargets1, 50)
Range:AddBombingTargets(bombtargets2, 10, true)

But it still doesn't work (it gives me the valuation with the starting point of the moving unit. According to the documentation, the best thing to do is to make the route in the editor (I already have it made in the editor). But it does not "update" in the script the position of the objects M1, M2 and M3 (bombtargets2).

Thanks you

Edit:

M1, M2 and M3, are M113 with a circular route (last point goes to the first) put in immortal and driveable, this put in the editor

**Comment by Applevangelist** [comment]
Fixed with #1767

**Comment by AzzameenF18** [comment]
Hi, I have been testing, and now the range does detect hits to moving targets (and in the dcs.log they are as randommove YES). What I have noticed, that although I put route in the DCS editor, when executing the mission, these units move randomly, they do not follow the route.

Thank you very much!
