### ISSUE TITLE
New Razbam Carriers Not Integrated to Script

### ISSUE THREAD

**Issue by engines-wafu** [FlightControl-Master/MOOSE#1757]
Need to add the new carrier (HMS Invincible) introduced by Razbam in DCS 2.7.15.26783 Open Beta.

This should be similar to the Hermes and Canberra functionality.

**Comment by gavinedwards** [comment]
Working on inclusion in this fork: https://github.com/gavinedwards/MOOSE/tree/Engines_Invincible

**Comment by gavinedwards** [comment]
Functionality added.

**Comment by Applevangelist** [comment]
Closed
