### ISSUE TITLE
AID-CGO-300 - Airplane - Pickup and Deploy

### ISSUE THREAD

**Issue by voipmonitor** [FlightControl-Master/MOOSE#1768]
I'm trying this scenario - mission from the https://github.com/FlightControl-Master/MOOSE_MISSIONS/tree/develop/AID%20-%20AI%20Dispatching/AID-CGO%20-%20AI%20Cargo%20Dispatching/AID-CGO-300%20-%20Airplane%20-%20Pickup%20and%20Deploy 

The C-130 is picking up only one of the four infantry
After airplane arrives on Sochi-Adler, the unit is not deployed. 

I did no modifications - loaded the AID-CGO-300 - Airplane - Pickup and Deploy.miz and run mission

**Comment by Applevangelist** [comment]
That#s not something we intent to fix any more. Suggest to move to the dev branch and https://flightcontrol-master.github.io/MOOSE_DOCS_DEVELOP/Documentation/Ops.OpsTransport.html
