### ISSUE TITLE
ATIS Radio Relay Unit breaking simulation

### ISSUE THREAD

**Issue by Sci-fer** [FlightControl-Master/MOOSE#1812]
ATIS is totally breaking simulation when using SetRadioRelayUnitName() function. Exemples are as follows:

- ATIS stops
- Stops simulation of controls like thrust, flaps, radio e etc
- Aircraft attitude freezes
- Aircraft halts collision
- Aircraft passes through the ground falling into infinity

The log receives no entries related to that.

To reproduce just make an simple mission with a player and a parked unsimulated aircraft. And load the following code:
```
ATIS:
  New( 'Kutaisi' ):
  SetRadioRelayUnitName( 'Radio Relay Unit' ):
  Start()
```
I only tested it with C-101EB.

Thank you!

**Comment by funkyfranky** [comment]
Can you please attach you complete mission (miz) file (without any mods required) so I can test this.
Maybe you could also try with other airframes to rule out that is its a problem with the C-101EB, which would be on the DCS side of issues, we cannot fix. Just saying, because I (and many others) use this kind of script without any issues but I personally don't use the C-101.

**Comment by The-Scifer** [comment]
I just tested with UH-1H and had the same problems.
[ATIS.caucasus.zip](https://github.com/FlightControl-Master/MOOSE/files/9869192/ATIS.caucasus.zip)

**Comment by The-Scifer** [comment]
Also, I check my files integrity since the beginning with no corruptions found.

**Comment by funkyfranky** [comment]
I just jumped into your mission but could not reproduce the issue. But I remember that I had something similar also. It is however more than likely not something within the MOOSE code but rather a DCS issue with the commands used to transmit the radio messages:
https://wiki.hoggitworld.com/view/DCS_command_setFrequency
https://wiki.hoggitworld.com/view/DCS_command_transmitMessage

If you can save a DCS track file when this happens, I can file this issue in the DCS forum.

**Comment by cbruccoleri** [comment]
I am experiencing the same issue with the ATIS classes when using sound files and a single-player mission. Is there any workaround?

**Comment by funkyfranky** [comment]
@thebgpikester No, I am still looking for a working track to reproduce the issue. @Sci-fer 's track loads stuff from local directory so the track will not play on anyone else's machine.
