### ISSUE TITLE
No band allocation for ATIS

### ISSUE THREAD

**Issue by The-Scifer** [FlightControl-Master/MOOSE#1813]
While receiving ATIS transmission, UHF/VHF selector makes no difference. The ATIS VHF transmission goes on even when UHF is selected.

p.s. I only tested in C-101EB.

**Comment by The-Scifer** [comment]
I just tested it with the UH-1H and had the same problem.

This attached file is the same as https://github.com/FlightControl-Master/MOOSE/issues/1812
[ATIS.caucasus.zip](https://github.com/FlightControl-Master/MOOSE/files/9869192/ATIS.caucasus.zip)

**Comment by Applevangelist** [comment]
Cannot replicate. I don't have the C-101B, but tested in the Mirage 2000, which has a combined AM/FM and an extra AM radio. Here everything works like expected. Looks like a C101B bug to me

**Comment by funkyfranky** [comment]
I also do not quite understand the issue. I would understand it for FM vs AM modulation but not for a frequency range.

**Comment by Applevangelist** [comment]
Dcs bug
