### ISSUE TITLE
Feature Request: Expanded "Nothing" AUFTRAG

### ISSUE THREAD

**Issue by Frozeph** [FlightControl-Master/MOOSE#1823]
Would it be possible to expand the AUFTRAG:NewNOTHING to be something akin to a "Ground ALERT5"?

You specify another AUFTRAG along with the Nothing one similar to ALERT5, then for those AUFTRAGs the Nothing groups are sent first.

**Comment by Applevangelist** [comment]
That's exactly what Alert5 does - what should be a useful difference?

**Comment by Frozeph** [comment]
wait ALERT5 works for ground units, and a zone?

**Comment by Frozeph** [comment]
https://discord.com/channels/378590350614462464/733434325412085791/968032423306752000 
relevent DISCORD discussion - was the initial proposition for the "Stageing" area idea

but I agree if ALERT5 could be used on ground units and specify a zone away from brigade spawn location then there wouldn't be a use for the NOTHING auftrag

**Comment by funkyfranky** [comment]
The `NOTHING` type AUFTRAG is indeed already the ground version of an `ALERT5` for air. Ground assets on that type of mission will be preferred over assets that are unspawned in the BRIGADE/WAREHOUSE.

Here is a demo mission for illustration https://github.com/FlightControl-Master/MOOSE_MISSIONS/tree/develop/OPS%20-%20Brigade/Brigade%20-%20050%20-%20Ground%20Attack
