### ISSUE TITLE
Task Report- Planned

### ISSUE THREAD

**Issue by ChumBombarda** [FlightControl-Master/MOOSE#1832]
[PvE-TEST.zip](https://github.com/FlightControl-Master/MOOSE/files/9964940/PvE-TEST.zip)
sometimes is working fine. 
another times the task report(planned) is working in all missions less for 1.
noticed in my a2a mission, if is 1 unit missing from the mission, the task report will not work, only afther all units are spawn.
but ussualy the mission that get this error more often is the a2g missions(using manual task's)
so i dont know if problem with my mission or mosse but the error i get is this.

MOOSE error in MENU COMMAND function: [string "Scripts/Moose/Wrapper/Unit.lua"]:1176: attempt to index local 'Attributes' (a nil value) 
19:55:37.818  INFO  SCRIPTING  stack traceback: [string "Scripts/Moose/Core/Menu.lua"]:307: in function <[string "Scripts/Moose/Core/Menu.lua"]:304> [string "Scripts/Moose/Wrapper/Unit.lua"]:1176: in function 'GetThreatLevel' [string "Scripts/Moose/Core/Set.lua"]:2626: in function 'CalculateThreatLevelA2G' [string "Scripts/Moose/Tasking/Task_A2G.lua"]:321: in function 'UpdateTaskInfo' [string "Scripts/Moose/Tasking/Task_A2G.lua"]:289: in function 'ReportOrder' [string "Scripts/Moose/Tasking/Mission.lua"]:1058: in function <[string "Scripts/Moose/Tasking/Mission.lua"]:1058> (tail call): ? [C]: in function 'sort' [string "Scripts/Moose/Utilities/Utils.lua"]:662: in function 'spairs' [string "Scripts/Moose/Tasking/Mission.lua"]:1058: in function 'ReportOverview' [string "Scripts/Moose/Tasking/Mission.lua"]:1170: in function <[string "Scripts/Moose/Tasking/Mission.lua"]:1168> (tail call): ? [C]: in function 'xpcall' [string "Scripts/Moose/Core/Menu.lua"]:318: in function <[string "Scripts/Moose/Core/Menu.lua"]:314>

the only change i did was this. and before i updated to the last Moose was working fine.
![original moose file](https://user-images.githubusercontent.com/108042141/200668374-1efc8ffb-bf56-45f3-b3f1-32d8c1286010.PNG)
![edited moose file](https://user-images.githubusercontent.com/108042141/200668387-a70a2d11-21f7-4453-b1b0-f560b4a71154.PNG)

P.S: dindt saw this last update from 6h ago. maybe this problem has been solved. sorry if so.

**Comment by ChumBombarda** [comment]
Most probably can be dcs bug...
is so random... first time i restarted server task report wasnt working in 1 mission. 
2 time i restarted, the task report was working in all missions.
3 time working fine aswell
4 time not working again.
and last time, task report(planned) is working fine again on all missions.

**Comment by Applevangelist** [comment]
The location of the error is interesting- a variable became nil while the function is running. Since we haven’t touched that code lately, I think it’s a memory chip issue on your HW more likely. Or a disk problem if memory is swapped in/out. Randomness of occurrence also points in that direction

**Comment by ChumBombarda** [comment]
well using old pc as server so probably thats is the issue... RIP

**Comment by ChumBombarda** [comment]
well i tried on new pc and is same thing... do i dont know if is hw or memory issue.
can be problem of my mission. but well just wanted to let you know
