### ISSUE TITLE
Intel Errors

### ISSUE THREAD

**Issue by Frozeph** [FlightControl-Master/MOOSE#1836]
> 2022-11-09 22:02:56.989 INFO    SCRIPTING (Main):  80474( 68571)/I:                         CHIEF07088.onafterStatus(General Abbas al-Musawi (Red) | Status Running [Agents=18]: Contacts=0, Clusters=0, New=0, Lost=0)
> 2022-11-09 22:02:56.990 INFO    SCRIPTING (Main):  68653(    -1)/I:                         CHIEF07088.function(General Abbas al-Musawi (Red) | Defcon=Green Strategy=Defensive: Assets=628, Contacts=0 [Border=0, Conflict=0, Attack=0], Targets=0, Missions=2)
> 2022-11-09 22:03:22.506 INFO    SCRIPTING (Main):  93794(    -1)/I:          PLAYERTASKCONTROLLER05892.function(New Targets: 00 | Active Tasks: 06 | Active Players: 00 | Assigned Tasks: 00)
> 2022-11-09 22:03:26.829 INFO    SCRIPTING (Main):  80461(    -1)/I:                         INTEL21427.function(Focus (Blue) | Starting INTEL v0.3.4)
> 2022-11-09 22:03:33.952 INFO    SCRIPTING (Main): Error in SCHEDULER function:[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:80534: attempt to call method 'GetUnitCategory' (a nil value)
> 2022-11-09 22:03:33.952 INFO    SCRIPTING (Main): stack traceback:
> 	[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:8032: in function 'GetUnitCategory'
> 	[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:80534: in function 'UpdateIntel'
> 	[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:80469: in function <[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:80465>
> 	(tail call): ?
> 	[C]: in function 'xpcall'
> 	[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:8036: in function '_call_handler'
> 	[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:8114: in function <[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:8042>
> 	(tail call): ?
> 	[C]: in function 'xpcall'
> 	[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:11152: in function <[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:11114>
> 2022-11-09 22:03:52.766 INFO    SCRIPTING (Main):  93794(    -1)/I:          PLAYERTASKCONTROLLER05892.function(New Targets: 00 | Active Tasks: 06 | Active Players: 00 | Assigned Tasks: 00)
> 2022-11-09 22:03:57.250 INFO    SCRIPTING (Main):  80474( 68571)/I:                         CHIEF07088.onafterStatus(General Abbas al-Musawi (Red) | Status Running [Agents=18]: Contacts=0, Clusters=0, New=0, Lost=0)
> 2022-11-09 22:03:57.250 INFO    SCRIPTING (Main):  68653(    -1)/I:                         CHIEF07088.function(General Abbas al-Musawi (Red) | Defcon=Green Strategy=Defensive: Assets=628, Contacts=0 [Border=0, Conflict=0, Attack=0], Targets=0, Missions=2)

The above error message has started appearing after no change to my script only updating Moose_.lua file, current version in use. 

I am unable to pinpoint exactly when it triggers, I think it's when a blue ground unit leaves its border. 

Initally I thought it was due to an overlap in borders but I confirmed that wasn't the case. Apart from that I have no idea what could be causing it. I'm happy to investigate further but would need some test cases as I'm stumped

**Comment by funkyfranky** [comment]
The error is that `GetUnitCategory` does not exist on the object it is applied to. It is used when INTEL:SetFilterCategory() is used and would fail if a STATIC object is detected because that function does not exist for STATIC object.

I'll add a check to ensure that the object is a UNIT and not a STATIC object if that filter is applied.

**Comment by Frozeph** [comment]
thank you so much, updated and testing now

**Comment by Frozeph** [comment]
Also that makes total sense, it was the Drone doing the detecting which explains the why it was only happening occationally (only when the drone saw the unit)
