### ISSUE TITLE
CHIEF:AddTarget error in GetThreatLevelMax

### ISSUE THREAD

**Issue by Frozeph** [FlightControl-Master/MOOSE#1839]
>  2022-11-10 01:02:59.198 INFO    SCRIPTING (Main):  80440( 68550)/I:                         CHIEF07088.onafterStatus(General Abbas al-Musawi (Red) | Status Running [Agents=12]: Contacts=0, Clusters=0, New=0, Lost=0)
> 2022-11-10 01:02:59.198 INFO    SCRIPTING (Main): Error in SCHEDULER function:[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:68822: attempt to call method 'GetThreatLevelMax' (a nil value)
> 2022-11-10 01:02:59.198 INFO    SCRIPTING (Main): stack traceback:
> 	[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:8028: in function 'GetThreatLevelMax'
> 	[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:68822: in function 'CheckTargetQueue'
> 	[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:68594: in function <[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:68549>
> 	(tail call): ?
> 	[C]: in function 'xpcall'
> 	[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:8032: in function '_call_handler'
> 	[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:8110: in function <[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:8038>
> 	(tail call): ?
> 	[C]: in function 'xpcall'
> 	[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:11140: in function <[string "C:\Users\aclav\Documents\GitHub\MOOSE_INCLUDE\Moose_Include_Static\Moose_.lua"]:11102>
> 2022-11-10 01:03:00.107 ERROR   APP (Main): Error: Unit [MQ-9 Reaper]: Corrupt damage model.

Sorry to be a pain, I just added the following line to script and invoked the above

`RedChief:AddTarget(GROUP:FindByName("Ground"))`

1 apc unit with a group name of Ground was active on map

**Comment by Applevangelist** [comment]
Read the manial pls. `AddTarget()` requires a Ops.Target#TARGET object to be added, not just a group. What you want is:
`RedChief:AddTarget(TARGET:New(GROUP:FindByName("Ground")))`
Appreciate if u start asking questions in our DISCORD before raising tickets here

**Comment by Frozeph** [comment]
I appologise for this one it was very late, but you know as well as I do, I ask questions in DISCORD and I try to really only raise issues when I'm totally sure it's an issue.

**Comment by Applevangelist** [comment]
No worries
