### ISSUE TITLE
PLAYERTASKMANAGER - Add actual target coordinates to the task info display

### ISSUE THREAD

**Issue by rollnthndr** [FlightControl-Master/MOOSE#1841]
Currently we see the BR/BRA call in the info that is displayed. I'd like to add the actual coordinates either along side or maybe optionally either/or determined by the addition of a new PLAYERTASKMANAGER setting.

I guess my questions are...

- Do you mind if I add this?
- If it's ok, any guideline you'd like me to follow?

**Comment by Applevangelist** [comment]
If you have an implementation suggestion go ahead. Mind you that the display is dependent on the user settings, eg if a user wants MGRS he gets MGRS already …

**Comment by rollnthndr** [comment]
Ok, I will check my user settings first.

**Comment by Applevangelist** [comment]
Implemented

**Comment by rollnthndr** [comment]
Ok, thank you!
