### ISSUE TITLE
CHIEF Capture Zone and Mi-8

### ISSUE THREAD

**Issue by phr0gz** [FlightControl-Master/MOOSE#1842]
Hello, I can't have zone capture working with a Mi-8 as the transport vehicle. If I change the Mi8 to a ch47d it's working.
[POC_chief_cap_mi8.miz.zip](https://github.com/FlightControl-Master/MOOSE/files/9992782/POC_chief_cap_mi8.miz.zip)

**Comment by funkyfranky** [comment]
Have not checked, but it is probably registered as an attack helo and not as a transport helo and only transport helos are considered for OPSTRANSPORT missions.

Try settting: `Red.Squadrons.MI8:SetAttribute(GROUP.Attribute.AIR_TRANSPORTHELO)`

Also setting `Red.Squadrons.MI8:SetTakeoffHot()` might cause problems with transports. They have to wait until the troops have finished boarding. That is only possible in cold+uncontrolled state. If the helos are spawned hot, they might just fly away before they loaded everything which probably confuses the script.

**Comment by phr0gz** [comment]
Thx, It make sense!
I tried to set the attribute without success.
`Red.Squadrons.MI8:SetAttribute(GROUP.Attribute.AIR_TRANSPORTHELO)`
`Red.Squadrons.MI8:SetAttribute("Air_TransportHelo")`

I have the following error:
```
2022-11-12 00:04:24.057 ERROR   SCRIPTING (Main): Mission script error: [string "C:\Users\phr0g\AppData\Local\Temp\DCS.openbeta\/~mis000061D0.lua"]:117: attempt to call method 'SetAttribute' (a nil value)
stack traceback:
	[C]: in function 'SetAttribute'
	[string "C:\Users\phr0g\AppData\Local\Temp\DCS.openbeta\/~mis000061D0.lua"]:117: in main chunk
```

**Comment by funkyfranky** [comment]
Strange error if you apply it to a SQUADRON object as this function certainly exists https://flightcontrol-master.github.io/MOOSE_DOCS_DEVELOP/Documentation/Ops.Squadron.html##(SQUADRON).SetAttribute

But I'll also add a demo mission soon, where this is also needed for an UH-1H because that is also registered as an attack helo.

**Comment by phr0gz** [comment]
I upgraded moose to the last dev, and no error.
