### ISSUE TITLE
Increase report planned task list size

### ISSUE THREAD

**Issue by ChumBombarda** [FlightControl-Master/MOOSE#1843]
is possible to increase the size of the box for the report planned task's?
all the task's avaialble on the mission are not showing up.
in my case is just 1 task missing from the report... but if 1 task get completed, the  task missing from the report planned will show up 

this why i believe an increase of the text box for the report planeed task will solve the problem.
![planned report](https://user-images.githubusercontent.com/108042141/201465534-53f3598a-2e57-4c8e-a3e8-5294e6060f0e.PNG)
in this report only the *NAVAL TASK#HARD* is missing from the report.

**Comment by Applevangelist** [comment]
No that’s a fixed size on DCS side

**Comment by ChumBombarda** [comment]
function MISSION:ReportOverview( ReportGroup, TaskStatus )

  self:F( { TaskStatus = TaskStatus } )

  local Report = REPORT:New()

  -- List the name of the mission.
  local Name = self:GetText()
  
  -- Determine the status of the mission.
  local Status = "<" .. self:GetState() .. ">"

  Report:Add( string.format( '%s - %s - %s Tasks Report', Name, Status, TaskStatus ) )
  
  -- Determine how many tasks are remaining.
  local Tasks = 0
  for TaskID, Task in UTILS.spairs( self:GetTasks(), function( t, a, b ) return t[a]:ReportOrder( ReportGroup ) <  t[b]:ReportOrder( ReportGroup ) end  ) do
    local Task = Task -- Tasking.Task#TASK
    if Task:Is( TaskStatus ) then
      Report:Add( string.rep( "-", 140 ) )
      Report:Add( Task:ReportOverview( ReportGroup ) )
    end
    Tasks = Tasks + 1
    if Tasks >= 8 then   *changed to 10 and now all task's show up*
      break
    end
  end

  return Report:Text()
end


wasnt make any sense if another's reports almost cover all screen from top to bottom and only the planned report was having a limit. couldnt be.

**Comment by Applevangelist** [comment]
No should be allright
