### ISSUE TITLE
Trim the DCS appended unique identifies in unit names if only one unit exists in the group.

### ISSUE THREAD

**Issue by Drofseh** [FlightControl-Master/MOOSE#1848]
I've recently started using RAT to have ambient aircraft in the mission I'm working on. Something I find a little immersion breaking is that when an aircraft lands the ATC sends the following message

Take landing, the ATC sends this message:
`string.format("ATC %s: Flight %s landed. Welcome to %s.", dest, name, dest)`

The `name` provided seems to be gotten using the DCS func `getName` and it includes the unique identifier assigned to the unit.

This means if I make an ambient flight like this
```
local Cessna_1 = RAT:New("Cessna N13BJ")
Cessna_1:Spawn(1)
```
When the only aircraft in the group goes to land the ATC will send the message
`ATC AIRFIELD: Flight Cessna N13BJ#001 landed. Welcome to AIRFIELD.`

Having the `#001` identifier makes the message look very odd, and I think trimming the string would make it appear a lot more natural.

**Comment by Applevangelist** [comment]
Looking into this - need to do some checks but an easy addition

**Comment by Drofseh** [comment]
That was super fast, thanks very much!
