### ISSUE TITLE
UTILS.SaveSetOfGroups Save Unit Types *Enhancement*

### ISSUE THREAD

**Issue by patpatpowercat** [FlightControl-Master/MOOSE#1855]
It would be nice if the SaveSetOfGroups saved the group composition (ie unit types as well). This would allow you to have mixed PLATOONS, better support SAM groups, have JTACs in a group, etc, without randomly losing a unit. A mechanized platoon with attached SA-19 would lose just the SA-19, rather than potentially (most likely due to random) losing a BMP instead. A SAM could have degraded launchers, but still have radars up, or if radars destroyed, be non functional rather than potentially changing from lost radar to lost launcher on LoadSet. 

The SPGG script (https://forum.dcs.world/topic/307157-spgg-simple-persistent-ground-groups/) does accomplish this with using MIST and establishing a table of groups (if that helps with scripting ideas), but integrated MOOSE support would work with all things MOOSE!

**Comment by Applevangelist** [comment]
Implemented
