### ISSUE TITLE
UTILS.SaveSaveSetOfStatics/SaveStationaryListOfStatics capture "DEAD" *ENHANCEMENT*

### ISSUE THREAD

**Issue by patpatpowercat** [FlightControl-Master/MOOSE#1856]
Don't know if this would be possible. But for static lists, it would be nice if when saving the STATIC as  dead, it loaded the static as having the "DEAD" box from mission editor checked, rather than just not loading it back. This would allow you to persistently carry over statics that are destroyed, without needing to modify a script that references that static.

For example, BLUE_WAREHOUSE is a static that an AIRWING/BRIGADE uses. If it spawns but in a dead state, the script still works, and the AIRWING is non-functional, same as if a bomb struck it during mission. If it doesn't load back at all, the script breaks.

**Comment by Applevangelist** [comment]
Implemented
