### ISSUE TITLE
Use PlayerName or UnitName when referring to the player in PseudoATC messages.

### ISSUE THREAD

**Issue by Drofseh** [FlightControl-Master/MOOSE#1864]
At present most PseudoATC messages use Callsign when referring to the player.

For example in function PSEUDOATC:ReportHeight:
`local _text=string.format("%s, your altitude is %s AGL.", callsign, Hs)`

or in function PSEUDOATC:PlayerTakeOff
`local text=string.format("%s, %s, you are airborne. Have a safe trip!", place, CallSign)`

I think it would be better if messages like these used either the PlayerName or the UnitName, as in my experience these are what matter to the player instead of the very limited callsign selection that ED allows in the mission editor.

**Comment by Applevangelist** [comment]
Should be there in the next build - #1870

**Comment by Drofseh** [comment]
Thank you!
