### ISSUE TITLE
Cargo unload

### ISSUE THREAD

**Issue by ChumBombarda** [FlightControl-Master/MOOSE#1865]
INFO    SCRIPTING (Main): Error in SCHEDULER function:[string "Scripts/Moose/Wrapper/Unit.lua"]:232: bad argument #1 to 'pairs' (table expected, got nil)

unload not working... still receive the message but the cargo dont get unload.

**Comment by Applevangelist** [comment]
Em, look at the code above it tries to get a GROUP object from some UNIT and then the Units from that group. Which is nil by the error message. What's your code invoking that function?

**Comment by ChumBombarda** [comment]
2023-01-02 13:28:31.976 INFO    SCRIPTING (Main):   1035(   227)/E:                         GROUP26924.GetVec3(ERROR: Cannot get Vec3 of group GOE TACTICAL SEN#004#CARGO)
2023-01-02 13:28:31.976 INFO    SCRIPTING (Main): Error in SCHEDULER function:[string "Scripts/Moose/Wrapper/Unit.lua"]:232: bad argument #1 to 'pairs' (table expected, got nil)
2023-01-02 13:28:31.976 INFO    SCRIPTING (Main): stack traceback:
                [string "Scripts/Moose/Core/Fsm.lua"]:634: in function <[string "Scripts/Moose/Core/Fsm.lua"]:631>
                [C]: in function 'pairs'
                [string "Scripts/Moose/Wrapper/Unit.lua"]:232: in function 'ReSpawnAt'
                [string "Scripts/Moose/Cargo/CargoUnit.lua"]:110: in function <[string "Scripts/Moose/Cargo/CargoUnit.lua"]:72>
                (tail call): ?
                [C]: in function 'xpcall'
                [string "Scripts/Moose/Core/Fsm.lua"]:642: in function '_call_handler'
                [string "Scripts/Moose/Core/Fsm.lua"]:765: in function <[string "Scripts/Moose/Core/Fsm.lua"]:654>
                (tail call): ?
                [C]: in function 'xpcall'
                [string "Scripts/Moose/Core/ScheduleDispatcher.lua"]:225: in function <[string "Scripts/Moose/Core/ScheduleDispatcher.lua"]:169>

**Comment by Applevangelist** [comment]
Thanks I meant the script you created not the error log... :)

**Comment by ChumBombarda** [comment]
CargoDispacther = TASK_CARGO_DISPATCHER:New(TransportMission,Transport)

Goe_Assault = CargoDispacther:AddTransportTask("SENAKI TACTICAL FORCE",Assault_ops_senaki_set,"Infantry Assault")
Goe_Assault2 = CargoDispacther:AddTransportTask("SENAKI BATTALION",Assault_platton_senaki_set,"Infantry Assault")
Goe_Assault3 = CargoDispacther:AddTransportTask("NOVOROSSIYSK TACTICAL FORCE",Assault_ops_novo_set,"Infantry Assault")
Goe_Assault4 = CargoDispacther:AddTransportTask("NOVOROSSIYSK BATTALION",Assault_platton_novo_set,"Infantry Assault")
CargoDispacther:SetTransportDeployZone(Goe_Assault,ZONE_DROP_COUNT_SOUTH_ASSAULT)
CargoDispacther:SetTransportDeployZone(Goe_Assault,ZONE_DROP_COUNT_NORTH_ASSAULT)
CargoDispacther:SetTransportDeployZone(Goe_Assault2,ZONE_DROP_COUNT_SOUTH_ASSAULT)
CargoDispacther:SetTransportDeployZone(Goe_Assault2,ZONE_DROP_COUNT_NORTH_ASSAULT)
CargoDispacther:SetTransportDeployZone(Goe_Assault3,ZONE_DROP_COUNT_SOUTH_ASSAULT)
CargoDispacther:SetTransportDeployZone(Goe_Assault3,ZONE_DROP_COUNT_NORTH_ASSAULT)
CargoDispacther:SetTransportDeployZone(Goe_Assault4,ZONE_DROP_COUNT_SOUTH_ASSAULT)
CargoDispacther:SetTransportDeployZone(Goe_Assault4,ZONE_DROP_COUNT_NORTH_ASSAULT)

**Comment by ChumBombarda** [comment]
humm i tihnk thats is all... or you want the set groups too?

**Comment by Applevangelist** [comment]
No but the miz would be nice for debugging/testing

**Comment by ChumBombarda** [comment]
ah ok ... you want with static or dynamic loader?

**Comment by Applevangelist** [comment]
Doesn't matter, I'll replace

**Comment by ChumBombarda** [comment]
[PvE-Training.zip](https://github.com/FlightControl-Master/MOOSE/files/10331928/PvE-Training.zip)

**Comment by ChumBombarda** [comment]
ok i think that is all

**Comment by ChumBombarda** [comment]
set groups are top of page... the cargo dispatcher is on the end of file

**Comment by ChumBombarda** [comment]
humm since you are testing stuffs... can you check the the message settings too?

i can change all the message timer settings, but the details message setting is the only setting i cant change.

**Comment by Applevangelist** [comment]
You're trying to make GROUPs directly into a SET_CARGO
`Assault_ops_senaki_set = SET_CARGO:New():FilterPrefixes("GOE TACTICAL SEN"):FilterStart()`
but those actually are not cargo groups, which you need to create first, so
`Assault_ops_senaki = CARGO_GROUP:New( GROUP:FindByName("GOE TACTICAL SEN"), "Infantry Sen", "GOE TACTICAL SEN", 125, 75 )
Assault_ops_senaki_set = SET_CARGO:New():FilterPrefixes("Infantry Sen"):FilterStart()`

**Comment by Applevangelist** [comment]
Also there are lot of funny UTF-8 chars in your other SETs, I don't think that's a wise idea, even if it looks cool.

**Comment by Applevangelist** [comment]
For reference: https://github.com/FlightControl-Master/MOOSE_MISSIONS/blob/master/TAD%20-%20Task%20Dispatching/CGO%20-%20Cargo%20Task%20Dispatching/TAD-CGO-003%20-%20Transport%20Test%20-%20Infantry%20and%20Crate/TAD-CGO-003%20-%20Transport%20Test%20-%20Infantry%20and%20Crate.lua

**Comment by ChumBombarda** [comment]
oh ok. i did this script so long time ago and everthing was working fine in that moment...
but will changed later so. ty for info.

**Comment by Applevangelist** [comment]
If that doesn't compute then there's an API issue with ED to not be able to get a unit list of non-active groups ... we can fix this in the said line in UNIT, but it won't spawn any units for you then (at least the script doesn't stop then)

**Comment by ChumBombarda** [comment]
humm... kk, im just a noob trying to make a simple mission to friends, but ty for help will keep playing with the code until i got it right xD

**Comment by ChumBombarda** [comment]
well i tried with the code you sent me and still got the same problem.
2 weeks ago everthing was working fine... i was able to unload the cargo. since i put the last updated MOOSE the cargo unload stoped working. probably is a issue from your side.

**Comment by ChumBombarda** [comment]
ye i tried many times just to have sure.... using your code or mine have the same results.
the error says cant get the coords to unload the cargo... is like missing 1 type of coord info. 
i just reported my issue and i saw other people in discord having the same problem.
i think the issue is from MOOSE.

**Comment by Applevangelist** [comment]
BAck at my desk. Fixed in the next build

**Comment by ChumBombarda** [comment]
ok ty for all info and support. wish you a nice day.
MOOSE Team <3

**Comment by ChumBombarda** [comment]
Cargo unload working 
Ty for quick fix.
