### ISSUE TITLE
scenery wrapper :Destroy() does not work

### ISSUE THREAD

**Issue by Shark149** [FlightControl-Master/MOOSE#1875]
Hi team,
When attempting to use the destroy function for objects in scenery wrapper, the code stops executing. A quick look inside moose.lua and I cannot see a scenery:Destroy() type function 

Example code:

	local sset = SET_SCENERY:NewFromZone(zone):FilterOnce()
	sset:ForEachScenery(function (scen) 
		scen:Destroy()
	end)

Thanks.

**Comment by Applevangelist** [comment]
Last time I tried that it crashed the game immediately

**Comment by Applevangelist** [comment]
Hence not implemented.

**Comment by Shark149** [comment]
apologies for not doing the research - Closing
