### ISSUE TITLE
Problems with debbuger with 2.8.1.34667

### ISSUE THREAD

**Issue by rosly** [FlightControl-Master/MOOSE#1876]
Have following error in dcs.log with debugger.lua script
load error Scripts/Mission Scripting.lua:[string ".\debugger.lua"]:182: attempt to call field 'getregistry' (a nil value).

**Comment by MitchDart** [comment]
I'm getting the same issue. Wanted to try and set up the Debugger but seems like debug.getregistry() no longer works in the new version of DCS.

**Comment by Applevangelist** [comment]
No a moose issue
