### ISSUE TITLE
(SUGGESTION) Tutorial/demo to show the easier way to get started with MOOSE

### ISSUE THREAD

**Issue by birgersp** [FlightControl-Master/MOOSE#188]
I've had some discussions regarding the level of complexity and sheer magnitude of MOOSE, and I claim there are players (especially people inexperienced with coding) that find it a bit hard to get started with MOOSE.

I suggest to make a "super-easy" demo that strips any "nice-to-know" details and sticks to "need-to-know" basics to just get a grasp on what MOOSE can do and how simply one can get started.

I think the following steps can be helpful when considering just how "basic" and "dumbed down" such a demo should be:

(Seen from the point of an imagined DCS and/or coding rookie)

> 1. Why should I keep reading this text or watching this? Impress me in 10 seconds or I'll go watch TV instead.
> 2. What do I NEED to do the same cool thing I just saw? (Not what I *should* have, or what I *can* have, only a bare minimum)
> 3. Is there something else I should know about (like, is there some computer program that would be really helpful (Eclipse, for instance))?
> 4. I got an idea on something I want to do with my mission, I'd like to easily find a clean example of it that doesn't confuse me with things I'm not looking for.
> 5. This was fun! Now I'm gonna try stuff from other examples.
> 6. (6 months later) Okay I'm ready to look at the API

**Comment by FlightControl-Master** [comment]
Which videos did you watch?

**Comment by FlightControl-Master** [comment]
This video exists.... https://www.youtube.com/watch?v=-Hxae3mTCE8

**Comment by FlightControl-Master** [comment]
I understand you points Birger, thank you for your feedback.

**Comment by thebgpikester** [comment]
I think in other words, we need content creators making great misisons with MOOSE and then it will sell itself. The issue is the complexity of MOOSE which hinders uptake. I can relate to this personally. I'm actively working on solving this right now.

**Comment by birgersp** [comment]
The steps are crude but in my experience, very real. The quality of the video (and, all your videos) is really good but it is long and packed with details. For the casual mission-designer I fear it is a bit too overwhelming.

**Comment by entropySG** [comment]
Thats why I think the most recent videos about the SPAWN class are perfect. Short, concise and to the point.

Well done!

best,

Entropy from the 132nd

________________________________
