### ISSUE TITLE
Addition of CJS Superhornet Mod to AIRBOSS class *Feature Request*

### ISSUE THREAD

**Issue by patpatpowercat** [FlightControl-Master/MOOSE#1884]
With the CJS Superhornet 2.0, it no longer overwrites the F-18C files. However this means that AIRBOSS no longer recognizes them as carrier capable aircraft. The flight model is still the same as the F-18C, so groove/hook alignment/etc should carry over directly. The new unit names are: "FA-18E", "FA-18F", "EA-18G". I think the HORNET code from the AIRBOSS class could be copy-pasted, utilizing RHINO="FA-18E" and "FA-18F" and GROWLER="EA-18G". The only thing that would need to be added is potentially some soundfiles for "Rhino" and "Growler".

**Comment by funkyfranky** [comment]
I have added these types. Please test in master or develop branch.

**Comment by patpatpowercat** [comment]
Seems to be working, thanks!

**Comment by funkyfranky** [comment]
Thanks for the feedback @patpatpowercat
