### ISSUE TITLE
Pseudo ATC - Append waypoint name to number.

### ISSUE THREAD

**Issue by Drofseh** [FlightControl-Master/MOOSE#1885]
In the PseudoATC F10 menu the waypoints are displayed only by their number. I think it would be benificial if it also showed the name of the waypoint.

For example, if waypoint 2 is named Join, display it as `Waypoint 2: Join` or `Waypoint 2 - Join` instead of just `Waypoint 2`

**Comment by Applevangelist** [comment]
Added

**Comment by Drofseh** [comment]
Thank you very much!
