### ISSUE TITLE
Repair Vehicle (ground unit)

### ISSUE THREAD

**Issue by Abburo** [FlightControl-Master/MOOSE#1896]
Hello,

An idea for a new feature would be to have a ground vehicle capable to provide repairs to any friendly units.
It can be any sort of ground vehicle but the ammo trucks, because ammo trucks are having another logistic role.

From functionality perspective, the repair unit would be nice to have the capability to search and assess health status for vehicles in a specified radius, then move close to the units to be repaired. A repair time would add more realism and the vehicles should stand still during repair. 

Besides adding more scope to the logistic capabilities for rotorheads, this feature can help when we have groups of units. In case one unit is hit, it's speed is heavily decreasing and this is making the entire group hard to operate.

Another nice to have feature for this "repair vehicle" would be the possibility to build reinforcements on the field like statics sand bags for example (via F10 mark).... but i might digress. :)

This "repair unit" idea was actually implemented on the FrenchPack mod for DCS, however that is not very reliable and is generating various errors. Having it in Moose will ensure a seamless environment to work with.

**Comment by Applevangelist** [comment]
Great! Awaiting your code!

**Comment by Abburo** [comment]
I would like to write such a code, but besides changing the scripts provided by MOOSE to tune to some of my preferences I am not having programming skills.

If that is something out of your interest please feel free to close these, as would be perfectly understandable.
Your work on MOOSE is already beyond passion ! Thank you!

**Comment by Abburo** [comment]
I would like to write such a code, but besides changing the scripts provided by MOOSE to tune to some of my preferences I am not having programming skills.

If that is something out of your interest please feel free to close these, as would be perfectly understandable.
Your work on MOOSE is already beyond passion ! Thank you!

**Comment by Applevangelist** [comment]
Well everyone started somewhere ;)

**Comment by Applevangelist** [comment]
Started this some time ago, but it does not make much sense as I cannot repair a single unit. I'd need to respawn the group which gives it full health & ammo

**Comment by Abburo** [comment]
Understood, that will be fine. Thank you having a look into that!
