### ISSUE TITLE
Ammo Truck TTL (time to live)

### ISSUE THREAD

**Issue by Abburo** [FlightControl-Master/MOOSE#1897]
Hello,

In order to add more immerse for logistic operations would be nice that Ammo Trucks to have a limited life time.
The operational life time could rely on either time alive or even better on the number of rearm events they are triggering.

Also, we have various type of ammo trucks in DCS and they can have different loading capacity (M939 big truck vs Opel Blitz small truck).   Would be great if we can have configurable loading capacity as this will make more sense to define them differently in CTLD. For example 2 heavy crates for M939 and one lighter crate for Opel Blitz to reflect its utility.

Don't know if this would make sense for more people so the developing time would be worthy.
Thank you!

**Comment by Applevangelist** [comment]
Sure! By when can you complete the additional code?

**Comment by Applevangelist** [comment]
ok, added basic functionality, need to test and merge with dev branch

**Comment by Applevangelist** [comment]
Ready for testing
