### ISSUE TITLE
ZONE_POLYGON::IsVec2InZone not working correctly

### ISSUE THREAD

**Issue by MrAlien753** [FlightControl-Master/MOOSE#1914]
I'm trying to modify the spawning inside a zone to place all unit inside the zone and not only the first one. However ZONE_POLYGON::IsVec2InZone doesn't seem to work well.

**Comment by MrAlien753** [comment]
I'm using quad_point zones in the ME and they are convex.

**Comment by Applevangelist** [comment]
Implementation looks like a solid even-odd algo to me.

**Comment by MrAlien753** [comment]
Yeah, I verified the math is seems ok indeed. Also created test mission and could not reproduce the issue this way. Must be something else happing in the spawn process after defining the position to be in the zone.
