### ISSUE TITLE
Potential Performance improvement in IsVec2InZone 

### ISSUE THREAD

**Issue by MrAlien753** [FlightControl-Master/MOOSE#1915]
IsVec2InZone in Both ZONE_RADIUS and ZONE_POLYGON_BASE doesn't do a quick bounding box check before doing some heavier computations. Doing this would improve performance of this check

Also ZONE_RADIUS:IsVec2InZone uses expensive math. Best to replace "^2" and "^0.5" by simple multiplications.

**Comment by Applevangelist** [comment]
This is old code and if you can improve the compute time - very welcome!
