### ISSUE TITLE
CTLD Ship zones: cannot drop troops 

### ISSUE THREAD

**Issue by iojeda11** [FlightControl-Master/MOOSE#1923]
CTLD Ship zones: cannot drop troops from a landed helo (on the ship) if the ship is moving at more than 2m/s (3.88Knots)

**Comment by Applevangelist** [comment]
That is due to the hover check, if the shipm exceeds a certain speed.

**Comment by Applevangelist** [comment]
`condition to verify if the Helo is in the air or not.` nice roar, lion. There's a check for that in the API but it doesn't really work for Helos - since they can hover - hence we can do a check about height vs land height, which doesn't give as answer either, unless you are sitting directly on the ground and not a structure

**Comment by iojeda11** [comment]
This is how I fixed it:

function CTLD:IsUnitInAir(Unit)
  local minheight=self.minimumHoverHeight
  if Unit:InAir(true) then -- draken35
      env.info('CTLD:IsUnitInAir(Unit) true',false)
  else  -- draken35
    env.info('CTLD:IsUnitInAir(Unit) false',false)
    return false
  end  -- draken35

  if self.enableHercules and self:IsHercules(Unit)then
    minheight=5.1
  end
    local uheight=Unit:GetHeight()
    local ucoord=Unit:GetCoordinate()
    local gheight=ucoord:GetLandHeight()
    local aheight=uheight-gheight
  if aheight>=minheight then
    return true
  else
    return false
  end
end

Pardon the unclean code but never went back to clean it up... Too many
squirrels to chase :)
I just did a quick test and it is still working. I guess ED fixed the API ?

**Comment by Applevangelist** [comment]
Sometimes ED fixes stuff - not that they bother to tell anyone 😂. Next step - put in your pull request for this class. Then - try make dropping while hovering over driving ships… :)

**Comment by iojeda11** [comment]
Thanks! Wild do it closer to the weekend...

**Comment by Applevangelist** [comment]
Great!

**Comment by Applevangelist** [comment]
Your change effectively cuts off the Hercules bit, btw, suggest

```
  function CTLD:IsUnitInAir(Unit)
    -- get speed and height
    local minheight = self.minimumHoverHeight
    if self.enableHercules and self:IsHercules(Unit) then
      minheight = 5.1 -- herc is 5m AGL on the ground
    end
    local uheight = Unit:GetHeight()
    local ucoord = Unit:GetCoordinate()
    local gheight = ucoord:GetLandHeight()
    local aheight = uheight - gheight -- height above ground
    if aheight >= minheight and Unit:InAir(true) then
      return true
    else
      return false
    end
  end
```

Needs testing wrt to general hovering and Hercules, ofc

**Comment by Applevangelist** [comment]
Did the the change work out?

**Comment by iojeda11** [comment]
Sorry, I haven't had the chance to test yet. Too much stuff IRL to do any
DCS.

**Comment by iojeda11** [comment]
I just realized that I have not idea on how to do the pull request... :S
Do you mind guiding me  on that?

**Comment by Applevangelist** [comment]
Still an issue?

**Comment by iojeda11** [comment]
Nope. not anymore. You can close it.
