### ISSUE TITLE
BAI-001 002 are broken

### ISSUE THREAD

**Issue by phr0gz** [FlightControl-Master/MOOSE#1928]
Hello, 

Using MOOSE_MISSION "dev" AND "master" branches I just tested the BAI-001 and BAI-002 the demo missions are broken. The bombers didn't destroy anything.

**Comment by funkyfranky** [comment]
Just checked BAI-001. The Su-34 tried to attack but was shoot down from SAM Chaparral M48 before it could destroy any target.
Probably a change in DCS behaviour that the SAM is not better.
Might be worth to set the ROE of the targets so they do not attack for demo purposes.
