### ISSUE TITLE
Feature Request - Use STTS with or in place of text output.

### ISSUE THREAD

**Issue by Drofseh** [FlightControl-Master/MOOSE#1932]
Several MOOSE modules display output to the player as text, just as getting the bearing and range to a waypoint in PsuedoATC, or the take off and landed messages in RAT.
```
-- Message text.
local text=string.format("%s (%s): %s, Bearing %s, Range %s.", UnitName, PlayerName, location, Bs, Rs)
-- Send message
self:_DisplayMessageToGroup(self.group[GID].player[UID].unit, text, self.mdur, true)
```
It would be cool if these text outputs could also be sent over SRS using STTS.
Something like this:
```
-- Message text.
local text=string.format("%s (%s): %s, Bearing %s, Range %s.", UnitName, PlayerName, location, Bs, Rs)
-- Send message
self:_DisplayMessageToGroup(self.group[GID].player[UID].unit, text, self.mdur, true)
if settings:UseSTTS() then
    STTS.TextToSpeech(text,"243","AM","1.0","SRS",2,null,1,"male","en-US")
end
```
A simple implementation could see the mission maker set which frequency/modulation/etc to use via variables, a more complex implementation could get frequencies from airfields or AWACS aircraft and transmit over them as appropriate.

**Comment by Applevangelist** [comment]
Ready for testing.

Implemented as follows:

```
          -- Mind the dot here, not using the colon this time around!
          -- Needed once only
          MESSAGE.SetMSRS("D:\\Program Files\\DCS-SimpleRadio-Standalone",5012,nil,127,radio.modulation.FM,"female","en-US",nil,coalition.side.BLUE)
          -- later on in your code
          MESSAGE:New("Test message!",15,"SPAWN"):ToAll():ToSRS()
```

**Comment by Drofseh** [comment]
Happy to see this start to be implemented!
It might be good to have some sort of qeueuing system so that multiple transmissions on the same frequency can play one after the other instead of at the same time jamming each other.

**Comment by Applevangelist** [comment]
Its using a MSRSQueue…

**Comment by Drofseh** [comment]
Excellent!
