### ISSUE TITLE
SET_GROUP, method :FilterZones seems to not work as should be.

### ISSUE THREAD

**Issue by Amarok73** [FlightControl-Master/MOOSE#1933]
After an extended investigation with WingThor and at his urging, I hereby report a problem with the ":FilterZones" method for the SET_GROUP object.
The test scenario available in the attached mission consists of two helicopters, spawned inside and outside the ZONE respectively. In the case of the InZoneHeli helicopter, the ":OnAfterAdded" event occurs once after entering the helicopter and only then. Occasionally ":OnAfterRemoved" fires when the helicopter crashes, whether inside or outside the zone.
For the "OutOfZoneHeli" helicopter, none of the events are triggered at any time.
According to WingThor, and also in my humble opinion, this action is rather incorrect and inconsistent with the assumptions of functionality regarding the ":FilterZones" method.
The MOOSE version on which the tests were performed is "2023-03-30T10:23:07.0000000Z-a97e844acaf7c4c875b21ce657ea10dfcdc718d1".
The testing code is as follows:
```
env.info("### Zone filtering test... ")
BASE:TraceClass("SET_GROUP")
BASE:TraceOn()


TestZone = ZONE:New("TestingZone")
TestSetGroup = SET_GROUP:New():FilterCoalitions("blue"):FilterZones({TestZone}, false):FilterCategories({"plane", "helicopter"}):FilterStart()

function TestSetGroup:OnAfterAdded(From, Event, To, ObjectName, Object)
	env.info("###" .. ObjectName .. " in zone.")
	MESSAGE:New(ObjectName .. " in zone.", 30, nil, false):ToAll()
end

function TestSetGroup:OnAfterRemoved(From, Event, To, ObjectName, Object)
	env.info("###" .. ObjectName .. " left zone.")
	MESSAGE:New(ObjectName .. " left zone.", 30, nil, false):ToAll()
end

env.info("### ...loaded. ")

```
![obraz](https://user-images.githubusercontent.com/6810260/231240357-e87671d7-9ffa-46bf-bd82-23cdc810c900.png)
[Filtering test.miz.zip](https://github.com/FlightControl-Master/MOOSE/files/11203152/Filtering.test.miz.zip)

**Comment by Applevangelist** [comment]
Not sure I understand the problem correctly. You say that whence the helo is outside of the zone and crashes, the remove should not fire?

**Comment by Amarok73** [comment]
If the heli is outside the zone, it should be no longer part of the SET_GROUP object, so none of the events related to this object should be triggered by crash/kill of this helicopter. Because the ":FilterStart" is used, so the SET_GROUP object should react with the ":OnAfterRemoved" event as soon, as the heli leave the zone, and no more as long, as the heli stays outside of the zone. 
In more general, the point is that using the dynamic filtering with ":FilterStart" is not causing the object, to react properly on the helis or planes entering or leaving the zone or zones defined with the ":FilterZones" method.

**Comment by Applevangelist** [comment]
Added to the dev branch for testing.

Test Code:

```
local zone = ZONE:New("Test Zone")
zone:DrawZone(-1,{1,0,0},Alpha,FillColor,FillAlpha,LineType,true)
  
local testset = SET_GROUP:New():FilterZones({zone}):FilterZoneTimer(20):FilterStart()

function testset:OnAfterAdded(From,Event,To,ObjectName,Object)
  MESSAGE:New("Group added: "..ObjectName,15,"SET_GROUP",false):ToAll()
end

function testset:OnAfterRemoved(From,Event,To,ObjectName,Object)
  MESSAGE:New("Group removed: "..ObjectName,15,"SET_GROUP",false):ToAll()
end
```

Effectively adds a re-filter check every 20 secs, adding and reomving objects as they enter/leave the zone

**Comment by Amarok73** [comment]
I have tested it and confirm it works correctly.
Thanks again Apple!
