### ISSUE TITLE
Crash Event fired on all planes

### ISSUE THREAD

**Issue by goliat26** [FlightControl-Master/MOOSE#1940]
It is normal that when i create one static object (plane) and add crash event handler to it, the event is fired every another plane crashed?
![obraz](https://user-images.githubusercontent.com/43955340/234930943-7d81d5e6-89cd-440e-b53d-0fcf99ab9a4e.png)

Can i fix it to fire only when my static object is crushed?

**Comment by Applevangelist** [comment]
It’s like the dead event - fired a lot. You need to check eg the name to see if it’s „yours“

**Comment by goliat26** [comment]
I want to understand events mechanism :). When i create event handler manualy
![obraz](https://user-images.githubusercontent.com/43955340/234950191-5fc5dae8-1476-4378-97cc-bd00f4afd7e0.png)
only Dead function is called. I use the same static model as in previous example.
For test, i crush SU-25T into static plane on ground.

**Comment by Applevangelist** [comment]
Well technically a static cannot crash … maybe sth  around this

**Comment by goliat26** [comment]
> Well technically a static cannot crash … maybe sth around this

Cannot crash? In my first example i had to use Crash event because Dead event never fired.

**Comment by funkyfranky** [comment]
Hit event not firing should be fixednow.
