### ISSUE TITLE
ESCORT / FOLLOW - option to escort / follow opposite coalition.

### ISSUE THREAD

**Issue by DCSRWC** [FlightControl-Master/MOOSE#1942]
​
 

Hi Developers,

Would like to request a added TASK to escort / follow enemy aircraft as a task option.

Now one can ONLY follow or escort a plane from the same coalition. 

BLUE AI -> Task : Follow / Escort -> RED AI .... and/or vise-versa.

If there IS a way to do this bypassing the basic option by script or any other way, please add in the comment.

DCS forum Link : https://forum.dcs.world/topic/325615-escort-follow-option-to-escort-follow-opposite-coalition/#comment-5216287

Thanks.

RWC.
![DCS 2023-05-11 08-42-40](https://github.com/FlightControl-Master/MOOSE/assets/133477928/0f8be219-1ac4-414e-b874-05c53564ff49)
![DCS 2023-05-11 08-42-25](https://github.com/FlightControl-Master/MOOSE/assets/133477928/12a12e09-abd9-4c7f-88a9-17dc93eb3fbe)

**Comment by funkyfranky** [comment]
You can try the `CONTROLLABLE:TaskEscort` task and give it a group of the other coalition to escort/follow. With scripting there are no restrictions to the group you pass. If DCS internal logic does it or not is another question though. (But for example, with the ME attack group/unit task cannot attack groups/units of the same coalition, whereas with scripting you can have blue-on-blue or red-on-red.)

If that does not work you can try the `AI_FORMATION` class.
