### ISSUE TITLE
AIRBOSS enhancement - Use SRS STTS

### ISSUE THREAD

**Issue by patpatpowercat** [FlightControl-Master/MOOSE#1946]
It would be nice to have AIRBOSS to have the ability to use SRS in the way that other classes (ie RANGE) can now. Not only would there be more voices, but the interval issues with the soundfiles and dealing with soundfiles would also be eliminated.

**Comment by oufy** [comment]
Agreed. Moreover since last update yesterday mission files with sounds in it do not work anymore on DCS dedicated server : the server hangs on the "loading .miz file" step...

**Comment by Applevangelist** [comment]
Initial version in dev, as of 16 June 18:20 CEST
