### ISSUE TITLE
•CONTROLLABLE.TaskFireAtPoint bug and workaround

### ISSUE THREAD

**Issue by 132nd-Entropy** [FlightControl-Master/MOOSE#196]
CONTROLLABLE:TaskFireAtPoint(Vec2,Radius)  

works, but the group will fire only once. 
workaround: set param expendQtyEnabled=false

expample code working and tested:

Group:SetTask({id = 'FireAtPoint', params = {x=vec2Target.x, y=vec2Target.y, radius=200, expendQty=100, expendQtyEnabled=false}}, 1)

**Comment by FlightControl-Master** [comment]
Fixed with merge #198
