### ISSUE TITLE
Helo FLIGHTGROUP Departing from Non-Moving Ship: Premature Stuck-Taxiing Cleanup

### ISSUE THREAD

**Issue by ttrebuchon** [FlightControl-Master/MOOSE#1960]
Let me preface this by saying that I already have a fix written and working but based on the contributors guide, since it involves adding a new function (for cleanliness), it looked like the correct process was to open an issue for this.

The original problem I ran into involved MOOSE despawning OPSTRANSPORT helos that were trying to take off of a stopped carrier after they had delivered their cargo. I dug into it and the reason for this was that the FLIGHTGROUP code was incorrectly categorizing the helo as TAXIING before it had taken off/moved, and therefore it hit the check for max `self.RTBRecallCounts` in `FLIGHTGROUP:onbeforeRTB` before it could take off, and was despawned.
The reason it was prematurely classified as TAXIING is because of an issue in `FLIGHTGROUP:GetParkingSpot`. When the airbase it checks is a ship, it takes a shortcut and sets the parking position to origin (x=0, y=0) and sets the maxdist to 500. This is fine if the ship only has a single parking spot, but aircraft carriers have more than 1 parking spot. So the function returns the parking spot closest to the origin, and later when the distance from that spot to the aircraft is calculated in order to determine the start of taxiing, it falsely believes taxiing has begun due to the large distance.

So the solution for this is to either transform the points of all of the carrier's parking spots to world coordinates, and compare them to the aircraft's position, or more efficiently: compute the relative coordinate of the aircraft with respect to the ship's position and orientation instead.

I could just add the ~40 lines of math to calculate this directly into the method, but given that this is effectively the inverse operation of `POSITIONABLE:GetOffsetCoordinate` it seems like it would make more sense to add it as a new `POSITIONABLE:GetRelativeCoordinate`  function instead.

(My bad if I made any mistakes/mislabel anything, let me know and I'll fix it!)

PR will be up in a moment

**Comment by ttrebuchon** [comment]
Follow up after my merged PR: I may have added a bug when cleaning things up and organizing them to get ready for PR. Even though it's not getting despawned, it looks like I'm seeing the "RTB event is suspended for 20 sec" messages again.

(So maintainers: Don't close this issue just yet please)

**Comment by ttrebuchon** [comment]
False alarm. I forgot the "suspended for 20 sec" message is before it checks for "IsParking" and increments the RTBRecallCount.

This issue should be fine to close.

**Comment by funkyfranky** [comment]
Great stuff. Thanks for your contribution :)
