### ISSUE TITLE
Syria map airbase removal

### ISSUE THREAD

**Issue by phr0gz** [FlightControl-Master/MOOSE#1966]
Hello,

Can you please remove/comment (it should come back later, i hope...)  Nicosia airbase:
["Nicosia"]="Nicosia" in AIRBASE.Syria={

![image](https://github.com/FlightControl-Master/MOOSE/assets/2039631/2dcc2e9e-6331-4faf-96ec-dfccdcc11dcb)

Thanks

**Comment by Applevangelist** [comment]
done
