### ISSUE TITLE
Problems with Core.Settings

### ISSUE THREAD

**Issue by Mysterio105** [FlightControl-Master/MOOSE#1983]
I have been fideling with MOOSE for a while and was trying to work the AIRBOSS script, For Some reason the "_SETTINGS:SetPlayerMenuOff()" isn't working at all i've tried virtually everything. Changing Trigger parameters, Changing the Script, but the F-10 Comm Menu i.e.
    -F-10 Others
     -SETTINGS "Playername"
isn't going away. And slowly i am going crazy. So i think it might be a Script issue.

**Comment by Applevangelist** [comment]
Can reproduce
