### ISSUE TITLE
Ops.CHIEF. CargoTransport seems not be exceuted when assigned to a "chief"

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#1985]
I and others can not make transport work with the chieft class. I have no idea why nothing is transported by helicopter. So I used Moose Ops.Transport mission (Auftrag 029) as a template, and tried both with FLIGHTGROUP and CHIEF. For the CHIEF the transport task seems to never be executed. Here is code, and a zipeed (due to github policy) miz file is attaced.:

```lua

---
-- AUFTRAG: Cargo Transport (TEST MISSION MODYFIED BY WINGTHOR)
-- 
---

BASE:TraceOn()
BASE:TraceLevel(2)
BASE:TraceClass("OPSGROUP")
BASE:TraceClass("AUFTRAG")
AUFTRAG.verbose=3
OPSGROUP.verbose=3

-- Static cargo objects.
-- NOTE that
-- * We need the "UNIT NAME here (not the "NAME").
-- * It has to have the tick box "CAN BE CARGO" activated.
local staticAmmo=STATIC:FindByName("Static Ammo-1")
local staticBarrels = STATIC:FindByName("Static Barrels-1")
local staticOiltank = STATIC:FindByName("Static Oiltank-1")

local staticAmmo_CHIEF = STATIC:FindByName("Static Ammo_CHIEF")
local staticBarrels_CHIEF = STATIC:FindByName("Static Barrels_CHIEF")
local staticOiltank_CHIEF = STATIC:FindByName("Static Oiltank_CHIEF")
-- Zone where to drop off the cargo.
-- NOTE that this has to be a zone defined in the ME!
local dropZone = ZONE:New("Drop Zone")
local dropZone_CHIEF = ZONE:New("Drop Zone_CHIEF")

-- Create a flightgroup.
local helo = FLIGHTGROUP:New("Rotary-1")

---@class AIRWING
local myAirWing = AIRWING:New("BatumiWarehouse", "BatumiAB")

---@class SQUADRON
local heliSquadron = SQUADRON:New("Rotary_CHIEF", 4, "Blah")

myAirWing:AddSquadron(heliSquadron)

---@class CHIEF
myChief = CHIEF:New("blue", nil, "Birdie Bro")

myChief:AddAirwing(myAirWing)

local missions = {}
-- Create mission to transport ammo. This has the highest prio (lowest value) so is done first.
local missionAmmo = AUFTRAG:NewCARGOTRANSPORT(staticAmmo, dropZone)
missionAmmo:SetPriority(30)

local missionAmmo_CHIEF = AUFTRAG:NewCARGOTRANSPORT(staticAmmo_CHIEF, dropZone)
missionAmmo:SetPriority(30)

-- Create mission to transport barrels. This has lowest prio (highest value) so is done last.
local missionBarrels = AUFTRAG:NewCARGOTRANSPORT(staticBarrels, dropZone)
missionBarrels:SetPriority(70)

local missionBarrels_CHIEF = AUFTRAG:NewCARGOTRANSPORT(staticBarrels_CHIEF, dropZone)
missionBarrels_CHIEF:SetPriority(70)

-- Create mission to transport an oil tank. This has medium prio and is done after the ammo but before the barrels.
local missionOiltank = AUFTRAG:NewCARGOTRANSPORT(staticOiltank, dropZone)
missionBarrels:SetPriority(50)

local missionOiltank_CHIEF = AUFTRAG:NewCARGOTRANSPORT(staticOiltank_CHIEF, dropZone)
missionOiltank_CHIEF:SetPriority(50)
[Auftrag - 029 - Cargo Transport.zip](https://github.com/FlightControl-Master/MOOSE/files/12327723/Auftrag.-.029.-.Cargo.Transport.zip)


-- Assign mission to Huey crew.
helo:AddMission(missionAmmo)
helo:AddMission(missionBarrels)
helo:AddMission(missionOiltank)

myChief:AddMission(missionAmmo_CHIEF)
myChief:AddMission(missionBarrels_CHIEF)
myChief:AddMission(missionOiltank_CHIEF)
```

Can you please have a look a time it suits you @funkyfranky?

Regards Wingthor 

[Auftrag - 029 - Cargo Transport.zip](https://github.com/FlightControl-Master/MOOSE/files/12327735/Auftrag.-.029.-.Cargo.Transport.zip)

**Comment by baluballa** [comment]
A followup: 

I have issued a `Start()` commands as shown below since I might should have, but still !no joy":

```lua
---@class AIRWING
local myAirWing = AIRWING:New("BatumiWarehouse", "BatumiAB")
myAirWing:Start()

---@class SQUADRON
local heliSquadron = SQUADRON:New("Rotary_CHIEF", 4, "Blah")
heliSquadron:Start()

myAirWing:AddSquadron(heliSquadron)

---@class CHIEF
myChief = CHIEF:New("blue", nil, "Birdie Bro")
myChief:Start()
```

And no errors in the dcs.log file...

**Comment by baluballa** [comment]
So I have investigatet further and it seems like to get CHIEF handle the mission also the transporting SQUADRON MissionCapability needs to be set like:
```lua

heliSquadron:AddMissionCapability({ AUFTRAG.Type.TROOPTRANSPORT, AUFTRAG.Type.OPSTRANSPORT, AUFTRAG.Type.CARGOTRANSPORT })
```
Also to get  transport for the troop , it seem that the AIRWING the AIRWING is attached too must be in the same warehouse as the transporting troops. Also it seems warehous must have  with a FARP attached to it.

_I have search docs and can't find this written anyware_. I might be wrong about this, but thats how it looks like for me.

However the droppoint seems to be random set, so transporter tends to creash into trees or land in a steep terrain. Forcing the StrategicZone to be in flat terrain with not trees. Would be nice if droppoint could be set in flat terrain if possible with no trees nearby.

**Comment by Amarok73** [comment]
...and possibly not on the any building.

**Comment by baluballa** [comment]
> I have defined everything as described above, but still there's no troop transports appearing in the mission. Are there any specific conditions for CHIEF required, like Strategy, or DEFCON?

I believe in order for getting the CHIEF to use transports in a self assigned mission, you nedd to assign it as a CHIEF.resource.  Cehck the docs 
<https://flightcontrol-master.github.io/MOOSE_DOCS_DEVELOP/Documentation/Ops.Chief.html>

Se section "Customized Reaction"

**Comment by Amarok73** [comment]
![obraz](https://github.com/FlightControl-Master/MOOSE/assets/6810260/3ef3e938-8ee3-478e-91cc-bc3e370d1b0a)
So I've added code as above, but there's no any change in the way the situation develops.

**Comment by Amarok73** [comment]
I've implemented _exactly_ what is described on that page, meaning:
`--- Create a resource list of mission types and required assets for the case that the zone is OCCUPIED.
--
-- Here, we create an enhanced CAS mission and employ at least on and at most two asset groups.
-- NOTE that two objects are returned, the resource list (ResourceOccupied) and the first resource of that list (resourceCAS).
local ResourceOccupied, resourceCAS=BlueChief:CreateResource(AUFTRAG.Type.CASENHANCED, 1, 2)
-- We also add ARTY missions with at least one and at most two assets. We additionally require these to be MLRS groups (and not howitzers).
BlueChief:AddToResource(ResourceOccupied, AUFTRAG.Type.ARTY, 1, 2, nil, "MLRS")
-- Add at least one RECON mission that uses UAV type assets.
BlueChief:AddToResource(ResourceOccupied, AUFTRAG.Type.RECON, 1, nil, GROUP.Attribute.AIR_UAV)
-- Add at least one but at most two BOMBCARPET missions.
BlueChief:AddToResource(ResourceOccupied, AUFTRAG.Type.BOMBCARPET, 1, 2)

--- Create a resource list of mission types and required assets for the case that the zone is EMPTY.
-- NOTE that two objects are returned, the resource list (ResourceEmpty) and the first resource of that list (resourceInf).
-- Here, we create an ONGUARD mission and employ at least on and at most five infantry assets.
local ResourceEmpty, resourceInf=BlueChief:CreateResource(AUFTRAG.Type.ONGUARD, 1, 5, GROUP.Attribute.GROUND_INFANTRY)
-- Additionally, we send up to three tank groups.
BlueChief:AddToResource(ResourceEmpty, AUFTRAG.Type.ONGUARD, 1, 3, GROUP.Attribute.GROUND_TANK)
-- Finally, we send two groups that patrol the zone.
BlueChief:AddToResource(ResourceEmpty, AUFTRAG.Type.PATROLZONE, 2)

-- Add a transport to the infantry resource. We want at least one and up to two transport helicopters.
BlueChief:AddTransportToResource(resourceInf, 1, 2, GROUP.Attribute.AIR_TRANSPORTHELO)`
...then  in the mission assigning the zones:
`  local ConflictZones = SET_ZONE:New():FilterPrefixes("Zone_"):FilterOnce()
  local OpsZones = SET_OPSZONE:New():FilterPrefixes("Zone_"):FilterOnce()
    
  ConflictZones:ForEachZone(
    function(_opszone)
      local _stratzone = OPSZONE:New(_opszone)
        :SetDrawZone(true)
        :SetMarkZone(false, true)
      -- ser(_stratzone:GetName())
      -- BlueChief:AddConflictZone(_opszone)
      -- RedChief:AddConflictZone(_opszone)
      RedChief:AddStrategicZone(_stratzone)
      BlueChief:AddStrategicZone(_stratzone, nil, 2, ResourceOccupied, ResourceEmpty)
    end)`
...and only change now is that the infantry groups goes on foot from the spawn zone near the base, to the assigned zones. Still no heli transport for them is spawned and assigned.

**Comment by Amarok73** [comment]
Some additional investigation outcome:
1. For the helo squad have to be set the group attribute to AIR_TRANSPORTHELO even if it is declared as capable for transport missions with `Blue.Squad.TSQ2:AddMissionCapability({AUFTRAG.Type.TROOPTRANSPORT, AUFTRAG.Type.OPSTRANSPORT, AUFTRAG.Type.CARGOTRANSPORT})` Otherwise this squadron is recognized as "AIR_ATTACKHELO".
2. For unknown reason, still two first created infantry groups takes over 100 miles hike instead calling for the "Uber".
![obraz](https://github.com/FlightControl-Master/MOOSE/assets/6810260/beac3c0c-edce-47c7-a03f-ebeea340a7ae)
3. The helicopters are spawned and depart, then land one by one to pick the infantry even if the FARP is capable to receive four of them. 

I'd appreciate for any tips for at least second point from the above...

**Comment by baluballa** [comment]
> 

Since last time I have made an example mission which you can find here. Nice of you to share your findings!.
<https://github.com/FlightControl-Master/MOOSE_MISSIONS/tree/develop/OPS%20-%20Chief/Chief%20-%20055%20-%20Transport%20Troops%20OPSZONE>

**Comment by Amarok73** [comment]
NOW I can see, this mechanism is way more complicated than I was thinking in my attempts. I wonder if this couldn't be simplified, as most of the settings required for this to work could be assumed and used as default, so for example, there could be just one method setting everything for transport Squadron if he's set to be transport capable.

**Comment by Amarok73** [comment]
And here's the another issue. Even if I have additional platoon for ground transport (APC and IFV), after exhausting the available transport helicopters, the troops goes on the foot from the spawn area to the tactical zones, instead of calling for the ground transport.
Here's the Brigade and Platoons definition:
```
Red.Brigade.Base1 = BRIGADE:New("WH_Red_Base1", "Red Base 1")
Red.Brigade.Base1:SetSpawnZone(ZoneRedBase1Spawn)
Red.Brigade.Base1:Start()

Red.Platoon.Platoon1MechanizedRedBase1 = PLATOON:New("RMECH1", 2, "Mechanized Platoon 1 Base 1")
Red.Platoon.Platoon1MechanizedRedBase1:AddMissionCapability({AUFTRAG.Type.GROUNDATTACK, AUFTRAG.Type.PATROLZONE, AUFTRAG.Type.ONGUARD, AUFTRAG.Type.CAPTUREZONE, AUFTRAG.Type.ARMORATTACK, AUFTRAG.Type.ARMOREDGUARD})
Red.Platoon.Platoon1MechanizedRedBase1:SetSkill(AI.Skill.EXCELLENT)

Red.Platoon.Platoon2MechanizedRedBase1 = PLATOON:New("RMECH2", 2, "Mechanized Platoon 2 Base 1")
Red.Platoon.Platoon2MechanizedRedBase1:AddMissionCapability({AUFTRAG.Type.GROUNDATTACK, AUFTRAG.Type.PATROLZONE, AUFTRAG.Type.ONGUARD, AUFTRAG.Type.CAPTUREZONE, AUFTRAG.Type.ARMORATTACK, AUFTRAG.Type.ARMOREDGUARD})
Red.Platoon.Platoon2MechanizedRedBase1:SetSkill(AI.Skill.EXCELLENT)

Red.Platoon.Platoon1TransportRedBase1 = PLATOON:New("RTRANS1", 60, "RTRANS1-APC")
Red.Platoon.Platoon1TransportRedBase1:SetAttribute(GROUP.Attribute.GROUND_APC)
-- ser(Red.Platoon.Platoon1TransportRedBase1:GetAttribute())
Red.Platoon.Platoon1TransportRedBase1:AddMissionCapability({AUFTRAG.Type.TROOPTRANSPORT, AUFTRAG.Type.OPSTRANSPORT})
Red.Platoon.Platoon1TransportRedBase1:SetSkill(AI.Skill.EXCELLENT)

Red.Platoon.Platoon1IFVRedBase1 = PLATOON:New("RTRANS1", 60, "RTRANS1-IFV")
Red.Platoon.Platoon1IFVRedBase1:SetAttribute(GROUP.Attribute.GROUND_IFV)
-- ser(Red.Platoon.Platoon1IFVRedBase1:GetAttribute())
Red.Platoon.Platoon1IFVRedBase1:AddMissionCapability({AUFTRAG.Type.TROOPTRANSPORT, AUFTRAG.Type.OPSTRANSPORT})
Red.Platoon.Platoon1IFVRedBase1:SetSkill(AI.Skill.EXCELLENT)


Red.Platoon.Platoon1InfantryRedBase1 = PLATOON:New("RINF1", 30, "Infantry Platoon 1 Base 1")
Red.Platoon.Platoon1InfantryRedBase1:AddMissionCapability({AUFTRAG.Type.PATROLZONE, AUFTRAG.Type.ONGUARD, AUFTRAG.Type.CAPTUREZONE})
Red.Platoon.Platoon1InfantryRedBase1:SetAttribute(GROUP.Attribute.GROUND_INFANTRY)
Red.Platoon.Platoon1InfantryRedBase1:SetSkill(AI.Skill.EXCELLENT)

Red.Platoon.Platoon2InfantryRedBase1 = PLATOON:New("RINF2", 30, "Infantry Platoon 2 Base 1")
Red.Platoon.Platoon2InfantryRedBase1:AddMissionCapability({AUFTRAG.Type.PATROLZONE, AUFTRAG.Type.ONGUARD, AUFTRAG.Type.CAPTUREZONE})
Red.Platoon.Platoon2InfantryRedBase1:SetAttribute(GROUP.Attribute.GROUND_INFANTRY)
Red.Platoon.Platoon2InfantryRedBase1:SetSkill(AI.Skill.EXCELLENT)


Red.Brigade.Base1:AddPlatoon(Red.Platoon.Platoon1TransportRedBase1)
Red.Brigade.Base1:AddPlatoon(Red.Platoon.Platoon1IFVRedBase1)
Red.Brigade.Base1:AddPlatoon(Red.Platoon.Platoon1MechanizedRedBase1)
Red.Brigade.Base1:AddPlatoon(Red.Platoon.Platoon2MechanizedRedBase1)
Red.Brigade.Base1:AddPlatoon(Red.Platoon.Platoon1InfantryRedBase1)
Red.Brigade.Base1:AddPlatoon(Red.Platoon.Platoon2InfantryRedBase1)
```
..and this is the code used for the resources distribution:
```
function RedTransport()
  env.info("#### Red transpor t  start...")
  RedResourceEmpty, RedResourceInfantry = RedChief:CreateResource(AUFTRAG.Type.ONGUARD, 1, 2, GROUP.Attribute.GROUND_INFANTRY)
  RedResourceOccupied, RedResourceAttackInfantry = RedChief:CreateResource(AUFTRAG.Type.ONGUARD, 3, 8, GROUP.Attribute.GROUND_INFANTRY)

  RedChief:AllowGroundTransport()
  RedChief:AddTransportToResource(RedResourceAttackInfantry, 1, 4, GROUP.Attribute.GROUND_IFV)
  RedChief:AddTransportToResource(RedResourceInfantry, 1, 4, GROUP.Attribute.GROUND_APC)
  RedChief:AddTransportToResource(RedResourceAttackInfantry, 4, 4, GROUP.Attribute.AIR_TRANSPORTHELO)
  RedChief:AddTransportToResource(RedResourceInfantry, 4, 4, GROUP.Attribute.AIR_TRANSPORTHELO)
  env.info("#### Red transport started.")
end
RedTransport()
```
Did I miss something, that Chief regardless of use `:AllowGroundTransport()` just does not want to assign the ground based transport?

**Comment by Amarok73** [comment]
It seems that some of the zones are just too far for the ground transports and they spawn for closer transports, so the issue can be closed.
