### ISSUE TITLE
Allow users to override the cargo capacities for POSITIONABLEs

### ISSUE THREAD

**Issue by ttrebuchon** [FlightControl-Master/MOOSE#1988]
(Could someone with permissions add the feature request tag?)

NOTE: PR for basic implementation is already available, if reading the code is faster.

The use case is that a MOOSE user may want to adjust or add cargo bay capacity values, as currently used in the local "Weights" tables in POSITIONABLE:SetCargoBayWeightLimit() when no value is specified. 
Rather than modifying every UNIT via a manual SetCargoBayWeightLimit(SomeCapacity) call, it would be more efficient to allow users to modify the table itself. Keeping the values inaccessible in the code as hard-coded local values is both worse for performance and sort of makes MOOSE less-flexible as a whole.
But exposing the Weights table allows advanced users to both add new values to the table, and to change some of the existing hard coded values.

The simple (probably naïve) solution would be to simply add the Weights table as a static member of the POSITIONABLE class. This way users could add/remove/modify weights as simply as adding a `POSITIONABLE.CargoBayCapacityValues.Air["C-130"] = ###` or `POSITIONABLE.CargoBayCapacityValues.Ground["Hummer"] = ###` at the beginning of their script files. 
This is the implementation I'm adding in my proposed PR.

Concerns/Feedback Requested:
1. An alternate implementation could utilize static methods (like `POSITIONABLE.SetDefaultTypeCargoCapacity("XYZ", ###)`) but I'm not sure if that would ultimately be any cleaner or more user friendly.
2. Although the actual method itself is on the POSITIONABLE class, I'm not sure if it's very intuitive to have it on that class, or whether it would be better to put it elsewhere.

NOTE: Assuming this is the desired implementation that we want to go with, I could also use some LuaDoc advice with the new field and how to properly get it to show up in docs. Unfortunately, I'm more familiar with Lua as a language than I am with the LuaDoc markup that MOOSE uses.

**Comment by Applevangelist** [comment]
#1989 - merged
