### ISSUE TITLE
Invesitgate SET:FilterPrefixes() not working when a table is used instead of string

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#1994]
[](https://discord.com/channels/378590350614462464/378594576195387403/1143630723115401327)
Seems changed 3 weeks back, but I couldn't determine the breakage really.

**Comment by Applevangelist** [comment]
Example? That code base didn’t change other than for SET_SCENERY

**Comment by Applevangelist** [comment]
The issue is not the input being a table, but the - special character in the name example. The 4th parameter “plain” for string.find has never been set in this code earlier on; question is what we want here, really. Magic characters allow to search for naming starting with etc, like “^UH.60L"
