### ISSUE TITLE
With the newer MOOSE versions, the heli transports do not depart. 

### ISSUE THREAD

**Issue by Amarok73** [FlightControl-Master/MOOSE#2002]
Hello,

I've updated the version of the MOOSE in the mission, where I implemented the heli transports, and the helicopters no longer depart after loading the troops.
The last working for me version is 2023-08-13T20:57:06.0000000Z-dbd78f35a416dde9ebe48b1252635773c86bd343
The version where I observe the problem is 2023-09-10T13:42:48.0000000Z-ef3127fdab82fe8566080c3402b8927e6679b346
The mission file in attachment, and script file that manages the transport is AMK_WAR.lua.
[Sphinx Nose 3_48.miz.zip](https://github.com/FlightControl-Master/MOOSE/files/12569693/Sphinx.Nose.3_48.miz.zip)

**Comment by Applevangelist** [comment]
I think this has been fixed, has it?

**Comment by Amarok73** [comment]
I can confirm, the issue is no more in the recent release. Thanks a lot!
