### ISSUE TITLE
MOOSE zone demo missions fail with error in dcs.log

### ISSUE THREAD

**Issue by kaltokri** [FlightControl-Master/MOOSE#2004]
"ZON-200 - Group Zone.miz" does not work.
Error: attempt to index field '?' (a string value)

It seems that the included script was wrong. I changed it to the script in the same folder and it is working now.

Same for "ZON-300 - Unit Zone.miz" & "ZON-400 - Radius Zone.miz"

**Comment by kaltokri** [comment]
Example mission "ZON-102 - Normal Zone Boundary.lua" failed with error Parameter #1 (country id) missed ...  in function 'BoundZone'
I changed this line in the example mission and it works now:
`ZoneA:BoundZone( 90, country.id.CHINA, false )`

**Comment by Applevangelist** [comment]
Resolved
