### ISSUE TITLE
MessageToAll

### ISSUE THREAD

**Issue by 132nd-Entropy** [FlightControl-Master/MOOSE#2013]
Hey, we used to use MessageToAll in our code, but Im getting DCS scripting errors everytime its calling the MessageToAll function. 

did that break in one of last updates? (using the dev branch moose.lua)

**Comment by funkyfranky** [comment]
The function was 
```
function MessageToAll( MsgText, MsgTime, MsgName )
  -- trace.f()

  MESSAGE:New( MsgText, MsgTime, "Message" ):ToCoalition( coalition.side.RED ):ToCoalition( coalition.side.BLUE )
end
```
and got removed with a code cleanup (UTILS.Routines.lua)

**Comment by 132nd-Entropy** [comment]
Thanks !
