### ISSUE TITLE
Mission OPS - Auftrag\Airforce\Auftrag - 011 - Anti-Ship does not work

### ISSUE THREAD

**Issue by kaltokri** [FlightControl-Master/MOOSE#2014]
I've tested mission "Auftrag - 011 - Anti-Ship.miz".
Viggen and Hornets take off, fly in the direktion of the target ship, but then after one third of the way they turn around and fly back home.
In the log this is found `AUFTRAG01344.Evaluate(Auftrag #1 Anti Ship | Mission 1 [Anti Ship] failed!).`
Even if Imove the Grisha to Grid GG24 in front of the airfield they abort the mission.

**Comment by kaltokri** [comment]
`I did a lot of test runs. After changing the loadout of the Hornet to 4 x Harpoon + ATFLIR, they shot 3 or 4 Missles to the Grisha and destroy it.
I could swear that I had tested the exact same thing before without success. But maybe I had pulled the target ship too close to the airfield.
But the Viggen did not attack the ship.`
So changing loadout and deleting Viggen should fix the mission.

**Comment by funkyfranky** [comment]
I have changed the loadout but left the Viggens in. It's a good demo that the DCS AI sometimes has some quirks.

**Comment by Applevangelist** [comment]
guess this can be closed
