### ISSUE TITLE
"Error in error handling" when using AIRBOSS and HMS Invincible

### ISSUE THREAD

**Issue by engines-wafu** [FlightControl-Master/MOOSE#2016]
Attempting to call AIRBOSS on a mission file that uses both Forrestal and Invincible:

```
--Airboss definitions (Marshall and LSO for ARK)
local AirbossARK=AIRBOSS:New("HMS Ark Royal")
AirbossARK:SetSoundfilesFolder("Airboss Soundfiles/") -- Set folder of airboss sound files within miz file.
AirbossARK:SetTACAN(1, "ARK", "X")
AirbossARK:SetICLS(1)
AirbossARK:SetMarshalRadio(230) -- Default is 305Mhz AM
AirbossARK:SetLSORadio(231) -- Default is 264Mhz AM
AirbossARK:SetRecoveryCase(1)
AirbossARK:SetEmergencyLandings(true)
-- AirbossARK:SetFunkManOn(10042)
AirbossARK.skipperMenu=true
AirbossARK:Load("C:\\Trapsheets")
AirbossARK:SetAutoSave("C:\\Trapsheets")
AirbossARK:Start()
```

```
--Airboss definitions (Marshall and LSO for ILL)
local AirbossILL=AIRBOSS:New("HMS Illustrious")
AirbossILL:SetSoundfilesFolder("Airboss Soundfiles/") -- Set folder of airboss sound files within miz file.
AirbossILL:SetTACAN(2, "ILL", "X")
AirbossILL:SetICLS(2)
AirbossILL:SetMarshalRadio(232) -- Default is 305Mhz AM
AirbossILL:SetLSORadio(233) -- Default is 264Mhz AM
AirbossILL:SetRecoveryCase(1)
AirbossILL:SetEmergencyLandings(true)
-- AirbossILL:SetFunkManOn(10043)
AirbossILL.skipperMenu=true
AirbossILL:Load("C:\\Trapsheets")
AirbossILL:SetAutoSave("C:\\Trapsheets")
AirbossILL:Start()
```

All aspects relating to the F-14s on Forrestal are as expected.  When using the Invincible and harriers we see:

`
2023-10-14 05:11:47.562 ERROR   SCRIPTING (Main): error in error handling
`

Latest static Moose.lua in use, mission file included for reference.

[OpPurpleWarrior.zip](https://github.com/FlightControl-Master/MOOSE/files/12902698/OpPurpleWarrior.zip)

**Comment by funkyfranky** [comment]
The error message is unfortunately not very informative and there is no trace or line where to look. It often appears when a function called via the F10 menu errors.
Do you have any clue which F10 menu function might cause this? Is anything not working airboss wise? Just want to make sure this is even an error thrown from the airboss part.

**Comment by engines-wafu** [comment]
The error posts whenever we try and use the skipper menu or have any AIRBOSS interaction. We don't get any response in the form of subtitles or sound files either. And the same interaction with the Forrestal works as expected.

**Comment by engines-wafu** [comment]
I've also increased the trace levels, but couldn't see anything more useful in terms of logging.

**Comment by funkyfranky** [comment]
Instead of `AirbossILL.skipperMenu=true` use `AirbossILL:SetMenuRecovery()`.
Otherwise some internal variables are not initialized and cause an error.

**Comment by engines-wafu** [comment]
Issue traced to having one carrier group (ARK) as Combined Task Force Blue, and the other (ILL) as UK.  When ILL was set to CTFB the error stopped.
