### ISSUE TITLE
Missing images in MOOSE_DOCS and MOOSE_DOCS_DEVELOP

### ISSUE THREAD

**Issue by kaltokri** [FlightControl-Master/MOOSE#2028]
We must add the following images to avoid broken links:
- Images/CORE_Pathline.png
- Images/Wrapper_Storage.png

**Comment by funkyfranky** [comment]
Yes, those are placeholders for now until I have time to make some images.

**Comment by kaltokri** [comment]
I've copied two already existing images as placeholders. They can be exchanged later. But we should add a placebo images right from the beginning to avoid broken links.
