### ISSUE TITLE
might not be an issue but DCS folder not present as directed at 30:54 of setup video 

### ISSUE THREAD

**Issue by d0o0m** [FlightControl-Master/MOOSE#203]
missing DCS folder under Moose development is a barrier to new users following youtube development tutorial to setup projects in Eclipse

**Comment by FlightControl-Master** [comment]
Thanks. We will fix this issue this weekend. , @birgersp are there other options that we have? Submodules seem to be confusing for the users.

**Comment by birgersp** [comment]
To pull the contents of the submodules, we use `git submodule update --init`.
But I'm guessing users of MOOSE won't be using Git, and MOOSE is not bundled into release versions (containing the submodule contents).
I think there is a way to make Github include submodules when the repo is downloaded, which would be a win-win situation. I'll get back to you shortly.

**Comment by birgersp** [comment]
(Following our Slack discussion) I've made a script that pulls the latest changes of the remote MOOSE repository, and updates the submodules. This script will populate the contents of the `Moose Development/Moose/Dcs` folder.
