### ISSUE TITLE
WAREHOUSE UAV

### ISSUE THREAD

**Issue by funkyfranky** [FlightControl-Master/MOOSE#2033]
Finally got Predators and Reapers to spawn at Creech via AIRWING with this mod
line: 110490
      old:  if _attribute==WAREHOUSE.Attribute.AIR_FIGHTER then
      new: if _attribute==WAREHOUSE.Attribute.AIR_FIGHTER or _attribute==WAREHOUSE.Attribute.AIR_UAV then
line: 178821
      old:  if _attribute==FLIGHTGROUP.Attribute.AIR_FIGHTER then
      new: if _attribute==FLIGHTGROUP.Attribute.AIR_FIGHTER or _attribute==FLIGHTGROUP.Attribute.AIR_UAV then

**Comment by schradj** [comment]
as requested, the name of the functions edited are 

function WAREHOUSE:_GetTerminal(_attribute, _category)
      old:  `if _attribute==WAREHOUSE.Attribute.AIR_FIGHTER then`
      new: `if _attribute==WAREHOUSE.Attribute.AIR_FIGHTER or _attribute==WAREHOUSE.Attribute.AIR_UAV then`

function FLIGHTGROUP:_GetTerminal(_attribute, _category)
      old:  `if _attribute==FLIGHTGROUP.Attribute.AIR_FIGHTER then`
      new: `if _attribute==FLIGHTGROUP.Attribute.AIR_FIGHTER or _attribute==FLIGHTGROUP.Attribute.AIR_UAV then`
