### ISSUE TITLE
USERSOUND is not working, while trigger.action.outSound is ok.

### ISSUE THREAD

**Issue by Amarok73** [FlightControl-Master/MOOSE#2037]
Hello,

I'd like to report problem with playing the sound using the USERSOUND class. 
The script from miz file is Chicken_Random_Routes.lua.
These OGG files triggered with ME defined triggers by the `fApplause[1-5]` flags set works ok, while using `Applause[1-5]:ToAll()` has no effect at all. No sound, no error message in the log. 
I've tried also the `trigger.action.outSound("beacon.ogg")` that is the command from the `USERSOUND:ToAll()` method and this one works correctly.
All the sound files are cached from wihtin the ME triggers by playing them to the "dummy" country.
[Chicken Run - Dubai Hastle.miz.zip](https://github.com/FlightControl-Master/MOOSE/files/13329278/Chicken.Run.-.Dubai.Hastle.miz.zip)

**Comment by Applevangelist** [comment]
A simple test with USERSOUND works as it should. Likely your script?

**Comment by Applevangelist** [comment]
Lua is CaseSenSitIVe. OGG is not equal to ogg.
```
local Applause = {}
	Applause[1] = USERSOUND:New("1.ogg")
	Applause[2] = USERSOUND:New("2.ogg")
	Applause[3] = USERSOUND:New("3.ogg")
	Applause[4] = USERSOUND:New("4.ogg")
	Applause[5] = USERSOUND:New("5.ogg")
	SndBeacon = USERSOUND:New("beacon.ogg")
```
USERSOUND has no queue btw, so all you hear is the beacon

**Comment by Amarok73** [comment]
So I have changed the "OGG" to "ogg", but still there's no sound from the lines 48-53, nor 64 (`Applause[Counter1to5]:ToAll()`)

**Comment by Amarok73** [comment]
Indeed, the file names are also case sensitive. Thanks for the help!
