### ISSUE TITLE
Aircraft Respawn Repeatedly 

### ISSUE THREAD

**Issue by quicksplice** [FlightControl-Master/MOOSE#2039]
DCS 2.9 Update 11/16/23

Spawn:New
InitRepeatOnEngineShutdown
SpawnScheduled(180,0)

The aircraft selected with Late Activation (AWACS) now spawns every 180 seconds not registering the original is still flying.

Originally would not spawn until the first one crashed, landed and shutdown

**Comment by Applevangelist** [comment]
Please use the new release
