### ISSUE TITLE
:InitLimit for Spawn not working

### ISSUE THREAD

**Issue by malamem** [FlightControl-Master/MOOSE#2040]
Max units alive at runtime not working. It keeps spawning at the :spawnScheduled interval.

Badguy6 = SPAWN
:New( "Badguy6" )
:InitLimit(7, 0) 
:InitRandomizePosition(true, 100,5)
:SpawnScheduled( 60, 0.5 )

**Comment by Applevangelist** [comment]
Please use the new release
