### ISSUE TITLE
SPAWNSTATIC:_SpawnStatic : no "T" function

### ISSUE THREAD

**Issue by docbrownd** [FlightControl-Master/MOOSE#2049]
Hi, 
in SPAWNSTATIC:_SpawnStatic, T/T2 function doesn't exist  : 

 self:T(Template)
 self:T("Spawning FARP")
 self:T({Template=Template})
 self:T({TemplateGroup=TemplateGroup})

self:T("Spawning Static")
self:T2({Template=Template})

I need this function so i commented all of this line, but a fix will be great ^^

thanks.

**Comment by Applevangelist** [comment]
Inheritance. You  are supposed to use o e of the New.. functions first, then due to inheritance all methods from base like T, T2 etc are there. Functions starting with an underscore are considered private and not for the end user.

**Comment by docbrownd** [comment]
> Inheritance. You are supposed to use one of the New.. functions first, then due to inheritance, all methods from base like T, T2 etc are there. Functions starting with an underscore are considered private and not for the end user.

Hi, sorry for late.

yes i don't call this function, that is my code : 

			```
SPAWNSTATIC:InitType(typeName):InitNamePrefix(nameStat .. "_" .. tostring(number)):InitShape(shapeName):InitCountry(country.id.RUSSIA):SpawnFromCoordinate(coord, math.deg(heading))
```

But SpawnFromCoordinate call _SpawnStatic  but i understand now, i need to use NewFromType, not InitType
