### ISSUE TITLE
Request : bypassing callsign in SPAWN:_Prepare

### ISSUE THREAD

**Issue by docbrownd** [FlightControl-Master/MOOSE#2050]
Hi, 
in SPAWN:_Prepare() function, template's callsign is overwrite by Moose.  Is it possible to add an option to bypass this bloc (for example if some attribut is find in template) ? because without that air unit callsign doesn't change in F10 view (callsign cahcnge only for unit name)

So my request is to change this : 
<code>
for UnitID=1,#SpawnTemplate.units do
  local Callsign=SpawnTemplate.units[UnitID].callsign
  if Callsign then
    if type(Callsign)~="number"then
      Callsign[2]=((SpawnIndex-1)%10)+1
      local CallsignName=SpawnTemplate.units[UnitID].callsign["name"]
      CallsignName=string.match(CallsignName,"^(%a+)")
     local CallsignLen=CallsignName:len()
     SpawnTemplate.units[UnitID].callsign["name"]=CallsignName:sub(1,CallsignLen)..SpawnTemplate.units[UnitID].callsign[2]..SpawnTemplate.units[UnitID].callsign[3]
    else
      SpawnTemplate.units[UnitID].callsign=Callsign+SpawnIndex
    end
  end
end

</code>

by this : 
<code>
if (SpawnTemplate.bypassCallsign == nil) then 

for UnitID=1,#SpawnTemplate.units do
  local Callsign=SpawnTemplate.units[UnitID].callsign
  if Callsign then
    if type(Callsign)~="number"then
      Callsign[2]=((SpawnIndex-1)%10)+1
      local CallsignName=SpawnTemplate.units[UnitID].callsign["name"]
      CallsignName=string.match(CallsignName,"^(%a+)")
     local CallsignLen=CallsignName:len()
     SpawnTemplate.units[UnitID].callsign["name"]=CallsignName:sub(1,CallsignLen)..SpawnTemplate.units[UnitID].callsign[2]..SpawnTemplate.units[UnitID].callsign[3]
    else
      SpawnTemplate.units[UnitID].callsign=Callsign+SpawnIndex
    end
  end
end

end

</code>

Best

**Comment by Applevangelist** [comment]
Not sure I understand the problem here. Are we talking red or blue callsigns? This snippet resolves the problem that if you have a template of one unit but spawn a group of 4 units, every blue plane will have the correct callsign eg Ford11, Ford21..  etc. and red callsigns will be consecutive numbers

**Comment by docbrownd** [comment]
> Not sure I understand the problem here. Are we talking red or blue callsigns? This snippet resolves the problem that if you have a template of one unit but spawn a group of 4 units, every blue plane will have the correct callsign eg Ford11, Ford21.. etc. and red callsigns will be consecutive numbers

I not sure, but if you want a group of 4, callsign must be Ford11/12/13/14 no ? but in my case i spawn N unit not in a group, for example 2 KC125. And in F10 view, both KC have Texaco11 callsign (but if you check unit, it's Texaco11 and Texaco21).

By bypassing this code, it's possible to define callsign by changing template directly

**Comment by Applevangelist** [comment]
Can you share your spawning code?

`I not sure, but if you want a group of 4, callsign must be Ford11/12/13/14` - no it’s callsign minor major

**Comment by Applevangelist** [comment]
Ok, so you want to set individual callsigns per Tanker. Works best for Groups which have only one unit.

**Comment by Applevangelist** [comment]
okay, added the following, let me know if that works for you:
```
--- [BLUE AIR only!] This method sets a specific callsign for a spawned group. Use for a group with one unit only!
-- @param #SPAWN self
-- @param #number ID ID of the callsign enumerator, e.g. CALLSIGN.Tanker.Texaco - - resulting in e.g. Texaco-2-1
-- @param #string Name Name of this callsign as it cannot be determined from the ID because of the dependency on the task type of the plane, and the plane type. E.g. "Texaco"
-- @param #number Minor Minor number, i.e. the unit number within the group, e.g 2 - resulting in e.g. Texaco-2-1
-- @param #number Major Major number, i.e. the group number of this name, e.g. 1 - resulting in e.g. Texaco-2-1
-- @return #SPAWN self
SPAWN:InitCallSign(ID,Name,Minor,Major)
```

**Comment by docbrownd** [comment]
> Ok, so you want to set individual callsigns per Tanker. Works best for Groups which have only one unit.

yes

**Comment by docbrownd** [comment]
> okay, added the following, let me know if that works for you:
> 
> ```
> --- [BLUE AIR only!] This method sets a specific callsign for a spawned group. Use for a group with one unit only!
> -- @param #SPAWN self
> -- @param #number ID ID of the callsign enumerator, e.g. CALLSIGN.Tanker.Texaco - - resulting in e.g. Texaco-2-1
> -- @param #string Name Name of this callsign as it cannot be determined from the ID because of the dependency on the task type of the plane, and the plane type. E.g. "Texaco"
> -- @param #number Minor Minor number, i.e. the unit number within the group, e.g 2 - resulting in e.g. Texaco-2-1
> -- @param #number Major Major number, i.e. the group number of this name, e.g. 1 - resulting in e.g. Texaco-2-1
> -- @return #SPAWN self
> SPAWN:InitCallSign(ID,Name,Minor,Major)
> ```

looks fine, except that this function doesn't exists in last release :s

**Comment by Applevangelist** [comment]
No you need to get a newer build. In github under Moose-Include

**Comment by docbrownd** [comment]
> No you need to get a newer build. In github under Moose-Include

? sorry i don't understand : i dowload new moose_include-2.9.3 and this function is not find. 

how i can have new build with this function ? 

ooh i get it, it's from other github repo.... sorry i will try that.

**Comment by docbrownd** [comment]
Works like a charm ^^ except one thing :  
![image](https://github.com/FlightControl-Master/MOOSE/assets/105074220/9c9c7f92-7a61-4769-8c16-b70e59ed5b36)

For me, first character of group's name need to be in uppercase (like in my previus screen). 

need to change :  self.SpawnInitCallSignName=string.lower(Name)or"enfield" by self.SpawnInitCallSignName=Name:lower():gsub("^%l", string.upper)  or "Enfield"
