### ISSUE TITLE
COORDINATE:GetAngleDegrees calculates incorrectly angle from 0,0 toward passed Vec3

### ISSUE THREAD

**Issue by okopanja** [FlightControl-Master/MOOSE#2051]
I have tried to use COORDINATE:GetAngleDegrees() in order to obtain angle from one coordinate toward another one. 

For this function the documentation states: "Obtain the angle in degrees from the current 3D point with the provided 3D direction vector." 
https://github.com/FlightControl-Master/MOOSE_DOCS/blob/394058dd98c0c2ac818a09048878cbb5801e4594/Documentation/Core.Point.html#L1752

Upon inspecting function I found out that it actually calls GetAngleRadians and converts into degree. So far so good.

However GetAngleRadians is calculating the angle from (0,0) toward the passed point, without taking the account of the own location. 

In turn this code will not correctly calculate the angle
``` 
local directionAngle = currentCoordinate:GetAngleDegrees(sourceCoordinate:GetVec3())
```

At the moment my workaround is:
```
        local directionAngle = currentCoordinate:GetAngleDegrees(currentCoordinate:GetDirectionVec3(sourceCoordinate:GetVec3()))
```
which produces correct results.

**Comment by Applevangelist** [comment]
Well it's what the description said, right: "Obtain the angle in degrees from the current 3D point with the provided **3D direction vector.**"

**Comment by Applevangelist** [comment]
Added an example

**Comment by okopanja** [comment]
So this is correct-as-is.
Can you please link the example?

**Comment by Applevangelist** [comment]
Basically what you figured out already 

https://flightcontrol-master.github.io/MOOSE_DOCS_DEVELOP/Documentation/Core.Point.html##(COORDINATE).GetAngleDegrees
