### ISSUE TITLE
non-existing function call in function EVENT:onEvent( Event )

### ISSUE THREAD

**Issue by davidp57** [FlightControl-Master/MOOSE#2053]
The `getPlayerName` function is undefined on the `Event.Weapon` object instance, [line 1351](https://github.com/FlightControl-Master/MOOSE/blob/4b8d120f20b4b695a32595b6aa26f03753a3f1e1/Moose%20Development/Moose/Core/Event.lua#L1351) of `Event.lua`.

I solved this problem locally by adding a check on the function (quick and dirty workaround):

```lua
Event.WeaponPlayerName=Event.WeaponUNIT and Event.Weapon.getPlayerName and Event.Weapon:getPlayerName()
```

**Comment by Applevangelist** [comment]
Thanks! Fixed now!
