### ISSUE TITLE
MESSAGE:ToCoalition does not show category string

### ISSUE THREAD

**Issue by ojemineh** [FlightControl-Master/MOOSE#2059]
In all message-functions (MESSAGE:ToClient, MESSAGE:ToGroup, MESSAGE:ToUnit, MESSAGE:ToCountry, MESSAGE:ToAll) a given category is taken into account - not in MESSAGE:ToCoalition.

for example:

in MESSAGE:ToClient [Line 210] in "Core/Message.lua" the string is build like this

`trigger.action.outTextForUnit( Unit:GetID(), self.MessageCategory .. self.MessageText:gsub("\n$",""):gsub("\n$",""), self.MessageDuration , self.ClearScreen)`

while in MESSAGE:ToCoalition [Line 371] the trigger action looks like this

`trigger.action.outTextForCoalition( CoalitionSide, self.MessageText:gsub( "\n$", "" ):gsub( "\n$", "" ), self.MessageDuration, self.ClearScreen )`

so :ToCoalition will never show a given category.

bug or feature?

**Comment by Applevangelist** [comment]
More of a bug

**Comment by Applevangelist** [comment]
fixed
