### ISSUE TITLE
FSM Logging is flooding the log making it useless

### ISSUE THREAD

**Issue by jeremysmitherman** [FlightControl-Master/MOOSE#210]

**Comment by FlightControl-Master** [comment]
Ok. Yes. I know... For the moment I let this happen.
I can move that one line to trace, but an afraid that a user will have a problem and I don't know what happened... What would you suggest?

**Comment by FlightControl-Master** [comment]
By the way jeremi, what is your user on ed?

**Comment by jeremysmitherman** [comment]
I'm Jers @ ED, but I'm on reddit most of the time at /r/hoggit for DCS stuff however.

Perhaps it would be possible to pass in a debug parameter?  I'll try to help look for a solution to this in the morning as well.

**Comment by FlightControl-Master** [comment]
Search in moose.lua for the following statements:

if self.Controllable then
        self:E( "FSM Transition for " .. self.Controllable.ControllableName .. " :" .. self.current .. " --> " .. EventName .. " --> " .. to )
      else
        self:E( "FSM Transition:" .. self.current .. " --> " .. EventName .. " --> " .. to )
      end

Replace self:E with self:T and you're done. I will do the same.
Pls confirm if ok.

**Comment by FlightControl-Master** [comment]
I will send you a PM on ED

**Comment by FlightControl-Master** [comment]
I just republished a new version of moose.lua + other changes.
This issue can be closed!
