### ISSUE TITLE
New function to remove units from a platoon

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#2103]
We have a function in the Brigade that allows us to add groups to a platoon in a brigade . So for instance I can create a platoon,
SyrianGarrison=PLATOON:New("Syrian Garrison", 100, "Al Bab Garrison"). this example creates a garrison platoon with 100 groups in it.
I use AlBabBrigade:AddPlatoon(SyrianGarrison) to add the platoon to the AlBabBrigade. 
I can add to this platoon using AlBabBrigade:AddAssetToPlatoon(SyrianPlatoon, 2). Now the platoon have 102 groups in it. 

We need a way to remove groups from a platoon similar to adding.  
So if I do AlBabBrigade:RemoveAssetFromPlatoon(SyrianPlatoon, 2), the Syrian Garrision will have 98 groups in it. 

There is a function called BRIGADE:RemoveAssetFromPlatoon(Asset), but this appears to remove the entire platoon from the brigade. What Im suggesting is different.

**Comment by gunterlund** [comment]
Hi @funkyfranky any thought on this?

**Comment by gunterlund** [comment]
Hi @funkyfranky I saw what looked like an update come through for this. will this remove assets at the platoon/squadron level?

**Comment by funkyfranky** [comment]
You can use `myplatoon:RemoveAssets(3)` @gunterlund
