### ISSUE TITLE
ESCORT seems to not work according to documentation

### ISSUE THREAD

**Issue by jeremysmitherman** [FlightControl-Master/MOOSE#211]
Given:
```
env.info("ESCORTEE CALLSIGN: " .. client:GetCallsign())
env.info("ESCORT GROUP NAME: " .. escorts[1]:GetName())
EscortPlanes = ESCORT:New(client, escorts[1], escorts[1]:GetName(), "You are being escorted by ".. escorts[1]:GetName() .. ".  F10 radio menu for orders.")
```

I am getting error:

```
01890.052 ERROR   SCRIPTING: [string "...\AppData\Local\Temp\DCS\/~mis0000692A"]:5495: attempt to call method 'GetClientGroupID' (a nil value)
```

Full trace:

```
stack traceback:
	[C]: in function 'GetClientGroupID'
	[string "C:\Users\...\AppData\Local\Temp\DCS\/~mis0000692A"]:5495: in function 'New'
	[string "C:\Users\...\AppData\Local\Temp\DCS\/~mis0000692A"]:20410: in function 'New'
	[string "E:\Documents\LUA\Moose_Missions\..."]:104: in function 'CommandMenuFunction'
	[string "C:\Users\...\AppData\Local\Temp\DCS\/~mis0000692A"]:5131: in function <[string "C:\Users\...\AppData\Local\Temp\DCS\/~mis0000692A"]:5130>
```

**Comment by FlightControl-Master** [comment]
Ok. I'll check that. This is possibly because of the work around to solve the multi player client group bug from dcs.
Will revert back.

**Comment by FlightControl-Master** [comment]
By the way, this is excellent feedback! I mean well documented. Thank you

**Comment by FlightControl-Master** [comment]
this is fixed with the latest release, who can test?

**Comment by FlightControl-Master** [comment]
@jeremysmitherman can you retest this?

**Comment by Grey-Echo** [comment]
For what it is worth, I tested the plane part of ESC-001, which contains  `EscortPlane2 = ESCORT
    :New( Client, EscortGroupPlane2, "Escort Test Plane" )`, and I didn't get an error in dcs.log.

So I'd say it's fixed !

**Comment by FlightControl-Master** [comment]
You need to try the functions too! The menu options. Man! You're missing out :-)

**Comment by FlightControl-Master** [comment]
Wanna see at least those users using the ESCORT class to confirm the fix!!!

**Comment by Grey-Echo** [comment]
I did ! Every one of them ! The flare one is pretty cool !

**Comment by FlightControl-Master** [comment]
OK! Closed!!!! We need to put some advertisements on this ESCORT class, wouldn't you think?
Have you tried the "assisted" attack?

**Comment by Grey-Echo** [comment]
Yep, it's a bit unknown and maybe under-documented ATM. I haven't tried the assisted attack yet!
