### ISSUE TITLE
InitCallSign : First caract need to be in upper case

### ISSUE THREAD

**Issue by docbrownd** [FlightControl-Master/MOOSE#2124]
Hi,
when using  SPAWN:InitCallSign, callsign in F10 view is in full lower case. But if you use editor, first caract is in uppser case -> enfield1-1 versus Enfield-1-1
Possible to change this line code :
<code>self.SpawnInitCallSignName=string.lower(Name)or"enfield"</code> 
by
<code>self.SpawnInitCallSignName=string.lower(Name):gsub("^%l", string.upper) or "Enfield"</code>

Btw, if Name is null, string.lower return an exception, not null value. so may be it's better to have a local var like :
<code>local Name = Name or 'Enfield'</code>

Finally InitCallSign became : 

<code>
function SPAWN:InitCallSign(ID,Name,Minor,Major)
  local Name = Name or "Enfield"
  self.SpawnInitCallSign=true
  self.SpawnInitCallSignID=ID or 1
  self.SpawnInitCallSignMinor=Minor or 1
  self.SpawnInitCallSignMajor=Major or 1
  self.SpawnInitCallSignName=string.lower(Name):gsub("^%l", string.upper)
  return self
end
</code>

Thanks

**Comment by Applevangelist** [comment]
Sure. https://github.com/FlightControl-Master/MOOSE/commit/044fb66ca064687a743791e5a4a5d02c109ca9c1

**Comment by docbrownd** [comment]
> Sure. [044fb66](https://github.com/FlightControl-Master/MOOSE/commit/044fb66ca064687a743791e5a4a5d02c109ca9c1)

thanks you,
best
