### ISSUE TITLE
STTS doesn't check if executable is find, causing CTD

### ISSUE THREAD

**Issue by docbrownd** [FlightControl-Master/MOOSE#2141]
Hi, 
we recently add a ctld script that use MOOSE STTS class. But we don't need DCS-SR-ExternalAudio.exe. When function try to execute STTS.TextToSpeech we have a game crash.

I check this class and it appear that executable is not check before.

is it possible to add a simple function that check if STTS.DIRECTORY and/or STTS.EXECUTABLE is find before try to use it ? 

Thanks

**Comment by Applevangelist** [comment]
Sure - what are u using instead of DCS-SR-ExternalAudio.exe and how do you make Moose/DCS recognize that? The only other working option I know of is the rust server

**Comment by Applevangelist** [comment]
Moose checks that but I do not recognize the above variable names. From Cirian's original script we only use STTS.getSpeechTime

**Comment by docbrownd** [comment]
Hi, 
this var are in STTS class (line 4132 to 4135 in moose 2.9.5 compil file : 
`STTS={
ClassName="STTS",
DIRECTORY="",
SRS_PORT=5002,
GOOGLE_CREDENTIALS="C:\\Users\\Ciaran\\Downloads\\googletts.json",
EXECUTABLE="DCS-SR-ExternalAudio.exe"
}
STTS.DIRECTORY="D:/DCS/_SRS"
STTS.SRS_PORT=5002
STTS.GOOGLE_CREDENTIALS="C:\\Users\\Ciaran\\Downloads\\googletts.json"
STTS.EXECUTABLE="DCS-SR-ExternalAudio.exe"`

We use this CTLD script : https://github.com/ciribob/DCS-CTLD/blob/master/CTLD.lua 

in line 5655, ctld call this moose function : `        STTS.TextToSpeech(_shortMessage, _freq, _modulation, _volume, _name, _side, nil, 1, _gender, _culture, _voice, _googleTTS)`

And we are a CTD crash with DCS-SR-ExternalAudio.exe not find windows exception.

I check TextToSpeech function, and see nothing about check if executable exists, only if os/io are available

Thanks,

**Comment by Applevangelist** [comment]
Both of them belong to [@ciribob](https://github.com/ciribob) and not to Moose. Sorry, mate.

**Comment by Applevangelist** [comment]
-> If you use Moose CTLD and Moose MSRS we're in a better position to help you
