### ISSUE TITLE
Sound.Radio - SetFrequency has an undocumented dependency on SetModulation being called ahead of time when attaching Radio to a Unit/Group

### ISSUE THREAD

**Issue by DarthZyll** [FlightControl-Master/MOOSE#2147]
```
blueConvoyRadio = blueConvoy:GetRadio()
blueConvoyRadio:SetAlias("Blue Convoy Radio")
blueConvoyRadio:SetFrequency(50)
blueConvoyRadio:SetModulation(radio.modulation.FM)
blueConvoyRadio.FileName = "Convoy Escort Soundfiles/looks clear rest of the way.ogg"
blueConvoyRadio:Broadcast()

```

Run the above code, and you will find that the unit radio actually gets set to 50 AM. The problem is in RADIO:SetFrequency(). It is taking a frequency, and checking if self.Positionable is a UNIT or GROUP. When it is, it reads the freq and modulation and sets it on the positionable. Problem is that if modulation is not passed first, then it takes the default modulation (which is AM). 

A solution that will break as few existing use-cases as possible, you probably need to remove the defaulting to AM modulation, and in both SetFrequency and SetModulation, do the check for each other and if both are set, do the self.Positionable:SetCommand() call passing the properly set values.

For now, folks need to be aware that they need to set modulation first, then frequency in the example above, unless using AM in which case it won't matter due to the default values of Radio.

**Comment by Applevangelist** [comment]
Fixed in today's build. Settings a FM modulation after SetFrequency() has been done will reset the frequency and modulation
