### ISSUE TITLE
Event Handlers Not Working

### ISSUE THREAD

**Issue by Sci-fer** [FlightControl-Master/MOOSE#2153]
I did a mission in Mariana Islands with C-101. I used the same code as I always did, but at least take off and landing are not getting called.

```lua
player_unit:HandleEvent(EVENTS.Takeoff)

function player_unit:OnEventTakeoff(EventData)
    MESSAGE:New("Aircraft took off", 10):ToGroup(player_group)
end
```

I got no errors in the log.

Please advise

**Comment by Applevangelist** [comment]
These 2 don’t work anymore since the latest DCS release. Try runway takeoff and runway touch

**Comment by Sci-fer** [comment]
@Applevangelist,

That worked.

Thank you so much!

**Comment by Sci-fer** [comment]
@FlightControl-User,

The documentation is not updated for that ;)

Kind regards

**Comment by funkyfranky** [comment]
Hopefully, the takeoff and land events will be fixed by ED. It is reported https://forum.dcs.world/topic/353842-events-3-takeoff-and-4-land-no-longer-sent-out/
