### ISSUE TITLE
Moose latest version error

### ISSUE THREAD

**Issue by seavoyage-dcs** [FlightControl-Master/MOOSE#2174]
I received an error today that the latest MOOSE v2.9.8 downloaded from https://github.com/FlightControl-Master/MOOSE is 'an old Moose version'.  

![Screenshot 2024-09-06 193032](https://github.com/user-attachments/assets/fc7738ae-19af-4452-9a1c-9ddb333f7a4a)

Please advise if there is a newer version that is not posted in the repository.

**Comment by Applevangelist** [comment]
The latest build is here as always https://github.com/FlightControl-Master/MOOSE_INCLUDE/tree/develop/Moose_Include_Static
