### ISSUE TITLE
SPAWN InitLimit only Spawns one Unit/Group

### ISSUE THREAD

**Issue by Maloschnikow** [FlightControl-Master/MOOSE#2193]
Hello, so I'm using the following script:
```lua
--BLUE
SpawnAWACSBlueWest = SPAWN:New("AWACS BLUE-1"):InitLimit( 1, 100 ) --also tried (1,0), because this should enable infinite groups
--:InitRepeatOnLanding() --tried with and without this line
:InitCleanUp( 300 )
:SpawnScheduled( 60, 0.2 )
```
but the AWACS only spawns once. It doesn't respawn after despawning.

So the functionality of the script above should, according to documentation, be:
- Spawn the AWACS
- (despawn the group on landing and spawn a new one `InitRepeatOnLanding()`)
- schedule every 60+-12 seconds a new spawn `SpawnScheduled( 60, 0.2 )`
- Units should not spawn if one unit is already alive or 100 groups have already been spawned (`InitLimit( 1, 100 )`)

When removing `InitLimit( 1, 100 )` the script works fine, by just spawning AWACS after AWACS, so I'm assuming something is wrong with the tracking of how many units are alive.

**Comment by Applevangelist** [comment]
Try InitLimit(0,1)

**Comment by Maloschnikow** [comment]
Thank you, that works. I'll try to figure out why, but I'll take it.
