### ISSUE TITLE
TASKING: handle pilot exit event

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#220]
(wingthor) I wonder flightcontrol, if your state machines, (fsm) for tasking (stuff), eg A2G tasking, lacks the event, "Pilot Disconnects"? At least for me it appears like an ongoing task having a disconnected pilot, never get re planned

**Comment by FlightControl-Master** [comment]
Will be fixed in the new tasking release.

**Comment by thebgpikester** [comment]
Was this completed? There have been interim releases.

**Comment by FlightControl-Master** [comment]
This needs work and good testing. Ok. This gets a priority.

**Comment by FlightControl-Master** [comment]
This should be fixed now!
