### ISSUE TITLE
Setup LDT with MOOSE

### ISSUE THREAD

**Issue by Zook3r** [FlightControl-Master/MOOSE#221]
I'm running into difficulty following along with videos on youtube, specifically https://www.youtube.com/watch?v=7bhsLYHLVP4. At approximately 3:45 into the video, there is step I am unable to complete. Is there a workaround I am missing?

**Comment by FlightControl-Master** [comment]
Please write your question here::

https://forums.eagle.ru/showthread.php?p=3036416#post3036416

I am not following up issues on videos here... Only code...
