### ISSUE TITLE
SPAWN: InitRandomizeTemplate not working well with more than 1 unit in a ME group

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#228]
When using a group defined in the editor with more than 1 unit and using InitRandomizeTemplate, the group is not spawned properly. The units are spawned stacked on top of each other in a single spot. Example code:

`local RU_GroundArray = {"RU AAA ZU-23 Template 1", "RU AAA ZU-23 Template 2"}`
`local RU_GroundSpawn = SPAWN:New("RU AAA ZU-23 Template"):InitRandomizeZones({ZoneValley1, ZoneValley1, ZoneValley1}):InitRandomizeTemplate(RU_GroundArray)`
`local RU_Group1 = RU_GroundSpawn:Spawn()`
`local RU_Group2 = RU_GroundSpawn:Spawn()`
`local RU_Group3 = RU_GroundSpawn:Spawn()`

I think this is due to the fact that there is some issue in Spawn in using the "RU AAA ZU-23 Template" as a template for the spawning. When really it should just be using the ones from the array. It also doesn't matter how "RU AAA ZU-23 Template" is defined in the ME. It could be a bunch of units or single unit.

If one uses something like the following though the groups get spawned how they are setup in the mission editor. This is the desired functionality especially for groups that are stationary. They should adhere to how the mission designer would like them placed.

Code like this works perfectly fine:

`local RU_GroundSpawn = SPAWN:New("RU AAA ZU-23 Template 1"):InitRandomizeZones({ZoneValley1, ZoneValley1, ZoneValley1})`
`local RU_Group1 = RU_GroundSpawn:Spawn()`
`local RU_Group2 = RU_GroundSpawn:Spawn()`
`local RU_Group3 = RU_GroundSpawn:Spawn()`

with the desired results of the units within the group positioned properly.

**Comment by FlightControl-Master** [comment]
The issue is with InitRandomizeZones I think. Haven't tried that combination yet with InitRandomizeTemplate.

**Comment by FlightControl-Master** [comment]
Try to put InitRandomizeTemplate before InitRandomizeZones

**Comment by Delta-99** [comment]
Nope, makes no difference on the order called. Again, must be an issue with the InitRandomizeTemplate because it likely picks up the template from inside the New() in order to figure out where to place the units. I haven't had issues at all with InitRandomizeZones -> works fine in all simple cases and without using InitRandomizeTemplate. Not I think another user was having the same issue without using InitRandomizeZones so just the InitRandomizeTemplate with multiple units in a  group stack on top of each other. But I could be wrong on that last part. So much discussion and testing hard to keep track. But my test posted above will show things not working.

**Comment by FlightControl-Master** [comment]
have a look at this test mission, there does not seem much wrong with templating ...

https://github.com/FlightControl-Master/MOOSE/tree/master/Moose%20Test%20Missions/SPA%20-%20Spawning/SPA-018%20-%20Ground%20Ops%20-%20Randomize%20Templates

**Comment by Delta-99** [comment]
Ok, take your test mission and remove the waypoints from the group "Spawn Vehicle 1". This is the issue. All units from the 3 random templates get spawned only on ONE single position of "Spawn Vehicle 1". This only happens when you use InitRandomTemplate. If you spawn using my work around they spawn properly and in position.

This is because some of us would like to arrange a static defense (or anything else) of vehicles or whatever that stay in place (ie. do not have waypoints). This is very common for SAM installations and that sort of thing.

**Comment by Delta-99** [comment]
I believe I found the bug in the code causing this. I'm not sure how to fix it though so just posting here. I'm sure FC can fix it in no time.

Look at lines 1308-1311 in Functional.Spawn:

`      self.SpawnGroups[SpawnIndex].SpawnTemplate.units[UnitID].heading = self.SpawnTemplate.units[1].heading
      self.SpawnGroups[SpawnIndex].SpawnTemplate.units[UnitID].x = self.SpawnTemplate.units[1].x
      self.SpawnGroups[SpawnIndex].SpawnTemplate.units[UnitID].y = self.SpawnTemplate.units[1].y
      self.SpawnGroups[SpawnIndex].SpawnTemplate.units[UnitID].alt = self.SpawnTemplate.units[1].alt`

I believe this is spawning all of the units of a group onto one location because of the .units[1] - I think this needs to be coded to be an offset of the x, y and alt based on the units being spawned and the unit template.

**Comment by FlightControl-Master** [comment]
You are right, and feel free to fix this to what you would like to see ...
I never tried with non routed units. Thus never saw them stapling.

There is however somewhere an other parameter that would randomize the units wihtin a zone, as an option. Don't remember anymore where that is. I think SpawnInZone or something...

sv.

**Comment by Delta-99** [comment]
The SpawnInZone to randomize where groups are spawned doesn't help this case at all. It will produce the same issue. Remember we are talking multiple units in a single group. No matter where you spawn that group units within that group will NOT be spawned in their correct location but will be spawned on top of each other.

I'm not sure how to fix it yet and might take me a while to figure out how. I figured you'd know in about 2 mins.

**Comment by FlightControl-Master** [comment]
A solution could be to translate the x, y points from the template (that got randomly selected) to this new route begin points. You got the template in the function. You need to "translate" these x, y coordinates of each units to the new template origin. The class POINT_VEC2 contains a couple of functions to do that.
It will be an interesting exercise for you to try this.

**Comment by Delta-99** [comment]
Yeah, I think that is the solution. In theory relatively easy. But if only I could find the time!! :)

**Comment by FlightControl-Master** [comment]
I could resimulator this problem ... sort of... The units however don't appear stacked upon each other. They appear to be all at the same place though ...

**Comment by FlightControl-Master** [comment]
Fixed with pull request #251 . Please retest and close this issue after testing @Delta-99 .

**Comment by Delta-99** [comment]
Stacked on top of each other may have not been the right wording. Unless you are thinking old style board wargame with counters ;)

In any event I can confirm this is now working as expected. Tested in one of my own missions where it was not working previous to the fix.
