### ISSUE TITLE
AIB - Airport cleanup can't process parked carrier aircraft.

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#229]
Whilst working for airports, on a carrier, parked aircraft occupy slots and clog up the ATC system preventing AIB spawning new planes to depart. This is a hard limit of 4 on the Kusnetsov. Not tested with Vinson.

**Comment by FlightControl-Master** [comment]
I think there isn't an easy solution to this problem. Does anybody have an idea how to get this implemented? Also how urgent is this?

**Comment by thebgpikester** [comment]
Well you can simply leave it out of scope - ED's aircraft carriers are very basic implementation and use different rules for taxiing, addiitonally, a moving aircraft carrier may defeat the cleanup as the object is shut down but moving.

**Comment by FlightControl-Master** [comment]
Maybe close this then?

**Comment by thebgpikester** [comment]
OK, just need to keep a note that this is not going to work for AIB or spawn in some notes somewhere

**Comment by FlightControl-Master** [comment]
Thanks
