### ISSUE TITLE
"ground" category filter for SET_GROUP does not work

### ISSUE THREAD

**Issue by Nyapon** [FlightControl-Master/MOOSE#254]
Trying to filter a SET_GROUP with FilterCategories("ground") will result in an empty Set according to the log after flushing the set. When this filter is removed the rest will work fine.

I think the error is in the Set.lua in the SET_GROUP class.
The "_UNIT" should be removed from the expression ground = Group.Category.GROUND_UNIT

**Comment by FlightControl-Master** [comment]
Aha. Will check what is the problem and will push a fix. Can do this today. Thanks!

**Comment by FlightControl-Master** [comment]
Actually, I'll create enumerations so you can use those instead of string values. 
The string value system was implemented because of the unit type filtering.

**Comment by FlightControl-Master** [comment]
Try to use "vehicle".... Not ground.

**Comment by Nyapon** [comment]
Using "vehicle" instead of "ground" does not work. The sets are still empty.
I tried a modified version of the Moose.lua where I removed the _Unit part and now it works when I use the category filter.
