### ISSUE TITLE
SCORING:  The scoring will determine the threat levels in the category the unit hit or killed, and depending on weapon used, a score will be calculated. Killing a ship has a higher score than killing a Sam. That is meant with unit category.

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#274]

**Comment by FlightControl-Master** [comment]
Implemented, but only half. The threat level is currently implemented without an attacker context.
Threat levels should be implemented in a context of: A2A, A2G, G2G, G2A, N2A, A2N.
On top, the scale for the category of units should differ:
- Naval: 50
- Air: 20
- Ground/vehicle: 10

Keeping this open until fully implemented.

**Comment by baluballa** [comment]
Seems implemented
