### ISSUE TITLE
SCORING: Scaling of scores based on Category of Target.

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#276]
Naval: 50
Air: 30
Ground: 10

**Comment by thebgpikester** [comment]
I believe there was work done on this already, has it been completed, or what's left to do?

**Comment by Grey-Echo** [comment]
Issue #50 had this comment about this feature :

**Comment by FlightControl-Master** [comment]
This is done. Can be closed!
