### ISSUE TITLE
SCORING: Fix in MP the lack of scoring of static structures

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#280]
I think the problem is with a different event sequence or different values in MP versus SP.

**Comment by FlightControl-Master** [comment]
PLEASE TEST THIS!

**Comment by thebgpikester** [comment]
Initial tests seemed OK, Would like another view on testing and more time.

**Comment by FlightControl-Master** [comment]
Has this been tested now? Can somebody confirm?

**Comment by FlightControl-Master** [comment]
@thebgpikester @baluballa do you consider this working now?

**Comment by FlightControl-Master** [comment]
This is implemented, nobody reverted or confirmed. I close this issue. @thebgpikester @baluballa @HellRayzr
