### ISSUE TITLE
SCORING: Fix in MP that some clients have the scoring menu and others don't. Weird problem to be tested.

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#281]
Dutch-Baron brought this up.

**Comment by thebgpikester** [comment]
Added question flag, has this been resovled?

**Comment by FlightControl-Master** [comment]
Not yet. This needs to he tested. Not an easy one.

**Comment by FlightControl-Master** [comment]
@baluballa @HellRayzr As part of the push of release 2.0, this issue is fixed I think.
