### ISSUE TITLE
EVENTDISPATCHER: Hit event not distinguishing between units and Group

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#283]
Following code was run in a mission at separate times.
1. with UNIT no message i broadcast when the UNIT FAC is hit
local FACTank = UNIT:FindByName( "FAC" )
FACTank:HandleEvent( EVENTS.Hit )
function FACTank:OnEventHit( EventData )
MESSAGE:New("FAC is taking taking fire",10,"Incoming Comms Bat HQ"):ToAll()
end
 
2. With GROUP used a message is broadcast whenever any unit is hit. Message should show when only Group FAC is hit. 
local FACTank = GROUP:FindByName( "FAC" )
FACTank:HandleEvent( EVENTS.Hit )
function FACTank:OnEventHit( EventData )
MESSAGE:New("FAC is taking taking fire",10,"Incoming Comms Bat HQ"):ToAll()
end

**Comment by FlightControl-Master** [comment]
I agree. I need to implement this. For the moment, try to use only the UNIT Event handler.

**Comment by FlightControl-Master** [comment]
Will try to fix this today @gunterlund

**Comment by FlightControl-Master** [comment]
Can you try to test this once fixed? @gunterlund

**Comment by FlightControl-Master** [comment]
This got fixed by patch to master #288 . Can this be tested and closed? @gunterlund

**Comment by FlightControl-Master** [comment]
This works now. Closed.
