### ISSUE TITLE
FSM's need a STOP or END state

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#287]
FSM's need some way to stop or end so that for example I can retask a group to a new Patrol Zone. I think this can probably apply to any FSM really but this is just one example I know I've needed.

Oh, a user today just came up with a problem where something like this would work well for AI_BALANCER too.

I don't know if that requires specific cleanup for each FSM or what it might entail.

**Comment by FlightControl-Master** [comment]
Will try to fix that today.

**Comment by FlightControl-Master** [comment]
I will add a **Stop** event to the AI FSM to trigger a state transition from * (any state) to a new **Stopped** state.

**Comment by FlightControl-Master** [comment]
@Delta-99 once fixed, can this be tested?

**Comment by FlightControl-Master** [comment]
@Delta-99 This problem is fixed by #288 . Can somebody test this functionality?

**Comment by FlightControl-Master** [comment]
I am closing this.

**Comment by Delta-99** [comment]
Sorry, I haven't had a chance to test this. I have no problem if you close it however. Will get around to using this functionality at some point and then if it is a problem will reopen this if needed.

**Comment by FlightControl-Master** [comment]
Just remember: Stop <> Disengage . Stop = Stop the process. State goes to Stopped. Disengage = Abort(). :-)

**Comment by Delta-99** [comment]
Yup, I am fully aware of that. Been using Abort() in the past without issues. Have not had a chance to use Stop() yet.
