### ISSUE TITLE
Add Wrapper for DCS Radio communications

### ISSUE THREAD

**Issue by Grey-Echo** [FlightControl-Master/MOOSE#293]
Functions to Wrap
- Command "SetFrequency"
- Command "TransmitMessage"
- Command "StopTransmission"
- function trigger.action.radioTransmission(string filename, vec3 point, enum modulation, boolean loop, number frequency, number power )

**Comment by FlightControl-Master** [comment]
Great stuff man!

**Comment by Grey-Echo** [comment]
Update on Slack ! [](https://flightcontrol.slack.com/archives/moose-comms/p1489100740232708)

**Comment by Grey-Echo** [comment]
Basi implementation is working, now adding the Beacon functionnality

**Comment by FlightControl-Master** [comment]
Cool
Where is the code located?

**Comment by Grey-Echo** [comment]
@FlightControl-Master on the RadioComs branch

The RADIO code is at the polishing stage to make it merge-able. BEACON will have to wait for the merge.

**Comment by Grey-Echo** [comment]
[Update on Slack !](https://flightcontrol.slack.com/archives/C4EQ10Q2H/p1490014488080474)

**Comment by Grey-Echo** [comment]
[Merge is requested !](https://github.com/FlightControl-Master/MOOSE/pull/332)
