### ISSUE TITLE
Messages within AI_CAP and AI_CAS

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#302]
In my opinion I don't think anything in AI_CAP or AI_CAS should be sending messages.

In  AI_CAP_ZONE:onafterDestroy() there is a MessageToAll being called.
In AI_CAS_ZONE:onafterDestroy() there is a MessageToAll being called.

Both these should be left to the discretion of the mission designer on what they want to be displayed to the screen. Not sure if these were left in for debugging purposes.

Further, I'm looking into a bug with these messages as I THINK I am receiving them multiple times for multiple CAS zones. In otherwords the onafterDestroy() might be triggering for all CAS zones that don't even have to do with the one being triggered. Need to investigate that further and will enter a separate bug report if I find this for certain.

**Comment by Delta-99** [comment]
Confirmed now that gunterlund just reported that he is getting multiple messages displayed per kill. So it seems that multiple onafterDestroy() events are being called across AI_CAS_ZONE objects.

To clarify, I have 4 separate AI_CAS_ZONEs setup. If a target is destroyed by a CAS flight in Zone 1 for example, all 4 zones onafterDestroy() seem to be called.

See discussion here from gunterlund on slack: https://flightcontrol.slack.com/archives/mission-development/p1489276477389585

**Comment by FlightControl-Master** [comment]
On the messages I agree. Messages should not be displayed. However, wouldn't there be something like default messages that can be activated or deactivated? Otherwise people would need to catch the ondestroy event. 

Only for those targets in scope of the AI_CAS object, a Destroy event should be triggered by the logic. Will check this.

**Comment by FlightControl-Master** [comment]
Looking at the code ... And i am a bit puzzled....

In my opinion I don't think anything in AI_CAP or AI_CAS should be sending messages.

In AI_CAP_ZONE:onafterDestroy() there is a MessageToAll being called.
In AI_CAS_ZONE:onafterDestroy() there is a MessageToAll being called.

In AI_CAP_ZONE i find that the Destroy event is never called, which is strange ... Are messages sent in AI_CAP_ZONE after it destroys a target?

**Comment by FlightControl-Master** [comment]
Fixed with pull request #303 . Can you pls test if this solves the problem?

This is fixed:

-- Removed the Messages from the Destroy event handler.
-- AI_CAP_ZONE never got a Destroy event trigger because the Dead event
was never catched.
-- The Dead event handlers are now the default name to keep up with the
standard.
-- Check that ONLY the Destroy event is triggered for the targets in
scope.

Pls check and close if fixed.

**Comment by FlightControl-Master** [comment]
@gunterlund wanna add you to this test. Pls accept invite on GitHub.

**Comment by Delta-99** [comment]
I may be able to test this today if all goes according to plan. FC you are right, messages were never fired for CAP so good find there.

**Comment by Delta-99** [comment]
@FlightControl-Master while we are on this subject I will mention it here and open up a new issue if needed. It is related but may or may not be a bug.

For all of these FSM events like OnBeforeEngage() for example. Should they be fired at the group level or unit level? I am getting  these events fired for each unit of a group whereas to me it makes more sense to be getting them at the group level. If you know what I mean. Each unit is reporting the state that they are in but shouldn't it really be the group overall transitioning from state to state?

**Comment by Delta-99** [comment]
Ok, I can say that the messages are now not being spammed to the screen when on after destroy is called. I am not sure how to check the other part as I'm not sure which event I'm supposed to hook into.

**Comment by FlightControl-Master** [comment]
The event system of dcs is on unit level. It is normal you see the events logged, but when received by AI_CAP or AI_CAS, they are filtered to ensure that a Destroy is only generated for those units in scope. Hook into the Destroy event to check as you mentioned it before that Destroy events were triggered for not in scope units too... 

On you quest to have only a Destroy event when the group is destroyed. Just know that events are on unit level. On top, the targets are on unit level too... However, in consistency with the TASK classes, a **Destroyed** event could be triggered that indicates all units within scope are destroyed...

**Comment by Delta-99** [comment]
I did try to hook into the Destroy event of the object FSM but never received anything as far as I can tell but not sure I was doing things correctly.

Ok, so if events are fired per unit then that makes sense that I was getting them on the FSM level multiple times. But to me this sort of doesn't make sense and makes it difficult to figure out what is going on with the group in an FSM. For example I cannot really tell what state they are in because events are fired per unit and therefore one unit could be in a state yet another one not. This is fine if this is how it is supposed to work. I had to do some elaborate work around to make this work on the group level. Because I don't care what state each unit is in, I am only really concerned what state the group is in.

Again, if that is how things work it is fine. Just need to know how it is supposed to work so that I can code a workaround.

**Comment by FlightControl-Master** [comment]
Have you considered my suggestion?

**Comment by Delta-99** [comment]
Are you saying this "all units destroyed -> **Destroyed**" exists now or are you saying its possible to add to Moose?

**Comment by FlightControl-Master** [comment]
This can be added, yes. So, when the last unit of the scope of the cas is destroyed, I can optionally trigger a Destroyed event. Note however, that a pilot executing a CAS will never know when his CAS is finished... He gets the instructions from other other friendly parties. A FAC decides for example when a CAS is correctly executed. So, on the Destroy event handler you can easily determine how many targets are left as one of the example test missions shows. I mean, a CAS can end if a specific unit was destroyed, even if there are other units in scope, or, if an amount or a %-tage of units are destroyed. In such cases, it was the purpose to instruct the CAS process to Accomplish, Abort or RTB. Makes sense?

**Comment by Delta-99** [comment]
Yes, I'm not concerned about this Destroyed at all for CAS actually. I'm not sure how it came up.

What I was pointing out was that in attempting to test the Destroy or Dead events it reminded me that I gave up using the FSM events because they were not at the group level. So I couldn't properly keep track of state because events are fired at the unit level. So I had to do my own state tracking as a workaround.

So, for example, I want to know when my GROUP is heading to the patrol zone, when they are on station in the patrol zone, when they are enroute to the engagement zone, when they are engaging in the engagement zone, when they are RTB'ing. Not straight forward to do.

**Comment by FlightControl-Master** [comment]
Now I am even more confused 😖
I mean, the commands you indicate are for the group level, but the destroy event is something different as that involves the target, not the attacker. Rtb, accomplish, etc are at group level, actually at controllable level.

**Comment by Delta-99** [comment]
Now you see why I'm confused, read my comment here - https://github.com/FlightControl-Master/MOOSE/issues/302#issuecomment-285967090

**Comment by FlightControl-Master** [comment]
No. It depends of the process flow and the implementation. You associate what you see in the 'log' with what the FSM does, and that is what confuses you. Correct?

**Comment by FlightControl-Master** [comment]
Let's discuss this on slack. No use sending messages up and down like this. Let's clear this out.

**Comment by Delta-99** [comment]
No, this is what I catch with events. We are talking about 3 different issues now here.

**Comment by FlightControl-Master** [comment]
So as clarified on slack and now tested:
1. Messages: Fixed
2. Destroy or dead events not fired properly: Fixed (also in CAP)
3. Events triggered per unit not happening.
4. During testing of abort, saw that planes did not go back patrolling: Fixed

**Comment by Delta-99** [comment]
@FlightControl-Master I agree. I tried reproducing #3 and could not as well. This issue is closed.

Thanks for your hard work here.
