### ISSUE TITLE
CAS mission not using parameters set by variables

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#304]
The CAS routine is not using the values being passed into it. for instance, this set
RusHvyBombMission:__Engage( 1,1100,8000 ) states that the bomber should engage at an altitude of 8000meters at a speed of 1100km. The routine over rides this and forces the aircraft to engage at 400km at an altitude of 2000m. This feature should also take into account the type of aircraft being used. For instance bombers should not dive bomb and use one bomb at a time. We should be able to tell it what weapon and how many.

**Comment by FlightControl-Master** [comment]
self.EngageSpeed = EngageSpeed or 400
self.EngageAltitude = EngageAltitude or 2000

I am sure I had changes those statements to variables. Sorry guys. I will change this today. These hardcodings are wrong.

**Comment by FlightControl-Master** [comment]
I just looked again at these statements and they are correct. I also retested this mission and it works okay. The 400 and 2000 aren't hard codings. These are defaults set when EngageSpeed or EngageAltitude are nil, thus not given as a parameter.

On the comment of the "This feature should also take into account the type of aircraft being used. For instance bombers should not dive bomb and use one bomb at a time. We should be able to tell it what weapon and how many.", I can only say that it is up to the mission designer to specify the behaviour.
You can also provide the weapon expend etc.

I'll document the Engage method better in the documentation.
I suggest, have a look at the updated documentation, and if you need another parameter let me know.

**Comment by FlightControl-Master** [comment]
Check pull request #305 ( change in CAS)
-- Documentation
-- Test mission

**Comment by Delta-99** [comment]
@FlightControl-Master, gunterlund left out the important part of this. On the first call (from user mission lua) to __Engage with these parameters all will work fine however, when a new route is selected for this internally by Moose, __Engage(1) is called. This looses the values passed initially and speed and altitude revert to using the defaults.

So, when units are rerouted internally by Moose after the initial time things revert back to the default.

See line 363 in AI_CAS and AI_CAP lines 354 and 392.

**Comment by FlightControl-Master** [comment]
Ok. Now I understand. I will go for a fix on this one! Thanks!

**Comment by FlightControl-Master** [comment]
@gunterlund fixed in pull request #313. Please retest if you can and give feedback.

**Comment by FlightControl-Master** [comment]
@gunterlund I published another fix and could resolve the weaponexpend problem. Check out the following merge #316  and please retest.

**Comment by FlightControl-Master** [comment]
this was fixed, can i close this?

**Comment by gunterlund** [comment]
I think we got the parameter piece figured out, but he aircraft type is still open. Bombers wont work with this.

**Comment by FlightControl-Master** [comment]
This is an other issue. Pls open a new issue on git. The remedy is different for this one i think., and it ia better to make a new one.
