### ISSUE TITLE
AI_BALANCER - Bugs

### ISSUE THREAD

**Issue by CraigOwen** [FlightControl-Master/MOOSE#317]
**AI_BALANCER BUGS:**

1. No Respawn after ai unit gets killed.
2. Spawn of an additional plane when a client tries to enter a module he does not own.

**Missionsetup as follows.**
`-- Define the SET of CLIENTs
local RU_PlanesClientSet = SET_CLIENT:New():FilterCoalitions( "red" ):FilterPrefixes( "Mig21 red" )
local US_PlanesClientSet = SET_CLIENT:New():FilterCoalitions( "blue" ):FilterPrefixes( "F-5E blue" )

-- Define the SPAWN objects for the AI plane template.
-- We use InitCleanUp to check every 20 seconds, if there are no planes blocked at the airbase, waithing for take-off.
-- If a blocked plane exists, this red plane will be ReSpawned.
local RU_PlanesSpawn = SPAWN:New( "AI patrol red" ):InitCleanUp( 20 )
local US_PlanesSpawn = SPAWN:New( "AI patrol blue" ):InitCleanUp( 20 )

-- Start the AI_BALANCER, using the SET of red CLIENTs, and the SPAWN object as a parameter.
local RU_AI_Balancer = AI_BALANCER:New( RU_PlanesClientSet, RU_PlanesSpawn )
local US_AI_Balancer = AI_BALANCER:New( US_PlanesClientSet, US_PlanesSpawn )

-- Create the red polygon zones ...
local PatrolZoneGroupRU1 = GROUP:FindByName( "AI template patrolzone red" )
local PatrolZoneRU1 = ZONE_POLYGON:New( "PatrolZoneRed1", PatrolZoneGroupRU1 )

-- Create the blue polygon zones ...
local PatrolZoneGroupUS1 = GROUP:FindByName( "AI template patrolzone blue" )
local PatrolZoneUS1 = ZONE_POLYGON:New( "PatrolZoneBlue1", PatrolZoneGroupUS1 )

-- Now, create an array of these zones ...
local PatrolZoneArrayRU = { PatrolZoneRU1, }
local PatrolZoneArrayUS = { PatrolZoneUS1, }

function RU_AI_Balancer:OnAfterSpawned( SetGroup, From, Event, To, AIGroup )

--CAP
  local AICapZone = AI_CAP_ZONE:New( PatrolZoneRU1, 3000, 6000, 500, 800 )
  
  AICapZone:SetControllable( AIGroup )
  AICapZone:SetEngageRange( 20000 ) -- Set the Engage Range to 20.000 meters. The AI won't engage when the enemy is beyond 20.000 meters.
  
  AICapZone:__Start( 1 ) -- They should statup, and start patrolling in the PatrolZone.
end

function US_AI_Balancer:OnAfterSpawned( SetGroup, From, Event, To, AIGroup )

--CAP
  local AICapZone = AI_CAP_ZONE:New( PatrolZoneUS1, 3000, 6000, 500, 800 )
  
  AICapZone:SetControllable( AIGroup )
  AICapZone:SetEngageRange( 20000 ) -- Set the Engage Range to 20.000 meters. The AI won't engage when the enemy is beyond 20.000 meters.
  AICapZone:__Start( 1 ) -- They should statup, and start patrolling in the PatrolZone.
end`

**Current Log**
[dcs.txt](https://github.com/FlightControl-Master/MOOSE/files/852381/dcs.txt)

**Comment by CraigOwen** [comment]
This issue was solved by deleting all "local" declarations from the script, as local objects get garbage collected by dcs, meaning this is not related to AI_Balancer and therefore closed.

**Comment by FlightControl-Master** [comment]
To explain a bit on this...

**Comment by FlightControl-Master** [comment]
To explain a bit on this. In this latest upgrade the eventdispatcher has been modified. In the previous version, the local objects that used a class using a new event dispatcher or kept persistent in memory. Even if they were declared as local to the scripting file, they would still be kept in memory. Now, with the latest version, if the object becomes nil or out of scope, send it to be destroyed by the garbage collector. This wasn't the case, the previous version. In the previous version, the events were kept persistent in memory. Endling to the master object will skip persistent in memory as well. As a result, the garbage collector would never collect those local variables. So with this new event dispatcher that was required to be developed to support the new tasking system, you need to remember to declare your objects global in your Mission Scripts, where it is required (or they will be deleted). Most of the time global variable objects will be needed on the top level of your mission script file.
