### ISSUE TITLE
Making ZoneTable of polygon zones not working

### ISSUE THREAD

**Issue by EasyEB** [FlightControl-Master/MOOSE#329]
`Zone1 = ZONE_POLYGON:New( "Zone 1", GROUP:FindByName( "Zone 1" ) )
Zone2 = ZONE_POLYGON:New( "Zone 2", GROUP:FindByName( "Zone 2" ) )
ZoneTable = { ZONE:New( Zone1 ), ZONE:New( Zone2 ) }`

 `Group = SPAWN:New( "Group template" ) 
  :InitRandomizeZones( ZoneTable )
  :Spawn()`

Tried making units spawn in a random point of polygon zones to no avail.

**Comment by EasyEB** [comment]
Works. My code was wrong. Sorry!

**Comment by FlightControl-Master** [comment]
i see, it got closed!!!
