### ISSUE TITLE
CONTROLLABLE:CommandStopRoute(StopRoute, Index) not working?

### ISSUE THREAD

**Issue by EasyEB** [FlightControl-Master/MOOSE#330]
It seems as if CONTROLLABLE:CommandStopRoute(StopRoute, Index) could use some attention. It doesn't seem to work, or of course I'm using it wrong because I'm getting CTD.

**Comment by FlightControl-Master** [comment]
how urgent is this?

**Comment by FlightControl-Master** [comment]
Fixed with pull request #351. please retest and confirm!

**Comment by FlightControl-Master** [comment]
Closing this issue. Nobody tested or confirmed. Job is done. @EasyEB I hope you agree!
