### ISSUE TITLE
Prevent players from despawning midair when enemies are nearby...

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#34]
[ACG_IronJockel](http://forums.eagle.ru/member.php?u=109836) has posed a requirement on the eagle dynamics forums: http://forums.eagle.ru/showpost.php?p=2758890&postcount=94

_Hi Sven,
Thank you for this awesome framework!
I think this is the way to go with mission scripting etc._

I'm trying to create a function that blocks people from despawning midair to prevent kill denying. So what i currently think I need is a method that prevents people from despawning what I enable via an event handler.

Alternatively, some kind of punishment mechanism that blocks people that did despawn midair to spawn again for n minutes.

you're idea is similar to what i was thinking about if the block of despawning doesn't work. I think a kick is a bit to harsh. To prevent em from spawning for n minutes if they do it would be something appropriate. I gonna check what i can do with the scoring class, and reply next week.

**Comment by FlightControl-Master** [comment]
Should implement this in scoring.

**Comment by Delta-99** [comment]
Just thinking out loud here. Is this really a scoring feature? Can a case be made that this is useful for people not using the scoring system? I suppose if it can be a stand alone feature of scoring without requiring other parts of scoring then probably ok.

**Comment by FlightControl-Master** [comment]
It is not really a scoring feature. But was thinking of the penalty system... Maybe a separate class is better... And that can then be used optionally in the scoring... But also outside the scoring. You're right.

**Comment by FlightControl-User** [comment]
I think this requirement can be implemented using the slot blocker.
