### ISSUE TITLE
ZONES: Add functionality in ZONEs that fire off events when a GROUP, UNIT enters the zone or leave the ZONE...

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#345]
ZONEs need extra methods that allow to set event handlers, so when objects appear or dissapear in the zone, that an event would be triggered that could be handled... In other words, ZONEs are finite state machines :-) It shouldn't be too hard to make this stuff working, as i just need to define the FSM at ZONE_BASE.

**Comment by thebgpikester** [comment]
Let's mark it as a bug, despite it not being an error, due to this causing issues with the TASK not being removed as per bug #322 . this incident is required fixed as part of fixing #322

**Comment by FlightControl-Master** [comment]
Ok.

**Comment by baluballa** [comment]
Think this is implemented.
