### ISSUE TITLE
SCORING: Add WEAPON TYPE in the list.

### ISSUE THREAD

**Issue by HellRayzr** [FlightControl-Master/MOOSE#347]

**Comment by thebgpikester** [comment]
marking as non urgent bug, multiple requests for this and seems core.

**Comment by Grey-Echo** [comment]
Isn't this a feature request instead of a bug ?

**Comment by thebgpikester** [comment]
FC said he will fix in Slack https://flightcontrol.slack.com/archives/C1JQC6U73/p1490296947653973
If nothing had been said I'd have marked as enhancement as you said, but he'll track it easier as a bug than enhancement.

**Comment by FlightControl-Master** [comment]
We can fix this, there only difficulty is those destroyed static buildings. There the weapon is the plane itself. Question is how that is to be registered... Maybe in the shot event the real weapon is given. Need to check that. I'll do a first attempt to be tested next week.

**Comment by FlightControl-Master** [comment]
Okay guys, I am going to work on this item. It is not an easy fix... Believe me, it is not ...

**Comment by FlightControl-Master** [comment]
Moved to release 2.3.

**Comment by baluballa** [comment]
Think this is implemented,
