### ISSUE TITLE
Players in client slots cannot contribute to the detection mechanism - its AI only

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#348]
As per title. You need the AI to do detections, Needs confirmation that this will be intended. Listing as enhancement for now until assessment.

**Comment by FlightControl-Master** [comment]
How would a human player detect targets?

**Comment by thebgpikester** [comment]
For the purposes of this a very simple visual detection based on the visual range would massively help as a start....however if you know how to access the ed method theres other methods that work to show things like planes when locked up at greater distances.

**Comment by Delta-99** [comment]
If we have voting this has my vote. To me this is a much more desirable feature than other detection work that is going on or planned.

**Comment by FlightControl-Master** [comment]
Sorry. I mean with my question: You want the player to point the targets in the screen?

**Comment by thebgpikester** [comment]
Nope, I really dont think something should be complex in this, like designation or anything. However if you want to be slightly more clever than just 'inside the fixed radius' there is a camera script from ESAC_Matador that does a recon script and captures all statics and units beneath the plane in an arc of camera view. can talk more about that if you prefer something more complex. It's actually a recon camera script. I think player detection should work as a minimum, like this:
1. Inside 1.6km around the aircraft, automatic detection for players/client slots.
2. Message to screen on the detection, probably should be vague as we want it for the tasking system, not the recons's own benefit. Something like, "you've detected targets and sent back details to HQ" But a message should be sent so you know the tasking now has stuff you fed into it.
3. Optional complexity - full recon script, detects targets under the plane in a cone whilst it is flying steady wings level at certain altitudes.

**Comment by Delta-99** [comment]
I think this detection is enherintly built into DCS but I could be wrong. Just play with FOW turned on for your side only. Get into a plane with a buddy. You fly around and find a target while your buddy just sits and doesn't move. See if it shows up on the map for the other player. I believe this is all DCS detection working is it not?? Nothing different than AI detection.

**Comment by thebgpikester** [comment]
yes this is how it is. Plus some other techniques, for example, if you lock up a target on radar in an F15C at 30 miles it appears under fog of war. The visual detection is fairly wide in Fog of War, for AI at least, around 6000m or more. There's tables somewhere. But for consistency you want to be close to the DCS method and ranges else you get target reports which are confusing. But for this we really need to be able to contribute to detection since relying on AI and fixed routes wont work for anythign dynamic spawning. Or will take a lot of effort to contrive at least.

**Comment by Delta-99** [comment]
If this http://wiki.hoggit.us/view/DCS_func_getDetectedTargets can be used with human units then this is done. I would bet this works for sure.

**Comment by FlightControl-Master** [comment]
Guys. They problem is not the recon logic. Just trying to understand the requirement.
In the ka-50 you have a **VISUAL recon mode**. This displays a red cross in the cockpit and you can point a target on the battle field... If there is a target, it will add that to the detected list... Hence my question.

**Comment by thebgpikester** [comment]
I've never had anything that used it, if so then that's super cool, is it hard to use? If it's not too much trouble go for it, I didn't expect anything more than a proximity detection. It really depends on difficulty.

**Comment by Delta-99** [comment]
For me the first pass would be to implement the DCS detection. Once that is done it can always be enhanced with methods like FC is thinking of or other. But first and foremost why not use what is built into DCS? Sure, it may not be the best but it is what is pretty much expected and matches what AI is doing etc.

**Comment by FlightControl-Master** [comment]
I AM using the built in :-)

**Comment by thebgpikester** [comment]
I dunno the effort level, but finding the player detection then would be fine. It woudl make a massive player effect to have tasking for players that they coudl use their own recon or other team mates for. It's a very squadron thing though,

**Comment by FlightControl-Master** [comment]
I see! Well, I'll see what i can do on this one. But first let's get tasking decently working and the bugs on DETECTION resolved, and some instructional videos on DETECTION released. There are events that can be handled on the DETECTION class that were not explained yet.
In my Gori valley mission, i have an AI in a PATROL_ZONE, which is detecting TARGETS. The patrol zone is dynamically set depending on the upcoming enemey front line, so the AI won't crash into the enemy...

**Comment by thebgpikester** [comment]
Perhaps time for a revisit on this, since it was asked for in Discord recently? Can we review what the possibilities are in discussion perhaps to see if we can implement a player based detection based on visual range as a simplified model?

**Comment by baluballa** [comment]
@thebgpikester reopen if still relevant.
