### ISSUE TITLE
Unit Detection is not provinding information about unit spotted

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#349]
Mission DET-200 is provided as an example of how the system detects Units. My understanding is the unit labelled "Recce" should detect individual units and a message should be provided and last 15 seconds about what the unit is. The code is as follows;
RecceSetGroup = SET_GROUP:New():FilterPrefixes( "Recce" ):FilterStart()
HQ = GROUP:FindByName( "HQ" )
CC = COMMANDCENTER:New( HQ, "HQ" )
RecceDetection = DETECTION_UNITS:New( RecceSetGroup )
RecceDetection:Start()
function RecceDetection:OnAfterDetect(From,Event,To)
  local DetectionReport = RecceDetection:DetectedReportDetailed()
  CC:MessageToAll( DetectionReport, 15, "" )
end

what it shows is the following;
![image](https://cloud.githubusercontent.com/assets/12703141/24323516/e1d182e2-1133-11e7-9e78-0be9c58d709a.png)

it never shows what the unit is so there is no indication that detection is happening.

**Comment by Grey-Echo** [comment]
I'm able to reproduce this issue in Moose 20170323_1912. All that happen is that the message `(HQ): Detected units:` fades out and then reappear every 20s.
The detection seem to be working though, as evidence by relevant parts of the dcs.log attached below:
https://gist.github.com/Grey-Echo/80177743d4c60901638da0c1502eb358

**Comment by FlightControl-Master** [comment]
Will check this tomorrow

**Comment by FlightControl-Master** [comment]
Fixed with pull #366

**Comment by FlightControl-Master** [comment]
@gunterlund issue is fixed ... please retest and confirm fix.

**Comment by Grey-Echo** [comment]
Tested and working, I'm closing the issue !
