### ISSUE TITLE
Spawn for mulriple objects is broken on master

### ISSUE THREAD

**Issue by snakesn** [FlightControl-Master/MOOSE#350]
[_air_force_ops2.zip](https://github.com/FlightControl-Master/MOOSE/files/870197/_air_force_ops2.zip)

anold bug returns. brief description: if i spawn multiple objects to do patrol - they never go to patrol and there are no errors in the log file. BUT if i use branch 2be25298b898dfc4baf46f2bdc80f3f67e4022dc from 201703151 - ALL working just fine - for spawning. script and mission file attached

**Comment by FlightControl-Master** [comment]
are your variables defined as local?

**Comment by Delta-99** [comment]
In the sample that I saw him post the PATROL ZONE was setup as local so probably why it isn't working. I would wait for his reply to look into this. Perhaps we need a new label for issues like this.

Suggested labels:

**Possible Bug**
**need more info**
**cannot reproduce**

**Comment by snakesn** [comment]
i'm closing this bug. it does work with suggested solution
