### ISSUE TITLE
Document how to create ogg files from text to speech

### ISSUE THREAD

**Issue by Grey-Echo** [FlightControl-Master/MOOSE#354]
@gunterlund liked the sounds I created for RAD-002 and told me it would be a good idea to write a tutorial going through how to record your own sound card and how to add radio effects to the recorded sound.
Although it is only loosely related to moose, I might get around to do it if it helps mission designers to create interesting missions, which is the goal in the end.

It's not a priority though.

**Comment by FlightControl-Master** [comment]
You do text to speech???

**Comment by Grey-Echo** [comment]
Well I used a text to speech program to generate the sounds for RAD-002, and @gunterlund seemed to really like them. He asked me to write a tutorial on how I did them...

**Comment by FlightControl-Master** [comment]
I would also be interested to learn this. 

Other thing, would it make sense to create a repository with ogg files?

**Comment by Grey-Echo** [comment]
Not for the text to speech generated sounds, but it may be useful to share our radio sound effects. I think they have something like that in the ARMA community.
I like the idea !
