### ISSUE TITLE
Move Moose Presentation / Moose Training / Moose Logo in their own repo, and clean the repo from unused/outdated files

### ISSUE THREAD

**Issue by Grey-Echo** [FlightControl-Master/MOOSE#355]
This issue is part of the new release plan process. More details here : https://flightcontrol.slack.com/files/greyecho/F4P5G11QT/-.txt
This should be pretty easy to do, but **should only be done just before the release of Moose-2.0**, to avoid confusion. 
It should also be heavily documented and communicated, to again avoid confusion.

**Comment by Grey-Echo** [comment]
Possibly done ? @FlightControl-Master  is working on it, at the very least.

**Comment by FlightControl-Master** [comment]
Done.

New repos created:
https://github.com/FlightControl-Master/MOOSE_MISSIONS
https://github.com/FlightControl-Master/MOOSE_PRESENTATIONS

And MOOSE repo cleaned...
https://github.com/FlightControl-Master/MOOSE

@Grey-Echo i am sure you'll agree :-)
