### ISSUE TITLE
Create a Moose Install batch file to set up the developpement environment for the moose developer/beta tester.

### ISSUE THREAD

**Issue by Grey-Echo** [FlightControl-Master/MOOSE#356]
This issue is part of the new release plan process. More details here : https://flightcontrol.slack.com/files/greyecho/F4P5G11QT/-.txt

This batch file needs to :
 - Ask the user to install 7zip if necessary
 - Ask the location of
            - the user's MOOSE local repo
            - the location of the user's DCS World (or get it from the registry ?)
            - the location of 7zip (or get it from the registry ?)
- Create hard links between the user's MOOSE local repo and the user's DCS World/Scripts
- Add the 7zip folder to PATH
This should only be done **just before the release of Moose-2.0**, to avoid confusion.
It should also be heavily documented and communicated, to again avoid confusion.

**Comment by Delta-99** [comment]
Don't know if this helps at all but FC and myself discussed only saving the source of a .miz file in the repository. It may help a BIT with merging issues because only a few pieces change inside the .miz file unless you make a change in the ME. I am doing this now for my own projects and it is working out well. It also allows me to double check that I've actually made ME changes and not just .lua changes. 

I assume this whole process is really only relevant to Devs that will be contributing to Moose not regular users. Otherwise this process is going to be over the top for regular users I think.

**Comment by Grey-Echo** [comment]
@Delta-99 This process will only be necessary for devs and beta testers, check the link in the OP.

I think the whole thing can be done in [Inno Setup](http://www.jrsoftware.org/is3rdparty.php), which would mean a nice familiar GUI to set up the development environment for working with Moose Dynamic.
Working on a script right now, will see how it goes.

**Comment by thebgpikester** [comment]
I'm happy to help if you need an automation, I can do Autoit or even MSI packaging. So with GUI.
I'm very wary of entering into a dev setup when I concentrate on user testing and use and have resisted so far though I do sync and use a copy tool to keep my moose binary updated and i also load moose and scritps dynamically when building missions. The reason being, is thus far, Moose development is fast paced and introduces some error. But working towards stability now, and user experience, and trying to be a good and useful community member, I feel inclined to offer my time, however you need. I woudl rather champion the end user experience though :) I feel I can offer stupidity, as a valid view, easier!

**Comment by thebgpikester** [comment]
Oh and directly related .... take this opportunity to consider a redesign. There's nothing that says it needs to be done a certain way. I assume the aims are that the developers are wanting to always have the latest verison injected to their Miz? Is that really a good idea? Should we not leave commits to a nightly build process? Any other questions that can be answered? I could create a virtualised build environment that can cooexist with whatever else an individual needs using Software virtualisation and thus release it as a completely standalone package. Sky is the limit.

**Comment by Grey-Echo** [comment]
I appreciate your offer and understand your point of view. I think this issue is misunderstood, so let me explain and address you concerns.

**1. The Problem**
The MOOSE development is fast paced in will stay this way, which introduces 2 problems 
- Instabilities
- The need for the user to use GitHub.
- The developers need to generate a static version of moose before any pull request to the master, which is a source of errors and confusions

We feel like the end user and the developers shouldn't have to deal with either of those problems.

**2. The Solution**
The solution is to only generate a static moose every Release. The end user downloads his Static Moose.lua and only have to update (re-download) it every Release. He doesn't have to use GitHub and deal with instabilities.

The other effect is that the Github master only contains the dynamic version of Moose.lua. That means that developers or people who want to test the bleeding edge features will have to set up their computers to use GitHub (obviously), and Dynamic loading.
Since we want to encourage people to test/contribute, this setup should be as transparent and user-friendly as possible

**3. This issue**
For the Dynamic Loading to work, we need to do a dofile() on the path of Moose.lua. But we don't know where the Developer/Tester set up is local Moose repo. So, there are only 2 solutions: 
- Ask the Developer/Tester to set up his local repo in DCSWorld/Scrpits/ which is not flexible and a generally bad idea.
- Create a setup program, which asks where is the local Moose repo, and creates a hardlink to DCSWorld/Scripts/

We agreed that the second option was the way to go. If there is an other option we haven't considered, feel free to pitch in !
Some tools for manipulating .miz files are also using 7zip, which should thus be added to the PATH environment variable. Again, to stay as user friendly as possible, we thought that making the setup program do it is the way to go. If there are other ways to do it, then please comment it below !

**4. Your concerns** 
Depending on what you want to do with Moose, you have 2 options:
- Test and use the Released static Moose as a normal end user. Then, no installation process, you just download the latest release of Moose.lua, add it to ME and you're good to go
- Test the bleeding edge features added by the latest commits and merges. You will have to setup GitHub, run the install program described in this issue, and, in ME, load Moose.lua located in DCSWorld/Scripts/, which is, by it dynamic nature, automatically updated every time you do a git pull.

For the .miz files, we are working on improving the already existing tools to batch update the Moose.lua in the .miz files. That way, if you started your mission on Moose Dynamic, and you want to release it with a static version of Moose.lua, or if you have an old version of the release Moose.lua in your .miz file and you want to update it, then you just have to use a tool inside LDT.

You are probably way more knowledgeable than me in how to release software in general, so if you think there is a better way to accomplish our goals, while keeping the setup process for Des/testers easy and user-friendly, I am totally opened to your suggestions

**Comment by thebgpikester** [comment]
Thanks for the added explanation. So the suggested tool will inject MOOSE.lua from somewhere to a place of the developers choice and all Miz files in those folders? Or just some? I can do that with a simple executable binary, rough design....you run it from the root of the folder it's in and it takes moose and put it there. One click, informational dialogue when complete. Is that design workable? Rather than try to be complicated with paths, how about a design that just looks for where it is currently? Put updated moose in the same folder as it and all the missions and run it, no dialogue required. Will work for any folder then. Is that useful or am i barkign up the wrong tree?
As for the remaining automation of getting moose there, I see the end to end process as this:
1. Sync Github. (does it have command line access? maybe, in which case can be part of this)
2. Sync  Moose.lua from Github to wherever the developer works (this DOES have command line so can be autroamted)
3. Run the suggested binary. (I can create it with command line so you can automate via WIndows scheduler to happen seamlessly)

End result. No user clicking, on a schedule, MOOSE.lua is updated in a specific folder of your choice.
Is this what you are proposing?

**Comment by Grey-Echo** [comment]
I think I need to explain in more details the difference between moose static and moose dynamic loading. 

- Moose static is really simple, there is a tool which concatenates every lua file which constitutes Moose into just one: Moose.lua. It the file loaded in ME by the end user. If the devs where using it, every time you change a line in Moose, you would need to generate the new Moose.lua, replace the old Moose.lua in the .miz file you are using to test your changes, and play the mission. This process is partly automated already, but ME doesn't like changes to the .miz file while the mission is open, so you would need to close and reopen the ME everytime.

- Enter Moose Dynamic loading. Instead of concatenating every lua file of Moose into a big one, you use a Moose.lua file which (simply put) calls a dofile() for every lua file on Moose. This way, your big Moose.lua is generated at runtime, using the last changes you made in the Moose lua files. You make the ME load this dynamic loader at the start of the mission, and every change you make to Moose is automatically taken into account when you restart the mission (you don't have to close the ME and change Moose.lua, then restart the ME). The drawback is that you need to call some dofile(), and you don't know where the local repo is located, that's why we need to do these hardlinks.

This dynamic loading technic is currently only used by devs in our test missions, on our own branch while working on Moose. Every time we merge, we need to generate the static Moose.lua, update our test missions to use this static Moose.lua and then merge. And every time Moose is changed, we need to update every .miz test files to use the new static Moose.lua. Even though it's partly automated, it is time-consuming and confusing, that's why we are trying to reduce the number of static Moose.lua generation to the minimum (only when releasing).

If I understand well (and correct me if I'm wrong), your proposition would be to use the static loading method, have a program which downloads the latest static moose.lua and then inserts it in every .miz files in a folder. This is useful for the end user who uses the static Moose.lua and wants to update their mission. We already have a tool to do that, it is a .lauch file in LDT that we want to make more flexible and user-friendly, but can do this job. But it doesn't resolve the issue that using static generation in a rapidly evolving moose development is a pain.
 
No, the goal is to generate the static Moose.lua as rarely as possible (every Release), and to make using Dynamic Loading of Moose as easy as possible. The best way would be to use dofile() to access the local repo directly, but it is impossible (we talked about that on slack). The only other way I can think of would be to create a program that copies every .lua file constituting Moose in DCSWorld/Scripts so that they can be loaded by dofile(), but at this point, why not use hardlinks?

Or maybe separate the Tester and the Dev work Process, and create a Tester only tool which would download from GitHub all the lua files constituting Moose, automatically concatenate them to generate a static Moose.lua, and update the .miz files with the new static Moose.lua in its folder. That way the master doesn't have to contain the static Moose.lua. Note that the tool described in the OP would still be needed to simplify the setup of the dev env for people who want to contribute to Moose anyways.

**Comment by thebgpikester** [comment]
ah much better. I wasn't understanding the concatenation (as I don't do it)But I do understand the problem now. Is it of any use then to track down where Github desktop stores the paths to projects, then? Also is a Moose updater file that inserts moose to mission files of any use? I had a quick look, Github desktop is not a conventional application, sadly.

**Comment by Grey-Echo** [comment]
THAT is a good idea. Is there a way to make the Moose.lua dynamic loader know the path of the MOOSE local repo ? If so, no need for hard links, we coud simply dofile() in the repo directly. In need to look into this more.
The Moose updater already exists, we want to refine it, as I said, because it is useful for the end user to update his missions to the latest Moose release, and for the dev to easily change his mission from using dynamic loading to static loading.
I don't know what you mean by "Github desktop is not a conventional application", I'm using the console anyway.

**Comment by FlightControl-Master** [comment]
Sorry.. I don't want again a discussion on static and dynamic loading... Done this a year ago and it is a never ending story.

Those who want the latest features and alpha test must cobfigure an environment and use dynamic loading from the scripts folder with the latest pre-release moose version or test branch.

Those who want an easy environment and no additional configuration can't test the leading Edge features and can only use the stable static loading version.

What's so difficult on this?

**Comment by Grey-Echo** [comment]
Acknowledged.
Let's make the setup of the development environment as simple and smooth as possible then, this is the core of this issue. If anyone has any better idea than an Inno Setup script, go ahead!

**Comment by thebgpikester** [comment]
Regarding getting the link to your local repo, it's in a file called C:\Users\username\AppData\Local\GitHub\cache.db but it's not nicely formatted and much of the information is saved in the cloud (your connection credentials and certificates are also messy) so after 30 minutes review, its less effort for the user to create the hard link to their local copy. Hence "non standard", Github Desktop is a .net app that's not saving information to the usual places in Windows....like the registry.

@FC, only looking ways to automate any of this to make it simpler, and easy ways at that. There's a completely different question on consumption of the moose.lua for users that is worth having. I write programs that automate things like this, using Autoit, which for a few lines code can do batch processing on things like 7Zip use, file searches in folders and so on.

**Comment by Grey-Echo** [comment]
Is there a way to look for a key in the windows registry and updating the %PATH% using Autoit? How hard would it be? I'm trying to find the best solution between Autoit and Inno Setup...

**Comment by thebgpikester** [comment]
Yes, for applications that use those. very easy, pseudocode is something like: $Myregpath = regread(HKLM\SOFTWARE\somewhere) Myfilepath = Fileread($myregpath/moose.lua) Filewrite(Myfilepath) etc etc. it's deisgned like that. Unfortunately Github desktop makes this realy difficult as it writes into little db files as far as I can tell.

**Comment by Grey-Echo** [comment]
Yeah, I know. Ok, then,  I would like to know, In your estimation, how user-friendly and how time-consuming would it be to create an Autoit script to do, bearing in mind that I need to learn Autoit first since I never used it before :
- Read the path to 7zip in the registry
- Add this path into %PATH%
- Ask the user the path of his DCS World install
- Ask the user the path of his local repository
- Create a hard link between the local repo and DCSWorld/Scripts/
- Ask the user if he is a contributor or a tester
- If he is a contributor, copy a folder in ProgramFiles

**Comment by thebgpikester** [comment]
if you were learning it, and if you had a developer head its very easy. I can cut some corners pointing to the resources. There's a UI builder that's graphical that outputs the code. But its really good for automation and I'd say worth while. You start to create things for work. It has SQL plugins and advanced stuff too. But its cheap on words, super high level and the only thing you ever struggle with is quotation marks and embedding scripts and counting if you are on a double quote or a single or double doubles...or even triples :P  If I can learn it, anyone can. but you woudlnt be on your own if you wanted to do it. I'd deffo help.

**Comment by Delta-99** [comment]
I think we have to keep in mind testers or bleeding edge users who want the latest version of Moose yet possibly won't go through this entire process or setup or environment.

So we need some middle ground here I THINK with a simple process that generates a static moose.lua if the intent is to NOT included it on a main merge or final commit of something. Something like this was mentioned in the thread above and I don't think it should be lost.

Or we need an automated thing that hooks into github or git desktop or something that generates the static moose.lua on every commit. Aren't there hooks like that for GIT? Got to be right?

For myself I haven't bothered at all with the dynamic moose.lua because I was confused with the instructions or reason for why I needed it. I can see the usefulness of it though.

So I just generate a static moose.lua after some changes by having a command window open all the time. Then couple clicks to include it while testing. But of course I was only doing a few small changes and testing with Moose and I can see this being a pain if you were primarily doing this.

**Comment by Grey-Echo** [comment]
@Delta-99 "For myself I haven't bothered at all with the dynamic moose.lua because I was confused with the instructions or reason for why I needed it."

Exactly. You are waisting your time because the setup process was too hard and not explained well enough. Both things we want to change. And there is something you might not have thought about: if some tester are using static and some are using dynamic, tracking down issues and bugs will be a mess. 

Honestly, if the setup process is a simple as GitHub install -> Click on MooseDevelopmentEnvironmentSetup.exe -> You are set, I think it is doable for everybody. With the added bonus of not having to update your test missions with a new Moose.lua everytime you make/there is a change.

**Comment by FlightControl-Master** [comment]
Guys, I really, really don't understand the issue @Delta-99 9 and @thebgpikester . So much words and text over a simple concept.
Those who want to continue to use the normal loading as of today, will be able to do so. Those who want more and faster delivery times on new features, will have to do something extra. Those will need to make a link on ONE directory. Wauw. What is the problem with that.
Those people who are not capable of doing so, will just load the missions from the release version and test. Those who want more features, will test in other branches and will be more happy.
We will create videos to explain these things. Only a few people read documents anyway. Videos is the way forward accompanied with documentation. It has proven to be very effective and works. The reason why i gave up on explaining dynamic loading was the lack of interest to help developing the framework from the community. Now maybe there is a momentum to change that. It is in the users interest to follow this initiative. But we will have to explain it well. And @Grey-Echo is working hard to smoothen the learning curve.

**Comment by Delta-99** [comment]
> Those people who are not capable of doing so, will just load the missions from the release version and test. Those who want more features, will test in other branches and will be more happy.

No issues here just comments.

Testing a release version is not testing and it has the potential of alienating a great majority of people here that are very interested in testing and providing valuable feedback and bug reports on non-stable releases, features and bug fixes. They may not necessarily be active or even able to develop Moose source.

These are the people I am talking about here and I am just making a very simple point. Don't dismiss them.

If the process is super simple and covers these people then discussion over. If not, keep thinking of a solution because otherwise you might end up with a VERY VERY small group helping you test before a proper release.

**Comment by Grey-Echo** [comment]
@Delta-99 Yes. This was the point since the beginning. The idea has always been like that. Let's make it easier for everyone. 
- For the end user : Simply use the stable release, no need to use GitHub anymore
- For the Beta tester : a very slighlty harder to setup (but we are working on making the setup super user friendly and very well documented), but then easier to use : no need to update the mission Moose.lua whenever there is a new merge, you sync master on Github and it's automagically done for you. You also get access to tools to batch process your .miz files.
- For the contributor : WAY simpler to setup, no need to generate and manage test missions with Moose.lua static (which is a pain ATM), bug reports from beta tester who are using the same setup (easier to track down bugs)

Don't be afraid of the very small added step to the setup for the beta tester, it is gonna be **a simple GUI program which is going to ask for some locations (folder paths), and then do the work for you**. And there will be a tutorial with screenshots. And hopefully a video. The (small) work will be well worth the reward I swear.

The hope in the end is that the many advantages for everyone outweigh the (very) small cost of a **very slightly** harder setup for beta tester, which can be made even easier by automation and documentation. This thread is the demonstration that **we need to work hard on our communication before releasing Moose-2.0**, so that we don't alienate a part of the community.

**Comment by Grey-Echo** [comment]
This is done. AutoLt was definitely the way to go.

**Comment by Grey-Echo** [comment]
Pull request : https://github.com/FlightControl-Master/MOOSE/pull/370
