### ISSUE TITLE
Update .lauch files to make them more flexible

### ISSUE THREAD

**Issue by Grey-Echo** [FlightControl-Master/MOOSE#357]
This issue is part of the new release plan process. More details here : https://flightcontrol.slack.com/files/greyecho/F4P5G11QT/-.txt

For the moment, the moose script command files (.launch files) added in LDT only work for Moose, even though some of them would be useful for users' missions. For example, users need a good tool to re-import their mission files into the .miz files for end-user mission developments. The tool exists, but it needs to be made more smooth.

It should be heavily documented and communicated, to avoid confusion.

**Comment by FlightControl-Master** [comment]
Done.

**Comment by FlightControl-Master** [comment]
Closing this issue. Job is done.
