### ISSUE TITLE
Communicate the changes done to the Realase plan.

### ISSUE THREAD

**Issue by Grey-Echo** [FlightControl-Master/MOOSE#358]
This issue is part of the new release plan process. More details here : https://flightcontrol.slack.com/files/greyecho/F4P5G11QT/-.txt
Here is what I think should be done to make the transition to Moose 2.0 as smooth as possible for everybody in term of communication

- Heavily update this page: http://flightcontrol-master.github.io/MOOSE/
	- **1.5) Moose release cycle** explain the release cycle. **Is there a better place to do it ?**
	- **4) Demonstration Missions** need to be updated to reflect the fact that they are on their own repo.
	- **5) MOOSE Directory Structure** need to be entirely reworked
	- **6) Mission Design with MOOSE** need to be reworked to reflect the fact that this is the end user way of doing thing, not the dev/beta tester
	- **7.1) MOOSE core Classes** add RADIO (because I'm proud of it :D)
	- **8) Credit** I'm sure some other people need to be credited... ahem... :shy: **Who else ?**
- Heavily update http://flightcontrol-master.github.io/MOOSE/Installation.html
  - The whole thing needs to be remade, separated into 2 parts: one for the user and one for the beta tester/developer.
	- Don't forget to include a link to here: https://github.com/FlightControl-Master/MOOSE/releases
	
- Remove the links and redo the Moose setup video: https://github.com/FlightControl-Master/MOOSE/releases
  - Maybe make a version for the beta tester/dev too?
	
- Prepare a small FAQ about the release cycle, the static vs dynamic moose loading and the installation process for the OP on ED's forums.
	- Could be useful on Slack too.
	
**Can you think of something else that should be done to better communicate and explain the changes that come with Moose 2.0?**

This should only be done **just before the release of Moose-2.0**, to avoid confusion.

**Comment by FlightControl-Master** [comment]
Been updating the documentation on master. 
**Created a Usage Guide** and cleaned the main page.

**Comment by Grey-Echo** [comment]
I'm working on the Beta_Test_Guide.md file on my branch (Grey-Echo). I would say 2/3 done, it's a huge chunk of the documentation. The Contribution_Guide.md will probably borrow from it heavily.

**Comment by Grey-Echo** [comment]
What is done on my end:
* Beta_Test_Guide: everything but part **4) Tools to help you manage your .miz files** -> On Master
* Contribution_Guide: everything but part **1) GitHub/Git organization** and part **6) The Issue Tracker : labels and milestones** -> On my branch.

**Comment by Grey-Echo** [comment]
When the two pull request pending are accepted, I think we are set !

**Comment by Grey-Echo** [comment]
Although dac work is never finished, I'd say we can close this issue.
