### ISSUE TITLE
Documentation, templates, and examples should default to "embedded" as the primary mode

### ISSUE THREAD

**Issue by glyphoglossus** [FlightControl-Master/MOOSE#36]
There are two modes for incorporating MOOSE: dynamic and embedded. By default the former is favored. This makes sense from the POV of Moose development. However, for mission builders using MOOSE or developers who are developing scripts that rely on MOOSE but not actually editing the MOOSE code base, it probably makes more sense to use rely on embedded MOOSE. I think favoring this approach in the MOOSE documentation will greatly increase adaptation rate, as people will find it easier to understand and do (as it follows how, e.g. MIST, CTLD or other scripts are used). 

In any case, I suggest two templates bundled with MOOSE: (1) the current one, which allows for easy switching between embedded/dynamic based on a flag value; (2) a embedded-only one, which allows for mission builders who just want to use MOOSE to easily build missions.

Both (1) and (2) should, of course, need to be updated every time the MOOSE library is updated. This can be a PIA, I know! But I am thinking in the future we could maybe have some support utility scripts that unzip the template mission file, replace the embedded MOOSE lua file with the new one (generating it first if needed), and then zipping it up again? Don't know if this is feasible or robust, but I could look into it in the future ....

**Comment by FlightControl-Master** [comment]
There are solutions for automatic file synchronization. I am using goodsync as a sync tool.
It copies the *.lua files automatically from my MOOSE package to the Scripts\Moose directory in the program files folder.

The embedded file is indeed a PIA, that is why i started with dynamic loading in the first place :-) Believe me, i've searched for all the options, and had to do some lua tricks to make the dynamic loader work ...

FC

**Comment by FlightControl-Master** [comment]
But i am hearing you... You suggest to emphasize the "embedded" loading as the only option...
I think you're right. I should emphasize this more in the documentation.

Embedded loading first, and only for those who are developing (and extending) Moose, dynamic loading is used, which is a more advanced loading method.

Also, maybe indeed we can setup a process to automatically copy the Moose_Embedded.lua file into a mission file before publishing... I think this can be easily done with a zip tool installed.

**Comment by glyphoglossus** [comment]
This sounds good.

Also, I think even when developing, we should definitely test with the embedded files. So the workflow is: edit MOOSE Lua, generate embedded file, and then the mission files load the embedded file. That way, we are testing the actual file that 99% of people (non MOOSE developers) will use. With good file syncrhonization and scripts, this should all be in the background. Eventually, do away with dynamic loading (two ways of using MOOSE makes maintenance/debugging etc. tricky)

**Comment by glyphoglossus** [comment]
I should note that I am currently having a lot of difficulty in getting even a simple mission to work with embedded MOOSE. Dynamic is no problem. But "Do Script File" with "MOOSE/Loaders/Moose_Load_Embedded.lua" does not work. Directly "Do Script File" with  "MOOSE/Embedded/Moose_Embedded.lua" also does not work. "Do Script File" with "MOOSE/Loaders/Moose_Load_Dynamic.lua" works fine. Still trying to figure this out.

**Comment by FlightControl-Master** [comment]
> I should note that I am currently having a lot of difficulty in getting even a simple mission to work with embedded MOOSE. Dynamic is no problem. But "Do Script File" with "MOOSE/Loaders/Moose_Load_Embedded.lua" does not work. Directly "Do Script File" with "MOOSE/Embedded/Moose_Embedded.lua" also does not work. "Do Script File" with "MOOSE/Loaders/Moose_Load_Dynamic.lua" works fine. Still trying to figure this out. 

I'll check it too... Haven't tested it.

**Comment by jeetsukumaran** [comment]
> Also, maybe indeed we can setup a process to automatically copy the Moose_Embedded.lua file into a mission file before publishing... I think this can be easily done with a zip tool installed.

If this can be automated, along with auto-generation of the Moose_Embedded file, then the dynamic loading can be deprecated.

But even if not, as I suggest above, I think a workflow in which following any editing of the MOOSE library, the library gets "compiled" into single embedded file, and this is the file that is loaded in the mission, would guarantee that all our testing/experimentation/mission-building is done using code/files that will generally be available to most people.

**Comment by glyphoglossus** [comment]
Again, got my accounts mixed up! Sorry. Above is me again ...

**Comment by FlightControl-Master** [comment]
Related to:

>  But "Do Script File" with "MOOSE/Loaders/Moose_Load_Embedded.lua" does not work. Directly "Do Script File" with "MOOSE/Embedded/Moose_Embedded.lua" also does not work.

I think i found the solution.
Reload the latest Moose_Embedded.lua file from the Moose\Embedded folder.

recheck pls.

**Comment by FlightControl-Master** [comment]
Before i forget. Nice to meet you Jeet. You're welcome to join.
Would this automatic including of the moose_embedded.lua file be something you could investigate?
The problem is with your following statement:
>  and this is the file that is loaded in the mission, 
cannot be done when your mission is open. You would have to close your mission, and reload it again after the embedded file got included. That is why i started with dynamic loading...

Once a mission is "finished" or ready for a release, the embedded file could be added. I think indeed that process can be further automated.

**Comment by glyphoglossus** [comment]
Nice to meet you, too!

OK, I do not understand this.

So here is the process:

1. Go to Mission Editor
2. create new mission
3. Create new trigger: ONCE, no condition, ACTION = "Do Script File", with file = "MOOSE/Embedded/Moose_Embedded.lua"
4. Create new trigger: ONCE, condition = time > 2 (though I have also tried nothing here), ACTION = "Do Script File", with file = "my_mission.lua" 
5. Fly

You are saying the above is wrong?

**Comment by FlightControl-Master** [comment]
It is not wrong. it is good, if you want only to use embedded loading, which is fine.
If you can make a trick to get every time ALL the mission file get updated with a new embedded.lua file, once i've changed some moose code, then that would be great.
Even the mission file you currently have open in your mission editor, without having to reload it..

**Comment by glyphoglossus** [comment]
Ah yes, but for some reason, the above does not seem to work for me. Still trying to figure it out!

**Comment by FlightControl-Master** [comment]
Jeet, i have completely reworked the loading method and have implemented a tool that can replace the MOOSE version in a batch of DCSW mission files residing in a couple of directories.
Now the embedded is the standard method. Dynamic is still supported, but not anymore documented. It is for developer purposes only.

**Comment by jeetsukumaran** [comment]
Definitely will be helpful getting people to use this!

**Comment by glyphoglossus** [comment]
Definitely will be helpful getting people to use this!

**Comment by FlightControl-Master** [comment]
Done, now only one file needs to be included, which is Mooe.lua.
