### ISSUE TITLE
Whenever Moose sends a MESSAGE to the user, give the possibility to send a RADIO Transmission as well/instead

### ISSUE THREAD

**Issue by Grey-Echo** [FlightControl-Master/MOOSE#360]
This is a huge endeavor, but it has already been requested by multiple people. 

It relies on issue #359

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
