### ISSUE TITLE
CLIENT: Some methods in GROUP and UNIT are inherited from POSITIONNABLE, but may not be compatible.

### ISSUE THREAD

**Issue by Grey-Echo** [FlightControl-Master/MOOSE#365]
Find which incompatible methods GROUP/UNIT inherit from POSITIONABLE,  and implement their polymorphic version to make the compatible, just like it has been done for issue #362

**Comment by Grey-Echo** [comment]
In fact, this applies the whole hierarchy if we want to strictly abide by Liskov's Substitution Principle. It's a HUGE task, and it is far from urgent, so I'm moving to Moose-Future

Note that we should be prepared to get asked why, for example, CLIENT:TaskAttckUnit() doesn't work, even though it exists.

**Comment by FlightControl-Master** [comment]
yeah. it is the 20%-80% rule... 80% of effort to make 20% of people happy. Note that i did already a lot in that field, or nothing would work :))

**Comment by FlightControl-Master** [comment]
Note that TaskAttackUnit etc. WILL work.... As units and groups ARE controllable.  So the task is not _that_ huge.

**Comment by Grey-Echo** [comment]
UNIT:TaskAttackUnit will work. not CLIENT:TaskAttackUnit, because AFAIK, CLIENT don't have a Controller (that wouldn't make any sense)

**Comment by FlightControl-Master** [comment]
Ha yes, true... However CLIENT is a unit, but cannot be signed tasks.. Hmmm... It is not controllable, but neither positionable... It is something else ...

**Comment by Grey-Echo** [comment]
I'm currently making the UML Diagram for the whole hierarchy. When done, I will be able to see more clearly which class should derive which functions and which shouldn't.
Honestly, don't think too hard on this issue, it's a long-term project to increase the cleanness of the code, and won't add any functionality for the mission designer.

**Comment by FlightControl-Master** [comment]
PLAYABLE?

**Comment by FlightControl-Master** [comment]
Please make so that it can be presented. There are PowerPoint slides in training. Dont start from zero. Did already work on that.

**Comment by FlightControl-Master** [comment]
you know, the issue with client is not an issue. It is good. The place of client in the hierarchy is good.

**Comment by Grey-Echo** [comment]
If you say so, I have no problem with that. Conceptually it makes sense that CLIENT is a UNIT. But this will create some confusion, because it inherits function which are not compatible and need to be rewritten just for it (polymorphism). 
Anyway, that's a long-term project, hence the Milestone Moose-Future

**Comment by FlightControl-Master** [comment]
It makes sense for making logic... Now using need to distinguish between a human or AI. We'll discuss on slack if ok.

**Comment by FlightControl-User** [comment]
Nope the design is correct.
