### ISSUE TITLE
SPAWN: bug in SPAWN:_OnDeadOrCrash() when :Respawn method from GROUP.

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#367]
Getting consistent error in log on this code
``` lua
--- Obscolete
-- @todo Need to delete this... _DATABASE does this now ...

--- @param #SPAWN self 
-- @param Core.Event#EVENTDATA EventData
function SPAWN:_OnDeadOrCrash( EventData )
  self:F( self.SpawnTemplatePrefix )

  local SpawnGroup = EventData.IniGroup
  
	if SpawnGroup then
		local EventPrefix = self:_GetPrefixFromGroup( SpawnGroup )
    self:T( { "Dead event: " .. EventPrefix } )
		if EventPrefix == self.SpawnTemplatePrefix or ( self.SpawnAliasPrefix and EventPrefix == self.SpawnAliasPrefix ) then
			self.AliveUnits = self.AliveUnits - 1
			self:T( "Alive Units: " .. self.AliveUnits )
		end
	end
end
```
Dont know what is causing it but probably needs to be looked at

**Comment by gunterlund** [comment]
Creates this error
01159.920 INFO    SCRIPTING: Error in SCHEDULER function:[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8467: attempt to call method 'getPlayer' (a nil value)
01159.920 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:4791: in function 'getPlayer'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8467: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8457>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:5077: in function 'onEvent'
	[string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>
01159.920 INFO    SCRIPTING:   5075(    13)/E:               EVENT00000.onEvent({[1]="Calling EventFunction for Class ",[2]="SET_GROUP#000001320",[3]=2,})
01159.920 INFO    SCRIPTING: Error in SCHEDULER function:[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8467: attempt to call method 'getPlayer' (a nil value)
01159.920 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:4791: in function 'getPlayer'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8467: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8457>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:5077: in function 'onEvent'

**Comment by gunterlund** [comment]
01159.920 INFO    SCRIPTING: Error in SCHEDULER function:[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8467: attempt to call method 'getPlayer' (a nil value)
01159.920 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:4791: in function 'getPlayer'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8467: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8457>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:5077: in function 'onEvent'
	[string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>

**Comment by gunterlund** [comment]
creates this error
00283.033 INFO    SCRIPTING: Error in SCHEDULER function:[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8467: attempt to call method 'getPlayer' (a nil value)
00283.033 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:4791: in function 'getPlayer'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8467: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:8457>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00005494"]:5077: in function 'onEvent'
	[string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>

**Comment by Grey-Echo** [comment]
Edited for clarity. Please use "\`\`\` lua" before your code and "\`\`\`" after, and "\`\`\`" before and after your log

**Comment by Grey-Echo** [comment]
To be clear, the code in the issue is Moose's code, in Functional.Spawn, line 1497.
Note that it is maked obsolete.

**Comment by gunterlund** [comment]
yes that is correct in the MOOSE code

**Comment by FlightControl-Master** [comment]
@gunterlund i've been testing destroy events S_EVENT_DEAD on many SPAWN demonstration missions, but just cannot reproduce this error. Can you provide a bit more details on the log? a few lines above the error and a few lines under the error please.

**Comment by FlightControl-Master** [comment]
May I ask you, what GROUP name is involved where you get the error, i am missing important information to resolve this. You should see a line like this above the error:

```
07280.827 INFO    SCRIPTING:    690(    13)/E:               EVENT00000.onEvent(S_EVENT_DEAD)
07280.827 INFO    SCRIPTING:    803(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_DEAD",[2]={["IniUnit"]={["ClassName"]="UNIT",["UnitName"]="Spawn Vehicle Scheduled CleanUp#001-01",},["IniCoalition"]=2,["initiator"]={["id_"]=16778752,},["id"]=8,["IniTypeName"]="M1097 Avenger",["IniObjectCategory"]=1,["IniUnitName"]="Spawn Vehicle Scheduled CleanUp#001-01",["IniCategory"]=2,["IniGroupName"]="Spawn Vehicle Scheduled CleanUp#001",["time"]=43335.727,["IniDCSGroup"]={["id_"]=1000002,},["IniGroup"]={["GroupName"]="Spawn Vehicle Scheduled CleanUp#001",["ClassName"]="GROUP",},["IniDCSUnitName"]="Spawn Vehicle Scheduled CleanUp#001-01",["IniDCSUnit"]=,["IniDCSGroupName"]="Spawn Vehicle Scheduled CleanUp#001",},[3]="Spawn Vehicle Scheduled CleanUp#001-01",[5]=-1,})
07280.827 INFO    SCRIPTING:    968(    13)/E:               EVENT00000.onEvent({[1]="Calling EventFunction for Class ",[2]="SPAWN#000000045",[3]=5,})
07280.827 INFO    SCRIPTING:   1498(    -1)/F:               SPAWN00045.function(Spawn Helicopter Scheduled CleanUp)

07280.827 INFO    SCRIPTING:   1504(    -1)/T:               SPAWN00045.{[1]="Dead event: Spawn Vehicle Scheduled CleanUp",}
07280.827 INFO    SCRIPTING:    968(    13)/E:               EVENT00000.onEvent({[1]="Calling EventFunction for Class ",[2]="SPAWN#000000048",[3]=5,})
07280.827 INFO    SCRIPTING:   1498(    -1)/F:               SPAWN00048.function(Spawn Vehicle Scheduled CleanUp)
07280.827 INFO    SCRIPTING:   1504(    -1)/T:               SPAWN00048.{[1]="Dead event: Spawn Vehicle Scheduled CleanUp",}
07280.827 INFO    SCRIPTING:   1507(    -1)/T:               SPAWN00048.Alive Units: 2
```

**Comment by gunterlund** [comment]
I included a log in mission development but I'll create another

**Comment by FlightControl-Master** [comment]
On slack... Try to put it here if you can.

**Comment by gunterlund** [comment]
https://flightcontrol.slack.com/files/gunterlund/F4R3VH8CT/dcs.log

**Comment by gunterlund** [comment]
ok did more research and found where this  issue arises. In my mission I am setting up a helo cas mission with the following code;

`local CASEngagementhelo = ZONE:New( "Engagement Zone" )
  local HeloGroup1 = GROUP:FindByName( "Georgian Air Force Attk 1" )
  local PatrolZone = ZONE:New( "Patrol Zone" )
  local AICasZonehelo = AI_CAS_ZONE:New( PatrolZone, 200, 500, 150, 200, CASEngagementhelo )` 

I am executing the code by activating a helo and starting the mission with this.
`MenuFAC_CAShelo1 = MENU_GROUP_COMMAND:New( TwoThreeFACSection, "Call Helo from BASE", MenuFAC1, 
  function ()
    local TemplateHelo1 = HeloGroup1:GetTemplate()
    HeloGroup1:SetTemplateControlled( TemplateHelo1, true )
    HeloGroup1:Respawn( TemplateHelo1 )
    AICasZonehelo:SetControllable( HeloGroup1 )
    AICasZonehelo:__Start( 1 )
    MESSAGE:New("Air Assets on the way to Rendevous Point X-Ray",10,"Incoming Comms from Attack 1"):ToAll()
   end
)`
when I do this I get this error
`00147.303 WARNING LOG: 2 duplicate message(s) skipped.
00147.303 INFO    SCRIPTING:  16921(   193)/E:               GROUP01148.GetTemplate(Georgian Air Force Attk 1)
00147.303 INFO    SCRIPTING:  16897(   195)/E:               GROUP01148.Respawn(1)
00147.303 INFO    SCRIPTING:  16900(   195)/E:               GROUP01148.Respawn(200)
00147.303 INFO    SCRIPTING:  16908(   195)/E:               GROUP01148.Respawn({[1]=1,[2]={["alt"]=528.62042236328,["hardpoint_racks"]=true,["alt_type"]="BARO",["livery_id"]="standard",["skill"]="High",["ropeLength"]=15,["speed"]=41.666666666667,["type"]="Mi-24V",["unitId"]=115,["psi"]=1.5122042505981,["y"]=845509.375,["x"]=-292136.78125,["name"]="200",["payload"]={["pylons"]={[6]={["CLSID"]="{B919B0F4-7C25-455E-9A02-CEA51DB895E3}",},[2]={["CLSID"]="{6A4B9E69-64FE-439a-9163-3A87FB6A4D81}",},[3]={["CLSID"]="{6A4B9E69-64FE-439a-9163-3A87FB6A4D81}",},[1]={["CLSID"]="{B919B0F4-7C25-455E-9A02-CEA51DB895E3}",},[4]={["CLSID"]="{6A4B9E69-64FE-439a-9163-3A87FB6A4D81}",},[5]={["CLSID"]="{6A4B9E69-64FE-439a-9163-3A87FB6A4D81}",},},["fuel"]="1704",["flare"]=192,["chaff"]=0,["gun"]=100,},["onboard_num"]="53",["callsign"]={[1]=3,[2]=1,["name"]="Uzi11",[3]=1,},["heading"]=359.95999724596,},[3]=,})
00147.303 INFO    SCRIPTING:   4791(    13)/E:               EVENT00000.onEvent(S_EVENT_CRASH)
00147.304 INFO    SCRIPTING:   4904(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_CRASH",[2]={["IniUnit"]={["ClassName"]="UNIT",["UnitName"]="200",},["IniCoalition"]=2,["initiator"]={["id_"]=16813568,},["id"]=5,["IniTypeName"]="Mi-24V",["IniObjectCategory"]=1,["IniUnitName"]="200",["IniCategory"]=1,["IniGroupName"]="Georgian Air Force Attk 1",["time"]=59.295,["IniDCSGroup"]={["id_"]=22,},["IniGroup"]={["GroupName"]="Georgian Air Force Attk 1",["ClassName"]="GROUP",},["IniDCSUnitName"]="200",["IniDCSUnit"]=,["IniDCSGroupName"]="Georgian Air Force Attk 1",},[3]="200",[5]=-1,})
00147.304 INFO    SCRIPTING:   5069(    13)/E:               EVENT00000.onEvent({[1]="Calling EventFunction for Class ",[2]="SPAWN#000001305",[3]=5,})
00147.304 INFO    SCRIPTING: Error in SCHEDULER function:[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00004B40"]:22450: attempt to concatenate local 'EventPrefix' (a nil value)
00147.304 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00004B40"]:4785: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00004B40"]:4781>
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00004B40"]:22450: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00004B40"]:22443>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00004B40"]:5071: in function 'onEvent'
	[string "Scripts/World/EventHandlers.lua"]:13: in function 'onEvent'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00004B40"]:3364: in function 'CreateEventCrash'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00004B40"]:16306: in function 'Destroy'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00004B40"]:16912: in function 'Respawn'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00001C08"]:195: in function 'CommandMenuFunction'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00004B40"]:5337: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00004B40"]:5336>
00147.304 INFO    SCRIPTING:   5069(    13)/E:               EVENT00000.onEvent({[1]="Calling EventFunction for Class ",[2]="AI_CAS_ZONE#000001302",[3]=5,})
00147.304 INFO    SCRIPTING:   5069(    13)/E:               EVENT00000.onEvent({[1]="Calling EventFunction for Class ",[2]="AI_PATROL_ZONE#000001324",[3]=5,})
00147.304 INFO    SCRIPTING:   5069(    13)/E:               EVENT00000.onEvent({[1]="Calling EventFunction for Class ",[2]="AI_CAS_ZONE#000001247",[3]=5,})
00147.304 INFO    SCRIPTING:   5069(    13)/E:               EVENT00000.onEvent({[1]="Calling EventFunction for Class ",[2]="SET_GROUP#000001311",[3]=2,})
00147.304 INFO    SCRIPTING:   8165(  8427)/E:           SET_GROUP01311.Remove({[1]="Georgian Air Force Attk 1",})
00147.304 INFO    SCRIPTING:   5069(    13)/E:               EVENT00000.onEvent({[1]="Calling EventFunction for Class ",[2]="SET_GROUP#000001318",[3]=2,})
00147.304 INFO    SCRIPTING:   8165(  8427)/E:           SET_GROUP01318.Remove({[1]="Georgian Air Force Attk 1",})
00147.304 INFO    SCRIPTING:   5069(    13)/E:               EVENT00000.onEvent({[1]="Calling EventFunction for Class ",[2]="SET_GROUP#000001309",[3]=2,})
00147.304 INFO    SCRIPTING:   8165(  8427)/E:           SET_GROUP01309.Remove({[1]="Georgian Air Force Attk 1",})
00147.304 INFO    SCRIPTING:   5069(    13)/E:               EVENT00000.onEvent({[1]="Calling EventFunction for Class ",[2]="SET_GROUP#000001316",[3]=2,})
00147.304 INFO    SCRIPTING:   8165(  8427)/E:           SET_GROUP01316.Remove({[1]="Georgian Air Force Attk 1",})
00147.304 INFO    SCRIPTING:   5069(    13)/E:               EVENT00000.onEvent({[1]="Calling EventFunction for Class ",[2]="DATABASE#000000003",[3]=1,})
00147.304 INFO    SCRIPTING:   7572(  7469)/E:            DATABASE00003._RegisterTemplate({[1]="Group",[2]="Georgian Air Force Attk 1",[3]="Coalition",[4]=2,[5]="Category",[6]=1,[7]="Country",[8]=16,[9]="Units",[10]="200",})
00147.305 INFO    SCRIPTING:   7418(  7479)/E:            DATABASE00003.AddGroup({[1]="Add GROUP:",[2]="DictKey_GroupName_199",})
00147.311 INFO    SCRIPTING:   4791(    13)/E:               EVENT00000.onEvent(S_EVENT_BIRTH)
00147.312 INFO    SCRIPTING:   4904(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_BIRTH",[2]={["IniUnit"]={["ClassName"]="UNIT",["UnitName"]="200",},["place"]={["id_"]=16777728,},["IniUnitName"]="200",["time"]=0,["IniGroup"]={["GroupName"]="Georgian Air Force Attk 1",["ClassName"]="GROUP",},["IniDCSGroupName"]="Georgian Air Force Attk 1",["IniCoalition"]=2,["id"]=15,["IniObjectCategory"]=1,["IniTypeName"]="Mi-24V",["subPlace"]=11,["IniCategory"]=1,["IniGroupName"]="Georgian Air Force Attk 1",["initiator"]={["id_"]=16855808,},["IniDCSUnitName"]="200",["IniDCSUnit"]=,["IniDCSGroup"]={["id_"]=22,},},[3]="200",[5]=1,})`

It looks like when the helo is spawning something is not getting passed to the CAS Start parameter?

**Comment by gunterlund** [comment]
the mission executes ok but something is erroring out.

**Comment by Delta-99** [comment]
A couple of issues I see with your code. You are using LOCAL on objects that you shouldn't be specifically the AICasZonehelo. Not 100% sure about the others but for those as well especially the HeloGroup1 I would not do that. This is definitely why you are getting "an" error. It might not be the entire issue.

Before I say there is something wrong with your menu function I need to know if you have previously spawned HeloGroup1. You may be but not showing the code. If not then I'm not sure using Respawn is going to work. In which case you can forget all that and just spawn it in your menu code. I do something very similar without any issues.

**Comment by gunterlund** [comment]
No Helogroup1 is not a spawned object. Its permanently on the map but
starts as inactive. The code there is used to activate it so it doesnt take
off on mission startup.

**Comment by Delta-99** [comment]
Then you should be able to get rid of a few lines in the MENU function and just use Helogroup1:Spawn(). But first make your other variables NOT local and try that. If it works then Respawn() is good too.

**Comment by gunterlund** [comment]
I know there was alot of discussion about local. I have local throughout my
code. Should I take it all out.

**Comment by Delta-99** [comment]
I wouldn't say all. But definitely on AI_CAS_ZONE type objects. Anything that is going to or potentially be used by a scheduler I believe.

**Comment by gunterlund** [comment]
HI delta
Got rid of the local and still get error

**Comment by Delta-99** [comment]
That sucks. I'm in my own debugging hell with some Event code and getting nowhere fast. Will probably have to abandon it as I don't see anything functioning straight forward with events on groups. I can't get anything consistent to work at all.

**Comment by FlightControl-Master** [comment]
@gunterlund i can't read your debugging output on my mobile. Can you please restructure it following the asvises from @Grey-Echo? I'll try to do this myself now on my mobile...

**Comment by FlightControl-Master** [comment]
@gunterlund...
I think i know what the problem is. 

```local TemplateHelo1 = HeloGroup1:GetTemplate()
HeloGroup1:SetTemplateControlled( TemplateHelo1, true )
HeloGroup1:Respawn( TemplateHelo1 )
```

You're doin a Respawn on the GROUP object... Didn't know you were doin that... Now i know.

GROUP:Respawn **triggers** a DEAD event to ensure that any other object knows that the group object you are respawning is destroyed, before the Respawn happens.
So, due to the change i did for @EasyEB (keep unit names), i had to rework the way spawn processes the dead event... It receives the unit name, and in the old version it would parse that name to see which object was dead (name of unit + group index of unit). Now, because of the change i did, i cannot parse anymore the unit name because the unit names may not correspond to the group name. So i look for the group name instead... That worked great.... But not when you Respawn a GROUP object that was spawned by SPAWN... SPAWN will get the DEAD event triggered, but the group in the sim does not exist anymore and this the group of the unit received will be nil... That is the error you are getting...

When i get back home, i will need to look into this issue.

But just put of curiosity, why you use a Respawn on the GROUP object and not on the SPAWN object? Or just a Spawn(). I don't think you need to Respawn...

**Comment by gunterlund** [comment]
Sven that is exactly what I was thinking. I have two helo's that go through this and I noticed the respawn on this as well. That is where the message hits.  This is consistent and reproducable. Everytime you make those two helo's controllable through the respawn process you get the error. Im also knowing that the detection system and what ever your using in the CAS program to detect units is erroring and it looks like its around a death event.
`01447.576 INFO    SCRIPTING:   4791(    13)/E:               EVENT00000.onEvent(S_EVENT_SHOT)
01447.576 INFO    SCRIPTING:   5101(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_SHOT",[2]={["id"]=1,["weapon"]={["id_"]=33629440,},["time"]=51247.442,["initiator"]={["id_"]=16837632,},},})
01447.638 INFO    SCRIPTING:   4791(    13)/E:               EVENT00000.onEvent(S_EVENT_DEAD)
01447.639 INFO    SCRIPTING:   4904(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_DEAD",[2]={["IniUnit"]={["ClassName"]="UNIT",["UnitName"]="692",},["IniCoalition"]=2,["initiator"]={["id_"]=16825088,},["id"]=8,["IniTypeName"]="BMP-2",["IniObjectCategory"]=1,["IniUnitName"]="692",["IniCategory"]=2,["IniGroupName"]="Co 3 1st Plt 23rd Lt Inf Bat",["time"]=51247.505,["IniDCSGroup"]={["id_"]=56,},["IniGroup"]={["GroupName"]="Co 3 1st Plt 23rd Lt Inf Bat",["ClassName"]="GROUP",},["IniDCSUnitName"]="692",["IniDCSUnit"]=,["IniDCSGroupName"]="Co 3 1st Plt 23rd Lt Inf Bat",},[3]="692",[5]=-1,})
01447.639 INFO    SCRIPTING:   5083(    13)/E:               EVENT00000.onEvent({[1]="Calling OnEventDead for Class ",[2]="AI_CAS_ZONE#000001301",[3]=5,})
01447.639 INFO    SCRIPTING:   5069(    13)/E:               EVENT00000.onEvent({[1]="Calling EventFunction for Class ",[2]="SPAWN#000001309",[3]=5,})
01447.639 INFO    SCRIPTING: Error in SCHEDULER function:[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00007B03"]:22450: attempt to concatenate local 'EventPrefix' (a nil value)
01447.639 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00007B03"]:4785: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00007B03"]:4781>
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00007B03"]:22450: in function <[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00007B03"]:22443>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00007B03"]:5071: in function 'onEvent'
	[string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>`

**Comment by gunterlund** [comment]
To answer your Spawn question above the code below was the code you gave me along time ago to make a unit controllable again. I wanted to have a helo on the map sitting on a farp but not moving on game startup so the only way to do this is make it uncontrollable. This code (HeloGroup1 is the name of the helo object)
`TemplateHelo1 = HeloGroup1:GetTemplate()
    HeloGroup1:SetTemplateControlled( TemplateHelo1, true )
    HeloGroup1:Respawn( TemplateHelo1 )`
made it controllable but for some reason you added a respawn in there. It works great as the helo's act as I was hoping but it does create the error in the log.

**Comment by Delta-99** [comment]
In the meantime as I suggested above try using Spawn(). Doesn't look like you need to use Respawn() in this instance. I do that and have no issues. In fact I even use Spawn() in places where a Respawn() would probably be more appropriate. But what it does is kill any currently active unit and then just spawns them again. I don't know if that causes other issues but I haven't seen anything arise from using this method.

**Comment by gunterlund** [comment]
changed code to this
`TemplateHelo1 = HeloGroup1:GetTemplate()
    HeloGroup1:SetTemplateControlled( TemplateHelo1, true )
    HeloGroup1:Spawn( TemplateHelo1 )`
This does not work.

**Comment by Delta-99** [comment]
Ok, I don't know what all that GetTemplate stuff is. I use the more simplified spawning as per the example files. I haven't had the need to use this template stuff. HOWEVER, if I understand what all that is, it means you have a GROUP object already and there is no need to use the GetTemplate and SetTemplateControlled. Unless of course you really are red-awning these based on a GROUP that is already created. I think you can get rid of all those lines and have one simple line `HeloGroup1:Spawn()` and that is it.

You may have that template stuff hanging around from trying to get this working in some other situation or other setup. But again, based on your requirements that this is a really a spawn and not a respawn not sure that is needed.

**Comment by FlightControl-Master** [comment]
You don't need that template stuff at all.

**Comment by gunterlund** [comment]
So what is the substitution for the Template setup. I want the unit on the map and not spawning in.

**Comment by Delta-99** [comment]
@gunterlund, what exactly are your requirements? Give me a couple of lines on what exactly you are trying to accomplish. Sorry if it is above but I just want to be clear on it.

**Comment by Delta-99** [comment]
Yeah, look at SPA-130. Then go from there. I guess in your MENU command you would just make it controlled and then do these lines that you have now:

`AICasZonehelo:SetControllable( HeloGroup1 )
    AICasZonehelo:__Start( 1 )
    MESSAGE:New("Air Assets on the way to Rendevous Point X-Ray",10,"Incoming Comms from Attack 1"):ToAll()`

Something like that anyway

**Comment by FlightControl-Master** [comment]
@gunterlund i don't think this is urgent, is it? I mean, we are not going to block a release because of this.

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
