### ISSUE TITLE
MOOSE-Template.miz saved with groups/units defined

### ISSUE THREAD

**Issue by glyphoglossus** [FlightControl-Master/MOOSE#37]
The mission template:

   https://github.com/FlightControl-Master/MOOSE/blob/master/Loaders/MOOSE-Template.miz

is prepopulated with units. Should that be the case? Should it not be empty except for the triggers that load the MOOSE library?

**Comment by FlightControl-Master** [comment]
Fixed in 

https://github.com/FlightControl-Master/MOOSE/releases/tag/v0.2.3-alpha
