### ISSUE TITLE
Improve MDES to better automate the set up of the dev env

### ISSUE THREAD

**Issue by Grey-Echo** [FlightControl-Master/MOOSE#372]
There would be 2 versions of MDES:
* For the mission designer : LDT, Java if necessary, download the latest Moose release and release test missions, hard link for test missions
* For the Tester/Developer : LDT, JAVA, 7-Zip, Lua5.1, Hardlinks, glogg...

Everything non-critical needs to be an option !

**Comment by Grey-Echo** [comment]
After a bit of discussion we came to the realisation that users who are advanced enough to install the software they need. So the solution looks like that:
* MDESMissionDesigner will
  * Install JAVA 
  * Install LDT
  * Download the latest Moose release
  * Explain what is glogg and give a link

* MDESAdvancedUser will
  * Verify that LDT and 7-zip and GitHub are installed
  * Add 7-Zip to PATH
  * Create a hardlink in scripts and another one for test mission if the user wants
  * Explain what are hardlinks and give a link to http://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html
  * Explain what is glogg and give a link to http://glogg.bonnefon.org/

**Comment by FlightControl-Master** [comment]
Okay. Makes sense.

**Comment by Grey-Echo** [comment]
Not relevant anymore, MDES is not used to setup a dev env anymore
