### ISSUE TITLE
SPAWN: InitRandomizeTemplate - Keep Group Template Names

### ISSUE THREAD

**Issue by BiggieSmallsVR** [FlightControl-Master/MOOSE#382]
For `SPAWN:InitRandomizeTemplate()`, it would be nice to have the new group spawned to have the name of the template group rather than the spawn group.

Ie. in my randomized template i have `Tank Group` and `Recon Group` that spawn off a single group called `Spawn Group`. Would be good to have the option to make the name of the spawned groups be `Tank Group #001` and `Recon Group #001`, and so on, depending on which of the template groups was spawned.

Right now it seems that regardless of which template was spawned it will be called  `Spawn Group #001`.

**Comment by Grey-Echo** [comment]
Edited to make it easier to read

**Comment by Delta-99** [comment]
I like the idea but lets make this an option (as a parameter or something)

**Comment by FlightControl-Master** [comment]
Yep! Thanks guys!

**Comment by baluballa** [comment]
Overdue.
