### ISSUE TITLE
http://flightcontrol-master.github.io/MOOSE/Documentation/Movement.html 404

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#390]
http://flightcontrol-master.github.io/MOOSE/Documentation/Movement.html

This page from http://flightcontrol-master.github.io/MOOSE/Documentation/ does not exist. Should it?

**Comment by Grey-Echo** [comment]
I can reproduce this problem.

**Comment by thebgpikester** [comment]
i'm not sure if the intention regarding movement is via using tasks, so it may be just a case of deleting the link.

**Comment by Grey-Echo** [comment]
You can't "just delete the link", this documentation is automatically generated from the comments in the code. I think some of the comment in the code are badly written and that confuses the html doc generator.

**Comment by FlightControl-Master** [comment]
Movement is very old... I am not sure people find it useful... To my knowledge nobody used it yet except me...

**Comment by Grey-Echo** [comment]
This is fixed by my last pull request.

**Comment by FlightControl-Master** [comment]
Fixed. Closed. No feedback.
