### ISSUE TITLE
SCORING: Events to XLS could be appended per mission

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#392]
Current method of scoring it to just create the XLS spreadsheet as soon as the mission starts with a timestamp/mission name as filename and begin appending to it. Scoring, is a fairly MP oriented function implemented by server admins. Appending to an existing XLS with the same mission could be easier to use and require less administration as restarting the mission will create an additional spreadsheet with a unique name.

Would require
A decision on if this should be an option and if so if default.
Checks to see if the mission name already exists and if a file can be opened and locked for editing
If so to append, if not, create new
Changing the method of naming the file to a static name (dropping the timestamp)

**Comment by baluballa** [comment]
Think this is in place.
