### ISSUE TITLE
Cargo demo missions using assert dynamic

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#393]
I'e double posted an issue (number2) in the misison repository, but felt this one was watched more.
None of the cargo test missions work, there's a bit of dynamic loading in the moose of them, also if you replace the moose with mooose static, some at least are still broken, like transferring, the guys go in, then they get out, then they walk to the next place and then get in.
38898.623 INFO    SCRIPTING: *** MOOSE DYNAMIC INCLUDE START ***
38898.623 INFO    SCRIPTING: Moose Generation Timestamp: 20170401_1103
38898.623 ERROR   DCS: Mission script error: : [string "e:\temp\DCS\/~mis000011DE"]:11: can't open 'Scripts/Moose/Utilities/Routines.lua'
stack traceback:
    [C]: ?
    [C]: in function 'assert'
    [string "e:\temp\DCS\/~mis000011DE"]:11: in function 'Include'
    [string "e:\temp\DCS\/~mis000011DE"]:24: in main chunk

**Comment by FlightControl-Master** [comment]
Which branch are you loading these from?

**Comment by thebgpikester** [comment]
Not this one, the one at https://github.com/FlightControl-Master/MOOSE_MISSIONS, the new project after it was split.

**Comment by thebgpikester** [comment]
I just double checked, by downloading a cargo transfering directly from there. the dynamic is still in the logs.

**Comment by FlightControl-Master** [comment]
Check here:

https://github.com/FlightControl-Master/MOOSE_MISSIONS/tree/master-release

Note the branch **master-release**

**Comment by Grey-Echo** [comment]
To be clear, on MOOSE_MIISSION, master contains the .miz file setup for DYNAMIC LOADING, and master-release the .miz files setup for STATIC LOADING. 
Note that new missions (added after 2.0 release) shouldn't even appear in master-release.

**Comment by FlightControl-Master** [comment]
Closed
