### ISSUE TITLE
DOCS: Document chapter how to include demo missions to ldt

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#395]
To facilitate far searching and explain how to search using ctrl-H

**Comment by Delta-99** [comment]
FC, can you also document anything else really useful in LDT? Any other shortcut keys etc. I'm constantly figuring out what the shortcut keys are for function parameter completion and such. There are I'm sure lots of useful shortcut keys.

**Comment by FlightControl-Master** [comment]
Sure. But not today. Will take note. However ldt has these documented. But some useful ok...

**Comment by Delta-99** [comment]
Yes, definitely not today. This is just whenever!

**Comment by FlightControl-Master** [comment]
Published.
