### ISSUE TITLE
Dcs project is missing from the generated documentation....

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#396]
Needs to be fixed asap!

**Comment by FlightControl-Master** [comment]
@Grey-Echo can you help me?

**Comment by Grey-Echo** [comment]
Yep ! This is fixed by my last pull request. 
https://github.com/FlightControl-Master/MOOSE/pull/401

**Comment by FlightControl-Master** [comment]
Very good ! Thanks!

**Comment by Delta-99** [comment]
Should this be closed? I see this popping up in the documentation now so looks good to me.
