### ISSUE TITLE
EVENT: MISSION_END is not handled

### ISSUE THREAD

**Issue by dwpenney** [FlightControl-Master/MOOSE#398]
This needs to be added so that the MISSION_END events can be handled (useful for scenarios that want to generate a scoring/action summary at the end of a mission).

**Comment by FlightControl-Master** [comment]
The requested enhancement seems easy, but it is not. A lot of testing is to be done, not on this event, but on the impact of all other events at the event dispatcher....
Right now, an event will only be fired if there is an initiator.
I can off course hardcode only to dispatch the END_MISSION event without initiator but that is not my preference.

**Comment by FlightControl-Master** [comment]
How critical is this to have this implemented?

**Comment by FlightControl-Master** [comment]
Fixed and pushed to master, ready for beta testing @dwpenney

**Comment by dwpenney** [comment]
Thanks! Sorry that I did not see the question posted above concerning the criticality. I will check my mail filters.

**Comment by FlightControl-Master** [comment]
no worries.

**Comment by dwpenney** [comment]
Tested and fix confirmed.
