### ISSUE TITLE
Add Event Handling to Zones

### ISSUE THREAD

**Issue by dwpenney** [FlightControl-Master/MOOSE#399]
If possible, this would eliminate having to have scanning functions (periodic scheduled functions) to scan for events happening in trigger zones - by having the zones, themselves, handle the events.

**Comment by FlightControl-Master** [comment]
Duplicate with #345...

**Comment by FlightControl-Master** [comment]
Will close this.

**Comment by FlightControl-Master** [comment]
Closed @dwpenney
