### ISSUE TITLE
Chech correct workin of landing events....

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#400]
For units, groups, generic classes OnEventLand... Does not seem to work. Pls confirm.

**Comment by FlightControl-Master** [comment]
Who can double check this?

**Comment by Delta-99** [comment]
In my case it is on HandleEvent(Event.Land) on a group object

**Comment by FlightControl-Master** [comment]
Ok! But other group events work?

**Comment by FlightControl-Master** [comment]
Not a moose bug but a dcs bug. When a helicopter executes a land task and lands at the landing spot, it will not generated a land event...

**Comment by Delta-99** [comment]
Mine is on planes not helicopters. I see the EVENT in the logs but it doesn't make it to my Moose event function. Whereas Birth and Takeoff DO.

I can also confirm that about 1 out of 10 runs of my mission when I am testing that Birth and Takeoff do not work either from the start of my mission. Don't know if this is a DCS bug or Moose. But when they do work, Land has never worked that I have seen.

**Comment by FlightControl-Master** [comment]
Can you open a new issue, don't want to mix the two. Thanks

**Comment by Delta-99** [comment]
Yeah, no problem. If I can put together a simple demo mission with the issue I will enter a new one.
