### ISSUE TITLE
TASKING: Mission Menu for Tasking is not rebuild after mission success

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#403]
When having more than on mission, you would like to select another mission when mission reach a certain stage, especial after a success. Mission menu is not rebuild.

**Comment by FlightControl-Master** [comment]
Ok! I see you are using the tasking! I'll look into this. Thanks! What is you set the mission to the initial status again?

**Comment by FlightControl-Master** [comment]
Going to work on this one tomorrow ... seems to be a tricky one.

**Comment by FlightControl-Master** [comment]
Fixed!
