### ISSUE TITLE
When having more than one mission, other mission that selected comes up with menu option "abort"

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#404]
A player should not have an option to abort a Mission he is not a part of in tasking.

**Comment by FlightControl-Master** [comment]
Probably due to a hanging menu. Or, because that player is also part of the set assigned to the task?

**Comment by baluballa** [comment]
You are right, seems to be a hanging menu

**Comment by FlightControl-Master** [comment]
Don't close... Any idea why the menu hang?

**Comment by baluballa** [comment]
I have no idea, but in all missions the plane was a part of the SET GROUP that the mission could be assigned too.

BTW: sorry for late reply

**Comment by Grey-Echo** [comment]
I hate to do this, but there is absolutely no way in the world we could reproduce this one, with the information we have. So I'm closing it.
@baluballa , if you ever have this problem again, please reopen this issue or create a new one, and try to follow the guidelines for reporting a bug : https://github.com/FlightControl-Master/MOOSE/blob/master/docs/Beta_Test_Guide.md#61-how-to-report-a-bug-.

**Comment by FlightControl-Master** [comment]
Please don't. I know what this is about. I need to check this today.

**Comment by FlightControl-Master** [comment]
But I agree it takes me about a whole morning to simulate and identify this issue and then try to fix it...

**Comment by FlightControl-Master** [comment]
This is fixed!
