### ISSUE TITLE
SCORING: Distribute destroy score over player contributors.

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#406]
When two players have HIT_SCORE both gets full credit in HIT_DESTROY score. Guess due to cache system. Most fair would be to share destroy score, I guess.

**Comment by FlightControl-Master** [comment]
Ok. I understand. Destroy score / players hit count to be assigned to each player individually who contributed in the destroy. 

This is a good observation. Forgot about that. Will implement. This will make SCORING even better than it already is.

**Comment by FlightControl-Master** [comment]
Implemented
