### ISSUE TITLE
CONTROLLABLE: Add more vectors between 2 routes generated

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#407]
@FlightControl-Master, I am posting this here so that it doesn't get lost. I wonder if something like this [http://wiki.hoggit.us/view/DCS_func_profile](http://wiki.hoggit.us/view/DCS_func_profile) can be used to generated intermediate points between two waypoints when you are creating routes in various functions.

It isn't clear what this returns but my guess is it returns points along the route with the height of the ground at that point. I suppose one can do this without this function though but anyway something to think about.

It might be useful when generating waypoint routes for units especially in mountainous terrain. We will always be stuck with crappy DCS AI behaviour flying through there but this might help mitigate it a little bit!!

**Comment by FlightControl-Master** [comment]
Okay!!!!! Cool!

**Comment by FlightControl-Master** [comment]
Remember our discussion to also identify routes through valleys??? I'll consider this one here too.

**Comment by Delta-99** [comment]
Sounds good FC (make it optional of course ;).

**Comment by baluballa** [comment]
Old.
