### ISSUE TITLE
SPAWN: Initial Formation

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#408]
Would like to have the ability for units to spawn in with the same formation set in the mission editor before mission start instead of spawning in a pile then moving into a formation.

**Comment by FlightControl-Master** [comment]
thanks!

**Comment by FlightControl-Master** [comment]
@gunterlund would it be a good solution to copy over the initial positions of each unit as defined in the template? Positioning to initial formation is going to be difficult... But i can copy over the initial positions more easily.

**Comment by FlightControl-Master** [comment]
You mean this is not an issue?

**Comment by gunterlund** [comment]
Don't think so as it spawns from initial formation

**Comment by FlightControl-Master** [comment]
Still confused. It is the usage of the language i guess.

**Comment by gunterlund** [comment]
Sorry the units are properly spawning in in the correct formation. No fix needed.
