### ISSUE TITLE
SET_UNIT:ForEachUnitCompletelyInZone not working

### ISSUE THREAD

**Issue by BiggieSmallsVR** [FlightControl-Master/MOOSE#412]
SET_UNIT:ForEachUnitCompletelyInZone is not being recognized in MOOSE 2.0.

Code run is as follows:
```lua
AllGroundUnits:ForEachUnitCompletelyInZone(Test_Zone, 
  function (unit_obj1)
    Ground_Unit_Message = MESSAGE:New(unit_obj1:GetName(), 10):ToAll() 
  end
)
```

error in snake tail is as follows:
```
05405.251 ERROR   DCS: Mission script error: : [string "C:\Users\Graeme\AppData\Local\Temp\DCS\/~mis000028DB"]:9370: attempt to call method 'IsCompletelyInZone' (a nil value)
```

**Comment by FlightControl-Master** [comment]
Ok. Need to check this. Something is wrong 👎

**Comment by CraigOwen** [comment]
To me this function should not be published by SET_UNIT, because a unit can hardly be partial in a zone.

**Comment by Delta-99** [comment]
> To me this function should not be published by SET_UNIT, because a unit can hardly be partial in a zone.

Maybe just a bad name for it. Maybe should be called ForEachUnitinZone()

**Comment by CraigOwen** [comment]
'This is right an after all maybe event the bug.
the method is named ForEachUnitCompletelyInZone and includes a call to IsCompletelyInZone on unit.
Unit lack of this method, but offers a IsInZone Method.

So renaming both the SET_UNIT method as well as the unit function call should do the trick.

`function SET_UNIT:ForEachUnitInZone( ZoneObject, IteratorFunction, ... )
  self:F2( arg )
  
  self:ForEach( IteratorFunction, arg, self.Set,
    --- @param Core.Zone#ZONE_BASE ZoneObject
    -- @param Wrapper.Unit#UNIT UnitObject
    function( ZoneObject, UnitObject )
      if UnitObject:IsInZone( ZoneObject ) then
        return true
      else
        return false
      end
    end, { ZoneObject } )

  return self
end`

**Comment by FlightControl-Master** [comment]
@BiggieSmallsVR this is fixed and can be tested. Fix is published to master. Closing this issue.

**Comment by FlightControl-Master** [comment]
Fix was published through commit https://github.com/FlightControl-Master/MOOSE/commit/545034034ebd4d0801335d6d9a62205f041c546a

**Comment by BiggieSmallsVR** [comment]
thanks FC, i'll test it out tonight.
