### ISSUE TITLE
ENHANCEMENT: AIB - make slot balancing for SPAWNs vs CLIENT

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#413]
I came up with an interesting concept that I think would be appreciated, almost the opposite of what AIB currently is.

**The idea is that, As a Client enters a Client slot for a role, the AI spawns an equivalent match.**

So for example, Blue team have 4 Mirage 2000's set to be monitored. Red team have 4 AI Mig29's marked with the existing filter() by naming convention. When client 1 joins Blue, Red SPAWN 1 Mig29. When a second joins, another Mig29 spawns. If a blue member leaves, the matching Mig29 gets an RTB order.

The purpose is that it easily builds a scalable PvE match, so if your squadron or group has one less player that night because he was at the pub, the AI scales to match what you have. It would make building missions a lot easier and adaptable.

**Comment by Delta-99** [comment]
Interesting concept. I like it. Need a new name to it as it sounds like a separate thing to AIB. As you say, its an opposite type of thing.

Maybe AI_SCALER or something along those lines. AI_RATIO?? Just throwing out some potential names.

This is common in other game environments where you scale the enemy force based on how many human players are in the game. I'd like to see it implemented where it isn't just 1 to 1 either. So you might have 4 enemy aircraft per human player or whatever ratio the mission designer decides.

**Comment by thebgpikester** [comment]
I think, like AIB, you can set which ones are available to be "matched". So programmatically, you can define limits on what spawns versus your client slot. I could see it being available for pure CAP the easiest, but there is no reason why it cannot be CAS vs CAS. Or...CAS vs CAP. So you jump in an A-10C and a Mig29 spawns. Just a matter of making sets. Perhaps....perhaps if you match prefixes? So "A-Client" (CAP) will spawn "A-AI" (CAP) but if you set up another pair "B-Client" (CAS) and "B-AI" (CAP)

**Comment by thebgpikester** [comment]
Here's what FC had to say about it:
GroupObject:HandleEvent( EVENTS.Birth )

 ```--- @param self
-- @param Core.Event#EVENTDATA EventData
function GroupObject:OnEventBirth( EventData )
  ... Logic ...
end

So I think it's achievable more easily in code and will give it a go.
In ..logic.. you can spawn anything you want

**Comment by d0o0m** [comment]
just a thought Pikey... if i have taken off as C1(Client1), your logic suggests O1(Opponent) will launch. I get this and I like it... However, lets say C2 joins and O2 immediately takes off.  C1 gets into a dogfight with O1&O2 while C2 exits.  Will O2 just deconflict immediately to RTB?  It could break immersion pretty bad.  I ask because I used to run into problems with GCICAP scripting and had really bizarre, apathetic if not suicidal behavior creep in on the AI when RTB commands were issued dynamically.

**Comment by FlightControl-Master** [comment]
@thebgpikester is this still a valid requirement?

**Comment by thebgpikester** [comment]
Would still be a great addition but it's not AIB, it's the opposite. For AIB AI takes client slots when the Clients arent occupied. with this there is more balancing and it's hard to deal with the way it balances. Although as per Doom's post above, there's a solution in AIB currently that AI not near a human only gets the RTB. I didn;t get a workaround yet to make this thing, events were not useable so its a hard shceduled check.

**Comment by Delta-99** [comment]
I commented above but I would 2nd this again as a great feature to add.
