### ISSUE TITLE
SPAWN:SpawnFromUnit will not spawn 'Late Activation' Units

### ISSUE THREAD

**Issue by dwpenney** [FlightControl-Master/MOOSE#414]
Due to a fix in Issue #97 (IsAlive() should not count late activation units) the SpawnFromUnit function will not spawn a 'Late Activation' units because it checks to see if the unit it is spawning from is alive.

Proposed solution: Add a function to the Units wrapper called IsLateActivation() that checks to see if the referenced unit is a Late Activation unit. How can we tell this? Because DCS:isActive() returns false AND the life of the unit is greater than (or equal to) 1.0 (Unit.getLife(Unit self) as defined in the ED DCS Lua Simulator Scripting Engine documentation (http://en.wiki.eagle.ru/wiki/Simulator_Scripting_Engine/DCS:_World/Part_2#Unit)). This proposed function would work the same as UNIT:IsAlive().

**Comment by dwpenney** [comment]
Forgot to add ... this means a change in the SPAWN:SpawnFromUnit() to check for this:

if HostUnit and (HostUnit:IsAlive() or HostUnit:IsLateActivation()) then...

**Comment by dwpenney** [comment]
I have added this code to the master-414-Late-Activation branch: https://github.com/FlightControl-Master/MOOSE/tree/master-414-Late-Activation

**Comment by FlightControl-Master** [comment]
@dwpenney Are you a beta tester, so, are you using github and dynamic loading?

**Comment by FlightControl-Master** [comment]
Fixed, ready to be tested, closed.

**Comment by dwpenney** [comment]
I will test this tonight

**Comment by dwpenney** [comment]
Tested and fix confirmed

**Comment by FlightControl-Master** [comment]
We need a "Tested" label
