### ISSUE TITLE
DETECTION: Separate Detection Units by Category

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#415]
Need to be able to filter the type of units being detected between air and Ground. This will allow for better control over what happens to detected units. For instance if I want to only shoot at detected ground units and not at detected Air units that may be in the same place. Should apply to Detection_Units and Detection_Area.

**Comment by FlightControl-Master** [comment]
@gunterlund workin on it.

**Comment by FlightControl-Master** [comment]
@gunterlund delivered, can be used now in master branch.

**Comment by gunterlund** [comment]
FC Looks like its working like a charm. Will continue to test but so far so good. If you have Tacview Ill send you a acmi to see how it works.

**Comment by FlightControl-Master** [comment]
Is the quality of the documentation good too?

**Comment by gunterlund** [comment]
let me review some more. One thing that is helpful is you did a wide variety of demo missions about this issue. Takes a ton of the guesswork out. Thanks much.

**Comment by FlightControl-Master** [comment]
Note that there is still an issue with structures detection for some reason. Not the detection itself, but understanding that a structure got detected....

**Comment by gunterlund** [comment]
got it Just tested it and the arty pounded some buildings I installed as structures, not static ones.
so far it is working brilliantly.
