### ISSUE TITLE
A2A_DISPATCHER: A2A Tasking and Dispatcher

### ISSUE THREAD

**Issue by Krinje** [FlightControl-Master/MOOSE#419]
My envisioning would be for a dispatcher that dynamically creates a few kinds of tasks for players. This is inspired by and would operate similar to the A2G Tasking Dispatcher. My assumption is that ground radar detection and AWACS detection would be the standard for detection here.

**CAP**: Based on a list of zones, the dispatch would offer patrol sectors (zones) to flights until an appropriate number of flights are tasked with patrolling a sector. That number could be scripted, or could be dynamic based on recently detected threats, or need for friendly (A2G tasks in zone?) protection in that area. A threat level could be given based on the enemy activity or type. Sector(s) information could be provided by the Briefing and/or a BRA or LAT/LONG to the center.

**Interception, GCI**: Based on detection with an optional zone(s) filter, the dispatcher would offer a task to intercept a specific target (or detection grouping) and give BRA ("Bearing 030 for 15 angels 10 Hot") calls at some interval to guide the intercepting fighter to the target. A "last known" version of BRA, when detection is lost is probably a good idea Threat levels seem fairly self explanatory. Some kind of priority system seems appropriate.

These two tasks I think would do a great deal to orient A2A in a mission and goal enhancing direction for both "PvE" and "PvP." I am especially fond of the idea Interception, I feel this could be significantly better than what is implemented in DCS.

**Comment by FlightControl-Master** [comment]
Thanks! The first priority is to get A2G tasking stable. Once it is stable, the sky is the limit to build other types of dispatchers and tasks...

**Comment by FlightControl-Master** [comment]
@Krinje I will include this in release 2.2!!!

**Comment by FlightControl-Master** [comment]
This will get a priority in release 2.2

**Comment by FlightControl-Master** [comment]
Implemented and released to master. Closing this @Krinje
