### ISSUE TITLE
SCO - SU25 counts as interceptor in kill message

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#421]
as comment says, if you kill one, shows player killed su25. Interceptor X points

**Comment by FlightControl-Master** [comment]
Ok. I need to check the properties of su25! Great find!

**Comment by FlightControl-Master** [comment]
Solved with commit e0829ce986b38c8eaaaa1724fa27301398de1d19. Closing this issue. Interceptor is the wrong word... Should have been Battleplane.
