### ISSUE TITLE
TSK - Scoring added even if you didn't kill the targets

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#423]
If you accept a task and the targets are destroyed by something else, you get credit.

**Comment by FlightControl-Master** [comment]
Ha!!!! Yes... This is an issue... Not an easy one though...

**Comment by FlightControl-Master** [comment]
This is also a design question. What it the Task is about letting AI kill targets, and you hold a position or defend...

**Comment by thebgpikester** [comment]
True, whilst it fits with real life though, it doesn't fit with a theme of "scoring". Scoring in my eyes is a personal effort. It would be devalued if it took no effort.

**Comment by FlightControl-Master** [comment]
Yes, BUT! what if the task scope is to let AI make an achievement? Not everything is about destroys you know.

**Comment by FlightControl-Master** [comment]
Scoring only to be given upon successful goals contributed to be achieved. Redesign.
