### ISSUE TITLE
TSK - Coordinates not accesible after accepting a task

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#424]
Whilst the tasking system gives you a BR, when you check status you can't get the original coordinates back or access them, which is a shame.

BR is a bit gimmicky, but should be an option.

Believe the fuller rendition of this module should be that Coords should be available in Task status in decimal, LL and MGRS at request. Or BR if requested. Updates sent should only be changes to the locations/numbers.

**Comment by FlightControl-Master** [comment]
What you mean with the last sentence, and, ... How to configure from an end user perspective? Menu options?

**Comment by FlightControl-Master** [comment]
@thebgpikester Can we live for the moment with a central setting to select the format between LL and MGRS. This would apply to all players in the mission.

**Comment by thebgpikester** [comment]
Yep. Similar to the latest Designation examples. If you reuse coords, then it might be a good idea to manage them centrally in moose and have the F10>Option>Coords>F1, F2, F3 as each of the types.

In fact this brings it to a different enhancement....do you want to managed some options centrally for Moose?

**Comment by FlightControl-Master** [comment]
There are two issues in one post:

- [ ] Issue 1: Whilst the tasking system gives you a BR, when you check status you can't get the original coordinates back or access them, which is a shame.

- [ ] Believe the fuller rendition of this module should be that Coords should be available in Task status in decimal, LL and MGRS at request. Or BR if requested. Updates sent should only be changes to the locations/numbers.

X means implemented...

**Comment by FlightControl-Master** [comment]
Issue 2 is implemented. May need fine tuning, but it is there now ...

Issue 1, is possible. The task keeps the detection information... So, once a player has engaged on a task, i will make a menu option that he can retrieve the task details, which will list all of the information fields on the task:

- Briefing
- Detection Information
- Detection Changes
- Players active on the Task
- ...

**Comment by FlightControl-Master** [comment]
![afbeelding](https://cloud.githubusercontent.com/assets/13690775/25403749/aee55fd8-29fd-11e7-8978-8aa52326d4ca.png)
The following fix implements issue 1 of this issue...

@thebgpikester please confirm!

**Comment by thebgpikester** [comment]
Seems like solved, that's all it needed. I will close.

**Comment by FlightControl-Master** [comment]
Once a task is assigned, you can activate this report by using "Task Status" from the Task menu.
The task menu will anyway be further optimized ...
