### ISSUE TITLE
DET/TSK - Planes are detected and assigned as BAI tasks

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#425]
Noticed both SU25 and L39ZA were detected and got tasks made for them. Should be filtered by ground units until a seperate "Air tasking module" is made.

**Comment by FlightControl-Master** [comment]
good point, i need to filter ground units only!

**Comment by FlightControl-Master** [comment]
Solved with a new change... Commit https://github.com/FlightControl-Master/MOOSE/commit/ecde6ad69450ade3f54c0d840959a0fa13b19a54

Closing this issue but needs to be tested.
