### ISSUE TITLE
SET_GROUP: ForEachGroupPartlyInZone halts the script if a GROUP has none in ZONE

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#427]
Here is log output. Need to check if a group is represented within a ZONE, if the group has none, it breaks with following error:

`68: attempt to compare number with nil`

**Comment by FlightControl-Master** [comment]
I'll check it. Any idea where it could go wrong here?

**Comment by baluballa** [comment]
I have not checked the Moose code for this function yet.. Happens when a GROUP in the SET NOT has any units in the actual ZONE. I have a work around, but since the entire script is halting, I guess it should be considered as an error.

**Comment by Grey-Echo** [comment]
Hey, I'm trying to reproduce your issue. Can you share your mission code, or at least the relevant part of it @baluballa  ?

**Comment by Grey-Echo** [comment]
I tried to reproduce this bug with the following code without success:
``` lua
local Group1 = GROUP:FindByName("Group1")
local Group2 = GROUP:FindByName("Group2")

local Zone = ZONE:New("MyZone")

local blueSoldierUnits = SET_GROUP:New()
blueSoldierUnits:AddGroupsByName("Group1")
blueSoldierUnits:AddGroupsByName("Group2")

blueSoldierUnits:ForEachGroupPartlyInZone(Zone,
  function(MooseGroup)
    MooseGroup:E("Hey, I'm partly in Zone !")
  end)
```
This worked flawlessly, so I think that either this bug is fixed, or it was a user error.

**Comment by FlightControl-Master** [comment]
His point was @greyecho if the SET_ GROUP is empty. So no GROUP added.... I think...

**Comment by Grey-Echo** [comment]
Yeah, I'm working with him on Slack on this issue.

**Comment by FlightControl-Master** [comment]
Ok. Cool and ... Thank you!

**Comment by Grey-Echo** [comment]
Ok, so the problem arose when the ZONE was passed as part of an array apparently. I changed my test code accordingly : 
``` lua
local Group1 = GROUP:FindByName("Group1")
local Group2 = GROUP:FindByName("Group2")

local Zone = ZONE:New("MyZone")
local Zone2 = ZONE:New("MyZone2")
local ZoneArray = {Zone, Zone2}

local blueSoldierUnits = SET_GROUP:New()
blueSoldierUnits:AddGroupsByName("Group1")
blueSoldierUnits:AddGroupsByName("Group2")

for i = 1, 2 do
  blueSoldierUnits:ForEachGroupPartlyInZone(ZoneArray[i],
    function(MooseGroup)
      MooseGroup:E("Hey, I'm partly in Zone !")
  end)
end
```
I also tried to emty the SET_GROUP, but still no problem. The error might have been a mistake somewhere else in the code or a one off. I'm closing this issue, if it happens again, feel free to reopen it with the code triggering the problem !
