### ISSUE TITLE
All group respawning when one unit shutts off engine.

### ISSUE THREAD

**Issue by rvotri** [FlightControl-Master/MOOSE#429]
In a group of two (or more) units, that has been spawned with "OnEngineShuttdown", happens that entire group is respawned when the first unit lands and turn it's engine off.
This usually happens when a unit gets some damage and needs to land, while other (s) unit (s) from same group keeps flying, and disappear in mid air soon as the  damaged unit shutts its engine off.

**Comment by Grey-Echo** [comment]
Hey, I think we need way more information on this issue. This could be intended behavior. Can you please update your post, following these guidelines for reporting a bug ?
https://github.com/FlightControl-Master/MOOSE/blob/master/docs/Beta_Test_Guide.md#61-how-to-report-a-bug-

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
