### ISSUE TITLE
POINT: LOS implementation between 2 points

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#431]

**Comment by Grey-Echo** [comment]
Looking into this one, I think it is already implemented :
 https://github.com/FlightControl-Master/MOOSE/blob/45640b531607178349a393ad2c6137a874c3b009/Moose%20Development/Moose/Core/Point.lua#L792-L808
Should we close this issue ?

**Comment by FlightControl-Master** [comment]
Yes, because i implemented it today for AI_DESIGNATE... @EasyEB this is done!

**Comment by FlightControl-Master** [comment]
Added POINT_VEC3:IsLOS() and UNIT:IsLOS()... @EasyEB
