### ISSUE TITLE
CARGO: Infantry stops running when boarding

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#433]
It is really strange, i set a correct route, and assign the route to the infantry. But they stop running suddenly... Vehicles don't have this problem, only infantry... Need to find a solution or workaround for this.

FC

**Comment by gunterlund** [comment]
are there enemy units near by. I believe if detected they will stop

**Comment by CraigOwen** [comment]
Looking through the example of Cargo210 (Heli), i realized, your giving a GROUP object as cargo. In case of the engeneers this consists of 5 UNITS.

After the first CARGO_UNIT is boarded the onafterLoad() method calls   self.CargoCarrier:SetTask( TaskRoute, 1 ).

So the fsm move forward although the rest of the group is not yet boarded.
This is, because group an unit call the same onafterLoad()

Maybe im wrong here.

What i cant really seems to find out is, are you setting the route info to a GROUP or a set of UNITS?
In case of GROUP the behaviour is clear

**Comment by FlightControl-Master** [comment]
Check TSK-211

**Comment by FlightControl-Master** [comment]
@CraigOwen nono what you say is not correct. The fsm waits until all are boarded. Move that group of 5 units closer to the helo and all 5 will board one by one.

**Comment by FlightControl-Master** [comment]
It seems that when infantry is far away they just stop running. Move the infantry further away. they will just stop running after a while before one has boarded.... I've been checking with ROE on hold, and that seemed to fix something. But not sure, need to test further.

**Comment by CraigOwen** [comment]
Yes, i just checked the logfile, went through the different fsms and their states. I was confused by the Carrier fsm moving forward. But the CargoGroup fsm calling each Cargo_Unit fsm in its group runs until all are boarded. I go on trying.

**Comment by CraigOwen** [comment]
Hey Sven..not nice but working....

```--- Enter Boarding State.
-- @param #CARGO_UNIT self
-- @param #string Event
-- @param #string From
-- @param #string To
-- @param Wrapper.Unit#UNIT CargoCarrier
function CARGO_UNIT:onenterBoarding( From, Event, To, CargoCarrier, NearRadius, ... )
  self:F( { From, Event, To, CargoCarrier.UnitName, NearRadius } )
  
  local Speed = 90
  local Angle = 180
  local Distance = 5
  
  NearRadius = NearRadius or 25

  if From == "UnLoaded" or "Boarding" then                             --Added "Boarding"
    local CargoCarrierPointVec2 = CargoCarrier:GetPointVec2()
    local CargoCarrierHeading = CargoCarrier:GetHeading() -- Get Heading of object in degrees.
    local CargoDeployHeading = ( ( CargoCarrierHeading + Angle ) >= 360 ) and ( CargoCarrierHeading + Angle - 360 ) or ( CargoCarrierHeading + Angle )
    local CargoDeployPointVec2 = CargoCarrierPointVec2:Translate( Distance, CargoDeployHeading )

    local Points = {}

    local PointStartVec2 = self.CargoObject:GetPointVec2()

    Points[#Points+1] = PointStartVec2:RoutePointGround( Speed )
    Points[#Points+1] = CargoDeployPointVec2:RoutePointGround( Speed )
    
    -- I need to do this mess, otherwise the units will stop boarding at a point in time...
    -- This is a DCS bug that i am handling in this way.
    do 
      local CargoBooardPointVec2 = CargoDeployPointVec2:GetRandomPointVec2InRadius(NearRadius,0)
      Points[#Points+1] = CargoBooardPointVec2:RoutePointGround( Speed )
    end
    do
      local CargoBooardPointVec2 = CargoDeployPointVec2:GetRandomPointVec2InRadius(NearRadius,0)
      Points[#Points+1] = CargoBooardPointVec2:RoutePointGround( Speed )
    end
    do
      local CargoBooardPointVec2 = CargoDeployPointVec2:GetRandomPointVec2InRadius(NearRadius,0)
      Points[#Points+1] = CargoBooardPointVec2:RoutePointGround( Speed )
    end
    do
      local CargoBooardPointVec2 = CargoDeployPointVec2:GetRandomPointVec2InRadius(NearRadius,0)
      Points[#Points+1] = CargoBooardPointVec2:RoutePointGround( Speed )
    end

    local TaskRoute = self.CargoObject:TaskRoute( Points )
    self.CargoObject:GetGroup():SetTask( TaskRoute, 2 )                        --ADDED the group call
    
  end
  
end´´´

**Comment by FlightControl-Master** [comment]
@CraigOwen  Genius!  Fantastic. 👍 
So you modified the logic that when the FSM is boarding it will always set the route until boarded.

Side question, you like the FSM approach?

**Comment by FlightControl-Master** [comment]
@CraigOwen can you do a pull request?

**Comment by CraigOwen** [comment]
@FlightControl-Master I really like this fsm approach as it atomized things alot.

Obviously i cant create a pull request. My branch has several changes atm and i could not use master for a pull request.

**Comment by FlightControl-Master** [comment]
Fixed through a nice workaround invented by @CraigOwen, think this can be closed ...

**Comment by Grey-Echo** [comment]
Why reopen this issue ?

**Comment by FlightControl-Master** [comment]
This is fixed, but i got into the issue that the fix i released did not fix it but now with the latest updates it got fixed so this is fixed i guess... i will keep it closed :-)
