### ISSUE TITLE
CARGO: Task Menu not working after unboarding

### ISSUE THREAD

**Issue by CraigOwen** [FlightControl-Master/MOOSE#435]
Testing TSK 210 - Heliclient

1. Assining to task transport - ok
2. Boarding troops "engineers" - ok
3. Unboarding troops "engineers" - ok

After these steps the task itself is still in the menu. Choosing the task the taskmenu itself is emtpy.

analysis: 

1. After unboarding the ProcessFSM goes into state unboarded.
2. Mission cant change state to success, so stays in ongoing.
3. While building the Taskmenu a dcs nil reference error occurs. See end of logfile below.

[log.txt](https://github.com/FlightControl-Master/MOOSE/files/925745/log.txt)

Trying to analize more and procede sharing info.

**Comment by FlightControl-Master** [comment]
You are right, i also saw that and was trying to resolve it. it is because of an error in the code, and just can't find out why (yet).

**Comment by FlightControl-Master** [comment]
fixed
