### ISSUE TITLE
SET_GROUP: New method SET_GROUP:HasGroupCompletelyInZone() etc.

### ISSUE THREAD

**Issue by shagratdcs** [FlightControl-Master/MOOSE#437]
Have a new method that checks if a group is present in a zone for a specific SET_GROUP and returns True or False.
Same for HasGroupPartlyInZone()
Reduces CPU cycles and can be used to evaluate conditions in if...then... else and other loops.

**Comment by FlightControl-Master** [comment]
Thanks!

**Comment by Grey-Echo** [comment]
Ok, I'm assigning this one to myself, as I'm working on it. (That's why we should only assign contributors on issues they are currently actively working on... )

 I currently have 2 new functions on branch issue437 : 
* `SET_GROUP:IsCompletelyInZone()` - return true if all the GROUPs are completely in the ZONE
* `SET_GROUP:HasGroupCompletelyInZone()` - return true if at least one of the GROUP is completely in the ZONE

What other functions would you think is needed @shagratdcs   ?

**Comment by shagratdcs** [comment]
Basically three.
SET_GROUP:AnyCompletelyInZone()
SET_GROUP:AnyPartlyInZone()
SET_GROUP:NoneInZone()

The idea is to be able to get a simple true or false condition that can be used in If...then...else or loops, so you can fire a trigger/action.

Unlike the current SET_GROUP iteration we only need the first true return and not iterate through all groups in the set. This saves CPU cycles and should be pretty useful in Mission design.

**Comment by Grey-Echo** [comment]
Ok, thank you for your feedback! I think `SET_GROUP:HasGroupCompletelyInZone()` is the same as `SET_GROUP:AnyCompletelyInZone()`. I'll work on the other 2 !

**Comment by shagratdcs** [comment]
Yep, just thought about the logic and found "AnyInZone" is much more descriptive and can't be mixed up.

**Comment by Grey-Echo** [comment]
So, to sum up, I implemented 4 new methods in SET_GROUP:

* `SET_GROUP:AllCompletelyInZone()`
* `SET_GROUP:AnyCompletelyInZone()` - only true if AT LEAST 1 GROUP is COMPLETELY in zone
* `SET_GROUP:AnyPartlyInZone()` - only true if AT LEAST 1 UNIT is in zone. Still true if a GROUP is COMPLETELY in zone
* `SET_GROUP:NoneInZone()`

Does that seem right ?
Please note that I still need to test them thoroughly before creating a pull request. But anyone can check them out on branch "issue437"

**Comment by CraigOwen** [comment]
I second shagratdcs. 

We have three to four questions here for each group.

1. GROUP:IsCompletelyInZone - true if all units of a group are in the zone.
2. GROUP:IsPartlyInZone - true if NOT all, but at least one is in the zone.
3. GROUP:IsAnyInZone - true if at least one unit is in the zone.
4. GROUP:IsNotInZone - true if no units are in the zone.

According to sets this would mean to me. 

1. SET_GROUP:AnyCompletelyInZone() - returns all groups having GROUP:IsCompletelyInZone = true
2. SET_GROUP:AnyPartlyInZone() - returns all groups having GROUP:IsPartlyInZone = true
3. SET_GROUP:AnyInZone() - returns all groups having GROUP:IsAnyInZone() = true
4. SET_GROUP:AnyNotInZone() - returns all groups having GROUP:IsNotInZone() = true.

makes sense?

**Comment by Grey-Echo** [comment]
@CraigOwen  I can see multiple issues with your proposition 

* `SET_GROUP:AnyCompletelyInZone()` is a very confusing name if it returns true only if **ALL** the GROUPs are in Zone. This is true with the other function names you proposed...
* Can you imagine a scenario in which you want to know if all GROUPs of a SET_GROUP are partly in a ZONE ? It makes sense for a GROUP, but not for a SET_GROUP IMO.
* In your proposed implementation, there is no way to know if some of the GROUPs are in zone, or some of the UNITs of some of the GROUP are in zone, which I think are 2 very usefull information.

I don't think we can simply copy paste the GROUP functions into SET_GROUP, we have to think of the use of a SET_GROUP. That's why I'm very interrested in @shagratdcs 's feedback : he is clearly trying to **use** the functions, and that is the best way to discover what is needed and what is not !

BTW, while implementing those function, I fixed a sneaky bug in `GROUP:IsPartlyInZone()` !

**Comment by CraigOwen** [comment]
I did edit this above. Was that not updated?

1. SET_GROUP:AnyCompletelyInZone() - returns true having a GROUP:IsCompletelyInZone = true
2. I see your point. this is maybe not very useful.
3. Using the four diffenrent methods on set, i can clearly distinguish between whole groups, only some units or truely not the whole group of a set in a zone.

Usecases would be moving convoys created by spawn routed through zones. 
I then would surely want to know if

1. At least one unit of the convoy groups is in a certain zone. 

```
ConvoysCityA = SET_GROUP:New():FilterPrefixes('Convoy')
if ConvoysCityA:AnyInZone( ZONE:New('CityA' ) ) then
   --either they are arriving, or one was left behind....
end
```
2. Some of the convoy groups units are in a certain zone. (Convoy is close to target zone ) 
```
ConvoysCityA = SET_GROUP:New():FilterPrefixes('Convoy')
if ConvoysCityA:AnyPartlyInZone( ZONE:New('CityA' ) ) then
   --Looks like one of my convoys has not yet fully arrived or left the city
end
```

Case 1 and 2 look very similar. But in case 2 i know for sure, that no group of my set is fully in the zone.


3. the other way round. I want to ensure that at least one group is Completely in. 
```
ConvoysCityA = SET_GROUP:New():FilterPrefixes('Convoy')
if ConvoysCityA:AnyCompletelyInZone( new Zone('CityA' )) then
   --Looks like one of my convoys has arrived.
end
```

Thinking further, maybe i need to know if the other coalition is there as well AND how many of them...

```
Convoys_Blue = SET_GROUP:New():FilterCoalition('blue'):FilterPrefixes('Convoy')
Convoys_Red = SET_GROUP:New():FilterCoalition('red'):FilterPrefixes('Convoy')
City = ZONE:New( 'City' ) 
if Convoys_Blue:CountAnyInZone( City ))  > Convoy_Red:CountAnyInZone( City ) then
   --looks like blue is taking over the City
end
```

Just ideas.

**Comment by shagratdcs** [comment]
Ok, I explain what I want to achieve.
First the scenario I have an Area of Operations zone("AO"). I spawn a couple groups with preplanned attack routes on different targets in the AO, randomly.
In parallel I want patrols both blue and red roaming around the roads and bump into each other or attack the unsuspecting player.
Planned as an endless mission for MP I want to respawn the random attack when one is defeated.
Two problems:
1) how to distinguish between red Attack and red Patrols? Solution use SET_GROUP by Country or Prefix. Example: redATK = SET_GROUP:New():FilterByCountry("RUSSIA")
2) only respawn a red Attack when no remaining Attack units remain in the zone(AO)...

To solve the second issue I could simply use:
If redATK:NoneInZone(AO) then <code to randomly respawn a new attack>
While the patrols are still in the AO.

The SET_GROUP filter is ingenious, as it could also help distinguish between combatants and neutral factions/civilians and multiple other issues where it comes in handy to simply check if any vehicle/aircraft/etc of a certain SET is completely, partly or not at all in a specific ZONE.

**Comment by shagratdcs** [comment]
Damn, typing on smartphone sucks...
If redATK:NoneInZone(AO) then *execute code to respawn a new random attack*

**Comment by Grey-Echo** [comment]
@CraigOwen It wasn't updated when i wrote my response. Now it makes much more sense.
Pretty much everything you describe is already implemented, except `AnyPartlyInZone()`. It's just a matter of renaming the functions I wrote.
The counting in zone is easily doable too. I'll add that to my todo list :)

@shagratdcs , ok, that makes sense and will be easy to do with the new functions !

As for the filters which both of you seem to like, would they return an array or GROUPs ? I'm interrested in the idea, but I think this should be its own GitHub issue, there is enough feature creep in this one :D

**Comment by CraigOwen** [comment]
@Grey-Echo Sounds great. I think these funktions will be very helpful. Thank you for the implementation.

@shagratdcs Sounds like a great idea, as unpredictability is a fun factor for this game.

**Comment by Grey-Echo** [comment]
Pull request created  : https://github.com/FlightControl-Master/MOOSE/pull/453

I've been thinking about filters too, but after a bit of brainstorming, I can't see what could be done with them that can't already be done with `SET_GROUP:ForEachGroup()` and similar functions. We need to discuss this more.

**Comment by shagratdcs** [comment]
@Grey-Echo - the SET_GROUP Filter is already there! We can use Coalition, Country, Prefix, Unit type(?) to filter a dynamic SET.
Now with the evaluation method return "true" or "false" unlike the current redATK:ForEachGroupCompletelyInZone( AO, function...CODE... end) it won't need to go through all groups, just iterate until it found the first condition match.
I hope I make sense here.

**Comment by Grey-Echo** [comment]
Yes you do. I was talking about functions that would return an array of GROUPs in a Zone for exemple. It was requested by @CraigOwen , and you seemed to like the idea : 
> The SET_GROUP filter is ingenious, as it could also help distinguish between combatants and neutral factions/civilians and multiple other issues where it comes in handy to simply check if any vehicle/aircraft/etc of a certain SET is completely, partly or not at all in a specific ZONE.

But I think all of what you described could (and should) be done with `SET_GROUP:ForEachGroup()` functions.

**Comment by shagratdcs** [comment]
Yep exactly, I was referring to the existing filter. Sorry for the confusion. :)
