### ISSUE TITLE
Missing files in the Moose repository

### ISSUE THREAD

**Issue by Alpenwolf** [FlightControl-Master/MOOSE#438]
Hi,

I'm just getting started here and had a problem while configuring MOOSE in LDT. Some folders are missing:

.git
Moose Presentations
Moose Test Missions
Moose Training

The rest of folders and files is there in addition to a folder by the name "Utils".

Thanks for the great work!

**Comment by Grey-Echo** [comment]
Are you using the latest Moose release (downloaded from here : https://github.com/FlightControl-Master/MOOSE/releases/tag/2.0) or are you using Git ?
If you downloaded the latest release in a .zip file, then it's perfectly normal:
* .git is something necessary for Git to work, no need for it in the release
* the presentations are now available here : https://github.com/FlightControl-Master/MOOSE_PRESENTATIONS (but you shouldn't need them in the short term)
* Download the test missions adapted fo the release here : https://github.com/FlightControl-Master/MOOSE_MISSIONS/releases/tag/2.0-updated

Does this answer your question ?

**Comment by Alpenwolf** [comment]
Sort of.

I simply followed your hints again and kinda worked my way around it. Now it works!

Thanks!

**Comment by Grey-Echo** [comment]
Well, if you need more help, feel free to ask, especially on Slack :) ! I'm closing this issue.

**Comment by FlightControl-Master** [comment]
@Alpenwolf please check the following video channel for very detailed installation instructions:

https://www.youtube.com/playlist?list=PL7ZUrU4zZUl1FR9HUgTXsVtRadDVp7X_u
