### ISSUE TITLE
on group respawn (not destruction) - group is considered dead

### ISSUE THREAD

**Issue by Igneous01** [FlightControl-Master/MOOSE#440]
There might be a possible bug with this. 

If you spawn air flight, using keep group name, and initRespawnOnLanding / initRespawnOnEngineShutdown, when the flight lands / shuts down engines, the group is deactivated. 

In Mission editor, any triggers that check if group dead (myGroup) or group in zone (myGroup) will be considered true when the group is despawned, even though they have not died (they will be respawning again soon).

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
