### ISSUE TITLE
CAP _Abort

### ISSUE THREAD

**Issue by 132nd-Entropy** [FlightControl-Master/MOOSE#442]
I try to have a CAP plane abort the attack when it leaves a certain zone, to allow the target to run away. 
When I put in a scheduler that will execute the _Abort() command, the CAP plane will return to its orbit zone. However, it apparently will stop detecting, because when the target plane re-enters the engagement zone, the CAP plane will ignore it .

Im not sure if that is intended or how I should set it up.

**Comment by Delta-99** [comment]
This is by design. See my comment on slack.

**Comment by Grey-Echo** [comment]
I'm closing this issue then.
