### ISSUE TITLE
Destroying Client Unit for fratricide will crash beta version of DCS multiplayer server

### ISSUE THREAD

**Issue by afinegan** [FlightControl-Master/MOOSE#447]
Destroying Client Unit for fratricide will crash beta version of DCS multiplayer server

I suggest commenting this line out, this should be pushed to when MOOSE-SERVER can control client slots by flags through the GameGUI.lua system

**Comment by FlightControl-Master** [comment]
can you make a solution Using a flag system?

**Comment by FlightControl-Master** [comment]
@afinegan can you please consider to make a solution with a flag system to kick players?

**Comment by afinegan** [comment]
Definitely, I know how to do it, have code that does it - getting it into a proper format, trying to find time to do it, its based on how handles player lives and slots in CSAR script.

**Comment by FlightControl-Master** [comment]
@afinegan It would be SOOOOOOO cool you could get this to work. Do you have any idea how much work we put into AIRBASEPOLICE? If you can make this work, we can have both SP and MP working with AIRBASE police!!!

**Comment by FlightControl-User** [comment]
This is not happening anymore. Closing. However there is still a pending report on this. #864
