### ISSUE TITLE
SPA - implement a variant of SpawnScheduled that checks time since death (not time since spawn)

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#455]
Use case:
During a typical Spawn Schedule the time limit has often been reached, even in 30 minutes of gameplay, if you set a spawn scheduled to 30, and kill it after some time, you get the unit instantly respawning. What would be more useful is checking the time since death, rather than since spawn. The reason is, this creates gaps in spawning. Ie kill an enemy flight, they dont instantly respawn, they respawn after 5 minutes if a scramble and 15 generally due to a colder start.

The workaround is to create funcitons for each group with timers, which is pretty heavy on the timers. In fact you will need to put an even tag on the death of the group, or manually check the group every minute or so. If you have many gorups to monitor this gets quite cumbersome.

I'd propose something along the lines of :RespawnDelay(seconds) as a new initiator of spawn. So MyGroup = SPAWN: New('MyGroup'):InitLimit(1,0):RespawnDelay(300) would respawn a group only 300 seconds after it died, rather than as soon as the limit was reached and so the unit wopuld keep respawning, but not immediately after it was killed.

Thoughts?

**Comment by FlightControl-Master** [comment]
Understand. Is it urgent?

**Comment by thebgpikester** [comment]
No. Since you can work around it, just with some messy code. The workaround is to create a scheduler checking for the group being alive, then once dead, to begin a loop that increments a value once a minute until the required time, THEN spawn the object again.

**Comment by FlightControl-Master** [comment]
Heum... What if SPAWN would listen to the dead events, and when it occurs, it would register the time that dead occurred as a timestamp for that group in a timestamp table... When schedule wants to spawn, will only spawn when the timestamp + delay time is smaller than the current tine...

**Comment by thebgpikester** [comment]
So, do you mean editing the SpawnScheduled to reflect death also? Would likely make more sense. ReSpawn() has everything normally.

**Comment by baluballa** [comment]
Old
