### ISSUE TITLE
TSK-212 - Helicopter: FSM transition broken

### ISSUE THREAD

**Issue by CraigOwen** [FlightControl-Master/MOOSE#456]
In TSK-212 - Helicopter - Cargo handle PickedUp and Deployed events - The Task is not properly forwarded after the Transition from 'Landing' to 'Landed'. The expected menu like 'Task' -> 'Task001' -> 'Unboard Group' is not available

**Comment by FlightControl-Master** [comment]
Ok. Thanks for telling!

**Comment by FlightControl-Master** [comment]
Fixed. @CraigOwen
