### ISSUE TITLE
Create a class to handle communications of informations to the player

### ISSUE THREAD

**Issue by Grey-Echo** [FlightControl-Master/MOOSE#467]
Right now, the communication to the player is done in Moose with multiple class that wraps DCS functionalities (mainly `MESSAGE` and `RADIO`). This works fine but prevents the player to choose options on how the information should be presented to him. For example, we may want to give the option to output every coordinate in MGRS or LL.

This would require a `COMMUNICATION_MANAGER` class (the name isn't final...) that would store the different options chosen by the player as attributes, and then call the right wrapper function to actually communicate the information. This class would be called everywhere **In Moose**, instead of `MESSAGE`.

The information will need to be sent through Add function. The type of addition would be determined by the second argument: a string. For example,
``` lua
COMMUNICATION_MANAGER:Add("Go to", "string")
COMMUNICATION_MANAGER:Add(PointVec3, "absolute coordinates")
COMMUNICATION_MANAGER:Add("which means fly towards", "string")
COMMUNICATION_MANAGER:Add(PointVec3, "relative coordinates")
COMMUNICATION_MANAGER:Output()
```
would be translated to `"Go to {LL/MGRS} which means fly towards 125° for {15km/9miles}"` by `COMMUNICATION_MANAGER`, and then be outputted with MESSAGE. The `COMMUNICATION_MANAGER` chooses between stuff in {} depending on the options previously set.

This would be totally retro-compatible, as mission designer could (and would) still use the wrapper functions as usual. Looking into the (distant) future, this would open the door for other features, like multiple language support and an option to use RADIO communication instead/as well (issue https://github.com/FlightControl-Master/MOOSE/issues/360)

__Suggested implemetation__
``` lua
-- During Moose's startup, we instantiate a `COMMUNICATION_MANAGER`, with some default options
COMMUNICATION_MANAGER:New(UseText, UseRadio, useMGRS, ... )

-- In the rest of Moose's code we replace every call to MESSAGE this way :
COMMUNICATION_MANAGER:Add("Info", "string")
COMMUNICATION_MANAGER:Output()
-- And then, the COMMUNICATION_MANAGER calls the right classes to output the information, given the options that have been previously set.

-- In their missions, MDs can choose options.
-- They need to be given a reference to the COMMUNICATION_MANAGER instantiated first...
-- There is probably a way to do that, I need to think about it...
-- This could be insert in a menu system too, to give the option to the player
COMMUNICATION_MANAGER:UseMGRS(true)
COMMUNICATION_MANAGER:UseText(false)

-- MD could even use the COMMUNICATION_MANAGER, but it will probably is simpler for them to use MESSAGE and RADIO directly, which is totally fine.
COMMUNICATION_MANAGER:Add("Info")
COMMUNICATION_MANAGER:Output()
```

This is a rough concept and probably needs some work. Give your ideas to improve this concept below !

**Comment by thebgpikester** [comment]
So I was discussing something related in TSK, with the coordinates and the same occured to me. That if two modules reuse the same setting, then should we not have central settings?

The two occasions that occur to me off the top of my head are
1) Coordinate format: H/Min/Sec, Decimal and MGRS.
2) Frequency of screen updates: 10, 5, 2, 1, OFF.

I'm sure there are more. This makes sense to the user, since in other scripts these can be configured. I vote for this, as it fits with a framework style objective of scripts and using a central setting reuses the maximum amount of code.

**Comment by thebgpikester** [comment]
using the GreyEcho example, additional settings:
Updates by:
1) Text Only (default)
2) Radio (Only get updates if tuned to a preset channel and a sound cue is provided on message)
3) Silence (Turn all updates off)

**Comment by baluballa** [comment]
Think this is in place.
