### ISSUE TITLE
TASK DISPATCHING: Order available tasks by distance from requesting client

### ISSUE THREAD

**Issue by CraigOwen** [FlightControl-Master/MOOSE#472]
Choosing a task from the "planned" list can be a bit confusing, and nearly all the time i tend to choose the first one, especially, when i'm in a plane/chopper where i can not use the coordinates to figure out the positions of those tasks.

So when it comes to showing all available tasks, the list could be ordered by the distance from the reuqesting client.

Taks CAS 001 ...qwererqe... 7km
Task BAI001 ...wuauauau ... 10km
Task SEAD 001 ...qweoiewrt ... 30 km

So a client can decide very fast wich task to assign to.

**Comment by FlightControl-Master** [comment]
requirement understood.

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
