### ISSUE TITLE
COORDINATES not updating

### ISSUE THREAD

**Issue by d0o0m** [FlightControl-Master/MOOSE#476]
Changing the coordinates does not retroactively update previous detections.  FAC identified a task and reported in MGRS, Coordinates were updated to use LL and only new targets were reported in LL from then on.  Mission description reporting and HQ still reported the earlier tasks identified in MGRS.

**Comment by FlightControl-Master** [comment]
yes, this can happen because the detection report willl only be updated when a detection happens.
I will see what i can do with that. I hope this is not a showstopper.

**Comment by d0o0m** [comment]
shouldnt be.  Most players are very much used to resorting to google for conversions anyway already.  And this was only noted because i had the FAC already making calls at mission start.  The more reasonable scenario would be having the reaper or FAC flying to a patrol zone thus giving clients LOTS of time to select the reporting standards they want in advance.

**Comment by Whiplash822** [comment]
While I do not think this is a show stopper, I think if left as is, changing the coordinate setting should only be allowed by a server admin since it effects all clients. In a populated server you could image how convoluted it would be with every new client changing the coordinate setting.

**Comment by FlightControl-Master** [comment]
Indeed... Need to think a bit more on this... The goal is to have coordinates per player, but it is hard to apply then on the objects... Maybe the menu is an option and the system can be configured by scripting. Or... The menu would be available at HQ...

**Comment by FlightControl-Master** [comment]
I am thinking on putting a coordinate setting per command center. Would such be a good idea. So you could have the French command center, the USA command center and the EU command center???

**Comment by FlightControl-Master** [comment]
And that setting then would only be modifyable when you join the Command Center group using CA, because then a menu option would become available.

**Comment by FlightControl-Master** [comment]
@d0o0m @Whiplash822 this is fixed :-)
