### ISSUE TITLE
TSK-A2G DISPATCH.  TASK assigned to aircraft and not client?

### ISSUE THREAD

**Issue by d0o0m** [FlightControl-Master/MOOSE#477]
Tasking selected by clientA is shown properly in Task Status report to client A and client B .... clientA exits plane A (groupA) and enters different aircraft B(GroupB).  API reports clientA aborting task to clientB.  clientA does not see task in new aircraftB.  clientB still saw client reported as assigned in original task.  When clientA returns to Aircraft A, then task is visible to clientA again.

**Comment by FlightControl-Master** [comment]
Test scenarios to check and improve on if not working (for Sven):

- [ ] Log into A, then B. Join Task X. Both A and B should receive a notification.

**Comment by FlightControl-Master** [comment]
- [ ] TODO: Log into A, then B. Join Task X. Both A and B should receive a notification. Both A and B should be assigned to the TASK.

**Comment by FlightControl-Master** [comment]
This is all fixed...
