### ISSUE TITLE
TSK-A2G Dispatch.  Task selection autoassigned to other groups

### ISSUE THREAD

**Issue by d0o0m** [FlightControl-Master/MOOSE#478]
Client A (Group A) selects task at mission start.  Client B (Group B) receives notification that their groupB has been assigned task.  ClientA observes Client B assignment in task status report and Client A recieves vector to target.

Client B does not receive vectors or option to abort/select task status until they actually select the same task themselves.

**Comment by d0o0m** [comment]
confirmed still happening with testing tonight.

**Comment by FlightControl-Master** [comment]
There is no task auto assignment anymore. 
Each group needs to select if they want to pariticpate in a task.
Each group can only have one maximum task active.
If a group has an assigned task, an assigned menu will pop up.
This assigned menu must dissapear when the group decides to abort the task.
The messages should now be sent consistently.
