### ISSUE TITLE
TSK-A2G DISPATCH Task status report not refreshing

### ISSUE THREAD

**Issue by d0o0m** [FlightControl-Master/MOOSE#479]
Task status reporting does not update following abort, mission success, change in task selection or change in client aircraft.  It continues to display the first task chosen by client during mission.

**Comment by FlightControl-Master** [comment]
Task status reporting does not update.

- [ ] Fix task status reporting following abort

- [ ] Fix task status reporting following mission success

- [ ] Change task selection

- [ ] Change client aircraft

**Comment by FlightControl-Master** [comment]
When and how did that task status show up?

I assume with Task, you meant Mission, correct? And that the message appeared that although the mission was complete, that the message still appeared that 0 tasks were awaiting to be executed?

I think that is fixed now.

**Comment by d0o0m** [comment]
heres the scenario.

Client A/GroupA joins BAI001, Client B/GroupB also joins BAI001.  Client A checks Task Status in F10.  It shows BAI001 assigned to both Client A and B.  Now  if any of the following occurs, the task status continues to show Client A and B assigned to BAI001:

- if Client B aborts task
- if client B leaves to go to a new group
- if client A aborts and selects a new task
- if BAI001 is successful.

**Comment by FlightControl-Master** [comment]
- [ ] 1. if Client B aborts task
- [ ] 2. if client B leaves to go to a new group
- [ ] 3. if client A aborts and selects a new task
- [ ] 4. if BAI001 is successful.

@d0o0m I just sent you a new moose.lua. 
- Can you retest problem 1 of this list? I think this should now be fixed.
- Can you also elaborate how 2 was done? Just back to spectators and then selected another group, right? In that case, the player also "aborted" the task, and thus the similar situation should be like case 1.

**Comment by Whiplash822** [comment]
@FlightControl-Master I observed problem 2 as you described. In plane A I select a task. Then I left plane A by selecting Plane B (without going to spectator just straight to selecting plane B). In Plane B, I did not have a task assigned to me. Then I left Plane B and entered Plane A and observed that I was assigned the original task. 

To elaborate further, I left plane A and d0o0m (In plane C) entered plane A and he observed that he had a task assigned to him. It is important to note that it is unclear whether the task was assigned to d0o0m in plane A was initiated when he selected a task in Plane C or if it was initiate when I selected a task in Plane A. However, based on the other observations I think we can assume the latter.   

Hope this helps.

**Comment by FlightControl-Master** [comment]
I think I fixed 1 and 2 now .... I'll publish to master in a second ... with pull request #484

**Comment by d0o0m** [comment]
UPDATE ... sorry FC alot was acting odd tonight with this:  test case = client1 and client 2 both select BAI001.  Confirm task status correct showing BAI001 Assigned to C1&C2.  Client 2 aborts, client 1 aborts.  Confirm task status showing BAI001 Aborted.  Client 1 and client 2 then select BAI002.  Receive assigment confirmation.  Check task status.  Client 1 shows BAI002 assigned.  Client 2 shows BAI001 Aborted still.  Client 1 aborts, client 2 aborts. receive confirmation of aborted tsk.  Check task status.  Client 2 still seeing BAI001 aborted message,  Client 1 did not have Task status as option available.  Client 1 and Client 2 attempt to select BAI003.  Client 2 saw BAI003 and selected. Client 1 did not have BAI003 as option.  Client 2 began receiving 2 vectors at once (2lines).

**Comment by Whiplash822** [comment]
![screen_170426_211653](https://cloud.githubusercontent.com/assets/25238456/25467930/bfa9b28c-2ac6-11e7-9368-745cdd814a22.jpg)
screenshot of two vectors assigned to client 2

**Comment by FlightControl-Master** [comment]
This is fixed. The A2G dispatcher will just display the available tasks... I will rework what it displays a bit.
