### ISSUE TITLE
TSK-A2G DISPATCH HQ continues to send vectors to target after target is destroyed

### ISSUE THREAD

**Issue by d0o0m** [FlightControl-Master/MOOSE#481]
Client receives vectors to BAI003.  Destroys BAI003.  Receives HQ confirmation that 0 targets remain with "GoodJob message"  Client returns to base but continues to receive vectors directing them toward the destroyed target even though nothing is there.

**Comment by FlightControl-Master** [comment]
oh ohhh... That sounds like the background process has not been killed...

**Comment by FlightControl-Master** [comment]
I think this is fixed now. I am explicitly cancelling the processes and explicitly for each process, cancelling the pending schedules.

**Comment by FlightControl-Master** [comment]
Fixed through commit #482
