### ISSUE TITLE
SCHEDULER - the last optional parameter "Stop after X seconds is not honoured."

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#494]
There are 3 weays at least to stop a schedule.
a) Use the last optional parameter stop after X seconds...its not dynamic but it might be the first to use more obviously.

s2 = SCHEDULER:New( t2, function() 
  test2:SpawnScheduleStart()
  MESSAGE:New("Red Spawn in progress",30,"Demo"):ToAll()
 end, {}, 6, 10, 0, **16** )
16 should stop the schedule after 16 seconds yet it does not.

Alternative methods of s2:Stop() or s2=nil then garbagecollect() could be used instead
Marked not urgent due to workarounds, but people need to be aware,

**Comment by thebgpikester** [comment]
I'm testing the alternatives but they do not work! s2 = nil then collectgarbage() does not kill the schedule!!

**Comment by thebgpikester** [comment]
OK ignore the above, you can bully a scheduler into dying but it's quite hard. Instead lets update scheduler to do some things we want:
1) Make a scheduler function to run after X seconds then delete itself. ONCE ONLY
2) Make a scheduler function to run after X seconds and then repeat until, OR fix the stop of the scheduler and make it work.
3) highlight additional power uses of scheduler by explaining the other uses better - already some information on attaching them to objects and so on bu the docs are confusing for simple minded people like me.

**Comment by FlightControl-Master** [comment]
@thebgpikester We fixed this issue in release 2.2.0.pre :-)

Thank you @funkyfranky for the help with the testing!
