### ISSUE TITLE
Rework the SCORING class

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#50]
Embed SCORING in other classes by making and using SCORING APIs to add scores of a certain type upon certain events.

**Comment by Grey-Echo** [comment]
Removed the first part of the issue : "Make a scoring based on "unit strength" parameters. The descriptors of the units need to be used for that." since it is already covered by issue #276

**Comment by FlightControl-Master** [comment]
This is done.
