### ISSUE TITLE
Moose cannot open Routines.lua

### ISSUE THREAD

**Issue by snakesn** [FlightControl-Master/MOOSE#500]
After today's update  - moose cannot open Routines.lua 

06579.899 ERROR   DCS: Mission script error: : [string "C:\Users\alexs\AppData\Local\Temp\DCS.openbeta\/~mis00007472"]:11: can't open 'Scripts/Moose/Utilities/Routines.lua'
stack traceback:
	[C]: ?
	[C]: in function 'assert'
	[string "C:\Users\alexs\AppData\Local\Temp\DCS.openbeta\/~mis00007472"]:11: in function 'Include'
	[string "C:\Users\alexs\AppData\Local\Temp\DCS.openbeta\/~mis00007472"]:24: in main chunk

**Comment by snakesn** [comment]
invalid. the setup was changed - after i adjusted to a new way - all good

**Comment by FlightControl-Master** [comment]
that was quick! are you still using the framework?

**Comment by snakesn** [comment]
yes. was busy lately - trying to focus on the website. https://www.gflwarfare.com/
By the way - can I refer to the Moose framework on my website - like "Power by MOOSE"

**Comment by FlightControl-Master** [comment]
That would be VERY kind of you!
If you do that, could you use one of these logos? See underlying link...

There are made by @EasyEB 

https://github.com/FlightControl-Master/MOOSE_PRESENTATIONS/tree/master/Moose%20Logo

**Comment by snakesn** [comment]
ok sure ! :-)

**Comment by snakesn** [comment]
question. should I keep moose files into the Scripts on the Server installation of DCS? before it was not required

**Comment by FlightControl-Master** [comment]
Sorry. Don't understand your question. Can you elaborate a bit please?

**Comment by Delta-99** [comment]
FC, my guess is he is running dynamic version of Moose. So this is still causing issues for people. When deploying missions for use or distribution or running on a server I think they should be creating a static moose version.

**Comment by FlightControl-Master** [comment]
Ha. Now i get it too.... You can choose... If you use the master branch on your server, you need those moose files on the server. Otherwise, you need a static moose.lua version. And this needs to be generated with the latest code base. Is this ok?

**Comment by snakesn** [comment]
i got it :-)

**Comment by FlightControl-Master** [comment]
what is your web site?
