### ISSUE TITLE
Aircraft not releasing in BAI mission if _start timer is greater than 1

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#504]
if the __Start() option is greater than 1, the aircraft will go to the patrol zone and never leave. 

Rus52HvyBombMission:__Start(100)
Rus52HvyBombMission:__Engage( 1, 1000, 5000, AI.Task.WeaponExpend.ALL )

**Comment by gunterlund** [comment]
looking at the code I think this is the same thing that was happening in CAS. the module was not reading the parameters fed in so it is defaulting to 400km and 2000m. This makes sense as with my parameters listed above once the aircraft drops its bombs at 5000m meters it dives for the deck to 2000m.

**Comment by Delta-99** [comment]
Thought this was fixed at some point but maybe not.

**Comment by FlightControl-Master** [comment]
The code won't work like this!
You're asking it to wait with the process about 100 sconds, but ask to engage after one second...
However, this will work:

```
Rus52HvyBombMission:__Start(100)
Rus52HvyBombMission:__Engage( 101, 1000, 5000, AI.Task.WeaponExpend.ALL )
```
