### ISSUE TITLE
TSK ACT_ROUTE_ZONE & ACT_ROUTE_POINT: Other ways to navigate 

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#507]
_ACT_ROUTE_ZONE_ and _ACT_ROUTE_POINT_ state give alternative options routing. Think it should be an option to not give route direction and distance, but rather give coordinates in various formats, so players have to use their navigation skills to achieve the mission goals.

**Comment by thebgpikester** [comment]
+1. BR is a good option for _some players_ and is important for many things, but with many players of advanced aircraft systems and full fidelity models, inputting the coords is both more faithful to the simulation and indeed gives them displays on their own aircraft for navigation purposes that constantly update (and so is less useful). I believe this should go in the same catagory as the "Options" for LL/decimal, MGRS, and should include a frameworked option for all settings like Metric vs Imperial, BR vs LL, Decimal, MGRS and so on.

**Comment by FlightControl-Master** [comment]
A few things...

The coordinates LL and MGRS are plane dependent, correct?
The choice whether to allow for BR is to be set by the mission designer?
If BR is allowed, should this choice then be made by the player or by the tactical commander?
Should menus to be disabled to enforce a certain mode?
...

**Comment by baluballa** [comment]
I believe Viggen and A10Cs uses different formats, so both should be available. FC models have to use F10 map, same goes for choppers. I think the mission editor should decide by somehow setting routing allowed to false in mission settings.  And also coordinates should be available by _report_ when player is assigned to the mission.

**Comment by FlightControl-Master** [comment]
Is it okay if I move this requirement to release 2.2?

**Comment by FlightControl-Master** [comment]
Started with this. WIP
