### ISSUE TITLE
TASKING: Should you not be able to see briefing given in mission setup?

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#509]
wingthor [9:51 PM] 
TY, feel like noob asking this, but this message comes about _briefing, press LALT + B_. But when doing so only the default briefing comes up. Should you not be able to see briefing given in mission setup?

**Comment by FlightControl-Master** [comment]
@baluballa 
Yes, but I have a couple of options here:
1. The mission briefing can be displayed when the player joins a task from the mission. 
2. The mission briefing can be flashed when the player has no mission ongoing.
3. The mission briefing can be displayed when the player goes into the mission menu and selects show briefing.

**Option 1** is really confusing for players. That would mean a lot of text that will be diplayed: 

- Mission briefing
- Task Briefing
- Task startup details.

That is confusing for players. What is the mission briefing, what is the task briefing ... An option could be however to delay the task briefing display and start with the mission briefing first.

**Option 2** is a side option. I could build in a message flashing that shows missions the player can join when he has no task assigned. The idea is to have a task assigned. However, there were already comments from people that the flashing is not a good idea...

**Option 3** is a _good one to avoid overdone text displays_, but this is an **action required by the player**. And I don't think he will every time go into the menu and select "show briefing" for each mission.

So, looking at the options, which one is the best? I'll add Option 3 already, because it is easy and the allows at least for a briefing to be shown. Please consider **Option 1** and **Option 2** for feasibility.

**Comment by FlightControl-Master** [comment]
I have added **Option 3**, a new Mission Briefing menu option under each mission. By selecting this option, you can allow the player to show the mission briefing text.
On top, I have also reworked the mission reports menu generation (removed it from the TASK class to the MISSION class).
As a result, a more consistent Mission menu end-user experience should be achieved.

**Comment by FlightControl-Master** [comment]
Please consider option 1 and 2. What to do with these?

**Comment by thebgpikester** [comment]
I'm an option three person. I want to browse the available 'missions' (naming confuses here....what is a task, what is a mission) I then want a selection, I then want to be able to access the current status, but not interested in updates flashing up that much. UNLESS its a completely new mission available. Then a generic message of "New mission available" is enough. If I can PULL my updates, I would check, anything being PUSHED to screen via essage should be minimised.

**Comment by dwpenney** [comment]
I do not like option 3 because the flashing can be really annoying. Also, it may be that the player is not in a position to take part in a mission (lets say he/she is returning to base or some other state that means that they are not immediately interested in joining a mission - like for example I am in my Ka-50 and get seriously damaged, I am not interested in joining a new mission at that point, only interested in getting my bird home. I would prefer Option 3 with a note in the text briefing (before launching) and a 'welcome' message displayed with a brief briefing and a note to 'check in' in the comms menu.

**Comment by dwpenney** [comment]
Also, if this works for multiplayer (at some point when ED can give more focus to multiplayer Lua issues) a flashing message when a client is part of another team (and maybe the teammate is handling the mission bureaucracy), a flashing message will get annoying real fast :-)

**Comment by thebgpikester** [comment]
My understanding is that Option 3 doesn't flash anything.

**Comment by FlightControl-Master** [comment]
That is correct.
So it looks like Option 3 is the preferred one. Will then just keep what i have at the moment and it also makes my life easier :-)
Option 3 it will be, a menu briefing per mission and user needs to select manually the briefing to see it.
I may add a menu to see "all briefings" in case multiple missions are playable... But that is for later i would say and is fine tuning.
Thanks guys!
