### ISSUE TITLE
DESIGNATE requires a manual method using POINT

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#514]
Right now DESIGNATE uses DETECTION to build lists of targets to lase. However this method excludes possibility to use it for lasing scenery or lasing only one very specific unit without the DETECTION process whichh could also limit.

I believe the class would benefit from being able to lase a POINT provided by a Vec2/vec3.

**Comment by FlightControl-Master** [comment]
Ok!

**Comment by baluballa** [comment]
Think its in place...
