### ISSUE TITLE
UNIT should have methods for getting flight data

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#515]
For GROUP we have getMaxSpeed and height across the group, but for UNIT there is no way of getting flight data which would make more sense.
Some of the more complex data that the ME provides, and MIST provides, but MOOSE does not are:

Height
Speed
AoA
Climb/Descent rate
Yaw
G
Bank/Roll
Turn rate
And so on...

Some of these would be useful for Landing assistance or an LSO module. There also could be a useful Data collection output to XLS as per scoring that could record max G, fastest instantaneous turn rate, max speed and altitude. Flight telemetry type uses or landing.

**Comment by FlightControl-Master** [comment]
Ok... I'll put this to release 2.2.

**Comment by baluballa** [comment]
Old
