### ISSUE TITLE
Check to see if coalition is in zone

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#530]
Would like the ability to check to see if a member of a coalition or side is in a zone. At this time to do this you would have to make a giant set group and then do a check to see if the group was partially or all in a zone.

**Comment by FlightControl-Master** [comment]
This is a difficult implementation. But crunching my head on this one.

**Comment by LosMackos** [comment]
Hi there,

just worked for me:
```
local RedAirSpace = ZONE_POLYGON:New( "Red Air Space", GROUP:FindByName( "Red Air Space" ) )
local BlueCoalitionSetGroup = SET_GROUP:New():FilterCoalitions("blue"):FilterStart()
if BlueCoalitionGroup:AnyInZone( Zone ) == true
 <code>
end
```

Br,
Alex
