### ISSUE TITLE
SCO - Allow scoring to "Teams" also (ENHANCEMENT)

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#531]
a couple of suggestions for Scoring; Players are tracked as individuals. It would be nice to add the following functions to broaden the use and scope:

**New:Team**("Teamname") -- Defines a team of any name that can be reused to add scores to

**AddTeamScore**("Team", "score", "Reason") -- Teamname from above, the score in Interger, A reason for the spreadsheet

**ReportScoreTeam**("Team") - Prints the Teams "score" to all

**ReportScoreTeamTopscorer**("Team") -- prints the teams top scorer and their score

**ReportScoreCoalition**("Coalition") - Prints the total of the current players scores combined on the coalition

**ReportScoreCoalitionTopscorer**("Coalition") --prints the Coalition Top Score and player name (filters by players and doesn't include Scores added to team.

Probably needs a bit more thought, but the idea is that we move scoring to a team event rather than just limtied to indicvidual performances.

**Comment by FlightControl-Master** [comment]
Let the ideas flow @thebgpikester !

**Comment by baluballa** [comment]
This can be implemented by Pivot function in XL, OOP or SQL.
