### ISSUE TITLE
CARGO: Set color of smoke

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#535]
Can't find an option for setting color of marker smoke, so hereby suggest we make one?

**Comment by FlightControl-Master** [comment]
Please do. Have a look at POSITIONABLE how it was implemented. You may want to create wrapper functions that use the POSITIONABLE methods of the self.CargoObject field.

**Comment by FlightControl-Master** [comment]
You can do a pull request, or ask for a code review first. It is not a lot of work.

**Comment by FlightControl-Master** [comment]
Pull request #537 implemented this.
