### ISSUE TITLE
RADIO - generates error when using broadcast and not all options set

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#541]
When using Broadcast but not all options set, radio.lua genearates an error. Not sure which options but specifically if SetLoop() is not set then error is generated as so. This is evident in RAD-000 mission right now as it generates that error. When SetLoop is specified no more error.

Here is the error from the DCS.log file:

> 00124.448 INFO    SCRIPTING:    104(    -1)/F:               RADIO00039.function({["StaticName"]="Russian Command Center",["ClassName"]="STATIC",})
00124.448 INFO    SCRIPTING:    120(    13)/F:               RADIO00039.SetFileName(Noise.ogg)
00124.448 INFO    SCRIPTING:    141(    14)/F:               RADIO00039.SetFrequency(108)
00124.448 INFO    SCRIPTING:    168(    15)/F:               RADIO00039.SetModulation(0)
00124.448 INFO    SCRIPTING:    184(    16)/F:               RADIO00039.SetPower(100)
00124.448 INFO    SCRIPTING:    298(    19)/F:               RADIO00039.Broadcast(nil)
00124.448 INFO    SCRIPTING:    314(    19)/T:               RADIO00039.Broadcasting from a POSITIONABLE
00124.448 ERROR   DCS: Mission script error: : [string "Scripts/Moose/Core/Radio.lua"]:315: Parameter #4 (loop) missed
stack traceback:
	[C]: ?
	[C]: in function 'radioTransmission'
	[string "Scripts/Moose/Core/Radio.lua"]:315: in function 'Broadcast'
	[string "C:\Users\tim\AppData\Local\Temp\DCS\/~mis000058D1"]:19: in main chunk

**Comment by Delta-99** [comment]
I think either wingthor or pikey used this in their mission and it fixed their problems. I'm not sure if that is confirmation of this fix or not. I've tested it myself but perhaps someone else should. Or just run the demo mission because it was broken and fixed now with this.

**Comment by FlightControl-Master** [comment]
Got a confirmation from @baluballa that this is fixed.
