### ISSUE TITLE
CONTROLLABLE: EnRouteTaskEngageTargets() defined twice

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#555]
EnRouteTaskEngageTargets() is defined twice and it looks like the 2nd one overrides the first one. I believe the 2nd definition is meant to be EnRouteTaskEngageTargetsInZone(). Should be an easy fix and I can probably do it.

Would like confirmation from @FlightControl-Master on this one.

**Comment by FlightControl-Master** [comment]
@Delta-99 if the function is the same i made a mistake. So go ahead with the change 👌

**Comment by Delta-99** [comment]
#559 Merged so consider this closed

**Comment by FlightControl-Master** [comment]
ok
