### ISSUE TITLE
Implement different classes of reference point for different task types

### ISSUE THREAD

**Issue by toppometer** [FlightControl-Master/MOOSE#556]
Players fulfilling different tasks (CAS, CAP etc.) may find it useful to have different scales of reference.  i.e. a CAP flight may find it sufficient to be told that the targets were detected x miles north of a city.  CAS attempting to support troops in contact may find it more useful to measure in terms of meters from a very specific point in that city.

To make this work, MOOSE the would require the ability to call different classes of reference point for different classes of task.

**Comment by FlightControl-Master** [comment]
I will first evaluate how much people are actually using the reference points. When there is a need, I will add this capability upon a sequent firm request 👍

**Comment by thebgpikester** [comment]
fixed
