### ISSUE TITLE
AI_A2A_DISPATCHER: A new class to create an automatic defense system.

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#562]
Using the same detection set, let AI take control, beside human players (TASK_A2A_DISPATCHER), of any threatening enemy A2A activity.

**Comment by Delta-99** [comment]
Damn, you don't stop. This sounds amazing!!!

**Comment by FlightControl-Master** [comment]
- [ ] 1. What determines when both sides are balanced? Probably a configuration setting method needs to be added. For example, blue has 4 intruders, 2 groups of 2 units each. Red has 2 groups of 3 units in CAP nearby. Those 2 groups should engage. I build the logic right now so that there are enough blue and red attackers / defenders spawned (if possible).

**Comment by FlightControl-Master** [comment]
- [ ] 3. Set a damage treshold. If a group of defenders get damaged beyond the treshold, The group goes RTB. The default treshold is that any damage will make the group RTB. However, the MD should be able to specify exactly how much damage is allowed.

**Comment by FlightControl-Master** [comment]
- [ ] 4. If there are a lot of groups in the air, the airbases get flooded with landing planes... And this stops the interceptions to be executed swiftly, as planes are holding position till the landing plane landed. Need to think about this what is the best solution.

**Comment by FlightControl-Master** [comment]
- [ ] 5. Once a defending group has destroyed all attacking planes as part of the commanded task, the defenders should orbit for a while before RTB. An orbit time setting is needed to specify how long they planes should orbit per squadron.

**Comment by FlightControl-Master** [comment]
- [ ] 6. The RTB process should be a continuous routing process, just like the Engage process. This prevents planes to RTB and cannot be controlled anymore. Planes should always have a task todo until right near the home base when returning.

**Comment by FlightControl-Master** [comment]
- [ ] 7. When friendlies are nearby a target, and an engage evaluation is done, then those friendlies that are the closest to the target need to be taken first!

**Comment by FlightControl-Master** [comment]
- [ ] 8. When a CAP plane is damaged, it should also remove itself from the attack list!

**Comment by FlightControl-Master** [comment]
- [ ] 9. Setup a parameter how many flights can be dispatched at the same time.

**Comment by FlightControl-Master** [comment]
- [ ] 10. When after a dogfight blue intruders have survived, and red defenders are near but have no task, these these red defenders should get a new task to attack the remaining intruders. In other words, any near friendly without a task, that is closer to a target than the assigned defender, should switch tasks!

**Comment by FlightControl-Master** [comment]
- [ ] 11. For CAP, the amount of attacking planes should balance the intruders (if no overhead set). When the CAP planes are in sets of 2 or more, the balancing seems to be incorrect. Needs to be checked.

**Comment by thebgpikester** [comment]
regarding 9. So important. I think some timing shoudl be enforced to stop SPAWN SPAM. It's normal for a CAP to have a "ready 5" timing, so it can depart in a scramble, but the next pair are usually 15 minutes out in real time. You don't have to enforce this exactly, but there shoudl be a DELAY in Spawn and a spawn governer to see how many planes can be airborne. Perhaps using an FSM you can define the airbase readiness. STATE "READY5", "STATE READY 15", "STATE MAXED OUT/UNABLE" and that governs the spawn per squadron. You might need an overall spawn governer too to limit planes airborne. Also need to check between squadrons too! You don't want 2 incomign planes towards Beslan, Mozdok and Vody producing 6 intercepts, you want just one airbase handling it. etc.
1) if an existing CAP is RTB, prepare the next one in 5 minutes for launch. because they would already know it is due to return.
2) If an intercept is needed, the reaction time should be slightly delayed.
3) For subsequent intercepts beyond the first, in the same squadron, it should be 15 minutes perhaps.
4) An airbase SHOULD be capable of being overwhelmed. you dont want a scenario where 15 incomign planes are met with 15 intercepts. it's not that realistic and the game would explode.

**Comment by FlightControl-Master** [comment]
- [ ] 12. Only planes which are "Returning", meaning, they have no damage, they are not without fuel, and they have sufficient arms, and they are "in control", should be evaluated to return to combat if new intruders are close by. All the rest that is to RTB should be ignored.

**Comment by FlightControl-Master** [comment]
- [ ] 13. When a choice needs to be taken to engage an CAP or a GCI, it needs to be evaluated what is further, the CAP which is airborne, or the GCI airbase... Airbase squadrons need to be taken into account into the closest defender possible. Even if it means spawning a new group into the air for intercept.

**Comment by Delta-99** [comment]
Comment on #4. I believe CGICAP has an option to spawn planes either from the airbase (on the ground) or above it. Perhaps need an option like this here too so that clutter at airbases is reduced somewhat. This could potentially be applied to RTB planes too if possible.

This certainly is not as cool or realistic BUT it does probably solve this problem until DCS can fix this properly ATC or otherwise.

Now, if this was done, how do you determine if an airbase has become inoperable? For example, I was actually testing this mission and also participating not he BLUE side. I shut down an airbase by blowing up a couple of planes taxiing. What if the runway was taking out by bombing? Can this be detected by Moose and render any take-offs from the airbase??

**Comment by FlightControl-Master** [comment]
You last question... Not an easy one and more work and complexity. If you don't mind, i would like to do things in steps. The requirement is valid. Airbase capture is another one... So when planes spawn in air, this should not be possible when the AB is destroyed... Dunno if i can check the health of an airbase lol. Otherwise i would need to detect bombs etc where they are falling but not going that route. Then we will never release... Will let this sink in a bit...

**Comment by Delta-99** [comment]
Most definitely. I would add the option to spawn in the air above the airbase first. The rest is nice to have.

**Comment by FlightControl-Master** [comment]
@Delta-99 @stonehouse, see point 4 updated.

**Comment by 457Stonehouse** [comment]
Not sure that you want to despawn aircraft in approach or just after wheels down as it destroys immersion. If the aircraft are not spawning too much and the stuck aircraft and shutdown aircraft are cleaned up promptly you should not have too much of an issue and not need to resort to this. Generally like the concepts though. Spawns in GCICAP were initial CAP either in their zone on patrol or as per specified method. Specified method was ramp, runway or some height over the base. On thebgpikester  comment re 9, we sort of discussed this and I too was concerned about the freq of CAP launches if you recall. Don't confuse CAP and Intercept flights. CAPs are pre-planned missions to patrol an area and shoot down intruders that get detected and assigned to them. In real life they don't leave their cap area unless someone gives them permission even to RTB. GCI/Alert/Intercept flights are scrambled to attack a specific threat that has been detected and can't be handled by CAP. If a CAP is assigned an intercept the script should launch a replacement (even though in real life this may not happen unless the intercept will leave their zone exposed and it would be the controllers decision AWACs or whatever) and if there are not enough CAPs or they are too far away to be useful then an alert flight is tasked.  I guess the way you are scripting things perhaps you might launch a GCI flight to address a balance issue for the CAP flight. ie 8 intruders detected, 4 a/c on CAP are tasked to intercept and 4 more are launched as a GCI. Of course this assumes you have airframes available around your squadrons.

**Comment by thebgpikester** [comment]
Part of clutter issues is dependant on the Airbase and you can design out of it. The traditional start from ramp is fine, if you spawn too many it will clog up but there shouldnt be any need for 6 departing planes at a time, if that is happening then the spawn timers need to chill a lot more.

**Comment by thebgpikester** [comment]
if you damage a runway ai know but there is no event as such, they just refuse to taxi.

**Comment by 457Stonehouse** [comment]
Thing is you don't need to spawn more CAPs than there are zones. You replace a CAP that is assigned to an intercept by launching a new CAP to head to the uncovered zone. Zones particularly for jet aircraft are large. Maybe 80-100km radius if they are circular. Most maps can't support more than 3-4 per side and if a CAP flight is 4 aircraft max you straight away have an upper limit of CAPs airborne or wanting to be. GCIs however can get out of control if there are a lot of intruder groups. The big problem is aircraft that get stuck because of a taxi accident or poor airbase ground path finding by DCS or some airfields just take a long time for a flight to taxi out from the ramp to the runway and then flights spawning in start to stack up waiting. Beslan is a bad one if the wind is in the wrong direction and it is prop aircraft. Perhaps have a concept of a FIFO queue for each airfield with a squadron attached and a gate size for the queue. So when an aircraft needs to spawn put them on the queue, first in first out. Have a max flights taxiing per base. When all units in a flight are airborne allow another to spawn. Probably can figure aircraft in approach in that idea too. So if a flight is RTB and within 5 kms of the base don't allow a new spawn.

**Comment by Delta-99** [comment]
All good points. Don't forget that there might be other activity at an airbase going on other than the AI CAPs/Intercepts so this is not a simple thing to solve. Not to mention DCS not letting flights take off at all depending on the weather / wind.

**Comment by FlightControl-Master** [comment]
When doing this development, the bottleneck for airbases seem to be:
1. During a landing of AI aircraft in RTB... Takeoff aircraft at the airbase wait and wait until the plane lands. Planes can circle and cycle around the airbase for minutes before landing. Everything stops.
2. During taxi for off... Some aircraft seem to stop without reason.
3. Airplanes collide during taxiing. Complete airbase stops working.

Another issue is... Airplanes can go RTB, and become uncontrolled... There's no event that warns of a plane going RTB. So, when a plane is RTB, they will lock airbases until they land. The problem is that it is hard to know which planes go RTB... 


A queuing mechanism won't help.

**Comment by FlightControl-Master** [comment]
Instead of spending numerous time on Normandy, they could spend a little more time on getting these issues resolved... The list is growing and growing.

**Comment by 457Stonehouse** [comment]
When you say RTB do you mean the aircraft has reached bingo fuel or no weapons state and is returning home automatically due to internal DCS rules or that they no intruder to intercept so you've sent them home?

**Comment by FlightControl-Master** [comment]
@457Stonehouse 
I do RTB in a controlled way healthy planes and also planes where the script detected damage and fuel, ammo, but those get back into combat when commanded, or, can hold in the air, and are of no issue.

It are the planes that go RTB, for whatever reason and out of control of the script:
- damage
- fuel
- Wing mate or leader damaged, other plane homes too.
- others?

Am thinkin on two things here ... Two ideas, since those planes block airbases:
- despawn those uncontrolled, where no enemy is close in the air.
- despawn near the home airport.
So no landing will be done. 

The disadvantage is that players will complain planes vanishing from their radar, count my words. And forum thread will flood...

**Comment by 457Stonehouse** [comment]
The automatic RTB on bingo fuel and RTB on no ammo are default behaviours so you should be able to set these off when you spawn a flight........but......they will then fly until they die. So you'd need to pick a value say perhaps 20% for fuel and 15% for ammo and check the status of the script spawned flights on a regular basis (might have to be an average over the group) and then do a controller.resettask and then controller.settask to send them home. That might help the situation at least a bit as you'd still have control. Perhaps a similar thing for damage ie less than a viable number of aircraft in group and/or average % damage < set value. 

I would have thought that a flight made RTB by DCS would have controller.hastask return false and if it was a script spawned group you could detect that and do a resettask and settask to send them home but probably turning off the auto RTB options would have a better chance to work. 

Unfortunately ATC for a base is still pretty bad in DCS so once a group that you had sent home for RTB reasons got within x'000 meters of their airfield you'd probably suspend spawning until they land to allow the aircraft on the ground a better change of not getting stuffed up.

**Comment by FlightControl-Master** [comment]
__The automatic RTB on bingo fuel and RTB on no ammo are default behaviours so you should be able to set these off when you spawn a flight........but......they will then fly until they die. So you'd need to pick a value say perhaps 20% for fuel and 15% for ammo and check the status of the script spawned flights on a regular basis (might have to be an average over the group) and then do a controller.resettask and then controller.settask to send them home. That might help the situation at least a bit as you'd still have control. Perhaps a similar thing for damage ie less than a viable number of aircraft in group and/or average % damage < set value.__

I am monitoring the damage and fuel levels already as part of the implementation and am sending them to base once these levels have been reached, in a controlled manner.
But I am not switching these settings off when I spawn the plane. So, yes, that helps! Thanks!

```lua
--- @param #AI_A2A self
function AI_A2A:onafterStatus()
  self:F()

  if self.Controllable and self.Controllable:IsAlive() then
  
    local RTB = false
    
    local Fuel = self.Controllable:GetUnit(1):GetFuel()
    self:F({Fuel=Fuel})
    if Fuel < self.PatrolFuelTresholdPercentage then
      self:E( self.Controllable:GetName() .. " is out of fuel: " .. Fuel .. " ... RTB!" )
      local OldAIControllable = self.Controllable
      local AIControllableTemplate = self.Controllable:GetTemplate()
      
      local OrbitTask = OldAIControllable:TaskOrbitCircle( math.random( self.PatrolFloorAltitude, self.PatrolCeilingAltitude ), self.PatrolMinSpeed )
      local TimedOrbitTask = OldAIControllable:TaskControlled( OrbitTask, OldAIControllable:TaskCondition(nil,nil,nil,nil,self.PatrolOutOfFuelOrbitTime,nil ) )
      OldAIControllable:SetTask( TimedOrbitTask, 10 )

      self:Fuel()
      RTB = true
    else
    end
    
    -- TODO: Check GROUP damage function.
    local Damage = self.Controllable:GetLife()
    local InitialLife = self.Controllable:GetLife0()
    self:F( { Damage = Damage, InitialLife = InitialLife, DamageTreshold = self.PatrolDamageTreshold } )
    if ( Damage / InitialLife ) < self.PatrolDamageTreshold then
      self:E( self.Controllable:GetName() .. " is damaged: " .. Damage .. " ... RTB!" )
      self:Damaged()
      RTB = true
    end

    -- Check if planes went RTB
    local TargetDistance = self.TargetDistance
    local ClosestTargetDistance = self.ClosestTargetDistance
    if TargetDistance then
      if ClosestTargetDistance <= 40000 then
        if TargetDistance > 40000 then
          self:E( "Lost control of group " .. self.Controllable:GetName() .. " ... RTB!" )
          self:LostControl()
          RTB = true
        end
      end
    end
    
    if RTB == true then
      self:RTB()
    else
      self:__Status( 10 ) -- Execute the Patrol event after 30 seconds.
    end
  end
end
```

**Comment by FlightControl-Master** [comment]
_I would have thought that a flight made RTB by DCS would have controller.hastask return false and if it was a script spawned group you could detect that and do a resettask and settask to send them home but probably turning off the auto RTB options would have a better chance to work._

I haven't thought of using that option though... HasTask()? hmmm... I will let that one sink in...

**Comment by FlightControl-Master** [comment]
@457Stonehouse _Unfortunately ATC for a base is still pretty bad in DCS so once a group that you had sent home for RTB reasons got within x'000 meters of their airfield you'd probably suspend spawning until they land to allow the aircraft on the ground a better change of not getting stuffed up._

Exactly, however, fortunately, if i succeed to send planes home in a controlled manner (that is, i set a route point towards the home base, every 5 km, and then reroute the plane until the home base has been reached, almost no resources are being used)... So, once the last RTB waypoint has been reached, i can despawn that plane...
And when an airplane succeeds to go RTB in an __uncontrolled__ way (because of damage), because that one is still open, then i might have a solution for that too.

What i don't want is to kick-off timers for each airplane airborne and monitor because that eats up CPU resources.

**Comment by FlightControl-Master** [comment]
- [ ] 14. messages send on/off

**Comment by FlightControl-Master** [comment]
- [ ] 15. Tactical Overview Report make an option

**Comment by FlightControl-Master** [comment]
- [ ] 16. Check coordinate RTB process... Seems the coordinate setting needs to be improved.

**Comment by FlightControl-Master** [comment]
- [ ] 17. Patrolling coordinate process to be improved to new method.

**Comment by FlightControl-Master** [comment]
- [ ] 18. Remove no borders mistake from chapter 3.

**Comment by FlightControl-Master** [comment]
This class is coming to  its end.
