### ISSUE TITLE
A2G Tasking: Completed still present in planned tasks

### ISSUE THREAD

**Issue by Mechanist11** [FlightControl-Master/MOOSE#566]
If you complet a task which is currently assigned for you or others, the task reamins in planned task regardless of complition, and you're able to select it again. If you request report on the task the task state is compleeted but you can join it again.

However, if you complet a task which is not assigned to anyone the task becomes obsolate and disapears from planned tasks. 

The completed task shall no longer apear in planned task submenu.

Recorder using Moose github masterbatch 2017.06.04

**Comment by FlightControl-Master** [comment]
@Mechanist11 what do you mean, the task remains planned? You mean, the menu did not refresh?
Normally, when a task would get completed, it would go into "complete" state, and a new task needs to be selected.

**Comment by FlightControl-Master** [comment]
@Mechanist11 This is fixed, which was the root cause of the problems!
