### ISSUE TITLE
A2G Tasking: Selecting already compleeted task cannot be aborted

### ISSUE THREAD

**Issue by Mechanist11** [FlightControl-Master/MOOSE#567]
If you select a task which was previously completed, you cannot exit from that task (abort). I become stuck and you cannot choose other task as well (this is intended). In this case you have to reconnect in the mission, or at least switch planes. This issue is link with issue #566  , due to succesfull missions is still selectable.

Recorded using Moose master batch 2017.06.04

**Comment by FlightControl-Master** [comment]
@Mechanist11 I need to prevent that a person can select a completed task. There should not be a menu option shown to join a task that is completed. I will appoach it in this way.

**Comment by FlightControl-Master** [comment]
@Mechanist11 I am trying to resimulate this issue but I can't for the moment :-( Just cannot resimulate to join a completed task.

**Comment by FlightControl-Master** [comment]
@Mechanist11 Good news! I could resimulate this reported issue!!!! Now trying to fix this one!!!!

**Comment by FlightControl-Master** [comment]
@Mechanist11 Fixed it!!!! It was a stupid stupid silly bug. Really! It is fixed now!
