### ISSUE TITLE
DCS 2.1 new function goToWaypoint should be wrapped by a future version of MOOSE

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#570]
http://wiki.hoggit.us/view/DCS_task_goToWaypoint
Ground units can now be tasked to go directly to a waypoint in DCSW 2.1. This simplifies a lot of routing and patrol type repetitive activities that were absent and on the wishlist for many years for DCS.

**Comment by FlightControl-Master** [comment]
Thanks Pikey, this is excellent news!

**Comment by FlightControl-Master** [comment]
Hi pikey...

**Comment by baluballa** [comment]
Implemented.
