### ISSUE TITLE
GROUP functions expanded

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#571]
We need extra methods in the GROUP class to do some of the following activities:

- Get the current waypoint of a group or air unit

- Determine and filter air groups from ground groups where the functions do not work on ground groups the same as in air groups

- Get a Ground groups Route (Points)

- Set a Ground groups "Mission task" with movement to point, movement to unit, movement to zone and define clearly the differences of replacing an entire route with pushing a movement Task as a Mission. Complex terminology beware!

- "Return to route" after pushing a Mission task to a ground unit which involves movement 

- "Return to route" that picks up the next waypoint before the Mission Task was pushed (ie send a group somewhere manually with a vec2 or other method, then return it it's previous route. This enables a ground unit to be commanded to go somewhere you define, then be released back to it's original route if you finished

- Documentation and demo missions of GROUP control, with capturing group waypoints, setting tasks and so on in demo missions, probably a YT tutorial too. 

There's more to this, but I forsee some development of GROUP class to better enable tighter control It is all possible to do, but DCS is a bit complex with the way it works with routes, points, waypoint, mission tasks....simply put, not easy to understand.

**Comment by baluballa** [comment]
Many things implemented.
