### ISSUE TITLE
DETECTION class accepted zones

### ISSUE THREAD

**Issue by funkyfranky** [FlightControl-Master/MOOSE#572]
DETECTION_BASE:SetAcceptZones() function gives  "attempt to call method 'IsPointVec2InZone' (a nil value)" when the a unit is detected. Might be related to the fact that IsPointVec2InZone() has been replaced by IsVec2InZone().

**Comment by FlightControl-Master** [comment]
I'll check this.

**Comment by FlightControl-Master** [comment]
Fixed
