### ISSUE TITLE
SET: Find a solution for "-" characters in names ...

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#578]
The method FilterPrefixes() will get confused when a "-" character is part of the string. I need to find a solution.

**Comment by FlightControl-Master** [comment]
@dwpenney see here the issue report!

**Comment by dwpenney** [comment]
@FlightControl-Master: I think I have a solution?

Replace (in Moose\Core\Set.lua:1234):
string.find( MooseGroup:GetName(), GroupPrefix, 1 ) 

With:
string.find( MooseGroup:GetName(), GroupPrefix:gsub ("-", "%%-"), 1 ) 

I ran this as my test/investigation code:
str = "BLUE-Test Trainer #01"
print (str)

fnd = "BLUE-Test"

print (string.find (str, fnd, 1))
print (string.find (str, fnd:gsub ("-", "%%-")))

**Comment by FlightControl-Master** [comment]
Now that is what i call help ! Thanks @dwpenney !
These small fixes are gold.

If you want you can do this change and send a pull request on master. I'll do the rest and publish the fix too!
