### ISSUE TITLE
TASKING: Show list of tasks when the menu is shown and an item needs to be selected

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#598]
In this way, people will remember which ID of the task belongs to the task details, because the people can look it up. I willl have to create a report that lists the task details of a specific task type.

**Comment by FlightControl-Master** [comment]
@everyone DCS menus have 2 kinds of menu systems, as we all know. There are *group* menus and *command* menus. 
- Group menus kind of group different child menus beneath. 
- Command menu items execute a command.

Now, I have an outstanding requirement to display automatically a message when a *group menu* is selected. Any idea how this can be done??? I need help here!
What I wanna achieve is that when you select in A2G tasking, the Assign Task => CAS menu for example, that it would automatically show the "planned task report" overview. So you would see immediately a report generated while in the menu! Then you would be able to view the overview report, and select the relevant task from the menu. Any views how this can be done?
