### ISSUE TITLE
CARGO TRANSPORT: When the carrier is in the air and near a pickup or a deployzone, it cannot board or unboard cargo.

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#610]

**Comment by The-Scifer** [comment]
The carrier being in motion and airborne doesn't prevent units from unboarding with CARGO:UnBoard().

**Comment by FlightControl-User** [comment]
Is this release 2.3? if yes, then just know cargo is being completely reworked.
