### ISSUE TITLE
Intelisense and Documention wrong for AI_A2A_Dispatchers BorderZone

### ISSUE THREAD

**Issue by robgrahamau** [FlightControl-Master/MOOSE#614]
The Intelisense/Documention is wrong on how to set up the Border zone and doesn't match the actual command, it reads that the zone should just be entered as passing the variable eg:
Dispatcher:SetBorderZone( BorderZone )
When it should be telling users to pass them as an array / list
Dispatcher:SetBorderZone({ BorderZone } )

This leads to issues if some one is coding from scratch using the API / Intelisense documentation as not passing the Zone as an Array/List will cause a nil value error in the detection code on line 614.

Lines in error are in AI.AI_A2A_Dispatcher on lines  795 - 807.
Suggest updating both the Intelisense base line to show the { } and the example as well.

**Comment by 132nd-etcher** [comment]
It seems that passing a single zone is accepted behaviour in ["Moose/Functional/Detection.lua"](https://github.com/FlightControl-Master/MOOSE/blob/master/Moose%20Development/Moose/Functional/Detection.lua#L961).

```
  function AI_A2A_DISPATCHER:SetBorderZone( BorderZone )

    self.Detection:SetAcceptZones( BorderZone )

    return self
  end
```

Where "self.Detection" is:

```
  function AI_A2A_DISPATCHER:New( Detection )

    -- Inherits from DETECTION_MANAGER
    local self = BASE:Inherit( self, DETECTION_MANAGER:New( nil, Detection ) ) -- #AI_A2A_DISPATCHER
    
    self.Detection = Detection -- Functional.Detection#DETECTION_AREAS
```

And "self.Detection:SetAcceptZones" is:

```
    --- Accept detections if within the specified zone(s).
    -- @param #DETECTION_BASE self
    -- @param AcceptZones Can be a list or ZONE_BASE objects, or a single ZONE_BASE object.
    -- @return #DETECTION_BASE self
    function DETECTION_BASE:SetAcceptZones( AcceptZones )
      self:F2()
    
      if type( AcceptZones ) == "table" then
        self.AcceptZones = AcceptZones
      else
        self.AcceptZones = { AcceptZones }
      end
      
      return self
    end

```

According to this chunk, it can be either a table, or a single value (which will be implicitly converted to a table).

Does this look OK to you? Or am I missing your point entirely ? =)

**Comment by robgrahamau** [comment]
What was happening (Sven and Myself spent 2 hrs on slack on this and i did this so we wouldn't forget) was this.. I set up the zones as listed in the documentation so

`RusAirspaceZone = ZONE_POLYGON:New("RUSSIANAIRSPACE", GROUP:FindByName("RAS")) `

and then later..

`A2ADispatcherR:SetBorderZone(  RusAirspaceZone  )`

When the mission ran we would get an error in line 614 each and every time, in Get Vector 2 
```

00341.435 INFO    SCRIPTING:    601(    -1)/F:     DETECTION_AREAS00998.function({[1]="Detected Target:",[2]="R_AWAC #1",[3]="Pilot #048",[4]=371.62666603027,[5]=0,})
00341.435 INFO    SCRIPTING: Error in SCHEDULER function:[string "Scripts/Moose/Functional/Detection.lua"]:614: attempt to call method 'IsVec2InZone' (a nil value)
00341.435 INFO    SCRIPTING: stack traceback:
    [string "Scripts/Moose/Core/Fsm.lua"]:566: in function 'IsVec2InZone'
    [string "Scripts/Moose/Functional/Detection.lua"]:614: in function <[string "Scripts/Moose/Functional/Detection.lua"]:541>
    (tail call): ?
    [C]: in function 'xpcall'
    [string "Scripts/Moose/Core/Fsm.lua"]:574: in function '_call_handler'
    [string "Scripts/Moose/Core/Fsm.lua"]:641: in function <[string "Scripts/Moose/Core/Fsm.lua"]:579>
    (tail call): ?
    [C]: in function 'xpcall'
    [string 
```

At first we thought it was an error caused by the fact that I use Client instead of User we checked that and it ended up being that I did as the documentation said I handed the border zone over as a SINGLE value and not a list.

The moment we changed the border zone to  read

`A2ADispatcherR:SetBorderZone( { RusAirspaceZone } )`

the error went away.

However a single value Would ALWAYS cause the above error Video and logs in Slack to show.

**Comment by FlightControl-Master** [comment]
@robgrahamau Fixed this issue....

See the documentation here:
http://flightcontrol-master.github.io/MOOSE/Documentation/AI_A2A_Dispatcher.html##(AI_A2A_DISPATCHER).SetBorderZone

Please adapt your mission if you want. The method accepts now both a list of ZONE_BASE derived objects or one ZONE_BASE derived object.
