### ISSUE TITLE
AI-A2A Dispatcher - More realistic Cold War responses

### ISSUE THREAD

**Issue by robgrahamau** [FlightControl-Master/MOOSE#615]
It would be nice if in the future the AI A2A dispatcher could take into account different levels of 'cold war' responses and act accordingly given that currently the situation is that you cross the border and you are fired on, when in reality you would actually get a warning, failing to leave you'd be intercepted and failing to follow orders then shot down.

In reality things would go like this:
1. A warning would be sent on Guard Frequencies (121.5AM and 243.0UHF) normally along the lines of 
"Unidentified Aircraft at <reference point> <BRA>, you are in violation of <airspace>, Turn heading <heading out> immediately.
2. If you failed to do that, then normally an Intercept would be triggered. 
3. If intercepted normally your going to be told to drop your gear and then 'escorted' to a nice landing at an Airbase where they can give you a warm welcome.. or if it's Soviet Russia they might just sit behind you and shoot even if your an Airliner.. 
4. if you make a hostile move during intercept chances are your gonna find a missile sent your way.

The timers etc could be expanded / contracted based on the actual cold war 'heat' level (an option ) as could the ROE for not doing as told etc.. a low heat level might result simply in warnings for a long time before an intercept is generated.. with the intercept craft on Return fire only ROE.. while a 'warm' cold war option might generate them quicker etc.

Suggestion on the state machine implimentation would be:
1. have it send the msg on border violation and set a timer running say 2 minutes.
2. if the AC hasn't left by then trigger an intercept on it with ROE set to return fire.
3. Once the ai ac are within a set range have another set of messages sent.. ordering the aircraft to turn maybe to the nearest Airfield? and a timer set giving them another 2 or so minutes.
4. if the ac isn't heading in that direction by the end of the timer, change the ROE to 'hot' 
if at any time at all they are attacked then ROE goes 'hot' on the target.

**Comment by baluballa** [comment]
Old
