### ISSUE TITLE
Detection Units are not detecting Units that have been spawned by the Spawn class

### ISSUE THREAD

**Issue by JohannesStrauTHBingen** [FlightControl-Master/MOOSE#617]
I tested this with the exact same units, one time with late activation spawning them with scheduledSpawning. I didn't got a Message about a new Task but when i set them up without late activation they got spotted immediately.

**Comment by FlightControl-Master** [comment]
Single player or multi player? Because i did a bug report to ED on late activated units.

**Comment by JohannesStrauTHBingen** [comment]
I've tested it in single player after i noticed that it didn't worked in mp aswell.

**Comment by FlightControl-Master** [comment]
@JohannesStrauTHBingen Were these visible at the start???

**Comment by thebgpikester** [comment]
this IS a DCS bug. the hidden variable really messes with stuff.
