### ISSUE TITLE
UTILS: Add a Knots to KM/H

### ISSUE THREAD

**Issue by robgrahamau** [FlightControl-Master/MOOSE#618]
At the moment there is no UTIL for converting explicitly from Knots - KM/H only Knots - M/S resulting in you having to do 2 conversions

UTILS.MpsToKmph(UTILS.KnotsToMps(value))

It would be easier if we could just do UTILS.KnotsToKmph(value)

**Comment by FlightControl-Master** [comment]
Please add the function and do a pull request :-)

**Comment by FlightControl-Master** [comment]
@robgrahamau I'll add you as a collaborator.

**Comment by FlightControl-Master** [comment]
@robgrahamau This is implemented and can be closed i guess.
