### ISSUE TITLE
GROUP:Respawn(Template) causes DCS world to freeze

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#623]
Error Log:

`00642.797 INFO    SCRIPTING:    908(    74)/E:               GROUP00169.GetTemplate(Test Pickup#001)
00642.797 INFO    SCRIPTING:    908(    75)/E:               GROUP00026.GetTemplate(Dummy TaskForce)
00662.818 INFO    SCRIPTING:    879(    79)/E:               GROUP00169.Respawn(9)
00662.818 INFO    SCRIPTING:    882(    79)/E:               GROUP00169.Respawn(Test Pickup#001-01)
00662.818 INFO    SCRIPTING:    890(    79)/E:               GROUP00169.Respawn({[1]=1,[2]={["alt"]=18.762195587158,["type"]="Soldier M4",["transportable"]={["randomTransportable"]=true,},["unitId"]="1000021",["skill"]="Excellent",["y"]=653203.5,["x"]=-285736.71875,["name"]="Test Pickup#001-01",["playerCanDrive"]=true,["heading"]=0,},[3]=,})
00662.818 INFO    SCRIPTING:    882(    79)/E:               GROUP00169.Respawn(Test Pickup#001-02)
00662.818 INFO    SCRIPTING:    890(    79)/E:               GROUP00169.Respawn({[1]=2,[2]={["alt"]=19.232496261597,["type"]="Soldier M4",["transportable"]={["randomTransportable"]=true,},["unitId"]="1000022",["skill"]="Excellent",["y"]=653260.9375,["x"]=-285476.46875,["name"]="Test Pickup#001-02",["playerCanDrive"]=true,["heading"]=0,},[3]=,})
00662.818 INFO    SCRIPTING:    882(    79)/E:               GROUP00169.Respawn(Test Pickup#001-03)
00662.818 INFO    SCRIPTING:    890(    79)/E:               GROUP00169.Respawn({[1]=3,[2]={["alt"]=19.235864639282,["type"]="Soldier M4",["transportable"]={["randomTransportable"]=true,},["unitId"]="1000023",["skill"]="Excellent",["y"]=653273.5625,["x"]=-285471.90625,["name"]="Test Pickup#001-03",["playerCanDrive"]=true,["heading"]=0,},[3]=,})
00662.818 INFO    SCRIPTING:    882(    79)/E:               GROUP00169.Respawn(Test Pickup#001-04)
00662.818 INFO    SCRIPTING:    890(    79)/E:               GROUP00169.Respawn({[1]=4,[2]={["alt"]=19.317447662354,["type"]="Soldier M4",["transportable"]={["randomTransportable"]=true,},["unitId"]="1000024",["skill"]="Excellent",["y"]=653183.0625,["x"]=-285446.3125,["name"]="Test Pickup#001-04",["playerCanDrive"]=true,["heading"]=0,},[3]=,})
00662.818 INFO    SCRIPTING:    882(    79)/E:               GROUP00169.Respawn(Test Pickup#001-05)
00662.819 INFO    SCRIPTING:    890(    79)/E:               GROUP00169.Respawn({[1]=5,[2]={["alt"]=19.295265197754,["type"]="Soldier M4",["transportable"]={["randomTransportable"]=true,},["unitId"]="1000025",["skill"]="Excellent",["y"]=653189.25,["x"]=-285457.21875,["name"]="Test Pickup#001-05",["playerCanDrive"]=true,["heading"]=0,},[3]=,})
00662.819 INFO    SCRIPTING:    882(    79)/E:               GROUP00169.Respawn(Test Pickup#001-06)
00662.819 INFO    SCRIPTING:    890(    79)/E:               GROUP00169.Respawn({[1]=6,[2]={["alt"]=19.387069702148,["type"]="Soldier M4",["transportable"]={["randomTransportable"]=true,},["unitId"]="1000026",["skill"]="Excellent",["y"]=653132.9375,["x"]=-285397.3125,["name"]="Test Pickup#001-06",["playerCanDrive"]=true,["heading"]=0,},[3]=,})
00662.819 INFO    SCRIPTING:    882(    79)/E:               GROUP00169.Respawn(Test Pickup#001-07)
00662.819 INFO    SCRIPTING:    890(    79)/E:               GROUP00169.Respawn({[1]=7,[2]={["alt"]=18.81307220459,["type"]="Soldier M249",["transportable"]={["randomTransportable"]=true,},["unitId"]="1000027",["skill"]="Excellent",["y"]=653267.0625,["x"]=-285706.4375,["name"]="Test Pickup#001-07",["playerCanDrive"]=true,["heading"]=0,},[3]=,})
00662.819 INFO    SCRIPTING:    882(    79)/E:               GROUP00169.Respawn(Test Pickup#001-08)
00662.819 INFO    SCRIPTING:    890(    79)/E:               GROUP00169.Respawn({[1]=8,[2]={["alt"]=18.98357963562,["type"]="Soldier M249",["transportable"]={["randomTransportable"]=true,},["unitId"]="1000028",["skill"]="Excellent",["y"]=653038.625,["x"]=-285573.3125,["name"]="Test Pickup#001-08",["playerCanDrive"]=true,["heading"]=0,},[3]=,})
00662.819 INFO    SCRIPTING:    882(    79)/E:               GROUP00169.Respawn(Test Pickup#001-09)
00662.819 INFO    SCRIPTING:    890(    79)/E:               GROUP00169.Respawn({[1]=9,[2]={["alt"]=18.668788909912,["type"]="Soldier M249",["transportable"]={["randomTransportable"]=true,},["unitId"]="1000029",["skill"]="Excellent",["y"]=653172.875,["x"]=-285774.75,["name"]="Test Pickup#001-09",["playerCanDrive"]=true,["heading"]=0,},[3]=,})
00662.820 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_CRASH",[2]={["IniUnit"]={["ClassName"]="UNIT",["UnitName"]="Test Pickup#001-01",},["IniCoalition"]=2,["initiator"]={["id_"]=16786944,},["id"]=5,["IniTypeName"]="Soldier M4",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-01",["IniCategory"]=2,["IniGroupName"]="Test Pickup#001",["time"]=59.001,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-01",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-01",[5]=-1,})
00662.820 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_CRASH",[2]={["IniUnit"]={["ClassName"]="UNIT",["UnitName"]="Test Pickup#001-02",},["IniCoalition"]=2,["initiator"]={["id_"]=16787200,},["id"]=5,["IniTypeName"]="Soldier M4",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-02",["IniCategory"]=2,["IniGroupName"]="Test Pickup#001",["time"]=59.001,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-02",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-02",[5]=-1,})
00662.821 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_CRASH",[2]={["IniUnit"]={["ClassName"]="UNIT",["UnitName"]="Test Pickup#001-03",},["IniCoalition"]=2,["initiator"]={["id_"]=16787456,},["id"]=5,["IniTypeName"]="Soldier M4",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-03",["IniCategory"]=2,["IniGroupName"]="Test Pickup#001",["time"]=59.001,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-03",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-03",[5]=-1,})
00662.822 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_CRASH",[2]={["IniUnit"]={["ClassName"]="UNIT",["UnitName"]="Test Pickup#001-04",},["IniCoalition"]=2,["initiator"]={["id_"]=16787712,},["id"]=5,["IniTypeName"]="Soldier M4",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-04",["IniCategory"]=2,["IniGroupName"]="Test Pickup#001",["time"]=59.001,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-04",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-04",[5]=-1,})
00662.823 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_CRASH",[2]={["IniUnit"]={["ClassName"]="UNIT",["UnitName"]="Test Pickup#001-05",},["IniCoalition"]=2,["initiator"]={["id_"]=16787968,},["id"]=5,["IniTypeName"]="Soldier M4",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-05",["IniCategory"]=2,["IniGroupName"]="Test Pickup#001",["time"]=59.001,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-05",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-05",[5]=-1,})
00662.823 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_CRASH",[2]={["IniUnit"]={["ClassName"]="UNIT",["UnitName"]="Test Pickup#001-06",},["IniCoalition"]=2,["initiator"]={["id_"]=16788224,},["id"]=5,["IniTypeName"]="Soldier M4",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-06",["IniCategory"]=2,["IniGroupName"]="Test Pickup#001",["time"]=59.001,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-06",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-06",[5]=-1,})
00662.824 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_CRASH",[2]={["IniUnit"]={["ClassName"]="UNIT",["UnitName"]="Test Pickup#001-07",},["IniCoalition"]=2,["initiator"]={["id_"]=16788480,},["id"]=5,["IniTypeName"]="Soldier M249",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-07",["IniCategory"]=2,["IniGroupName"]="Test Pickup#001",["time"]=59.001,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-07",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-07",[5]=-1,})
00662.825 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_CRASH",[2]={["IniUnit"]={["ClassName"]="UNIT",["UnitName"]="Test Pickup#001-08",},["IniCoalition"]=2,["initiator"]={["id_"]=16788736,},["id"]=5,["IniTypeName"]="Soldier M249",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-08",["IniCategory"]=2,["IniGroupName"]="Test Pickup#001",["time"]=59.001,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-08",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-08",[5]=-1,})
00662.825 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_CRASH",[2]={["IniUnit"]={["ClassName"]="UNIT",["UnitName"]="Test Pickup#001-09",},["IniCoalition"]=2,["initiator"]={["id_"]=16788992,},["id"]=5,["IniTypeName"]="Soldier M249",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-09",["IniCategory"]=2,["IniGroupName"]="Test Pickup#001",["time"]=59.001,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-09",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-09",[5]=-1,})
00662.827 INFO    SCRIPTING:    486(   378)/E:            DATABASE00003._RegisterGroupTemplate({[1]="Group",[2]="Test Pickup#001",[3]="Coalition",[4]=2,[5]="Category",[6]=2,[7]="Country",[8]=2,[9]="Units",[10]="Test Pickup#001-01",[11]="Test Pickup#001-02",[12]="Test Pickup#001-03",[13]="Test Pickup#001-04",[14]="Test Pickup#001-05",[15]="Test Pickup#001-06",[16]="Test Pickup#001-07",[17]="Test Pickup#001-08",[18]="Test Pickup#001-09",})
00662.874 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_BIRTH",[2]={["IniGroupName"]="Test Pickup#001",["initiator"]={["id_"]=16789504,},["id"]=15,["IniTypeName"]="Soldier M4",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-01",["IniCategory"]=2,["IniCoalition"]=2,["time"]=0,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-01",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-01",[5]=1,})
00662.875 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_BIRTH",[2]={["IniGroupName"]="Test Pickup#001",["initiator"]={["id_"]=16789760,},["id"]=15,["IniTypeName"]="Soldier M4",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-02",["IniCategory"]=2,["IniCoalition"]=2,["time"]=0,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-02",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-02",[5]=1,})
00662.876 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_BIRTH",[2]={["IniGroupName"]="Test Pickup#001",["initiator"]={["id_"]=16790016,},["id"]=15,["IniTypeName"]="Soldier M4",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-03",["IniCategory"]=2,["IniCoalition"]=2,["time"]=0,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-03",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-03",[5]=1,})
00662.878 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_BIRTH",[2]={["IniGroupName"]="Test Pickup#001",["initiator"]={["id_"]=16790272,},["id"]=15,["IniTypeName"]="Soldier M4",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-04",["IniCategory"]=2,["IniCoalition"]=2,["time"]=0,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-04",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-04",[5]=1,})
00662.879 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_BIRTH",[2]={["IniGroupName"]="Test Pickup#001",["initiator"]={["id_"]=16790528,},["id"]=15,["IniTypeName"]="Soldier M4",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-05",["IniCategory"]=2,["IniCoalition"]=2,["time"]=0,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-05",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-05",[5]=1,})
00662.881 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_BIRTH",[2]={["IniGroupName"]="Test Pickup#001",["initiator"]={["id_"]=16790784,},["id"]=15,["IniTypeName"]="Soldier M4",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-06",["IniCategory"]=2,["IniCoalition"]=2,["time"]=0,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-06",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-06",[5]=1,})
00662.882 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_BIRTH",[2]={["IniGroupName"]="Test Pickup#001",["initiator"]={["id_"]=16791040,},["id"]=15,["IniTypeName"]="Soldier M249",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-07",["IniCategory"]=2,["IniCoalition"]=2,["time"]=0,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-07",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-07",[5]=1,})
00662.883 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_BIRTH",[2]={["IniGroupName"]="Test Pickup#001",["initiator"]={["id_"]=16791296,},["id"]=15,["IniTypeName"]="Soldier M249",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-08",["IniCategory"]=2,["IniCoalition"]=2,["time"]=0,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-08",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-08",[5]=1,})
00662.885 INFO    SCRIPTING:    864(    13)/E:               EVENT00000.onEvent({[1]="S_EVENT_BIRTH",[2]={["IniGroupName"]="Test Pickup#001",["initiator"]={["id_"]=16791552,},["id"]=15,["IniTypeName"]="Soldier M249",["IniObjectCategory"]=1,["IniUnitName"]="Test Pickup#001-09",["IniCategory"]=2,["IniCoalition"]=2,["time"]=0,["IniDCSGroup"]={["id_"]=1000000,},["IniGroup"]={["GroupName"]="Test Pickup#001",["Takeoff"]={["Air"]=1,["Hot"]=3,["Runway"]=2,["Cold"]=4,},["ClassName"]="GROUP",},["IniDCSUnitName"]="Test Pickup#001-09",["IniDCSUnit"]=,["IniDCSGroupName"]="Test Pickup#001",},[3]="Test Pickup#001-09",[5]=1,})
00662.890 INFO    SCRIPTING:    475(  1154)/E:               EVENT00000.Reset({[1]="Resetting subscriptions for class: ",[2]="GROUP#000000169",})
00662.890 INFO    SCRIPTING:    475(   936)/E:               EVENT00000.Reset({[1]="Resetting subscriptions for class: ",[2]="UNIT#000000326",})
00662.890 INFO    SCRIPTING:    475(   936)/E:               EVENT00000.Reset({[1]="Resetting subscriptions for class: ",[2]="UNIT#000000330",})
00662.890 INFO    SCRIPTING:    475(   936)/E:               EVENT00000.Reset({[1]="Resetting subscriptions for class: ",[2]="UNIT#000000334",})
00662.890 INFO    SCRIPTING:    475(   936)/E:               EVENT00000.Reset({[1]="Resetting subscriptions for class: ",[2]="UNIT#000000338",})
00662.890 INFO    SCRIPTING:    475(   936)/E:               EVENT00000.Reset({[1]="Resetting subscriptions for class: ",[2]="UNIT#000000342",})
00662.890 INFO    SCRIPTING:    475(   936)/E:               EVENT00000.Reset({[1]="Resetting subscriptions for class: ",[2]="UNIT#000000346",})
00662.890 INFO    SCRIPTING:    475(   936)/E:               EVENT00000.Reset({[1]="Resetting subscriptions for class: ",[2]="UNIT#000000350",})
00662.890 INFO    SCRIPTING:    475(   936)/E:               EVENT00000.Reset({[1]="Resetting subscriptions for class: ",[2]="UNIT#000000354",})
00662.890 INFO    SCRIPTING:    475(   936)/E:               EVENT00000.Reset({[1]="Resetting subscriptions for class: ",[2]="UNIT#000000358",})
`

**Comment by FlightControl-Master** [comment]
Have you updated the field lateActivate = false ?

**Comment by baluballa** [comment]
All units involved has LateActivate sett in ME to true. All groups is spawned in game by scripting. The purpose is to make an unit adopt another groups WPs by using GetTemplate(), then UTILS.Deepcopy route and then respawn.

**Comment by FlightControl-Master** [comment]
So add:
Template.lateActivate = false
Group:Respawn( Template )

**Comment by FlightControl-Master** [comment]
@baluballa is this still valid?

**Comment by baluballa** [comment]
It happens when I pick the template from a group that was already spawned, and then re-spawned. When I picked to template from a group not spawned then tweaked the template and re-spawned it worked.

In my case it was a CARGO_GROUP w hich I wanted to pick up a route from an other group defined in ME. 
So: 
`function myTransportTask:OnAfterCargoDeployed(From,Event,To,TaskUnit,Cargo,DeployZone)
local CargoTempl =  Cargo:GetTemplate()
        local DummyTemplate = dummyGroup:GetTemplate()
        CargoTempl.lateActivation = false
        CargoTempl.route = UTILS.DeepCopy(DummyTemplate.route)
        Cargo:Respawn(CargoTempl)`
Will crash DCS. but getting template from Cargo group like `local groupy = GROUP:FindByName("Test Pickup")` then respawn cargo group with `local groupy` template  will work.

Cargo was created like this ` TestSpawnGroup = SPAWN:New("Test Pickup"):InitCleanUp(180):InitRandomizeUnits( true, 200, 50 ):OnSpawnGroup(function (MooseGroup ) 
       cargo = CARGO_GROUP:New(MooseGroup, "Task Force", "Delta Gang", 500, 100)
       end)`
So as you can see both using same template from ME

Its abit complicated, took me several test runs to figure it out. Maybe I dd wrong in first-place. IT works now, except group halts more than 2.6 km away from WP mark in ME.
