### ISSUE TITLE
A2G LL coordinates 

### ISSUE THREAD

**Issue by PorcoRosso86** [FlightControl-Master/MOOSE#624]
Tested the new A2G feature (MOOSE 2.2) When I joined the task, didn't appear the LL coordinates routing messages .

**Comment by FlightControl-Master** [comment]
Ok. The issue was that this wasn't an A2G issue, but an A2A issue.
Now players can do MGRS, LL, BR for A2G and BRAA, BULLS, LL and MGRS for A2A.
New functions have been included in release 2.2.0.pre.
You need to download new moose.lua from release to test.
