### ISSUE TITLE
InitArray() spawns units inside each other

### ISSUE THREAD

**Issue by RAFraven** [FlightControl-Master/MOOSE#625]
Using DCS 2.1 Normandy, any unit spawned with :InitArray() will spawn inside units at the same location

**Comment by FlightControl-Master** [comment]
Highly likely this is a dcs bug

**Comment by FlightControl-Master** [comment]
Works fine for 1.5.6...
![screen_170719_191511](https://user-images.githubusercontent.com/13690775/28380450-a947b9de-6cb7-11e7-9b45-7ca836369a49.jpg)

**Comment by FlightControl-Master** [comment]
@RAFraven how many units in your group?

**Comment by FlightControl-Master** [comment]
If more than one, you need to put sufficient space....

**Comment by RAFraven** [comment]
One unit
