### ISSUE TITLE
COORDINATE: Atmospheric data

### ISSUE THREAD

**Issue by funkyfranky** [FlightControl-Master/MOOSE#626]
Add wrapper function to get atmospheric data (wind, temperature, pressure) as a function of map coordinates. See DCS API singleton function "atmosphere".

**Comment by FlightControl-Master** [comment]
Suggest this to be added to the COORDINATE class as a method, that returns QFE and Wind.

**Comment by FlightControl-Master** [comment]
Temperature and pressure are returned in kelvin and pascal...
We will need to have tools to calculate between C°, F° or kelvin. Pressure in QNH?

**Comment by FlightControl-Master** [comment]
Temperature and pressure are returned in kelvin and pascal...
We will need to have tools to calculate between C°, F° or K°. Pressure in QNH?

**Comment by FlightControl-Master** [comment]
http://nl.m.wikihow.com/Kelvin-naar-Fahrenheit-of-Celsius-converteren

**Comment by FlightControl-Master** [comment]
C° = K - 273
F° = 1.8 * ( K - 273 ) + 32

**Comment by FlightControl-Master** [comment]
@funkyfranky An other thing that pops into my mind is that SETTINGS may want in the measurements and metrics section menus to switch between F° and C° and K? 
How is wind expressed? In knots?

**Comment by funkyfranky** [comment]
Yes, depending on SETTINGS it's probably best to have the default report in Celsius (metric) and Fahrenheit (imperial). Kelvin in pretty useless to report.

Pressure is a bit difficult because many different units are used. Maybe it would require a special section in the SETTINGS. But it's also very interesting because different aircraft use different pressure units. I have to check which one the ATC reports. But it could be cool to have the option which one is reported by MOOSE. I think users often need to convert between the units the ATC reports and the units their aircraft altimeter uses.
Wind should be in knots or m/s. Don't know. Have to think about all this. You're fast ;)

**Comment by FlightControl-Master** [comment]
@funkyfranky you see now why it makes a lot of sense to put new ideas and requirements here?
We can think a bit together how to design and discuss the parameters and analysis.

**Comment by funkyfranky** [comment]
BTW, the DCS ATC only reports QFE. But sometimes pilots would like to dial in QNH. So adding that option would also be helpful to some people I guess. Just saw that recently in the German forum as criticism of the DCS ATC.

**Comment by FlightControl-Master** [comment]
@funkyfranky When you're in the viggen, in A2G mode target coordinates are communicated as part of an A2G task, how would the wind direction, temperature and atmospheric pressure be communicated as part of the target briefing?

**Comment by FlightControl-Master** [comment]
@funkyfranky It is also good for helo pilots, to understand the optimal engage angle, especially wind direction.

**Comment by FlightControl-Master** [comment]
Just note that wind direction in dynamic weather was bugged, it returned 0 always.
Not sure if this is still the case.

**Comment by funkyfranky** [comment]
Need to check how it is reported in the Viggen when I get home. You get a kneeboard page with the data for all waypoints defined in the ME. Most important thing is QFE pressure. Don't know which unit they use though.

**Comment by funkyfranky** [comment]
Okay, for the pressure units we need:
inHg for the american aircraft (A-10C, F-86F)
mmHg for all russian aircraft and
mbar/hPa for the european aircraft (Hawk, M2000C)

The standard atmosphere for these units is
29.92 inHg
760 mmHg
1013.25 hPa

**Comment by funkyfranky** [comment]
Just did a quick test. Getting temperature and pressure from t,p=atmosphere.getTemperatureAndPressure(dcsvec3) works nicely.
However, w1=atmosphere.getWind(dcsvec3) (or w1=atmosphere.getWindWithTurbulence(dcsvec3)) returns only zero values for w1.x, w1.y, w1.z :(

**Comment by funkyfranky** [comment]
That was tested in DCS 2.1.1 (I'm not using 1.5.x any more).

**Comment by FlightControl-Master** [comment]
Dynamic or static weather?

**Comment by funkyfranky** [comment]
I tested in both static and dynamic weather - same result. However, Grimes says it's working for him:
https://forums.eagle.ru/showthread.php?t=190818
Maybe it's my fault. Have to carefully check again.

**Comment by funkyfranky** [comment]
Just thought about it. I'm trying to get the wind at exactly zero meters above ground level. Maybe this causes the issue. Need to try to increase the height at least a few meters and check again when I get home.

**Comment by FlightControl-Master** [comment]
That will be the issue. It would be interesting to explore from zero to 10000 meters with a 1000 meter increment. COORDINATE:GetLandHeight() returns the height of the land at the coordinate.

http://flightcontrol-master.github.io/MOOSE/Documentation/Point.html##(COORDINATE).GetLandHeight

**Comment by FlightControl-Master** [comment]
Maybe if you get it working, would you have time to extend COORDINATE and add methods for these calculations? In this way you contribute.

**Comment by funkyfranky** [comment]
Yes, sure. I'll write some functions for COORDINATE. Might take a bit of time and I'll need some guidance here and there but it sounds like fun :)

**Comment by FlightControl-Master** [comment]
No stress eh. There are plenty of examples in the code. And while adding these methods, you can test it interactively in your mission.

**Comment by funkyfranky** [comment]
Jap, was an issue because of height=0. Some meters above ground it works like a charm. In static and dynamic weather.

**Comment by FlightControl-Master** [comment]
This is superb! Yup. Yup. And now the methods :-)

**Comment by FlightControl-User** [comment]
@funkyfranky implemented all.
