### ISSUE TITLE
A2G DISPATCHER  - DESIGNATE On same menu

### ISSUE THREAD

**Issue by PorcoRosso86** [FlightControl-Master/MOOSE#627]
- [x] We need to allow DESIGNATE to place its menu under a MISSION menu. 

- [ ] Also currently DESIGNATE manu don't work properly, appear and disappear randomly

**Comment by FlightControl-Master** [comment]
OK. Will check this.

**Comment by FlightControl-Master** [comment]
@PorcoRosso86 : The menu appears and dissapears randomly is actually a DCS bug.
But I will try to fix this by generating the menu incrementally...

**Comment by FlightControl-Master** [comment]
No, I will first test if the mission placement under a mission is working for you.
When this is working, I will see if i can generate the menu incrementally.
This will not remove the menu completely and then regenerate, but only add/delete the changed items.
Note that by doing this, the sorting of the menu items may change.

**Comment by FlightControl-Master** [comment]
Test ongoing with @PorcoRosso86 ...

**Comment by PorcoRosso86** [comment]
Test N 1)
Put DESIGNATE:SetMission(mission) externally the missions object: not work

Example:
RECCE_LASER = SET_GROUP:New():FilterPrefixes( "REAPER" ):FilterStart()
RECCE_LASER_DET = DETECTION_AREAS:New( RECCE_LASER, 1000 ):FilterCategories( Unit.Category.GROUND_UNIT )
MLTATTACKER = SET_GROUP:New():FilterPrefixes("MLT"):FilterStart()
RECCE_DESIGNATION2 = DESIGNATE:New( CC_US, RECCE_LASER_DET, MLTATTACKER )	
RECCE_DESIGNATION2:SetLaserCodes({1113})
RECCE_DESIGNATION2:__Detect( -15 )
do
  local MLT1 = MISSION:New( CC_US,"briefing", 
  coalition.side.BLUE )   
  local DETECTION_AREA_MLT1 = DETECTION_AREAS:New( RECCESET_M2, 8000 )  
  MLT1_TASKMLT_DISP = TASK_A2G_DISPATCHER:New( MLT1, MLT_M1, DETECTION_AREA_MLT1 )
end
RECCE_DESIGNATION2:SetMission(MLT1)

-------------------------------------------------------------------------------------------------------------------

Test N 2)
Put DESIGNATE:SetMission(mission) inside the missions object: not work

Example:
RECCE_LASER = SET_GROUP:New():FilterPrefixes( "REAPER" ):FilterStart()
RECCE_LASER_DET = DETECTION_AREAS:New( RECCE_LASER, 1000 ):FilterCategories( Unit.Category.GROUND_UNIT )
MLTATTACKER = SET_GROUP:New():FilterPrefixes("MLT"):FilterStart()
RECCE_DESIGNATION2 = DESIGNATE:New( CC_US, RECCE_LASER_DET, MLTATTACKER )	
RECCE_DESIGNATION2:SetLaserCodes({1113})
RECCE_DESIGNATION2:__Detect( -15 )
do
  local MLT1 = MISSION:New( CC_US,"briefing", 
  coalition.side.BLUE )   
  local DETECTION_AREA_MLT1 = DETECTION_AREAS:New( RECCESET_M2, 8000 )  
  MLT1_TASKMLT_DISP = TASK_A2G_DISPATCHER:New( MLT1, MLT_M1, DETECTION_AREA_MLT1 )
  RECCE_DESIGNATION2:SetMission(MLT1) 
end

**Comment by FlightControl-Master** [comment]
I fixed this item in *master* now.
Note that missions will be set under a command center for a coalition.

**Comment by FlightControl-Master** [comment]
I have modified the syntax a bit ... But backward compatible. I added an optional parameter to DESIGNATE:New(). The last parameter can optionally be the MISSION object.
See the following example:

```lua
  local NATO_M1 = MISSION
    :New( NATO_HQ, "Destroy SAM-6","Primary","Destroy SAM-6 batteries", coalition.side.BLUE )
    :AddScoring( Score )

  -- Define the Recce groups that will detect the upcoming ground forces.
  local NATO_M1_RecceSet = SET_GROUP:New():FilterCoalitions("blue"):FilterPrefixes( "M1 NATO Recce" ):FilterStart()
  
  NATO_M1_Spawn_Reaper = SPAWN
    :New( "M1 NATO Recce Reaper" )
    :InitLimit( 1, 5 )
    :SpawnScheduled( 300, 0 )

  
  NATO_M1_ReccePatrolArray = {}
  NATO_M1_RecceSpawn_US = SPAWN
    :New( "M1 NATO Recce AH-64" )
    :InitLimit( 2, 10 )
    :SpawnScheduled( 60, 0.4 )
    :InitCleanUp( 300 )
    :OnSpawnGroup(
      function( SpawnGroup )
        local M1_ReccePatrolZoneWP = GROUP:FindByName( "M1 US Patrol Zone@ZONE" )
        local M1_ReccePatrolZone = ZONE_POLYGON:New( "PatrolZone", M1_ReccePatrolZoneWP )
        local M1_ReccePatrol = AI_PATROL_ZONE:New( M1_ReccePatrolZone, 30, 50, 50, 100 )
        NATO_M1_ReccePatrolArray[#NATO_M1_ReccePatrolArray+1] = M1_ReccePatrol
        
        M1_ReccePatrol:SetControllable( SpawnGroup )
        M1_ReccePatrol:__Start( 10 ) -- It takes a bit of time for the Recce to start
      end
     )
  
  
  -- Define the detection method, we'll use here AREA detection.
  local NATO_M1_DetectionAreas = DETECTION_AREAS:New( NATO_M1_RecceSet, 4500 )
  --M1_DetectionAreas:BoundDetectedZones()
  
  local NATO_M1_Attack = SET_GROUP:New():FilterCoalitions( "blue" ):FilterPrefixes( "M1 NATO Attack" ):FilterStart()
  
  -- Define the Task dispatcher that will define the tasks based on the detected targets.
  NATO_M1_TaskA2GDispatcher = TASK_A2G_DISPATCHER:New( NATO_M1, NATO_M1_Attack, NATO_M1_DetectionAreas )

  NATO_M1_Designate = DESIGNATE:New( NATO_HQ, NATO_M1_DetectionAreas, NATO_M1_Attack, NATO_M1 )
```

In the last line, **NATO_M1** is given as a parameter to DESIGNATE:New().

**Comment by FlightControl-Master** [comment]
It may be you see more missions in the menu under the command center 
than your group can see, but that is okay.
It also solves the Mission menu not being visible in the dispatchers when there aren't any targets detected yet.
