### ISSUE TITLE
COORDINATE: Add Marks on F10 for Groups and Coalitions

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#628]
Would be nice to be able to, from script adding Marks on F10 map. You can _show way-points, give briefings, tactical info_ and more.

**Comment by FlightControl-Master** [comment]
If you place a mark in a running mission, is there a way to retrieve it and obtain the name and the coordinates?

**Comment by baluballa** [comment]
I cannot find any getMark function or similar in hoggits documentation. If it can be removed it can be retrieved too. To create requires an unique ID.  Question is which command 8 (if available), and what about the _Marks_ made by players.

**Comment by FlightControl-Master** [comment]
Maybe there is an EVENT. We should monitor the events...

**Comment by baluballa** [comment]
That might be as solution.

**Comment by FlightControl-Master** [comment]
@baluballa if you have time, at this source (Event.lua) on the master branch

https://github.com/FlightControl-Master/MOOSE/blob/master/Moose%20Development/Moose/Core/Event.lua

1. Add on line 732 the following statement:
`self:E( { Event } )

2. Create a test mission using the dynamic loading that will use this change.

3. Run the mission, and add a mark in the map.

4. Stop the mission.

5. Paste dcs.log here...

Curious what comes out of it.

**Comment by baluballa** [comment]
Nothing comes out...

**Comment by FlightControl-Master** [comment]
Pfff. So no enquiry. Only set...

**Comment by Delta-99** [comment]
It exists now but not when you guys were discussing this. This is how Arty works.
