### ISSUE TITLE
AI A2A dispatcher - Add racetrack pattern for CAP's

### ISSUE THREAD

**Issue by 132ndNeck** [FlightControl-Master/MOOSE#632]
Would it be possible n the AI A2A dispatcher to set the CAP in a racetrack pattern between two points? If my understanding is correct, the CAP flight now flies randomly in a zone. The racetrack will normally be put where the flight is 50 % of the time, nose hot on the threat (in the direction of where they anticipate any threats, or where they are protecting). Doing it this way will also enable to AWACS on the other side to identify AI CAP's

**Comment by 132ndNeck** [comment]
Requirements:
Beeing able to set two points, where the CAP flight flies between.

(**Bonus1:** beeing able to set radar off while flying the cold leg. While flying the cold leg, the CAP flight will rely on AWACS/GCI to get information about any threat. If any threat arrives, the flight will turn radar on and fly to intercept it

**Bonus 2**: When the CAP is a 4-ship, they flight should fly so that one element (2-ship) flies hot leg, while the other element flies the cold leg. This way, the flight will have continuos coverage toward the anticipated threat area).

Example for Bonus2:
![bilde](https://user-images.githubusercontent.com/26002570/28569151-f0b0477a-7138-11e7-82c1-709ecabed920.png)

**Bonus 3**: Possibility for 2 CAP's to work together  (2x ship flights). One flight on the cold leg, while the other on hot leg, very similar to the 4ship in Bonus2 example. Biggest difference is that there are now two different flights, that can be tasked to fly to different taskings, while the 4ship will operate against a single tasking.

Example for Bonus3:
![bilde](https://user-images.githubusercontent.com/26002570/28569201-39b3eefe-7139-11e7-939c-139fb1721f7c.png)

**Comment by 132ndNeck** [comment]
**Bonus 4:** Add an option for CAP's to use aeriel refueling to stay up longer.  For example, at 50% fuel, the flight flies to the tanker to refuel.
Another variant is for a 4ship, where one element flies to refuel, while the other remain on station, and when they are back from refueling they rotate so the second element flies to refuel.

As such, in the AI A2A dispatcher, maybe add a possibility for having a tanker patrolling, supporting several CAP's. 

So the AI A2A dispatcher also dispatches support, such as AWACS and Tankers as required

**Comment by FlightControl-Master** [comment]
I've been thinking on the following... Define a new ZONE_ROUTE class that does not create a polygon but a deal task between the nodes (route). This class is polymorphic with ZONE_BASE, meaning that no code change will be required in any DISPATCH module or TASK module. It will work just like ZONE_POLYGON, but behave differently, like a route....
Especially ZONE_ROUTE:GetRandomCoordinate could be interesting. This would return a random point on the route to fly to. Or a point in sequence.... ZONE_ROUTE_SEQUENCE maybe...

**Comment by FlightControl-Master** [comment]
@132ndNeck A race track could be of any form, even diamond, star, or around a border area... Really!

**Comment by 132ndNeck** [comment]
@FlightControl-Master : regarding your comment:
"@132ndNeck A race track could be of any form, even diamond, star, or around a border area... Really!"
Yes, but from my experience from real operations, we planned the CAP's in one direction, like a racetrack. And this is why I suggested to be able to set the CAP to operate that way, so that the CAP's better can fly as they do in the real world.¨

Regarding the other comments, I think your suggestion with ZONE_ROUTE:GetRandomCoordinate(), as I doubt the real life pilots turn excatly at the same spot everytime.

But let's say we have a CAP with 20nm leg's, then the coordinate should only be taken from the last 3/4 of the leg. (In the 20nm example, a random point from the last 5 nm of the leg).

**Comment by FlightControl-Master** [comment]
- [ ] Add on the Zone module new ZONE classes that model routes as "zones".

**Comment by 457Stonehouse** [comment]
Possibly you are reinventing the wheel.........were you aware there is a waypoint action that sets up an orbit which is either circular or racetrack? Essentially for a race track orbit you place a waypoint, set the action on it and then place a second waypoint. The two waypoints define the long axis of the racetrack orbit. So for MOOSE I guess you would randomly place the first waypoint within the cap area somewhere near an edge with the waypoint action set and then place the second somewhere on the far side of the cap area. The aircraft will fly to the first waypoint and then commence a racetrack orbit until the find a target or need to RTB at bingo fuel.

**Comment by FlightControl-Master** [comment]
Hi @457Stonehouse , yes, there is the orbit task. It is a bit simplistic though.
The idea is to have a zone object that implements a route. And instead of a racetrack, you can let the planes follow a figure of your choice in terms of CAP.

**Comment by Ked57** [comment]
Can you not just add 2 waypoints so the vectore between them faces the border and then add a race track task just like in the ME but automaticaly ?

**Comment by thebgpikester** [comment]
as per my much later duplicate bug I think we should have just had the racetrack and not done complex things. Wandering around in a zone isn't how planes behave irl.

**Comment by Delta-99** [comment]
Agree with the racetrack orbit here although should be optional or perhaps the default. Although the fly randomly within a zone is NOT all that realistic I do like to use it for various missions to simulate other things other than a real CAP.

**Comment by thebgpikester** [comment]
Just had a bump from Neck on this. Remember the request is for "GCICAP" to have it's CAP's as a standard military racetrack, not to replace AI_CAP patrols or to kill other patrol types, but specifically for CAP to operate racetrack (not oval). This is MORE easily done and MORE realiistic, not less of either. There are simply two waypoints and the planes fly between them, turning in one direction. It points in the direction of enemy so they can search that direction.

From looking at FC's reply @FlightControl-User I believe he might not be aware there are two types of "Orbit" task, the first is with one waypoint and goes in a circle. The second is made of the same task but two waypoints.

I believe the purpose of GCICAP is to model a real world CAP flown by pilots, rather than a random patrol on station. If I am correct, then, the exact method would be a racetrack pattern and it's already in the game.

**Comment by Delta-99** [comment]
I would say for the first iteration to keep it super simple. You know where the **patrol** area is, you know where the **border** or suspected enemy approach is. Setup a racetrack pattern in that direction. Done.

For the more fancy stuff leave it as an enhancement request for down the road.

**Comment by thebgpikester** [comment]
Frank committed this just now.
