### ISSUE TITLE
AI G2G Dispatcher: New module request

### ISSUE THREAD

**Issue by 132ndNeck** [FlightControl-Master/MOOSE#633]
Would it be possible to create a dispatcher for the AI to handle Ground-to-ground combat?

My idea is to create a structure, with headquarter units that controls their group. Example on structure:
![bilde](https://user-images.githubusercontent.com/26002570/28570357-237c0248-713e-11e7-8896-dd2d4cbf8bd7.png)

![bilde](https://user-images.githubusercontent.com/26002570/28570370-2e310ada-713e-11e7-9fbb-f151bf18c500.png)

![bilde](https://user-images.githubusercontent.com/26002570/28570374-342458e8-713e-11e7-9ff6-945b75373c17.png)

Based on this, and some supporting units such as logistics and recon (acting as forward observers for artillery and the "main" combat forces) A combat situation can happen like this:

First, Recon moves into places on either side of the FLOT (Forward Line of Own Troops). Recon locates the enemy, and reports back to Brigade HQ, who then will dispacth the rest of the Brigade and set up or an offensive
![bilde](https://user-images.githubusercontent.com/26002570/28570433-6a5a4fe4-713e-11e7-919c-31e63a92b77d.png)

![bilde](https://user-images.githubusercontent.com/26002570/28570470-87591d96-713e-11e7-9d62-c280a6841191.png)

![bilde](https://user-images.githubusercontent.com/26002570/28570478-8d3e6d4c-713e-11e7-9b28-567145863faf.png)

As a preperation to the offensive, the artillery uses its range and starts engaging the enemy, while the "main" combat forces moves into positions:
![bilde](https://user-images.githubusercontent.com/26002570/28570505-a64835fc-713e-11e7-94f9-023703824dd9.png)

![bilde](https://user-images.githubusercontent.com/26002570/28570514-ae0e70d0-713e-11e7-91b4-6000c98a36f7.png)

One Battalion will be used as the main offensive force, while the other battalion is reserve and can reinforce the main offensive force, or can repel of any enemy attacks happening in other areas.

![bilde](https://user-images.githubusercontent.com/26002570/28570543-d9350df0-713e-11e7-8267-d619c0d897d8.png)

![bilde](https://user-images.githubusercontent.com/26002570/28570544-decc1592-713e-11e7-8805-2045694e61d0.png)

![bilde](https://user-images.githubusercontent.com/26002570/28570545-e40fa316-713e-11e7-9dab-689f3520445d.png)

![bilde](https://user-images.githubusercontent.com/26002570/28570546-e91159ea-713e-11e7-99c6-a2653d64e55b.png)

![bilde](https://user-images.githubusercontent.com/26002570/28570554-ef5d11a4-713e-11e7-8ae9-eed46c2001ff.png)

![bilde](https://user-images.githubusercontent.com/26002570/28570516-b3fbe338-713e-11e7-9a3c-b0593e7202e6.png)

**Comment by 132ndNeck** [comment]
The AI G2G dispatcher can then also be expanded, to handle defensive situations, various offensive situations, and resupply(logistical) situations.

Maybe it can also be seen in conjunction with a AI A2G Dispatcher, where the Brigade HQ, can send Air Request for an AI HQ for CAS when they are preparing/conducting offensive operations, or when they are in defensive situations. For example, various HQ's can work together in a way like this:

![bilde](https://user-images.githubusercontent.com/26002570/28570667-6db1e6d8-713f-11e7-9678-bddf6b54af4c.png)

**Comment by FlightControl-Master** [comment]
@132.neck These are some impressive concepts here... I can only say hat off. I will have to study this in more detail but this looks like a great and fun project to make and work together upon.

Can we also come up for a concept for "human" G2G task dispatcher?

**Comment by FlightControl-Master** [comment]
@gunterlund have you seen this?

**Comment by 132ndNeck** [comment]
@FlightControl-Master : 
"Can we also come up for a concept for "human" G2G task dispatcher?"
I guess it is possible, the question I guess is how low on the hierarchy the human G2G dispatcher would be convenvient to have.

I think it would be better to have the human part of it on a "higher" place in the hierarchy, where it can control on Brigade sized units, and make decisions wheter the Briagade should start an offensive (and some options on how the offensive can be conducted or for example: speed, security, surprise, support). Or if the Brigades should conduct defensive operations, and then how it should be conducted, for example: Static defense, moving/patrolling, alert state, defense in debth, defense as many areas as possible etc).
The AI should then use these injects, and the HQ at the Brigade and BN should dispatch and task the various sub-units to solve the missions they have been assigned.

In order to support this, I think we would need to bring in some objective zones, which then can be used as objectives for the vaious brigades.

**Comment by baluballa** [comment]
Overdue
