### ISSUE TITLE
AI_A2A_DISPATCHER: Overriding AI_A2A_GCICAP defaults

### ISSUE THREAD

**Issue by 457Stonehouse** [FlightControl-Master/MOOSE#636]
Currently AI_A2A_GCICAP hardcodes defaults for many of the parameters of AI_A2A_Dispatcher. It is possible to override these defaults using methods from AI_A2A_Dispatcher but for many of these cases the change must be done for each squadron or airbase or situation etc individually, meaning lots of near identical calls to the same method. Depending on what the mission builder has designed this could become a big task. It would be handy if there was a method available to override a default globally for a coalition (since AI_A2A_GCICAP is at a coalition level ie if you want the air defence network for both sides you need a red and blue instance of AI_A2A_GCICAP) and then you could use the minimum number of calls to AI_A2A_Dispatcher methods for tweaking. 

For example, the map and bases being used for the mission might be very good for allowing AI aircraft to start up on the ramp and taxi and take off so you want the default action to be a ramp start for all AI under GCICAP but the default is to start airborne. It is possible to override this by doing calls to the various set squadron takeoff methods but you need to do it for each squadron. Times two if you wanted the full landing and shut down as well.

It would be good if there was a single method that allowed you to override the GCICAP default and change it from airborne to ramp in a single line. Then at the worse case you might only need to set the method for one or two squadrons if play testing revealed a problem. This would reduce lines needed from 1 per squadron to just 1 to set the default for that aspect.

The idea applies to other defaults as well although squadron centric ones are the ones likely to benefit the most.

**Comment by FlightControl-Master** [comment]
Added default behaviour functions for AI_A2A_DISPATCHER:

    function AI_A2A_DISPATCHER:SetDefaultTakeoff( Takeoff )
    function AI_A2A_DISPATCHER:SetDefaultTakeoffFromParkingCold()
    function AI_A2A_DISPATCHER:SetDefaultTakeoffFromParkingHot()
    function AI_A2A_DISPATCHER:SetDefaultTakeoffFromRunway()
    function AI_A2A_DISPATCHER:SetDefaultTakeoffInAir()
    function AI_A2A_DISPATCHER:SetDefaultLanding( Landing )
    function AI_A2A_DISPATCHER:SetDefaultLandingAtEngineShutdown()
    function AI_A2A_DISPATCHER:SetDefaultLandingAtRunway()
    function AI_A2A_DISPATCHER:SetDefaultLandingNearAirbase()
    function AI_A2A_DISPATCHER:SetDefaultGrouping( Grouping )
    function AI_A2A_DISPATCHER:SetDefaultOverhead( Overhead )
