### ISSUE TITLE
AI_A2A_DISPATCHER: Limiting Distance/Time GCI Flights Will Engage Intruders

### ISSUE THREAD

**Issue by Invisibull** [FlightControl-Master/MOOSE#637]
Hello, I've noticed that intercepting GCI flights will fly over 100 miles to chase intruders and I'd like to have the ability to control that either via time of GCI flights or distance they can travel before they RTB.

Thx

**Comment by FlightControl-Master** [comment]
@Invisibull Just to summarize our discussion on slack:

1. By range: So the defender won't engage airplanes beyond a certain range from the home base. An API can be set there.
2. By border: So the defender won't cross the border while defending (if there is a border).

Suggest to create 4 APIs:

- [ ] Add :SetDefaultDisengageRange( DisengageRange ) -- Disengage by default beyond the specified range when engaging.
- [ ] :SetSquadronDisengageRange( DisengageRange ) -- Disengage a squadron beyond the specified range when engaging.
- [ ] :SetDefaultDisengageOnBorder( Disengage ) -- Disengage by default when crossing the border. Disengage can be true or false.
- [ ] :SetSquadronDisengageOnBorder( Disengage ) -- Disengage a squadron when crossing the border. Disengage can be true or false.

**Comment by FlightControl-Master** [comment]
@Invisibull I've sent you a demonstration mission on slack. Haven't published yet.

**Comment by FlightControl-Master** [comment]
I don't think that i am going to do a border implementation, i don't think it is the right approach and it is more CPU intensive. No need i think.

**Comment by FlightControl-Master** [comment]
@Invisibull could you test this sir? Please check.

**Comment by FlightControl-Master** [comment]
Was tesed, closing
