### ISSUE TITLE
A2A_GCICAP_XXX:SetSquadronCap add activation times.

### ISSUE THREAD

**Issue by Beamrider14** [FlightControl-Master/MOOSE#639]
Is it possible to set activation times for CAP groups. I.E. assigned to Cap zone A start at XX:XX time and subsequent missions to that CAP zone are based on the original start time.

A2A_GCICAP_Blue:SetSquadronCap( "Squadron Name", Zone, FloorAltitude, CeilingAltitude, PatrolMinSpeed, PatrolMinSpeed, EngageMinSpeed, EngageMaxSpeed, AltType, **StartTimeInSeconds** )

This would allow spacing missions out to feel more realistic.

**Comment by FlightControl-Master** [comment]
@Beamrider14 Great requirement. Let me thing a bit how to build this in. Question: would you wanna have this start time being flexible or would this just be a one time configuration for a GCICAP?

**Comment by FlightControl-Master** [comment]
You do know about the method :SetSquadronCapInterval() no?

**Comment by FlightControl-Master** [comment]
@Beamrider14 So as we discussed, this is already implemented using the :SetSquadronCapInterval() method.
