### ISSUE TITLE
AI_A2A_GCICAP: - Airfields Run out of planes after a while

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#641]
Would it be possible to increase the amount of plans per instance to 255 or even inifinte so that if a online server has a LOT of players and server runs for a long time planes will keep spawning

**Comment by FlightControl-Master** [comment]
I will look to see what it the best solution. Maybe by default "infinite" could be set as the amount of resources, and then add an API where you can limit the resources per squadron.

I think this would be the best.

- [ ] Add method: AI_A2A_DISPATCHER: SetSquadronResources( Resources )

- [ ] Add method: AI_A2A_DISPATCHER: SetDefaultResources( Resources )

Don't know yet if this is feasible. Will confirm later.

**Comment by shadowze** [comment]
Could it be feasable to add to AI_A2A_GCICAP:New  and AI_A2A_GCICAP:NewWithBorder 
A new parameter PLANE_COUNT (if not set default to 20)

**Comment by FlightControl-Master** [comment]
Sounds like a good idea, this. Yes.

**Comment by FlightControl-Master** [comment]
@shadowze This is implemented by pull request #648 . It is not yet released but can be tested on **master** branch. The test mission is AID-108 which you can find in the MISSIONS repo.


    Changed methods :New() and :NewWithBorder() for the AI_A2A_GCICAP module. A resources parameter has been added.
    By default, when Squadrons are defined using AI_A2A_DISPATCHER and AI_A2A_GCICAP the Squadron will have unlimited resources, unless the now optional Resources parameter of the :SetSquadron() method is specified.

**Comment by FlightControl-Master** [comment]
* Changed methods :New() and :NewWithBorder() for the AI_A2A_GCICAP module. A resources parameter has been added.
  * By default, when Squadrons are defined using AI_A2A_DISPATCHER and AI_A2A_GCICAP the Squadron will have unlimited resources, unless the now optional **Resources** parameter of the :SetSquadron() method is specified.

**Comment by FlightControl-Master** [comment]
@shadowze Can you test this please? Thanks!!!

**Comment by shadowze** [comment]
testing ongoing , DCS world is crashing after 1.5hr approx

**Comment by FlightControl-Master** [comment]
yeah
but this is a dcs crash
could be anything. can you drop the dcs.log here? the last 100 lines pls.

**Comment by shadowze** [comment]
Seems to work ok , left server running for 12hours , airports did not run out of planes

close out ?

**Comment by FlightControl-Master** [comment]
Ok.
