### ISSUE TITLE
AI_A2A_GCICAP - in 1.5.7 Planes will still sometimes land and park (airfield gest crowded after a while)

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#642]
Not all the time but sometimes and if a server is running a long time AI red planes will land and park and just chill out, this morning after 10hours server running found 5 aircraft parked at one field and 4 at the other

**Comment by FlightControl-Master** [comment]
@shadowze Are these exceptions or are ALL planes that land just chilling out? Normally, when a plane lands or shuts down its engine, it would be removed from the mission when the default or squadron setting is set to LandAtRunway or LandAfterEngineShutdown

**Comment by shadowze** [comment]
Unknown if all planes , limit of 20 max spawning + lots of A2A players means most of the time , the spawned AI get killed, but last night server ran from 00:00 to 10:00 ish , found situation as described in first post

Though I have witnessed AI planes touch down and dissapear shortly after

I used 
GCICAP_Red_modern = AI_A2A_GCICAP:NewWithBorder("EWR Red", "Squadron Red", "BORDER Red", { "CAP Red 1", "CAP Red 2" }, 5)

to create these groups (in mission supplied)
http://havoc-company.com/download/files/dcs/moose/Weapons_Training_v1.39.2.miz
updated

**Comment by FlightControl-Master** [comment]
Then I think the issue is with some planes that are "lost". That means, some planes somehow get "out of control". I may need to build a "scheduler" to handle those lost planes. A schedule that cleans every minute or so "lost" planes.

**Comment by FlightControl-Master** [comment]
I have good news. I found a defect in the logic where after landing it would recognize that the aircraft is "home". I am trying to fix this as we speak :-)

**Comment by FlightControl-Master** [comment]
@shadowze I think I could fix this. But need a confirmation. Can you test this please???

**Comment by shadowze** [comment]
Tested and confirmed to still be happening

Found 5 aircraft parked at one airfield and 4 at another, it is happening intermittantly because I witnessed a plane touch down and then dissapear (it was damaged pretty bad)

**Comment by FlightControl-Master** [comment]
i ran a GCICAP process here for about 3 hours, and not even one plane stranded ...

**Comment by shadowze** [comment]
I was running it for nearly 9 hours using 1.5.7 (1.5.7 is possibly the shitest DCS version ever)
Overnight in multiplayer with 10+ players connected

Could it be something inside DCS World 1.5.7 not triggering every time it is supposed to ?

**Comment by shadowze** [comment]
Update server was left running last night for 12hours, logged in this morning and some AI planes were parked on airfields (they had returned)
here is the log (with debug on)
http://havoc-company.com/download/files/dcs/moose/4.saturday.dcs.7z

**Comment by FlightControl-Master** [comment]
How many planes?

**Comment by shadowze** [comment]
4 at one airfield and 3 at the other

**Comment by shadowze** [comment]
New patch 1.5.7 DCS world tested last night, left server running for 11 hours
1st airfield has 11 landed AI planes
2nd had 4 AI landed planes
3rd had 2 AI landed planes

**Comment by FlightControl-Master** [comment]
@shadowze I found the issue, and fixed it. I will release today the fix.
The issue was with planes out of fuel doing CAP, which would return to a different airbase because they were out of control. At the landing, these weren't despawned. This is now also fixed.

**Comment by shadowze** [comment]
this bug is back again

**Comment by FlightControl-Master** [comment]
Which version of moose?
