### ISSUE TITLE
AI_A2A_GCICAP: - Planes spawn at a very low alititude (causes issues if close to coast and ridges are near by)

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#643]
Observed several AI planes spawn fly for 20 seconds and then crash straight into hillside

They spawned at Gelendzhik and after maybe 10-20 seconds crashed into ridge to NE of this airport
Witnessed this several times

REQUEST: - Make the default ALT to spawn AI aircraft to be 1000m above the airfield

thanks

**Comment by FlightControl-Master** [comment]
I will create for you a test mission. I will share and please run it to see how it behaves.

**Comment by FlightControl-Master** [comment]
I can add a method to modify the Default or Squadron altitude when planes spawn in the air.

- [ ] Add method AI_A2A_DISPATCHER:SetSquadronSpawnInAirAltitude( Altitude )

- [ ] Add method AI_A2A_DISPATCHER:SetDefaultSpawnInAirAltitude( Altitude )

**Comment by FlightControl-Master** [comment]
Fixed by pull request #646 . This can be tested on master.

**Comment by FlightControl-Master** [comment]
Added methods :SetSquadronTakeoffInAirAltitude() and :SetSquadronTakeoffInAirAltitude() in AI_A2A_DISPATCHER and AI_A2A_GCICAP.
    Modified method :SetSquadronTakeoffInAir() in AI_A2A_DISPATCHER and AI_A2A_GCICAP, adding an optional TakeoffAltitude parameter.
    Modified method :SpawnFromAirbase() in SPAWN, adding an optional TakeoffAltitude parameter.

**Comment by FlightControl-Master** [comment]
@shadowze Can you test this please? Thanks!!!

**Comment by shadowze** [comment]
I assume

AI_A2A_GCICAP:SetDefaultTakeoffInAirAltitude( 1500 )

Will set alt to 1500m above air base for all spawned aircraft if i use AI_A2A_GCICAP

**Comment by FlightControl-Master** [comment]
yep

**Comment by shadowze** [comment]
implementation tested in multiplayer 1.5.7 , observed to work correctly

**Comment by FlightControl-Master** [comment]
closing then. thanks for testing!!!
