### ISSUE TITLE
CORE_SET :FilterHasSEAD() returns none SEADable units

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#644]
SEAD units are units that has radars, and might be targeted by Anti Radiation Missiles. Search Radars, Track Radars or Early Warning Radars (EWR), and even Roland Radar and ADS.

**Comment by FlightControl-Master** [comment]
I will check this method. It can be I only check for radar presence in the dispatcher, but not in this method. Something is not cooking then!

**Comment by baluballa** [comment]
I am not sure, Had a look into this, and I am not sure if its correct, from Core.Set `--- Returns if the @{Set} has targets that can be SEADed.
-- @param #SET_UNIT self
-- @return #number The amount of SEADable units in the Set
function SET_UNIT:HasSEAD()
  self:F2()

  local SEADCount = 0
  for UnitID, UnitData in pairs( self:GetSet()) do
    local UnitSEAD = UnitData -- Wrapper.Unit#UNIT
    if UnitSEAD:IsAlive() then
      local UnitSEADAttributes = UnitSEAD:GetDesc().attributes
  
      local HasSEAD = UnitSEAD:HasSEAD()
         
      self:T3(HasSEAD)
      if HasSEAD then
        SEADCount = SEADCount + 1
      end
    end
  end

  return SEADCount
end`

**Comment by FlightControl-Master** [comment]
Ha! That is the issue!
It does not filter, we'll need to add a filter method to filter all the SEAD targets from the SET_UNIT.

**Comment by baluballa** [comment]
Exactly...

**Comment by FlightControl-Master** [comment]
Maybe there is a method like that already, no?

**Comment by baluballa** [comment]
Not sure,  Where is the actual filter algo?

**Comment by FlightControl-Master** [comment]
I think there isn't a method yet. This will need to be added. I need to check the code.

**Comment by baluballa** [comment]
The algorithm must look something like this
 if HasSEAD then
    SEADCount = SEADCount + 1
       check if already in SET, if not ADD IT
    else
       check if already in SET, if it is REMOVE IT,
  end

**Comment by FlightControl-Master** [comment]
@baluballa I am not sure that this is a valid request. I have been testing this and it works perfectly.
