### ISSUE TITLE
AI_A2A_GCICAP: - Slow flying aircraft just after spawn 1.5.7 DCS World

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#645]
I am not sure if this is an issue with MOOSE or the game 1.5.7 itself

OBSERVATIONS in Multiplayer: 
If you spawn maybe 5 aircraft , 1 will operate a normal speeds the other 4 will fly just above stall speeds (this is for JETS)
If you spawn a few WW2 aircraft they seem to be flying at a good speed (un-affected)

Unknown if this is a MOOSE or DCS World 1.5.7 issue, several complaints on ED forum regarding AI aircraft not flying fast enough in single player campaign missions

**Comment by FlightControl-Master** [comment]
Need to follow up with ED on this. Please all try to check a resolution for this issue. I noticed this problem also.

**Comment by shadowze** [comment]
Confirmed DCS bug

RESOLVED in: 1.5.7.8899
