### ISSUE TITLE
Results of yesterday multi player testing

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#653]
- [x] 1. Designation still needs work. Too many messages.
- [ ] 2. GCICAP works too, but I need to get a backup for ewr being shot from the sky.
- [ ] 3. Once the ewr is shot, defences stop. Need to get an s-300 to defend the airbase.
- [ ] 4. When a task is selected by a player, it takes 30 seconds for a player to get the menu to select the same task. Reason is that after selection, the task menu own gets cleaned. But there is not immediately a new one generated.
- [ ] 5. There is a problem when a target area is removed (destroyed), designation does not remove it from its menu....
- [ ] 6. Got a weird situation where a BAI task was cancelled because of tactical change.
- [ ] 7. Too many tasks listed in the reports. Makes the report disappear too soon.
- [ ] 8. Designate menu not showing up when changing aircraft.
- [ ] 9. Defend tankers. This should be a GCICAP tasks... SetTanker should get a CAP as,a moving zone.
- [x] 10. Problem with planes holding. RTBHold goes into a loop. Found the root cause.

**Comment by FlightControl-Master** [comment]
Found problem 10.

This is now the correct code:

```lua
local function SetTask( Controller, DCSTask )
      local Controller = self:_GetController()
      Controller:setTask( DCSTask )
    end

    if not WaitTime or WaitTime == 0 then
      SetTask( DCSTask )
    else
      self.TaskScheduler:Schedule( self, SetTask, { DCSTask }, WaitTime )
    end
```
