### ISSUE TITLE
MOOSE Feature Request: Grass airfields be added to list of airbase/FARP

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#654]
Hi Sven,
      Is it possible to get the in game placed editor object grass air field added to list of airbases that MOOSE will find ?

I would like to use it for GCICAP 

Many thanks

**Comment by FlightControl-Master** [comment]
If a grass airfield does not appear in the airbases collection, then maybe i need to search for it in the mission file ... pfff. DCS. Again half baked implementation.

**Comment by thebgpikester** [comment]
still a nope! :)
