### ISSUE TITLE
Latitude Longitude (LL) Accuracy 3 doesn't work as expected DD MM.MMM

### ISSUE THREAD

**Issue by Ramsay58** [FlightControl-Master/MOOSE#655]
Hi, I understand MOOSE player settings are Wip but thought I'd report this so it can be added to a 'To Do' list.

In the DCS F10 map co-ordinates are reported in MGRS, Lat/Long DDD°MM'SS" or Lat/Long DDD°MM.MMM'

Setting the player co-ordinate system to latitude and longitude in MOOSE enables degrees, minutes and seconds. Seconds by default have 2 decimal places (1 ft), which doesn't make sense.

1' of latitude = 1 nm (1.8km) = 60" so 1" = 100 ft (30m).

I think your intention for LL accuracy 3 was DDD°MM.MMM'

The A-10C, M-2000C and Gazelle navigation systems accept degrees and decimal minutes.

function SETTINGS:SetPlayerMenu( PlayerUnit )

A2A and A2G co-ordinate options might be
- BR/BRA
- Bullseye
-  MGRS
-  Lattitude Longitude DMS
-  Lattitude Longitude DD MM.MMM

-----------------------------------------------------
Tested in a mission based off 

- DCS 1.5.7
- A2G DYNAMIC TASK DISPATCHING - TAD 220 - Detection Types and Scoring - [Script]
- Moose for Dummies - 16. Designation of Targets
- using MOOSE ( 'Moose Generation Timestamp: 20170812_1708' )

flying a M-2000C.

![moose_20170812_1708_latlongacc3](https://user-images.githubusercontent.com/31033413/29312548-d38e19f8-81ad-11e7-93dd-21690f1e38f2.jpg)
A-10C CDU Lat Long display (DDD°MM.MMM')
![a-10c_cdu_degree_decimal_minute](https://user-images.githubusercontent.com/31033413/29312551-d72e06a4-81ad-11e7-9009-3ff0c4763393.PNG)

**Comment by FlightControl-Master** [comment]
Have you tried the LL in decimal mode?

**Comment by FlightControl-Master** [comment]
By the way Ramsay, you like this development?

**Comment by Ramsay58** [comment]
> Have you tried the LL in decimal mode?

A2G Coordinate System - Latitude Longitude (LL) Decimal On \ Off didn't appear to have an effect other than change the text message ""Settings: A2G LL format mode set to HMS for player Wolf."

Changing the LL accuracy does change the number of decimal places however.

> By the way Ramsay, you like this development?

Yes, of course. MOOSE has lots of dynamic features that I wish had been available in DCS a couple of years ago when I first started running DCS's limitations (hard coding zones, triggers and scripts).

ATM I playing with (updating) an old L-39 mission which became unplayable, as it grew to have too many targets to script 'smoke markers' and ZU-23 AAA are too small/deadly to spot visually for medium altitude bombing by a newbie. It might also work well for M-2000C laser guided bombing practice as it can't 'self lase'.

For settings, I wish MOOSE could default to the players default DCS settings and/or set them on a per aircraft/mission basis but that feature might already be available or on a wish list for the future.

**Comment by FlightControl-Master** [comment]
For the settings defaults, I am playing with the idea to save settings per player on the server. So settings become persistent.

**Comment by FlightControl-Master** [comment]
@Ramsay58 So it I understand it well, the LL accuracy comes only into play when the DDM (Degrees Decimal Minutes or DD MM.MMM) is selected, where the latter 3 MMMs can be tweaked in terms of accuracy?
When DMS is selected, accuracy is not of any relevance. Correct? Because then the accuracy is fixed.

**Comment by FlightControl-Master** [comment]
@thebgpikester have a look above too if you want.

**Comment by FlightControl-Master** [comment]
@Ramsay58 and @thebgpikester Would it be more sense to make the DDM the default format? And the DMS the format that needs to be selected then from the menu?
Maybe I can rework this a bit. I could have directly 2 different LL menu options to select from:
LL DMS
LL DDM

That would make it faster and easier for players. And only in case of LL DDM there would be precision or accuracy options. Not for DMS.

**Comment by Ramsay58** [comment]
@FlightControl-Master 
> When DMS is selected, accuracy is not of any relevance. Correct? Because then the accuracy is fixed.
Yes.

> Would it be more sense to make the DDM the default format?
It depends on the player/aircraft, the A-10C, Ka-50, SA-342M and M-2000C accept DDM co-ordinates when entering navigation information but a player using the F10 map to navigate might use any format.

DMS is usually the default, even though it doesn't make the most sense for data entry.

>... only in case of LL DDM there would be precision or accuracy options. Not for DMS.
That sounds excelent.

**Comment by FlightControl-Master** [comment]
@Ramsay58 @thebgpikester I've revised now the LL coordinate settings system.

Now the LL menu is replaced by 2 menus:

- Lon/Lat Degree Min Sec (LL DMS)
- Lon/Lat Degree Dec Min (LL DDM)

LL Accuracy menu options are only available when LL DDM. As agreed, for DMS there won't be any accuracy. Optimized the menu settings logic. 

Default menu setting is BR for A2G and BRAA for A2A.

![screen_170827_172745](https://user-images.githubusercontent.com/13690775/29751519-d4dcd1d2-8b4e-11e7-8780-e139b078e6ce.jpg)

![screen_170827_172236](https://user-images.githubusercontent.com/13690775/29751545-15f81e1a-8b4f-11e7-93c2-58f307c56752.jpg)

![screen_170827_172205](https://user-images.githubusercontent.com/13690775/29751548-1826b098-8b4f-11e7-8e5d-74ece94008e7.jpg)



I will package this and release to 2.2.pre so you can use this.
I'll put an announcement when ready.

**Comment by FlightControl-Master** [comment]
It is very interesting, and I didn't know. My geography knowledge has increased.
So 40.000km / 360 = 111, ... Divide 111 by 60 (60 minutes in one degree) gives 1.85... which is ... one sea mile???? So LL DDM MM.MMM the decimal part is to more specifically specify the location on earth, almost to the metre?

**Comment by FlightControl-Master** [comment]
https://en.wikipedia.org/wiki/Nautical_mile#Sea_mile

**Comment by Ramsay58** [comment]
Mission target co-ordinates where good, the default format was BRA and I was able to test DMS and DDM, though I didn't adjust the LL DDM decimal as it's easy enough to truncate them in my head.

To create a way point in 3D space, I also needed the targets elevation (587 ft MSL), I read that from the F10 map.

**DESIGNATE**
I did run into a problem using Designate as it uses BRA and a different naming scheme Area1, Area2, etc. to the A2G task I had joined BAI.002 (Ural mounted ZU-23). BRA is difficult to use as it is always changing. IIRC it used to use the same user preference.
![screen_170827_213044](https://user-images.githubusercontent.com/31033413/29754213-82eeef70-8b78-11e7-8bdf-584cf0ea783f.jpg)

Could DESIGNATE pickup on the active mission task?

Perhaps the A2G task manager can navigate players to the target (using BRA prompts as now), while DESIGNATE could be more FAC/9 line like and deal with the target info LL, BRA, MSL, laser code, etc. for data entry and accept requests for target marking with laser/smoke.

It's useful to see the info of the target I'm asking to have lased.

**Note:** when switching between Metric and Imperial settings the target height was reported as 0 m or 1000 ft which looks like a bug, should I create another issue report ?
![imperial_metric_height_differ_moose_2_2_pre_build_20170827_1755](https://user-images.githubusercontent.com/31033413/29754291-01f81cfa-8b7a-11e7-9613-6be61f3427b5.jpg)

**Comment by FlightControl-Master** [comment]
One more thing in the feedback:

_To create a way point in 3D space, I also needed the targets elevation (587 ft MSL), I read that from the F10 map._

Where exactly were you creating a 3D waypoint?
It there something else you need as info, like land height?

**Comment by Ramsay58** [comment]
@FlightControl-Master 

> Where exactly were you creating a 3D waypoint?

I added a target waypoint in the M-2000C PCN using latitude/longitude and the difference in height between Krasnodar (PASHKOVSKY) and Maykop (the target area).

I was testing the M-2000C HUD 3D waypoint "+" for finding targets and CCRP designation from 10,000ft to drop laser guided GBU-12's.

It wasn't particularly successful as the waypoint was usually a bit off (3000ft/500m) and the GBU-12 failed to guide to the laser spot. However the test was inconclusive as Tacview showed some strange GBU-12 behaviour or I may have been approaching from a bad direction for the GBU-12 to detect the reflected laser (random JTAC placement and ingress direction).

> Is there something else you need as info, like land height?

Target elevation in feet MSL is usually part of a JTAC 9 line, it probably shouldn't be part of A2G tasking target selection, but is needed for "by the numbers" bombing altitudes/profiles.

How targets are marked is something we probably should know before joining planned tasks - i.e. flying a UH-1H to find enemy infantry marked by laser during the day isn't useful, Su-25T needs code 1113, F-5E+M-2000C set their codes before start up, etc.

Designate covers most of the JTAC 9-line but is missing the IP ingress direction so guided weapons can track to a laser spot. I'd leave it "as is" for now and work on getting designate to work reliably i.e. target lists.

**Comment by FlightControl-Master** [comment]
_Target elevation in feet MSL is usually part of a JTAC 9 line, it probably shouldn't be part of A2G tasking target selection, but is needed for "by the numbers" bombing altitudes/profiles._

_How targets are marked is something we probably should know before joining planned tasks - i.e. flying a UH-1H to find enemy infantry marked by laser during the day isn't useful, Su-25T needs code 1113, F-5E+M-2000C set their codes before start up, etc._

_Designate covers most of the JTAC 9-line but is missing the IP ingress direction so guided weapons can track to a laser spot. I'd leave it "as is" for now and work on getting designate to work reliably i.e. target lists._

@Ramsay58 Can you raise a new request so we can discuss this item in detail?
