### ISSUE TITLE
Formations and Set Options advanced waypoint actions

### ISSUE THREAD

**Issue by 457Stonehouse** [FlightControl-Master/MOOSE#657]
Add an enhancement for A2A dispatcher and therefore also GCICAP to allow you to set a default formation and spacing (open or closed) as well as also setting the same at the squadron level. Note that these items are advanced waypoint actions but that the relevant formations type are only for non bombers. Hopefully it is just a matter of tweaking the code that creates the first waypoint of a spawned group so isn't much work.

Potentially could also add the other waypoint actions for Set Option that MOOSE does not regard as reserved (eg MOOSE likes bingo fuel RTB off so it can control RTB itself) eg turn off passing waypoint radio call,

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
