### ISSUE TITLE
Defaults

### ISSUE THREAD

**Issue by 457Stonehouse** [FlightControl-Master/MOOSE#658]
Add an enhancement for GCICAP so that the defaults are era specific. eg WW2, Post WW2, modern
Thought in mind was a new parameter to use when establishing GCICAP to indicate era and then have a table of default values with the index being the era so you could pull out a specific set of defaults and use them and reduce the amount of overrides required.

**Comment by shadowze** [comment]
+1
great idea stonehouse

**Comment by 457Stonehouse** [comment]
Oops accidently clicked close issue

**Comment by FlightControl-Master** [comment]
Indeed. Would you have suggestions which era you would model and which defaults?

Era: WWII, 1960, 1970, 1980, 1990 ?

Example:

**WWII**
- Engage Radius:  25000
- Grouping Radius: 8000
- Gci Radius: 35000
- ...

**Comment by 457Stonehouse** [comment]
Welcome back. You caught me on a work from home day so get a near instant response :)
I think for at least now you only really need 3, WW2 Korean and modern. Eventually modern might need to be split into 80-90s and now. As far as values go, apparently late war EW radar carried by an SBD (aug 1944) could see large aircraft or groups of aircraft out to 100miles so about 160000 metes. Ground based could see further. In fact the German version Freya had about a 200 km range late war in good conditions for large or groups of aircraft. I assume post war got better. Does that help you?

**Comment by FlightControl-Master** [comment]
My question is more about the radius parameters, what would be good settings.

Group radius models when a group of planes is considered a, group... 8000 meters or 20000 meters... Wwii planes weren't that fast.
Gci radius is when they would take off to engage intruders. I guess in WWII,less far than in modern. I guess 35000 meters?
Engage radius is when engaging when airborne. I guess in WWII, not further than 20000?

**Comment by 457Stonehouse** [comment]
I do think WW2 radars struggled to pick up low flying aircraft by the way. So perhaps most of the post war improvements were not in range but in ability. Maybe base it on flying speed. ie how far could a WW2 aircraft moving flat out get in time to do something. ie raid is at 6000m and is picked up 100kms away and is moving at say 300 kph which is sort of bomber speed. That's about 90m/s so a km every 11 secs and 1100 secs to get the 100 kms or 18 mins. Spitfire IXe had a top speed of about 650 kph at 21000 ft and a climb rate of about 24 m/s at 10000 ft. 6000m is about 20000ft. Anyway it would take about 6 mins for the Spitfire to get to 6000m. 650kph is about 180 m/s. So even if we did a completely inaccurate thing and said that the spits went vertical to reduce complexity and therefore only had 12 mins to intercept. That would give them an engagement range of about 120 kms. Factor in some fluff time to assign the scramble and get airborne and say 80 kms.

**Comment by 457Stonehouse** [comment]
Just on the 35000 meters for GCI even in the battle of Britain in 1940, RAF radar could see raids forming up inland from the coast of france. So I think even at Calais that is about 20 plus miles yeah? So I would 35000m is too low a value for WW2 GCI even in 1940.

**Comment by 457Stonehouse** [comment]
Engage range? is that visually acquired or meant to represent a GCI intercept? if the latter I would think more like 50km is the min. Grouping it harder. A big formation of bombers could be pretty large in terms of how many m2 it was but this has to be one size for all so probably something around the 8 kms would be about right. This might help if you consider a single 36 bomber formation as a group. See comment re B24s towards the bottom [https://aviation.stackexchange.com/questions/35051/what-were-the-typical-dimensions-of-a-ww2-us-bomber-formation](https://aviation.stackexchange.com/questions/35051/what-were-the-typical-dimensions-of-a-ww2-us-bomber-formation)

**Comment by FlightControl-Master** [comment]
Engage range: None of both. It is the range to decide whether an airborne group without an assigned task will engage with intruders or a gci will be spawned. So if a defence plane is airborne in CAP f.e., and an intruder group is 50 km away, then the engagement will happen if the engagement range is larger than 50 km. If smaller, no engagement will happen and an intercept may spawn from the nearest airbase. **may** spawn, depending on the gci radius setting.

**Comment by 457Stonehouse** [comment]
Ok so GCI ordering patrol to engage v's scrambling an intercept radius. Well I would think probably 50% of the GCI radius would be about right as a rule of thumb because basically in a real life situation it's who can get there first. So if you had 80km for a WW2 GCI radius then 40kms for the engage range sounds about right to me. I can't remember if you've got the script to the point of checking availability to influence the decision as well? eg no airframes for a intercept means have to use patrol already airborne or no CAP on station because it's enroute from somewhere and there is a GCI capable squadron close so an intercept is scrambled. I think I recall you have done that logic already.

**Comment by FlightControl-Master** [comment]
The logic is implemented. So if the engage range is too big, you'll have planes flying towards target from too far and the effectivity if the defenses is lost. If too small, too many gci are started. We'll keep 1/2 as a start then and we'll see how that goes.

**Comment by FlightControl-User** [comment]
I think this can be closed @457Stonehouse , correct?

**Comment by 457Stonehouse** [comment]
Hi Sven,
Yes agreed, you've covered the essentials of the old script I believe. Time for GCICAP to be put out to pasture.

Cheers

**Comment by FlightControl-User** [comment]
There is still the issue of airbase capture, but this is a larger scope that I'll put into release 2.4.

**Comment by FlightControl-User** [comment]
We can discuss on discord.
