### ISSUE TITLE
AI_A2A_DISPATCHER: Too many GCI spawned when CAP is not used.

### ISSUE THREAD

**Issue by FlightControl-Master** [FlightControl-Master/MOOSE#661]
What happened @thebgpikester ?

**Comment by thebgpikester** [comment]
I tried this on a dedicated server on 2.1 and got a different result! It worked as expected. So now more testing needs to be done to check!

**Comment by FlightControl-Master** [comment]
What is meant with "too many"? It is very hard to balance the amount of GCI.
There is one situation where I have seen a problem.

When a group gets detected, an area is defined in the background. That area is the "target" area and the dispatcher spawns (GCI) the amount of defender units as there are attacker units in the area.
However... When a unit flies outside of the area boundaries, and a new detection is run, then the area is "split" into two. The dispatcher will see now "two" areas. It will unfortunately spawn new GCI defenders for the new area. The GCI defenders for the old area are not transferred to the new area.

Some logic is required there to re-allocate defenders when an area is split. But it is not an easy implementation and there are hidden pitfalls.

So, as a conclusion, I will finalize and stabilize the dispatcher with the functionality as of now.
Later we can fine-tune and implement this "splitting" logic.

**Comment by thebgpikester** [comment]
The numbers were 2-3. when the number should have been one, but for some reason I didn't work on this setup again and I'm not sure it's valid right now.

However I did get this with your test MOOSE version from yesterday 28th Aug, I think it's linked to the too many CAP spawned bug and to do with the ATC issues in DCS. Ie stackign up to land or some other congestion.

**Comment by FlightControl-Master** [comment]
where you using takeoff at runway?

**Comment by thebgpikester** [comment]
Yes. I can see what you will say in return. 
No matter, I'll test in the airborne configurations to rule that out for all the recently reported A2A dispatcher issues. It would help you build a better picture of what is going on.

With the ground starts it's always my aimpoint, and from cold as it adds a realistic downtime to response timers for alert aircraft and sometimes I use these on the friendly sides too, so immersion is the key thing (for me)

**Comment by FlightControl-Master** [comment]
I don't think this issue is a showstopper at the moment. Will close this one.

**Comment by FlightControl-Master** [comment]
Reopening it, i'll put it to the future to be further checked. The implementation for this will be difficult.

**Comment by thebgpikester** [comment]
OK, still an issue in 2.1 on MOOSE version of last few days. Sometimes (and it's intermittent and ONLY after initial detections, the interceptors spam takeoffs repeatedly with nothing to do and no legitimate detections.
https://youtu.be/8FVUfLR3nlQ

It's slightly intermittent, but often happens. You need to have a detection and then no detections at least.

**Comment by thebgpikester** [comment]
[dcs - Copy.zip](https://github.com/FlightControl-Master/MOOSE/files/1302602/dcs.-.Copy.zip)
DetectionSetGroup = SET_GROUP:New()
DetectionSetGroup:FilterPrefixes( { "EWR" } ) -- Change Prefix with the start of the group names that you will use to build the collection of the EWR network.
DetectionSetGroup:FilterStart()
A2ADetection = DETECTION_AREAS:New( DetectionSetGroup, 30000 )
A2ADispatcher = AI_A2A_DISPATCHER:New( A2ADetection )
A2ADispatcher:SetTacticalDisplay( false )
A2ADispatcher:SetEngageRadius( 25000 )
A2ADispatcher:SetSquadron( "9th Fighter Squadron", AIRBASE.Nevada.Laughlin_Airport, { "9thFS" }, 12 )
A2ADispatcher:SetSquadronOverhead( "9th Fighter Squadron", .5 ) 
A2ADispatcher:SetSquadronGrouping( "9th Fighter Squadron", 1 ) -- A grouping of 1
A2ADispatcher:SetSquadronTakeoffFromRunway( "9th Fighter Squadron" )
A2ADispatcher:SetSquadronLandingAtEngineShutdown( "9th Fighter Squadron" )
A2ADispatcher:SetSquadronGci( "9th Fighter Squadron", 400, 700 )

**Comment by FlightControl-Master** [comment]
Solved ... Fixed Spawn From Runway stuff, which was the root cause.
