### ISSUE TITLE
 SPAWN - Player Can Control vehicles seems to be overridden when spawning.

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#664]
1. mission is hosted on server (NOTE not self hosted, but on a seperate PC and you connect to it)
2. I have the below code running at just after mission start
3. The first group of spawned AI are fine, once some are killed they respawn
4. These newly spawned ones now have the ability to be controlled by people (see pic)

using to keep convoys moving on a route thru the map
Spawn_Vehicle_1 = SPAWN:New( "Spawn Vehicle 1" )
  :InitLimit( 5, 600 )
  :SpawnScheduled( 40, 0 )

Picture of what I mean -> http://i.imgur.com/feyfTiy.jpg

Mission used -> http://havoc-company.com/download/files/dcs/moose/Weapons_Training_v1.40.4.no_ships.miz

**Comment by FlightControl-Master** [comment]
Ha! so, you want to prevent the "player can control" option?

**Comment by FlightControl-Master** [comment]
Is this urgent? @shadowze

**Comment by shadowze** [comment]
Ha! so, you want to prevent the "player can control"? When you switch off the player controllability in the template, and then when a vehicle is spawned, the player can control the vehicle?

Player can drive, is not ticked in the template that is spawned
SO they should not be able to set the vech speed .. but they can

No it is not that urgent

**Comment by 132nd-etcher** [comment]
I have somewhat of the opposite issue; the vehicle is supposed to be able to receive orders from any players on the F10 map ("set path" function), but vehicles spawned from a template (NOT vehicles that are activated, only the spawned ones) do not accept orders.

**Comment by FlightControl-Master** [comment]
Interesting. Some stuff to look into! I promise to investigate.

**Comment by 132nd-Entropy** [comment]
I had the same issue. It was a regular Spawn:New("unitname"):Spawn() like I did many times before. Was not able to issue any move commands to the unit. 
I had set the unit to 'RoE:hold fire' in teh mission editor. When I removed that option and restarted the mission, it worked. 
Then I went to re-set the same RoE again, and it still works. So apparently the template got 'bad' somehow.

**Comment by FlightControl-Master** [comment]
@132nd-Entropy . Am having difficulty in understanding this.

**Comment by 132nd-Entropy** [comment]
I dont understand it either, just describing what happened. The group would move when you try to move them via F10 map as Game Master. I recreated the template without any options set in the mission editor, then it worked. This seems to be a workaround for the issue 132nd-etcher is describing.

**Comment by thebgpikester** [comment]
definitely a DCS issue and still there.
