### ISSUE TITLE
Player options for coordinates should include LL decimal

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#666]
Go to F10 map then pressing CTRL-Y and seeing **MGRS**, **LL**, **LL decimal** (and XYZ not important). On top of that you have bullseye.

LL is hours minutes and seconds, which is what you have. LL decimal is used by the Gazelle and Mirage and is a decimal conversion of the "seconds" so instead of 0-59, it is 0-99. You can do this conversion roughly in your head, but likely want something more exact for bombing something.

I forgot to mention BRA. You use this too, that's also fine. Bullseye and BRAA used for A2A. for A2G it should be accurate MGRS, LL or LL decimal. They can use BULLS to refer to it, but that's not an accurate coordinate, just a reference. 

So for speed one pilot uses BULLS for a sam site or air threat to talk to another pilot, it can be found fast on a TAD. But in a **briefing** and for **JTAC** you use a precise measurement, one of the MGRS, LL or LL decimal.

For air to air, we use BRAA and Bullseye because its fast, depending on the systems in the aircraft and who is talking. For a2g the only time you might use BRA is inside a flight, or a controller referencing it. Depending on the airframe they might use a BULLSEYE method to get mile or so accuracy if they already have it identified. Elsewise, if planning an attack, they will use coords.

The only reason I asked for LL decimal is because if a Mirage or Gazelle is using a briefed target, their INS uses decimal so they compute their attack to use it. If they have hours, minutes and seconds they then really need a calculator for accuracy on a target. For a waypoint, perhaps OK to convert say 45 seconds into decimal .75 in your head.

I believe the MOOSE conversion system should have this, it's a perfect automation for a computer programme and is used still depending on nation and airframe and time period.

**Comment by thebgpikester** [comment]
OK close this, I found it

**Comment by FlightControl-Master** [comment]
@thebgpikester and @ramsay58 thanks for testing! I hope the changes are okay now! Pls feedback.
