### ISSUE TITLE
TASK_A2G_DISPATCHER: Support scenery objects in A2G tasking

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#667]
DCS has usually been all about the units. Kill tanks, kill vehicles.

But the vast majority of bombing in wartime has been versus infastructure, killing buildings and bridges. Especially prior to the advent of precision guided munitions. And we miss this.

Scenery objects are a little more tricky to pull out of DCS, but we still have capabilities to do so. There is very little reward for players to hit scenery due to the lack of obvious feedback on hit and miss other than to see this accurately from the cockpit, which is not always sensible or possible.

**Could we have the A2G tasking system create tasks against predefined scenery objects?** Track and record the destruction of scenery map objects and feed into the existing Task system? 

The likely method might be to create a very small zone in game and record the object ID's in the zone. Tie the zone to the object ID's, then record their POINT, their status (alive/dead) or the event that killed them, depending, and feedback into the tasking system?

Using the task system you can compile random lists of these zones in a table, provide random Mission descriptions like Munitions factory, Insurgent hideout, and so on and make the scenery destruction feel more worthwhile, especially if it has knock on effects to the mission progress.

**Comment by thebgpikester** [comment]
Update...what about generic flags that can trigger mission success? I understand after discussion that Tasking is linked to a detection. Therefore the solution of Mission:Complete() doesn't work. We could easily broaden the scope of tasking with this flexibility.

**Comment by TracerFacer** [comment]
This was actually the first thing I tried after the demo missions, was to get static objects to work. I was really hoping to be able to create predefined mission tasks with static objects as the targets that complete the mission objectives for the reasons you have specified. The destruction of infrastructure is a key element of most of my missions. It's great we can use the scoring system with static objects, but I would like to be able to make them the main mission objective in the tasking system as well. Thx for sending me over here from ed forums pike.

**Comment by FlightControl-Master** [comment]
Ok! I will look into this... Thanks for the explanation. It may take some time and will become part of release 2.3.

**Comment by thebgpikester** [comment]
Could we get a ticket review on this and also the Tasking being hard linked to deteted items?
