### ISSUE TITLE
AI_A2A_DISPATCHER: Bad overage of EWR network can break detection and dispatcher

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#670]
Current way it works. have an EWR in the detection list, if the intruder is detected, dispatching works OK.

First issue, if one intruder is not detected by the EWR, then no matter how close the CAP is, it cannot see the intruder and acts dumb. Seems a bit silly they are blind to their own sensors.

_"Attempt at solution, add the CAP to the detection list."_

**However**, since the CAP aircraft are not an approved sensor, it cannot share it's detection with the network. What is more....it entirely breaks the entire detection and the CAP flies around oblivious to any intruders!!!

Quite weird.

**Comment by FlightControl-Master** [comment]
I have been thinking a bit about this ...
I think you have a point. Adding the CAP to the EWR network may do a good thing...
My worry is the amount of targets that get detected by each unit running a detection.
So if a plane is running a detection, it may detect hundreds of units, and if I have 10 planes running CAP, that makes a 1000 units detected!!! Each detected unit is evaluated to be included or discarded as part of the detection set. So potentially we may run into CPU problems...

However ...

The EWR network should be radar only for GCICAP or A2A DISPATCHER! Right now, and that is hidden, the EWR network is set to detect using all methods. That includes visible. I've been testing with the functionality to use specific detection methods, like radar only, or optical etc. But filtering the detection makes it highly confusing. It seems not all units detect if you have radar only enabled.

If I get the radar only enabled, then maybe indeed I can add the CAP planes to the EWR network (hidden in the background). The amount of targets using radar only detection is minimal, and should be okay if a couple of more planes are added to the list in the detection algorithm. I just need to add the CAP prefixes to the EWR prefix list to allow CAP also to be included in the detections... The A2A_DISPATCHER class can do this in the background.

Stay tuned on this!

**Comment by FlightControl-Master** [comment]
@thebgpikester and all,

fixed the problem with CAP not engaging when there isn't any EWR coverage.
CAP are now part of the EWR and are dynamically added and deleted as CAP is spawned, destroyed, landed etc.

**Comment by thebgpikester** [comment]
Pretty good change, will mean AI never act dumb without a GCI radar covering the intruders. Must test soon.
