### ISSUE TITLE
AI_A2A_DISPATCHER: Dispatcher CAP ignores a lot of trespassing intruders

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#671]
CAP can ignore a fighter engaging them and dispatcher can pass off to GCI for no particular reason, allowing the GCI intercept to carry out the task, whilst pretty much doing nothing and patrolling.

You can also see this with Attack aircraft. Whilst an attack aircraft will intrude to airspace, dispatcher doesn;t task the CAP to engage and they remain happy and leave it.

This is with a border enabled, which cancels the AI's default desire to chase things right across the map.

**Comment by FlightControl-Master** [comment]
I have been thinking a bit about this ...
I think you have a point. Adding the CAP to the EWR network may do a good thing...
My worry is the amount of targets that get detected by each unit running a detection.
So if a plane is running a detection, it may detect hundreds of units, and if I have 10 planes running CAP, that makes a 1000 units detected!!! Each detected unit is evaluated to be included or discarded as part of the detection set. So potentially we may run into CPU problems...

However ...

The EWR network should be radar only for GCICAP or A2A DISPATCHER! Right now, and that is hidden, the EWR network is set to detect using all methods. That includes visible. I've been testing with the functionality to use specific detection methods, like radar only, or optical etc. But filtering the detection makes it highly confusing. It seems not all units detect if you have radar only enabled.

If I get the radar only enabled, then maybe indeed I can add the CAP planes to the EWR network (hidden in the background). The amount of targets using radar only detection is minimal, and should be okay if a couple of more planes are added to the list in the detection algorithm. I just need to add the CAP prefixes to the EWR prefix list to allow CAP also to be included in the detections... The A2A_DISPATCHER class can do this in the background.

Stay tuned on this!

**Comment by FlightControl-Master** [comment]
There is the "engage radius" functionality. Have you see this?

**Comment by thebgpikester** [comment]
yep. What I am testing on is a One CAP two-ship, the CAP should be the only thing around with 140km engage range and a border. The proximities are in terms of 10-20km where the CAP is ignoring engaging and leaving to the GCI. They do return fire. But don't initiate any BVR missile shots. WHich I think would make tyhe CAP pretty useless. For some reason they dont get an order to engage when the intruder trespasses

**Comment by FlightControl-Master** [comment]
Okay. Two other questions:

- Is the intruder behind a border?
- Is the CAP close to a border?
- Is the EWR detecting the intruder?

Have you tested this with the latest moose.lua version i provided on slack?

**Comment by thebgpikester** [comment]
Yes, around 40km inside.
Yes, around 40km inside - varies but the patrol zone is along the border.
I believe it is detected, as it spawns a GCI and a task comes up in the overlay.
I have been using a lot of 20-40x speed testing, not sure how or if that affects the code.

Yes, the latest version I tested twice on the same config. The only change was that it actually spawned more GCI and CAP never bothered with any of the detections, which was the opposite of the intended result.

I could do a video around lunchtime and provide configs. Pictures make more sense. Also - it's not consistent but more than 75% of occasions.

**Comment by thebgpikester** [comment]
Testing right now went quite normally and as expected. I had only one occurrence of multiple CAP and was at a "congestion" phase. I didn;t have an occurence of "CAP not engaging and using GCI intercept".
Rather than test again, I'll test with the air starts and see how it looks.
I have a concern that restarting DCS sometimes affects scripting and behaviour also... Especially after long sessions.

**Comment by thebgpikester** [comment]
Again didn't see any of this behaviour. To replicate I believe you have to A) have a CAP, B) have an intruder detected and A2A DIspatcher looking for a "customer", C) have a set of circumstances where the dispatcher chooses against CAP and instead launches a GCI. It can be where the config creates an ideal scenario for GCI, due to range at detection, or that the CAP hasn;t properly disengaged from it's previous duty and is thought to be unavailable. If you then add the airbase congestion to this you can have a circular issue with timing and spawning of GCI (or CAP). The problem may still exist given the particular scenario, but on low aircraft counts and normal use is intermittent enough (or gone in latest fix) I don;t know if you want to close this or not, can maybe monitor for a while?

**Comment by FlightControl-Master** [comment]
As I said, i fixed a lot of stuff in the moose.lua i just sent you. So it looks promising.
Are the CAP spawing to the correct amount as specified?

**Comment by FlightControl-Master** [comment]
I will close this issue. @thebgpikester . We just need to have a good EWR coverage.
