### ISSUE TITLE
Designate reports Vehicles at 0 metre or 1000ft height depending on units preference setting

### ISSUE THREAD

**Issue by Ramsay58** [FlightControl-Master/MOOSE#673]
Designate reports detected vehicle heights as 0 metres using MOOSE's metric user preference.
![designate_height_bug_vehicles_reported_at_0m_screen_170827_211152](https://user-images.githubusercontent.com/31033413/29891891-99370cba-8dc4-11e7-8dd2-21a2a121d140.jpg)

However if I use the Imperial setting - vehicle heights are reported as 1000 ft, the strange thing about this bug is that infantry are as reported as being at 0 ft?
![designate_height_bug_vehicles_reported_at_1000ft_infrantry_at_0ft_screen_170830_134818](https://user-images.githubusercontent.com/31033413/29890996-7869eff0-8dc1-11e7-89e5-d6700d4f57a4.jpg)

IMHO it'd be better if DESIGNATE reported height above MSL for ground targets or not at all, it should be a given that infrantry or vehicles are on the ground at 0m (0ft).

DCS 1.5.7
MOOSE build timestamp: 20170830_0932

**Comment by FlightControl-Master** [comment]
I need to remove the rounding for an A2G context of height.
More precision is needed. Understood.
