### ISSUE TITLE
SET_CLIENT: only alive players?

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#682]
Delta99 wrote on slack: I see that SET_CLIENT is supposed to include only ALIVE units according to the documentation on ForEachClient() but I don't see where it is implementing that. Is that documentation correct?

**Comment by FlightControl-Master** [comment]
Implement SET_PLAYER

**Comment by FlightControl-Master** [comment]
@Delta-99 is this still a valid issue?

**Comment by Delta-99** [comment]
I think so. But low priority.
