### ISSUE TITLE
Task_A2G attempting to use Coordinate:GetX()

### ISSUE THREAD

**Issue by dwpenney** [FlightControl-Master/MOOSE#688]
In Task_A2G.lua (and Task_A2A.lua) the function Fsm:onafterRouteToTarget() gets the coordinate of the first unit in the target group. This is a COORDINATE object. It then attempts to access the X and Y values though GetX(), GetY() and GetZ() calls but the COORDINATE object does not have these functions.

The line causing the error is this one: Task_A2G.lua (line 145)
```
self:T( { TargetCoordinate = Coordinate, Coordinate:GetX(), Coordinate:GetY(), Coordinate:GetZ() } )
```

It is possible that the intent was to use a POINT_VEC2 or POINT_VEC3 object instead (or COORDINATE was intended to have some functionality that it does not currently have). This is also a trace/debug message so I am not sure if it is a simple fix to just remove the calls to GetX(), GetY() and GetZ() or if some other part of the code requires these functions/values from a COORDINATE object.

**Comment by FlightControl-Master** [comment]
I saw it too!
I fixed it in the latest push to master. Can you retry?

**Comment by dwpenney** [comment]
Looks good! I was only able to test if briefly but I did not see the error occur. Wooo!

**Comment by FlightControl-Master** [comment]
Very good. I am deeply again into tasking. Trying to get this briefing done using the markings.
It is not so easy. How to calculate the target position of a set of units, including average velocity and global heading.... hahaha.
Especially the heading, if an observation results in all targets driving towards a joint point in the center of the vicinity or all targets driving in a circle. So the global heading cannot be determined if:
1. there aren't any moving vehicles.
2. there are moving vehicles, which are not driving according the global heading.
