### ISSUE TITLE
DCS-BUG-8 - Late activated ground units that get activated don't move... 

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#693]
https://forums.eagle.ru/showthread.php?p=3244337#post3244337

Hi,

DCS 1.5.6

In a client/server setup, client connected to server, there is an issue with ground late activated units that get activated.

So, when you have a running connection to a server, in a running mission, and a late activated ground unit gets activated, it shows on the server as activated and you see it running on the map and in external view.

But on the client, the unit just stays where it is. It does not move.

There is no indication of movement at all on the client side. Nothing.
You don't see it on the map, and you don't see it in external view as
moving.

When you have the late activated ground unit with flag "show before active" set, you see it, but it still does not move!

If you then disconnect the client, and rejoin the client, then you see the unit moving!!!

This is a quite inconvenient error! Can somebody at ED look at this issue please? I can run a test mission if you want. I mean, people wanna see ground units moving, no? Even if they were late activated or not.

@Grimes are you aware of this error?

Sven

**Comment by FlightControl-Master** [comment]
Sorry for being a pain , but let me post this bug demonstration mission.

There IS a problem with late activation, in multi player.


Please download the attached test mission, and follow the following test procedure.

The test mission contains an infantry to observe tanks in external view. 4 SA-6 combinations are deployed, each having an SA-6 STR and a SA-6 LN. The SA-6 STR should start turning when it is alive.

This is the test mission setup:

- SA-6 TANK A: Not late activated.
- SA-6 TANK B: Late activated, and activated using Controller:setOnOff( true )
- SA-6 TANK C: Late activated, activated using trigger.action.activateGroup( ... )
- SA-6 TANK D: Late activated and with a route point, activated using trigger.action.activateGroup( ... )

The test results should be that ALL 4 tanks should have running radars and should be operational after the scripts have run.
The script runs after 30 seconds.

Code:

TANK_B = Group.getByName( "TANK B" )
TANK_B_CONTROLLER = TANK_B:getController()
TANK_B_CONTROLLER:setOnOff( true )

TANK_C = Group.getByName( "TANK C" )
trigger.action.activateGroup( TANK_C )


TANK_D = Group.getByName( "TANK D" )
trigger.action.activateGroup( TANK_D )

trigger.action.outText( "Now TANK B, C and D should also start turning their RADAR", 30 )

A/ In a SINGLE PLAYER setup:

- Run the mission.
- Select Game Master slot on red coalition.
- Select on the map the INFANTRY and go EXTERNAL VIEW (F7).
- Observe the SA-6. All the radars of the 4 SA-6 STR should turn.

Only 3 do!

B/ In a MULTI PLAYER setup:

- Run the mission on a server DCS, ensure the mission will only run when a client logs into the server.
- Open the client DCS, and select the server DCS in multi player.
- Select Game Master slot on red coalition.
- Select on the map the INFANTRY and go EXTERNAL VIEW (F7).
- Observe the SA-6. All the radars of the 4 SA-6 STR should turn.

BUT! there is an issue:

1. Only TANK A radar is turning.
2. TANK B, C and D have no turning radars.
3. TANK D is not moving.

Now do the following:

- Exit the client DCS.
- Open the client DCS, and select the server DCS in multi player.
- You'll see TANK A, B and TANK D radars turning
- TANK D is moving.

Please have the ED team check this out too.

Thanks
Sven
