### ISSUE TITLE
DCS: lua predicates not functional in the mission editor

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#694]
Lua Predicates not functional in the mission editor

ID at DCS: 32145

Description: This one i find hard to believe, but it is true. The LUA predicate functionality is completely NOT WORKING in DCS world. Try to add an evaluation function on a group waypoint action... Good luck.

Consequence: Missions using LUA predicates are not working properly. Can you please have this looked at?

References of posts on the forum:

http://forums.eagle.ru/showthread.ph...=lua+predicate

**Comment by thebgpikester** [comment]
Been like that for years, fyi :)

**Comment by fuxx** [comment]
https://forums.eagle.ru/showthread.php?t=201188&highlight=LUA+PREDICATE seems to be fixed in 2.5 👍

**Comment by FlightControl-Master** [comment]
REALLY?????? Amazing!!!!

**Comment by FlightControl-User** [comment]
This is fixed in version 2.5.
