### ISSUE TITLE
DCS-BUG-2 - Destroy units at S_EVENT_CRASH or S_EVENT_DEAD

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#695]
https://forums.eagle.ru/showthread.php?t=206066

Crashed air units cannot be destroyed using Group.destroy(AirGroup) or Unit.destroy(AirGroup)

ID at DCS: don't know.

Description: <URGENT>When an air unit has crashed ( a S_EVENT_CRASH has occurred ), and the unit is burning, units cannot be destroyed anymore. These units will keep being visible and will keep burning... This in single and multi player.
IMPORTANT Note: The destroy() functions for burning groups and units worked on previous DCS world versions (i believe it worked on DCS world 1.2.6). And then suddenly this stopped working completely.

Consequence: I believe this is an important bug to look at. Some of our scripting talents have build a cleanup function to keep or cleanup airbases clean in running multi-player missions. When units crash at airbases, the complete airbase will stop functioning. By monitoring the health status of units at these airbases using lua scripting, and destroying crashed or dead units, the airbase used to be able to keep on running and operating normally. Please have a look at this bug, it is a really annoying thing and i believe most of the mission design will want to have this fixed.

References of posts on the forum:

http://forums.eagle.ru/showthread.ph...estroy+burning

**Comment by FlightControl-Master** [comment]
Track post on ED Forums:

https://forums.eagle.ru/showthread.php?p=3244338#post3244338

**Comment by FlightControl-Master** [comment]
Other:

https://forums.eagle.ru/showthread.php?t=153773&highlight=destroy+burning
