### ISSUE TITLE
A2G_TASKING: Embed Designate feature into accepted missions

### ISSUE THREAD

**Issue by Mechanist11** [FlightControl-Master/MOOSE#702]
To reduce clutter and confusion between Designate and A2G tasking if designate (designator) is available on the accepted task vicinity separate designate menu option shall be removed and enbeded into the A2G tasking.

![image](https://user-images.githubusercontent.com/19891419/30660027-dbfe7066-9e3f-11e7-91a4-0e87e012b7f8.png)

**Comment by Mechanist11** [comment]
Sure, take your time. Just bringing up some ideas.

**Comment by FlightControl-Master** [comment]
The idea is great. How is A2G working if I may ask.

An Overall experience... Maybe do a report on the MOOSE thread on the ED forums.
The whole idea of this module came from you, so how do you see this coming together?

**Comment by Ramsay58** [comment]
@FlightControl-Master 
>How is A2G working if I may ask.

Designate is working well when flying daylight missions with plenty of recon.

At night, I'm having issues with the designate menu - to get targets marked - I'm testing using the A-10C, SA-342M and M2A2 Bradley in DCS 1.5.7, it's hard to tell if it's a menu issue or something else as it can work reliably. 

See #700 for more detail

**Comment by Mechanist11** [comment]
The A2G tasking it self is an awsome tool and works fine, we use it regurarly in my squad. Good for training and for missions as well. It gets a bit practise to get used to it, but it is really a dream come true.

Instead of a comment in the forum we shall do a several step action.
1. Make a video, a tutorial using the A2G tasking as a client, not as a mission maker.
2. Publish missions incorporating A2G testing.
3. Create an own thread like A2G dynamic multiplayer missions, this should be catchy enough.
4. Post the video and the missions in the thread.

I don't know how to make a video but I sure do how to make missions. I can prepare a 5 mission pack with different uses of the A2G tasking. Will take about month to assamble the pack.

**Comment by FlightControl-Master** [comment]
OK! good!

I can do the video. We can record in a teammeeting and talk to each other, and we can then setup a scenario for the video... a coop mission. i will fly a ka-50.

**Comment by FlightControl-Master** [comment]
i have a mission ready.

**Comment by FlightControl-Master** [comment]
part of the demo is to brief the team. I have an idea, as was suggested by Dunham.

**Comment by FlightControl-Master** [comment]
[A51 - Area 51 - In Progress - The hidden secret.zip](https://github.com/FlightControl-Master/MOOSE/files/1321799/A51.-.Area.51.-.In.Progress.-.The.hidden.secret.zip)

**Comment by Mechanist11** [comment]
I'm back from vacation, I'll start to do some replayeble missions promoting this module.

**Comment by FlightControl-Master** [comment]
Cool. Take it step by step ... If you have questions, call in on slack.
