### ISSUE TITLE
Feature request - smaller MOOSE.lua file (minus any comments)

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#703]
Hi Sven,
        Would it be possible when you are creating versions of the moose.lua file that there is a smaller one we could download  as well that has no comments in it (to help make mission files sizes smaller)

Thanks

**Comment by FlightControl-Master** [comment]
Been thinking the same.

I think that when i generate the moose.lua, i could do a unix-like command to delete all comments.

Something like grep, but i don't know the unix or windows command to actually delete results of regular expressions. Any views on that?

**Comment by shadowze** [comment]
sounds good
there is this http://webserver2.tecgraf.puc-rio.br/~lhf/ftp/lua/#lstrip

but I dont know much about lua to be honest

**Comment by FlightControl-Master** [comment]
I installed cgywin.
The grep command is: **grep -v "\-\-.*" Moose.lua**

Now I need to add this to the Moose generation process...
Which is somewhat a challenge... Using windows, stupid windows.

**Comment by Delta-99** [comment]
I was going to point you here - https://stackoverflow.com/questions/17392869/how-to-print-a-file-excluding-comments-and-blank-lines-using-grep-sed

Lots of different examples. Yours seems overly simplified in that maybe it will delete more than you want BUT I can't think of any situations so maybe it is good!!! :)

Just thought of one. I think it will delete legitimate lines that have comments on the same line as code. So you'll need a better expression.

**Comment by FlightControl-Master** [comment]
done the job

**Comment by shadowze** [comment]
thanks for doing this, I really appreciate it  .....
But I should have been more explicit in what I was after

I was looking for 2 versions to be available in the download section
1. Full normal version (with comments - for making stuff with, kinda reference version)
2. Compact (lite) version that would be included in final versions of missions

**Comment by FlightControl-Master** [comment]
Why #1?

**Comment by FlightControl-Master** [comment]
I will close this one.
