### ISSUE TITLE
Feature request - scoring - user underscore in filenames instead of space

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#708]
I would like to have _ (under scores) used instead of spaces in the filenames for the output file

**Comment by FlightControl-Master** [comment]
Understood. will look into this.

**Comment by FlightControl-User** [comment]
Is this an urgent requirement?

**Comment by FlightControl-User** [comment]
@shadowze is this an urgent requirement???

**Comment by shadowze** [comment]
nope, take your time
