### ISSUE TITLE
CGO Feature Request - Fast Roping

### ISSUE THREAD

**Issue by Fargo007** [FlightControl-Master/MOOSE#714]
It would be fantastic to have a capability to fast rope troops from a helicopter.   

Wishes of how it could work might be:

> 
> 
> local FastRopeGroup = GROUP:FindByName( "FastRopers" )
> 
> local FastRopeCargo = CARGO_GROUP:New( FastRopeGroup, "SealTeam1", " Shooters", 20 )
> 
> local CargoCarrier = UNIT:FindByName( "TransportHelo1" )
> 
> FastRopeCargo:Board( CargoCarrier, 20 )
> 
> -- Set the rope length at which the troops will fast rope down.
> -- For example here, they will rope down at 10 meters with an allowable ceiling of 5
> FastRopeCargo:SetRopeLength(10,5)
> 
> -- Set the fast rope velocity.  Here the helo is required to be between 0 and 2 KM/h for the troops 
> -- to fast rope out.  
> 
> FastRopeCargo:SetVelocity(0,2)
> 
> -- Set the interval at which the troops will fast rope down.  
> -- Here they will exit one every five seconds
> 
> function FastropeCargo:OnEnterLoaded()
>   self:__FastRopeExit( 5 )
>   self.OnEnterLoaded = nil
> end
> 

---

The holy grail of this would be to have them be able to:

1 - Remain on a rooftop where they were dropped off:

and/or

2 - Proceed to a point to accomplish an objective.

**Comment by FlightControl-Master** [comment]
OK. we will look at this when working on cargo transportation.
