### ISSUE TITLE
SpawnInZone - Randomize Position TRUE - Currently missing ALTITUDE Atributes

### ISSUE THREAD

**Issue by deadlyfishes** [FlightControl-Master/MOOSE#719]
I'm trying to utilize this SPAWN function:

SpawnInZone
http://flightcontrol-master.github.io/MOOSE/Documentation/Spawn.html##(SPAWN).SpawnInZone

My intention with the script below:

Spawn a single PLANE which is randomly chosen from my "TemplateTable_Normal" with a limit of up to 4 maximum alive, a randomized route and also for it to spawn in a RANDOMIZED position in zone named "CPS"

Great, everything works when calling the script in the DCS Mission Editor using DO SCRIPT "a2a_norm_start()"

I can keep calling this via trigger over and over again, and it works fine as described, however there is one big issue.

They do not spawn at the altitude given in the group in the ME "A2A_Spawn_Init_NORM" of 32k feet.

Even if I set all the groups in the "TemplateTable_NORMAL" to 32k feet, they do not spawn at that altitude.

The planes will spawn as low as possible, and if they are in the mountains, sometimes they do not have enough room to pull up and will crash instantly.

I did notice that they will attempt to go to the FIRST waypoint's altitude, which in my case, they are all 32k feet. Eventually they'll make it there, but that is not ideal as I'd want them to all start at 32k feet every single time they are called up to spawn.

See my code below:

```
CPS = ZONE:New("CPS")

TemplateTable_NORMAL = { "su27_norm", "su33_norm", "mig29_norm", "m2k_norm" } -- x2 Per Group

A2A_Norm = SPAWN:New( "A2A_Spawn_Init_NORM" )
    :InitLimit( 4, 20 )
    :InitRandomizeTemplate( TemplateTable_NORMAL )
    :InitRandomizeRoute( 1, 1, 2000 ) 

--function to spawn in random position in zone

function a2a_norm_start()
    A2A_Norm:SpawnInZone( CPS, true )
end
```

**Comment by Delta-99** [comment]
Try removing the randomize route to see if your altitude then works. That might be your problem.

**Comment by deadlyfishes** [comment]
Tried the above settings, including removing randomize route, the planes still spawn as low as possible.

**Comment by FlightControl-Master** [comment]
This is only with SpawnInZone?

**Comment by deadlyfishes** [comment]
`:Spawn()` places them in the position given in the editor or as defined, including the correct altitude in the editor.

`SpawnInZone` with randomize TRUE, will place them in a random location in the zone, but not at the given altitude defined in the editor.

**Comment by FlightControl-Master** [comment]
ok
i see, thank for the info.

**Comment by FlightControl-Master** [comment]
Didn't get to it fixing it today. Work and family first! Will try tomorrow.

**Comment by Delta-99** [comment]
FC, if you do put in an optional random altitude would be nice to specify min/max to randomize between.

**Comment by FlightControl-Master** [comment]
ok, i understand

**Comment by FlightControl-Master** [comment]
This is implemented and @deadlyfishes tested this, closing this issue.
