### ISSUE TITLE
Missing `return self` in ATC_GROUND_NEVADA:New() and ATC_GROUND_NORMANDY

### ISSUE THREAD

**Issue by victorcotap** [FlightControl-Master/MOOSE#721]
in the file ATC_GROUND.lua

ATC_GROUND_CAUCASUS:New() line 843 you have
`return self`

ATC_GROUND_NEVADA:New() line 1369 and ATC_GROUND_NORMANDY:New() line 2138
It seems to be missing

Therefor when we call `ATC_GROUND_NEVADA:New():SetKickSpeedKmph(80)` it doesn't take it into account

**Comment by FlightControl-Master** [comment]
Thank you! I will update this and release a new version!

GREAT STUFF!

@victorcotap

**Comment by FlightControl-Master** [comment]
Fixed.
