### ISSUE TITLE
ATC_GROUND kicking lead plane when wingmen violate taxi speed

### ISSUE THREAD

**Issue by deadlyfishes** [FlightControl-Master/MOOSE#722]
I have many players in my server reporting being kicked due to another player within their group speeding or violating ATC_GROUND rules.

**Comment by FlightControl-Master** [comment]
Hmm! What you mean with... Within their group? This is an important question.

**Comment by deadlyfishes** [comment]
In the mission editor, you can make a group that has 4 planes within the group maximum.

I have done a taxiway takeoff as unit 2 of 4 in a group, and the lead plane (1 of 4) gets kicked.

Need to do more testing though

**Comment by FlightControl-Master** [comment]
The script of ciribob works on group level. Let me see if i can make a version of slotblocker, that works on unit level. And i will share with you for test. I need 2 days for that.
Anyways, you know that there are severe bugs in dcs allowing 2 or more clients in the same group?

**Comment by deadlyfishes** [comment]
I didn't know that officially, but I've come to guess that with a lot of weird things happening with other scripts.

**Comment by FlightControl-Master** [comment]
Unit:getGroup() returns nil when the group has 2 or more Client units in MP, on the server, when both clients are connected remotely.

**Comment by 131stGutts** [comment]
Solved in #1095 Pull Request
