### ISSUE TITLE
COORDINATE: Waypoint function optimizations.

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#730]
mechanist [10:29 AM] 
As a mission designer I would like to have the following functions:
 function COORDINATE:WaypointAirTurningPoint( AltType, Speed )
These shall have an optional altitude parameter which overrides the coordinate z if set
function COORDINATE:WaypointAirTurningPoint( AltType, Speed, Alt )
alt #number in meters
This is an important parameter if you set the coordinate to of the waypoint to fly over a ground target or zone.

A similar function like SetTaskWaypoint for options. Like SetOptionWaypoint
SetOptionWaypoint(Waypoint, Option)

An easier way to call up tasks and options like now.
Something like this:
infightoption = SetOption (AI.Option.Air.val.RADAR_USING.NEVER)
myflight:SetOptionWaypoint(Waypoint3, infightoption)

**Comment by FlightControl-Master** [comment]
delta99 [3:37 AM] 
Don’t forget when having any options for setting altitude you need to make it so that you can specify BARO or RADIO type.
