### ISSUE TITLE
SET_ZONE: Create new SET class

### ISSUE THREAD

**Issue by Mechanist11** [FlightControl-Master/MOOSE#732]
Would be lovely to have a SET_ZONE function with parameters such as :FilterPrefixes

Should work like SET_GROUPS but of zones.

**Comment by FlightControl-Master** [comment]
I think this is feasible, but it requires some thinking...

Normal trigger zones only, or also polygon zones?

**Comment by Mechanist11** [comment]
Should work for both if possible.

**Comment by FlightControl-Master** [comment]
I agree. Maybe with 2 methods... FilterRadiusZones() and FilterPolygonZones() each with different parameters.  And the SET_ZONE would create new objects of each object found...

**Comment by FlightControl-User** [comment]
Implemented :-) Done
