### ISSUE TITLE
SPAWNSTATIC: NewFromType seems not to work. 

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#733]
@mechanist I would make anything a string that is quoted as defined in the mission. The example above you posted. So, for example I would quote "garagh-small-b" in your call. The documentation could be wrong.

Like this: ` MST_Log_Garage_Small_B = SPAWNSTATIC:NewFromType("Garage small B", "garagh-small-b", "Fortifications", country.id.GERMANY) `

**Comment by FlightControl-Master** [comment]
@delta99 The Spawn call works fine, I tested it with the regular template call method ofr the definition of spawn group.
MST_Log_Garage_Small_B = SPAWNSTATIC:NewFromStatic( "Garage Small B", country.id.ABKHAZIA )
@flightcontrol Yes I use that metod and it works well. However I think the NewFromType method have so much potential. Not much for static but if we can get similar function for ground units the possibilites could be endless.
With that you could possibly create truely random groups. Like you define 10 unit with NewFromType and then build a group by randomly selcting them for each place. That way every time the convoys or battle groups could be random. With a few lines you could eliminate the need of templates and create truely random ground targets.
Of course you can doo that now by preseting a lot of templates but I see a great possiblitiy if your code just would put togethet a group with random number of units and random type of units.

**Comment by thebgpikester** [comment]
wfm
