### ISSUE TITLE
Have Artillery units participate in the capture of zones

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#735]
If an enemy unit enters a contested zone the Zone capture feature should not only direct units to move and capture the zone, but Arty units within their maximum range, not just line of site should fire on  enemy units if there is a friendly within line of site of the enemy in the zone They should fire based on designer parameters including number of rounds, length of bombardment, type of shell. Should be selectable by designer on how arty reacts.

**Comment by FlightControl-User** [comment]
@funkyfranky what are your ideas on this frank?
