### ISSUE TITLE
A2A Dispatcher will still launch AI from bases it no longer owns.

### ISSUE THREAD

**Issue by TracerFacer** [FlightControl-Master/MOOSE#736]
Requirements
- AI should not launch from a airbases it does not own. 

Example: 
Started mission with blue owning and spawning A2ADispatches at a particular airbase. That airbase is lost due to normal DCS mechanics and is now red. Blue AI continue to spawn from what is now a red airbase.

**Comment by FlightControl-User** [comment]
@TracerFacer i just implemented this, and will release the enhancement as part of patch 2.4.3 today. Closing. So when an airbase gets captured, that is, when there is no more friendly unit near the airbase, the airbase will change coalition. As a result, the airbase operations will cease. No more CAP or GCI. But the still airborne planes will still react until all airplanes of the squadron located at the airbase are eliminated.
