### ISSUE TITLE
Displaying Tasks Status returns nothing to the player. 

### ISSUE THREAD

**Issue by TracerFacer** [FlightControl-Master/MOOSE#738]
When trying to display task status, nothing is displayed to the player, and the below is logged every time.

`
02883.924 INFO    SCRIPTING:  27595( 26970)/E:        TASK_A2G_BAI02057.UpdateTaskInfo({})
02883.924 INFO    SCRIPTING: MOOSE error in MENU COMMAND function: [string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002AA3"]:27623: attempt to call method 'GetVelocityVec3' (a nil value)
02883.924 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002AA3"]:3716: in function 'GetVelocityVec3'
	[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002AA3"]:27623: in function 'UpdateTaskInfo'
	[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002AA3"]:26970: in function 'ReportDetails'
	[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002AA3"]:26674: in function <[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002AA3"]:26673>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002AA3"]:3726: in function <[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002AA3"]:3722>
`
![image](https://user-images.githubusercontent.com/32231252/32701375-8ff7c7ac-c799-11e7-8b5a-bd6b7a33b1df.png)

![image](https://user-images.githubusercontent.com/32231252/32701376-94c52798-c799-11e7-82b0-5b15b2432a14.png)

**Comment by TracerFacer** [comment]
Also see this in the dcs.log on a regular basis. Seems similar.
`
01094.572 INFO    SCRIPTING:  60628(    -1)/E: TASK_A2G_DISPATCHER01907.function(onafterReport)
01094.572 INFO    SCRIPTING:  60958( 60632)/E: TASK_A2G_DISPATCHER01907.ProcessDetected(nil)
01094.572 INFO    SCRIPTING:  61000( 60632)/E: TASK_A2G_DISPATCHER01907.ProcessDetected({["DetectedItemID"]=1,["TaskIndex"]=1,["DetectedItemChanged"]=false,})
01094.572 INFO    SCRIPTING:  61000( 60632)/E: TASK_A2G_DISPATCHER01907.ProcessDetected({["DetectedItemID"]=2,["TaskIndex"]=2,["DetectedItemChanged"]=false,})
01094.572 INFO    SCRIPTING:  61000( 60632)/E: TASK_A2G_DISPATCHER01907.ProcessDetected({["DetectedItemID"]=3,["TaskIndex"]=3,["DetectedItemChanged"]=true,})
01094.573 INFO    SCRIPTING:  60233( 61085)/E:        TASK_A2G_BAI16523.SetDetection({[1]=3,[2]={["current"]="Detecting",["_FlareDetectedUnits"]=false,["FriendliesCategory"]=2,["DetectionRun"]=2,["DetectedItemMax"]=4,["DetectedObjectsIdentified"]={["RU AAA GROUND #007"]=true,["Z1 #005"]=true,["Spawn Vehicle 1#003-02"]=true,["Z3 #005"]=true,["Spawn Vehicle 1#003-01"]=true,["Spawn Vehicle 1#002-02"]=true,["Z1 #003"]=true,["Z3 MAIN #003"]=true,["Spawn Vehicle 1#001-02"]=true,["Z1 #001"]=true,["Z3 #001"]=true,["Z1 #004"]=true,["Z3 #004"]=true,["Z1 MAIN #004"]=true,["Z3 MAIN #002"]=true,["Z2 #005"]=true,["Z1 MAIN #002"]=true,["Spawn Vehicle 1#001-01"]=true,["Z3 #003"]=true,["Unit #113"]=true,["Z2 MAIN #002"]=true,["Z1 MAIN #001"]=true,["Z2 MAIN #003"]=true,["Z2 #003"]=true,["Z2 #002"]=true,["Z1 #002"]=true,["Spawn Vehicle 1#002-01"]=true,["Z3 #002"]=true,["Z3 MAIN #001"]=true,["Z1 MAIN #003"]=true,["RU AAA GROUND #006"]=true,["Z3 MAIN #004"]=true,["Z2 MAIN #001"]=true,["Z2 #004"]=true,["Z2 #001"]=true,["Z2 MAIN #004"]=true,},["DetectedItemCount"]=4,["DetectionCount"]=2,["_SmokeDetectedZones"]=false,["_SmokeDetectedUnits"]=false,["DetectionZoneRange"]=10000,["ClassName"]="DETECTION_AREAS",["_FlareDetectedZones"]=false,["_BoundDetectedZones"]=false,},})
01094.573 INFO    SCRIPTING:  61673( 61086)/E:        TASK_A2G_BAI16523.UpdateTaskInfo({[1]={["current"]="Detecting",["_FlareDetectedUnits"]=false,["FriendliesCategory"]=2,["DetectionRun"]=2,["DetectedItemMax"]=4,["DetectedObjectsIdentified"]={["RU AAA GROUND #007"]=true,["Z1 #005"]=true,["Spawn Vehicle 1#003-02"]=true,["Z3 #005"]=true,["Spawn Vehicle 1#003-01"]=true,["Spawn Vehicle 1#002-02"]=true,["Z1 #003"]=true,["Z3 MAIN #003"]=true,["Spawn Vehicle 1#001-02"]=true,["Z1 #001"]=true,["Z3 #001"]=true,["Z1 #004"]=true,["Z3 #004"]=true,["Z1 MAIN #004"]=true,["Z3 MAIN #002"]=true,["Z2 #005"]=true,["Z1 MAIN #002"]=true,["Spawn Vehicle 1#001-01"]=true,["Z3 #003"]=true,["Unit #113"]=true,["Z2 MAIN #002"]=true,["Z1 MAIN #001"]=true,["Z2 MAIN #003"]=true,["Z2 #003"]=true,["Z2 #002"]=true,["Z1 #002"]=true,["Spawn Vehicle 1#002-01"]=true,["Z3 #002"]=true,["Z3 MAIN #001"]=true,["Z1 MAIN #003"]=true,["RU AAA GROUND #006"]=true,["Z3 MAIN #004"]=true,["Z2 MAIN #001"]=true,["Z2 #004"]=true,["Z2 #001"]=true,["Z2 MAIN #004"]=true,},["DetectedItemCount"]=4,["DetectionCount"]=2,["_SmokeDetectedZones"]=false,["_SmokeDetectedUnits"]=false,["DetectionZoneRange"]=10000,["ClassName"]="DETECTION_AREAS",["_FlareDetectedZones"]=false,["_BoundDetectedZones"]=false,},[2]=3,})
01094.573 INFO    SCRIPTING: Error in SCHEDULER function:[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002F60"]:61706: attempt to call method 'GetVelocityVec3' (a nil value)
01094.573 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002F60"]:17199: in function 'GetVelocityVec3'
	[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002F60"]:61706: in function 'UpdateTaskInfo'
	[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002F60"]:61086: in function 'ProcessDetected'
	[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002F60"]:60632: in function <[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002F60"]:60626>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002F60"]:17207: in function '_call_handler'
	[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002F60"]:17274: in function <[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002F60"]:17212>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002F60"]:4782: in function <[string "C:\Users\TRACER~1\AppData\Local\Temp\DCS.openalpha\/~mis00002F60"]:4742>
`

**Comment by TracerFacer** [comment]
[dcs.zip](https://github.com/FlightControl-Master/MOOSE/files/1465048/dcs.zip)

**Comment by FlightControl-Master** [comment]
This is fixed now. I've done many enhancements:

- When the task is planned, it will **preserve** the initial task Coordinate, Target composition and Target threat level in a temporary storage.
- When the task is assigned, it will "update" the task Coordinate, Target types and Target threat level upon progress within the mission (targets may move and targets are destroyed, changing the threat level and target composition).
- when the task is not planned and not assigned, it will take the **preserved** task Coordinate, Target compostion and Target threat level for achievement reporting.

In this way, the reports and target markings will always work and the logic will never crash again!
Also, target information is now consistently reported according the task life cycle.

This is fixed in release 2.3. Can't fix this in 2.2.6. I'll need to do an update.

**Comment by FlightControl-Master** [comment]
This is fixed in 2.3
