### ISSUE TITLE
CommandMenuFunction Error In scoring 2.3a

### ISSUE THREAD

**Issue by neonbasschild** [FlightControl-Master/MOOSE#739]
Error from log 

[string "C:\Users\NEONBA~1\AppData\Local\Temp\DCS\/~mis00002747"]:6735: in function 'CommandMenuFunction'
[string "C:\Users\NEONBA~1\AppData\Local\Temp\DCS\/~mis00002747"]:6744: in function <[string "C:\Users\NEONBA~1\AppData\Local\Temp\DCS\/~mis00002747"]:6743>
[C]: in function 'xpcall'
[string "C:\Users\NEONBA~1\AppData\Local\Temp\DCS\/~mis00002747"]:6746: in function <[string "C:\Users\NEONBA~1\AppData\Local\Temp\DCS\/~mis00002747"]:6742>

Lua calling the scoring

--air base clean up and police

CleanUpAirports = CLEANUP_AIRBASE:New( { AIRBASE.Caucasus.Senaki_Kolkhi, AIRBASE.Caucasus.Vaziani, AIRBASE.Caucasus.Kutaisi, AIRBASE.Caucasus.Kobuleti, AIRBASE.Caucasus.Batumi } )

--AirbasePoliceCaucasus = ATC_GROUND_CAUCASUS:New()

--end

--BLUE Command Center

GORGASCC = COMMANDCENTER:New( GROUP:FindByName( "Gorgas HQ" ), "Gorgas HQ" )

--Spawn for tankger and AWACS for Blue
BlueAWACS = SPAWN:New( "EWR Blue Awacs" )
:InitLimit( 1, 0 ) -- 1 tanker live at the same time.
:InitRepeatOnEngineShutDown() -- Launch a new Tanker when the Tanker is destroyed.
:InitRandomizeRoute( 1, 1, 40000 ) -- This randomizes the routes from the second route point till the last - 1 waypoint with a radius of 40000 meters.
:SpawnScheduled( 900, 0.5 ) -- Check for a new Tanker every 300 seconds, with a 50% time variation (so between 150 and 450 seconds).

BlueTanker = SPAWN:New( "Shell" )
:InitLimit( 1, 0 ) -- 1 tanker live at the same time, 4 tankers in stock.
:InitRepeatOnEngineShutDown() -- Launch a new Tanker when the Tanker is destroyed.
:InitRandomizeRoute( 1, 1, 40000 ) -- This randomizes the routes from the second route point till the last - 1 waypoint with a radius of 40000 meters.
:SpawnScheduled( 900, 0.5 ) -- Check for a new Tanker every 300 seconds, with a 50% time variation (so between 150 and 450 seconds).

--Suport aircraft calls
Eyeball = SPAWN:New( "Recon Eyeball" )
Eyeball:InitCleanUp(300)
Cargo = SPAWN:New( "Recon Cargo" )
Cargo:InitCleanUp(300)
Hunter = SPAWN:New( "Recon Hunter" )
Hunter:InitCleanUp(300)
Tiger = SPAWN:New( "Recon Tiger" )
Tiger:InitCleanUp(300)
Arco = SPAWN:New( 'Arco' )
Arco:InitCleanUp(300)
Magic = SPAWN:New( 'EWR Blue Magic' )
Magic:InitCleanUp(300)

--spawn function for calling support aircraft
local function SpawnFunction( SpawnObject ) 
local SpawnGroup = SpawnObject:Spawn()
end

--functions for setting the flags to activate sub systems
function LoadMissionsFLAG()
trigger.action.setUserFlag('1', 2)
end
function LoadTrafficFLAG()
trigger.action.setUserFlag('1', 3)
end

-- Mission Radio User Menu
MissionSystemsMENU = MENU_COALITION:New( coalition.side.BLUE, "Server Systems" )
SystemLoaderMENU = MENU_COALITION:New( coalition.side.BLUE, "System Loader", MissionSystemsMENU )
MenuSupportBlueMENU = MENU_COALITION:New( coalition.side.BLUE, "Activate Support", MissionSystemsMENU )
LoaderMissionsMENU = MENU_COALITION_COMMAND:New( coalition.side.BLUE, "Load Missions", SystemLoaderMENU, LoadMissionsFLAG, nil )
LoaderTrafficMENU = MENU_COALITION_COMMAND:New( coalition.side.BLUE, "Load CIV Traffic", SystemLoaderMENU, LoadTrafficFLAG, nil )
ACTEyeball = MENU_COALITION_COMMAND:New( coalition.side.BLUE, "Active Eyeball", MenuSupportBlueMENU, SpawnFunction, Eyeball )
ACTCargo = MENU_COALITION_COMMAND:New( coalition.side.BLUE, "Active Cargo", MenuSupportBlueMENU, SpawnFunction, Cargo )
ACTHunter = MENU_COALITION_COMMAND:New( coalition.side.BLUE, "Active Hunter", MenuSupportBlueMENU, SpawnFunction, Hunter )
ACTTiger = MENU_COALITION_COMMAND:New( coalition.side.BLUE, "Active Tiger", MenuSupportBlueMENU, SpawnFunction, Tiger )
ACTMagic = MENU_COALITION_COMMAND:New( coalition.side.BLUE, "Active Magic", MenuSupportBlueMENU, SpawnFunction, Magic )
ACTArco = MENU_COALITION_COMMAND:New( coalition.side.BLUE, "Active Arco", MenuSupportBlueMENU, SpawnFunction, Arco )
ACTRange = MENU_COALITION_COMMAND:New( coalition.side.BLUE, "Active Range", MenuSupportBlueMENU, RangeStart, nil )

--range code & also Blue Command
function RangeStart()
Scoring = SCORING:New( "Shooting Range" )
Scoring:SetScaleDestroyScore( 0 ) 
Scoring:SetScaleDestroyPenalty( 10 )
SCORING:SetMessagesHit()
SCORING:SetMessagesDestroy() 

ShootingRangeZone = ZONE:New( "Range" )
Scoring:AddZoneScore( ShootingRangeZone, 1 )
end
--end range

-----Auto Lasing System
RecceSetGroup = SET_GROUP:New():FilterPrefixes( "Recon" ):FilterStart()

-- Let the RecceSetGroup vehicles in the collection detect targets and group them in AREAS of 1000 meters.
RecceDetection = DETECTION_AREAS:New( RecceSetGroup, 1000 )

-- Create a Attack Set, which contains the human player client slots and CA vehicles.
AttackSet = SET_GROUP:New():FilterPrefixes("406th vFS"):FilterStart()

RecceDesignation = DESIGNATE:New( CC, RecceDetection, AttackSet )

RecceDesignation:SetMission()

-- This sets the current status menu flashing on
RecceDesignation:SetFlashStatusMenu( true )

-- This sets the threat level prioritization on
RecceDesignation:SetThreatLevelPrioritization( true )

-- Set the possible laser codes.
RecceDesignation:GenerateLaserCodes()

-- Start the detection process in 5 seconds.
RecceDesignation:__Detect( -5 )

**Comment by FlightControl-Master** [comment]
@neonbasschild what do i need to do with this report?
