### ISSUE TITLE
TASK_CARGO_TRANSPORT not allowing clients to join a task

### ISSUE THREAD

**Issue by toppometer** [FlightControl-Master/MOOSE#741]
In 1.5.7,  players joining a server can see but not join a task configured via the TASK_CARGO_TRANSPORT function.   

However, if the script generating the tasks is run after the client has joined the server (e.g. via a trigger) the client can join the task normally.

**Comment by Delta-99** [comment]
@toppometer if / when you get a chance can you confirm this is fixed for you now?

**Comment by FlightControl-User** [comment]
@toppometer this is fixed.

**Comment by toppometer** [comment]
@FlightControl-User @Delta-99, Thanks for this!  I'll give it a go once the rest of my kit arrives.  I've relocated to Sydney so have had to take a break from computer stuff while my stuff is shipped out here!
