### ISSUE TITLE
AI_CAP_ZONE minor problems

### ISSUE THREAD

**Issue by PorcoRosso86** [FlightControl-Master/MOOSE#742]
-----------------------------------------------------------------------------------------------------------------
RU_PlanesSpawn1 = SPAWN:New( "RU SQ 1" ):InitLimit( 2, 100 ):SpawnScheduled( 600, 0.5 ):InitRepeatOnLanding()
`
CapGroupRed1 = RU_PlanesSpawn1:Spawn()

RedPatrolZone1 = ZONE:New( "Cap Red 1" )

RedEngangeZone1 = ZONE_POLYGON:New( "Confine Red 1", RedGroup1 )

CAP_RU1 = AI_CAP_ZONE:New( RedPatrolZone1, 8000, 8500, 500, 600 )
CAP_RU1:SetControllable( CapGroupRed1 )
CAP_RU1:SetEngageZone( RedEngangeZone1 )

CAP_RU1:__Start( 1, 500, 4000 )
-------------------------------------------------------------------------------------------------------------------
If the pair of fighter is destroyed, one of the plane of the pair respawned don't follow the AI_CAP_ZONE engage and cap rules and the other one follow the rules, shipping on his cap zone and activing only if engage zone is exceeded from a foe.

**Comment by Delta-99** [comment]
This is probably not a bug. You need to use an OnSpawnGroup to add the spawns to the AI_CAP_ZONE on the subsequent spawns. If you hit me up in Discord I can probably dig up an example.

**Comment by FlightControl-User** [comment]
Is this fixed?

**Comment by Delta-99** [comment]
@FlightControl-User I don't think this is actually an issue. See my comment.

**Comment by FlightControl-User** [comment]
OK. I'll close it then. @Delta-99 thanks.
