### ISSUE TITLE
1.5.7 - Spawn:InitArray - units and not visable in F7 or the F10 views - Are visible from External view 

### ISSUE THREAD

**Issue by falcon76** [FlightControl-Master/MOOSE#743]
Spawn:InitArray - units and not visible in F7 or the F10 views - Are visible from External view.
IF Initarray is not used units are correctly created and visible from all views 
This also seems to affect the set table from being populated with these phantom units.

Reproduce issue:
  local Inf_Assault_Template = {"USA Infantry M249 Template", "USA Infantry M4 Template", "USA Infantry M4 Template"}
   local Spawn_Assault_Inf_2 = SPAWN:New( "USA_Assault_Inf_2" )
          :InitLimit(300,30)
          :InitRandomizeTemplate(Inf_Assault_Template)
          :InitArray(0,5,4,4)
    Spawn_Assault_Inf_2_Group = Spawn_Assault_Inf_2:Spawn()

Issue:  thirty units visible from external views, not visiable in F10 Map, or F7 view.  Also the Set_Group does not populate with the 30 created groups.

Thanks 

Falcon_76th

**Comment by falcon76** [comment]
verified this is also an issue in 2.1.1.11317 dcs 
thanks 

Falcon

**Comment by FlightControl-Master** [comment]
This is a DCS issue. There is a bug report submitted to ED. Closing down this issue. Cannot do anything on that. The issues is that activated units that are visible, are not synced to the clients from the server. So you "see them" on the server, but not in F7 or in F10.

**Comment by FlightControl-Master** [comment]
For more information:

https://forums.eagle.ru/showthread.php?t=190028&highlight=late+activation
