### ISSUE TITLE
Issue with Scoring in Multiplayer

### ISSUE THREAD

**Issue by dwpenney** [FlightControl-Master/MOOSE#747]
Is scoring working in a multiplay context? I am trying to add scoring to a mission with the following:
```
Trainers_Scoring_Ref = SCORING:New ( Trainers_Name )
Trainers_Scoring_Ref:SetScaleDestroyScore( 10 )
Trainers_Scoring_Ref:SetScaleDestroyPenalty( 40 )
```
But I am not getting a scoring comms menu entry, which I think is supposed to happen. 

I set up my own comms menu entry to trigger a call to ReportScoreAllSummary where I pass in a group of expected client positions. This is the set I am using:
```
Trainers_Scoring_Grp = SET_GROUP:New():FilterCoalitions( Trainers_Group_Side ):FilterPrefixes(Trainers_Group_Prefix ):FilterStart()
```
But that call returns an empty string and no messages are presented in game. If I look at the scoring code I see a call to SCORING:OnEventPlayerEnterUnit( Event ), so I thought that maybe I would turn on the Trace info to see if I was getting detected when I enter the client position. 

When running the mission from the mission editor I do not see an EVENT fired when I enter the client but I do see this:
```
DATABASE00003.AddPlayer({[1]=Add player for unit:,[2]=Pilot #020,[3]=Fridge,})
```
I thought that maybe it had to do with the way the mission editor creates the game world so I tried running it from a multiplayer server (this is not a stand-alone server but a multiplayer session on my main DCS instance which I also play from/within). When I unpause the mission and then join, I get the EVENT I expected to see:
```
EVENT00000.onEvent({[1]=S_EVENT_PLAYER_ENTER_UNIT,[2]={[IniUnit]={[ClientAlive2]=false,[ClientBriefing]=,[ClassName]=CLIENT,[AliveCheckScheduler]={[SchedulerObject]=,[MasterObject]=,[ClassName]=SCHEDULER,[Schedules]={[1]=2#CLIENT#000000019,},},[ClientAlive]=false,[Messages]={},[MessageSwitch]=true,[ClientTransport]=false,[_Tasks]={},[ONBOARDSIDE]={[BACK]=3,[FRONT]=4,[RIGHT]=2,[NONE]=0,[LEFT]=1,},[ClientBriefingShown]=false,[_Menus]={},[ClientName]=Pilot #003,},[IniPlayerName]=Fridge,[initiator]={[id_]=16777985,},[id]=19,[IniTypeName]=F-86F Sabre,[IniObjectCategory]=1,[IniUnitName]=Pilot #003,[IniCategory]=0,[IniCoalition]=2,[time]=43219.677,[IniDCSGroup]={[id_]=3,},[IniDCSUnitName]=Pilot #003,[IniDCSUnit]=,[IniDCSGroupName]=BLUE-Trn-F-86F 01,},[3]=Pilot #003,[5]=1,})
```
and I see SCORING respond:
```
SCORING00000._AddPlayerFromUnit({[ClientAlive2]=false,[ClientBriefing]=,[ClassName]=CLIENT,[AliveCheckScheduler]={[SchedulerObject]=,[MasterObject]=,[ClassName]=SCHEDULER,[Schedules]={[1]=2#CLIENT#000000019,},},[ClientAlive]=false,[Messages]={},[MessageSwitch]=true,[ClientTransport]=false,[_Tasks]={},[ONBOARDSIDE]={[BACK]=3,[FRONT]=4,[RIGHT]=2,[NONE]=0,[LEFT]=1,},[ClientBriefingShown]=false,[_Menus]={},[ClientName]=Pilot #003,})
```
But I do not get a SCORING menu entry nor does my menu item return values from SCORING:ReportScoreAllSummary()

Mystery: What am I doing wrong? :smiley:

I am attaching my test mission with code and logging snippet from the multiplayer test (not from within the mission editor). I am using the MOOSE code from the master branch at this commit 22-Nov-2017: https://github.com/FlightControl-Master/MOOSE/commit/b7183023c9064fb918ec71e111dff5598e8dd3a9

[MOOSE-Test-05-DCS15x-23Nov2017.zip](https://github.com/FlightControl-Master/MOOSE/files/1500394/MOOSE-Test-05-DCS15x-23Nov2017.zip)

**Comment by FlightControl-Master** [comment]
@dwpenney I'll check this!

**Comment by FlightControl-Master** [comment]
The mistery is this statement in

**Comment by FlightControl-Master** [comment]
@dwpenney this is fixed and ready for testing on master branch (2.3)
