### ISSUE TITLE
Detection Bug in Setdetectioninterval

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#749]
My Lua code is as follows;
RecceSetGroup = SET_GROUP:New():FilterCoalitions( "blue" ):FilterPrefixes( "F" ):FilterStart()
HQ = GROUP:FindByName( "EWR Gori" )

CC = COMMANDCENTER:New( HQ, "Georgian Brigade HQ" )
RecceDetection = DETECTION_UNITS:New( RecceSetGroup )
RecceDetection:SetDetectionInterval(15)
RecceDetection:FilterCategories(Unit.Category.GROUND_UNIT)
--RecceDetection:SetAcceptRange( 12000 )
RecceDetection:Start()

Im logging an error of 
00416.611 ERROR   DCS: Mission script error: : [string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00001AB3"]:6: attempt to call method 'SetDetectionInterval' (a nil value)
stack traceback:
	[C]: in function 'SetDetectionInterval'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00001AB3"]:6: in main chunk

Something wrong with the detection interval

Using Moose version env.info( 'Moose Generation Timestamp: 20171112_2105' )

**Comment by FlightControl-Master** [comment]
@gunterlund Since the new release, :SetDetectionInterval has been renamed to :SetRefreshTimeInterval().

So use RecceDetection:SetDetectionInterval(15) instead.
The change was documented in a release page, but you may have missed it.

Sven

**Comment by FlightControl-Master** [comment]
I close this issue. Syntax problem.
