### ISSUE TITLE
Designate.lua - little fix

### ISSUE THREAD

**Issue by dslawek** [FlightControl-Master/MOOSE#751]
I think there is a small error in Designate.lua, in function Spot:OnAfterDestroyed.

~~Little fix:
--cut--
  function Spot:OnAfterDestroyed( From, Event, To )
    self:E( "Destroyed Message" )
\-   self.Recce:ToSetGroup( "Target " .. TargetUnit:GetTypeName() .. " destroyed. " .. TargetSetUnit:Count() .. " targets left.", 5, **AttackSet**, self.DesignateName )
\+   self.Recce:ToSetGroup( "Target " .. TargetUnit:GetTypeName() .. " destroyed. " .. TargetSetUnit:Count() .. " targets left.", 5, **self.AttackSet**, self.DesignateName )
  end
--cut--~~ 

**fix v2:**
--cut--
  local Spot = RecceUnit:LaseUnit( TargetUnit, LaserCode, Duration )
  local AttackSet = self.AttackSet
**\+ local DesignateName = self.DesignateName**

  function Spot:OnAfterDestroyed( From, Event, To )
    self:E( "Destroyed Message" )
\-   self.Recce:ToSetGroup( "Target " .. TargetUnit:GetTypeName() .. " destroyed. " .. TargetSetUnit:Count() .. " targets left.", 5, AttackSet, **self.DesignateName** )
\+   self.Recce:**Message**ToSetGroup( "Target " .. TargetUnit:GetTypeName() .. " destroyed. " .. TargetSetUnit:Count() - 1 .. " targets left.", 5, AttackSet, **DesignateName** )
end
--cut--

[Designate_v2.zip](https://github.com/FlightControl-Master/MOOSE/files/1515073/Designate_v2.zip)

**Comment by FlightControl-Master** [comment]
@dslawek thank you! I will look into this!

**Comment by FlightControl-Master** [comment]
OK. Fixed in release 2.3 in master.
