### ISSUE TITLE
SETTINGS Menu - Option to remove

### ISSUE THREAD

**Issue by deadlyfishes** [FlightControl-Master/MOOSE#752]
Writing per FC's request.

It would be useful to have an option to omit the settings option in the F10 - Other Menu removed.

**Comment by 132nd-Entropy** [comment]
agreed

**Comment by glyphoglossus** [comment]
Just saw this. Opened another issue #775 . Closing that now to merge here.

**Comment by Delta-99** [comment]
Duplicate, see #774
