### ISSUE TITLE
ATC Ground Text issues and ideas

### ISSUE THREAD

**Issue by deadlyfishes** [FlightControl-Master/MOOSE#753]
Grammar issues: "Welcome at [airport]" is not grammatically correct. It should be "Welcome to [airport]"

"[Player] is kicked" is also incorrect and should be "[Player] has been kicked"

Customization idea:

Make it an option for us to change the text for when a player pulls up to the runway. We have some rules about this on our server, so maybe it would be nice for people to put their own message here.

**Comment by FlightControl-Master** [comment]
Which module is this about? @deadlyfishes
