### ISSUE TITLE
Detection not reading base parameters

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#754]
Detection not reading base parameters including
RecceDetection:SetDetectionInterval( 15 )
RecceDetection:FilterCategories(Unit.Category.GROUND_UNIT)
RecceDetection:SetAcceptRange( 12000 )

Error in log with this code
RecceSetGroup = SET_GROUP:New():FilterCoalitions( "blue" ):FilterPrefixes( "FO" ):FilterStart()
HQ = GROUP:FindByName( "EWR Gori" )

CC = COMMANDCENTER:New( HQ, "Georgian Brigade HQ" )
RecceDetection = DETECTION_UNITS:New( RecceSetGroup )
RecceDetection:SetDetectionInterval( 15 )
RecceDetection:FilterCategories(Unit.Category.GROUND_UNIT)
RecceDetection:SetAcceptRange( 12000 )

RecceDetection:Start()

no error with this code
RecceSetGroup = SET_GROUP:New():FilterCoalitions( "blue" ):FilterPrefixes( "FO" ):FilterStart()
HQ = GROUP:FindByName( "EWR Gori" )

CC = COMMANDCENTER:New( HQ, "Georgian Brigade HQ" )
RecceDetection = DETECTION_UNITS:New( RecceSetGroup )
--RecceDetection:SetDetectionInterval( 15 )
--RecceDetection:FilterCategories(Unit.Category.GROUND_UNIT)
--RecceDetection:SetAcceptRange( 12000 )

RecceDetection:Start()

verified unit EWR Gori exists and unit with prefix name of "FO" exists

**Comment by gunterlund** [comment]
log error

00469.794 INFO    SCRIPTING:  10451( 11055)/E:           SET_GROUP00066._FilterStart({[1]=Adding Object:,[2]=FO 1,})
00469.796 INFO    SCRIPTING:   6158(  6281)/E:            SETTINGS00065.IsA2A_BRAA({[BRA]=true,})
00469.801 ERROR   DCS: Mission script error: : [string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00002649"]:7: attempt to call method 'SetDetectionInterval' (a nil value)
stack traceback:
	[C]: in function 'SetDetectionInterval'
	[string "C:\Users\BWHITL~1\AppData\Local\Temp\DCS\/~mis00002649"]:7: in main chunk

**Comment by FlightControl-Master** [comment]
hmmm

**Comment by gunterlund** [comment]
I was going to attach the test mission but it would take an miz file

**Comment by gunterlund** [comment]
additional comment. Did more testing and the one parameter that is not working is setdetectioninterval. The other two are working.
