### ISSUE TITLE
DETECTION_BASE:SetAcceptZones, Units outside Zone not being removed from Detected Items.

### ISSUE THREAD

**Issue by Krinje** [FlightControl-Master/MOOSE#756]
DETECTION_BASE:SetAcceptZones currently behaves incorrectly. Once a unit has been detected in the Zone, if it moves out of the Zone it remains in the Detected Items table. It is no longer updated by detection. :DetectedReportDetailed will continue to report a sort of 'last known' details of the Unit.

(practical band-aid for mission creators in need is to iterate the entire DetectedItems and RemoveDetectedItems on everything, wiping the list)

Tested With:
DCS: 1.5.8beta MOOSE: 2.2.4 & 2.3alpha

**Comment by FlightControl-Master** [comment]
Ok. Thanks for telling.  I need to look into this.

**Comment by FlightControl-User** [comment]
Retest this in 2.4.

**Comment by FlightControl-User** [comment]
This is by design. Duplicate issue with #988 . Closing this one. A complete explanation is given in the post of #988 .
