### ISSUE TITLE
CONROLLABLE:OptionAlarmStateGreen, Red and Auto fail to return

### ISSUE THREAD

**Issue by Krinje** [FlightControl-Master/MOOSE#757]
Using GROUP:OptionAlarmStateGreen() Red or Auto all fail to return, and stops the script. I also tested with CONTROLLABLE:OptionAlarmStateGreen() directly.

In testing CONTROLLABLE I'm not 100% sure I used the correct object for though, I used a DCSgroup via getbyname.

DCS: 1.5.8b MOOSE: 2.2.6

**Comment by FlightControl-Master** [comment]
Use a GROUP object.

GroupObject = GROUP:FindByName( "Group" )

**Comment by Krinje** [comment]
The primary problem I ran into was using exactly that. I wanted to test controller directly and for controller I was unsure.

GroupObject = GROUP:FindByName('test group')
GroupObject:OptionAlarmStateGreen()

Fails. I can update with a trace soon.

**Comment by FlightControl-Master** [comment]
OK. I've been testing this now with a completely new test mission I made. The API and the options work perfectly.

**Comment by FlightControl-Master** [comment]
This is the mission I made to test this functionality.

https://github.com/FlightControl-Master/MOOSE_MISSIONS/tree/Release/GRP%20-%20Group%20Commands/GRP-900%20-%20Option%20Green%20and%20Red%20State

**Comment by FlightControl-Master** [comment]
What is the error you got in dcs.log?
