### ISSUE TITLE
Error now appearing in ScheduleDispatcher and ZoneCaptureCoalition

### ISSUE THREAD

**Issue by robgrahamau** [FlightControl-Master/MOOSE#760]
Since the last set of Commits ZoneCaptureCoalition is causing a scheduler error 

```
01133.289 INFO    SCRIPTING: Error in timer function: [string "Scripts/Moose/Core/Base.lua"]:811: attempt to index local 'Object' (a nil value)
01133.289 INFO    SCRIPTING: stack traceback:
	[string "Scripts/Moose/Core/ScheduleDispatcher.lua"]:95: in function <[string "Scripts/Moose/Core/ScheduleDispatcher.lua"]:92>
	[string "Scripts/Moose/Core/Base.lua"]:811: in function 'GetState'
	[string "Scripts/Moose/Functional/ZoneCaptureCoalition.lua"]:418: in function <[string "Scripts/Moose/Functional/ZoneCaptureCoalition.lua"]:416>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "Scripts/Moose/Core/ScheduleDispatcher.lua"]:130: in function <[string "Scripts/Moose/Core/ScheduleDispatcher.lua"]:89>


```

Steps to recreate - Pull Master Branch
Dynamic Load
Run Mission.

Shortly after first major spawn you'll see the error happen as bluefor gets gaurded on town.

[miniflag1-2.zip](https://github.com/FlightControl-Master/MOOSE/files/1545127/miniflag1-2.zip)

**Comment by robgrahamau** [comment]
Can also confirm this is happening in the latest alpha branch static build as well

`08359.899 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\robert\AppData\Local\Temp\DCS.openalpha\/~mis00001AEA"]:4769: in function <[string "C:\Users\robert\AppData\Local\Temp\DCS.openalpha\/~mis00001AEA"]:4766>
	[string "C:\Users\robert\AppData\Local\Temp\DCS.openalpha\/~mis00001AEA"]:3743: in function 'GetState'
	[string "C:\Users\robert\AppData\Local\Temp\DCS.openalpha\/~mis00001AEA"]:46274: in function <[string "C:\Users\robert\AppData\Local\Temp\DCS.openalpha\/~mis00001AEA"]:46272>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\robert\AppData\Local\Temp\DCS.openalpha\/~mis00001AEA"]:4804: in function <[string "C:\Users\robert\AppData\Local\Temp\DCS.openalpha\/~mis00001AEA"]:4763>
`

same error.

**Comment by FlightControl-Master** [comment]
I think you tested with a version that indeed had this error, but I fixed this I think. Can you retry with the latest master branch at the moment please?

**Comment by FlightControl-Master** [comment]
https://github.com/FlightControl-Master/MOOSE/releases/tag/2.3-alpha

Please confirm if this resolved your issue or if the issue persists.

FC

**Comment by FlightControl-Master** [comment]
@robgrahamau I could resimulate this problem. Will try to find the root cause and fix this!

**Comment by robgrahamau** [comment]
Thanks @FlightControl-Master   Sorry I was kinda asleep 7 hrs ago so i couldn't test but yeah I tested both Master Branch and 2.3-Alpha and had the same result yet it was working 24 hrs before hand.

It's almost like it's ignoring that there is a GetState option in the FSM lua, or that the FSM lua is not passing SELF for some reason...

**Comment by FlightControl-Master** [comment]
It is because I made a mistake in the scheduler implementation.
I am fixing it right now as we speak. Am on top of it.

**Comment by FlightControl-Master** [comment]
OK. Fixed, tested and confirmed by @robgrahamau . Issue closed. Issue fixed.
