### ISSUE TITLE
CARGO: `UnLoad()`/`__UnLoad()`/`UnBoard()`/`__UnBoard()` errors (multiple)

### ISSUE THREAD

**Issue by glyphoglossus** [FlightControl-Master/MOOSE#762]
Given the following code,

    LiftLoads = {} -- global book-keeping

    function LoadAlliedLightInfantry(LiftElement)
        if LiftLoads[LiftElement] then
            LiftElement:Message("Squad is already loaded!")
        else
            local AlliedLightInfantryGroup = AlliedLightInfantrySpawner1:Spawn()
            local AlliedLightInfantryCargoGroup = CARGO_GROUP:New( AlliedLightInfantryGroup, "Infantry" , "Airborne", 2000 )
            function AlliedLightInfantryCargoGroup:OnEnterLoaded()
                LiftElement:Message( "Squad loaded!", 1, "Lift")
            end
            function AlliedLightInfantryCargoGroup:OnEnterUnBoarded()
                LiftElement:Message( "Squad unboarded!", 1, "Lift")
            end
            function AlliedLightInfantryCargoGroup:OnEnterUnLoaded()
                LiftElement:Message( "Squad unloaded!", 1, "Lift")
            end
            AlliedLightInfantryCargoGroup:Load( LiftElement )
            LiftLoads[LiftElement] = AlliedLightInfantryCargoGroup
        end
    end

    function UnloadAlliedLightInfantry(LiftElement)
        if LiftLoads[LiftElement] then
            LiftElement:Message( "Squad unloading!", 1, "Lift")
            local AttackCoord = ConflictZone1:GetRandomCoordinate()
            LiftLoads[LiftElement]:UnLoad() -- does not work
            -- LiftLoads[LiftElement]:__UnBoard(1, AttackCoord)
            -- LiftLoads[LiftElement]:UnBoard(AttackCoord)
            -- LiftLoads[LiftElement]:UnLoad(AttackCoord) --- does not work
            -- LiftLoads[LiftElement]:__UnLoad(1, AttackCoord) --- does not work
            -- local loadedGroup = LiftLoads[LiftElement].CargoGroup
            -- LiftElement:Message( loadedGroup.GroupName, 1, "Lift")
            -- loadedGroup:RouteGroundTo( AttackCoord, 14, "Vee", 1 )
            LiftLoads[LiftElement] = nil
        else
            LiftElement:Message( "No troops loaded!", 1, "Lift")
        end
    end

Given the above,

(1) `UnLoad()` and`__UnLoad()` results in a "'ToPointVec2' (a nil value)" error. For reference, I am using MOOSE on master revision 3135639, and the error occurs in method:
 
    CARGO_GROUP:onenterUnLoaded

in line:

    RandomVec2=ToPointVec2:GetRandomPointVec2InRadius(10)

(2) `UnBoard` and `__UnBoard()` work fine in that the troops unload and run toward objective, but the `OnEnterUnLoaded` and `OnEnterUnBoarded` events do not fire.

**Comment by FlightControl-User** [comment]
All fixed. code stabilizing.
