### ISSUE TITLE
CARGO: Feature Request: Speed-Up or Custom Time Option for `Cargo:UnBoard`

### ISSUE THREAD

**Issue by glyphoglossus** [FlightControl-Master/MOOSE#763]
Is it possible to have an option to change speed of ``Cargo:UnBoard()`` to reflect different vehicle capacities and unboard rate? Maybe just as optional parameter passed to ``UnBoard()`` function?

**Comment by FlightControl-User** [comment]
I guess so yes. It will require some tweaking and testing though. there are some complexities under the hood. I could make the infantry unboard very quickly.

**Comment by FlightControl-User** [comment]
done. closing this one
