### ISSUE TITLE
AI_Balance unrestricted spawning. 

### ISSUE THREAD

**Issue by JGrinnelli** [FlightControl-Master/MOOSE#768]
Use of AI_Balancer goes spawn crazy when a unit is shot down by a player or another AI. This should be 6v6 but when the red ai get shot down it just continues to spawn non-stop till the server crashes.

![test](https://user-images.githubusercontent.com/34423431/34081891-cc462678-e322-11e7-8576-6889e70d2c56.PNG)

**Comment by FlightControl-Master** [comment]
Thanks for the report. I will check this immediately! Is there a test mission I can test this with?

**Comment by JGrinnelli** [comment]
I will try to upload the 6v6 mission I used for testing. Worst case I will pm you a link.

**Comment by FlightControl-Master** [comment]
I've just tested AIB-004 and the issue appears there also! I can resimulate it!

**Comment by FlightControl-Master** [comment]
I will go now for a fix!

**Comment by FlightControl-Master** [comment]
I fixed this bug. Ready for testing. I updated the release version 2.3-alpha.

**Comment by thebgpikester** [comment]
We've still got issues with AI_BALANCER that can lead to this state if using some of the advanced functions, so have been unable to test properly. #809

**Comment by Delta-99** [comment]
Strange, I use AI_BALANCER extensively in most of my missions and haven't seen this behaviour before. Most of my missions are likely using an older version of Moose as well. Perhaps this Set:Add bug was added in a more recent version of Moose and therefore a fix needed.

**Comment by Delta-99** [comment]
@JGrinnelli can you confirm if this is fixed?

**Comment by FlightControl-User** [comment]
no reaction. this is fixed.
