### ISSUE TITLE
Demo mission CAP-001

### ISSUE THREAD

**Issue by Blast-1** [FlightControl-Master/MOOSE#769]
Hi everyone,

The demo mission CAP-001 is not working properly. Despite the mission description mentioning that "the Su-27 airplane will patrol and not engage any enemy automatically", the su27 was actually attacking...
Something seems fishy/broken. What is the problem?

TY

**Comment by Blast-1** [comment]
Following my request, Grinnelli had a look on my issue and after testing it it seems that missions CAP-001 and ZON-100 are not working properly.
For the others missions, it was a misunderstanding from me about the mission logic.

**Comment by FlightControl-Master** [comment]
ok. I will look at this tommorow. It is great to see you are getting great help.

**Comment by JGrinnelli** [comment]
I have no idea why the ZON-100 Mission does not work. I did notice when we tested the CAP defmo missions the Enemy plane needs to have designation if none is provided it seems to sill go active and attempt to kill the friendly unit. When you define a zone to engage it works.

**Comment by Delta-99** [comment]
I believe there is a related issue about ZON-100 not working. Let me see if I can find it.

**Comment by Delta-99** [comment]
@Blast-1 is this still an issue? If not I'd like to close it. See my previous comment about related to #810. That is fixed. If it fixes this then can close this.

**Comment by Blast-1** [comment]
@Delta-99 this thread is about CAP-001 demo mission which is not related with smoke. I don't know if this has been fixed or not since nobody tested it.
I don't know if the ZON-100 demo mission is fixed either btw.

**Comment by FlightControl-User** [comment]
i am closing this one.
