### ISSUE TITLE
Spawning ground vehicles

### ISSUE THREAD

**Issue by Blast-1** [FlightControl-Master/MOOSE#770]
Hi,
I'm currently testing the mission demo SPA-011 which purpose is to spawn a ground vehicle. The lua file contains the following lines:
_Spawn_Vehicle_1 = SPAWN:New( "Spawn Vehicle 1" )
Spawn_Group_1 = Spawn_Vehicle_1:Spawn()_

I put in comment these two lines and saved the file to see if the vehicle would spawn again. And it was spawning...
I don't understand because the unit is set to "late activation" in the mission editor then it is not supposed to spawn unless we use these 2 script lines above??

Other thing i tried is to spawn another unit by adding these 2 lines:
SpawnAPC = SPAWN:New("Spawn Vehicle 2")
Spawn_Group_2 = SpawnAPC:Spawn()

But the vehicle didn't spawn at all.
What am i missing here?

TY

**Comment by Blast-1** [comment]
Wingthor helped me on discord to figure out that issue:  i wasn't reloading the lua file in the trigger mission editor. 
Problem solved :)

**Comment by FlightControl-Master** [comment]
Have you read the manual?

**Comment by Blast-1** [comment]
I watched your video tutorial and read the mission demo with the LDT comments. I'll take a look at the manual you provide me. ty.

**Comment by FlightControl-Master** [comment]
OK. So this problem is solved.
