### ISSUE TITLE
DETECTION_UNITS class broken ?

### ISSUE THREAD

**Issue by Blast-1** [FlightControl-Master/MOOSE#773]
With Grinnelli I tried the mission DES-100, and the menu F10 doesn't show up any target as it should be.
The problem has been bypassed by replacing this line : 
RecceDetection = DETECTION_UNITS:New( RecceSetGroup )
by that : RecceDetection = DETECTION_AREAS:New( RecceSetGroup, 1000 )

Is the detection_units class buged?

**Comment by FlightControl-User** [comment]
I will check this. @Blast-1

**Comment by FlightControl-User** [comment]
I have fixed this issue this morning.  Published to master and ready for testing.

**Comment by eric963** [comment]
Ran a quit test usind the DET-200 and individual units were detected.  

Question.. all units were showing
Threat:[]

Should there be some filled in squares there for the threat values?

**Comment by FlightControl-User** [comment]
I'll check.

**Comment by FlightControl-User** [comment]
Thank you for telling. I have found an issue using the A2G dispatcher when using DETECTION_UNITS and DETECTION_TYPES. It has to do with the internal indexes that are being placed to make the relation between the detections and the dispatched tasks (for the detected units). I have a solution, but need to think how to implement it. It may take a day or two.

**Comment by FlightControl-User** [comment]
this is fixed. closing.
