### ISSUE TITLE
Optional Disabling of Player Menu (Settings)

### ISSUE THREAD

**Issue by glyphoglossus** [FlightControl-Master/MOOSE#774]
Is it possible to have the Player Menu disabled or allow client code control of its creation?

Reason is that I have code that creates some F10 options when an MP player unit spawns. The first unit spawned in the MP mission gets my menus as F1, F2 etc., with the player settings menu as the last one, e.g., F4. But a unit that spawns later on will have the menus as F2, F3, F4, because F1 is taken up by the Player settings menu which got there "first". This makes it inconsistent. I would like to stop the Player settings menu from automatically being added (and, optionally, a way to add it later so I can control the sequence).

**Comment by Blast-1** [comment]
i have same issue. The setting menu doesn't is not displayed at the same place for all clients. It seems to be random placed.

**Comment by Delta-99** [comment]
+1 for this. Default should be off unless mission designer turns it on or perhaps if a required Moose class / method is used then it is on.

**Comment by Quadrafarian** [comment]
+1 Would really like to turn it off, instead of commenting it out in the lua

**Comment by victorcotap** [comment]
+1, It also seems to be affected by the menu bug that do not synchronize correctly
![unknown](https://user-images.githubusercontent.com/7770859/36648061-2db80e7e-1a43-11e8-9deb-540c3c3161c2.png)

**Comment by FlightControl-User** [comment]
@glyphoglossus, @Blast-1 , @victorcotap 
 
I have pushed a solution in the master branch; 

Can you test by calling _SETTINGS:SetPlayerMenuOff() at the very start of your script? And check if you still see the Settings menus.

The latest Moose.lua version can be downloaded from here:
https://github.com/FlightControl-Master/MOOSE_INCLUDE/tree/master/Moose_Include_Static

Download Moose.lua for test.

Sven
