### ISSUE TITLE
Disable Default Showing of Briefing Text

### ISSUE THREAD

**Issue by glyphoglossus** [FlightControl-Master/MOOSE#775]
This comes on automatically, and stays on the screen for a long time. I think it should not come on by default, but only if requested by client code / mission designer. But if not, then at least client code/ mission designer should have a way of disabling this?

**Comment by glyphoglossus** [comment]
Saw a similar issue has been already raised in issue #752. Closing this duplicate.

**Comment by FlightControl-Master** [comment]
Ok
