### ISSUE TITLE
BASE 

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#776]
If passing several arguments BASE:ScheduleOnce(Start, SchedulerFunction, ...) this function sends arguments as a #table
 `BASE:ScheduleOnce(1, myFunction , {Test1, Test 2}) -- These are sent as 1 table, not two strings...`

_eg._
```
myFunction (string1, string2)
if type(string1)=="string" then
   -- Ok
else if type(string1) == "table"
 --   NOT ok
end
BASE:ScheduleOnce(1, myFunction , {"Test1", "Test2"}) -- Will end up in claus NOT ok
```

**Comment by FlightControl-User** [comment]
This is not a bug. The arguments in your demo are wrong, you should call it like this:

`BASE:ScheduleOnce(1, myFunction , Test1, Test 2 )`

ScheduleOnce has variable parameters.
