### ISSUE TITLE
DCS-BUG-7 - Detection is detecting invisible units. 

### ISSUE THREAD

**Issue by TracerFacer** [FlightControl-Master/MOOSE#779]
https://forums.eagle.ru/showthread.php?t=206071

Detection system is detecting units that are marked as invisible in the mission editor. Thereby creating tasks for players to destroy targets that are invisible and inmortal. See images below.

![unknown](https://user-images.githubusercontent.com/32231252/34290140-728f6b7a-e6bb-11e7-9f67-68b139ca741a.png)
![unknown](https://user-images.githubusercontent.com/32231252/34290133-6adb0e5c-e6bb-11e7-982a-5e81c523a73c.png)

**Comment by FlightControl-User** [comment]
Solution for this: implement workaround.

**Comment by FlightControl-User** [comment]
@TracerFacer you still there? Do i urgently need to fix this? Or can this wait a bit?

**Comment by TracerFacer** [comment]
No hurry sir.  Appreciate your continued efforts! Thx!

**Comment by FlightControl-User** [comment]
I fixed this. Pushed to master branch.
But you need to do something extra.
Invisible units are only invisible if DLINK detection is not used.
Therefore, ensure you execute the following statements by example:

```lua
FACSetGroup = SET_GROUP:New():FilterPrefixes( "FAC Group" ):FilterStart()

FACDetection = DETECTION_AREAS:New( FACSetGroup, 150, 250 ):BoundDetectedZones():SmokeDetectedUnits()

**FACDetection:InitDetectVisual( true )
FACDetection:InitDetectRWR( true )
FACDetection:InitDetectRadar( true )**

FACDetection:__Start( 5 )
```

**Comment by TracerFacer** [comment]
Very cool, will try at first opportunity!

**Comment by FlightControl-User** [comment]
Have to disappoint you. I thought I had a solution but this morning during testing I found out my solution didn't work for dlink detections.  So I had to revert... I'll find a solution. It just takes time and a good idea.

**Comment by FlightControl-User** [comment]
I will move this to release 2.4 and will release a hotfix when i find a solution for this.

**Comment by FlightControl-User** [comment]
@TracerFacer it seems ED fixed this in the latest release of DCS world.
Can you retest if this is still an issue?

Thank you!

FC

**Comment by FlightControl-User** [comment]
This seems to be fixed by ED. Closing.
