### ISSUE TITLE
OnEventPlayerEnterUnit(EventData) not working

### ISSUE THREAD

**Issue by Blast-1** [FlightControl-Master/MOOSE#784]
The **OnEventPlayerEnterUnit**(EventData) is not working. 
I've been testing others events and I was fine. Since I haven't find any report of it in the GitHub, then I post it to keep a trace.

**Comment by FlightControl-User** [comment]
I know. It is reported to ED. They need to fix this for multi player. Cannot help.

**Comment by FlightControl-User** [comment]
@Blast-1 see here for more info ...

https://www.youtube.com/watch?v=Un9S67NDoLg

**Comment by FlightControl-User** [comment]
Closing this. double issue with #692
