### ISSUE TITLE
ZoneCaptureCoalition Scan Error if used  on Zone Polygon - Moose Generation Timestamp: 20171222_1247

### ISSUE THREAD

**Issue by robgrahamau** [FlightControl-Master/MOOSE#785]
Zone Capture Coalition is producing an error after entering guarded on Moose Release Alpha 2.3 with Time Stamp as shown in the Topic, Exact errors is given below but  Scan is coming back as nil. 

This happens only if using a Zone Polygon 

`23331.175 INFO    SCRIPTING: Error in timer function: [string "C:\Users\robert\AppData\Local\Temp\DCS\/~mis00006C8E"]:46219: attempt to call method 'Scan' (a nil value)
23331.176 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\robert\AppData\Local\Temp\DCS\/~mis00006C8E"]:4769: in function 'Scan'
	[string "C:\Users\robert\AppData\Local\Temp\DCS\/~mis00006C8E"]:46219: in function 'StatusZone'
	[string "C:\Users\robert\AppData\Local\Temp\DCS\/~mis00006C8E"]:46645: in function <[string "C:\Users\robert\AppData\Local\Temp\DCS\/~mis00006C8E"]:46640>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\robert\AppData\Local\Temp\DCS\/~mis00006C8E"]:4809: in function <[string "C:\Users\robert\AppData\Local\Temp\DCS\/~mis00006C8E"]:4763>
`
Mission Attached, Simply run allow enter guarded to occur and error will happen.

[TGWARRIOR.zip](https://github.com/FlightControl-Master/MOOSE/files/1588914/TGWARRIOR.zip)

**Comment by FlightControl-User** [comment]
I haven't implemented this yet on ZONE POLYGON. Only on circles. The reason is that it is a lot of work to do this... I will consider this as an enhancement.

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
