### ISSUE TITLE
DATABASE: Ability to add scenery object

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#791]
Would be nice to add a scenery object with a random name and scenery ID. It could be used to create targes, add to scoring etc. Also ability to export DB stuff as LUA tables or CSV files.

Scenery object might be buildings, bridges, power stations +++

**Comment by FlightControl-User** [comment]
There are already methods for doing this.

**Comment by baluballa** [comment]
Think this is in place
