### ISSUE TITLE
AIBALANCER: Planes crashing after takeoff with AI_BALANCER / AI_PATROL

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#793]
I would consider this an **enhancement** rather than a bug because I think this was introduce with a recent DCS update. I have never noticed this behaviour before in my missions that use AI_BALANCER up until it was pointed out by Quax on the Discord chat that AIB_002 (and later with AIB_007).

See discussion in Discord in AI_BALANCER channel starting Jan 7th.

My observation is that underpowered or lower powered planes have difficulty getting up to speed and crash. My guess is this is a change to DCS AI behaviour in conjunction with perhaps Moose setting the initial waypoint of the group to be in the patrol zone (which may be far away). It could be that planes are not adjust their height or speed properly while attempting to reach the first waypoint.

Note, to see this happening easy test with Mig21, Mig23's. When I tested these were the most likely planes to crash whereas SU30's, F15's and F16's didn't seem to have much of an issue.

Suggested fix is to create a few waypoints on route to the patrol zone. In fact stuff like this was discussed before especially when Moose creates waypoints that might be in the mountains and such. Or really, any waypoint that is far enough distance that there might be a hill between current position and final waypoint position. This will never be solved 100% but I think putting in some wizardy would help. I know FC can come up with some genius solution to this.

**Comment by Delta-99** [comment]
This may or may not be a thing still. I think between DCS releases this gets better or worse. Leaving it as not urgent for the time being and possible bug!!

**Comment by FlightControl-User** [comment]
ok. Note taken ...

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
