### ISSUE TITLE
TASKS. Report Tasks seems broken

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#794]
Generate this error in log:

> INFO    SCRIPTING: MOOSE error in MENU COMMAND function: [string "Scripts/Moose/Tasking/Task_A2A.lua"]:398: attempt to index field 'Coordinates' (a nil value)

This an is rather fundamental function and seems to affect all tasks.

Wingthor

**Comment by thebgpikester** [comment]
Thanks for reminding me! I've seen this repeatedly also. However the menu for me appears to work and only some things are broken which might not be connected. Things I noticed were:
Player options
Setting a map marker from the top menu (is broken)

**Comment by FlightControl-User** [comment]
@baluballa Task menu should work. Can you retry and confirm if the error is still in there? I would be surprised if it is.
