### ISSUE TITLE
DCS: ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Blast-1** [FlightControl-Master/MOOSE#795]
Hello, Im currently experiencing a DCS crash apparently when i use the DETECTION class. From the log file i have an access_violation but i dont know how to solve that issue. Do you have any idea?.  Here is the log file i had during the crashes.

`00148.983 INFO    SCRIPTING:    312(   937)/E:           SET_GROUP02493._FilterStart({[1]=Adding Object:,[2]=Blue Player #019,})
00158.955 INFO    SCRIPTING:    312(   937)/E:           SET_GROUP02909._FilterStart({[1]=Adding Object:,[2]=Blue Player #019,})
00162.056 INFO    SCRIPTING:    518(    -1)/E:     DETECTION_AREAS01533.function({[1]=Detecting,[2]=Detect,[3]=Detecting,})
00162.255 INFO    SCRIPTING:    541(    -1)/E:     DETECTION_AREAS01533.function({[1]=Detecting,[2]=DetectionGroup,[3]=Detecting,})
00163.288 WARNING LOG: 1 duplicate message(s) skipped.
00163.288 INFO    EDCORE: try to write dump information
00163.348 INFO    EDCORE: # -------------- 20180110-012219 --------------
00163.359 INFO    EDCORE: D:\Programmes\DCS World\bin\edObjects.dll
00163.370 INFO    EDCORE: # C0000005 ACCESS_VIOLATION at 28C54974 00:00000000
00163.381 INFO    EDCORE: 00000000 00000000 0000:00000000 
00163.392 INFO    EDCORE: 28C54974 003DEBC0 0000:00000000 D:\Programmes\DCS World\bin\edObjects.dll ?getObjectType@SceneObject@@UEBAPEAVIModel@model@@XZ()+4
00163.403 INFO    EDCORE: 1E57691C 003DEC20 0000:00000000 D:\Programmes\DCS World\bin\WorldGeneral.dll ?getObjectType@woLandPoint@@UEBAPEAVIModel@model@@XZ()+2C
00163.404 INFO    EDCORE: 1E554D76 003DEC50 0000:00000000 D:\Programmes\DCS World\bin\WorldGeneral.dll ?getDetectionPoint@MovingObject@@UEAA?AVVec3d@osg@@XZ()+26
00163.405 INFO    EDCORE: 1E5B4AA3 003DEE20 0000:00000000 D:\Programmes\DCS World\bin\WorldGeneral.dll ?buildTargetDetectionInfo@wDetector@@IEBAXPEAVMovingObject@@AEBVwTargetDetectionStatus@@AEAUwTargetDetectionInfo@@I@Z()+2C3
00163.406 INFO    EDCORE: 1E5B2F3E 003DF040 0000:00000000 D:\Programmes\DCS World\bin\WorldGeneral.dll ?checkTarget@wDetector@@UEAAIPEAVMovingObject@@AEAVwTargetDetectionStatus@@_N@Z()+12E
00163.406 INFO    EDCORE: 860F2441 003DF070 0000:00000000 D:\Programmes\DCS World\bin\DCS.exe
00163.407 INFO    EDCORE: 860F219A 003DF330 0000:00000000 D:\Programmes\DCS World\bin\DCS.exe
00163.407 INFO    EDCORE: 860F1F50 003DF3D0 0000:00000000 D:\Programmes\DCS World\bin\DCS.exe
00163.409 INFO    EDCORE: 860E9115 003DF430 0000:00000000 D:\Programmes\DCS World\bin\DCS.exe
00163.410 INFO    EDCORE: 860E83CA 003DF490 0000:00000000 D:\Programmes\DCS World\bin\DCS.exe
00163.410 INFO    EDCORE: 860C3CC0 003DF4D0 0000:00000000 D:\Programmes\DCS World\bin\DCS.exe
00163.411 INFO    EDCORE: 860C349B 003DF520 0000:00000000 D:\Programmes\DCS World\bin\DCS.exe
00163.411 INFO    EDCORE: 1E546C2C 003DF560 0000:00000000 D:\Programmes\DCS World\bin\WorldGeneral.dll ??4GoToWaypoint@AI@@QEAAAEAV01@$$QEAV01@@Z()+DC
00163.412 INFO    EDCORE: 21EAC373 003DF5E0 0000:00000000 D:\Programmes\DCS World\bin\World.dll
00163.412 INFO    EDCORE: 21EAC921 003DF640 0000:00000000 D:\Programmes\DCS World\bin\World.dll
00163.413 INFO    EDCORE: 861209A6 003DF6B0 0000:00000000 D:\Programmes\DCS World\bin\DCS.exe
00163.413 INFO    EDCORE: 86130D5E 003DF710 0000:00000000 D:\Programmes\DCS World\bin\DCS.exe
00163.414 INFO    EDCORE: 85DA08CB 003DF740 0000:00000000 D:\Programmes\DCS World\bin\DCS.exe
00163.414 INFO    EDCORE: 85DA2379 003DFE40 0000:00000000 D:\Programmes\DCS World\bin\DCS.exe
00163.416 INFO    EDCORE: 862AB163 003DFE80 0000:00000000 D:\Programmes\DCS World\bin\DCS.exe
00163.418 INFO    EDCORE: 3AD516AD 003DFEB0 0000:00000000 C:\Windows\system32\KERNEL32.DLL BaseThreadInitThunk()+D
00163.419 INFO    EDCORE: 3D245444 003DFF00 0000:00000000 C:\Windows\SYSTEM32\ntdll.dll RtlUserThreadStart()+34
00163.531 INFO    EDCORE: Minidump created.
00163.531 INFO    DCS: try to write track file
00163.532 INFO    DCS: 'C:\Users\Administrator\Saved Games\DCS\Logs\dcs.20180110-012219.crash' deleted successfully
00163.654 INFO    DCS: 'C:\Users\Administrator\Saved Games\DCS\Logs\dcs.20180110-012219.dmp' deleted successfully
00163.654 INFO    DCS: failed to open '' for reading
=== Log closed.`

**Comment by FlightControl-User** [comment]
@Blast-1 I know, this kind of error I had also in the past. Detection has a bug since DCS 2.2... In certain cases the detection crashes.

Do you have a view how many objects were in the area? I could fix the crashes by removing static objects from the battle scene. Then it would work.

**Comment by FlightControl-User** [comment]
Sorry @Blast-1 but i can't help you here. This is DCS and it is a BUG. I can resimulate this also with a mission that I had. It has to do with static objects.

**Comment by Blast-1** [comment]
@FlightControl-User sorry for my late answer. I had this issue few month ago and today I am not having this issue with DCS 2.5 anymore with my mission. 
I don't know why this happened. We should consider this thread as close. 
Ty for your help.
