### ISSUE TITLE
AI_A2A_DISPATCHER: Remove Squadron

### ISSUE THREAD

**Issue by felipexlr50** [FlightControl-Master/MOOSE#796]
Hi, I am new in the moose script, I have build a mission that have the AI_A2A_DISPATCHER for RED side, when the airfield, which is dispatching the CGI, is captured for BLUE side, the AI_A2A_DISPATCHER keeps respawning the CGI squadron.

There is a way to remove the CGI squadron from AI_A2A_DISPATCHER object? to be triggered whenever the airfield is captured?

Thanks.

**Comment by FlightControl-User** [comment]
@felipexlr50 This is a VERY good question. Unfortunately, not (yet). But I'll check into that!

**Comment by FlightControl-User** [comment]
OK. Working on this one at the moment!

**Comment by FlightControl-User** [comment]
@felipexlr50 I will fix this as part of patch 2.4.3. that i will publish in a moment. Closed.
