### ISSUE TITLE
Example documentation for CONTROLLABLE:TaskFunction is wrong

### ISSUE THREAD

**Issue by cjbehm** [FlightControl-Master/MOOSE#799]
There are a few errors overall and if I have time, I'll try to write a replacement usage block and submit a PR. But the absolute bug is the example of calling SetTaskWaypoint -- I spent a long time thinking I was just somehow doing something wrong.

The docs have this
`Vehicle:SetTaskWaypoint( Route, #Route, TaskRouteToZone )`

But it should be
`Vehicle:SetTaskWaypoint( Route[#Route], TaskRouteToZone )`

**Comment by FlightControl-User** [comment]
@cjbehm Thank you, This is fixed by commit 3ce5d71fc9a67bef1371755301dd7525a8972523.

Would it be okay to also advise on the other fixes you discovered?

thank you!

**Comment by cjbehm** [comment]
Thanks for reminding me about this; and the other good news is that after I went back and tried it again successfully. I suspect I managed to break something while trying to get the example to work originally, so I think it's just the fix to SetTaskWaypoint that was wrong.

**Comment by FlightControl-User** [comment]
OK. Fix is fixed. Closing this one.
