### ISSUE TITLE
F10 Marker function has changed in 2.5

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#800]
http://wiki.hoggit.us/view/DCS_func_markToAll
has been updated by Grimes, still being tested. There's now a read only parameter.

This breaks the marker use in Task and Coalition Zones modules.

**Comment by FlightControl-User** [comment]
Has this been published?

**Comment by thebgpikester** [comment]
Franky did an interim version fixing the crash but I'm not sure about if any commits were authorised, things were a blur here. There's instructions for the two lines to just edit them. Also not sure what commit the appveyor version is actually on today :)

**Comment by FlightControl-User** [comment]
The AppVeyor version is of the master branch always. So the fix for thisissue is published to master.

**Comment by FlightControl-User** [comment]
I can close this issue I think.  Are the markers working now?

**Comment by funkyfranky** [comment]
Marker fix was in one of my last commits to master. Issue can be closed.

**Comment by Delta-99** [comment]
Plus ED made it an optional parameter so even without the fix things would likely work again. They did this in one of the hotfixes.

**Comment by Delta-99** [comment]
Ah, ok. Either way you fixed it faster than them so no worries!!
