### ISSUE TITLE
DCS 2.5  shit storm --> SOLVED

### ISSUE THREAD

**Issue by Blast-1** [FlightControl-Master/MOOSE#802]
**EDIT: The following report has been solved and is explained in my last post**

My title is a bit exaggerated but not that much considering the number of classes that are not working anymore in the DCS 2.5 version.

Classes that are not working:
**SET_PLAYER** -> nil value
**USERSOUND** -> nil value
**SET_STATIC** -> 2018-02-04 22:10:05.362 INFO    SCRIPTING: Error in timer function: [string "C:\Users\ADMINI~1\AppData\Local\Temp\DCS.openbeta\/~mis0000203E"]:624: attempt to index global 'SET_STATIC' (a nil value)

Methods that is not working:
**ForEachGroupAlive** -> 2018-02-04 22:10:07.323 INFO    SCRIPTING: Error in timer function: [string "C:\Users\ADMINI~1\AppData\Local\Temp\DCS.openbeta\/~mis0000203E"]:591: attempt to call method 'ForEachGroupAlive' (a nil value)

I precise that these errors are not showing in DCS 1.5.8.
I may found others issues  when i'll replaced the class and methods not working by others class/methods. 

I am using this moose version:
env.info( '*** MOOSE STATIC INCLUDE START *** ' )
env.info( 'Moose Generation Timestamp: 20171031_1115' )

I hope a solution will be find.

**Comment by thebgpikester** [comment]
local BlueVictory = USERSOUND:New( "micclick.ogg" )
  BlueVictory:ToAll()
Worked when tested. As in, it produced the sound I loaded into the mission. in 2.5 current.

**Comment by Blast-1** [comment]
I retested my sound file again in the mission editor->triggers and they are working fine there but when launching the mission i have the error:
2018-02-07 16:27:29.020 ERROR   DCS: Mission script error: : [string "C:\Users\ADMINI~1\AppData\Local\Temp\DCS.openbeta\/~mis000064A7"]:56: attempt to index global 'USERSOUND' (a nil value)

And in line 56 in my script file i have: 
son_GoodKill = USERSOUND:New( "goodKill.ogg" )

Then I dont understand why its not working.

My moose version  is: 
2018-02-07 16:32:17.397 INFO    SCRIPTING: *** MOOSE STATIC INCLUDE START *** 
2018-02-07 16:32:17.397 INFO    SCRIPTING: Moose Generation Timestamp: 20171031_1115

**Comment by Delta-99** [comment]
Does @thebgpikester have the .miz file he used for this? Maybe send to Blast. If it works, Blast is doing something wrong (even though it can't get much simpler than this). If it doesn't work then something is really up with Blasts setup or something.

**Comment by Blast-1** [comment]
In the end, we found out that these issues happened because i was using the moose version 2.2.6 from 31th october 2017. When using the moose version 2.3-alpha everything works normally with DCS 2.5!
So the shit was only for me (fortunately), meaning that all classes mentioned above are ALL working on DCS 2.5 ONLY IF you use the moose 2.3-alpha.
TY guys for helping me to solve that mystery.

**Comment by FlightControl-Master** [comment]
good you got that solved!
