### ISSUE TITLE
TASK_A2A: Task_A2A_Dispatcher throws error

### ISSUE THREAD

**Issue by Quax456** [FlightControl-Master/MOOSE#804]
SCRIPTING: Error in SCHEDULER function:[string "Scripts/Moose/Tasking/Task_A2A_Dispatcher.lua"]:502: attempt to call method 'IsIDLE' (a nil value)

Every 1/2 second 

But the Dispatcher is calling the Method **MISSION:IsIDLE()** which seems not to work.

**Comment by FlightControl-User** [comment]
The Task_A2A_Dispatcher needs a lot of work to get it in sync with the A2G latest changes.

**Comment by FlightControl-User** [comment]
OK. I have updated back the A2A dispatcher so that it "works".
I cannot guarantee that it is perfectly working for the moment, but at least the obvious crashes should be eliminated.

**Comment by FlightControl-User** [comment]
We are preparing for something bit on this one ... In release 2.4.

**Comment by FlightControl-User** [comment]
Load the latest moose.lua from here:
https://github.com/FlightControl-Master/MOOSE_INCLUDE/tree/master/Moose_Include_Static

**Comment by FlightControl-User** [comment]
Fixed A2A, closing
