### ISSUE TITLE
COORDINATES Bulls showing bearing too BULLS.

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#807]
Is not the correct way to give BRA heading out of BULLS?

Appears like CHOORDINATES :StringToBULLS() shows bearing from object to BULLs Eye.

Wingthor

**Comment by FlightControl-User** [comment]
@baluballa You mean I need to reverse it? (like a 180° turn?)

**Comment by baluballa** [comment]
Yes, the idea with BULLs is that its a now reference, for all coalition. And I am rather sure when calling out a position in BULLs BRA(A), you use out of BULLs as reference. You can check with the "Magic/AWACs" in game. Like it is now, you have to add or subtract 180 to get it right.

**Comment by FlightControl-User** [comment]
Fixed this. Now the BULLS calculation is taking it out of BULLS to the COORDINATE. (It used to be the other way around).

```lua
  --- Return a BULLS string out of the BULLS of the coalition to the COORDINATE.
  -- @param #COORDINATE self
  -- @param Dcs.DCSCoalition#coalition.side Coalition The coalition.
  -- @return #string The BR text.
  function COORDINATE:ToStringBULLS( Coalition, Settings )
    local BullsCoordinate = COORDINATE:NewFromVec3( coalition.getMainRefPoint( Coalition ) )
    local DirectionVec3 = BullsCoordinate:GetDirectionVec3( self )
    local AngleRadians =  self:GetAngleRadians( DirectionVec3 )
    local Distance = self:Get2DDistance( BullsCoordinate )
    local Altitude = self:GetAltitudeText()
    return "BULLS, " .. self:GetBRText( AngleRadians, Distance, Settings )
  end
```

**Comment by Delta-99** [comment]
@baluballa did you confirm if this was fixed?

**Comment by fastfiveoh** [comment]
I can confirm this is fixed in SP and MP.  We use the BULLs BRA coordinates in our SP and MP dynamic mission.   Targets spawn at random locations and the BRA calls were accurate.

**Comment by FlightControl-User** [comment]
Thank you for the feedback, i can close this issue then.
