### ISSUE TITLE
ZON-100 demo mission throwing an error in DCS 2.5

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#810]
DCS Version: 2.5.0.14304 (x86_64; Windows NT 10.0.16299)
Moose Version: Moose Generation Timestamp: 20171222_1247

Looks like perhaps something has broken or changed with Smoking functions in 2.5. This demo mission is causing an error on the Smoke method(s). Note, this was reported via the forums and I haven't checked which particular Smoke method as of yet but my guess maybe both of them.

This could potentially be a DCS Bug too. So marking as so and potential bug for Moose.

If this is really a general smoke issue this could be breaking a ton of missions. Basically anything using Smoke methods so marking it urgent.

> 2018-02-16 20:25:48.098 ERROR   DCS: Mission script error: : [string "C:\Users\tim\AppData\Local\Temp\DCS.25OpenBeta\/~mis000025BE"]:9: attempt to index field 'SmokeColor' (a nil value)

**Comment by FlightControl-User** [comment]
@Delta-99 fixed. There was an issue with the internal script in the mission, it was outdated. Updated now.

![screen_180303_062210](https://user-images.githubusercontent.com/13690775/36931031-0db59e2e-1eae-11e8-8e05-139c0c1cb20e.png)

Is the smoke also not become larger than before?
