### ISSUE TITLE
UNIT:OnDetected, UNIT:OnDetectedRadar callback functions

### ISSUE THREAD

**Issue by Igneous01** [FlightControl-Master/MOOSE#811]
It would be really nice if there was a custom callback for when a unit or group is detected.

Sometimes a scripter only cares about whether a subset of units have detected another subset of units - being able to define what these sets are would offer a lot of flexibility and allow us to express our intents when writing detection logic.

I think it would make most sense to extend this to the GROUP and UNIT classes

UNIT:OnDetection(function(selfUnit, DetectionType, DetectedBy, ....) ... end) -- fires when unit has been detected by someone
UNIT:OnLostDetection(function(selfUnit, DetectionType, LostBy, ....) ... end) -- fires when a unit that was detected by someone, is now lost from their site (visual, radar, ir, whatever)
UNIT:HasDetection(function(selfUnit, DetectionType, DetectedWho, ....) ... end) -- fires when unit has detected some other unit

-- wrapper functions of the above
UNIT:OnDetectionRadar(function ....)
UNIT:OnDetectionIR(function ....)
UNIT:OnDetectionVisual(function .....)
UNIT:OnLostDetectionRadar(function ....)
UNIT:OnLostDetectionIR(function ...)
UNIT:OnLostDetectionVisual(function ...)

This would register a callback function that will be called if the unit in question is detected by something. It would pass to the function some important parameters (like the type of detection (radar, IR, visual, something else), the unit that detected this unit, and other data that's available (like the known range, altitude, aspect, etc). 

Similar types of functions for GROUP

GROUP:OnDetected(function(selfGroup, ...) end)
GROUP:HasDetected(function(selfGroup, ....) end)
GROUP:OnDetectedRadar(function ....)
GROUP:OnDetectedIR(function ....)
GROUP:OnDetectedVisual(function .....)

Similar to the above, but fires when any unit part of a group is detected.

Internally i believe moose would have to create scheduled function that checks every second if a detection has occurred - would need to be written in such a way that if multiple ondetection callbacks are running it will manage all of them in a way that avoids checking the same sets of units/groups multiple times or something.

**Comment by thebgpikester** [comment]
Hi Igneous,
if I understand correctly, I think you want the reverse of detection, to return if a single unit is known about to any of the opposite side? So manually, it would be to create an entire unfiltered set of detectors, and search the detected units of all of them for a single group? I'm not sure on the load of CPU of that as I understand FC additionally filters the entire detection mechanic against other calculations, but I've certainly used narrower sets like a few EWR's to do the same.

Am I close or did i completely miss the mark?

**Comment by Igneous01** [comment]
Hey Mike,

Yeah for UNIT:OnDetection that would fire when any unit has detected this particular unit, to this sort of calculation for all units/groups would be really expensive I agree. However you could potentially have a scheduled function run on all group leaders instead of all units (20 groups is less to calculate vs 200 units) - technically once one group member spots a unit, there is some information sharing between the units in the group.

Perhaps it should be UNIT:OnDetection(callbackfnc, unitlist)

where if any of the units in unitlist have detected this UNIT, it will fire the callback function. One important aspect would be that the callback is not fired again for the same unit that detected (so would need to store target history).

some example code
```Lua
local EWRNetwork = { UNIT:FindByName("EWR1"), UNIT:FindByName("EWR2"), UNIT:FindByName("EWR3") }
local F15Unit = UNIT:FindByName("F15Pilot")
F15Unit:OnDetection(EWRNetwork,
function(thisunit, spottedbyunit, detectinfo)
    if detectinfo.By == DETECTION.Types.RADAR then
         -- do some code here
    end
end)
```

Or another example,
```Lua
local SAMGroups = { GROUP:FindByName("SAM1"), GROUP:FindByName("SAM2"), ... }
local AlliedFlights = { GROUP:FindByName("F15-1"), GROUP:FindByName("F15-2"), ...}

-- OnSingleDetect is a one time event - once it's fired the handler is called and the event unregistered
DETECTION.OnSingleDetect(SAMGroups, AlliedFlights,
function(DetectedGrp, DetectedByGrp, detectinfo)
    if detectinfo.By == DETECTION.Types.RADAR then
        if DetectedByGrp.Name == "SAM1" and detectinfo.RangeKnown and detectinfo.Range < 20000 then
             -- do some action when SAM1 has detected a group with Radar and the range is under 20km
        end
    end
end)

-- or something more elegant
DETECTION.OnSingleRadarDetect(SAMGroups, AlliedFlights,
function(DetectedGrp, DetectedByGrp, detectinfo)
        if DetectedByGrp.Name == "SAM1" and detectinfo.Range < 20000 then
             -- do some action when SAM1 has detected a group with Radar and the range is under 20km
        end
end
```

**Comment by Igneous01** [comment]
There are few different functions that could be provided that would be make this aspect of DCS more intuitive to code.

UNIT:OnSingleDetect -- one time event that is raised when unit is detected (could take list of units, or list of groups as parameter)
-- wrapper functions
UNIT:OnSingleDetectRadar -- similar to above, but only for radar
UNIT:OnSingleDetectIR -- similar to above but only for IR
UNIT:OnSingleDetectRWR 
UNIT:OnSingleDetectOptic
UNIT:OnSingleDetectDataLink
UNIT:OnSingleDetectVisual

-- Fires whenever a unit is detected, multiple use
UNIT:OnDetect
-- similar wrapper functions above for OnDetect

-- Fires when a unit is no longer being detected by list of groups - if the unit was never detected in the first place this event does not fire. It only fires if the unit was spotted, then disappeared off the list.
UNIT:OnLostDetection

-- similar to above but one time event
UNIT:OnSingleLostDetection

-- Similar methods on GROUP

-- can take 2 group lists as parameter
DETECTION.OnSingleDetect
-- wrapper functions
DETECTION.OnSingleRadarDetect
DETECTION.OnSingleIRDetect
DETECTION.OnSingleRWRDetect
DETECTION.OnSingleOpticDetect
DETECTION.OnSingleDataLinkDetect
DETECTION.OnSingleVisualDetect

**Comment by thebgpikester** [comment]
OK I get it and it's use. We need Sven to comment on complexity and CPU/strain as I think he knows this quite well. There would be some very interesting uses of this type of function, and would reduce the line count massively on any current and unwieldy effort.

**Comment by FlightControl-User** [comment]
I will read this next week if okay.

**Comment by FlightControl-User** [comment]
To some extent I could do this, but only when a detection runs for the recces in scope.
So, imagine there are 3 units: A, B, C.
A recce would detect unit A and C, then yes, it could fire for those units an event detection OnDetected().
However, to have for each unit (A, B, C) such logic implemented for all other possible recces (each other unit is potentially a recce), then that would become very CPU intensive.

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
