### ISSUE TITLE
DESIGNATE: Linking DESIGNATE to A2G_BAI TASKS

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#812]
Hi,

Currently have Designate and BAI with area detection running in the same mission. Sadly they run and feel like different things and don't connect, whereas I think DESIGNATE should be rolled into any ground based DETECTION (not air).

What I mean is, 
1) Large area of groups spread
2) Task makes many tasks and makes them available through the COMMANDER menu
3) Designate items are detected and put in the designate menu as AREAS
4) Player cannot link a task to a designate at all, there is no common naming, he can approach a task, if he wanted a designation he cannot tell if its for his task or not. SO basically he cannot get a designation for his task. which is counter intuitive and frustrating. I mean, in a wide battle space, how can you search for a laser spot that you don't know where it is?

I think the designate function is good, but it lacks the direction and coords or BRA that task has, and then if you gave it those, you get the same as task, but without the scoring and the menu optimisation. I see the future that DESIGNATION should be baked into TASK and filtered by ground units providing if they are close enough. Unless anyone can think of a better way to link the two.

**Comment by FlightControl-User** [comment]
This has been always in the back of my mind also. I will come back to this later.
