### ISSUE TITLE
DESIGNATE: Menu stalls

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#813]
Hi, please forgive this sub-par report. It's been reported by at least four people but the steps to reproduce are a bit "poor quality" as I haven't done any proper testing and not used basic demo missions for this. The problem occurs in AREA, not tested UNIT designations and only in live missions. But there is a problem somewhere with the menus.

Steps:
1. Initially all appears correct. Designate an AREA with laser via the menu.
2. Now attempt to do anything else with that area and you should get a "Stop lasing" perpetually you cannot break out of.

There may be more steps between 1&2, but I didn't want this to stop an initial report.

**Comment by FlightControl-User** [comment]
OK. That can indeed be a bug. Needs to be checked.

**Comment by FlightControl-User** [comment]
@thebgpikester @funkyfranky 
So, I've been trying this myself. There are a couple of issues i can see ... 

- [ ] There is a new requirement that i haven't understood, but now i do. People wanna lase targets, but while lasing also illuminate or smoke the area or targets. That means a little redesign of the system, which I can do.

- [ ] Then the issues with lasing ... When a target has been designated, it will be lased automatically when auto lase is on. When the lasing is ongoing, the menu will change to "stop lasing" for that area (hence the requirement about the other designation options like smoking etc). When the lase is stopped, the menu changes back to the correct state, but ... when asked to lase again, the lasing seems not to be working anymore.

So two issues to solve here.

**Comment by FlightControl-User** [comment]
Fixed it, please test the changes. Explanation in DESIGNATE channel on discord.

**Comment by Delta-99** [comment]
@thebgpikester can you confirm if this is fixed?

**Comment by FlightControl-User** [comment]
this is fixed.
