### ISSUE TITLE
Ability to disable default Moose "Settings" menu

### ISSUE THREAD

**Issue by EasyEB** [FlightControl-Master/MOOSE#815]
For lightweight missions that maybe require only one or two mission specific items in the F10 menu, it would be nice to disable the default Moose menu item with player settings as it may not be in use in some missions.

Maybe even default off but have a way to enable it?

**Comment by Delta-99** [comment]
Duplicate, see #774

**Comment by FlightControl-User** [comment]
@EasyEB I understand that the settings menu may seem bothering. However, the settings menu by default off is not such a good idea. The settings menu will contain in the future more menu settings. 
I have done before, but will try to find a good solution to allow to switch the settings menu off, but not by default.

**Comment by FlightControl-User** [comment]
@EasyEB - I have pushed a solution in master; Can you test by calling _SETTINGS:SetPlayerMenuOff() at the very start of your script? And check if you still see the Settings menus.
The latest Moose.lua version can be downloaded from here:
https://github.com/FlightControl-Master/MOOSE_INCLUDE/tree/master/Moose_Include_Static

Download Moose.lua for test.

Sven
