### ISSUE TITLE
SPAWN: Spawn groups facing a specified direction

### ISSUE THREAD

**Issue by RagingIguana** [FlightControl-Master/MOOSE#816]
It would be useful to be able to spawn new groups facing a specified direction, without the need to specify it in the ME. 
As a workaround I have to specify a number of templates with each facing a different direction, and then choose the appropriate one at runtime, which is a bit of a pain.

**Comment by FlightControl-User** [comment]
@mardineb ok. I hear you. Question, so all the units in the group would be faced in the same direction?

**Comment by Delta-99** [comment]
I would say that the group should be spawned as set in the mission editor but rotated as a whole to a specific facing. My guess is this is for some defensive setups etc.

**Comment by mardineb** [comment]
@Delta-99, Yes, that would be my suggestion. Because I am using templates a lot, I have them laid out in a particular formation which I wish to preserve, and do indeed use them for defensive purposes. 

I would find it useful if I could rotate them as a complete set, by some arbritary degrees. 

Moving them to a new route means they break out of formation, so I can't use that technique

**Comment by mardineb** [comment]
Just to try and be clear, rather than all units face the same direction, I would like to rotate each unit by an arbitrary amount. So specifying 30 degrees on a group, would rotate each individual unit by 30 degrees, preserving their formation to one another

**Comment by FlightControl-User** [comment]
I have an idea...
A GROUP is actually a list of units...

What if SPAWN would get a method :InitHeadings that would take as a parameter a list of headings. Each heading would correspond with a unit of the GROUP respectively. 

For example

Group:SetHeading( { 120, 230, 45 } ) for a group of 3 units.

**Comment by mardineb** [comment]
I don't doubt that this would offer more flexibility to an end user, but I feel this would only really be useful with smaller group sizes of around 5 units.

In some of my templates I am using, there may be as many as 15-20 units, all laid out in a specific formation. This would give scope for user error as it would not be clear at a glance what heading corresponds to what unit.

I was thinking more along the lines of:
GROUP:SetHeading(45)

This would work in the same manner as if I had specified 45 degrees in the mission editor for the template. I don't pretend to know how this may work under the hood, I will leave that to your expertise, but how I see it would be as if all units within the template/group were one entity, with that entity being pivoted around its central point to face 45 degrees.

**Comment by Delta-99** [comment]
Yes I don’t see what a setheading on each unit would be useful for. Certainly could be but the more general case would be to rotate the entire group. Now I can see this being a little challenging cause FC needs to determine the position of all the units and rotate them around some point? Which translates their location as well. Maybe always use the first unit in the group. Or maybe use the center of all the units? I would go with 2nd option if easy enough or first if you want to make it more simplified. 

Note @FlightControl-User, you did something similar with translating unit positions when something wasn’t working right I think on the random zone placement or something. Once you made that change then the units were places properly corresponding to how they were setup in the editor. This concept I think just takes it one step further and faces them in a certain direction. 

I diagram would probably help immensely here if needed.

**Comment by mardineb** [comment]
@Delta-99, 
Yes, I do believe this would be challenging. I was surprised at first that there was no way to do this, but the more I have thought about it, the more complexity I now realise there is to this

**Comment by FlightControl-User** [comment]
> I was surprised at first that there was no way to do this, but the more I have thought about it, the more complexity I now realise there is to this

Can you pls recap what you had in mind  initially? What was the issue you tried to solve?

**Comment by mardineb** [comment]
Sure, initially I had a template consisting of a number of units set out in the mission editor with the group itself having an initial heading of 0 degrees, but each individual unit within the template group has its own specific directional heading.
I wanted to be able to use this template to spawn in random zones I have throughout the world. 
Depending on which zone they get spawned to, I wanted to be able to alter the templates direction, to say 180 degrees, instead of 0 degrees. This would keep the formation of the template as a whole, but would be facing in the opposite direction to that set in the mission editor

**Comment by mardineb** [comment]
I can try and put a diagram together that may help explain things clearer

**Comment by FlightControl-User** [comment]
Would you want to rotate the whole template unit locations or just the heading or both?

**Comment by mardineb** [comment]
![unit1_0_deg](https://user-images.githubusercontent.com/7946813/36949494-1a93fd3c-1fe1-11e8-8111-4c5636059c2c.png)
![unit1_90_deg](https://user-images.githubusercontent.com/7946813/36949499-240a1ebe-1fe1-11e8-83d8-89bef2cc582a.png)
![unit1_180_deg](https://user-images.githubusercontent.com/7946813/36949500-2426692a-1fe1-11e8-82a5-c9a3266a2387.png)
![unit1_270_deg](https://user-images.githubusercontent.com/7946813/36949501-243b50c4-1fe1-11e8-9d31-d7b7dd4b81e5.png)

**Comment by mardineb** [comment]
Ok, so lets say we only have the top group as a template, with the first unit having an initial heading of 0 degrees. 
What I would like to achieve is to be able to set the heading on the first unit in the group dynamically when spawning, which in turn will translate the positions of the other units around it. So if I specify 90 degrees on the first unit, when spawned the group would appear like in the second image.

I don't know how hard this would be to achieve, or if it's even possible, but would be a nice feature to have

**Comment by FlightControl-User** [comment]
Now I understand.

**Comment by Delta-99** [comment]
@mardineb its pretty simple math to achieve this. Just needed to be clear to FC what you're looking for and it cannot be clearer with your diagram. This is exactly what I was thinking. The only tricky part is like I posted above. Do we use unit 1 of the group as the initial facing and do we rotate based on that unit or the central point of the group.

**Comment by FlightControl-User** [comment]
Rotation can be done around the first unit.

**Comment by Delta-99** [comment]
Also, you're example was a little bit simplified. Imagine if your 3 units above the centre one were slightly offset on their own angles. In your example they are all facing the same way but I can see a situation where they are on their own angles which should translate as well.

**Comment by FlightControl-User** [comment]
Group:InitRotation( 90 )
Group:Spawn()

**Comment by FlightControl-User** [comment]
Something like this?

**Comment by Delta-99** [comment]
I think that would definitely do it FC.

**Comment by Delta-99** [comment]
Make it clear in the docs that the rotation or basis is based on unit 1 of the group. Have to base it on something right?

**Comment by FlightControl-User** [comment]
This can be done.  Definitely. Thanks gents for the ideas!

**Comment by FlightControl-User** [comment]
Indeed!

**Comment by mardineb** [comment]
Thanks guys, would be great to see. Keep up the good work..!

**Comment by thebgpikester** [comment]
this is done in spawn

**Comment by Loophole62ndFF** [comment]
I can't find any function in Spawn that can do this.
