### ISSUE TITLE
SET_AIRBASE does not update

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#817]
I believe this code would show the airbase coalition owner. The filters do not update. Sample miz attached.
```

Blue = SET_AIRBASE:New():FilterCoalitions("blue"):FilterStart()
Red = SET_AIRBASE:New():FilterCoalitions("red"):FilterStart()
Neutral = SET_AIRBASE:New():FilterCoalitions("neutral"):FilterStart()

SCHEDULER:New( nil,function()
 Blue:Flush()
 Red:Flush()
 Neutral:Flush()
 BlueNo = Blue:Count()
 RedNo = Red:Count()
 NeutralNo = Neutral:Count()
 
 MESSAGE:New("Red: " .. RedNo .. " Blue: " .. BlueNo .. " Neutral: " .. NeutralNo,10):ToAll()
end, {}, 1, 10)
```
[airbasesetbug.zip](https://github.com/FlightControl-Master/MOOSE/files/1778013/airbasesetbug.zip)

**Comment by FlightControl-User** [comment]
I fixed this issue in release 2.3 and in release 2.4 through a hotfix. You can find the updated Moose.lua in MOOSE_INCLUDE master and develop branch :-)

(master = release 2.3, develop = release 2.4) !!!

Give it a few minutes to update MOOSE_INCLUDE.

**Comment by FlightControl-User** [comment]
@thebgpikester I tested this with your attached mission. It works. I've implemented now also the base capture event, generated by DCS, and is now interpreted, checking the owning coalition of the set, and adding/removing bases to/from the set based on the filter criteria.
I think this is a welcome addition for you.

**Comment by FlightControl-User** [comment]
Implemented this one, closing.

**Comment by thebgpikester** [comment]
verified working also.
