### ISSUE TITLE
SchedulerDispachter throwing errors: just started today - possible bug

### ISSUE THREAD

**Issue by falcon76** [FlightControl-Master/MOOSE#818]
2018-03-04 18:46:46.471 INFO    SCRIPTING: Error in SCHEDULER function:[string "Scripts/Moose/Tasking/Task.lua"]:234: attempt to index global 'TASKINFO' (a nil value)
2018-03-04 18:46:46.471 INFO    SCRIPTING: stack traceback:
	[string "Scripts/Moose/Core/Fsm.lua"]:566: in function <[string "Scripts/Moose/Core/Fsm.lua"]:562>
	[string "Scripts/Moose/Tasking/Task.lua"]:234: in function 'New'
	[string "Scripts/Moose/Tasking/Task_A2G.lua"]:58: in function 'New'
	[string "Scripts/Moose/Tasking/Task_A2G.lua"]:479: in function 'New'
	[string "Scripts/Moose/Tasking/Task_A2G_Dispatcher.lua"]:363: in function 'ProcessDetected'
	[string "Scripts/Moose/Tasking/DetectionManager.lua"]:148: in function <[string "Scripts/Moose/Tasking/DetectionManager.lua"]:142>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "Scripts/Moose/Core/Fsm.lua"]:574: in function '_call_handler'
	[string "Scripts/Moose/Core/Fsm.lua"]:641: in function <[string "Scripts/Moose/Core/Fsm.lua"]:579>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "Scripts/Moose/Core/ScheduleDispatcher.lua"]:130: in function <[string "Scripts/Moose/Core/ScheduleDispatcher.lua"]:89>

**Comment by funkyfranky** [comment]
you got the latest MOOSE_INCLUDE?

**Comment by falcon76** [comment]
I am using GitHub desktop to sync and dynamic file to use the latest since I am mission developing

**Comment by falcon76** [comment]
FunkyFranky,
looks like you were right, I had not updated my include file in the ME, but now when I call my mission file dynamically it includes the \Scripts\moose\ and then adds c:\debug\.  I am using the __Moose.include('c:/debug/','missionfile.lua')  command.  I noticed that the orig include file had MOOSE.Include = function( LuaPath, IncludeFile ) but the new one is missing the LuaPath here is the new call __Moose.Include = function( IncludeFile )  was this intentional on FC part?

**Comment by FlightControl-User** [comment]
Yup. It was confusing to have two parameters.

**Comment by FlightControl-User** [comment]
Yup. It was confusing to have two parameters.
