### ISSUE TITLE
UTILS: Possible minor bug in Utils.lua

### ISSUE THREAD

**Issue by pellelil** [FlightControl-Master/MOOSE#819]
Trying to get up to speed with LUA and MOOSE at the same time, so forgive me if I'm wrong. But in line 333 in Utils.LUA (UTILS.tostringLL) there seems to be small bug formatting Lat/Lon as DMS. To me the longitude should be formatted with 3 in stead of 2. So I guess it should be "string.format('%03d', lonDeg)" in stead of "string.format('%02d', lonDeg)" ?

**Comment by pellelil** [comment]
Don't know if its by design, but it seams that latHemi and lonHemi are also omitted from the return value-

**Comment by pellelil** [comment]
To clearify I am not using this function, or have seen it produce a "wrong" output, however I am looking into the MOOSE source in order to learn some LUA. Regarding latHemi and lonHemi my bad, I just looked at the source on the web and here some of the source is clipped (not visible). So I now see that latHemi and lonHemi indeed are within the return value.

However I still think that the longitude degrees should be formattet med 3 digits in stead of 2, hence "string.format('%03d', lonDeg)" in stead of "string.format('%02d', lonDeg)" (replace "2" with "3")?

**Comment by FlightControl-User** [comment]
OK! Thank you for the information! That is a very sharp observation.
May I ask you, is the code good and readable?

**Comment by FlightControl-User** [comment]
Fixed. Closing.

**Comment by pellelil** [comment]
Can't complain about the code, of what I have seen so far. Naturally there a things I would have done differently be it comes down to personal taste. The MOOSE framework is HUGE (especially learning LUA at the same time). I want to learn some more LUA and get deeper into the framework before trying to make missions with MOOSE. Great job you'we done (and those contributing), and all of the videos help as well :-)

**Comment by FlightControl-User** [comment]
Cool. Have also a look at the donation pls. We could use some help.

**Comment by pellelil** [comment]
Just had a look, it seems you now changed both Lat and Lon-degrees to 3 digits:
    return string.format('%03d', latDeg) .. ' ' .. string.format('%02d', latMin) .. '\' ' .. string.format(secFrmtStr, latSec) .. '"' .. latHemi .. '   '
.. string.format('%03d', lonDeg) .. ' ' .. string.format('%02d', lonMin) .. '\' ' .. string.format(secFrmtStr, lonSec) .. 

The Latitude only needs 2 digits (-90 to 90), hence its only the Longitude that needs 3 (-180 to 180), but the sign is not included (instead latHemi/lonHemi i used).  :-)

**Comment by pellelil** [comment]
I've noticed that Routines.lua has many of "the same" functions as Utils, Hence the routines.tostringLL has the same (minor) "bug" formatting lonDeg with only 2 digits as in Utils.lua.

Can I ask why both Util.lua and Routines.lua have many of "the same" funktions? Only having them in one  place, bugs only have to be fixed once, and it should reduce the size of the framework (not a lot, but still) ?
