### ISSUE TITLE
Increase SPAWN flexibility

### ISSUE THREAD

**Issue by CraigOwen** [FlightControl-Master/MOOSE#82]
Users are able to use the spawn class to spawn groups into a zone. Using the function SPAWN:SpawnToZone() it should be possible to use the scheduled function as well as the limit initializer.

A great benefit would be, to even have the SPAWN:NewWithAlias as an initialization, because that way it should be easy to set up GROUP_SETS by the name given as alias.

So u could end up having a single Group (Unit) Template in the mission designer, and spawn this one to a zone e.g. 20 times. If those grous (units) die, they would respawn in the given interval and thus be filled up to the given limit.

**Comment by FlightControl-Master** [comment]
thanks, understood ...

**Comment by FlightControl-Master** [comment]
Done
