### ISSUE TITLE
TASK-CARGO-TRANSPORT - Double Command Center menu in MP

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#821]
Thanks for getting menus for this working in dedicated MP

Issues observed - in mission that borrows code from tsk 211
Mission task accepted - 3 groups engs delivered to 3 LZ's

- [x] 1. When you have landed near the cargo troops, after a few seconds the menu does appear for boarding them, when you select for example F1 to board group Alpha ..... nothing happens, the menu stays on screen If I F12 and quit the menu and wait a few seconds then try it again - - it works then they try to board

- [x] 2. Of the 3 groups trying to board - 2 did it without problem, the third moved extremely slowly (snail speed_ but did not board, I had to lift off (to cancel) land a little bit away then try again - it worked this time (was close to all 3 groups when boarding began, they were not too far away)

- [x] 3. Limits - I tried using 4 groups in a version of my mission - is there a limit on groups it can handle of 3? I did not have option to board group #4?

- [x] 4. Deployment zones - I tried putting oil rigs at sea as drop off points for the cargo infantry, when I landed on the Rig no option came up for unload. I think this maybe a DCS World issue - I cannot remember if I got a message on text chat for Has landed from the game engine - will test again later on today

**Comment by baluballa** [comment]
I have tested my cargo task with new Moose.lua, and same error. It works like assigning mission and route to cargo, and land. However when I choose board the cargo start to run in opposite direction. Also I try to fly closer, it auto aborts boarding... Fine... But still they run away from me when I choose board again. Then I started fly a bit around. I got the option to choose route to cargo and script is reporting you have arrived land. But now after landed I had to cancel routing manually. Then I got the option to board, but again they run away from my helicopter

**Comment by shadowze** [comment]
Update

5. In Dedicated MP, once you have successfully completed a cargo task (delivered cargo to destination)
the task remains in the F10 menu, so you cannot do any other tasks once you complete as task
Verified this twice in MP

**Comment by thebgpikester** [comment]
I saw this in SP by the way. WIth BAI. so think its generic issue with completion of tasks. SHould be a new issue though, it's lost here.

**Comment by FlightControl-User** [comment]
On #3 : You need to declare each group as a CARGO in the script. Read carefully the code. Had you declared the cargo like this?:


``` lua
  local EngineersCargoAlpha = CARGO_GROUP:New( GROUP:FindByName( "Engineers Alpha" ), "Engineers", "Team Alpha", 500 ):RespawnOnDestroyed(true)  
  local EngineersCargoBeta = CARGO_GROUP:New( GROUP:FindByName( "Engineers Beta" ), "Engineers", "Team Beta", 500 ):RespawnOnDestroyed(true)
  local EngineersCargoGamma = CARGO_GROUP:New( GROUP:FindByName( "Engineers Gamma" ), "Engineers", "Team Gamma", 500 ):RespawnOnDestroyed(true)

```

and added a 4th cargo object?

**Comment by FlightControl-User** [comment]
On #4: There is probably no landing event generated when landing on oil rigs. I am closing this here and you need to make a separate report of this on github here and flag it as a dcs bug.

**Comment by FlightControl-User** [comment]
@shadowze 
On #2: How did you board these troops and how close were you near the troops with your helo? Were these troops being borded simulaneously?

**Comment by shadowze** [comment]
#1 observed a few times were F10 menu was present and when i navigated it to board and pressed the key eg F2 ... nothing happened

#2 Was group was less than 50m distance from heli, each group loaded one group at a time, i did not try all at once

#3 I declared another cargo group same set-up as the other first 3 from demo mission

**Comment by FlightControl-User** [comment]
On issue #1 that is because the menu is set by a timer. I cannot let the timer run every second as this we too much CPU overhead. This cannot be solved. 
Also, when the menu is set, it can be that underlying menu items are still generated. When this happens, it appears as if the menu is there, but when you select it, indeed, nothing happens. I can't really change this but you need to have some patience with the menu in transport.

**Comment by FlightControl-User** [comment]
On issue #3. There is a limit on the amount of UNITS that can be boarded. This was done to be realistic. If you are boarding in a helo like an UH-1H a group of 20 units of infantry, that would be totally unrealistic.
The limit was set to 2, I've upgraded it by default to 6.
There is a method `TASK_CARGO:SetCargoLimit( CargoLimit )` that can be used to configure the limit of cargo that the APC can handle.

**Comment by FlightControl-User** [comment]
On Issue #2 i've right now published a couple of changes. 
Can you retest the process pls? @shadowze ?

thanks for the feedback!

**Comment by shadowze** [comment]
#1 ok i get u, menu has to be generated first then back end code is enabled

#3 think iam not communicating right 
I use TASK_CARGO:SetCargoLimit( 8 )
i have 4 groups of 2 AI, I can board 3 groups (6 units) but there is no menu option for board group #4

#2 will test shortly

**Comment by shadowze** [comment]
#2 just tested, nope still not working, once you are assigned the task and then when you complete it and get the good job message the task is still in your F10 menu and you are prevented from accepting any more tasks

**Comment by shadowze** [comment]
#2 oh and if you even disconnect from the dedicated server and reconnect, you still cannot accept any new tasks

**Comment by FlightControl-User** [comment]
I am going to take my time for this and test all carefully.

**Comment by FlightControl-User** [comment]
Maybe in two weeks I'll come beck on this.

**Comment by shadowze** [comment]
#2 re-tested, the issue is actually the menu F10 not removing the task you have completed, so you can add a new task but you now have 2 tasks in your F10 list

Is there something weird if you create a new task later on eg use an ME trigger to call some code that adds a new task to the task list ?

**Comment by FlightControl-User** [comment]
I will check this in detail now.

**Comment by FlightControl-User** [comment]
So, the "task" menu is not the "task" menu, but the "action" menu of cargo transport. The task menu is under the command center and works fine. When you accept a cargo transport task, a temporary menu is created to help the player execute the actions for the cargo transportation, like routing, boarding, unboarding cargo. I've tested and resolved that when a task is completed, the action menu is removed. On top, task success is achieved when all the cargo is deployed within one of the zones.
So, when you have 2 cargo transport tasks for the same mission, you need to board and transport the cargo and unboard the cargo of the first task. Task will go into completion and then you can accept teh 2nd task of hte mission under the command center.

**Comment by FlightControl-User** [comment]
I've done some changes, so pls reload the latest moose.lua from the MOOSE_INCLUDE repo.

**Comment by Delta-99** [comment]
@shadowze can you test this and let us know if fixed? If so we can close this issue

**Comment by shadowze** [comment]
tested, in dedicated MP the same mission duplicates the HQ MISSION menu
see 2 attached pictures

you want my mission as well ?

![menu_sp](https://user-images.githubusercontent.com/30597073/37571331-54d0a0aa-2af3-11e8-8c5f-e381d213a063.jpg)

![menu_dedicated_mp](https://user-images.githubusercontent.com/30597073/37571333-5b12a59e-2af3-11e8-9715-cbf552fa667a.jpg)

**Comment by FlightControl-User** [comment]
Yes, please, can you post it in a pm on github? Thanks!

**Comment by shadowze** [comment]
I pmed you the mission in discord

**Comment by FlightControl-User** [comment]
Thank

**Comment by FlightControl-User** [comment]
@shadowze got it, updating this ....

**Comment by shadowze** [comment]
status using
2018-03-27T13:08:00.0000000Z-81822f25bd9ab8750d30e9f430a75197953bb0d6 ***' build moose_.lua

mission 
Weapons_Freeflight_Training_v3.01.08.test.miz
I will PM you this mission file in discord Sven 

started a mountain mi-8 hot

1. single menu in dedicated MP - good job
2. Selected MISSION transport - Troops relief (was able to board units ok)
3. flew units to drop off point - landed - unloaded - task success
4. Mission complete on this worked ok
5. Selected MISSION transport - Troops home (boarded units ok)
5. flew units back to start at drop off point - landed - unloaded - task  success
6. But this task still in F10 list - was able to list other MISSIONS
 end of line

**Comment by FlightControl-User** [comment]
Ok

**Comment by FlightControl-User** [comment]
Closing all, not anymore happening.
