### ISSUE TITLE
A2A_CAP not stopping when far from base

### ISSUE THREAD

**Issue by Ked57** [FlightControl-Master/MOOSE#823]
I've set the DisengageRadius to be 170 km, when the ennemy is engaged and step out of that zone IA still goes for it. Tactical overview shows no target and logs even show that the detection system doesn't see the ennemy anymore.

I've tried to remove the cap mission from the IA in the mission editor but it doesn't change much

**Comment by thebgpikester** [comment]
This is without border or with? fire the code up here, we had a long discussion on discord and it seems CAP controls are wonky, but can't describe it well.

**Comment by Ked57** [comment]
``DetectionSetGroup = SET_GROUP:New()
DetectionSetGroup:FilterPrefixes( { "B_EWRNETWORK_AWACS "})--, "B_EWRNETWORK_PATRIOT" } )
DetectionSetGroup:FilterStart()
DetectionSetGroup:Flush()

Detection = DETECTION_AREAS:New( DetectionSetGroup, 30000 )

-- Setup the A2A dispatcher, and initialize it.
A2ADispatcher = AI_A2A_DISPATCHER:New( Detection )

A2ADispatcher:SetTacticalDisplay( true )

A2ADispatcher:SetDisengageRadius( 170000 )

BorderZone = ZONE_POLYGON:New( "Border", GROUP:FindByName( "Border" ) )
A2ADispatcher:SetBorderZone( BorderZone )
 A2ADispatcher:SetSquadron( "Senaki", AIRBASE.Caucasus.Senaki_Kolkhi, { "SQ_SENAKI_QR" }, 4 )
 A2ADispatcher:SetSquadronGrouping( "Kutaisi", 2 )

  -- CAP Squadron execution.
  CAP_GEORGIA = ZONE_POLYGON:New( "CAP_GEORGIA", GROUP:FindByName( "CAP_GEORGIA" ) )
  A2ADispatcher:SetSquadronCap( "Kutaisi", CAP_GEORGIA, 4000, 10000, 600, 700, 900, 2000, "BARO" )
  A2ADispatcher:SetSquadronCapInterval( "Kutaisi", 1, 30, 60, 2 )

  A2ADispatcher:SetSquadronFuelThreshold( "Kutaisi", 0.35 )``

A2ADispatcher works fine but the cap never disengages even if tactical display shows it's not targeting anything anymore

**Comment by Ked57** [comment]
Another clue i have is the tactical overview showing no target but the CAP state is still "Engaging" and no Patrolling. It seems like it's not changing when the detection system doesn't see the enemy anymore

**Comment by FlightControl-User** [comment]
@Ked57 is this a showstopper?

**Comment by Ked57** [comment]
what do you mean by showstopper ?

**Comment by FlightControl-User** [comment]
I mean, is this an urgent issue and does it have to be fixed urgently?

**Comment by Ked57** [comment]
Oh, well it doesn't stop CAP from working but they chase you until they die so it's pretty much like CAP from ME

**Comment by thebgpikester** [comment]
It's probably up there with important issues, because it makes CAP either not engage or engage without limit! Which is quite an effect.

**Comment by thebgpikester** [comment]
dup of #933 (this is original)
Reproduced. see more details in #933

**Comment by thebgpikester** [comment]
Good find. Can we set up some sort of testing to confirm? If you give me the line (on current Dev branch) and change to be made I already have the original test mission I can confirm it in 20-40 mins and we can propose the change.

**Comment by CSG1-Shogun** [comment]
I tested adjusting that line in moose.lua from RTB = false to RTB = true, but still fails. 

I tested with the MOOSE example mission to show Disengage Radius but AI never gets an RTB to return home.

**Comment by FlightControl-User** [comment]
OK. checking in 2.5.

**Comment by baluballa** [comment]
Can't find function.
