### ISSUE TITLE
CARGO_GROUP:onafterBoarding() bug

### ISSUE THREAD

**Issue by funkyfranky** [FlightControl-Master/MOOSE#824]
If one or more units of a group defined as CARGO_GROUP died, the CARGO_GROUP:Board() command does not trigger the CARGO_GRUOP:OnEnterLoaded() function.

Fix:
In the CARGO_GROUP:onafterBoarding() function the line
if (not Cargo:is( "Loaded" )) then Boarded=false end
must be
if (not Cargo:is( "Loaded" )) **and (not Cargo:is( "Destroyed" )**) then Boarded=false end

**Comment by FlightControl-User** [comment]
Thank you!

**Comment by FlightControl-User** [comment]
Implemented.

**Comment by funkyfranky** [comment]
@Delta-99 @FlightControl-User Working like a charm for me now :)

**Comment by FlightControl-User** [comment]
closed
