### ISSUE TITLE
DESIGNATE: Limit the types of designation to be used.

### ISSUE THREAD

**Issue by eric963** [FlightControl-Master/MOOSE#828]
Be able to set the designating unit to only use a certain type of designation method (Lase or Smoke)

**Comment by FlightControl-User** [comment]
Ok. I get the requirement. But how to implement. I can provide an option to deactivate smoking and illumination, but it will be for the whole set of Recce!

**Comment by eric963** [comment]
That would work.
Are we currently able to have more than 1 reccesetgroup ?
Something like...

RecceSetGroupA = SET_GROUP:New():FilterPrefixes( "Recce" ):FilterStart()
RecceSetGroupB = SET_GROUP:New():FilterPrefixes( "FAC" ):FilterStart()

**Comment by FlightControl-User** [comment]
Yes! Set classes allow to set a FilterPrefix table. 

RecceSetGroup = SET_GROUP:New():FilterPrefixes( { "Recce", "FAC" } ):FilterStart()

Depends what you wanna do. 

In your example above you have 2 Recce groups that can be used in two detection objects. 

In my example you have one group filtering from two prefixes.
