### ISSUE TITLE
Ground units should not be given a default speed of 999 km/h in COORDINATE:WaypointGround()

### ISSUE THREAD

**Issue by funkyfranky** [FlightControl-Master/MOOSE#831]
If ground units get a speed higher than their max. physically possible speed, DCS "thinks" that they have reached their waypoint before they actually do.

This often makes units stop, before they arrive at their intended destination.

If a units are given a speed which they can "physically" achieve, this problem is much less pronounced or almost not existent.

**Comment by thebgpikester** [comment]
I believe the default 11kts (whatever that is in kmph or m/s) would be ideal to default to, but I'ver never tested to see if any of the ground units fail to achieve 11kts, but DCS seems to start there. Good find by the way!!

**Comment by FlightControl-User** [comment]
@funkyfranky confirmed. thanks frank.

**Comment by FlightControl-User** [comment]
How much is 11kts in meters per second?

**Comment by thebgpikester** [comment]
5.65889

**Comment by FlightControl-User** [comment]
ok!

**Comment by FlightControl-User** [comment]
Fixed and pushed to master.

**Comment by FlightControl-User** [comment]
closing
