### ISSUE TITLE
bug conception with ZoneCaptureCoalition class 

### ISSUE THREAD

**Issue by Blast-1** [FlightControl-Master/MOOSE#832]
Hi, I'm reporting this tricky issue with the _**ZoneCaptureCoaltion**_ class that you can reproduce easily:
1. Make a zone and put inside it one red unit as light vehicle and one blue unit as heavy tank so that the blue can win.

2. In the mission script write:
> 
> CaptureZone = ZONE:New( "zone test" )
> ZoneCaptureCoalition = ZONE_CAPTURE_COALITION:New( CaptureZone, coalition.side.RED ) 
> 
> function ZoneCaptureCoalition:OnAfterGuard(From, Event, To)  
>   son_WinSite:ToAll()
>   MESSAGE:New("The test site has been captured! good job!", 20):ToAll() 
> end

The result is when the blue are inside a red zone (zone is in **attacked state**) and the blue finally win the zone then the _**OnAfterCapture**_ event is not triggered. I found out that the zone must transit to the **empty state** which is not possible in this very common example! 

 I think the finite state machine should add another link to work properly:
https://imgur.com/a/lG5Od

I am not sure if this is the reason of that issue but who knows.

**Comment by FlightControl-User** [comment]
Please check the feedback of wingthor on discord and my notes regarding my change I've implemented! You need to adapt your mission.

**Comment by FlightControl-User** [comment]
So, did you expect the result to be there immediately? there is a time delay of about 15 seconds.

**Comment by FlightControl-User** [comment]
@Blast-1 hi. Did your issue get resolved?

**Comment by Blast-1** [comment]
@FlightControl-User i've not testing yet the suggestions you gave me on discord. I was away of that, dealing with trolls. They tend to multiply when spring is coming...
I'll test it as soon as i can and report here if its ok.

**Comment by FlightControl-User** [comment]
Ok ok ok :)

**Comment by FlightControl-User** [comment]
Moving this to release 2.4 for a fix.

**Comment by FlightControl-User** [comment]
This is fixed. No bug.
