### ISSUE TITLE
bug - radio:beacon - only supports a single beacon

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#833]
https://flightcontrol-master.github.io/MOOSE_DOCS/Documentation/Radio.html##(BEACON).RadioBeacon

tried messing about with example mission and added another unit, tried to add a second beacon
it seems to over ride the first beacon ?

first beacon is at 190Khz
second is at 400Khz

checked on huey ADF

**Comment by shadowze** [comment]
just to be clear it is the audio ogg file that stops working in the first beacon when hte second one start
ADF works on both

[RAD-010 - 2 Beacons.zip](https://github.com/FlightControl-Master/MOOSE/files/1822633/RAD-010.-.2.Beacons.zip)
see attached file I have added 1 more beacon, both are soldiers

**Comment by FlightControl-User** [comment]
not for now...
