### ISSUE TITLE
RANGE: Line 550

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#834]
`self:E(RANGE.id..string.fromat("ERROR! Could not find bombing target %s.", name))`

Guess it should be `string.format`

Regards 

Wingthor

**Comment by funkyfranky** [comment]
Thanks, will fix!

**Comment by funkyfranky** [comment]
Fixed in https://github.com/FlightControl-Master/MOOSE/pull/840

**Comment by funkyfranky** [comment]
Typo fixed so we can close this one.
