### ISSUE TITLE
Suggestion: Add new SET_GROUP:ForEachGroupAnyInZone / GROUP:IsAnyInZone

### ISSUE THREAD

**Issue by Zyfr** [FlightControl-Master/MOOSE#836]
Add a new function to provide the ability to detect if ANY unit of a group is within a Zone, regardless of whether it is Completely or Partially in a Zone.

Avoids the need to evaluate both 
- SET_GROUP:ForEachGroupCompletelyInZone
- SET_GROUP:ForEachGroupPartlyInZone

Scenario: a Group is moving into a Zone, these function would capture and return true as soon as any Unit in the Group enters the zone and will remain true until the last Unit leaves the zone.

Some musings. It's almost the inverse of GROUP:IsNotInZone
--- Returns true if any units of the group are within a @{Zone}.
-- @param #GROUP self
-- @param Core.Zone#ZONE_BASE Zone The zone to test.
-- @return #boolean Returns true if any unit of the Group is within the @{Zone#ZONE_BASE}
function GROUP:IsAnyInZone( Zone )
  self:F2( { self.GroupName, Zone } )
  
  if not self:IsAlive() then return false end
    
  for UnitID, UnitData in pairs( self:GetUnits() ) do
    local Unit = UnitData -- Wrapper.Unit#UNIT
    if Zone:IsVec3InZone( Unit:GetVec3() ) then
      return true
    end
  end
  return false
end

--- Iterate the SET_GROUP and call an iterator function for each **alive** GROUP that has any unit in the @{Zone}, providing the GROUP and optional parameters to the called function.
-- @param #SET_GROUP self
-- @param Core.Zone#ZONE ZoneObject The Zone to be tested for.
-- @param #function IteratorFunction The function that will be called when there is an alive GROUP in the SET_GROUP. The function needs to accept a GROUP parameter.
-- @return #SET_GROUP self
function SET_GROUP:ForEachGroupAnyInZone( ZoneObject, IteratorFunction, ... )
  self:F2( arg )
  
  self:ForEach( IteratorFunction, arg, self:GetSet(),
    --- @param Core.Zone#ZONE_BASE ZoneObject
    -- @param Wrapper.Group#GROUP GroupObject
    function( ZoneObject, GroupObject )
      if GroupObject:IsAnyInZone( ZoneObject ) then
        return true
      else
        return false
      end
    end, { ZoneObject } )

  return self
end

Note: The above is something I just copy/pasted/modified while creating this request... I'll test it later tonight once I get back to my DCS machine.

**Comment by FlightControl-User** [comment]
checking in 2.4.

**Comment by FlightControl-User** [comment]
ok, thank you @Zyfr for your kind sources. I have added these methods in the code base. good idea and thanks!
