### ISSUE TITLE
SETs used to define CARGO Groups - Seems to be missing GetUnits functions

### ISSUE THREAD

**Issue by falcon76** [FlightControl-Master/MOOSE#837]
Based on this video:  https://www.youtube.com/watch?v=D3YQ18JxRRY
It appears that it is possible to use the Set:Base class as the Group for the CARGO:New call.  but the issue is that when I try to implement this same structure the SET class is missing the GetUnit function and I receive a error when replicating the same calls in the video.
example:
``function` ChinookUnitAlphaOne:OnEventLand( EventData )
      if ChinookUnitAlphaOne:IsInZone( ZnChinookPickup) then
         ChinookUnitAlphaOne:MessageToBlue("Landed at Pickup LZ. Escort maintain orbit.", 35, "Chinook One-One Landing")
         ChinookOneCargoSet = SET_UNIT:New()
         SetAssaultInfOne:ForEachUnitCompletelyInZone( ZnAssaultSpawnOne,
         function (UnitObject)
         ChinookOneCargoSet:Add( UnitObject:GetName(), CARGO_UNIT:New( UnitObject, "Infantry", "Infantry", 76, 2000, 25))
         UnitObject:E( {UnitObject:GetName(), "I am in Alpha Inf One Zone." })
         end)
         ChinookOneCargo = CARGO_GROUP:New( ChinookOneCargoSet, "Infantry", "Infantry", 2000, 25)
         ChinookOneCargo:Board( ChinookUnitAlphaOne , 3 )         
      end -- End the if ChinookUnitAlphaOne
      if ChinookUnitAlphaOne:IsInZone( ZnBravoTroop ) then 
         ChinookUnitAlphaOne:MessageToBlue("Landed at DropOff LZ Bravo, Escort, maintain CAP while troops disembark.", 35, "Chinook One-One DropOff")
         Assault_1_Cargo:UnBoard( ZnBravoFOB )
      end
      local Chinook1OrbitVector = SpawnGroupChinook1:GetCoordinate()
      local OrbitChinook1DCSTask = SpawnGroupChinookEscort1:TaskOrbitCircleAtVec2( Chinook1OrbitVector:GetVec2(), 100, 81)
      SpawnGroupChinookEscort1:ClearTasks()
      SpawnGroupChinookEscort1:SetTask(OrbitChinook1DCSTask, 1) 
  end
 
   function CreateSpawnOneInf()
    local InfOne = 0
    while( InfOne <= 30) 
    do         
      Assault_1_Cargo_GP = Spawn_Assault_Inf_1:SpawnInZone(ZnAssaultSpawnOne,true)
      InfOne = InfOne + 1
    end
   end
   CreateSpawnOneInf() `'

Error in Log:
2018-03-17 21:28:09.627 INFO    SCRIPTING: Error in SCHEDULER function:[string "C:\Users\<UserName>\AppData\Local\Temp\DCS\/~mis000009CF"]:22953: attempt to call method 'GetUnits' (a nil value)
2018-03-17 21:28:09.627 INFO    SCRIPTING: stack traceback:
	[string "C:\Users\<UserName>\AppData\Local\Temp\DCS\/~mis000009CF"]:5691: in function 'GetUnits'
	[string "C:\Users\<UserName>\AppData\Local\Temp\DCS\/~mis000009CF"]:22953: in function 'New'
	[string "C:\Users\<UserName>\AppData\Local\Temp\DCS\/~mis00000A2B"]:254: in function <[string "C:\Users\<UserName>\AppData\Local\Temp\DCS\/~mis00000A2B"]:229>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "C:\Users\<UserName>\AppData\Local\Temp\DCS\/~mis000009CF"]:5874: in function 'onEvent'
	[string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>

Potential solution:
1. Add the GROUP:GetUnit(UnitNumber) to the SET: class
2. Modify the GARGO:New to accept the SET:GetSet(UnitNumber) inplace of the GetUnit(UnitNumber) when a set is given as the first parameter of CARGO:New().

Possible issues with some Set classes 
1. not all unit in a group are in the Set ( some in zone, some out of zone) can those in the zone still be boarded but not the unit outside the zone.
2. not all sets types can be cargos maybe.

Why do we need this?  
the array function does not work because of the DCS bug to create only the first of the unit in array on not the whole array.
Scenario:
Create 30 units in Pickup Zone - load those 30 in chinook - chinook fly's to LZ - unboards 30 units - human picks up 6 units of 30 and fly's to Area of Engagement and drops off.  This is repeated until the inventory of assault troops are dispatched.  

Disclaimer:  I may be doing this all wrong but it seems like you should be able to create a set and board the set on a chopper.
thanks 
Falcon_76th

**Comment by FlightControl-User** [comment]
I have been looking into this problem, but it is a bit unclear to me what you are trying to achieve. It is also the English. You're using some kind of translator?

**Comment by FlightControl-User** [comment]
closing, no answer.
