### ISSUE TITLE
DESINGATE no option for lase/smoke

### ISSUE THREAD

**Issue by eric963** [FlightControl-Master/MOOSE#839]
Just updated to most recent moose and moose missions tonight.  While trying to figure out how to use DESIGNATE:SETMISSION and struggling I decided to run DES -201 and then DES - 010.

In both those mission target groups where detected but the menu to select lase or smoke would not appear.

If I swap out the moouse_.lua from 3/17/18 the lase/smoke menu appears.

**Comment by FlightControl-User** [comment]
Fixed

**Comment by eric963** [comment]
Working fine.

**Comment by FlightControl-User** [comment]
closing
