### ISSUE TITLE
TSK-100/010 TASK_A2G_BAI and TASK_A2G_SEAD issues in client hosted/dedicated server

### ISSUE THREAD

**Issue by eric963** [FlightControl-Master/MOOSE#842]
Mission work fine in single player. In client hosted MP it displays 2 "Command Center Bravo" entries.  one displays the task correctly the other does not
![tsk100cmp](https://user-images.githubusercontent.com/20633883/37872343-9424033e-2fd3-11e8-8517-2bad514f63e0.PNG)

On dedicated server machine It displays a single Command Center but when you select it the only option that's displays is "Mission Reports"

![tsk100ded](https://user-images.githubusercontent.com/20633883/37872353-dcb4c002-2fd3-11e8-8668-f1f05318d791.PNG)

**Comment by FlightControl-User** [comment]
this is fixed.
