### ISSUE TITLE
ZONE_CAPTURE_COALITION Enhancement

### ISSUE THREAD

**Issue by Quadrafarian** [FlightControl-Master/MOOSE#844]
Would it be possible to have a setting so only ground units are detected/count towards zone capture in this class?

or a setting so a unit is in zone for X amount of time or 2-3 scheduler cycles to try and filter out aircraft flying into/through zone as the scheduler triggers.

**Comment by FlightControl-User** [comment]
Ok. Understood.

**Comment by thebgpikester** [comment]
+1

**Comment by thebgpikester** [comment]
Bump!

**Comment by FlightControl-User** [comment]
Boingggg

**Comment by Quadrafarian** [comment]
Bump!

**Comment by Quadrafarian** [comment]
Added in recent MOOSE update
Seems to be working properly
