### ISSUE TITLE
DESIGNATE:SetMission not putting Designate Menu under Mission Menu

### ISSUE THREAD

**Issue by eric963** [FlightControl-Master/MOOSE#846]
Does this in SP, Client Hosted and Dedicate Server
![setmission1](https://user-images.githubusercontent.com/20633883/37996018-dc945662-3205-11e8-842c-a717e4171ca4.PNG)
![setmission2](https://user-images.githubusercontent.com/20633883/37996025-de97cf5c-3205-11e8-8a75-c78e8f9a5ca8.PNG)
![setmission3](https://user-images.githubusercontent.com/20633883/37996028-e03b5b9e-3205-11e8-9c5c-b348f18acb3e.PNG)

**Comment by FlightControl-User** [comment]
Ok. There is an activity planned to "integrate" designate with A2G tasking.

**Comment by FlightControl-User** [comment]
Meaning, that under each task menu you should see designate indicators.

**Comment by FlightControl-User** [comment]
I think this is fixed, but i'll check.
