### ISSUE TITLE
AI_A2A_DISPATCHER SetDefaultFuelThreshold & SetSquadronFuelThreshold

### ISSUE THREAD

**Issue by eric963** [FlightControl-Master/MOOSE#851]
Neither SetDefaultFuelThreshold & SetSquadronFuelThreshold are working.  Using AID -011 Fuel Threshold Test has the follow setting

A2ADispatcher:SetDefaultFuelThreshold( 0.4 )
![fuel](https://user-images.githubusercontent.com/20633883/38158271-0aae6a82-345f-11e8-8be8-4cade4507bf3.PNG)

**Comment by eric963** [comment]
This is Release 2.3.1 and 2.4.a.  Happens in both AID-011 and AID-016

**Comment by n00dl3st** [comment]
Can confirm I also have this issue.

`BLUFOR_A2A_Dispatcher:SetDefaultFuelThreshold( 0.90 )
BLUFOR_A2A_Dispatcher:SetDefaultTanker( "BLUFOR_AAR_1" )`

CAP Flights in my mission don't return to tanker until about <10% remaining in the tank. 

There is also a typo in the docs. 
[https://flightcontrol-master.github.io/MOOSE_DOCS/Documentation/AI_A2A_Dispatcher.html##(AI_A2A_DISPATCHER).SetDefaultFuelThreshold]()

SetDefaultFuelThreshold Is the correct statement, but docs reference, "DefaultRefuelThreshold"

**Comment by thebgpikester** [comment]
There was a change in Dev on Fuel, can you recheck on Dev?

**Comment by eric963** [comment]
Just rechecked with latest dev version and still not working.

**Comment by FlightControl-User** [comment]
OK. will check in 2.4.

**Comment by FlightControl-User** [comment]
okay @eric963 i fixed this. I was my mistake. Sorry. And actually it really messed up bigtime the code. Due to your error log, i could fix this!
