### ISSUE TITLE
COMMANDCENTER:ReportSummary() function contains a bug

### ISSUE THREAD

**Issue by funkyfranky** [FlightControl-Master/MOOSE#853]
In line 435
Report:Add( " - " .. Mission:ReportSummary() )
the Mission:ReportSummary() functions expects the argument "ReportGroup", i.e. should read
Report:Add( " - " .. Mission:ReportSummary(ReportGroup) )

**Comment by thebgpikester** [comment]
Did this get fixed in dev?

**Comment by FlightControl-User** [comment]
i think so by now ... I'll check in 2.4.

**Comment by FlightControl-User** [comment]
OK. fixed this. Closing.
