### ISSUE TITLE
A2G Task Dispatching issue with detected group containing sead unit

### ISSUE THREAD

**Issue by eric963** [FlightControl-Master/MOOSE#854]
FAC detects a group of ground units containing a SAM and 2 tanks.  Task SEAD.001 mission gets created.  Join the task and destroy the SAM unit. 
Get he message Task SEAD.001 is successful. Good Job!

After that no task is generated for the remaining 2 tanks.
Attached is my simple test mission.  Does this in SP, Client hosted and dedicated.

[A2GSispatcherseadgroup.zip](https://github.com/FlightControl-Master/MOOSE/files/1865938/A2GSispatcherseadgroup.zip)

**Comment by thebgpikester** [comment]
Need help to check all these, sorry, no chance anyone will likely do it unless it's handed on a plate, if you know what I mean.

**Comment by eric963** [comment]
Ok, retested this with both release and dev version.

This was using DETECTION_AREAS


Both release and dev version works correctly only if there is only just the SEAD unit in the detection area or the SEAD unit and one other unit.

If the detection area contains more then 2 units, once the sead unit is destroyed a CAS task for the remaining units is never generated.

[detectiontgts3.zip](https://github.com/FlightControl-Master/MOOSE/files/2163748/detectiontgts3.zip)

**Comment by FlightControl-User** [comment]
ok. will check in 2.4.

**Comment by FlightControl-User** [comment]
@eric963 ok, checking this at the moment ...

**Comment by FlightControl-User** [comment]
@eric963 so, the split of tasking in a task "planned" state is still working. So a SEAD task with other vehicles is split into a SEAD and a CAS task when the units move out of areas radius. So that is still working, which is good.

**Comment by FlightControl-User** [comment]
@eric963 Now here's the discussion that we need to have. I had intended ONLY to split tasks when these tasks were "planned". Not when "assigned"! In assigned mode, the player will have to execute the task, that is, destroy all units in the task scope. So let me test now the SEAD scope. Because when all units in scope are destroyed, then the task should become complete and indeed, then a CAS task should be created for the remaining units. So, i am testing this now ...

**Comment by FlightControl-User** [comment]
So, this is fixed ... a new CAS task is generated after the SEAD targets have been destroyed and the SEAD task is flagged as completed. See the attached picture.

![screen_180930_070947](https://user-images.githubusercontent.com/13690775/46253609-08f60900-c480-11e8-9495-87b1df17f9a9.png)

Please test again, i will close this issue and will flag this as tested.
