### ISSUE TITLE
TASK_A2G_Dispatcher unit killed message only appearing for 1 client

### ISSUE THREAD

**Issue by eric963** [FlightControl-Master/MOOSE#856]
Using TASK_A2G_DISPATCHER in a mission running on dedicated server with 2 clients connecting.  Both clients join the "Planned Task". The "Report Task Details" showed both clients assigned to the task.  

When either client destroys one of the targets only one client gets the message...

"You have destroyed a target.
Your group assigned with task BAI.001 has
1 targets  (1 of T-55) left to be destroyed."

Once the last target gets destroyed both clients do get the ..

"HQ - Task BAI.001 is successful! Good Job!"

It did not matter what client slot the player choose, only the first client to join the task would receive the "destroyed messages".

My partner ran out of time or we would have ran a couple more tests.  Attached is the log file.  There are some scheduler errors in it.

[dcs.txt](https://github.com/FlightControl-Master/MOOSE/files/1869798/dcs.txt)

**Comment by FlightControl-User** [comment]
OK. will check in 2.4.

**Comment by FlightControl-User** [comment]
How can we retest this?

**Comment by FlightControl-User** [comment]
@eric963 i need a squadron to reconfirm this test. Can somebody help me testing this?

**Comment by thebgpikester** [comment]
I reviewed the logs from March 2018. They are full of errors relating to the code. The code has changed many times since and this ticket won't be actioned until we reproduce on recent persons.
