### ISSUE TITLE
COORDINATE.MarkToAll:  Read/Write is hard coded, should be opened up to the end user

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#857]
After 2.5 when this function was added to a fourth variable, Boolean for readonly. Frank fixed this quickly by hardcoding true. What we need is this variable true false to be available to the user in MOOSE in MarkToAll and the other functions using it to be configurable.

**Comment by funkyfranky** [comment]
There is also a fifth option that triggers an annoying message if a mark is set. Maybe we should also include this (optionally) - just in case...

**Comment by funkyfranky** [comment]
Was implemented. Closing...
