### ISSUE TITLE
TASK_CARGO_TRANSPORT: Issues with multiple cargo transporting by multiple clients

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#859]
*Multiple cargos:*
------------------------------------------------------------------

- [x] 1. Still option for loading stuff from too far for my liking. 150 meters, (its ok for troops but not crates)

- [x] 2. Can load several crates a a time., seems like only one got unloaded but they stack.

- [x] 3. After two trips rest of cargo is lost in menu. 

- [x] 4. Crates disappear, or menu for loading becomes gone from menu after unloading at deploy site,

- [x] 5. Routing to crates does not work.

*Multi player:* (TESTED WITH Shadowze)
--------------------------------------------------

- [x] 6. Can load same group as Shadowze,After he has chosen Engineers

- [x] 7. Slingload cargo hangs in the air after dropped, see pictures. Most likely Eagle Dynamics.

Same issues as in mission above

**Comment by FlightControl-User** [comment]
- [ ] I get option to disembark Shadowz loaded engineers.

- [ ] Did not get option to load cargo after arrived near it

- [ ] Does still not detect when lading in "routing" mode for Crates

- [ ] After flying around I a bit I got finally got the menu for boarding Workers. engineers gone, no option might be due to Shadowz disconnected.

- [ ] Seems to be able to route to several location at same time

- [ ] Still can load several crates

- [ ] Chooses route to cargo after loaded metal and engines, then task menu was lost. And cannot rejoin

- [ ] Back to spectators and back to cockpit, menu for joying is back 

- [ ] Now on menu I got option to unload the stuff which I loaded before I got to Spectators.

- [ ] Cargo stack due to several crate in Heli unloaded from same spot.

- [ ] After routed and, landed, you have arrived, no option for load, and the routing option for the "routing target" is gone.

- [ ] And Task menu goes away after choosing to route to another crate. So guess I need to get back to spectators to get it back.

**Comment by FlightControl-User** [comment]
@baluballa 

_1. Still option for loading stuff from too far for my liking. 150 meters, (its ok for troops but not crates)_

There is a near parameter. You can specify the load distance yourself. Updated missions.

**Fixed**

**Comment by FlightControl-User** [comment]
@baluballa 

_2. Can load several crates a a time., seems like only one got unloaded but they stack._

I've implemented now that when unloaded, the cargo will be spread in a band around the carrier between 30 meters range and 10 meters where the carrier is placed. This will minimize the risk of cargo stacking, and will not block the carrier with placed cargo.

**Fixed**

**Comment by FlightControl-User** [comment]
@baluballa 

_3. After two trips rest of cargo is lost in menu._

I can'r resimulator this... Flagging this off as I've done lots of improvements. If it returns we'll need to investigate this deeper.

**Fixed**

**Comment by FlightControl-User** [comment]
@baluballa 

_4. Crates disappear, or menu for loading becomes gone from menu after unloading at deploy site,_

Crates don't dissappear. Menu for loading a crate indeed is not anymore selectable when the crate is deployed in the deployment site. This is by design.

Why would this be a problem?

**Open**

**Comment by FlightControl-User** [comment]
@baluballa 

_5. Routing to crates does not work._

Routing to crates does work. However, when the player is within the reporting zone of the crate, the routing options are not anymore visible.

**Fixed**

**Comment by FlightControl-User** [comment]
@baluballa 

_6. Can load same group as Shadowze,After he has chosen Engineers_

I've done a fix for that. But we need to test it.

**For testing**

**Comment by FlightControl-User** [comment]
@baluballa 

_7. Slingload cargo hangs in the air after dropped, see pictures. Most likely Eagle Dynamics._

This is a bug report to ED that is required. If you have a picture of it I can send it to ED as a report.

**Fixed**

**Comment by FlightControl-User** [comment]
@baluballa 

_8. I get option to disembark Shadowz loaded engineers._

I've done a fix for this. This needs to be retested with 2 or more players within loading range of each other with one loaded cargo in the helicopter of one player. 
Also, we need to test that multiple players load cargo, and nobody should be able to load cargo of the other players!

**Test**

**Comment by FlightControl-User** [comment]
@baluballa 

_9. Did not get option to load cargo after arrived near it_

This needs further investigation. It seems it has to do with landing.

**Investigate**

**Comment by FlightControl-User** [comment]
@baluballa 

_10. Does still not detect when lading in "routing" mode for Crates_

Same issue as #9.

**Investigate**

**Comment by FlightControl-User** [comment]
@baluballa 

_11. After flying around I a bit I got finally got the menu for boarding Workers. engineers gone, no option might be due to Shadowz disconnected._

I've increased the menu updating frequency to 1 second.
When the engineers were in the helicopter of Shadowze, and he disconnected, then the helicopter dissapeared. As a result, the engineers are indeed gone!
There is an option to automatically respawn then cargo in such cases.
I will flag this off as fixed as the issue seems to be the same as #9 and #10.

**Fixed**

**Comment by FlightControl-User** [comment]
@baluballa 

_12. Seems to be able to route to several location at same time_

This is by design. The player should be able to change routes immediately.

**Fixed**

**Comment by FlightControl-User** [comment]
@baluballa 

_13. Still can load several crates_

Fixed this. A player can now load maximum one item. This can be a group, package, crate, slingload.
I'll build in the CARGO_GROUP:New that the size of the group cannot be larger than 10 units and must be of:
- infantry
- mortars
- Stingers

**Fixed**

**Comment by FlightControl-User** [comment]
@baluballa 

_14. Chooses route to cargo after loaded metal and engines, then task menu was lost. And cannot rejoin_

Task menu lost? That is strange. Now when a cargo is loaded, you won't be able anymore to route to another cargo. So, this problem is fixed i think.

**Fixed**

**Comment by FlightControl-User** [comment]
@baluballa 

_15. Cargo stack due to several crate in Heli unloaded from same spot._

Same issue as #2.

**Fixed**

**Comment by FlightControl-User** [comment]
@baluballa 

_16. After routed and, landed, you have arrived, no option for load, and the routing option for the "routing target" is gone._

Same issue as #9 and #10. The latter comment about no menu to route to target is by design. When within reporting range, there is no routing requirement anymore.

**Fixed**

**Comment by FlightControl-User** [comment]
@baluballa 

_17. And Task menu goes away after choosing to route to another crate. So guess I need to get back to spectators to get it back._

We need to talk about this, what **exactly** happened here? Can you explain the scenario a bit more clear?

**Open**

**Comment by FlightControl-User** [comment]
I am now updating the code and the missions for a new mission test version.

**Comment by FlightControl-User** [comment]
@baluballa I have fixed a lot of issues and also carefully checked the situation on the routing. All my previous comments were wrong. I've done a complete update how the routing works...
So this is the latest situation:

- Only one cargo object can be loaded.
- Only one routing action is possible at the time. Once a routing action is selected, the player cannot select another routing action.
- When a routing action is cancelled, the new routing actions reappear.

On top, there are more modifications on cargo.

- Crates and slingloads are "representable" cargo. When a truck is nearby within 500 meters, the truck will report the locations of the cargo. The truck name is used to identify itself, but you can also set a callsign on it.
- When you move near a slingloadable cargo, then these are also reported.
- When within a report zone of a cargo, the cargo will indicate the action like "Board, Load or Slingload" ...
- When near enough to the cargo, the cargo will indicate the action like "boarding, loading, slingloading" ...
- When a group cargo is running towards the carrier, and boards, that carrier will receive a message from the CC as loaded.

I think a lot of things are now fixed and i think it is time to retest with a new test mission in a larger group.

**Retest All**

**Comment by gunterlund** [comment]
Can #2 (cargo stacking) be done with the AI_Cargo module also so statics dont pile up?

**Comment by FlightControl-User** [comment]
All was tested and fixed...

**Comment by FlightControl-User** [comment]
- [ ] 18. When routing to the deployzone, after landing, i need to cancel the routing before i can unboard.

**Comment by FlightControl-User** [comment]
Fixed issue 18.

**Comment by FlightControl-User** [comment]
@gunterlund can this be handled at another issue please?
