### ISSUE TITLE
DCS-BUG-10 - Vehicles that move according the path set on the map, cannot hold movement.

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#860]
https://forums.eagle.ru/showthread.php?t=205923

**Comment by FlightControl-User** [comment]
Response from BIGNEWY:

Hi Sven

just to feed back on this one, it is not considered a bug, the team have said

When a user takes control of a unit all commands are dropped, this is working as intended.

thanks

**Comment by thebgpikester** [comment]
Should be closed, do keep DCS bugs open?
