### ISSUE TITLE
Unable to check if statics are in zone

### ISSUE THREAD

**Issue by FubarBundy** [FlightControl-Master/MOOSE#862]
IsCompletelyInZone, :IsPartlyInZone IsNotInZone not presently working for statics and possibly shipping groups (need to confirm). Following example works if "Target" is a group but not if is a static or shipping group.

function Sub_Menu_Alive ()
     Message = "\n\nIntel has identified ".. (Description) ..(location)
     for k,v in ipairs (Red_AA_Zones) do
     if 
     Target:IsCompletelyInZone(v) or Target:IsPartlyInZone(v)  then
     AA_Threat = "\n\nAA threat thought to be HIGH\n\n"
     elseif
     Target:IsNotInZone(v) then
     AA_Threat = "\n\nAA threat thought to be low\n\n"
     end
     end
     Client_Message ()
  end

**Comment by thebgpikester** [comment]
There is the scanobjects method for this.
