### ISSUE TITLE
AID:SetSquadron( "Nalchik", AIRBASE.Caucasus.Nalchik, ( "51TFS" ), 1 ) does not observe resource limit

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#874]
`:SetSquadron( "Nalchik", AIRBASE.Caucasus.Nalchik, ( "51TFS" ), 1 )`
The last parameter as I understand is an optional "Resource" parameter describing the limit of planes as an integer. This parameter is ignored. You can set it to 1 and planes continues to take off from the squadron ad infinitum.

The parameter should count down to 0 then I would expect no more planes from that squadron to depart.

I looked through MOOSE and can find some references to Resources and these were linked to some events. I think the issue with monitoring landing and crashing is that they aren't that consistent and I'd suggest just count takeoffs at the airbase and deduct, and add landing events at the airbase. Crashes and engine stops are completely inconsistent and just don't add up due to being able to crash, stop engine, together or separately, depnding if the plane was "injured", hit the ground first or disintegrated mid air.

Possible solution sample code. Note this doesn't get granular if there are multiple sqn's at the same airbase, it would get complicated there. 
Need to check take off for deduction and landing for addition. If AI lands elsewhere it will add to a different sqn's pool or get lost. Tricky situation.
```

Graveyard={} -- can be preloaded, read from file or blank.
AnyTO = EVENTHANDLER:New()
AnyTO:HandleEvent( EVENTS.Takeoff )

function AnyTO:OnEventTakeoff( EventData )
--if EventData.IniCategory == 0 then 
if Graveyard[EventData.place:getName()] then
env.info("Deducting Take Off")
  Graveyard[EventData.place:getName()] = Graveyard[EventData.place:getName()] - 1
  else Graveyard[EventData.place:getName()] = 1
  env.info("WARNING! Non scripted Airfield has been written to disk.")
end
  EventData.IniUnit:MessageToAll( EventData.place:getName() .. ": " .. EventData.IniTypeName .. " departed.", 15, "Departure" )
--end
end
```
This code will populate the table with airbase names as a key and a value for the number of available aircraft. That can be used as the resource. I've generally been using this and wanted to use the resource as the table entry for the airfield.

**Comment by thebgpikester** [comment]
Bump, is there an alternative way to stop a Squadron Spawning if I do the counting myself?

**Comment by jtoppins** [comment]
I like the possible solution. I think handling multiple squadrons from the same airbase is already able to be handled as the unit has a reference to its squadron. See the AI_A2A_DISPATCHER:OnEventLand() handler, it checks if a unit has a squadron and if it does it does extra things.

**Comment by raikix** [comment]
Some things to play around with:
Possible solution to the limiting/resource thing at least for now by doing this: 
GCICAP_Red = AI_A2A_GCICAP:NewWithBorder( { "Red EWR" }, { "Red CAP" }, "Red BORDER", nil, nil, nil, nil, nil, 4)

This is within the ai_a2a_gci though, for clarity. In singleplayer testing on one base it respects the tested resource value of 4, 1 and 0 when that is predefined. Attaching code if anyone wants to play around with it.

What it does not do is respect the 1 value when defending planes get shot down. Then it keeps spawning stuff. Tried the same with value 2, that halted spawns on 2 bases after their respective resource was spent.

Sorry if this isn't very exhaustive, hope it's helpful!

below is the lua script:
`--GCICAP_Red = AI_A2A_GCICAP:NewWithBorder("Red EWR", "Red CAP", "Red BORDER")

GCICAP_Red = AI_A2A_GCICAP:NewWithBorder( { "Red EWR" }, { "Red CAP" }, "Red BORDER", nil, nil, nil, nil, nil, 2)

--Spawn state
GCICAP_Red:SetDefaultTakeoffFromRunway()

--End state
GCICAP_Red:SetDefaultLandingAtRunway()

--Sqn Grouping
GCICAP_Red:SetDefaultGrouping(2)

--Set Balance
GCICAP_Red:SetDefaultOverhead(1)`

**Comment by baluballa** [comment]
Its a bit old. In case still relevant, reopen.
