### ISSUE TITLE
Task Dispatching- Cargo

### ISSUE THREAD

**Issue by 132nd-Entropy** [FlightControl-Master/MOOSE#883]
humble suggestion: 
would be more immersive to in additon/instead of the BRA calls by the CC if a beacon would be placed on the pickup/dropoff zones so pilots could fly the needles instead. 
We use a variation of this by using dynamically spawned CTLD radiobeacons which works very nicely imo. Maybe this could be included here also

**Comment by FlightControl-User** [comment]
We can do beacons. It is planned as part of CARGO.

**Comment by FlightControl-User** [comment]
That being said... beacons is a bit more complex.  I first would like to have a comprehensive system ready.

**Comment by FlightControl-User** [comment]
closing this, off topic.
