### ISSUE TITLE
RANGE: Targets Coords and Strafe Range direction

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#884]
Several planes has sophisticated computers. Would be nice if coordinates of range bomb targets could be given in various formats.

Also information about strafe pit approach heading could be given in Range information report.

Regards

Wingthor

**Comment by funkyfranky** [comment]
good idea with the strafe pit heading!
what would be the coordinate formats you need. maybe it could be the same as defined in SETTINGS?

**Comment by baluballa** [comment]
The Moose built in setting feature would be awesome for coordinates format.

**Comment by FlightControl-User** [comment]
Frank, I can advise you how to use and implement it

**Comment by baluballa** [comment]
That would be cool. Lest agree on a time in Discord...

Its Wingthor BTW:

**Comment by funkyfranky** [comment]
This was implemented quite some time ago. Closing....
