### ISSUE TITLE
CSAR test mission is bugged and does not work

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#885]
https://github.com/FlightControl-Master/MOOSE_MISSIONS/tree/develop/TAD%20-%20Task%20Dispatching/CGO%20-%20Cargo%20Dispatching/TAD-CGO-000%20-%20CSAR%20Test

does not work right due to helicopter being shot to bits by enemy planes

I have posted a working version

**Comment by FlightControl-User** [comment]
Thanks!

**Comment by shadowze** [comment]
https://cdn.discordapp.com/attachments/430607025140006913/438372850315952128/this_works_better_TAD-CGO-000_-_CSAR_Test.miz

get it here

**Comment by shadowze** [comment]
closing out
