### ISSUE TITLE
TAD-CGO-008 Settings menu doesn't always show in SP or MP

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#887]
In fact it rarely shows for me. Out of about 5-6 attempts I think I only saw the menu once. I figured it wasn't implemented but then it was there once. This is in both MP and SP.

I'm sure this is just an overall settings menu issue common across all missions but mentioning it here as one can probably easily reproduce with this mission.

**Comment by baluballa** [comment]
...
