### ISSUE TITLE
TAD-CGO-008 Cargo drop-off BR messages do not show again

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#889]
Once you reach a cargo drop-off location and the mission tells you to land, there is no way to find the drop-off location again if for example you don't land but keep flying and then are outside the zone. OR lets say you drop the cargo just outside the zone and want to pick it up again and put it back in the zone. This doesn't' seem doable or at least not that I could figure out.

I tried cancelling the drop-off directions and turning them back on but that didn't help either. At that point I get no more BR task drop-off messages.

**Comment by thebgpikester** [comment]
Not sure we can redo this, so archiving for now. Feel free to re-raise.
