### ISSUE TITLE
RATMANAGER not randomizing added templates properly

### ISSUE THREAD

**Issue by Sci-fer** [FlightControl-Master/MOOSE#893]
RATMANAGER doesn't vary added templates when minimum is set to 0 like `manager:Add(RAT_group, 0)`
```
local manager = RATMANAGER:New(10)

local templates = {
	-- OPFOR airplanes
	'An-26', 'An-30', 'IL-76', 'Yak-40', 'A-50',
	'Tu-142', 'IL-78', 'KC-130', 'Tu-95',
	
	-- OPFOR helicopters
	'Ka-27', 'Mi-26', 'Mi-8',
	
	-- BLUFOR airplanes
	'C-101', 'C-130', 'C-17', 'E-2', 'KC-135', 'S-3',
	'Hawk',
	
	-- BLUFOR helicopters
	'CH-47', 'CH-53', 'OH-58', 'SA342', 'SH-60',
	'UH-1H', 'UH-60'
}

for index, item in pairs(templates) do
	local RAT_group = RAT:New(item)
	manager:Add(RAT_group, 0)
end

manager:Start()
```
At every mission restart it spawns mostly the same aircrafts e.g. Yak-40(s) and C-130(s). Other aircrafts may be spawned but always with a lot of repetitions.

p.s. If minimum is set to 1 RATMANAGER(ntot) won't limit the total flights and spawn every template in the table.

Am I missing anything?

Kind regards

**Comment by FlightControl-User** [comment]
@funkyfranky did you already have a look at this? what we do with this?
