### ISSUE TITLE
Requesting a method for counting units in zone by coalition

### ISSUE THREAD

**Issue by Fargo007** [FlightControl-Master/MOOSE#913]
We talked about this on discord.

Zone.lua - 

So after conducting a scan on units, it would be useful to have a method that returns a count of units in the zone, and optionally via arguments a count by coalition.

**Comment by FlightControl-User** [comment]
ok, i'll check if this can be made within this release.

**Comment by FlightControl-User** [comment]
Is it okay i move this to "future"? unless you find the energy to write this function yourself and post it here?

**Comment by Fargo007** [comment]
Totally fine to move it, Sir!

**Comment by thebgpikester** [comment]
This has been done.
