### ISSUE TITLE
Carrier going to road to pick up cargo no matter the circumstances.

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#920]
New issue with AI_Cargo_Dispatcher... If the cargo is sitting right next to the carrier to start, the carrier will go look for a road to connect on then come back and pick up the cargo even though the cargo started 10 feet from the carrier. The carrier may travel a good long distance to touch the road before it comes to pick up cargo.

**Comment by funkyfranky** [comment]
Logic for ground on road task has been improved. Carrier will go directly (i.e. not on the road) when the distance on road is 10x larger than the direct path (or distance on road is <5% of total path length).
So can we close this?
