### ISSUE TITLE
S_EVENT_MARK_* give a wrong vec3 position of the placed mark.

### ISSUE THREAD

**Issue by funkyfranky** [FlightControl-Master/MOOSE#921]
DCS bug of the newly introduced S_EVENT_MARK_* functions. Event.pos vec3 is wrong. In particular, the x and z components are switched.
To correct
    -- Convert (wrong x-->z, z-->x) vec3
    -- TODO: This needs to be "fixed", once DCS gives the correct numbers for x and z.
    -- local vec3={y=Event.pos.y, x=Event.pos.x, z=Event.pos.z}
    local vec3={y=Event.pos.y, x=Event.pos.z, z=Event.pos.x}
    
    -- Get coordinate from vec3.
    local _coord=COORDINATE:NewFromVec3(vec3)
This needs to be fixed in ARTY classs onces DCS fixes the error.

**Comment by thebgpikester** [comment]
Wondering if we posted this as a bug on the forums? The first we will likely know it gets fixed is when arty starts missing by about 5000 miles!

**Comment by FlightControl-User** [comment]
This is still the case?

**Comment by victorcotap** [comment]
I use this piece of code to retrieve the COORDINATE from the event
```
        local vec3 = {y=Event.pos.y, x=Event.pos.z, z=Event.pos.x}
        local coord = COORDINATE:NewFromVec3(vec3)
        coord.y = coord:GetLandHeight()
```

**Comment by funkyfranky** [comment]
I reported - multiple times also directly in the russian bug section.
https://forums.eagle.ru/showthread.php?t=213275
