### ISSUE TITLE
ATC_Ground Kicking You on a Runway

### ISSUE THREAD

**Issue by WolfofQuebec** [FlightControl-Master/MOOSE#925]
The ATC_Ground kicks me half way down the Secondary runway  @(RWY 02) at Sochi-Adler.

**Comment by FlightControl-User** [comment]
Oops. Sorry. Well need to check that

**Comment by FlightControl-User** [comment]
This must be because of the overlapping runways. I check two runways there. If you are out of bounds on runway one, but in bounds runway two, then you'll get kicked.  This is wrong.

**Comment by WolfofQuebec** [comment]
Thats fine. Ill disable it in the meantime.

**Comment by FlightControl-User** [comment]
Ok. Thanks.

**Comment by baluballa** [comment]
Overdue...
