### ISSUE TITLE
TASK_CARGO_DISPATCHER:New throws errors in Develop branch of MOOSE

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#926]
used 2018-06-03T20:03:35 of static MOOSE with TASK_CARGO_DISPATCHER:New = all OK
tried
2018-06-16T17:14:09 = not ok throws an error
Using same basic script in both

2018-06-17 12:16:16.110 INFO    SCRIPTING:  34775( 37590)/I:             MISSION02770.AddTask({[1]===> Adding TASK ,[TaskName]=AA Repair.001,[MissionName]=Cargo Ops,})
2018-06-17 12:16:16.115 INFO    SCRIPTING:  34775( 37866)/I:             MISSION02770.AddTask({[1]===> Adding TASK ,[TaskName]=AA Repair.001,[MissionName]=Cargo Ops,})
2018-06-17 12:16:16.122 ERROR   DCS: Mission script error: : [string "C:\Users\ss\AppData\Local\Temp\DCS.openbeta\/~mis00004581"]:37818: Task does not exist
stack traceback:
	[C]: ?
	[C]: in function 'error'
	[string "C:\Users\ss\AppData\Local\Temp\DCS.openbeta\/~mis00004581"]:37818: in function 'SetTransportDeployZone'
	[string "D:\games\PG_Havoc_moose_scripts.lua"]:288: in function 'start_sea_cargo_tasks'
	[string "D:\games\PG_Havoc_moose_scripts.lua"]:403: in function 'start_sea_tasks'
	[string "D:\games\PG_Havoc_moose_scripts.lua"]:435: in main chunk

-- Cargo build task AA Repair 
  i_AA_repair_count = 0  -- used to check both items delivered
  SAMSite = SPAWN:New( "SAM Site 1" )

  MissionAA_Repair1 = MISSION:New( CC_SEA1, s_cargo, s_cargo_d, "Transport Cargo", coalition.side.BLUE )
  
  TaskDispatcherAA = TASK_CARGO_DISPATCHER:New( MissionAA_Repair1, HelicopterSEA1 )
  
  local CargoSetAA_materials = SET_CARGO:New():FilterTypes( "AA_materials" ):FilterStart()

  local AA_partsCargo = CARGO_SLINGLOAD:New( STATIC:FindByName( "AA parts" ), "AA_materials", "AA parts", 150, 50 ):RespawnOnDestroyed( true )
  local AA_CargoGroup = CARGO_GROUP:New( GROUP:FindByName( "Repair team 1" ), "AA_materials", "Repair team 1", 250 ):RespawnOnDestroyed( true )
  
  TaskDispatcherAA:AddTransportTask( "AA Repair", CargoSetAA_materials, "Transport Repair team 1 & AA parts crate to Abu Musa Island Airport" )
  TaskDispatcherAA:SetTransportDeployZone( "AA Repair.001", ZONE:New( "AA Repair area" ) )
  
  AA_Repair1Task = TaskDispatcherAA:GetTransportTask( "AA Repair.001" )

**Comment by FlightControl-User** [comment]
I've seen it. Sorry. I will see how to fix.

**Comment by FlightControl-User** [comment]
Can you show me the fragment of code you have used? I have changed the interface a lot there.

**Comment by FlightControl-User** [comment]
With reason by the way. Now it is much more simple.

**Comment by shadowze** [comment]
see modified first post, it is basically a copy of your demo mission code with names changed

**Comment by shadowze** [comment]
I will be happy to test this, currently as is, most of your demo missions with cargo in
https://github.com/FlightControl-Master/MOOSE_MISSIONS/tree/develop/TAD%20-%20Task%20Dispatching/CGO%20-%20Cargo%20Dispatching

will be not working right now

**Comment by FlightControl-User** [comment]
The interface to setup transport tasks has been changed a little bit.
The method `TASK_CARGO_DISPATCHER:AddTransportTask()` now returns a **TASK** object!

example:
```lua
local FactoryTask = TaskDispatcher:AddTransportTask( "Transport liquids", CargoSetLiquids, "Transport the milk, gas, fuel, oil to the factory." )
TaskDispatcher:SetTransportDeployZone( FactoryTask, ZONE:New( "Factory" ) )
```

This is important, as the FactoryTask now needs to be given as a paramter to the `TaskDispatcher:SetTransportDeployZone` method.

In your version, the first paramter to that method will be the name of the task (a string I guess), but that is really bad. Now, the task object is passed, which is much better.

As a result, the task object can now also be used to catch the events, as in the following example:

```lua
function WorkplaceTask:OnAfterCargoDeployed( From, Event, To, TaskUnit, Cargo, DeployZone )
  Helos[ math.random(1,#Helos) ]:Spawn()
  EnemyHelos[ math.random(1,#EnemyHelos) ]:Spawn()

end
```


This would be the complete reworked code fragment, which you can find in mission TAD-CGO-008:

```lua
local WorkplaceTask = TaskDispatcher:AddTransportTask( "Build a Workplace", CargoSetWorkmaterials, "Transport the workers, engineers and the equipment near the Workplace." )
TaskDispatcher:SetTransportDeployZone( WorkplaceTask, ZONE:New( "Workplace" ) )

Helos = { SPAWN:New( "Helicopters 1" ), SPAWN:New( "Helicopters 2" ), SPAWN:New( "Helicopters 3" ), SPAWN:New( "Helicopters 4" ), SPAWN:New( "Helicopters 5" ) }

EnemyHelos = { SPAWN:New( "Enemy Helicopters 1" ), SPAWN:New( "Enemy Helicopters 2" ), SPAWN:New( "Enemy Helicopters 3" ) }

function WorkplaceTask:OnAfterCargoDeployed( From, Event, To, TaskUnit, Cargo, DeployZone )
  Helos[ math.random(1,#Helos) ]:Spawn()
  EnemyHelos[ math.random(1,#EnemyHelos) ]:Spawn()

end
```

**Comment by FlightControl-User** [comment]
I have updated all test mission to this format. For the CSAR dispatcher, this format is not required.

**Comment by FlightControl-User** [comment]
@shadowze have a look at the code examples in the revised TAD-CGO missions, and check your code to incorporate the API change. I am flagging this off as fixed. If your tests aren't working, please reopen this one and we'll look in detail.
