### ISSUE TITLE
AI_A2A_DISPATCHER: when a unit gets shot down they are immediately deleted

### ISSUE THREAD

**Issue by jtoppins** [FlightControl-Master/MOOSE#932]
Preconditions:
A CAP squadron is set with AI_A2A_DISPATCHER:SetSquadronLandingAtEngineShutdown()

Observed Problem:
When this CAP engages and gets shotdown the unit is immediately deleted instead of seeing the plane crash into the ground.

Believed Code Problem:
This appears to be the result of the OnEngineShutdown() event firing and deleting the unit. Though I am not sure when the event handler is registered. If it is registered at unit spawn time this would align with the observation.

Possible Solution:
If the scripting engine allows register the OnEngineShutdown() handler in the OnLand() handler, preventing the odd deletion behavior.

**Comment by FlightControl-User** [comment]
Thanks. I'll check.

**Comment by thebgpikester** [comment]
oh wow I crossed posted the same possible cause in your possible solution to another bug.

 ... and not UNIT:InAir() 
first.

**Comment by jtoppins** [comment]
@thebgpikester good point, I didn't realize there was an "in air" check. That would be another way to do it. Though I am still partial to not registering a handler unless needed. It reduces the call chain and the delay of processing a handler that does nothing. The problem when registering handlers only when needed is the potential for races unless there is a facility to atomically register handlers.

**Comment by jtoppins** [comment]
I should mention I tested the proposed change on top of tag 2.3.1_-_New_Mark_Events but posted for pulling into develop.

**Comment by jtoppins** [comment]
With the merge of the pull request above I am pretty confident this fixes the issue. Please reopen if there are problems.
