### ISSUE TITLE
Ability to maintain targets in queue as they go in and out of range. 

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#942]
If an arty group is spawned in, and are out of range of a target that is detected by another unit, the arty program throws an error on _target. Need to have the ability to deal with targets that are detected by other units but may be out of range of artillery and either gracefully deal with out of range or keep in queue until target comes into range. This could be important for immobile arty units like mortars a that may get moved via cargo in and out of range of targets.

**Comment by FlightControl-User** [comment]
@funkyfranky ?

**Comment by FlightControl-User** [comment]
2.5?

**Comment by thebgpikester** [comment]
Frank can this be closed?

**Comment by funkyfranky** [comment]
I'd like to keep this in for now.
