### ISSUE TITLE
Settings: 7 figure DMS coords enhancement

### ISSUE THREAD

**Issue by thebgpikester** [FlightControl-Master/MOOSE#945]
DMS is accurate to within .2nm which is not so good for bombing via INS. A precision mode coordinate will be done for Hornet that could make use of 7 figures in the computer.

**Comment by FlightControl-User** [comment]
aha! i'll put that in 2.5

**Comment by Zyfr** [comment]
Morning, I had a go at adding a LL tostring func based on what was already existing. Snippets below.

COORDINATE.ToStringLLDMSDS = function( self, Settings )
  local LL_Accuracy = Settings and Settings.LL_Accuracy or _SETTINGS.LL_Accuracy
  local lat, lon = coord.LOtoLL( self:GetVec3() )
  return "LL DS, " .. UTILS.tostringLLDMSDS( lat, lon, LL_Accuracy, false )
end

UTILS.tostringLLDMSDS = function( lat, lon, acc)    
  local latHemi, lonHemi
  if lat > 0 then
    latHemi = 'N'
  else
    latHemi = 'S'
  end

  if lon > 0 then
    lonHemi = 'E'
  else
    lonHemi = 'W'
  end

  lat = math.abs(lat)
  lon = math.abs(lon)

  local latRem = lat
  local latDeg = math.floor(latRem)
  latRem = (latRem - latDeg)*60
  local latMin = math.floor(latRem)
  latRem = (latRem - latMin)*60
  local latSec = latRem

  local lonRem = lon
  local lonDeg = math.floor(lonRem)
  lonRem = (lonRem - lonDeg)*60
  local lonMin = math.floor(lonRem)
  lonRem = (lonRem - lonMin)*60
  local lonSec = lonRem   
  
  latSec = UTILS.Round(latSec, acc)
  lonSec = UTILS.Round(lonSec, acc)

  if latSec == 60 then
    latSec = 0
    latMin = latMin + 1
  end

  if lonSec == 60 then
    lonSec = 0
    lonMin = lonMin + 1
  end
  
  if latMin == 60 then
    latMin = 0
    latDeg = latDeg + 1
  end

  if lonMin == 60 then
    lonMin = 0
    lonDeg = lonDeg + 1
  end
  
  local secFrmtStr -- create the formatting string for the minutes place
  if acc <= 0 then  -- no decimal place.
    secFrmtStr = '%02d'
  else
    local width = 3 + acc  -- 01.310 - that's a width of 6, for example.
    secFrmtStr = '%0' .. width .. '.' .. acc .. 'f'
  end

  return string.format('%03d', latDeg) .. ' ' .. string.format('%02d', latMin) .. ' ' .. string.format(secFrmtStr, latSec) .. '\'' .. latHemi .. '   '
   .. string.format('%03d', lonDeg) .. ' ' .. string.format('%02d', lonMin) .. ' ' .. string.format(secFrmtStr, lonSec) .. '\'' .. lonHemi

end

**Comment by thebgpikester** [comment]
this is done.
