### ISSUE TITLE
SCORING: Seems to give positive score for DESTROY_PENALTY

### ISSUE THREAD

**Issue by baluballa** [FlightControl-Master/MOOSE#948]
In CVS file after a massive event with more that 30 players we get some DESTROY_PENALTY, these have positive score. 

Also some of the records the damages had same TargetName as PlayerName.

Wingthor

**Comment by baluballa** [comment]
It give negative HIT_PENALTY though :)

**Comment by thebgpikester** [comment]
It's unclear if this only happens with lots of players or you can reproduce with a simple mission and one player. Can you confirm?

**Comment by FlightControl-User** [comment]
i don't think this is hot, closing.

**Comment by baluballa** [comment]
Christ.... is it no way to branch from issue in github. 
Error is in function SCORING:ReportScoreAllSummary( PlayerGroup )
` local PlayerPenalty = PenaltyHits + PenaltyDestroys + PenaltyCoalitionChanges + ScoreGoals + PenaltyMissions`
**Should not be ScoreGoals  but PenaltyGoals**

**Comment by thebgpikester** [comment]
closing as fixed according to above
