### ISSUE TITLE
DEV BRANCH:DESIGNATE Smoke

### ISSUE THREAD

**Issue by eric963** [FlightControl-Master/MOOSE#950]
When selecting a target area and the selecting one of the smoke options the smoke does not appear.
The smoke option works correctly in the release version.

Attached is the dcs.log with the error messages

[dcs.log](https://github.com/FlightControl-Master/MOOSE/files/2161807/dcs.log)

**Comment by funkyfranky** [comment]
Should be fixed now

**Comment by funkyfranky** [comment]
No answer, but I'm pretty sure this bug is solved. Closing...
