### ISSUE TITLE
Carrier will not fly faster than 76knots

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#952]
SetPickupSpeed(270) andSetDeploySpeed(270) do not seem to have any impact on how fast the carrier flies. Tried code listed below and same results always occur. Carrier flies 76 knots to deploy zone.

local SetCargohelo = SET_CARGO:New():FilterTypes( "RAir" ):FilterStart()
local SetHelicopter = SET_GROUP:New():FilterPrefixes( "Russairlft" ):FilterStart()
local SetheloZones = SET_ZONE:New():FilterPrefixes( "Dropzone" ):FilterStart()

Russairlift = AI_CARGO_DISPATCHER_HELICOPTER:New( SetHelicopter, SetCargohelo, SetheloZones ) 
Russairlift:SetHomeZone( ZONE:FindByName( "Russ Pickup Zone" ) )
Russairlift:SetPickupSpeed(270,200)
Russairlift:SetDeploySpeed(270,200)

function Russairlift:OnAfterUnloaded( From, Event, To, Carrier, Cargo )
  local CargoGroup4 = Cargo:GetObject() -- Wrapper.Group#GROUP
  local Task = CargoGroup4:TaskRouteToZone( Marine, true, 10, "Vee" )
  CargoGroup4:SetTask( Task, 5 )
end

Russairlift:Start()

**Comment by funkyfranky** [comment]
Should be fixed now.

**Comment by funkyfranky** [comment]
Fixed. Closing...
