### ISSUE TITLE
Load Cargo before mission Start

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#953]
Need the ability to designate cargo and carrier and have them preloaded on Mission Start. The naming convention used to ID Cargo is too long to do this after mission start. For instance I cant spawn in units with the naming convention for Cargo and have the lua run the AI_Cargo_Dispatcher routine after mission start because the group name gets truncated on Spawn.

**Comment by gunterlund** [comment]
any thought on this

**Comment by FlightControl-User** [comment]
done.
