### ISSUE TITLE
AI_CARGO_DISPATCHER_APC needs option for off road pickup.

### ISSUE THREAD

**Issue by funkyfranky** [FlightControl-Master/MOOSE#954]
On maps where road infrastructure is sparse, it is not (always) advisable to have the carrier use roads. The carrier could be located just 1 km away from the cargo group and sometimes needs to drive 50 km on  road to actually pick up the cargo.

**Comment by gunterlund** [comment]
This was already submitted

**Comment by funkyfranky** [comment]
This has been partly solved by improving the logic. APC will go directly if path on road is 10 times longer than the direct way.

**Comment by FlightControl-User** [comment]
I will close this one. APCs need to transport cargo over large distances over roads.
