### ISSUE TITLE
ARTY - Rearming smoke and illumination does not adhere to initial levels set

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#955]
When using Smoke and Illumination rounds with a specified initial setting using SetIlluminationShells(50) for example and a mortar that has 20 regular rounds.

After rearming the regular 20 regular rounds both Illumination and smoke rounds will be set to 20 rather than 50.

Maybe this is by design the more I think about it. If so, can just close this issue.

**Comment by funkyfranky** [comment]
Yes, that is by design. The group needs to have the normal explosive shells to fire smoke/illumination or nuclear shells. So the max number of the "special" shells is the number of the normal shells.

**Comment by Delta-99** [comment]
Ok, that makes sense. I have no problem with the implementation I guess.
