### ISSUE TITLE
SPAWN: Group Template doesn't always register its group and units

### ISSUE THREAD

**Issue by Delta-99** [FlightControl-Master/MOOSE#960]
Now, I know this is going to be a very difficult one to debug but I have seen it happen over and over again in one of my missions. I thought it was a corrupt mission or semi-corrupt mission cause I used to go in, delete the group and then re-add it. **However**, after running the mission enough times I have concluded that this happens very infrequently. I may have proven it happens on the first load of the mission cause this is when it happened last and I investigated. Actually I was wrong. The first 2 runs of the mission it happened. But then I ran the mission a dozen times after that and it never happened again. I gave up trying to reproduce.

To note. This is a mission that was saved a few days ago. Nothing has been changed whatsoever. No DCS updates, no Moose updates. I'm not even running it from the editor as I wasn't making changes just playing it by loading it from the mission menu selection.

You can see the lines at 4:55, The GroupTemplate is registered but nothing further. Just an attempted spawn an failure because the group is not in the Moose database.

2nd run at 4:56 the group is registered. This time there is no script error but this is because this unit is randomly chosen to be spawned. In this case it was not chosen. But again you can see only the GroupTemplate is registered.

3rd and every other run that was executed we get a proper registration of the group and unit after the template. 4:57 timestamps. Can see that the Group and Unit were both registered milliseconds after the GroupTemplate was registered.

`
2018-07-20 04:55:38.588 INFO    SCRIPTING:  10603( 11191)/I:            DATABASE00003._RegisterGroupTemplate({[Coalition]=0,[Category]=2,[Group]=RUS BMP3 #001,[Country]=0,[Units]={[1]=RUS BMP3 #001,},})
2018-07-20 04:55:39.159 ERROR   DCS: Mission script error: : [string "C:\Users\tim\AppData\Local\Temp\DCS.25OpenBeta\/~mis00003B5E"]:21260: SPAWN:New: There is no group declared in the mission editor with SpawnTemplatePrefix = 'RUS BMP3 #001'
2018-07-20 04:56:44.892 INFO    SCRIPTING:  10603( 11191)/I:            DATABASE00003._RegisterGroupTemplate({[Coalition]=0,[Category]=2,[Group]=RUS BMP3 #001,[Country]=0,[Units]={[1]=RUS BMP3 #001,},})
2018-07-20 04:57:43.202 INFO    SCRIPTING:  10603( 11191)/I:            DATABASE00003._RegisterGroupTemplate({[Coalition]=0,[Category]=2,[Group]=RUS BMP3 #001,[Country]=0,[Units]={[1]=RUS BMP3 #001,},})
2018-07-20 04:57:43.211 INFO    SCRIPTING:  10728( 10061)/E:            DATABASE00003._RegisterGroupsAndUnits({[1]=Register Group:,[2]=RUS BMP3 #001,})
2018-07-20 04:57:43.211 INFO    SCRIPTING:  10414( 10729)/E:            DATABASE00003.AddGroup({[1]=Add GROUP:,[2]=RUS BMP3 #001,})
2018-07-20 04:57:43.211 INFO    SCRIPTING:  10734( 10061)/E:            DATABASE00003._RegisterGroupsAndUnits({[1]=Register Unit:,[2]=RUS BMP3 #001,})
`

**Comment by Delta-99** [comment]
Good idea @thebgpikester.

I'll cover a few things now that I'm thinking about it more:

- Don't think it has anything to do with the number of units registered. I use the exact same methods and spawning etc. in a number of my other missions and have NOT noticed the same behaviour.

- Don't think this is related to spawn at all or how units are spawned. Its basically that Moose somehow misses fully registering the unit in the database. It logs the fact that it read the GroupTemplate but it does NOT register the group and unit. This is the issue right there. Whether it is Moose or something bogus in the mission that Moose chokes on is probably where we have to concentrate our efforts.

- I do have a feeling this only happens with the LAST unit created in the ME. Have not proven this yet but it does only happen with this ONE particular unit and I believe it was the last one created in the ME. At first I thought this was a copy/paste issue and the group created in the ME was corrupt but that doesn't seem to be the case. Need to look at the .MIZ mission file or wherever groups are defined and see if there is something weird there.

I'm going to look at the Moose DATABASE registration to see if there is something going on there that could cause this OR if there is additional debugging statements that can be put in. Need to know how it works.

**Comment by Delta-99** [comment]
Ok, I examined my .MIZ mission file and found something. This is **MY ERROR**. Before I was spawning these units in randomly with MOOSE I was testing by spawning them in with a probability. Guess, what, this ONE unit was left with probability of 75% so 25% of the time this mission would fail. I didn't happen often!!!!!!

So going to close this as I don't think it is a bug. At least not in this case.

**Comment by funkyfranky** [comment]
Well, on the one hand it is good because if this were a bug, it really would have been down to the very core of MOOSE. On the other hand, if this was due to the probability thingy (which I never used) it will also be difficult to capture if users report unusual behavior of MOOSE.
So we should be keeping this in mind somehow! Maybe even raise another report to check whether the probability stuff is working correctly with MOOSE. Otherwise we might forget about it.

**Comment by Delta-99** [comment]
Good point @funkyfranky. I guess the question is then is this an enhancement? Can Moose determine if the probability is less that 100%? My guess is not but maybe. Not sure if this is exposed via the API or not. It seems Moose was somewhat aware of the template being defined but it couldn't create the Group and Unit (for potentially obvious reasons).

I would say that probability should be ignored by Moose if possible. Doesn't really make that much sense. OR, it could be handled by Moose internally. I've always handled this myself in code in that I don't always spawn the same units but rather randomly pick from a bunch.

**Comment by thebgpikester** [comment]
Weird,  would have thought a spawn template ignored probability just like it ignores activation. It still comes.

**Comment by Delta-99** [comment]
Well it probably kind of does but internally DCS probably doesn't create the unit (saving memory or whatever) and therefore Moose is able to determine that the GroupTemplate exists but then when building the GROUP and UNIT it can't. I read the code and it looks like it should spit out the fact that the GROUP or UNIT cannot be added to the database but I don't think I saw those lines in the log. I will look again cause I possibly only looked at my ERROR searching output and not gone back to all the lines in the output.
