### ISSUE TITLE
The cargo system picks up late activation units in its carrier list.

### ISSUE THREAD

**Issue by gunterlund** [FlightControl-Master/MOOSE#964]
What is happening is when you spawn groups you have a late activated unit that the spawn is keying off of. The spawn uses the name of that unit to generate the name of the spawned groups.  Now when you do the SET_GROUP command for the carriers its picking up this late activated group... When Moose cycles through the process to pick units up it hits this late activated unit and stops processing any carrier that comes after that unit
Example 7 groups with 7 carriers. Normally the get picked up and dropped off at Beachhead
       unit1 = GROUP:FindByName("USMCINF Plt#001")
       USMCCargo1 = CARGO_GROUP:New(unit1,"USMCINF","Platoon 1", 500, 25)
       unit2 = GROUP:FindByName("USMCINF Plt#002")
       USMCCargo2 = CARGO_GROUP:New(unit2,"USMCINF","Platoon 2", 500, 25)
       unit3 = GROUP:FindByName("USMCINF Plt#003")
       USMCCargo3 = CARGO_GROUP:New(unit3,"USMCINF","Platoon 3", 500, 25)
       unit4 = GROUP:FindByName("USMCINF Plt#004")
       USMCCargo4 = CARGO_GROUP:New(unit4,"USMCINF","Platoon 4", 500, 25)
       unit5 = GROUP:FindByName("USMCINF Plt#005")
       USMCCargo5 = CARGO_GROUP:New(unit5,"USMCINF","Platoon 5", 500, 25)
       unit6 = GROUP:FindByName("USMCINF Plt#006")
       USMCCargo6 = CARGO_GROUP:New(unit6,"USMCINF","Platoon 6", 500, 25)
       unit7 = GROUP:FindByName("USMCINF Plt#007")
       USMCCargo7 = CARGO_GROUP:New(unit7,"USMCINF","Platoon 7", 500, 25)
        USMCCargoSet = SET_CARGO:New():FilterTypes("USMCINF"):FilterStart()
        local SetZoneUSMC = SET_ZONE:New():FilterPrefixes("Beachhead"):FilterStart()
        local SetUSMCAPC=SET_GROUP:New():FilterPrefixes("USMCCarrier"):FilterStart()
        bla=AI_CARGO_DISPATCHER_APC:New(SetUSMCAPC,USMCCargoSet, SetZoneUSMC, 0)
        bla:SetPickupSpeed(40, 40)
        bla:SetDeploySpeed(50, 50)
        bla:Start()
 If you add an 8th carrier with the same prefix and put it as late activation some of the carriers wont be used depending on where they end up in the carrier array. Any unit listed after the late activated unit will not get used.

**Comment by FlightControl-User** [comment]
@gunterlund is this still an issue?
