### ISSUE TITLE
DESIGNATE function not working for 2.4.a - Patch 1

### ISSUE THREAD

**Issue by alvesobr** [FlightControl-Master/MOOSE#967]
Hi,
The mission and script attached used to work for Moose Release 2.3.1, but it’s not working for MOOSE Release 2.4.a - Patch 1

Can someone help?

Script:

US_HQ = GROUP:FindByName("HQ")

US_CC = COMMANDCENTER:New(US_HQ,"Command")

US_M1 = MISSION:New(US_CC,"A2G Targets","Primary",
                    "JTAC will indicate the position of the targets on the Island",
                    coalition.side.BLUE)

US_Attack = SET_GROUP:New():FilterPrefixes("US-AV"):FilterStart()

US_JTAC = SET_GROUP:New():FilterPrefixes("US - Jtac"):FilterStart()

US_Detect = DETECTION_AREAS:New(US_JTAC,1090)

Designate = DESIGNATE:New(US_CC,US_Detect,US_Attack,US_M1)
Designate:SetThreatLevelPrioritization(true)
Designate:SetLaserCodes(LaserCod)
Designate:SetFlashStatusMenu(true)
Designate:AddMenuLaserCode(1113,"Laser Code 1113")
Designate:AddMenuLaserCode(1462,"Laser Code 1462")
Designate:SetMaximumDesignations(2)

[Jtac.zip](https://github.com/FlightControl-Master/MOOSE/files/2233539/Jtac.zip)

**Comment by funkyfranky** [comment]
Fixed in develop branch
https://github.com/FlightControl-Master/MOOSE/tree/develop

**Comment by funkyfranky** [comment]
https://github.com/FlightControl-Master/MOOSE_INCLUDE/tree/develop
for the Moose.lua download

**Comment by funkyfranky** [comment]
No answer by OP, but I'm pretty sure this has been fixed. Closing...

**Comment by alvesobr** [comment]
Tks
