### ISSUE TITLE
DATABASE add Marks

### ISSUE THREAD

**Issue by funkyfranky** [FlightControl-Master/MOOSE#968]
https://wiki.hoggitworld.com/view/DCS_func_getMarkPanels
This new function allows to get all marks placed in a mission. These should be included in the DATABASE.

**Comment by Delta-99** [comment]
Is it really worthwhile to put it in the DATABASE? What are the advantages / disadvantages?

**Comment by funkyfranky** [comment]
Advantages:
- You can apply/add all kinds of other convenient functions, e.g. filter etc.
- It has a very similar structure to the other objects in the database.
- Who knows what crazy ideas people come up with ;)
Disadvantages:
- Needs to be implemented. But again, it's very similar to code that is already present. So the effort is okay.

**Comment by Delta-99** [comment]
Yeah, I guess it is worth doing.

**Comment by Delta-99** [comment]
I think this should be assigned to Moose Future not 2.4. We should try to get 2.4 out the door without adding features. Just my 2 cents.

**Comment by thebgpikester** [comment]
Is this doable by yourself Frank? The idea of the Mark ID being monitored in the DB is solid at least imo.
