### ISSUE TITLE
Cap takes about 18 or so minutes to spawn

### ISSUE THREAD

**Issue by grandpaSam** [FlightControl-Master/MOOSE#970]
I am using this command in LUA: 
`GCICAP_Red = AI_A2A_GCICAP:NewWithBorder("EWR Red","CAP Squadron Red","Border Red", "CAP Red Patrol", 2)`

When I run the mission to test it out it seems that red cap takes about 18 minutes to spawn the cap for patrol.

**Comment by grandpaSam** [comment]
Ok I found the command to change that time but when I set the time interval to 60 to 120 seconds the cap groups will sometimes spawn between 1 minute and two minutes but other times they wont spawn until 10 minutes into the mission.

**Comment by Delta-99** [comment]
Will need more info like an attached mission etc. There are tons of people using AI_A2A_GCICAP and don't think anything like this has been reported before.

**Comment by FlightControl-User** [comment]
@grandpaSam i have retested completely the A2A dispatcher. I will close this issue. If you still have an issue, please re-open and add the mission.
