### ISSUE TITLE
SET_UNIT:FilterCategories(Categories) does not appear to work

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#971]
when i try to use this fun ction to get a set of units of a type eg "plane"
it crashes out with an error

2018-08-06 22:00:30.121 INFO    SCRIPTING: Error in timer function: [string "D:\games\1_Develop_Moose.lua"]:13635: attempt to index a nil value
2018-08-06 22:00:30.121 INFO    SCRIPTING: stack traceback:
	[string "D:\games\1_Develop_Moose.lua"]:4974: in function <[string "D:\games\1_Develop_Moose.lua"]:4971>
	[string "D:\games\1_Develop_Moose.lua"]:13635: in function 'IsIncludeObject'
	[string "D:\games\1_Develop_Moose.lua"]:11638: in function 'FilterOnce'

**Comment by Delta-99** [comment]
@shadowze can you provide a .miz or simple script at least?

**Comment by shadowze** [comment]
local gnd_units = SET_UNIT:New():FilterCategories("ground"):FilterOnce()
env.info(" ground count units = " .. gnd_units:Count() )

stick that in any mission you have ground units and call it

**Comment by shadowze** [comment]
tested with ME units and this works fine ....

Start my spawning scripts in the mission and you get the error in first report

Can you look at this now Delta99 ?

**Comment by shadowze** [comment]
ok, managed to get a demo moose mission and MOD it so this happens

See attached mission, can someone who knows what thay are doing have a quick look at this please
[TAD-CGO-009 - Transport Test - Respawning Cargo_MOD.zip](https://github.com/FlightControl-Master/MOOSE/files/2280384/TAD-CGO-009.-.Transport.Test.-.Respawning.Cargo_MOD.zip)

**Comment by Delta-99** [comment]
Someone will take a look when they can. Thanks for the additional info.

**Comment by shadowze** [comment]
I assumed it would be you delta-99 since you replied ................................................

**Comment by shadowze** [comment]
closing out because some knob set to to Incomplete report but could not spend the 30 seconds of time it would take to run attached test mission
