### ISSUE TITLE
UNIT:UnHandleEvent(Event) gives a MOOSE error "attempt to call method 'RemoveForUnit' (a nil value)"

### ISSUE THREAD

**Issue by Goreuncle** [FlightControl-Master/MOOSE#973]
Last week, UNIT:UnHandleEvent(Event.Takeoff) started giving me trouble in a DCS mission I'm creating (MOOSE 2.4.1).
It fails to unsubscribe from the takeoff event and, on top of it, produces a MOOSE error, which stops the script on its tracks.  This also happens when trying to unsubscribe from other events, not just takeoff, btw.

Here's an example of the error from dcs.log:
```
2018-08-06 22:06:33.504 INFO    SCRIPTING: MOOSE error in MENU COMMAND function: [string "C:\Users\Xavi\AppData\Local\Temp\DCS.openbeta\/~mis00005A48"]:31278: attempt to call method 'RemoveForUnit' (a nil value)
2018-08-06 22:06:33.504 INFO    SCRIPTING: stack traceback:
        [string "C:\Users\Xavi\AppData\Local\Temp\DCS.openbeta\/~mis00005A48"]:7409: in function 'RemoveForUnit'
        [string "C:\Users\Xavi\AppData\Local\Temp\DCS.openbeta\/~mis00005A48"]:31278: in function 'UnHandleEvent'
        [string "C:\Users\Xavi\AppData\Local\Temp\DCS.openbeta\/~mis000018DB"]:175: in function <[string "C:\Users\Xavi\AppData\Local\Temp\DCS.openbeta\/~mis000018DB"]:142>
        (tail call): ?
        [C]: in function 'xpcall'
```

(In this case, UNIT:UnHandleEvent(EVENTS.Takeoff) was located inside a MENU_GROUP_COMMAND function)

I've created a test mission so other users can reproduce the issue:
https://drive.google.com/open?id=1KDb1SF-JASHH0foTa7kSax_kFN3QUPDr

Here's the lua script from the test mission:
https://drive.google.com/open?id=1VqAHfQZgB0WuJSY_Fq5GmdTlwW76bTGB

I've already tried moving the event unhandler around the script (inside functions and outside), same error.

**Comment by ArgelErx** [comment]
Can confirm this.
Fix: Remove `UNIT:UnHandleEvent( Event )`. Use `BASE:UnHandleEvent( Event )` instead.

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
