### ISSUE TITLE
Feature Request - CSAR Module - After completion of a task can the CSAR troop be deleted (after 25 seconds)

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#976]
To reduce load on the DCS server would it be possible to destroy the CSAR pilot after he has been returned to the zone to complete the task eg wait maybe 25 seconds after he has unboarded the heli then remove him with destroy

**Comment by FlightControl-User** [comment]
It can be done by the event handlers:

https://flightcontrol-master.github.io/MOOSE_DOCS_DEVELOP/Documentation/AI.AI_Cargo_Dispatcher.html

**Comment by FlightControl-User** [comment]
I will close this issue as the mission designer can tailor the logic in his script.

**Comment by shadowze** [comment]
section 5.2 of this document shows how to handle this stuff, Thanks @FlightControl-User 
https://flightcontrol-master.github.io/MOOSE_DOCS_DEVELOP/Documentation/Tasking.Task_Cargo_Dispatcher.html
