### ISSUE TITLE
Feature Request - SPAWN - would like ability to combine spawn with a rotate parameter

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#978]
currently
SPAWNSTATIC:Spawn(Heading, (, NewName)

Has the ability to set the spawn items heading

I would like the ability to do with with normal spawn when using units

eg i use
SPAWN:NewWithAlias( template, alias ):SpawnFromVec2( location )

would like to be able to use
SPAWN:NewWithAlias( template, alias ):SpawnFromVec2( location ):Heading( 90)

which would make the unit spawn at location and be facing east

many thanks

**Comment by Delta-99** [comment]
Need to keep in mind that if there is a group template with multiple units arranged in the ME in particular orientation then the rotation should be based on the entire group not an individual unit. So Probably a heading doesn't make sense but :Rotate(90) would take the current template config and rotate it 90 degrees.

This was something FC fixed in one of the spawn methods way back when. It used to take all the units in the template and just make them face the direction of the 1st unit.

For example, you have a group with 4 units setup in a template. 1st is pointing N, 2nd ins pointing E, 3rd is pointing S, 4th is pointing W. When you apply the :Rotate(90), each would rotate 90 degrees.

**Comment by shadowze** [comment]
good point, a rotate command would make more sense

**Comment by Mechanist11** [comment]
+1 to this one, I guess there is no difference in manipluation rotation for ground and air units...

**Comment by shadowze** [comment]
Changed title to be more descrptive, ground units would be too difficult to set a heading on easily
ground units in set position would be a massive ballache to calculate how to change heading

single units would be easy

**Comment by Mechanist11** [comment]
It is not difficult to rotating the whole group in according to their current placement. You get the current coordinate of the groups unit for 1 to n then you define the distance and the heading from the firs unit to each one. then you transform this with the given heading parameter * -1.

**Comment by shadowze** [comment]
you got workable lua . moose code for this ?
I would like to test it out

**Comment by Mechanist11** [comment]
I don't have this currently, I've experienced with zone translations to define spawnpoints, worked well. Uses same method. But to burr this code inside group level would require skill above my current knowledge.

**Comment by Delta-99** [comment]
It is in Moose already so it’s been done. Don’t know where but somewhere in the spawn class.

**Comment by shadowze** [comment]
> 
> 
> It is in Moose already so it’s been done. Don’t know where but somewhere in the spawn class. Used in a different situation.

You mean spawning not with static spawn has a rotate method ? getting confused here

**Comment by Delta-99** [comment]
The transformation has been written as part of another Moose spawn function to keep units as they were defined in ME template. It’s pretty straight forward. Can easily be used to create this rotate method.

**Comment by Delta-99** [comment]
If only I had the time :smile:

**Comment by shadowze** [comment]
is there any chance now that we have the release out in the wild, this could please be looked at ?
I edited original post to refer to ROTATION

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
