### ISSUE TITLE
Merge Groups

### ISSUE THREAD

**Issue by funkyfranky** [FlightControl-Master/MOOSE#979]
Request to be able to merge different groups into one group. Especially for ground groups this can be handy. I am thinking about SAM groups for example since all units have to be in the same group to work.

With the new cargo weight limit, it might not be possible to transport a complete SAM site as a whole because the group might be to heavy to transport and groups are not split for transport.

In order to use the SAM site after transport, the individual groups need to be merged again into one single group.

**Comment by thebgpikester** [comment]
Even you are not immune from the mass closure!!!

;)
