### ISSUE TITLE
Scoring Telemetry to Server TCP or UPD

### ISSUE THREAD

**Issue by snakesn** [FlightControl-Master/MOOSE#980]
Hi Team,

I want to submit this request to finish and make this to work:
**Scoring:SetTelemetryServer( "xx.xx.xx.xx", 5010 )** 

Cheers,
Alex

**Comment by FlightControl-User** [comment]
What is the purpose and use case?

**Comment by snakesn** [comment]
my understanding of existence the Scoring class is to track players statistic. otherwise, I don't understand the existence of this class at all! having an ability to send data to a server will significantly simplify efforts to share a mission stats to our pilots.

please advise if this is fits to the moose philosophy and roadmap. if not I'm ok this that and will be looking for a different solution. 

thanks

**Comment by FlightControl-User** [comment]
Still confused. What do you expect me to do and by when.

**Comment by Delta-99** [comment]
I think @snakesn is looking for the scoring info to be written to a socket rather than to a file.

As a workaround @snakesn there are probably utilities out there that will monitor a file and any changes / updates to it can then be sent to a socket. This might not entirely be what you're looking for and perhaps you're looking for more / different info than what scoring is outputting to a file.

**Comment by FlightControl-User** [comment]
It's not that delta. After months of silence suddenly this request again. It is also the way how this request is written. There has always been some kind of strange competition. Maybe I am wrong and if I am so be it. I want now to finish of the cargo stuff. Scoring has been out of my sight for a while now. Wanna pick it back up but first cargo stable and working. Hence my question... when and what is expected from me,  and more,  what is the purpose. I have a feeling there could be more transparency. I've been looking into this stuff and somehow there was always a disconnect. I met Dexa here in Belgium. We had beers. But wanna understand context, urgency, ideas, etc. What's wrong with that?

**Comment by Delta-99** [comment]
I was just trying to clarify what I thought he wanted. I don't know the history. If I'm wrong no worries, he will clear it up hopefully.

Something like this would be very low priority I would think, if it is what I think it is.

Any new requests should be relatively low priority until 2.4 is officially out the door. Cargo being stable and working nicely is part of that I would think.

**Comment by snakesn** [comment]
@Delta-99 it is correct. all I want is to send the scoring class data to a socket. I'm ok about the file info and I'm not pushing for anything, I'm just trying to understand if it's possible and if this will be in a roadmap. I'm also not pushing for any deadlines, will be weird if I was. I'm confused about the "strange competition" comment, I'm not competing with anyone. I'm helping pilots to get together in a community which is more than 200 pilots now and has been promoting the Moose and not just for English speaking community. about a "silence" - don't understand either. I asked - the response was - wait, so i'm waiting, all the feature I need already in the framework. the only left stuff for me is the proper stats. using workarounds - all cool, but why (rhetorical question). I'm not sure what I did wrong

**Comment by FlightControl-User** [comment]
@snakesn ok! 

(I guess your feedback is correct, so now I will speak in full transparency with you guys). I am a father of 4 with a wife and kids, and sometimes I am just unable to do stuff on DCS for longer periods of time. And then I forgot about it ... I mean, about the scoring. To be honest, I had my 4th medical exam yesterday and I was in a **very** bad mood. I still need 2 to go (CT scan and radio pictures), but the echo and the blood are okay (i think). If I am without any positives now, I will be okay for the next year too I guess ... I don't feel sick anymore at all! So I guess it is going to be okay now. And I am back 100% at work, which is a great feeling too! But I have much less time than I used to have. However, now that I understand @snakesn I can only encourage your inititiative and thanks @Delta-99 for the moderation and the help! I needed this.

Let us get back to the subject ...

So, I **think** it works, I wanted to do a prototype test with Dexa, but somehow we never got to this. The port and the IP address are still hardcoded for now, but once the prototype works, we can move to next steps to make it parameteriseable. I am online most of the time during the day this week.
What I suggest we do is:

1. Tell me if the code I've written looks "all right" or not.
2. If it is all right, let us do a prototype test. I run a small mission to kill an object, and it "scores".
3. We'll test if the connection happens, and if you receive the string.
4. The communication is working in full UDP. Protocol is JSON.

Note: You'll have to configure your server! For that, let's get onto discord so we can chat ourselves through the process.

kind regards,
Sven

**Comment by snakesn** [comment]
Hi Sven, sounds good! glad to hear you are good and staying positive. this week will be a bit crazy for me, but i'll prepare a server and listener. i'll ping you on Discord to schedule a time to do configurations. 

Cheers,
Alex

**Comment by FlightControl-User** [comment]
ok. I am here ... Just remember, there is absolutely no deadline here or any stress ...

**Comment by snakesn** [comment]
agreed. when you have time maybe you will give me instructions of a server setup and JSON structure you will be sending. i'll do preparations and let you know IP and PORT

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
