### ISSUE TITLE
Feature request - Movable polygon zones (ZONE_POLYGON_UNIT)

### ISSUE THREAD

**Issue by Bankler** [FlightControl-Master/MOOSE#981]
I'd like a way to add a zone, with the shape defined as a polygon zone, that follows a unit around as the unit moves. Both the position and the heading should be taken (and updated) from the unit.

For instance, create a square polygon starboard of the carrier. As the carrier moves around, the zone should follow along and always be located just to the right of the carrier.

The best way to know each zone corner's relative position to the moving unit, is probably to read the initial state, making it mirror how the mission designer positioned stuff in the ME. _(Unlike how I believe the circular unit zones work today, where they will always be considered to be centered on the unit, regardless of where you actually put the zone in the ME)._

**Stretch goal:**
Provide optional functionality so that the polygon zone only follows the unit's position, ignoring heading.

_Additional info and brainstorming between FlightControl and Bankler available in #core-zones in Discord (search in channel for "ZONE_POLYGON_UNIT")._

**Comment by FlightControl-User** [comment]
Understood, but we'll postpone this to a later release if okay (let's say in a few weeks).

**Comment by Bankler** [comment]
Yes, no problem. I can sort of work around it by combining circular zones with additional conditions.

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
