### ISSUE TITLE
in A2G tasks, it is possible to put some designation functions?

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#984]
=ABU=ZEROvandaag om 02:36
It is also possible to put designate together with tasking. Use the same DETECTION object for both: Yes, I know, but my idea is to have designate integrated into A2G task in the same function, in th same menu. It will be great.
I mean, when you select a task, you will have a menu to choose smoke or laser your target all integrated
give me permissions to upload missions
my id: @janiolos

**Comment by janiolos** [comment]
Thank you FlightControl.
The ideia is put togheter in the same menus and in the same function the best of the both functions into one function.
My suggestion is put some designate function into A2G task dispatch function. When you choose the task, you can designate your target. It will allow the bombers to select targets and lase them or smoke them to find it easely.

**Comment by thebgpikester** [comment]
Thank you for making the effort to improve MOOSE. Our main developer Flight Control has not been contributing to MOOSE for over a year now and we are in sustained maintenance mode for emergency bug fixes for modules that he created. 
In order for us to be working on the most serious of issues we have to make some hard decisions on how to prioritise Github tickets. 
•	Currently, emergency issues created by DCS changes are our number one concern
•	Issues with wide and serious impact effect are our next concern but after so many years most have been found.
•	Any Modules created by FunkyFranky (Ops) will require less analysis and investigation and he will prioritise separately.
•	CORE MOOSE issues, will always be important but will often require long investigations on unfamiliar code.
•	Fixes on FlightControl’s FUNCTIONAL and TASK, DISPATCHER modules are incredibly complex to rework his original code.
•	Finally feature requests will in most cases have to be closed but will be assessed in case they are simple to do.
Github uses a system of labels and states for tickets that is not limited to closed/open and all your data uploaded, and details will remain viewable by everyone. Your work has not been lost or disregarded, but in this case, it’s fairer to set realistic expectations. As things change over time this will be reassessed.
