### ISSUE TITLE
BUG - TASK_CARGO_DISPATCHER:OnAfterCargoDeployed()  -> Cargo:Destroy() not working

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#987]
When using spawned static cargo and using it it tasks it all works great, but for some reason I cannot seem to get rid of Cargo when it is finished with ( I want to remove it from DCS and MOOSE)
eg

function TaskDispatcherCargo:OnAfterCargoDeployed( From, Event, To, Task, TaskPrefix, TaskUnit, Cargo, DeployZone )

Cargo:Destroy() -- this does not work
end -- EOF

If I use Cargo.CargoObject:Destroy(), it will remove the object from DCS (it dissapears - but I think it is still "alive" inside MOOSE

**Comment by shadowze** [comment]
what help do you need ?

**Comment by thebgpikester** [comment]
OK what do we do with this? We can't change cargo so can it be worked around outside of code or not?

**Comment by thebgpikester** [comment]
> If I use Cargo.CargoObject:Destroy(), it will remove the object from DCS (it dissapears - but I think it is still "alive" inside MOOSE

Impact? Will autoclose in 1 week

**Comment by shadowze** [comment]
cargo still exists in moose database, need to change Cargo:Destroy()  to directly call the destroy API function and then remove that cargo at same time from moose  database

**Comment by baluballa** [comment]
Maybe documented Cargo:Destroy(). Cargo:Destroy does not de-spawns the Positionable representing the Cargo. as far as I can see from Docs or Code.

**Comment by shadowze** [comment]
re-opening as the code section that has this error was not completed

**Comment by thebgpikester** [comment]
so let me get this straight.
CARGO:Destroy() works as it destroy() the physical object using the SSE API, but does not trigger the deletion of the object from the MOOSE database? Is this it?

**Comment by baluballa** [comment]
@shadowze Can you plz update status on this issue, and reply to @thebgpikester question. I am currently looking into this?

**Comment by shadowze** [comment]
been a while since I looked at this, but  think that @thebgpikester is correct object physically dissapears but is still on the database

**Comment by baluballa** [comment]
Ok 

> 
> 
> cargo still exists in moose database and in the sim engine , need to change Cargo:Destroy() to directly call the destroy API function (destroys the cargo properly) and then remove that cargo at same time from moose database

What flaws causes this, if I might ask? What should I look fro when debugging @shadowze ?

**Comment by shadowze** [comment]
Cargo:Destroy() (where Cargo is a cargo type dcs object)  called from  TaskDispatcherCargo:OnAfterCargoDeployed  function when a cargo has been deployed is where this was observed, franky had a look thru  MOOSE and noticed some code to do with class cargo and the destroy method were never finished ... I think

**Comment by baluballa** [comment]
Right makes sense.

**Comment by baluballa** [comment]
When destroying Cargos, the dispatcher reports this:
![image](https://user-images.githubusercontent.com/7481653/102102952-abfe8780-3e2c-11eb-99b3-0c428aa0f2ab.png)

Not ok, @shadowze?

**Comment by shadowze** [comment]
try to see if you can search the database for the "destroyed" objects
also try with a cargo crate type object

**Comment by baluballa** [comment]
Ok

**Comment by shadowze** [comment]
tihnk this is what were were looking at

  function CARGO_REPRESENTABLE:Destroy()
  
    -- Cargo objects are deleted from the _DATABASE and SET_CARGO objects.
    self:F( { CargoName = self:GetName() } )
    --_EVENTDISPATCHER:CreateEventDeleteCargo( self )
  
    return self
  end

this is probably where this is fucked, if you look at other destroy methods
eg
function STATIC:Destroy( GenerateEvent )
you see they do something that triggers a database removal, cargo aint got that

**Comment by baluballa** [comment]
Indeed, @shadowze nothing happens, when CARGO_REPRESENTABLE:Destroy() is called. Cargo crate remains in game and in the dispatchers tasks list.

**Comment by baluballa** [comment]
I see in function the CreateEvent call is commented.
```lua
 --- CARGO_REPRESENTABLE Destructor.
  -- @param #CARGO_REPRESENTABLE self
  -- @return #CARGO_REPRESENTABLE
  function CARGO_REPRESENTABLE:Destroy()
  
    -- Cargo objects are deleted from the _DATABASE and SET_CARGO objects.
    self:F( { CargoName = self:GetName() } )
    --_EVENTDISPATCHER:CreateEventDeleteCargo( self )
  
    return self
  end
```
Ill try un-comment and see whats happening.

**Comment by baluballa** [comment]
`function CARGO_REPRESENTABLE:Destroy()` is not completed. 

Commenting `_EVENTDISPATCHER:CreateEventDeleteCargo( self )` leads to nothing.

**Comment by shadowze** [comment]
yeah, looks like the code for this stuff is not yet completed

**Comment by FlightControl-User** [comment]
It was never completed because the dcs sim could not delete the crates. Bugs ... I simply gave up.


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by shadowze** [comment]
Yeah but DCS API does now delete the crates ...... its just the moose code not removing the cargo from the database is the issue .. I think

**Comment by baluballa** [comment]
> 
> It was never completed because the dcs sim could not delete the crates. Bugs ... I simply gave up. 

Hehe, right bug... _Still hope you are doing well!_

Anyway, Ill dig into the Moose's "destruction department" when on my way for _Christmas holiday_ to see if I understand the logic. It seems create events of some type. "death" I think While tracing I found this comment long comment in Moose.lua:

```      -- When cargo was deleted, it may probably be because of an S_EVENT_DEAD.
      -- However, in the loading logic, an S_EVENT_DEAD is also generated after a Destroy() call.
      -- And this is a problem because it will remove all entries from the SET_CARGOs.
      -- To prevent this from happening, the Cargo object has a flag NoDestroy.
      -- When true, the SET_CARGO won't Remove the Cargo object from the set.
      -- But we need to switch that flag off after the event handlers have been called.
```
 Seems to be in this long function `function EVENT:onEvent( Event )` just above 
```lua
    if Event.id == EVENTS.DeleteCargo then
        Event.Cargo.NoDestroy = nil
      end
```

**Comment by baluballa** [comment]
@shadowze is this still relevant?
