### ISSUE TITLE
Feature Request - Command Center ->The abililty to disable Auto assign TASK menus  DisableTaskAssignMenu()

### ISSUE THREAD

**Issue by shadowze** [FlightControl-Master/MOOSE#990]
I would like the abiltity to remove the following two menus from a command center
Assign Task on  ( this also has an off state)
Assign Task
See picture below
for example -> COMMAND_CENTER:DisableTaskAssignMenu()
this would disable those 2 menus from appearing in the menu for a command center called COMMAND_CENTER

Spoke to @FlightControl-User  about this, just creating this request to log it

![unknown](https://user-images.githubusercontent.com/30597073/45952088-c48ce800-bffd-11e8-88b3-2917ea101e10.png)

**Comment by FlightControl-User** [comment]
OK. so a solution has been implemented where the auto assign task menus are now under the command center group. The remaining assign task menu item is kept for the moment, not to impact too much on the release 2.4. But we'll keep this open for release 2.5.
