### ISSUE TITLE
TASKING: optimize tasking menu

### ISSUE THREAD

**Issue by FlightControl-User** [FlightControl-Master/MOOSE#994]
1. Add opt-in to disable. 
2. Make task assignment menu for COMMANDCENTER.

**Comment by FlightControl-User** [comment]
@shadowze I will fix this in a special way.
I will keep the Assign task to the player menu, but it will only be active for THAT PLAYER ONLY.
The auto task assignment menus, will be positioned at the menu structure of the command center group (which is in the battlefield). You can join the group to govern the command center settings...
A command center could be for example a ship, or even a plane, like an AWACS.

**Comment by shadowze** [comment]
iam confused? can i disable the tasking menu  for a command center and this menu will not be visible to anyone?

**Comment by FlightControl-User** [comment]
You won't see the menu




Get Outlook for Android







On Wed, Sep 26, 2018 at 10:12 PM +0200, "Shadowze" <notifications@github.com> wrote:












iam confused? can i disable the tasking menu  for a command center and this menu will not be visible to anyone?

**Comment by FlightControl-User** [comment]
Let me explain




On Wed, Sep 26, 2018 at 10:12 PM +0200, "Shadowze" <notifications@github.com> wrote:












iam confused? can i disable the tasking menu  for a command center and this menu will not be visible to anyone?

**Comment by FlightControl-User** [comment]
A command center is a group. It has a separate menu. So, the task auto assign is governed on the command center and is meant for game masters only. 




On Wed, Sep 26, 2018 at 10:34 PM +0200, "Sven Van de Velde" <sven.van.de.velde@telenet.be> wrote:










You won't see the menu




Get Outlook for Android







On Wed, Sep 26, 2018 at 10:12 PM +0200, "Shadowze" <notifications@github.com> wrote:












iam confused? can i disable the tasking menu  for a command center and this menu will not be visible to anyone?

**Comment by boagord** [comment]
Another Idea: could you add the possibilty to automaticly affect the task to a group, without any request of confirmation or accessing the F10 menue?

**Comment by FlightControl-User** [comment]
yes, that is also possible, that could also be an option. I'll think about that one.

**Comment by FlightControl-User** [comment]
But right now, you'll notice there is less menu ...

**Comment by FlightControl-User** [comment]
I'll close this one now, and we'll open a new one for the more advance topics. I want to stabilize now for the release.
