### ISSUE TITLE
Static object:  errors when using static set in TASK_A2G_BAI

### ISSUE THREAD

**Issue by falcon76** [FlightControl-Master/MOOSE#999]
I have attached the mission (still building it) and the lua scripts separately so you do not have to pull them out.

**Here is my code:**

 RUCombine = MISSION
        :New( CommandCenter, 
          "Tyrnyauz Combine Assault", 
          "Primary", 
          "Interdict into enemy held area and destroy all target at the Tyrnyauz town.\n "..
          "The target coordinates are(ALT: Bora FT.):\n   " ..
          "ALT: 0000 WP:0 Departing Airport\n   "..
          "ALT: 7010 WP:1 N 43.18.36 E 42.45.13 [IP]\n   "..
          "ALT: 4380 WP:2 N 43.23.44 E 42.55.24 [Target]\n   ".. 
          "These will need to go into your UFC/HSI waypoints\n"..
          "Rearm and refuel on the Tarawa TACAN: 65X or\n"..
          "Rearm and refuel on the Stennis TACAN: 55X or\ "..
          "Boom Refuel aircraft: Texaco on 252 AM, TACAN 51X.\n"..
          "Drone and Probe: Arco on 253.0 AM, TACAN 56X. (At the carriers)\n"..
          "Drone and Probe: Shell on 251.0 AM, TACAN 50X. (Along the ridge of the mountains)\n",
          coalition.side.BLUE )
        :AddScoring( Scoring )

  RUCombineStatic = STATIC:FindByName("Static RU Combine", false )
  RUCombineStatic:Destroy( true )     
  RUCombineStatic.threatlevel = 0

  RUCombineUnit = SET_STATIC:New()
  :FilterPrefixes("Static RU Combine")
  :FilterOnce()
  
  RUCombineTask = TASK_A2G_BAI:New( RUCombine, AttackGroups, "Destroy Tyrnyauz Combine", RUCombineUnit , "Bomb the Combine at Tyrnyauz. Primary: Combine Factory. Secondary: All enemy vehicles.")
   
 function RUCombineStatic:Destroy()
    RUCombineTask:Success()
    CommandCenter:MessageToCoalition("Russian Combine destroyed, good job.")
 end

**I get the following errors:**

2018-09-29 05:32:06.401 INFO    SCRIPTING: Error in FSM_PROCESS call handler:[string "Scripts/Moose/Actions/Act_Account.lua"]:194: attempt to call method 'GetUnitTypesText' (a nil value)
2018-09-29 05:32:06.401 INFO    SCRIPTING: stack traceback:
	[string "Scripts/Moose/Core/Fsm.lua"]:972: in function 'GetUnitTypesText'
	[string "Scripts/Moose/Actions/Act_Account.lua"]:194: in function <[string "Scripts/Moose/Actions/Act_Account.lua"]:192>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "Scripts/Moose/Core/Fsm.lua"]:985: in function '_call_handler'
	[string "Scripts/Moose/Core/Fsm.lua"]:687: in function <[string "Scripts/Moose/Core/Fsm.lua"]:592>
	(tail call): ?
	[string "Scripts/Moose/Actions/Act_Account.lua"]:117: in function <[string "Scripts/Moose/Actions/Act_Account.lua"]:114>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "Scripts/Moose/Core/Fsm.lua"]:985: in function '_call_handler'
	[string "Scripts/Moose/Core/Fsm.lua"]:687: in function <[string "Scripts/Moose/Core/Fsm.lua"]:592>
	(tail call): ?
	[string "Scripts/Moose/Core/Fsm.lua"]:665: in function <[string "Scripts/Moose/Core/Fsm.lua"]:592>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "Scripts/Moose/Core/ScheduleDispatcher.lua"]:131: in function <[string "Scripts/Moose/Core/ScheduleDispatcher.lua"]:90>
2018-09-29 05:32:06.402 INFO    SCRIPTING:    210(   150)/E:                BASE00000.GetPointVec3({[1]=Cannot GetPointVec3,[Positionable]={[threatlevel]=0,[StaticName]=Static RU Combine,[ClassName]=STATIC,},[Alive]=false,})
2018-09-29 05:32:06.402 INFO    SCRIPTING: Error in FSM_PROCESS call handler:[string "Scripts/Moose/Tasking/Task_A2G.lua"]:151: attempt to index local 'Coordinate' (a nil value)
2018-09-29 05:32:06.402 INFO    SCRIPTING: stack traceback:
	[string "Scripts/Moose/Core/Fsm.lua"]:972: in function <[string "Scripts/Moose/Core/Fsm.lua"]:968>
	[string "Scripts/Moose/Tasking/Task_A2G.lua"]:151: in function <[string "Scripts/Moose/Tasking/Task_A2G.lua"]:141>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "Scripts/Moose/Core/Fsm.lua"]:985: in function '_call_handler'
	[string "Scripts/Moose/Core/Fsm.lua"]:682: in function <[string "Scripts/Moose/Core/Fsm.lua"]:592>
	(tail call): ?
	[C]: in function 'xpcall'
	[string "Scripts/Moose/Core/ScheduleDispatcher.lua"]:131: in function <[string "Scripts/Moose/Core/ScheduleDispatcher.lua"]:90>

[CVW-5_Caucus_Training_US.zip](https://github.com/FlightControl-Master/MOOSE/files/2430323/CVW-5_Caucus_Training_US.zip)

**Comment by baluballa** [comment]
Overdue.
